import LastLib.Book05LocalClassFieldTheory.Chapter06.Section03TorsionPointsAndEisensteinPolynomials

namespace LastLib.Book05LocalClassFieldTheory.Chapter06

noncomputable section

open scoped BigOperators

/-!
### 6.4. The Galois action on torsion
-/

/-- Every primitive root is carried to another primitive root by the formal
scalar action, so the action lies in the field generated by the chosen point. -/
theorem chapter06_primitive_action_mem_torsion_field
    {K : Type*} [Field K] [UniformSpace (AlgebraicClosure K)]
    (D : Chapter06LocalFieldData K)
    [UniformSpace (Chapter06ValuationRing D)]
    (n : ℕ) (hn : 0 < n)
    (f : Chapter06UnivariateSeries (Chapter06ValuationRing D))
    (hf : chapter06LubinTateCondition D f)
    (M : Chapter06FormalModuleData D f)
    (A : Chapter06TorsionAction D f n hn M)
    (ω : Chapter06PrimitiveTorsionPoint D n hn)
    (a : (Chapter06TorsionResidueRing D n)ˣ) :
    (A.quotientAction (a : Chapter06TorsionResidueRing D n)
      (chapter06PrimitivePointAsTorsion D n hn ω)).1 ∈
      chapter06TorsionField D n ω.point := by
  sorry

/-- The automorphism sending `ωₙ` to `[a]ₙ(ωₙ)`. -/
theorem chapter06_torsion_action_gives_automorphism
    {K : Type*} [Field K] [UniformSpace (AlgebraicClosure K)]
    (D : Chapter06LocalFieldData K)
    [UniformSpace (Chapter06ValuationRing D)]
    (n : ℕ) (hn : 0 < n)
    (f : Chapter06UnivariateSeries (Chapter06ValuationRing D))
    (hf : chapter06LubinTateCondition D f)
    (M : Chapter06FormalModuleData D f)
    (A : Chapter06TorsionAction D f n hn M)
    (ω : Chapter06PrimitiveTorsionPoint D n hn)
    [FiniteDimensional K (chapter06TorsionField D n ω.point)]
    [IsGalois K (chapter06TorsionField D n ω.point)]
    (a : (Chapter06TorsionResidueRing D n)ˣ) :
    ∃ σ : Gal(chapter06TorsionField D n ω.point / K),
      ((σ (chapter06PrimitivePointInField D n hn ω) :
        chapter06TorsionField D n ω.point) : AlgebraicClosure K) =
        A.quotientAction (a : Chapter06TorsionResidueRing D n)
          (chapter06PrimitivePointAsTorsion D n hn ω) := by
  let L := chapter06TorsionField D n ω.point
  let P := chapter06PrimitiveTorsionPolynomialOverK D n
  have hmonicQ := chapter06_Qn_monic D n hn
  have hq : 1 < chapter06ResidueCardinality D := by
    let _ := D.residue_finite
    let _ : Fintype (Chapter06ResidueField D) := Fintype.ofFinite _
    simpa [chapter06ResidueCardinality, Nat.card_eq_fintype_card] using
      (Fintype.one_lt_card : 1 < Fintype.card (Chapter06ResidueField D))
  have hposQ : 0 < (chapter06Qn D n).natDegree := by
    rw [chapter06_Qn_degree D n hn]
    exact Nat.mul_pos (pow_pos (chapter06_residue_cardinality_pos D) _)
      (by omega)
  have hdegP : P.natDegree = (chapter06Qn D n).natDegree := by
    unfold P chapter06PrimitiveTorsionPolynomialOverK
    apply Polynomial.natDegree_map_eq_of_isUnit_leadingCoeff
    rw [hmonicQ.leadingCoeff]
    exact isUnit_one
  have hpos : 0 < P.natDegree := by
    rw [hdegP]
    exact hposQ
  have hirrA : Irreducible (chapter06Qn D n) := by
    apply (chapter06_Qn_is_eisenstein D n hn).irreducible
      (IsLocalRing.maximalIdeal.isMaximal _).isPrime
      hmonicQ.isPrimitive hposQ
  have hirrK : Irreducible P := by
    exact (hmonicQ.irreducible_iff_irreducible_map_fraction_map).mp hirrA
  have hroot : Polynomial.aeval ω.point P = 0 :=
    chapter06_primitive_torsion_point_is_primitive_division_root D n hn ω
  have hmin : P = minpoly K ω.point := by
    exact minpoly.eq_of_irreducible_of_monic hirrK hroot
      (hmonicQ.map (algebraMap (Chapter06ValuationRing D) K))
  have hmem :
      (A.quotientAction (a : Chapter06TorsionResidueRing D n)
        (chapter06PrimitivePointAsTorsion D n hn ω)).1 ∈ L := by
    exact chapter06_primitive_action_mem_torsion_field D n hn f hf M A ω a
  let y : L := ⟨_, hmem⟩
  obtain ⟨r, hr⟩ := Ideal.Quotient.mk_surjective (a : Chapter06TorsionResidueRing D n)
  let I : Ideal (Chapter06ValuationRing D) :=
    Ideal.span ({D.uniformizer} : Set (Chapter06ValuationRing D))
  have hI : I = IsLocalRing.maximalIdeal (Chapter06ValuationRing D) := by
    change Ideal.span ({D.uniformizer} : Set (Chapter06ValuationRing D)) =
      LastLib.Book02FiniteExtensionsOfLocalFields.Chapter01.chapter01MaximalIdeal
        D.valuation.toValuation
    exact D.uniformizer_spec.2.symm
  let _ : I.IsMaximal := hI ▸ inferInstance
  have hunit_mk (r : Chapter06ValuationRing D) :
      IsUnit (Ideal.Quotient.mk
        ((Ideal.span ({D.uniformizer} : Set (Chapter06ValuationRing D))) ^ n) r) ↔
      IsUnit r := by
    have hunitI : IsUnit (Ideal.Quotient.mk (I ^ n) r) ↔ IsUnit r := by
      rw [Ideal.Quotient.isUnit_mk_pow_iff_notMem I (Nat.ne_of_gt hn)]
      rw [hI, IsLocalRing.mem_maximalIdeal, mem_nonunits_iff]
      simp
    simpa [I] using hunitI
  have hrunit : IsUnit r := (hunit_mk r).mp (by
    rw [hr]
    exact Units.isUnit a)
  have hrprimitive := (A.primitive_iff_unit r ω).mp hrunit
  have hyroot : Polynomial.aeval (y : AlgebraicClosure K) P = 0 := by
    change Polynomial.aeval
      (A.quotientAction (a : Chapter06TorsionResidueRing D n)
        (chapter06PrimitivePointAsTorsion D n hn ω)).1 P = 0
    rw [← hr, A.quotientAction_spec r
      (chapter06PrimitivePointAsTorsion D n hn ω)]
    exact hrprimitive
  have hminL :
      minpoly K (chapter06PrimitivePointInField D n hn ω) = minpoly K ω.point := by
    rw [← minpoly.algebraMap_eq
      (algebraMap L (AlgebraicClosure K)).injective]
    rfl
  have hymin : Polynomial.aeval y (minpoly K (chapter06PrimitivePointInField D n hn ω)) = 0 := by
    rw [hminL, ← hmin]
    apply L.val.injective
    change L.val (Polynomial.aeval y P) = 0
    rw [← Polynomial.aeval_algHom_apply L.val]
    exact hyroot
  obtain ⟨φ, hφ⟩ :=
    IntermediateField.exists_algHom_of_splits_of_aeval
      (fun x : L =>
        ⟨Algebra.IsIntegral.isIntegral x, IsGalois.splits K x⟩) hymin
  let σ : L ≃ₐ[K] L :=
    AlgEquiv.ofBijective φ (φ.normal_bijective K L L)
  refine ⟨σ, ?_⟩
  have hφ' := congrArg (fun z : L => (z : AlgebraicClosure K)) hφ
  simpa [σ, y, L, chapter06PrimitivePointInField] using hφ'

theorem chapter06_torsion_action_gives_unique_automorphism
    {K : Type*} [Field K] [UniformSpace (AlgebraicClosure K)]
    (D : Chapter06LocalFieldData K)
    [UniformSpace (Chapter06ValuationRing D)]
    (n : ℕ) (hn : 0 < n)
    (f : Chapter06UnivariateSeries (Chapter06ValuationRing D))
    (hf : chapter06LubinTateCondition D f)
    (M : Chapter06FormalModuleData D f)
    (A : Chapter06TorsionAction D f n hn M)
    (ω : Chapter06PrimitiveTorsionPoint D n hn)
    [FiniteDimensional K (chapter06TorsionField D n ω.point)]
    [IsGalois K (chapter06TorsionField D n ω.point)]
    (a : (Chapter06TorsionResidueRing D n)ˣ) :
    ∃! σ : Gal(chapter06TorsionField D n ω.point / K),
      ((σ (chapter06PrimitivePointInField D n hn ω) :
        chapter06TorsionField D n ω.point) : AlgebraicClosure K) =
        A.quotientAction (a : Chapter06TorsionResidueRing D n)
          (chapter06PrimitivePointAsTorsion D n hn ω) := by
  obtain ⟨σ, hσ⟩ :=
    chapter06_torsion_action_gives_automorphism D n hn f hf M A ω a
  refine ⟨σ, hσ, ?_⟩
  intro τ hτ
  have hhom : τ.toAlgHom = σ.toAlgHom := by
    refine IntermediateField.algHom_ext_of_eq_adjoin
      (F := K) (E := AlgebraicClosure K)
      (S := chapter06TorsionField D n ω.point)
      (s := ({ω.point} : Set (AlgebraicClosure K))) ?_ ?_
    · change IntermediateField.adjoin K ({ω.point} : Set (AlgebraicClosure K)) =
        IntermediateField.adjoin K ({ω.point} : Set (AlgebraicClosure K))
      rfl
    · intro x hx
      subst x
      apply Subtype.ext
      simpa [chapter06PrimitivePointInField] using hτ.trans hσ.symm
  apply AlgEquiv.ext
  intro x
  exact DFunLike.congr_fun hhom x

/-- A choice of the automorphism `σₐ`. -/
noncomputable def chapter06SigmaA
    {K : Type*} [Field K] [UniformSpace (AlgebraicClosure K)]
    (D : Chapter06LocalFieldData K)
    [UniformSpace (Chapter06ValuationRing D)]
    (n : ℕ) (hn : 0 < n)
    (f : Chapter06UnivariateSeries (Chapter06ValuationRing D))
    (hf : chapter06LubinTateCondition D f)
    (M : Chapter06FormalModuleData D f)
    (A : Chapter06TorsionAction D f n hn M)
    (ω : Chapter06PrimitiveTorsionPoint D n hn)
    [FiniteDimensional K (chapter06TorsionField D n ω.point)]
    [IsGalois K (chapter06TorsionField D n ω.point)]
    (a : (Chapter06TorsionResidueRing D n)ˣ) :
    Gal(chapter06TorsionField D n ω.point / K) :=
  Classical.choose
    (chapter06_torsion_action_gives_automorphism D n hn f hf M A ω a)

theorem chapter06SigmaA_spec
    {K : Type*} [Field K] [UniformSpace (AlgebraicClosure K)]
    (D : Chapter06LocalFieldData K)
    [UniformSpace (Chapter06ValuationRing D)]
    (n : ℕ) (hn : 0 < n)
    (f : Chapter06UnivariateSeries (Chapter06ValuationRing D))
    (hf : chapter06LubinTateCondition D f)
    (M : Chapter06FormalModuleData D f)
    (A : Chapter06TorsionAction D f n hn M)
    (ω : Chapter06PrimitiveTorsionPoint D n hn)
    [FiniteDimensional K (chapter06TorsionField D n ω.point)]
    [IsGalois K (chapter06TorsionField D n ω.point)]
    (a : (Chapter06TorsionResidueRing D n)ˣ) :
    ((chapter06SigmaA D n hn f hf M A ω a)
      (chapter06PrimitivePointInField D n hn ω) :
      chapter06TorsionField D n ω.point) =
      ⟨(A.quotientAction (a : Chapter06TorsionResidueRing D n)
          (chapter06PrimitivePointAsTorsion D n hn ω)).1,
        chapter06_primitive_action_mem_torsion_field D n hn f hf M A ω a⟩ := by
  have hspec :=
    Classical.choose_spec
      (chapter06_torsion_action_gives_automorphism D n hn f hf M A ω a)
  apply Subtype.ext
  exact hspec

/-- The scalar relations give the group law on the torsion automorphisms. -/
theorem chapter06SigmaA_mul
    {K : Type*} [Field K] [UniformSpace (AlgebraicClosure K)]
    (D : Chapter06LocalFieldData K)
    [UniformSpace (Chapter06ValuationRing D)]
    (n : ℕ) (hn : 0 < n)
    (f : Chapter06UnivariateSeries (Chapter06ValuationRing D))
    (hf : chapter06LubinTateCondition D f)
    (M : Chapter06FormalModuleData D f)
    (A : Chapter06TorsionAction D f n hn M)
    (ω : Chapter06PrimitiveTorsionPoint D n hn)
    [FiniteDimensional K (chapter06TorsionField D n ω.point)]
    [IsGalois K (chapter06TorsionField D n ω.point)]
    (a b : (Chapter06TorsionResidueRing D n)ˣ) :
    chapter06SigmaA D n hn f hf M A ω a *
        chapter06SigmaA D n hn f hf M A ω b =
      chapter06SigmaA D n hn f hf M A ω (a * b) := by
  sorry

theorem chapter06SigmaA_injective
    {K : Type*} [Field K] [UniformSpace (AlgebraicClosure K)]
    (D : Chapter06LocalFieldData K)
    [UniformSpace (Chapter06ValuationRing D)]
    (n : ℕ) (hn : 0 < n)
    (f : Chapter06UnivariateSeries (Chapter06ValuationRing D))
    (hf : chapter06LubinTateCondition D f)
    (M : Chapter06FormalModuleData D f)
    (A : Chapter06TorsionAction D f n hn M)
    (ω : Chapter06PrimitiveTorsionPoint D n hn)
    [FiniteDimensional K (chapter06TorsionField D n ω.point)]
    [IsGalois K (chapter06TorsionField D n ω.point)] :
    Function.Injective (chapter06SigmaA D n hn f hf M A ω) := by
  sorry

theorem chapter06SigmaA_exhausts_galois_group
    {K : Type*} [Field K] [UniformSpace (AlgebraicClosure K)]
    (D : Chapter06LocalFieldData K)
    [UniformSpace (Chapter06ValuationRing D)]
    (n : ℕ) (hn : 0 < n)
    (f : Chapter06UnivariateSeries (Chapter06ValuationRing D))
    (hf : chapter06LubinTateCondition D f)
    (M : Chapter06FormalModuleData D f)
    (A : Chapter06TorsionAction D f n hn M)
    (ω : Chapter06PrimitiveTorsionPoint D n hn)
    [FiniteDimensional K (chapter06TorsionField D n ω.point)]
    [IsGalois K (chapter06TorsionField D n ω.point)] :
    Function.Surjective (chapter06SigmaA D n hn f hf M A ω) := by
  sorry

theorem chapter06_torsion_galois_group_card
    {K : Type*} [Field K] (D : Chapter06LocalFieldData K)
    (n : ℕ) (hn : 0 < n)
    (ω : Chapter06PrimitiveTorsionPoint D n hn)
    [FiniteDimensional K (chapter06TorsionField D n ω.point)]
    [IsGalois K (chapter06TorsionField D n ω.point)]
    [Fintype (Gal(chapter06TorsionField D n ω.point / K))] :
    Nat.card (Gal(chapter06TorsionField D n ω.point / K)) =
      chapter06ResidueCardinality D ^ (n - 1) *
        (chapter06ResidueCardinality D - 1) := by
  sorry

/-- The torsion labeling equivalence. Its construction depends on the
chosen primitive point, even though its isomorphism type does not. -/
theorem chapter06_torsion_galois_equiv_exists
    {K : Type*} [Field K] [UniformSpace (AlgebraicClosure K)]
    (D : Chapter06LocalFieldData K)
    [UniformSpace (Chapter06ValuationRing D)]
    (n : ℕ) (hn : 0 < n)
    (f : Chapter06UnivariateSeries (Chapter06ValuationRing D))
    (hf : chapter06LubinTateCondition D f)
    (M : Chapter06FormalModuleData D f)
    (A : Chapter06TorsionAction D f n hn M)
    (ω : Chapter06PrimitiveTorsionPoint D n hn)
    [FiniteDimensional K (chapter06TorsionField D n ω.point)]
    [IsGalois K (chapter06TorsionField D n ω.point)] :
    Nonempty
      (Gal(chapter06TorsionField D n ω.point / K) ≃*
        (Chapter06TorsionResidueRing D n)ˣ) := by
  sorry

noncomputable def chapter06TorsionGaloisEquiv
    {K : Type*} [Field K] [UniformSpace (AlgebraicClosure K)]
    (D : Chapter06LocalFieldData K)
    [UniformSpace (Chapter06ValuationRing D)]
    (n : ℕ) (hn : 0 < n)
    (f : Chapter06UnivariateSeries (Chapter06ValuationRing D))
    (hf : chapter06LubinTateCondition D f)
    (M : Chapter06FormalModuleData D f)
    (A : Chapter06TorsionAction D f n hn M)
    (ω : Chapter06PrimitiveTorsionPoint D n hn)
    [FiniteDimensional K (chapter06TorsionField D n ω.point)]
    [IsGalois K (chapter06TorsionField D n ω.point)] :
    Gal(chapter06TorsionField D n ω.point / K) ≃*
      (Chapter06TorsionResidueRing D n)ˣ :=
  Classical.choice
    (chapter06_torsion_galois_equiv_exists D n hn f hf M A ω)

theorem chapter06_torsion_galois_equiv_apply_sigma
    {K : Type*} [Field K] [UniformSpace (AlgebraicClosure K)]
    (D : Chapter06LocalFieldData K)
    [UniformSpace (Chapter06ValuationRing D)]
    (n : ℕ) (hn : 0 < n)
    (f : Chapter06UnivariateSeries (Chapter06ValuationRing D))
    (hf : chapter06LubinTateCondition D f)
    (M : Chapter06FormalModuleData D f)
    (A : Chapter06TorsionAction D f n hn M)
    (ω : Chapter06PrimitiveTorsionPoint D n hn)
    [FiniteDimensional K (chapter06TorsionField D n ω.point)]
    [IsGalois K (chapter06TorsionField D n ω.point)]
    (a : (Chapter06TorsionResidueRing D n)ˣ) :
    chapter06TorsionGaloisEquiv D n hn f hf M A ω
        (chapter06SigmaA D n hn f hf M A ω a) = a := by
  sorry

theorem chapter06_torsion_galois_group_commutative
    {K : Type*} [Field K] [UniformSpace (AlgebraicClosure K)]
    (D : Chapter06LocalFieldData K)
    [UniformSpace (Chapter06ValuationRing D)]
    (n : ℕ) (hn : 0 < n)
    (f : Chapter06UnivariateSeries (Chapter06ValuationRing D))
    (hf : chapter06LubinTateCondition D f)
    (M : Chapter06FormalModuleData D f)
    (A : Chapter06TorsionAction D f n hn M)
    (ω : Chapter06PrimitiveTorsionPoint D n hn)
    [FiniteDimensional K (chapter06TorsionField D n ω.point)]
    [IsGalois K (chapter06TorsionField D n ω.point)] :
    ∀ σ τ : Gal(chapter06TorsionField D n ω.point / K),
      σ * τ = τ * σ := by
  sorry

theorem chapter06_theorem_6_3
    {K : Type*} [Field K] [UniformSpace (AlgebraicClosure K)]
    (D : Chapter06LocalFieldData K)
    [UniformSpace (Chapter06ValuationRing D)]
    (n : ℕ) (hn : 0 < n)
    (f : Chapter06UnivariateSeries (Chapter06ValuationRing D))
    (hf : chapter06LubinTateCondition D f)
    (M : Chapter06FormalModuleData D f)
    (A : Chapter06TorsionAction D f n hn M)
    (ω : Chapter06PrimitiveTorsionPoint D n hn)
    [FiniteDimensional K (chapter06TorsionField D n ω.point)]
    [IsGalois K (chapter06TorsionField D n ω.point)] :
    ∃ V : Chapter06ValuedFiniteExtension D
        (chapter06TorsionField D n ω.point),
      Module.finrank K (chapter06TorsionField D n ω.point) =
          chapter06ResidueCardinality D ^ (n - 1) *
            (chapter06ResidueCardinality D - 1) ∧
        chapter06TotallyRamifiedValuedExtension D V ∧
        V.valuation (chapter06PrimitivePointInField D n hn ω) = 1 ∧
        (∀ σ τ : Gal(chapter06TorsionField D n ω.point / K),
          σ * τ = τ * σ) ∧
        Nonempty
          (Gal(chapter06TorsionField D n ω.point / K) ≃*
            (Chapter06TorsionResidueRing D n)ˣ) := by
  sorry

/-- Multiplication by `π` on the explicit torsion sets.  The proof that the
map lands at the preceding level is the formal-module torsion calculation. -/
noncomputable def chapter06TorsionPiReduction
    {K : Type*} [Field K] [UniformSpace (AlgebraicClosure K)]
    (D : Chapter06LocalFieldData K)
    [UniformSpace (Chapter06ValuationRing D)]
    (f : Chapter06UnivariateSeries (Chapter06ValuationRing D))
    (hf : chapter06LubinTateCondition D f)
    (M : Chapter06FormalModuleData D f)
    (hExplicit : f = chapter06ExplicitLubinTateSeries D)
    (n : Chapter06PositiveNat) :
    {x : AlgebraicClosure K // x ∈ chapter06TorsionSet D (n.1 + 1)} →
      {x : AlgebraicClosure K // x ∈ chapter06TorsionSet D n.1} :=
  fun x =>
    ⟨chapter06FormalModuleScalarEvaluation M D.uniformizer x.1, by
      sorry⟩

/-- Compatible choices of primitive points form a nested torsion tower. -/
structure Chapter06CompatibleTorsionTower
    {K : Type*} [Field K] [UniformSpace (AlgebraicClosure K)]
    (D : Chapter06LocalFieldData K)
    [UniformSpace (Chapter06ValuationRing D)]
    (f : Chapter06UnivariateSeries (Chapter06ValuationRing D))
    (hf : chapter06LubinTateCondition D f)
    (M : Chapter06FormalModuleData D f) where
  explicit_series : f = chapter06ExplicitLubinTateSeries D
  point : ∀ n : Chapter06PositiveNat,
    Chapter06PrimitiveTorsionPoint D n.1 n.2
  pi_reduction : ∀ n : Chapter06PositiveNat,
    {x : AlgebraicClosure K // x ∈ chapter06TorsionSet D (n.1 + 1)} →
      {x : AlgebraicClosure K // x ∈ chapter06TorsionSet D n.1}
  pi_reduction_is_formal : ∀ n x,
    pi_reduction n x =
      chapter06TorsionPiReduction D f hf M explicit_series n x
  point_compatibility : ∀ n,
    pi_reduction n ⟨(point ⟨n.1 + 1, Nat.succ_pos n.1⟩).point,
      (point ⟨n.1 + 1, Nat.succ_pos n.1⟩).torsion⟩ =
      ⟨(point n).point, (point n).torsion⟩
  point_compatibility_is_formal_pi : ∀ n,
    (pi_reduction n ⟨(point ⟨n.1 + 1, Nat.succ_pos n.1⟩).point,
      (point ⟨n.1 + 1, Nat.succ_pos n.1⟩).torsion⟩).1 =
      chapter06FormalModuleScalarEvaluation M D.uniformizer
        (point ⟨n.1 + 1, Nat.succ_pos n.1⟩).point
  field_inclusion : ∀ n,
    chapter06TorsionField D n.1 (point n).point ≤
      chapter06TorsionField D (n.1 + 1)
        (point ⟨n.1 + 1, Nat.succ_pos n.1⟩).point

theorem chapter06_compatible_torsion_tower_exists
    {K : Type*} [Field K] [UniformSpace (AlgebraicClosure K)]
    (D : Chapter06LocalFieldData K)
    [UniformSpace (Chapter06ValuationRing D)]
    (f : Chapter06UnivariateSeries (Chapter06ValuationRing D))
    (hf : chapter06LubinTateCondition D f)
    (M : Chapter06FormalModuleData D f)
    (hExplicit : f = chapter06ExplicitLubinTateSeries D) :
    Nonempty (Chapter06CompatibleTorsionTower D f hf M) := by
  sorry

theorem chapter06_torsion_fields_nested
    {K : Type*} [Field K] [UniformSpace (AlgebraicClosure K)]
    (D : Chapter06LocalFieldData K)
    [UniformSpace (Chapter06ValuationRing D)]
    (f : Chapter06UnivariateSeries (Chapter06ValuationRing D))
    (hf : chapter06LubinTateCondition D f)
    (M : Chapter06FormalModuleData D f)
    (T : Chapter06CompatibleTorsionTower D f hf M)
    (n : Chapter06PositiveNat) :
    chapter06TorsionField D n.1 (T.point n).point ≤
      chapter06TorsionField D (n.1 + 1)
        (T.point ⟨n.1 + 1, Nat.succ_pos n.1⟩).point :=
  T.field_inclusion n

noncomputable def chapter06TowerField
    {K : Type*} [Field K] [UniformSpace (AlgebraicClosure K)]
    (D : Chapter06LocalFieldData K)
    [UniformSpace (Chapter06ValuationRing D)]
    {f : Chapter06UnivariateSeries (Chapter06ValuationRing D)}
    {hf : chapter06LubinTateCondition D f}
    {M : Chapter06FormalModuleData D f}
    (T : Chapter06CompatibleTorsionTower D f hf M)
    (n : Chapter06PositiveNat) : IntermediateField K (AlgebraicClosure K) :=
  chapter06TorsionField D n.1 (T.point n).point

/- The restriction diagram makes the phrase “reduction modulo `πⁿ`” a
   first-class interface.  The reduction map is the canonical quotient-ring
   map from the preceding section, while the compatibility theorem is the
   part used by the chapter. -/
structure Chapter06TorsionTowerGaloisCompatibility
    {K : Type*} [Field K] [UniformSpace (AlgebraicClosure K)]
    (D : Chapter06LocalFieldData K)
    [UniformSpace (Chapter06ValuationRing D)]
    {f : Chapter06UnivariateSeries (Chapter06ValuationRing D)}
    {hf : chapter06LubinTateCondition D f}
    {M : Chapter06FormalModuleData D f}
    (T : Chapter06CompatibleTorsionTower D f hf M) where
  restriction : ∀ n : Chapter06PositiveNat,
    Gal(chapter06TowerField D T ⟨n.1 + 1, Nat.succ_pos n.1⟩ / K) →*
      Gal(chapter06TowerField D T n / K)
  restriction_is_restriction : ∀ n σ x,
    ((restriction n σ) x : AlgebraicClosure K) =
      (σ (⟨x.1, T.field_inclusion n x.2⟩ :
        chapter06TowerField D T ⟨n.1 + 1, Nat.succ_pos n.1⟩) : AlgebraicClosure K)
  label : ∀ n : Chapter06PositiveNat,
    Gal(chapter06TowerField D T n / K) ≃*
      (Chapter06TorsionResidueRing D n.1)ˣ
  reduction_spec : ∀ n σ,
    label n (restriction n σ) =
      chapter06TorsionResidueUnitTransition D n.1
        (label ⟨n.1 + 1, Nat.succ_pos n.1⟩ σ)

theorem chapter06_torsion_tower_galois_compatibility_exists
    {K : Type*} [Field K] [UniformSpace (AlgebraicClosure K)]
    (D : Chapter06LocalFieldData K)
    [UniformSpace (Chapter06ValuationRing D)]
    {f : Chapter06UnivariateSeries (Chapter06ValuationRing D)}
    {hf : chapter06LubinTateCondition D f}
    {M : Chapter06FormalModuleData D f}
    (T : Chapter06CompatibleTorsionTower D f hf M) :
    Nonempty (Chapter06TorsionTowerGaloisCompatibility D T) := by
  sorry

theorem chapter06_torsion_tower_restriction_is_reduction
    {K : Type*} [Field K] [UniformSpace (AlgebraicClosure K)]
    (D : Chapter06LocalFieldData K)
    [UniformSpace (Chapter06ValuationRing D)]
    {f : Chapter06UnivariateSeries (Chapter06ValuationRing D)}
    {hf : chapter06LubinTateCondition D f}
    {M : Chapter06FormalModuleData D f}
    (T : Chapter06CompatibleTorsionTower D f hf M)
    (R : Chapter06TorsionTowerGaloisCompatibility D T)
    (n : Chapter06PositiveNat)
    (σ : Gal(chapter06TowerField D T ⟨n.1 + 1, Nat.succ_pos n.1⟩ / K)) :
    R.label n (R.restriction n σ) =
      chapter06TorsionResidueUnitTransition D n.1
        (R.label ⟨n.1 + 1, Nat.succ_pos n.1⟩ σ) := by
  exact R.reduction_spec n σ

end

end LastLib.Book05LocalClassFieldTheory.Chapter06
