import LastLib.Book10FaithfullyFlatDescentInAlgebraicGeometry.Chapter05.Dependencies
import LastLib.Book10FaithfullyFlatDescentInAlgebraicGeometry.Chapter05.Section01InvariantModule
import LastLib.Book10FaithfullyFlatDescentInAlgebraicGeometry.Chapter05.Section02ProofOfEffectivity
import LastLib.Book10FaithfullyFlatDescentInAlgebraicGeometry.Chapter05.Section03MorphismsAndExactSequences
import LastLib.Book10FaithfullyFlatDescentInAlgebraicGeometry.Chapter05.Section04BaseChangeAndTransitivity
