import LastLib.Book10FaithfullyFlatDescentInAlgebraicGeometry.Chapter07.Dependencies
import LastLib.Book10FaithfullyFlatDescentInAlgebraicGeometry.Chapter07.Section01DescentOfAlgebraStructures
import LastLib.Book10FaithfullyFlatDescentInAlgebraicGeometry.Chapter07.Section02QuotientsAndEquations
import LastLib.Book10FaithfullyFlatDescentInAlgebraicGeometry.Chapter07.Section03AffineDescent
import LastLib.Book10FaithfullyFlatDescentInAlgebraicGeometry.Chapter07.Section04FiniteAndFiniteLocallyFreeAffineSchemes
