import LastLib.Book10FaithfullyFlatDescentInAlgebraicGeometry.Chapter09.Section01DescentOfLocalFreeness
import LastLib.Book10FaithfullyFlatDescentInAlgebraicGeometry.Chapter09.Section02TransitionMatricesAndCocycles
import LastLib.Book10FaithfullyFlatDescentInAlgebraicGeometry.Chapter09.Section03DeterminantsSectionsAndForms
import LastLib.Book10FaithfullyFlatDescentInAlgebraicGeometry.Chapter09.Section04WhyLocalTrivialityIsNotDescentData

namespace LastLib.Book10FaithfullyFlatDescentInAlgebraicGeometry.Chapter09

end LastLib.Book10FaithfullyFlatDescentInAlgebraicGeometry.Chapter09
