import LastLib.Book10FaithfullyFlatDescentInAlgebraicGeometry.Chapter12.Dependencies
import LastLib.Book10FaithfullyFlatDescentInAlgebraicGeometry.Chapter12.Section01GroupLawsDescend
import LastLib.Book10FaithfullyFlatDescentInAlgebraicGeometry.Chapter12.Section02HopfAlgebraForm
import LastLib.Book10FaithfullyFlatDescentInAlgebraicGeometry.Chapter12.Section03SubgroupsHomomorphismsExactness
import LastLib.Book10FaithfullyFlatDescentInAlgebraicGeometry.Chapter12.Section04ActionsAndQuotients
