import LastLib.Book10FaithfullyFlatDescentInAlgebraicGeometry.Chapter16.Dependencies
import LastLib.Book10FaithfullyFlatDescentInAlgebraicGeometry.Chapter16.Section01GeneralizedEllipticCurves
import LastLib.Book10FaithfullyFlatDescentInAlgebraicGeometry.Chapter16.Section02PELObjects
import LastLib.Book10FaithfullyFlatDescentInAlgebraicGeometry.Chapter16.Section03RepresentabilityAfterDescent
import LastLib.Book10FaithfullyFlatDescentInAlgebraicGeometry.Chapter16.Section04PracticalDescentProtocol
