import LastLib.Book10FaithfullyFlatDescentInAlgebraicGeometry.Chapter17.Section01TheThreeLevelsOfDescent
import LastLib.Book10FaithfullyFlatDescentInAlgebraicGeometry.Chapter17.Section02TheReusableTheoremPackage
import LastLib.Book10FaithfullyFlatDescentInAlgebraicGeometry.Chapter17.Section03Conclusion
