import Mathlib

namespace ValuationsBook.Chapter04

open scoped BigOperators Multiplicative PowerSeries WithZero
open Ideal IsLocalRing

noncomputable section

/-!
# Chapter 4: Discrete valuation rings

This file is a statement-generation pass for Sections 4.1--4.3 of Book 1.  The
zero-extended multiplicative target `ℤᵐ⁰` is used for Mathlib valuations; its
nonzero part is the additive integer-valued valuation `Kˣ → ℤ` from the prose.
-/

/-! ## 4.1. Discrete valuation data and uniformizers -/

/-- A Mathlib valuation is discrete in the chapter's sense when it is surjective
onto the zero-extended multiplicative copy of `ℤ`. -/
def IsSurjectiveIntegerValuation (K : Type*) [Field K]
    (v : Valuation K ℤᵐ⁰) : Prop :=
  Function.Surjective v

/-- A valuation witness saying that `A` is the valuation ring of a surjective
integer-valued valuation on its fraction field. -/
structure Chapter04DVRValuationWitness (A K : Type*)
    [CommRing A] [IsDomain A] [Field K] [Algebra A K] [IsFractionRing A K] where
  valuation : Valuation K ℤᵐ⁰
  surjective : IsSurjectiveIntegerValuation K valuation
  valuationSubring_eq_image :
    valuation.valuationSubring.toSubring =
      Subring.map (algebraMap A K) (⊤ : Subring A)

/-- “`A` is the valuation ring of a discrete valuation `Kˣ → ℤ`”, expressed
using the zero-extended Mathlib valuation interface. -/
def IsValuationRingOfDiscreteValuation (A K : Type*)
    [CommRing A] [IsDomain A] [Field K] [Algebra A K] [IsFractionRing A K] : Prop :=
  Nonempty (Chapter04DVRValuationWitness A K)

/-- A chapter-local spelling of “uniformizer”: an element generating the maximal
ideal of a local domain. -/
def Chapter04Uniformizer (A : Type*) [CommRing A] [IsDomain A] [IsLocalRing A]
    (π : A) : Prop :=
  π ≠ 0 ∧ IsLocalRing.maximalIdeal A = Ideal.span ({π} : Set A)

/-- Mathlib's normalized additive valuation on a DVR, exposed with a chapter-local name. -/
def chapter04AdditiveValue (A : Type*) [CommRing A] [IsDomain A]
    [IsDiscreteValuationRing A] (x : A) : ℕ∞ :=
  IsDiscreteValuationRing.addVal A x

/-- The ideal `(π^r)` used throughout the arithmetic part of the chapter. -/
def chapter04IdealPower (A : Type*) [CommRing A] (π : A) (r : ℕ) : Ideal A :=
  Ideal.span ({π ^ r} : Set A)

/-- The abstract order-theoretic condition that a magnitude order has a first
positive magnitude. -/
def HasLeastPositiveMagnitude (Γ : Type*) [Preorder Γ] [Zero Γ] : Prop :=
  ∃ γ : Γ, 0 < γ ∧ ∀ δ : Γ, 0 < δ → γ ≤ δ

/-- The failure of a first positive magnitude, recording the nondiscrete
rank-one phenomenon mentioned in Section 4.1. -/
def HasNoLeastPositiveMagnitude (Γ : Type*) [Preorder Γ] [Zero Γ] : Prop :=
  ¬ HasLeastPositiveMagnitude Γ

/-- A surjective integer valuation has the discrete generator required by
Mathlib's rank-one discrete valuation interface. -/
theorem surjective_integer_valuation_is_rank_one_discrete
    (K : Type*) [Field K] (v : Valuation K ℤᵐ⁰)
    (hv : IsSurjectiveIntegerValuation K v) :
    Valuation.IsRankOneDiscrete v := by
  sorry

/-- The first positive step in a discrete value group is represented by a
generator below `1` in the multiplicative Mathlib convention. -/
theorem rank_one_discrete_valuation_has_generator
    (K : Type*) [Field K] (v : Valuation K ℤᵐ⁰)
    [Valuation.IsRankOneDiscrete v] :
    ∃ γ : (ℤᵐ⁰)ˣ,
      Subgroup.zpowers γ = MonoidWithZeroHom.valueGroup (.ofClass v) ∧ γ < 1 := by
  sorry

/-- The valuation-ring/DVR correspondence for the chapter's discrete valuation
interface. -/
theorem is_discrete_valuation_ring_iff_chapter04_valuation_witness
    (A K : Type*) [CommRing A] [IsDomain A] [Field K]
    [Algebra A K] [IsFractionRing A K] :
    IsDiscreteValuationRing A ↔ IsValuationRingOfDiscreteValuation A K := by
  sorry

/-- In a DVR the maximal ideal is generated by a uniformizer, and every
nonzero ideal is a unique power of it. -/
theorem dvr_maximal_ideal_and_unique_ideal_powers
    (A : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A] :
    (∃ π : A, π ≠ 0 ∧ Chapter04Uniformizer A π) ∧
      ∀ I : Ideal A, I ≠ ⊥ →
        ∃! n : ℕ, I = IsLocalRing.maximalIdeal A ^ n := by
  sorry

/-- A nonzero ideal contains an element of least additive valuation. -/
theorem dvr_nonzero_ideal_has_least_additive_value
    (A : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    (I : Ideal A) (hI : I ≠ ⊥) :
    ∃ x : A, x ∈ I ∧
      ∀ y : A, y ∈ I → chapter04AdditiveValue A x ≤ chapter04AdditiveValue A y := by
  sorry

/-- The least-valued element of a nonzero ideal generates that ideal. -/
theorem dvr_least_value_element_generates_ideal
    (A : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    (I : Ideal A) (hI : I ≠ ⊥) (x : A) (hx : x ∈ I)
    (hmin : ∀ y : A, y ∈ I →
      chapter04AdditiveValue A x ≤ chapter04AdditiveValue A y) :
    I = Ideal.span ({x} : Set A) := by
  sorry

/-- A principal maximal ideal forces every nonzero element to leave the chain
of its successive powers at a finite stage. -/
theorem principal_maximal_ideal_has_finite_power_order
    (A : Type*) [CommRing A] [IsDomain A] [IsNoetherianRing A]
    [IsLocalRing A] {π : A} (hπ : π ≠ 0)
    (hmax : IsLocalRing.maximalIdeal A = Ideal.span ({π} : Set A))
    {x : A} (hx : x ≠ 0) :
    ∃ n : ℕ,
      x ∈ IsLocalRing.maximalIdeal A ^ n ∧
        x ∉ IsLocalRing.maximalIdeal A ^ (n + 1) := by
  sorry

/-- Repeated division by a principal maximal-ideal generator gives a unit times
a unique power of that generator. -/
theorem principal_maximal_ideal_gives_unique_unit_power_factorization
    (A : Type*) [CommRing A] [IsDomain A] [IsNoetherianRing A]
    [IsLocalRing A] {π : A} (hπ : π ≠ 0)
    (hmax : IsLocalRing.maximalIdeal A = Ideal.span ({π} : Set A))
    {x : A} (hx : x ≠ 0) :
    ∃ (n : ℕ) (u : Aˣ),
      x = (u : A) * π ^ n ∧
        ∀ (m : ℕ) (w : Aˣ), x = (w : A) * π ^ m → m = n ∧ w = u := by
  sorry

/-- Every DVR is integrally closed. -/
theorem dvr_is_integrally_closed
    (A : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A] :
    IsIntegrallyClosed A := by
  sorry

/-- Every DVR is one-dimensional. -/
theorem dvr_is_one_dimensional
    (A : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A] :
    ringKrullDim A = 1 := by
  sorry

/-- The determinant-trick step in the integrally-closed characterization: under
the one-dimensional Noetherian local hypotheses, the maximal ideal is principal. -/
theorem principal_maximal_ideal_of_one_dimensional_integrally_closed_local_domain
    (A : Type*) [CommRing A] [IsDomain A] [IsNoetherianRing A] [IsLocalRing A]
    (hfield : ¬ IsField A) (hdim : ringKrullDim A = 1)
    (hnormal : IsIntegrallyClosed A) :
    (IsLocalRing.maximalIdeal A).IsPrincipal := by
  sorry

/-- The six conditions in Theorem 4.1, with the one-dimensional assertions
written using `ringKrullDim`. -/
def Chapter04HasUniqueNonzeroPrimeIdeal (A : Type*) [CommRing A] : Prop :=
  ∃! P : Ideal A, P ≠ ⊥ ∧ P.IsPrime

def Chapter04IsNoetherianValuationRing (A : Type*) [CommRing A] [IsDomain A] : Prop :=
  IsNoetherianRing A ∧ ValuationRing A

def Chapter04IsPIDWithUniqueNonzeroPrime (A : Type*) [CommRing A] [IsDomain A] : Prop :=
  IsPrincipalIdealRing A ∧ Chapter04HasUniqueNonzeroPrimeIdeal A

def Chapter04IsOneDimensionalNoetherianLocalPrincipal (A : Type*)
    [CommRing A] [IsDomain A] : Prop :=
  IsNoetherianRing A ∧ IsLocalRing A ∧ ringKrullDim A = 1 ∧
    ∃ m : Ideal A, m.IsMaximal ∧ m.IsPrincipal

def Chapter04IsOneDimensionalNoetherianLocalIntegrallyClosed (A : Type*)
    [CommRing A] [IsDomain A] : Prop :=
  IsNoetherianRing A ∧ IsLocalRing A ∧ IsIntegrallyClosed A ∧ ringKrullDim A = 1

def Chapter04IsLocalWithUniqueIdealPowers (A : Type*) [CommRing A] [IsDomain A] : Prop :=
  IsLocalRing A ∧
    ∃ π : A, π ≠ 0 ∧
      ∀ I : Ideal A, I ≠ ⊥ →
        ∃! n : ℕ, I = Ideal.span ({π ^ n} : Set A)

/-- Theorem 4.1: the six standard characterizations of a DVR are equivalent. -/
theorem theorem_4_1_characterizations_of_a_dvr
    (A K : Type*) [CommRing A] [IsDomain A] [Field K]
    [Algebra A K] [IsFractionRing A K] (hfield : ¬ IsField A) :
    List.TFAE
      [ IsValuationRingOfDiscreteValuation A K,
        Chapter04IsNoetherianValuationRing A,
        Chapter04IsPIDWithUniqueNonzeroPrime A,
        Chapter04IsOneDimensionalNoetherianLocalPrincipal A,
        Chapter04IsOneDimensionalNoetherianLocalIntegrallyClosed A,
        Chapter04IsLocalWithUniqueIdealPowers A ] := by
  sorry

/-- The normalized valuation is unique once its valuation ring is fixed. -/
theorem normalized_integer_valuation_unique
    (A K : Type*) [CommRing A] [IsDomain A] [Field K]
    [Algebra A K] [IsFractionRing A K]
    {v w : Valuation K ℤᵐ⁰}
    (hv : IsSurjectiveIntegerValuation K v)
    (hw : IsSurjectiveIntegerValuation K w)
    (hvA : v.valuationSubring.toSubring =
      Subring.map (algebraMap A K) (⊤ : Subring A))
    (hwA : w.valuationSubring.toSubring =
      Subring.map (algebraMap A K) (⊤ : Subring A)) :
    v = w := by
  sorry

/-- A fixed uniformizer gives the unique fraction-field normal form
`x = π^n u` (written using Mathlib's scalar action of `Aˣ`). -/
theorem dvr_fraction_field_unique_normal_form
    (A K : Type*) [CommRing A] [IsDomain A] [Field K]
    [Algebra A K] [IsFractionRing A K] [IsDiscreteValuationRing A]
    {π : A} (hπ : Chapter04Uniformizer A π) {x : K} (hx : x ≠ 0) :
    ∃ (n : ℤ) (u : Aˣ),
      x = u • (algebraMap A K π) ^ n ∧
        ∀ (m : ℤ) (w : Aˣ),
          x = w • (algebraMap A K π) ^ m → m = n ∧ w = u := by
  sorry

/-- A uniformizer has normalized additive value `1`. -/
theorem dvr_uniformizer_has_value_one
    (A : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    {π : A} (hπ : Chapter04Uniformizer A π) :
    chapter04AdditiveValue A π = 1 := by
  sorry

/-- Two uniformizers differ by a unit. -/
theorem dvr_uniformizers_are_associated
    (A : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    {π ρ : A} (hπ : Chapter04Uniformizer A π)
    (hρ : Chapter04Uniformizer A ρ) :
    Associated π ρ := by
  sorry

/-- In a DVR, generating the maximal ideal is equivalent to being a
uniformizer, and hence to being irreducible. -/
theorem dvr_uniformizer_iff_irreducible
    (A : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    (π : A) :
    Chapter04Uniformizer A π ↔ Irreducible π := by
  sorry

/-! ## 4.2--4.3. Arithmetic of powers of the maximal ideal -/

/-- Membership in the valuation ring is the valuation inequality `v(x) ≤ 1`
in Mathlib's multiplicative convention. -/
theorem dvr_witness_mem_ring_iff_value_le_one
    (A K : Type*) [CommRing A] [IsDomain A] [Field K]
    [Algebra A K] [IsFractionRing A K]
    (W : Chapter04DVRValuationWitness A K) (x : K) :
    (∃ a : A, algebraMap A K a = x) ↔ W.valuation x ≤ 1 := by
  sorry

/-- Membership in the unit group is exactly valuation `0` in additive language,
or value `1` in the multiplicative Mathlib language. -/
theorem dvr_witness_mem_unit_iff_value_one
    (A K : Type*) [CommRing A] [IsDomain A] [Field K]
    [Algebra A K] [IsFractionRing A K]
    (W : Chapter04DVRValuationWitness A K) (x : K) :
    (∃ u : Aˣ, algebraMap A K (u : A) = x) ↔ W.valuation x = 1 := by
  sorry

/-- The maximal ideal is the strict valuation ball below `1`. -/
theorem dvr_witness_mem_maximal_ideal_iff_value_lt_one
    (A K : Type*) [CommRing A] [IsDomain A] [IsLocalRing A] [Field K]
    [Algebra A K] [IsFractionRing A K]
    (W : Chapter04DVRValuationWitness A K) (a : A) :
    a ∈ IsLocalRing.maximalIdeal A ↔
      W.valuation (algebraMap A K a) < 1 := by
  sorry

/-- For a uniformizer, powers of the maximal ideal are the corresponding
valuation balls. -/
theorem dvr_witness_mem_maximal_ideal_power_iff_value_le_power
    (A K : Type*) [CommRing A] [IsDomain A] [IsLocalRing A] [Field K]
    [Algebra A K] [IsFractionRing A K]
    (W : Chapter04DVRValuationWitness A K) {π : A}
    (hπ : Chapter04Uniformizer A π) (r : ℕ) (a : A) :
    a ∈ IsLocalRing.maximalIdeal A ^ r ↔
      W.valuation (algebraMap A K a) ≤
        W.valuation (algebraMap A K π) ^ r := by
  sorry

/-- The additive Mathlib valuation gives the same power-of-the-maximal-ideal
filtration, including the zero element at value `∞`. -/
theorem dvr_additive_value_mem_maximal_ideal_power_iff
    (A : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    (a : A) (r : ℕ) :
    (r : ℕ∞) ≤ chapter04AdditiveValue A a ↔
      a ∈ IsLocalRing.maximalIdeal A ^ r := by
  sorry

/-- Units are precisely the elements of additive value zero. -/
theorem dvr_additive_value_eq_zero_iff_isUnit
    (A : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    (a : A) :
    chapter04AdditiveValue A a = 0 ↔ IsUnit a := by
  sorry

/-- Divisibility in a valuation ring is a total relation. -/
theorem dvr_divisibility_is_total
    (A : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A] :
    ∀ x y : A, x ∣ y ∨ y ∣ x := by
  sorry

/-- Sums of principal powers use the smaller exponent. -/
theorem dvr_ideal_power_sum_min
    (A : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    {π : A} (hπ : Chapter04Uniformizer A π) (a b : ℕ) :
    chapter04IdealPower A π a ⊔ chapter04IdealPower A π b =
      chapter04IdealPower A π (min a b) := by
  sorry

/-- Intersections of principal powers use the larger exponent. -/
theorem dvr_ideal_power_inf_max
    (A : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    {π : A} (hπ : Chapter04Uniformizer A π) (a b : ℕ) :
    chapter04IdealPower A π a ⊓ chapter04IdealPower A π b =
      chapter04IdealPower A π (max a b) := by
  sorry

/-- Products of principal powers add exponents. -/
theorem dvr_ideal_power_mul_add
    (A : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    {π : A} (hπ : Chapter04Uniformizer A π) (a b : ℕ) :
    chapter04IdealPower A π a * chapter04IdealPower A π b =
      chapter04IdealPower A π (a + b) := by
  sorry

/-- The irreducibles of a DVR are exactly the elements of normalized value `1`. -/
theorem dvr_irreducible_iff_value_one
    (A : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    (a : A) :
    Irreducible a ↔ chapter04AdditiveValue A a = 1 := by
  sorry

/-- All irreducibles in a DVR are associates. -/
theorem dvr_all_irreducibles_are_associates
    (A : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    {p q : A} (hp : Irreducible p) (hq : Irreducible q) :
    Associated p q := by
  sorry

/-! ## 4.3. Principal examples -/

/-- A reusable spelling for localization at a prime ideal. -/
abbrev chapter04AtPrimeLocalization (R : Type*) [CommRing R] (P : Ideal R)
    [P.IsPrime] : Type _ :=
  Localization.AtPrime P

/-- In a Dedekind domain, localization at a nonzero prime is a DVR. -/
theorem dedekind_localization_at_nonzero_prime_is_dvr
    (R : Type*) [CommRing R] [IsDomain R] [IsDedekindDomain R]
    (P : Ideal R) (hP : P ≠ ⊥) [P.IsPrime] :
    IsDiscreteValuationRing (chapter04AtPrimeLocalization R P) := by
  sorry

/-- For a prime ideal of `ℤ` generated by a rational prime, the local ring is a
DVR. The displayed `P` records the usual notation `ℤ_(p)`. -/
theorem integer_localization_at_prime_is_dvr
    (p : ℕ) (hp : Nat.Prime p) (P : Ideal ℤ) [P.IsPrime]
    (hP : P = Ideal.span ({(p : ℤ)} : Set ℤ)) (hP0 : P ≠ ⊥) :
    IsDiscreteValuationRing (chapter04AtPrimeLocalization ℤ P) := by
  sorry

/-- The uniformizer of `ℤ_(p)` is the image of `p`. -/
theorem integer_localization_uniformizer
    (p : ℕ) (hp : Nat.Prime p) (P : Ideal ℤ) [P.IsPrime]
    (hP : P = Ideal.span ({(p : ℤ)} : Set ℤ)) (hP0 : P ≠ ⊥) :
    Chapter04Uniformizer (chapter04AtPrimeLocalization ℤ P)
      (algebraMap ℤ (chapter04AtPrimeLocalization ℤ P) (p : ℤ)) := by
  sorry

/-- The residue field of `ℤ_(p)` is `𝔽_p`, represented by `ZMod p`. -/
theorem integer_localization_residue_field
    (p : ℕ) (hp : Nat.Prime p) (P : Ideal ℤ) [P.IsPrime]
    (hP : P = Ideal.span ({(p : ℤ)} : Set ℤ)) (hP0 : P ≠ ⊥) :
    Nonempty (IsLocalRing.ResidueField (chapter04AtPrimeLocalization ℤ P) ≃+* ZMod p) := by
  sorry

/-- The localization `k[t]_(t)` is a DVR with uniformizer `t`. -/
theorem polynomial_localization_at_X_is_dvr
    (k : Type*) [Field k] (P : Ideal (Polynomial k)) [P.IsPrime]
    (hP : P = Ideal.span ({Polynomial.X} : Set (Polynomial k))) :
    IsDiscreteValuationRing (chapter04AtPrimeLocalization (Polynomial k) P) := by
  sorry

/-- The image of `t` is the uniformizer in `k[t]_(t)`. -/
theorem polynomial_localization_at_X_uniformizer
    (k : Type*) [Field k] (P : Ideal (Polynomial k)) [P.IsPrime]
    (hP : P = Ideal.span ({Polynomial.X} : Set (Polynomial k))) :
    Chapter04Uniformizer (chapter04AtPrimeLocalization (Polynomial k) P)
      (algebraMap (Polynomial k)
        (chapter04AtPrimeLocalization (Polynomial k) P) Polynomial.X) := by
  sorry

/-- The residue field of `k[t]_(t)` is `k`. -/
theorem polynomial_localization_at_X_residue_field
    (k : Type*) [Field k] (P : Ideal (Polynomial k)) [P.IsPrime]
    (hP : P = Ideal.span ({Polynomial.X} : Set (Polynomial k))) :
    Nonempty (IsLocalRing.ResidueField (chapter04AtPrimeLocalization (Polynomial k) P) ≃+* k) := by
  sorry

/-- For irreducible `P ∈ k[t]`, the local ring `k[t]_(P)` is a DVR with
uniformizer the image of `P`. -/
theorem polynomial_localization_at_irreducible_is_dvr
    (k : Type*) [Field k] (f : Polynomial k) (hf : Irreducible f)
    (P : Ideal (Polynomial k)) [P.IsPrime]
    (hP : P = Ideal.span ({f} : Set (Polynomial k))) :
    IsDiscreteValuationRing (chapter04AtPrimeLocalization (Polynomial k) P) := by
  sorry

/-- The image of an irreducible polynomial generates the maximal ideal of
`k[t]_(P)`. -/
theorem polynomial_localization_at_irreducible_uniformizer
    (k : Type*) [Field k] (f : Polynomial k) (hf : Irreducible f)
    (P : Ideal (Polynomial k)) [P.IsPrime]
    (hP : P = Ideal.span ({f} : Set (Polynomial k))) :
    Chapter04Uniformizer (chapter04AtPrimeLocalization (Polynomial k) P)
      (algebraMap (Polynomial k)
        (chapter04AtPrimeLocalization (Polynomial k) P) f) := by
  sorry

/-- The residue field at `(f)` is `k[t]/(f)`. -/
theorem polynomial_localization_at_irreducible_residue_field
    (k : Type*) [Field k] (f : Polynomial k) (hf : Irreducible f)
    (P : Ideal (Polynomial k)) [P.IsPrime]
    (hP : P = Ideal.span ({f} : Set (Polynomial k))) :
    Nonempty
      (IsLocalRing.ResidueField (chapter04AtPrimeLocalization (Polynomial k) P) ≃+*
        (Polynomial k ⧸ (Ideal.span ({f} : Set (Polynomial k))))) := by
  sorry

/-- The formal parameter `t` in a formal power series ring. -/
def chapter04FormalPowerSeriesParameter (k : Type*) [Semiring k] : PowerSeries k :=
  PowerSeries.X

/-- The formal power series residue-field equivalence supplied by Mathlib. -/
def chapter04FormalPowerSeriesResidueEquiv (k : Type*) [Field k] :
    IsLocalRing.ResidueField (PowerSeries k) ≃+* k :=
  PowerSeries.residueFieldOfPowerSeries (k := k)

/-- Every element of `k[[t]]` is a coefficient sequence, i.e. a formal sum
`∑ aₙ tⁿ`. -/
theorem formal_power_series_coefficient_expansion
    (k : Type*) [Semiring k] (f : PowerSeries k) :
    ∃ a : ℕ → k, f = PowerSeries.mk a := by
  sorry

/-- A power series over a field is a unit exactly when its constant coefficient
is nonzero. -/
theorem formal_power_series_unit_iff_constant_coefficient_ne_zero
    (k : Type*) [Field k] (f : PowerSeries k) :
    IsUnit f ↔ PowerSeries.constantCoeff f ≠ 0 := by
  sorry

/-- Every nonzero power series is `t^n u` for a unit `u`. -/
theorem formal_power_series_unique_power_unit_factorization
    (k : Type*) [Field k] {f : PowerSeries k} (hf : f ≠ 0) :
    ∃ (n : ℕ) (u : (PowerSeries k)ˣ),
      f = (PowerSeries.X ^ n) * (u : PowerSeries k) ∧
        ∀ (m : ℕ) (w : (PowerSeries k)ˣ),
          f = (PowerSeries.X ^ m) * (w : PowerSeries k) → m = n ∧ w = u := by
  sorry

/-- `k[[t]]` is a DVR. -/
theorem formal_power_series_is_dvr
    (k : Type*) [Field k] :
    IsDiscreteValuationRing (PowerSeries k) := by
  sorry

/-- The maximal ideal of `k[[t]]` is generated by `t`. -/
theorem formal_power_series_maximal_ideal
    (k : Type*) [Field k] :
    IsLocalRing.maximalIdeal (PowerSeries k) =
      Ideal.span ({PowerSeries.X} : Set (PowerSeries k)) := by
  sorry

/-- The residue field of `k[[t]]` is `k`. -/
theorem formal_power_series_residue_field
    (k : Type*) [Field k] :
    Nonempty (IsLocalRing.ResidueField (PowerSeries k) ≃+* k) := by
  sorry

/-- The fraction field of `k[[t]]` is the Laurent-series field `k((t))`. -/
theorem formal_power_series_fraction_field_is_laurent_series
    (k : Type*) [Field k] :
    IsFractionRing (PowerSeries k) (LaurentSeries k) := by
  sorry

/-- Formal power series are complete for the `t`-adic topology. -/
theorem formal_power_series_is_complete
    (k : Type*) [Field k] :
    IsAdicComplete
      (Ideal.span ({PowerSeries.X} : Set (PowerSeries k))) (PowerSeries k) := by
  sorry

/-- The local polynomial example and the formal power-series example have the
same uniformizer and residue field, but only the latter is complete. -/
theorem polynomial_localization_and_power_series_comparison
    (k : Type*) [Field k] (P : Ideal (Polynomial k)) [P.IsPrime]
    (hP : P = Ideal.span ({Polynomial.X} : Set (Polynomial k))) :
    Chapter04Uniformizer (chapter04AtPrimeLocalization (Polynomial k) P)
        (algebraMap (Polynomial k)
          (chapter04AtPrimeLocalization (Polynomial k) P) Polynomial.X) ∧
      Chapter04Uniformizer (PowerSeries k) PowerSeries.X ∧
      Nonempty (IsLocalRing.ResidueField (chapter04AtPrimeLocalization (Polynomial k) P) ≃+* k) ∧
      Nonempty (IsLocalRing.ResidueField (PowerSeries k) ≃+* k) ∧
      ¬ IsAdicComplete
          (IsLocalRing.maximalIdeal (chapter04AtPrimeLocalization (Polynomial k) P))
          (chapter04AtPrimeLocalization (Polynomial k) P) ∧
      IsAdicComplete
        (Ideal.span ({PowerSeries.X} : Set (PowerSeries k))) (PowerSeries k) := by
  sorry

/-! ## 4.3. Failure examples -/

/-- The coefficient description of `k[[t²,t³]]`: the coefficient of `t` is
zero, while all degrees `0` and at least `2` are allowed. -/
def chapter04CuspPowerSeriesSubring (k : Type*) [CommRing k] :
    Subring (PowerSeries k) := by
  refine
    { carrier := {f | PowerSeries.coeff 1 f = 0}
      zero_mem' := by simp
      add_mem' := by
        intro f g hf hg
        change PowerSeries.coeff 1 f = 0 at hf
        change PowerSeries.coeff 1 g = 0 at hg
        change PowerSeries.coeff 1 (f + g) = 0
        simpa [map_add, hf, hg]
      one_mem' := by simp
      mul_mem' := by
        sorry
      neg_mem' := by
        intro f hf
        change PowerSeries.coeff 1 f = 0 at hf
        change PowerSeries.coeff 1 (-f) = 0
        simpa [map_neg, hf] }

/-- The `t²` generator of the cusp power-series ring. -/
def chapter04CuspPowerSeriesT2 (k : Type*) [CommRing k] :
    chapter04CuspPowerSeriesSubring k := by
  refine ⟨PowerSeries.X ^ 2, ?_⟩
  change PowerSeries.coeff 1 (PowerSeries.X ^ 2) = 0
  simp

/-- The `t³` generator of the cusp power-series ring. -/
def chapter04CuspPowerSeriesT3 (k : Type*) [CommRing k] :
    chapter04CuspPowerSeriesSubring k := by
  refine ⟨PowerSeries.X ^ 3, ?_⟩
  change PowerSeries.coeff 1 (PowerSeries.X ^ 3) = 0
  simp

/-- The maximal ideal `(t²,t³)` in the cusp power-series ring. -/
def chapter04CuspPowerSeriesMaximalIdeal (k : Type*) [CommRing k] :
    Ideal (chapter04CuspPowerSeriesSubring k) := by
  exact Ideal.span
    ({chapter04CuspPowerSeriesT2 k, chapter04CuspPowerSeriesT3 k} :
      Set (chapter04CuspPowerSeriesSubring k))

/-- The ambient parameter `t`, which is absent from `k[[t²,t³]]`. -/
def chapter04CuspAmbientParameter (k : Type*) [CommRing k] : PowerSeries k :=
  PowerSeries.X

/-- `k[[t²,t³]]` is a complete one-dimensional domain but is not normal. -/
theorem cusp_power_series_is_complete_one_dimensional_non_normal
    (k : Type*) [Field k] :
    IsDomain (chapter04CuspPowerSeriesSubring k) ∧
      IsLocalRing (chapter04CuspPowerSeriesSubring k) ∧
      IsAdicComplete
        (chapter04CuspPowerSeriesMaximalIdeal k)
        (chapter04CuspPowerSeriesSubring k) ∧
      ringKrullDim (chapter04CuspPowerSeriesSubring k) = 1 ∧
      ¬ IsIntegrallyClosed (chapter04CuspPowerSeriesSubring k) := by
  sorry

/-- The missing parameter `t` is integral over `k[[t²,t³]]` but is not an
element of that ring. -/
theorem cusp_parameter_is_integral_but_absent
    (k : Type*) [Field k] :
    IsIntegral (chapter04CuspPowerSeriesSubring k)
        (chapter04CuspAmbientParameter k) ∧
      chapter04CuspAmbientParameter k ∉
        (chapter04CuspPowerSeriesSubring k : Set (PowerSeries k)) := by
  sorry

/-- Consequently the cusp power-series ring is not a DVR. -/
theorem cusp_power_series_is_not_a_dvr
    (k : Type*) [Field k] :
    ¬ IsDiscreteValuationRing (chapter04CuspPowerSeriesSubring k) := by
  sorry

/-- The maximal ideal `(x,y)` in the two-variable polynomial ring. -/
def chapter04TwoVariablePolynomialMaximalIdeal (k : Type*) [CommSemiring k] :
    Ideal (MvPolynomial (Fin 2) k) :=
  Ideal.span ({MvPolynomial.X 0, MvPolynomial.X 1} :
    Set (MvPolynomial (Fin 2) k))

/-- The local ring `k[x,y]_(x,y)` is normal and two-dimensional, hence not a
DVR. -/
theorem two_variable_polynomial_localization_is_integrally_closed_two_dimensional
    (k : Type*) [Field k] (P : Ideal (MvPolynomial (Fin 2) k)) [P.IsPrime]
    (hP : P = chapter04TwoVariablePolynomialMaximalIdeal k) :
    IsIntegrallyClosed (chapter04AtPrimeLocalization (MvPolynomial (Fin 2) k) P) ∧
      IsLocalRing (chapter04AtPrimeLocalization (MvPolynomial (Fin 2) k) P) ∧
      ringKrullDim (chapter04AtPrimeLocalization (MvPolynomial (Fin 2) k) P) = 2 ∧
      IsLocalRing.maximalIdeal (chapter04AtPrimeLocalization (MvPolynomial (Fin 2) k) P) =
        Ideal.map
          (algebraMap (MvPolynomial (Fin 2) k)
            (chapter04AtPrimeLocalization (MvPolynomial (Fin 2) k) P)) P ∧
      ¬ IsDiscreteValuationRing
        (chapter04AtPrimeLocalization (MvPolynomial (Fin 2) k) P) := by
  sorry

/-- The `p`-adic power-series ring `ℤ_p[[t]]`. -/
abbrev chapter04PadicPowerSeries (p : ℕ) [Fact (Nat.Prime p)] :=
  PowerSeries (PadicInt p)

/-- Its maximal ideal `(p,t)`, written with the constant power series `C p`. -/
def chapter04PadicPowerSeriesMaximalIdeal (p : ℕ) [Fact (Nat.Prime p)] :
    Ideal (chapter04PadicPowerSeries p) :=
  Ideal.span ({PowerSeries.C (p : PadicInt p), PowerSeries.X} :
    Set (chapter04PadicPowerSeries p))

/-- The complete regular local ring `ℤ_p[[t]]` has dimension two and is not a
DVR. -/
theorem padic_power_series_is_complete_regular_local_two_dimensional
    (p : ℕ) [Fact (Nat.Prime p)] :
    IsAdicComplete (chapter04PadicPowerSeriesMaximalIdeal p)
        (chapter04PadicPowerSeries p) ∧
      IsRegularLocalRing (chapter04PadicPowerSeries p) ∧
      ringKrullDim (chapter04PadicPowerSeries p) = 2 ∧
      IsLocalRing.maximalIdeal (chapter04PadicPowerSeries p) =
        chapter04PadicPowerSeriesMaximalIdeal p ∧
      ¬ IsDiscreteValuationRing (chapter04PadicPowerSeries p) := by
  sorry

end
end ValuationsBook.Chapter04
