import LastLib.Book05LocalClassFieldTheory.Chapter10.Dependencies

namespace LastLib.Book05LocalClassFieldTheory.Chapter10

noncomputable section

open LastLib.Book05LocalClassFieldTheory.Chapter05

/-! ## 10.1. Unramified extensions -/

/- The residue extension and normalized valuation data used by the explicit
   unramified norm calculation.  The residue algebra is an instance field
   because the canonical Book 2 norm theorem consumes it through typeclass
   inference. -/
structure Chapter10UnramifiedExtensionData
    {K L : Type*} [Field K] [Field L] [Algebra K L]
    [FiniteDimensional K L] [Algebra.IsSeparable K L]
    (D : Chapter10LocalFieldProfile K) (m : ℕ) where
  valuation : AddValuation L (WithTop ℤ)
  unramified :
    LastLib.Book02FiniteExtensionsOfLocalFields.Chapter11.chapter11UnramifiedValuedExtension
      D.valuation valuation
  positive : 0 < m
  degree_eq : Module.finrank K L = m
  uniformizer_is_uniformizer :
    LastLib.Book02FiniteExtensionsOfLocalFields.Chapter11.chapter11IsUniformizer
      D.valuation (D.uniformizer : K)
  residue_degree_eq :
    m =
      LastLib.Book01ValuationsDVRsAndCompletions.Chapter11.chapter11AdditiveResidueDegree
        D.valuation valuation unramified.1
  [residue_algebra :
    Algebra
      (LastLib.Book02FiniteExtensionsOfLocalFields.Chapter11.chapter11ResidueField
        D.valuation)
      (LastLib.Book02FiniteExtensionsOfLocalFields.Chapter11.chapter11ResidueField
        valuation)]
  [residue_finite_dimensional :
    FiniteDimensional
      (LastLib.Book02FiniteExtensionsOfLocalFields.Chapter11.chapter11ResidueField
        D.valuation)
      (LastLib.Book02FiniteExtensionsOfLocalFields.Chapter11.chapter11ResidueField
        valuation)]
  [residue_separable :
    Algebra.IsSeparable
      (LastLib.Book02FiniteExtensionsOfLocalFields.Chapter11.chapter11ResidueField
        D.valuation)
      (LastLib.Book02FiniteExtensionsOfLocalFields.Chapter11.chapter11ResidueField
        valuation)]
  residue_reduction_compatible :
    LastLib.Book02FiniteExtensionsOfLocalFields.Chapter11.chapter11ResidueReductionCompatible
      D.valuation valuation
      (LastLib.Book02FiniteExtensionsOfLocalFields.Chapter11.chapter11ResidueMap
        D.valuation)
      (LastLib.Book02FiniteExtensionsOfLocalFields.Chapter11.chapter11ResidueMap
        valuation)

/- The full norm subgroup is generated by the `m`th power of a uniformizer and
   the entire base unit group. -/
theorem chapter10_unramified_norm_subgroup_eq_value_unit_subgroup
    {K L : Type*} [Field K] [Field L] [Algebra K L]
    [FiniteDimensional K L] [Algebra.IsSeparable K L]
    (D : Chapter10LocalFieldProfile K) (m : ℕ)
    (U : Chapter10UnramifiedExtensionData (L := L) D m) :
    chapter10NormSubgroup K L =
      chapter10ValueUnitSubgroup D D.uniformizer m 0 := by
  sorry

/- The quotient has only the valuation coordinate.  `Multiplicative (ZMod m)`
   is the multiplicative presentation of the source's additive `ℤ/mℤ`. -/
theorem chapter10_unramified_norm_quotient_equiv
    {K L : Type*} [Field K] [Field L] [Algebra K L]
    [FiniteDimensional K L] [Algebra.IsSeparable K L]
    (D : Chapter10LocalFieldProfile K) (m : ℕ)
    (U : Chapter10UnramifiedExtensionData (L := L) D m) :
    Nonempty
      ((Chapter10NormQuotient K L) ≃*
        Multiplicative (ZMod m)) := by
  sorry

theorem chapter10_unramified_norm_quotient_card
    {K L : Type*} [Field K] [Field L] [Algebra K L]
    [FiniteDimensional K L] [Algebra.IsSeparable K L]
    (D : Chapter10LocalFieldProfile K) (m : ℕ)
    (U : Chapter10UnramifiedExtensionData (L := L) D m) :
    Nat.card (Chapter10NormQuotient K L) = m := by
  sorry

/- The uniformizer class is the arithmetic Frobenius class at finite level.
   This wrapper reuses the normalized finite-reciprocity theorem from Chapter
   5 rather than introducing a second Artin-map convention. -/
theorem chapter10_unramified_uniformizer_is_arithmetic_frobenius
    {K L : Type} [Field K] [Field L] [Algebra K L]
    [FiniteDimensional K L] [IsAbelianGalois K L]
    [Fintype (Gal(L / K))]
    (D : Chapter05LocalClassFormationData K L)
    (U : Chapter05UnramifiedExtensionData K L)
    (N : Chapter05UnramifiedCapNormalization D U) :
    chapter05FiniteReciprocityMap D U.uniformizer =
      U.arithmeticFrobenius := by
  exact chapter05_unramified_uniformizer_is_arithmetic_frobenius D U N

theorem chapter10_unramified_units_are_norms
    {K L : Type*} [Field K] [Field L] [Algebra K L]
    [FiniteDimensional K L] [Algebra.IsSeparable K L]
    (D : Chapter10LocalFieldProfile K) (m : ℕ)
    (U : Chapter10UnramifiedExtensionData (L := L) D m) :
    chapter10LocalUnitSubgroup D ≤ chapter10NormSubgroup K L := by
  rw [chapter10_unramified_norm_subgroup_eq_value_unit_subgroup D m U]
  exact le_sup_right

/- A finite residue norm is solved by a residue step followed by principal-unit
   corrections.  The direct surjectivity assertion is exposed independently
   for callers that do not need the full subgroup formula. -/
theorem chapter10_unramified_residue_norm_surjective
    (k l : Type*) [Field k] [Field l] [Algebra k l]
    [FiniteDimensional k l] [Finite l] :
    Function.Surjective (Algebra.norm k (S := l)) := by
  exact
    LastLib.Book02FiniteExtensionsOfLocalFields.Chapter11.chapter11_finite_residue_norm_surjective
      k l

/- SOURCE WARNING: an arithmetic-Frobenius lift in a ramified quotient is only
   determined modulo inertia.  The following elementary map lemma records the
   exact dependence on changing a chosen uniformizer by a unit. -/
theorem chapter10_reciprocity_uniformizer_change_by_unit
    {K G : Type*} [Field K] [Group G]
    (reciprocity : Kˣ →* G) (π u : Kˣ) :
    reciprocity (π * u) = reciprocity π * reciprocity u := by
  exact reciprocity.map_mul π u

theorem chapter10_reciprocity_uniformizer_change_is_nontrivial
    {K G : Type*} [Field K] [Group G]
    (reciprocity : Kˣ →* G) (π u : Kˣ)
    (hu : reciprocity u ≠ 1) :
    reciprocity (π * u) ≠ reciprocity π := by
  intro h
  apply hu
  rw [reciprocity.map_mul] at h
  exact mul_left_cancel (show reciprocity π * reciprocity u = reciprocity π * 1 by
    simpa using h)

end

end LastLib.Book05LocalClassFieldTheory.Chapter10
