import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter13.Section04TheTamePositiveCharacteristicRange
import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter03.Section05MixedAndEqualCharacteristic
import Mathlib.Algebra.Module.ZMod
import Mathlib.RingTheory.LaurentSeries

namespace LastLib.Book02FiniteExtensionsOfLocalFields.Chapter13

noncomputable section

universe uk

open Polynomial
open scoped BigOperators WithZero

local instance chapter13LaurentSeriesCharP
    (k : Type*) [Field k] (p : ℕ) [CharP k p] :
    CharP (LaurentSeries k) p :=
  charP_of_injective_ringHom
    (f := (HahnSeries.C : k →+* LaurentSeries k))
    HahnSeries.C_injective p

/-! ## 13.5. Wild equal characteristic: an infinite family -/

abbrev chapter13LaurentSeriesLocalField (k : Type*) [Field k] :=
  LaurentSeries k

noncomputable def chapter13LaurentSeriesUniformizer
    (k : Type*) [Field k] : LaurentSeries k :=
  (PowerSeries.X : PowerSeries k)

def chapter13ArtinSchreierRightHandSide
    (k : Type*) [Field k] (m : ℕ) : LaurentSeries k :=
  (chapter13LaurentSeriesUniformizer k)⁻¹ ^ m

def chapter13ArtinSchreierPolynomial
    (k : Type*) [Field k] (p m : ℕ) : (LaurentSeries k)[X] :=
  (X : (LaurentSeries k)[X]) ^ p - X -
    C (chapter13ArtinSchreierRightHandSide k m)

/-- The additive Artin--Schreier map. -/
def chapter13ArtinSchreierMap
    (K : Type*) [Field K] (p : ℕ) [Fact p.Prime] [CharP K p] : K →+ K :=
  { toFun := fun x => x ^ p - x
    map_zero' := by sorry
    map_add' := by
      intro x y
      sorry }

def chapter13ArtinSchreierCoboundarySubgroup
    (K : Type*) [Field K] (p : ℕ) [Fact p.Prime] [CharP K p] : AddSubgroup K :=
  (chapter13ArtinSchreierMap K p).range

abbrev Chapter13ArtinSchreierQuotient
    (K : Type*) [Field K] (p : ℕ) [Fact p.Prime] [CharP K p] :=
  K ⧸ chapter13ArtinSchreierCoboundarySubgroup K p

def chapter13ArtinSchreierClass
    (K : Type*) [Field K] (p : ℕ) [Fact p.Prime] [CharP K p]
    (a : K) : Chapter13ArtinSchreierQuotient K p :=
  QuotientAddGroup.mk' _ a

/-- The one-dimensional `F_p`-line generated by an Artin--Schreier class. -/
def chapter13ArtinSchreierLine
    (K : Type*) [Field K] (p : ℕ) [Fact p.Prime] [CharP K p]
    (a : K) : Set (Chapter13ArtinSchreierQuotient K p) :=
  Set.range (fun c : ZMod p =>
    chapter13ArtinSchreierClass K p ((ZMod.cast c : K) * a))

def chapter13ArtinSchreierEquivalent
    (K : Type*) [Field K] (p : ℕ) [Fact p.Prime] [CharP K p]
    (a b : K) : Prop :=
  ∃ c : ZMod p, c ≠ 0 ∧
    ∃ x : K, b - (ZMod.cast c : K) * a = x ^ p - x

theorem chapter13_artin_schreier_line_equality_iff
    (K : Type*) [Field K] (p : ℕ) [Fact p.Prime] [CharP K p]
    (a b : K) :
    chapter13ArtinSchreierLine K p a =
      chapter13ArtinSchreierLine K p b ↔
    chapter13ArtinSchreierEquivalent K p a b := by
  sorry

/-- The root equation for `T^p - T - a`. -/
theorem chapter13_artin_schreier_root_equation_iff
    (K : Type*) [Field K] (p : ℕ) [Fact p.Prime] [CharP K p]
    (a x : K) :
    aeval x ((X : K[X]) ^ p - X - C a) = 0 ↔
      x ^ p - x = a := by
  sorry

theorem chapter13_artin_schreier_polynomial_derivative
    (K : Type*) [Field K] (p : ℕ) [Fact p.Prime] [CharP K p]
    (a : K) :
    ((X : K[X]) ^ p - X - C a).derivative = -1 := by
  sorry

theorem chapter13_artin_schreier_polynomial_is_separable
    (K : Type*) [Field K] (p : ℕ) [Fact p.Prime] [CharP K p]
    (a : K) :
    ((X : K[X]) ^ p - X - C a).Separable := by
  sorry

def chapter13ArtinSchreierCoboundary (K : Type*) [Field K]
    (p : ℕ) (a : K) : Prop :=
  ∃ x : K, x ^ p - x = a

theorem chapter13_artin_schreier_has_root_iff_coboundary
    (K : Type*) [Field K] (p : ℕ) [Fact p.Prime] [CharP K p]
    (a : K) :
    (∃ x : K,
      aeval x ((X : K[X]) ^ p - X - C a) = 0) ↔
    chapter13ArtinSchreierCoboundary K p a := by
  sorry

theorem chapter13_artin_schreier_irreducible_of_not_coboundary
    (K : Type*) [Field K] (p : ℕ) [Fact p.Prime] [CharP K p]
    (a : K) (ha : ¬chapter13ArtinSchreierCoboundary K p a) :
    Irreducible ((X : K[X]) ^ p - X - C a) := by
  sorry

/-- Data for the cyclic degree-`p` extension generated by an
Artin--Schreier root. -/
structure Chapter13ArtinSchreierExtensionData
    (k : Type uk) [Field k] (p m : ℕ) [Fact p.Prime] [CharP k p]
    (a : LaurentSeries k) where
  carrier : Type uk
  [carrierField : Field carrier]
  [carrierAlgebra : Algebra (LaurentSeries k) carrier]
  [carrierFinite : FiniteDimensional (LaurentSeries k) carrier]
  root : carrier
  root_equation :
    aeval root
      ((X : (LaurentSeries k)[X]) ^ p - X - C a) = 0
  generates :
    Algebra.adjoin (LaurentSeries k) ({root} : Set carrier) = ⊤
  degree : Module.finrank (LaurentSeries k) carrier = p
  separable : Algebra.IsSeparable (LaurentSeries k) carrier
  galois : IsGalois (LaurentSeries k) carrier
  cyclic : IsCyclic (carrier ≃ₐ[LaurentSeries k] carrier)

noncomputable def chapter13ArtinSchreierExtensionModel
    (k : Type*) [Field k] (p m : ℕ) [Fact p.Prime] [CharP k p]
    (a : LaurentSeries k)
    (D : Chapter13ArtinSchreierExtensionData k p m a) :
    Chapter13FiniteExtensionModel (LaurentSeries k) :=
  letI : Field D.carrier := D.carrierField
  letI : Algebra (LaurentSeries k) D.carrier := D.carrierAlgebra
  letI : FiniteDimensional (LaurentSeries k) D.carrier := D.carrierFinite
  { carrier := D.carrier
    field_carrier := inferInstance
    algebra := inferInstance
    finite_dimensional := inferInstance }

noncomputable def chapter13ArtinSchreierExtensionClass
    (k : Type*) [Field k] (p m : ℕ) [Fact p.Prime] [CharP k p]
    (a : LaurentSeries k)
    (D : Chapter13ArtinSchreierExtensionData k p m a) :
    Chapter13FiniteExtensionClass (LaurentSeries k) :=
  chapter13FiniteExtensionClassOf (chapter13ArtinSchreierExtensionModel k p m a D)

theorem chapter13_artin_schreier_isomorphic_data_give_equal_classes
    (k : Type*) [Field k]
    {p m n : ℕ} [Fact p.Prime] [CharP k p]
    (Dm : Chapter13ArtinSchreierExtensionData k p m
      (chapter13ArtinSchreierRightHandSide k m))
    (Dn : Chapter13ArtinSchreierExtensionData k p n
      (chapter13ArtinSchreierRightHandSide k n))
    (hiso :
      letI := Dm.carrierField
      letI := Dn.carrierField
      letI := Dm.carrierAlgebra
      letI := Dn.carrierAlgebra
      Nonempty (Dm.carrier ≃ₐ[LaurentSeries k] Dn.carrier)) :
    chapter13ArtinSchreierExtensionClass k p m
        (chapter13ArtinSchreierRightHandSide k m) Dm =
      chapter13ArtinSchreierExtensionClass k p n
        (chapter13ArtinSchreierRightHandSide k n) Dn := by
  sorry

/-! The valuation calculations are stated for an arbitrary normalized
additive valuation, making the pole-order obstruction reusable. -/

theorem chapter13_artin_schreier_pole_order_multiple_of_p
    {K Γ : Type*} [Field K] [LinearOrderedAddCommGroupWithTop Γ]
    {p : ℕ} [Fact p.Prime] [CharP K p]
    (v : AddValuation K Γ) (x : K) (hx : v x < 0) :
    v (x ^ p - x) = p • v x := by
  sorry

theorem chapter13_artin_schreier_no_pole_from_integral_input
    {K Γ : Type*} [Field K] [LinearOrderedAddCommGroupWithTop Γ]
    {p : ℕ} [Fact p.Prime] [CharP K p]
    (v : AddValuation K Γ) (x : K) (hx : 0 ≤ v x) :
    0 ≤ v (x ^ p - x) := by
  sorry

theorem chapter13_laurent_series_rhs_has_pole_order
    (k : Type*) [Field k] {p m : ℕ} [Fact p.Prime] [CharP k p]
    (v : AddValuation (LaurentSeries k) (WithTop ℤ))
    (ht : v (chapter13LaurentSeriesUniformizer k) = 1)
    (hm : 0 < m) :
    v (chapter13ArtinSchreierRightHandSide k m) =
      (-(m : ℤ) : WithTop ℤ) := by
  sorry

theorem chapter13_laurent_series_artin_schreier_rhs_not_coboundary
    (k : Type*) [Field k]
    {p m : ℕ} [Fact p.Prime] [CharP k p]
    (v : AddValuation (LaurentSeries k) (WithTop ℤ))
    (ht : v (chapter13LaurentSeriesUniformizer k) = 1)
    (hm : 0 < m) (hmp : ¬p ∣ m) :
    ¬chapter13ArtinSchreierCoboundary
      (LaurentSeries k) p (chapter13ArtinSchreierRightHandSide k m) := by
  sorry

theorem chapter13_artin_schreier_extension_exists
    (k : Type*) [Field k]
    {p m : ℕ} [Fact p.Prime] [CharP k p]
    (v : AddValuation (LaurentSeries k) (WithTop ℤ))
    (ht : v (chapter13LaurentSeriesUniformizer k) = 1)
    (hm : 0 < m) (hmp : ¬p ∣ m) :
    Nonempty (Chapter13ArtinSchreierExtensionData k p m
      (chapter13ArtinSchreierRightHandSide k m)) := by
  sorry

theorem chapter13_artin_schreier_extension_data_is_cyclic_degree_p
    (k : Type*) [Field k] {p m : ℕ} [Fact p.Prime] [CharP k p]
    (a : LaurentSeries k)
    (D : Chapter13ArtinSchreierExtensionData k p m a) :
    letI : Field D.carrier := D.carrierField
    letI : Algebra (LaurentSeries k) D.carrier := D.carrierAlgebra
    letI : FiniteDimensional (LaurentSeries k) D.carrier := D.carrierFinite
    Module.finrank (LaurentSeries k) D.carrier = p ∧
      IsCyclic (D.carrier ≃ₐ[LaurentSeries k] D.carrier) := by
  exact ⟨D.degree, D.cyclic⟩

abbrev Chapter13PositiveNonPIndex (p : ℕ) :=
  {m : ℕ // 0 < m ∧ ¬p ∣ m}

structure Chapter13WildArtinSchreierFamily
    (k : Type*) [Field k] (p : ℕ) [Fact p.Prime] [CharP k p] where
  extension : ∀ m : Chapter13PositiveNonPIndex p,
    Chapter13ArtinSchreierExtensionData k p m.1
      (chapter13ArtinSchreierRightHandSide k m.1)
  pairwise_nonisomorphic :
    ∀ m n : Chapter13PositiveNonPIndex p, m ≠ n →
      letI := (extension m).carrierField
      letI := (extension n).carrierField
      letI := (extension m).carrierAlgebra
      letI := (extension n).carrierAlgebra
      ¬Nonempty ((extension m).carrier ≃ₐ[LaurentSeries k]
        (extension n).carrier)

theorem chapter13_wild_artin_schreier_family_classes_pairwise_distinct
    (k : Type*) [Field k] (p : ℕ) [Fact p.Prime] [CharP k p]
    (F : Chapter13WildArtinSchreierFamily k p)
    (m n : Chapter13PositiveNonPIndex p) (hmn : m ≠ n) :
    chapter13ArtinSchreierExtensionClass k p m.1
        (chapter13ArtinSchreierRightHandSide k m.1) (F.extension m) ≠
      chapter13ArtinSchreierExtensionClass k p n.1
        (chapter13ArtinSchreierRightHandSide k n.1) (F.extension n) := by
  sorry

/- DEPENDENCY_GUESS: The preceding pole-order lemmas and the standard
   Artin--Schreier construction supply this family, but the project has no
   earlier bundled construction of all the generated root fields. -/
theorem chapter13_laurent_series_has_wild_artin_schreier_family
    (k : Type*) [Field k]
    (p : ℕ) [Fact p.Prime] [CharP k p] :
    Nonempty (Chapter13WildArtinSchreierFamily k p) := by
  sorry

theorem chapter13_artin_schreier_same_field_implies_same_line
    (k : Type*) [Field k]
    {p m n : ℕ} [Fact p.Prime] [CharP k p]
    (hm : 0 < m) (hn : 0 < n)
    (hmp : ¬p ∣ m) (hnp : ¬p ∣ n)
    (Dm : Chapter13ArtinSchreierExtensionData k p m
      (chapter13ArtinSchreierRightHandSide k m))
    (Dn : Chapter13ArtinSchreierExtensionData k p n
      (chapter13ArtinSchreierRightHandSide k n))
    (hiso :
      letI := Dm.carrierField
      letI := Dn.carrierField
      letI := Dm.carrierAlgebra
      letI := Dn.carrierAlgebra
      Nonempty (Dm.carrier ≃ₐ[LaurentSeries k] Dn.carrier)) :
    chapter13ArtinSchreierLine (LaurentSeries k) p
        (chapter13ArtinSchreierRightHandSide k m) =
      chapter13ArtinSchreierLine (LaurentSeries k) p
        (chapter13ArtinSchreierRightHandSide k n) := by
  sorry

theorem chapter13_artin_schreier_same_field_gives_scalar_coboundary_relation
    (k : Type*) [Field k]
    {p m n : ℕ} [Fact p.Prime] [CharP k p]
    (hm : 0 < m) (hn : 0 < n)
    (hmp : ¬p ∣ m) (hnp : ¬p ∣ n)
    (Dm : Chapter13ArtinSchreierExtensionData k p m
      (chapter13ArtinSchreierRightHandSide k m))
    (Dn : Chapter13ArtinSchreierExtensionData k p n
      (chapter13ArtinSchreierRightHandSide k n))
    (hiso :
      letI := Dm.carrierField
      letI := Dn.carrierField
      letI := Dm.carrierAlgebra
      letI := Dn.carrierAlgebra
      Nonempty (Dm.carrier ≃ₐ[LaurentSeries k] Dn.carrier)) :
    chapter13ArtinSchreierEquivalent (LaurentSeries k) p
      (chapter13ArtinSchreierRightHandSide k m)
      (chapter13ArtinSchreierRightHandSide k n) := by
  sorry

theorem chapter13_artin_schreier_isomorphism_iff_same_line
    (k : Type*) [Field k]
    {p m n : ℕ} [Fact p.Prime] [CharP k p]
    (hm : 0 < m) (hn : 0 < n)
    (hmp : ¬p ∣ m) (hnp : ¬p ∣ n)
    (Dm : Chapter13ArtinSchreierExtensionData k p m
      (chapter13ArtinSchreierRightHandSide k m))
    (Dn : Chapter13ArtinSchreierExtensionData k p n
      (chapter13ArtinSchreierRightHandSide k n)) :
    (letI := Dm.carrierField
     letI := Dn.carrierField
     letI := Dm.carrierAlgebra
     letI := Dn.carrierAlgebra
     Nonempty (Dm.carrier ≃ₐ[LaurentSeries k] Dn.carrier)) ↔
      chapter13ArtinSchreierLine (LaurentSeries k) p
          (chapter13ArtinSchreierRightHandSide k m) =
        chapter13ArtinSchreierLine (LaurentSeries k) p
          (chapter13ArtinSchreierRightHandSide k n) := by
  sorry

theorem chapter13_artin_schreier_distinct_rhs_has_maximal_pole_order
    (k : Type*) [Field k]
    {p m n : ℕ} [Fact p.Prime] [CharP k p]
    (hm : 0 < m) (hn : 0 < n) (hmp : ¬p ∣ m) (hnp : ¬p ∣ n)
    (hmn : m ≠ n)
    (v : AddValuation (LaurentSeries k) (WithTop ℤ))
    (ht : v (chapter13LaurentSeriesUniformizer k) = 1) :
    v (chapter13ArtinSchreierRightHandSide k n -
        (chapter13ArtinSchreierRightHandSide k m)) =
      (- (max m n : ℤ) : WithTop ℤ) := by
  sorry

theorem chapter13_laurent_series_wild_lines_are_pairwise_distinct
    (k : Type*) [Field k]
    {p m n : ℕ} [Fact p.Prime] [CharP k p]
    (hm : 0 < m) (hn : 0 < n) (hmp : ¬p ∣ m) (hnp : ¬p ∣ n)
    (hmn : m ≠ n)
    (v : AddValuation (LaurentSeries k) (WithTop ℤ))
    (ht : v (chapter13LaurentSeriesUniformizer k) = 1) :
    chapter13ArtinSchreierLine (LaurentSeries k) p
        (chapter13ArtinSchreierRightHandSide k m) ≠
      chapter13ArtinSchreierLine (LaurentSeries k) p
        (chapter13ArtinSchreierRightHandSide k n) := by
  sorry

/-- One fixed finite-residue Laurent-series field has infinitely many
pairwise nonisomorphic separable extensions of degree `p`. -/
theorem chapter13_laurent_series_has_infinitely_many_degree_p_separable_extensions
    (k : Type*) [Field k]
    (p : ℕ) [Fact p.Prime] [CharP k p] :
    Set.Infinite (chapter13DegreeClasses (K := LaurentSeries k) p) := by
  sorry

theorem chapter13_laurent_series_wild_pole_orders_are_unbounded
    (k : Type*) [Field k]
    (p : ℕ) [Fact p.Prime] [CharP k p]
    (v : AddValuation (LaurentSeries k) (WithTop ℤ))
    (ht : v (chapter13LaurentSeriesUniformizer k) = 1) :
    ∀ B : ℕ, ∃ m : ℕ, 0 < m ∧ ¬p ∣ m ∧
      (- (B : ℤ) : WithTop ℤ) >
        v (chapter13ArtinSchreierRightHandSide k m) := by
  sorry

theorem chapter13_laurent_series_is_complete
    (k : Type*) [Field k] :
    CompleteSpace (LaurentSeries k) := by
  exact LastLib.Book02FiniteExtensionsOfLocalFields.Chapter03.chapter03_equal_characteristic_model_is_complete k

theorem chapter13_laurent_series_has_complete_discrete_finite_residue_profile
    (k : Type*) [Field k] [Fintype k] :
    chapter13CompleteFiniteResidueProfile
      (Valued.v : Valuation (LaurentSeries k) ℤᵐ⁰) := by
  sorry

end

end LastLib.Book02FiniteExtensionsOfLocalFields.Chapter13
