import LastLib.Book04AdelesAndIdeles.Chapter12.Core

namespace LastLib.Book04AdelesAndIdeles.Chapter12

noncomputable section

open Set NumberField
open NumberField.InfinitePlace
open scoped BigOperators

/-! # Book 4, Chapter 12, §12.3: A real quadratic field -/

structure Chapter12RealQuadraticFieldData
    (K : Type*) [Field K] [NumberField K] [Algebra ℚ K] where
  sqrtFive : K
  sqrtFive_sq : sqrtFive ^ 2 = 5
  degree_two : Module.finrank ℚ K = 2
  generates : Algebra.adjoin ℚ ({sqrtFive} : Set K) = ⊤
  sigma : Fin 2 → K →ₐ[ℚ] ℝ
  epsilon : (𝓞 K)ˣ
  epsilon_value :
    algebraMap (𝓞 K) K (epsilon : 𝓞 K) = (1 + sqrtFive) / 2
  epsilon_real_value :
    sigma 0 (algebraMap (𝓞 K) K (epsilon : 𝓞 K)) =
      (1 + Real.sqrt 5) / 2
  epsilon_conjugate_value :
    sigma 1 (algebraMap (𝓞 K) K (epsilon : 𝓞 K)) =
      (1 - Real.sqrt 5) / 2
  epsilon_norm :
    Algebra.norm ℚ (algebraMap (𝓞 K) K (epsilon : 𝓞 K)) = -1
  epsilon_signs :
    0 < sigma 0 (algebraMap (𝓞 K) K (epsilon : 𝓞 K)) ∧
      sigma 1 (algebraMap (𝓞 K) K (epsilon : 𝓞 K)) < 0

structure Chapter12RealQuadraticInfinitePortrait
    {K : Type*} [Field K] [NumberField K] [Algebra ℚ K]
    (G : Chapter12RealQuadraticFieldData K) where
  real_place_equiv :
    chapter12InfiniteAdeleRing K ≃+* (ℝ × ℝ)
  all_places_real : ∀ v : InfinitePlace K, IsReal v
  two_real_places : Nat.card (InfinitePlace K) = 2

theorem chapter12_real_quadratic_has_two_real_places
    {K : Type*} [Field K] [NumberField K] [Algebra ℚ K]
    (G : Chapter12RealQuadraticFieldData K) :
    Nonempty (Chapter12RealQuadraticInfinitePortrait G) := by
  sorry

def chapter12RealQuadraticNormOneLine : Set (ℝ × ℝ) :=
  {t | t.1 + t.2 = 0}

theorem chapter12_real_quadratic_norm_one_line_iff (t : ℝ × ℝ) :
    t ∈ chapter12RealQuadraticNormOneLine ↔ t.1 + t.2 = 0 :=
  Iff.rfl

def chapter12RealQuadraticLogAbs (x : ℝ) : ℝ :=
  Real.log |x|

def chapter12RealQuadraticLogUnitVector
    {K : Type*} [Field K] [NumberField K] [Algebra ℚ K]
    (G : Chapter12RealQuadraticFieldData K) : ℝ × ℝ :=
  (chapter12RealQuadraticLogAbs
      (G.sigma 0 (algebraMap (𝓞 K) K (G.epsilon : 𝓞 K))),
    chapter12RealQuadraticLogAbs
      (G.sigma 1 (algebraMap (𝓞 K) K (G.epsilon : 𝓞 K))))

theorem chapter12_real_quadratic_log_unit_vector_formula
    {K : Type*} [Field K] [NumberField K] [Algebra ℚ K]
    (G : Chapter12RealQuadraticFieldData K) :
    chapter12RealQuadraticLogUnitVector G =
      (Real.log ((1 + Real.sqrt 5) / 2),
        -Real.log ((1 + Real.sqrt 5) / 2)) := by
  sorry

theorem chapter12_real_quadratic_log_unit_vector_in_norm_one_line
    {K : Type*} [Field K] [NumberField K] [Algebra ℚ K]
    (G : Chapter12RealQuadraticFieldData K) :
    chapter12RealQuadraticLogUnitVector G ∈ chapter12RealQuadraticNormOneLine := by
  sorry

/-- The lattice generated by powers of the fundamental unit in the norm-one line. -/
def chapter12RealQuadraticLogUnitLattice
    {K : Type*} [Field K] [NumberField K] [Algebra ℚ K]
    (G : Chapter12RealQuadraticFieldData K) : Set (ℝ × ℝ) :=
  Set.range (fun n : ℤ => n • chapter12RealQuadraticLogUnitVector G)

theorem chapter12_real_quadratic_log_unit_powers_are_lattice_points
    {K : Type*} [Field K] [NumberField K] [Algebra ℚ K]
    (G : Chapter12RealQuadraticFieldData K) (n : ℤ) :
    n • chapter12RealQuadraticLogUnitVector G ∈
      chapter12RealQuadraticLogUnitLattice G := by
  exact ⟨n, rfl⟩

def chapter12RealQuadraticLogRatioLattice
    {K : Type*} [Field K] [NumberField K] [Algebra ℚ K]
    (G : Chapter12RealQuadraticFieldData K) : Set ℝ :=
  Set.range (fun n : ℤ => n •
    chapter12RealQuadraticLogAbs
      (G.sigma 0 (algebraMap (𝓞 K) K (G.epsilon : 𝓞 K))))

theorem chapter12_real_quadratic_log_ratio_is_compact_modulo_units
    {K : Type*} [Field K] [NumberField K] [Algebra ℚ K]
    (G : Chapter12RealQuadraticFieldData K) :
    chapter12CompactModulo (chapter12RealQuadraticLogRatioLattice G) := by
  sorry

/-! ## Signs, ordinary classes, and narrow classes -/

def chapter12RealQuadraticSignPattern
    {K : Type*} [Field K] [NumberField K] [Algebra ℚ K]
    (G : Chapter12RealQuadraticFieldData K) (u : (𝓞 K)ˣ) : Fin 2 → Bool :=
  by
    classical
    exact fun i => decide (G.sigma i (algebraMap (𝓞 K) K (u : 𝓞 K)) < 0)

def chapter12RealQuadraticSignPatterns
    {K : Type*} [Field K] [NumberField K] [Algebra ℚ K]
    (G : Chapter12RealQuadraticFieldData K) : Set (Fin 2 → Bool) :=
  Set.range (chapter12RealQuadraticSignPattern G)

theorem chapter12_real_quadratic_unit_sign_patterns_are_adjustable
    {K : Type*} [Field K] [NumberField K] [Algebra ℚ K]
    (G : Chapter12RealQuadraticFieldData K) :
    Function.Surjective (chapter12RealQuadraticSignPattern G) := by
  sorry

def chapter12RealQuadraticSignQuotientData
    {K : Type*} [Field K] [NumberField K] [Algebra ℚ K]
    (G : Chapter12RealQuadraticFieldData K) : Prop :=
  ∀ s : Fin 2 → Bool, ∃ u : (𝓞 K)ˣ,
    chapter12RealQuadraticSignPattern G u = s

theorem chapter12_real_quadratic_narrow_ordinary_distinction_is_real_sign_data
    {K : Type*} [Field K] [NumberField K] [Algebra ℚ K]
    (G : Chapter12RealQuadraticFieldData K) :
    chapter12RealQuadraticSignQuotientData G := by
  exact chapter12_real_quadratic_unit_sign_patterns_are_adjustable G

/-! ## Compact finite unit factors -/

def chapter12FiniteAdeleUnitSet
    {R K : Type*} [CommRing R] [IsDedekindDomain R] [Field K]
    [Algebra R K] [IsFractionRing R K] :
    Set (chapter12FiniteAdeleRing R K) :=
  {x | ∀ v : IsDedekindDomain.HeightOneSpectrum R,
    ∃ u : (v.adicCompletionIntegers K)ˣ,
      algebraMap (v.adicCompletionIntegers K) (v.adicCompletion K) u = x v}

theorem chapter12_finite_adelic_unit_factors_are_compact
    {K : Type*} [Field K] [NumberField K] [Algebra ℚ K] :
    IsCompact (chapter12FiniteAdeleUnitSet (R := 𝓞 K) (K := K)) := by
  sorry

end
end LastLib.Book04AdelesAndIdeles.Chapter12
