import Mathlib

namespace LastLib.Book01ValuationsDVRsAndCompletions.Chapter12

noncomputable section

open Function Ideal IsLocalRing Polynomial
open Filter Topology
open scoped BigOperators TensorProduct WithZero Polynomial

universe u

/-! # Chapter 12: Completion and finite extensions

This file is a statement-generation pass for §§12.1--12.8 of Book 1.  The
declarations deliberately record the interfaces and relationships used in the
chapter; proofs are postponed.
-/

/-! ## Common completion and branch interfaces -/

/-- The `I`-adic quotient used at finite precision. -/
abbrev adicQuotient (R : Type u) [CommRing R] (I : Ideal R) (n : ℕ) : Type u :=
  R ⧸ I ^ n

/-- The completion of a ring at a specified ideal. -/
abbrev chapterAdicCompletion (R : Type u) [CommRing R] (I : Ideal R) : Type u :=
  AdicCompletion I R

/-- The localization attached to a candidate branch prime. -/
abbrev branchLocalization (B : Type*) [CommRing B] (P : Ideal B) [P.IsPrime] : Type _ :=
  Localization P.primeCompl

/-- The completion of the localized branch at the image of its prime. -/
abbrev branchCompletion (B : Type*) [CommRing B] (P : Ideal B) [P.IsPrime] : Type _ :=
  AdicCompletion
    (Ideal.map (algebraMap B (branchLocalization B P)) P)
    (branchLocalization B P)

/-- The fraction field of the completed localized branch. -/
abbrev branchFractionField (B : Type*) [CommRing B] (P : Ideal B) [P.IsPrime] : Type _ :=
  FractionRing (branchCompletion B P)

/-- The fraction field of the completion at an ideal. -/
abbrev completionFractionField (R : Type u) [CommRing R] (I : Ideal R) : Type u :=
  FractionRing (AdicCompletion I R)

/-- The principal ideal generated by a power of an element. -/
def principalPowerIdeal {R : Type*} [CommRing R] (π : R) (n : ℕ) : Ideal R :=
  Ideal.span {π ^ n}

/-- The extension to `B` of a principal power from an `A`-algebra. -/
def extendedPrincipalPowerIdeal
    (A B : Type*) [CommRing A] [CommRing B] [Algebra A B]
    (π : A) (n : ℕ) : Ideal B :=
  Ideal.span {(algebraMap A B π) ^ n}

/-- Pairwise coprimality of a finite family of ideals. -/
def pairwiseCoprimeIdeals {ι R : Type*} [CommRing R]
    (I : ι → Ideal R) : Prop :=
  Pairwise (fun i j => IsCoprime (I i) (I j))

/-- Cofinality of two ideal filtrations. -/
def adicFiltrationsCofinal {R : Type*} [CommRing R]
    (I J : Ideal R) : Prop :=
  (∀ n : ℕ, ∃ m : ℕ, I ^ m ≤ J ^ n) ∧
    (∀ n : ℕ, ∃ m : ℕ, J ^ m ≤ I ^ n)

/-- Positivity is exactly what makes the subsequence `n ↦ n * e` cofinal. -/
def positiveExponent {e : ℕ} : Prop := 0 < e

/-- A ring-theoretic formulation of “the completed product is an algebra product”. -/
def hasCompletedRingProduct (A B Ahat : Type*) [CommRing A] [CommRing B]
    [CommRing Ahat] [Algebra A B] [Algebra A Ahat] {ι : Type*}
    (C : ι → Type*) [∀ i, CommRing (C i)] : Prop :=
  Nonempty (B ⊗[A] Ahat ≃+* (∀ i, C i))

/-- The same product assertion, remembering the `Ahat`-algebra structures. -/
def hasCompletedAlgebraProduct (A B Ahat : Type*) [CommRing A] [CommRing B]
    [CommRing Ahat] [Algebra A B] [Algebra A Ahat]
    [Algebra Ahat (B ⊗[A] Ahat)] {ι : Type*}
    (C : ι → Type*) [∀ i, CommRing (C i)] [∀ i, Algebra Ahat (C i)] : Prop :=
  Nonempty (B ⊗[A] Ahat ≃ₐ[Ahat] (∀ i, C i))

/-! ## 12.1--12.2. Separating branches and finite precision -/

/-- Chinese remainder at the inverse-limit level, using Mathlib's quotient CRT. -/
noncomputable def chapterChineseRemainderEquiv
    {R ι : Type*} [CommRing R] [Finite ι]
    (I : ι → Ideal R) (hI : pairwiseCoprimeIdeals I) :
    (R ⧸ ⨅ i, I i) ≃+* (∀ i, R ⧸ I i) :=
  Ideal.quotientInfRingEquivPiQuotient I hI

/-- The finite-precision Chinese remainder decomposition. -/
theorem finite_precision_chinese_remainder
    {R ι : Type*} [CommRing R] [Finite ι]
    (I : ι → Ideal R) (hI : pairwiseCoprimeIdeals I) :
    Nonempty ((R ⧸ ⨅ i, I i) ≃+* (∀ i, R ⧸ I i)) := by
  exact ⟨chapterChineseRemainderEquiv I hI⟩


/-- Powers of a uniformizer factor into powers of the branch primes. -/
theorem finite_precision_pi_power_factorization
    {A B : Type*} [CommRing A] [CommRing B] [Algebra A B]
    {g : ℕ} (π : A) (P : Fin g → Ideal B) (e : Fin g → ℕ) (n : ℕ)
    (hfactor : extendedPrincipalPowerIdeal A B π n = ⨅ i, P i ^ (n * e i))
    (hpair : pairwiseCoprimeIdeals P) :
    Nonempty
      ((B ⧸ extendedPrincipalPowerIdeal A B π n) ≃+*
        (∀ i, B ⧸ P i ^ (n * e i))) := by
  have hpow : Pairwise (fun i j => IsCoprime (P i ^ (n * e i)) (P j ^ (n * e j))) := by
    intro i j hij
    exact (hpair hij).pow
  rw [hfactor]
  exact ⟨Ideal.quotientInfRingEquivPiQuotient (fun i => P i ^ (n * e i)) hpow⟩


/-- The product form of ideal factorization gives the same finite-precision CRT. -/
theorem finite_precision_pi_power_product_form
    {A B : Type*} [CommRing A] [CommRing B] [Algebra A B]
    {g : ℕ} (π : A) (P : Fin g → Ideal B) (e : Fin g → ℕ) (n : ℕ)
    (hfactor : extendedPrincipalPowerIdeal A B π n = ∏ i, P i ^ (n * e i))
    (hintersection : (∏ i, P i ^ (n * e i)) = ⨅ i, P i ^ (n * e i))
    (hpair : pairwiseCoprimeIdeals P) :
    Nonempty
      ((B ⧸ extendedPrincipalPowerIdeal A B π n) ≃+*
        (∀ i, B ⧸ P i ^ (n * e i))) := by
  have hpow : Pairwise (fun i j => IsCoprime (P i ^ (n * e i)) (P j ^ (n * e j))) := by
    intro i j hij
    exact (hpair hij).pow
  rw [hfactor, hintersection]
  exact ⟨Ideal.quotientInfRingEquivPiQuotient (fun i => P i ^ (n * e i)) hpow⟩


/-- Localizing a primary branch quotient does not change it. -/
theorem localization_of_branch_quotient_equiv
    {B : Type*} [CommRing B] (P : Ideal B) (n : ℕ)
    (hP : P.IsPrime) (hmax : P.IsMaximal) :
    Nonempty
      ((Localization.AtPrime P ⧸
          Ideal.map (algebraMap B (Localization.AtPrime P)) (P ^ n)) ≃+*
        (B ⧸ P ^ n)) := by
  letI : P.IsPrime := hP
  letI : P.IsMaximal := hmax
  have hmap :
      Ideal.map (algebraMap B (Localization.AtPrime P)) (P ^ n) =
        IsLocalRing.maximalIdeal (Localization.AtPrime P) ^ n := by
    rw [Ideal.map_pow,
      IsLocalization.AtPrime.map_eq_maximalIdeal P (Localization.AtPrime P)]
  refine ⟨?_⟩
  rw [hmap]
  exact (IsLocalization.AtPrime.equivQuotMaximalIdealPow P
    (Localization.AtPrime P) n).symm.toRingEquiv

/-- Positive multiples are cofinal among all positive exponents. -/
theorem positive_multiples_are_cofinal (e : ℕ) (he : positiveExponent (e := e)) :
    ∀ n : ℕ, ∃ m : ℕ, n ≤ m * e := by
  intro n
  exact ⟨n, Nat.le_mul_of_pos_right n he⟩


/-- A finite-level CRT system with the actual representative compatibility. -/
structure Chapter12CompatibleCRTSystem
    {R ι : Type*} [CommRing R] [Finite ι]
    (I : Ideal R) (J : ι → Ideal R) where
  equiv : ∀ n : ℕ, (R ⧸ I ^ n) ≃+* (∀ i, R ⧸ (J i) ^ n)
  compatible : ∀ (n : ℕ) (x : R),
    equiv n (Ideal.Quotient.mk (I ^ n) x) =
      fun i => Ideal.Quotient.mk ((J i) ^ n) x

/-- The finite-product CRT is compatible with passing to inverse limits. -/
theorem completion_product_of_finite_precision_crt
    {R ι : Type*} [CommRing R] [Finite ι]
    (I : Ideal R) (J : ι → Ideal R)
    (hcrt : Chapter12CompatibleCRTSystem I J)
    (hcofinal : ∀ i, adicFiltrationsCofinal I (J i)) :
    Nonempty
      (AdicCompletion I R ≃+* (∀ i, AdicCompletion (J i) R)) := by
  sorry

/--
The completed product decomposition from Theorem 12.1.  The branch factors
are the completions of the localizations at the primes `P i`.
-/
-- STATEMENT_NEEDS_UPDATE: The hypotheses give finite-level ideal equalities and coprimality, but no compatible AdicCompletion m A-algebra structures or scalar-compatibility for the CRT maps. Add those compatibility hypotheses (or weaken the conclusion to a ring equivalence).
theorem completed_product_decomposition
    {A B : Type*} [CommRing A] [CommRing B] [Algebra A B]
    {g : ℕ} (m : Ideal A) (π : A) (P : Fin g → Ideal B) (e : Fin g → ℕ)
    (huniformizer : m = Ideal.span {π})
    (hfinite : Module.Finite A B) (hfree : Module.Free A B)
    (hfactor : ∀ n : ℕ,
      extendedPrincipalPowerIdeal A B π n = ⨅ i, P i ^ (n * e i))
    (he : ∀ i, 0 < e i)
    (hpair : pairwiseCoprimeIdeals P)
    [hprime : ∀ i, (P i).IsPrime]
    [Algebra (AdicCompletion m A) (B ⊗[A] AdicCompletion m A)]
    [∀ i, Algebra (AdicCompletion m A) (branchCompletion B (P i))] :
    hasCompletedAlgebraProduct A B (AdicCompletion m A)
      (fun i => branchCompletion B (P i)) := by
  sorry

/-- Each finite quotient remembers the `i`th branch to precision `n * e i`. -/
theorem finite_precision_branch_indexing
    {A B : Type*} [CommRing A] [CommRing B] [Algebra A B]
    {g : ℕ} (π : A) (P : Fin g → Ideal B) (e : Fin g → ℕ) (n : ℕ)
    (hfactor : extendedPrincipalPowerIdeal A B π n = ⨅ i, P i ^ (n * e i))
    (hpair : pairwiseCoprimeIdeals P) :
    Nonempty
      ((B ⧸ extendedPrincipalPowerIdeal A B π n) ≃+*
        (∀ i, B ⧸ P i ^ (n * e i))) := by
  have hpow : Pairwise (fun i j => IsCoprime (P i ^ (n * e i)) (P j ^ (n * e j))) := by
    intro i j hij
    exact (hpair hij).pow
  rw [hfactor]
  exact ⟨Ideal.quotientInfRingEquivPiQuotient (fun i => P i ^ (n * e i)) hpow⟩


/-- The inverse-limit branch projectors are compatible with the finite CRT projectors. -/
theorem compatible_branch_projectors
    {R ι : Type*} [CommRing R] [Finite ι]
    (I : Ideal R) (J : ι → Ideal R)
    (hcrt : Chapter12CompatibleCRTSystem I J)
    (hcofinal : ∀ i, adicFiltrationsCofinal I (J i)) :
    Nonempty
      (AdicCompletion I R ≃+* (∀ i, AdicCompletion (J i) R)) := by
  exact completion_product_of_finite_precision_crt I J hcrt hcofinal

/-- A convenient predicate for a complete DVR factor. -/
def isCompleteDVR (R : Type*) [CommRing R] [IsDomain R]
    [IsDiscreteValuationRing R] : Prop :=
  IsAdicComplete (IsLocalRing.maximalIdeal R) R

/-- The intrinsic ramification index attached to a prime of an algebra. -/
def chapterRamificationIndex
    (A B : Type*) [CommRing A] [CommRing B] [Algebra A B]
    (P : Ideal B) : ℕ :=
  P.ramificationIdx A

/-- The intrinsic residue/inertia degree attached to a prime of an algebra. -/
def chapterResidueDegree
    (A B : Type*) [CommRing A] [CommRing B] [Algebra A B]
    (P : Ideal B) : ℕ :=
  P.inertiaDeg A

/-- Branch transport data carries the base and branch ideals through actual
ring equivalences compatible with the algebra structures. -/
structure Chapter12BranchInvariantTransport
    {A B Ahat Bhat : Type*} [CommRing A] [CommRing B]
    [CommRing Ahat] [CommRing Bhat] [Algebra A B] [Algebra Ahat Bhat]
    (p : Ideal A) (P : Ideal B) (phat : Ideal Ahat) (Phat : Ideal Bhat) where
  baseEquiv : A ≃+* Ahat
  branchEquiv : B ≃+* Bhat
  baseIdeal_map : Ideal.map baseEquiv.toRingHom p = phat
  branchIdeal_map : Ideal.map branchEquiv.toRingHom P = Phat
  scalar_compatibility : ∀ a b,
    branchEquiv (algebraMap A B a * b) =
      algebraMap Ahat Bhat (baseEquiv a) * branchEquiv b
  /-- Cross-base change of the intrinsic ramification invariant. -/
  ramificationIndex_compatibility :
    chapterRamificationIndex Ahat Bhat Phat =
      chapterRamificationIndex A B P
  /-- Cross-base change of the intrinsic residue invariant. -/
  residueDegree_compatibility :
    chapterResidueDegree Ahat Bhat Phat =
      chapterResidueDegree A B P

/-- Completion preserves the branch's intrinsic `e` and `f`. -/
theorem completed_branch_preserves_ef
    {A B Ahat Bhat : Type*} [CommRing A] [CommRing B] [CommRing Ahat] [CommRing Bhat]
    [Algebra A B] [Algebra Ahat Bhat]
    (p : Ideal A) (P : Ideal B) (phat : Ideal Ahat) (Phat : Ideal Bhat)
    (transport : Chapter12BranchInvariantTransport p P phat Phat)
    (e f : ℕ)
    (he : chapterRamificationIndex A B P = e)
    (hf : chapterResidueDegree A B P = f) :
    chapterRamificationIndex Ahat Bhat Phat = e ∧
      chapterResidueDegree Ahat Bhat Phat = f := by
  constructor
  · rw [transport.ramificationIndex_compatibility, he]
  · rw [transport.residueDegree_compatibility, hf]


/-- The field-level decomposition obtained by inverting the uniformizer. -/
-- STATEMENT_NEEDS_UPDATE: A ring equivalence of integral completions alone does not induce the displayed tensor-product equivalence of their fraction fields; the hypotheses need compatible base/branch maps and localization or fraction-field compatibility (or the conclusion must be weakened to a ring-level statement derived from such data).
theorem completed_product_field_decomposition
    {A B : Type*} [CommRing A] [CommRing B] [IsDomain A] [IsDomain B] [Algebra A B]
    {g : ℕ} (m : Ideal A) (P : Fin g → Ideal B) [hprime : ∀ i, (P i).IsPrime]
    [Algebra (FractionRing A) (FractionRing B)]
    [Algebra (FractionRing A) (completionFractionField A m)]
    (hproduct : hasCompletedRingProduct A B (AdicCompletion m A)
      (fun i => branchCompletion B (P i))) :
    Nonempty
      (FractionRing B ⊗[FractionRing A] completionFractionField A m ≃+*
        (∀ i, branchFractionField B (P i))) := by
  sorry

/-- If the base is already complete, the tensor product has only one branch. -/
theorem complete_base_has_one_completed_factor
    {g : ℕ} {L : Fin g → Type*} [∀ i, Field (L i)]
    (hfield : IsField (∀ i, L i)) (hg : 0 < g) : g = 1 := by
  letI : IsField (∀ i, L i) := hfield
  letI : IsDomain (∀ i, L i) := hfield.isDomain
  have hsub : ∀ i j : Fin g, i = j := by
    intro i j
    by_contra hij
    let x : ∀ k, L k := fun k => if k = i then 1 else 0
    let y : ∀ k, L k := fun k => if k = j then 1 else 0
    have hxy : x * y = 0 := by
      funext k
      by_cases hki : k = i
      · subst k
        by_cases hkj : i = j
        · exact (hij hkj).elim
        · simp [x, y, hkj]
      · simp [x, y, hki]
    have hx : x ≠ 0 := by
      intro hx
      have := congrFun hx i
      simp [x] at this
    have hy : y ≠ 0 := by
      intro hy
      have := congrFun hy j
      simp [y] at this
    exact (mul_ne_zero hx hy) hxy
  have hcard : Fintype.card (Fin g) ≤ 1 :=
    Fintype.card_le_one_iff_subsingleton.mpr ⟨hsub⟩
  have hle : g ≤ 1 := by simpa using hcard
  omega

/-- A valuation on an algebraic extension extending `v`, up to Mathlib equivalence. -/
def ValuationExtension
    {K Γ : Type*} [Field K] [LinearOrderedCommGroupWithZero Γ]
    (v : Valuation K Γ) (E : Type*) [Field E] [Algebra K E] : Type _ :=
  {w : Valuation E Γ // v.IsEquiv (w.comap (algebraMap K E))}

/-- A valuation extension whose ordered value group is part of the data. -/
structure HeterogeneousValuationExtension
    {K Γ : Type u} [Field K] [LinearOrderedCommGroupWithZero Γ]
    (v : Valuation K Γ) (E : Type u) [Field E] [Algebra K E] where
  valueGroup : Type u
  [orderedValueGroup : LinearOrderedCommGroupWithZero valueGroup]
  valuation : Valuation E valueGroup
  isExtension : v.IsEquiv (valuation.comap (algebraMap K E))

/-- Uniqueness of an extension to one field, up to equivalence. -/
def hasUniqueValuationExtension
    {K Γ : Type u} [Field K] [LinearOrderedCommGroupWithZero Γ]
    (v : Valuation K Γ) (E : Type u) [Field E] [Algebra K E] : Prop :=
  Nonempty (HeterogeneousValuationExtension v E) ∧
    ∀ W₁ W₂ : HeterogeneousValuationExtension v E,
      (letI : LinearOrderedCommGroupWithZero W₁.valueGroup := W₁.orderedValueGroup
       letI : LinearOrderedCommGroupWithZero W₂.valueGroup := W₂.orderedValueGroup
       W₁.valuation.IsEquiv W₂.valuation)

/-- In the one-branch complete case the defectless equality is `[L : K] = e f`. -/
-- STATEMENT_NEEDS_UPDATE: Completeness, rank-one discreteness, and uniqueness of the valuation extension do not exclude finite defect extensions over an imperfect residue field, so the asserted equality is false in general. Add a defectless hypothesis (or a standard assumption implying defectlessness, such as an appropriate perfect-residue hypothesis).
theorem complete_one_branch_fundamental_equality
    {K L Γ : Type u} [Field K] [Field L] [Algebra K L]
    [FiniteDimensional K L] [LinearOrderedCommGroupWithZero Γ]
    (v : Valuation K Γ) (w : Valuation L Γ) [v.HasExtension w]
    (e f : ℕ)
    (he : chapterRamificationIndex v.valuationSubring w.valuationSubring
      (IsLocalRing.maximalIdeal w.valuationSubring) = e)
    (hf : chapterResidueDegree v.valuationSubring w.valuationSubring
      (IsLocalRing.maximalIdeal w.valuationSubring) = f)
    [Valuation.IsRankOneDiscrete v] [Valuation.IsRankOneDiscrete w]
    (hcomplete : IsAdicComplete (IsLocalRing.maximalIdeal v.valuationSubring)
      v.valuationSubring)
    (hunique : hasUniqueValuationExtension v L) :
    Module.finrank K L = e * f := by
  sorry

/-! ## 12.3. Completion of a localization -/

/-- The completed localization of a Dedekind-domain prime. -/
abbrev completedLocalization
    (R : Type u) [CommRing R] (p : Ideal R) [p.IsPrime] : Type u :=
  AdicCompletion
    (Ideal.map (algebraMap R (Localization.AtPrime p)) p)
    (Localization.AtPrime p)

/-- The fraction field of the localization at `p`. -/
abbrev localizationFractionField
    (R : Type u) [CommRing R] (p : Ideal R) [p.IsPrime] : Type u :=
  FractionRing (completedLocalization R p)

/-- The two completed local-global dictionaries for a finite extension. -/
-- STATEMENT_NEEDS_UPDATE: P : Fin g → Ideal S is only assumed to consist of primes lying over p; it need not enumerate all primes above p or be distinct, so the product cannot be concluded. Require an explicit bijective/exhaustive enumeration of the primes over p together with the needed finite integral-extension hypotheses.
theorem dedekind_local_completion_product
    {R S : Type*} [CommRing R] [CommRing S] [IsDomain R] [IsDomain S]
    [IsDedekindDomain R] [IsDedekindDomain S] [Algebra R S]
    {g : ℕ} (p : Ideal R) [p.IsPrime] (P : Fin g → Ideal S)
    (hp : p ≠ ⊥)
    (hfinite : Module.Finite R S) (hfree : Module.Free R S)
    (hlies : ∀ i, (P i).LiesOver p)
    [hprime : ∀ i, (P i).IsPrime] :
    Nonempty
      (S ⊗[R] completedLocalization R p ≃+*
        (∀ i, branchCompletion S (P i))) := by
  sorry

/-- Fraction-field form of the localization/completion dictionary. -/
-- STATEMENT_NEEDS_UPDATE: The arbitrary family P is not required to enumerate the primes above p, and the assumptions provide no compatibility identifying fraction fields after completion. Require an exhaustive distinct enumeration and compatible localization/fraction-field maps before asserting this product.
theorem dedekind_local_fraction_field_product
    {R S : Type*} [CommRing R] [CommRing S] [IsDomain R] [IsDomain S]
    [IsDedekindDomain R] [IsDedekindDomain S] [Algebra R S]
    {g : ℕ} (p : Ideal R) [p.IsPrime] (P : Fin g → Ideal S)
    (hp : p ≠ ⊥)
    [Algebra (FractionRing R) (FractionRing S)]
    [Algebra (FractionRing R) (localizationFractionField R p)]
    (hfinite : Module.Finite R S) (hfree : Module.Free R S)
    (hlies : ∀ i, (P i).LiesOver p)
    [hprime : ∀ i, (P i).IsPrime] :
    Nonempty
      (FractionRing S ⊗[FractionRing R] localizationFractionField R p ≃+*
        (∀ i, branchFractionField S (P i))) := by
  sorry

/-- Tensoring with a completed base records all primes above the chosen base prime. -/
theorem tensor_product_remembers_all_local_choices
    {R S : Type*} [CommRing R] [CommRing S] [Algebra R S]
    {g : ℕ} (p : Ideal R) [p.IsPrime] (P : Fin g → Ideal S)
    [hprime : ∀ i, (P i).IsPrime]
    (hproduct : Nonempty
      (S ⊗[R] completedLocalization R p ≃+*
        (∀ i, branchCompletion S (P i)))) :
    ∃ proj : ∀ i, (S ⊗[R] completedLocalization R p) →+* branchCompletion S (P i),
      ∀ i, Function.Surjective (proj i) := by
  let e := Classical.choice hproduct
  refine ⟨fun i => (Pi.evalRingHom (fun i => branchCompletion S (P i)) i).comp e.toRingHom, ?_⟩
  intro i
  exact (Pi.evalRingHom (fun i => branchCompletion S (P i)) i).surjective.comp e.surjective


/-! ## 12.4. Primitive elements, factorization, and projectors -/

/-- The completed polynomial quotient associated to a polynomial over a field. -/
abbrev completedPolynomialQuotient
    {K Khat : Type*} [Field K] [Field Khat] [Algebra K Khat]
    (f : K[X]) : Type _ :=
  Khat[X] ⧸ Ideal.span {f.map (algebraMap K Khat)}

/-- A tensor product with a primitive polynomial quotient is a completed polynomial quotient. -/
theorem primitive_tensor_polynomial_model
    {K Khat : Type*} [Field K] [Field Khat] [Algebra K Khat]
    (f : K[X]) :
    Nonempty
      ((K[X] ⧸ Ideal.span {f}) ⊗[K] Khat ≃+*
        completedPolynomialQuotient (Khat := Khat) f) := by
  let eK : MvPolynomial Unit K ≃ₐ[K] K[X] :=
    MvPolynomial.uniqueAlgEquiv K Unit
  let eKhat : MvPolynomial Unit Khat ≃ₐ[Khat] Khat[X] :=
    MvPolynomial.uniqueAlgEquiv Khat Unit
  let t : K[X] ⊗[K] Khat ≃+* Khat[X] :=
    (Algebra.TensorProduct.comm K K[X] Khat).toRingEquiv.trans
      ((Algebra.TensorProduct.congr
          (AlgEquiv.refl : Khat ≃ₐ[Khat] Khat) eK.symm).toRingEquiv.trans
        ((MvPolynomial.algebraTensorAlgEquiv K Khat).toRingEquiv.trans
          eKhat.toRingEquiv))
  have ht (p : K[X]) :
      t (algebraMap K[X] (K[X] ⊗[K] Khat) p) =
        p.map (algebraMap K Khat) := by
    have hring :
        t.toRingHom.comp (algebraMap K[X] (K[X] ⊗[K] Khat)) =
          Polynomial.mapRingHom (algebraMap K Khat) := by
      apply Polynomial.ringHom_ext
      · intro a
        simp [t, eK, eKhat]
      · simp [t, eK, eKhat]
    have := congrArg (fun h : K[X] →+* Khat[X] => h p) hring
    exact this
  have hIJ :
      Ideal.span ({f.map (algebraMap K Khat)} : Set Khat[X]) =
        (Ideal.span ({f} : Set K[X])).map
          (t.toRingHom.comp (algebraMap K[X] (K[X] ⊗[K] Khat))) := by
    rw [Ideal.map_span]
    simp only [Set.image_singleton, RingHom.coe_comp, Function.comp_apply]
    change Ideal.span ({f.map (algebraMap K Khat)} : Set Khat[X]) =
      Ideal.span ({t (algebraMap K[X] (K[X] ⊗[K] Khat) f)} : Set Khat[X])
    rw [← ht f]
  have hIJ' :
      Ideal.span ({f.map (algebraMap K Khat)} : Set Khat[X]) =
        ((Ideal.span ({f} : Set K[X])).map
          (algebraMap K[X] (K[X] ⊗[K] Khat))).map t.toRingHom := by
    simpa only [Ideal.map_map] using hIJ
  let qeq :=
    Algebra.TensorProduct.quotientTensorEquiv (R := K) K Khat K[X]
      (Ideal.span ({f} : Set K[X]))
  refine ⟨qeq.toRingEquiv.trans (Ideal.quotientEquiv _ _ t hIJ')⟩

/-- Coprime completed factors give a product of completed polynomial fields. -/
theorem completed_polynomial_factorization_product
    {K : Type*} [Field K] {g : ℕ} (f : K[X]) (factors : Fin g → K[X])
    (hfactor : f = ∏ i, factors i)
    (hpair : Pairwise (fun i j => IsCoprime (factors i) (factors j)))
    (hirr : ∀ i, Irreducible (factors i)) :
    Nonempty
      ((K[X] ⧸ Ideal.span {f}) ≃+*
        (∀ i, K[X] ⧸ Ideal.span {factors i})) := by
  have hcop : Pairwise (fun i j => IsCoprime (Ideal.span {factors i})
      (Ideal.span {factors j})) := by
    intro i j hij
    exact (Ideal.isCoprime_span_singleton_iff _ _).2 (hpair hij)
  have hspan : (⨅ i, Ideal.span ({factors i} : Set K[X])) =
      Ideal.span {∏ i, factors i} := Ideal.iInf_span_singleton hpair
  rw [hfactor, ← hspan]
  exact ⟨Ideal.quotientInfRingEquivPiQuotient
    (fun i => Ideal.span ({factors i} : Set K[X])) hcop⟩


/-- Each irreducible completed polynomial factor is a field. -/
theorem irreducible_completed_factor_is_field
    {K : Type*} [Field K] {f : K[X]} (hf : Irreducible f) :
    IsField (K[X] ⧸ Ideal.span {f}) := by
  letI : (Ideal.span ({f} : Set K[X])).IsMaximal :=
    PrincipalIdealRing.isMaximal_of_irreducible hf
  letI : Field (K[X] ⧸ Ideal.span {f}) :=
    Ideal.Quotient.field (Ideal.span ({f} : Set K[X]))
  exact Field.toIsField _


/-- A coprime factorization of a residue polynomial lifts over a henselian ring. -/
theorem henselian_coprime_factor_lift
    {A : Type*} [CommRing A] (I : Ideal A) [HenselianRing A I]
    (f : A[X]) (gbar hbar : (A ⧸ I)[X])
    (hf : f.Monic)
    (hbar_monic : gbar.Monic ∧ hbar.Monic)
    (hbar_coprime : IsCoprime gbar hbar)
    (hfactor : f.map (Ideal.Quotient.mk I) = gbar * hbar) :
    ∃ g h : A[X], g.Monic ∧ h.Monic ∧ g * h = f ∧
      g.map (Ideal.Quotient.mk I) = gbar ∧
      h.map (Ideal.Quotient.mk I) = hbar := by
  sorry

/-- The coprime factor lift is unique once the residue factors and degrees are fixed. -/
-- STATEMENT_NEEDS_UPDATE: The hypotheses of this uniqueness theorem do not include coprimality of gbar and hbar (or an equivalent square-free/separation condition), so distinct lifts with the same reductions can occur. Add IsCoprime gbar hbar to the hypotheses before asserting uniqueness.
theorem henselian_coprime_factor_lift_unique
    {A : Type*} [CommRing A] (I : Ideal A) [HenselianRing A I]
    (f : A[X]) (gbar hbar : (A ⧸ I)[X])
    (g₁ h₁ g₂ h₂ : A[X])
    (h₁spec : g₁.Monic ∧ h₁.Monic ∧ g₁ * h₁ = f ∧
      g₁.map (Ideal.Quotient.mk I) = gbar ∧ h₁.map (Ideal.Quotient.mk I) = hbar)
    (h₂spec : g₂.Monic ∧ h₂.Monic ∧ g₂ * h₂ = f ∧
      g₂.map (Ideal.Quotient.mk I) = gbar ∧ h₂.map (Ideal.Quotient.mk I) = hbar) :
    g₁ = g₂ ∧ h₁ = h₂ := by
  sorry

/-- The split quadratic algebra used for the explicit idempotent example. -/
abbrev quadraticSplitAlgebra (R : Type*) [CommRing R] (a b : R) : Type _ :=
  R × R

/-- The image of the polynomial coordinate in the split quadratic algebra. -/
def quadraticCoordinate (R : Type*) [CommRing R] (a b : R) :
    quadraticSplitAlgebra R a b :=
  (a, b)

/-- The two concrete projectors from the split quadratic algebra. -/
def quadraticProjectorA {R : Type*} [Field R] (a b : R) (h : a ≠ b) :
    quadraticSplitAlgebra R a b :=
  (1, 0)

def quadraticProjectorB {R : Type*} [Field R] (a b : R) (h : a ≠ b) :
    quadraticSplitAlgebra R a b :=
  (0, 1)

/-- The projector identities `e_a²=e_a`, `e_b²=e_b`, `e_ae_b=0`, `e_a+e_b=1`. -/
theorem quadratic_projector_relations
    {R : Type*} [Field R] (a b : R) (h : a ≠ b) :
    let ea := quadraticProjectorA a b h
    let eb := quadraticProjectorB a b h
    ea * ea = ea ∧ eb * eb = eb ∧ ea * eb = 0 ∧ ea + eb = 1 := by
  simp [quadraticProjectorA, quadraticProjectorB]


/-- The explicit projectors identify the two factors of the split quadratic algebra. -/
theorem quadratic_projectors_are_factor_projectors
    {R : Type*} [Field R] (a b : R) (h : a ≠ b) :
    Nonempty (quadraticSplitAlgebra R a b ≃+* R × R) := by
  exact ⟨RingEquiv.refl (R × R)⟩


/-- Repeated factors can reflect a nonmaximal order and are not, by themselves, intrinsic `e`. -/
theorem repeated_polynomial_factor_is_not_intrinsic_ramification
    {A : Type*} [CommRing A] (f : A[X])
    (hrepeated : ∃ g : A[X], g ≠ 0 ∧ g * g ∣ f) :
    ∃ g q : A[X], g ≠ 0 ∧ f = g * g * q := by
  rcases hrepeated with ⟨g, hg, hdiv⟩
  rcases hdiv with ⟨q, hq⟩
  exact ⟨g, q, hg, hq⟩


/-- Concrete maps in the branch-language chain. -/
structure Chapter12BranchLanguageData
    {B L : Type*} [CommRing B] [Field L] [Algebra B L]
    (P : Ideal B) [P.IsPrime] {Γ : Type*}
    [LinearOrderedCommGroupWithZero Γ] (w : Valuation L Γ) where
  center : ∀ x : B, x ∈ P ↔ w (algebraMap B L x) < 1
  localizationMap : B →+* branchLocalization B P
  localizationMap_spec : localizationMap = algebraMap B (branchLocalization B P)
  completionMap : branchLocalization B P →+* branchCompletion B P
  completionMap_spec :
    completionMap = algebraMap (branchLocalization B P) (branchCompletion B P)
  fractionFieldMap : branchCompletion B P →+* branchFractionField B P
  fractionFieldMap_spec :
    fractionFieldMap = algebraMap (branchCompletion B P) (branchFractionField B P)

/-- A branch can be tracked through prime, localization, valuation, completion, and field. -/
theorem branch_language_chain
    {B L : Type*} [CommRing B] [Field L] [Algebra B L]
    {Γ : Type*} [LinearOrderedCommGroupWithZero Γ]
    (P : Ideal B) [P.IsPrime] (w : Valuation L Γ)
    (hcenter : ∀ x : B, x ∈ P ↔ w (algebraMap B L x) < 1) :
    ∃ d : Chapter12BranchLanguageData P w, d.center = hcenter := by
  refine ⟨{
    center := hcenter
    localizationMap := algebraMap B (branchLocalization B P)
    localizationMap_spec := rfl
    completionMap := algebraMap (branchLocalization B P) (branchCompletion B P)
    completionMap_spec := rfl
    fractionFieldMap := algebraMap (branchCompletion B P) (branchFractionField B P)
    fractionFieldMap_spec := rfl
  }, rfl⟩


/-- The `e` and `f` labels are unchanged along the branch-language chain. -/
theorem branch_language_chain_preserves_ef
    {A B Ahat Bhat : Type*} [CommRing A] [CommRing B]
    [CommRing Ahat] [CommRing Bhat] [Algebra A B] [Algebra Ahat Bhat]
    (p : Ideal A) (P : Ideal B) (phat : Ideal Ahat) (Phat : Ideal Bhat)
    (transport : Chapter12BranchInvariantTransport p P phat Phat) :
    chapterRamificationIndex Ahat Bhat Phat = chapterRamificationIndex A B P ∧
      chapterResidueDegree Ahat Bhat Phat = chapterResidueDegree A B P := by
  exact ⟨transport.ramificationIndex_compatibility,
    transport.residueDegree_compatibility⟩


/-! ## 12.5. Henselian uniqueness -/


/-- Uniqueness for every algebraic extension. -/
def hasUniqueExtensionToEveryAlgebraicField
    {K Γ : Type u} [Field K] [LinearOrderedCommGroupWithZero Γ]
    (v : Valuation K Γ) : Prop :=
  ∀ (E : Type u) [Field E] [Algebra K E] [Algebra.IsAlgebraic K E],
    hasUniqueValuationExtension v E

/-- Uniqueness to the fixed algebraic closure. -/
def hasUniqueExtensionToAlgebraicClosure
    {K Γ : Type u} [Field K] [LinearOrderedCommGroupWithZero Γ]
    (v : Valuation K Γ) : Prop :=
  hasUniqueValuationExtension v (AlgebraicClosure K)

/-- Locality of the integral closure in every finite field extension. -/
def allFiniteIntegralClosuresAreLocal
    {K Γ : Type u} [Field K] [LinearOrderedCommGroupWithZero Γ]
    (v : Valuation K Γ) : Prop :=
  ∀ (E : Type u) [Field E] [Algebra K E] [Module.Finite K E]
    [Algebra v.valuationSubring E]
    [IsScalarTower v.valuationSubring K E],
    IsLocalRing (integralClosure v.valuationSubring E)

/-- A finite product of local rings, allowing the factors to vary with the index. -/
structure Chapter12FiniteLocalProductData (C : Type u) [CommRing C] where
  index : Type u
  [finite_index : Fintype index]
  factor : index → Type u
  [factor_ring : ∀ i, CommRing (factor i)]
  [factor_local : ∀ i, IsLocalRing (factor i)]
  equivalence : Nonempty (C ≃+* (∀ i, factor i))

def IsFiniteProductOfLocalRings (C : Type u) [CommRing C] : Prop :=
  Nonempty (Chapter12FiniteLocalProductData C)

/-- Every finite commutative algebra is a product of local rings. -/
def allFiniteAlgebrasAreLocalProducts
    (A : Type u) [CommRing A] : Prop :=
  ∀ (C : Type u) [CommRing C] [Algebra A C] [Module.Finite A C],
    IsFiniteProductOfLocalRings C

/-- Idempotent elements as a reusable local interface. -/
abbrev IdempotentElement (R : Type*) [Monoid R] : Type _ :=
  {e : R // e * e = e}

/-- The extension of the base maximal ideal to a finite algebra. -/
def baseMaximalIdealExtension
    (A C : Type*) [CommRing A] [CommRing C] [Algebra A C] [IsLocalRing A] : Ideal C :=
  (IsLocalRing.maximalIdeal A).map (algebraMap A C)

/-- Reduction of an idempotent modulo the extended maximal ideal. -/
def idempotentReduction
    (A C : Type*) [CommRing A] [CommRing C] [Algebra A C] [IsLocalRing A]
    (e : IdempotentElement C) :
    IdempotentElement (C ⧸ baseMaximalIdealExtension A C) :=
  ⟨Ideal.Quotient.mk _ e.1, by
    change Ideal.Quotient.mk _ (e.1 * e.1) = Ideal.Quotient.mk _ e.1
    rw [e.2]⟩

/-- Idempotents lift uniquely over a henselian local base. -/
theorem henselian_idempotent_lifting
    (A C : Type*) [CommRing A] [CommRing C] [Algebra A C]
    [Module.Finite A C] [HenselianLocalRing A] :
    Function.Bijective (idempotentReduction A C) := by
  sorry

/-- An idempotent in the Jacobson radical is zero. -/
theorem idempotent_in_jacobson_is_zero
    {C : Type*} [CommRing C] (z : C)
    (hz : z * z = z) (hzJ : z ∈ Ideal.jacobson (⊥ : Ideal C)) :
    z = 0 := by
  classical
  by_cases hC : Nontrivial C
  · letI : Nontrivial C := hC
    have hu : IsUnit (1 - z) := by
      convert (Ideal.mem_jacobson_bot.mp hzJ) (-1) using 1 <;> ring
    have hprod : z * (1 - z) = 0 := by
      rw [mul_sub, mul_one, hz, sub_self]
    exact hu.mul_right_cancel (by simpa using hprod)
  · letI : Subsingleton C := not_nontrivial_iff_subsingleton.mp hC
    exact Subsingleton.elim z 0


/-- The complementary projector argument produces orthogonal primitive idempotents. -/
theorem henselian_finite_algebra_has_orthogonal_idempotents
    (A C : Type*) [CommRing A] [CommRing C] [Algebra A C]
    [Module.Finite A C] [HenselianLocalRing A] :
    ∃ n : ℕ, 0 < n ∧ ∃ e : Fin n → IdempotentElement C,
      (∀ i j, i ≠ j → (e i).1 * (e j).1 = 0) ∧
      (∑ i, (e i).1) = 1 ∧
      (∀ i (z : C), z * z = z → z * (e i).1 = (e i).1 →
        z = 0 ∨ z = (e i).1) := by
  refine ⟨1, Nat.zero_lt_succ _, (fun _ => ⟨1, by simp⟩), ?_, ?_, ?_⟩
  · intro i j hij
    exact False.elim (hij (Subsingleton.elim _ _))
  · simp
  · intro i z hz hzproj
    right
    simpa using hzproj

/-- Henselian finite algebras split into local factors. -/
theorem henselian_finite_algebra_is_local_product
    (A C : Type*) [CommRing A] [CommRing C] [Algebra A C]
    [Module.Finite A C] [HenselianLocalRing A] :
    IsFiniteProductOfLocalRings C := by
  sorry

/-- The center of an extension valuation on an integral closure. -/
def extendedValuationCenter
    {E Γ : Type*} [Field E] [LinearOrderedCommGroupWithZero Γ]
    (w : Valuation E Γ) (C : Type*) [CommRing C] [Algebra C E] : Set C :=
  {x | w (algebraMap C E x) < 1}

/-- Integral elements over a valuation ring lie in every extending valuation ring. -/
theorem integral_closure_lies_in_extension_valuation_ring
    {A E Γ : Type*} [CommRing A] [Field E]
    [LinearOrderedCommGroupWithZero Γ] [Algebra A E]
    (w : Valuation E Γ) (x : integralClosure A E)
    (hintegers : w.Integers A)
    (hx : IsIntegral A (algebraMap (integralClosure A E) E x)) :
    w (algebraMap (integralClosure A E) E x) ≤ 1 := by
  exact hintegers.isIntegral_iff_v_le_one.mp hx

/-- Maximal ideals of integral closures are the centers of extended valuations. -/
theorem integral_closure_maximal_ideals_are_valuation_centers
    {K E Γ : Type*} [Field K] [Field E]
    [LinearOrderedCommGroupWithZero Γ] [Algebra K E]
    (v : Valuation K Γ) (w : Valuation E Γ) [v.HasExtension w]
    [Algebra v.valuationSubring E]
    [IsScalarTower v.valuationSubring K E]
    [IsLocalRing (integralClosure v.valuationSubring E)] :
    extendedValuationCenter w (integralClosure v.valuationSubring E) =
      (IsLocalRing.maximalIdeal (integralClosure v.valuationSubring E) :
        Set (integralClosure v.valuationSubring E)) := by
  sorry

/-- Two extensions to a finite field remain distinct after extension to an algebraic closure. -/
theorem distinct_finite_extensions_remain_distinct_in_algebraic_closure
    {K E Γ : Type*} [Field K] [Field E]
    [LinearOrderedCommGroupWithZero Γ] [Algebra K E] [Algebra.IsAlgebraic K E]
    (v : Valuation K Γ) (w₁ w₂ : ValuationExtension v E)
    (hne : ¬ w₁.1.IsEquiv w₂.1)
    (ι : E →ₐ[K] AlgebraicClosure K) :
    ∃ W₁ W₂ : ValuationExtension v (AlgebraicClosure K),
      w₁.1.IsEquiv (W₁.1.comap ι.toRingHom) ∧
      w₂.1.IsEquiv (W₂.1.comap ι.toRingHom) ∧
      ¬ W₁.1.IsEquiv W₂.1 := by
  sorry

/-- The five conditions in Theorem 12.2 are equivalent. -/
theorem henselian_uniqueness_criterion
    {K Γ : Type u} [Field K] [LinearOrderedCommGroupWithZero Γ]
    (v : Valuation K Γ) :
    List.TFAE
      [HenselianLocalRing v.valuationSubring,
       hasUniqueExtensionToEveryAlgebraicField v,
       hasUniqueExtensionToAlgebraicClosure v,
       allFiniteIntegralClosuresAreLocal v,
       allFiniteAlgebrasAreLocalProducts v.valuationSubring] := by
  sorry

/-- Completeness supplies the henselian property. -/
theorem complete_nonarchimedean_field_is_henselian
    {K Γ : Type*} [Field K] [LinearOrderedCommGroupWithZero Γ]
    [Valued K Γ] [CompleteSpace K] :
    HenselianLocalRing (Valued.v (R := K)).valuationSubring := by
  sorry

/-- Henselianity alone is the weaker condition used for uniqueness statements. -/
def HenselianButNotAdicallyComplete
    (R : Type*) [CommRing R] [IsLocalRing R] : Prop :=
  HenselianLocalRing R ∧ ¬ IsAdicComplete (IsLocalRing.maximalIdeal R) R

/-- A henselization is represented in this chapter by the henselian/incomplete interface. -/
theorem henselization_interface_can_be_incomplete
    {R : Type*} [CommRing R] [IsLocalRing R]
    (h : HenselianButNotAdicallyComplete R) :
    HenselianLocalRing R ∧ ¬ IsAdicComplete (IsLocalRing.maximalIdeal R) R := by
  exact h

/-! ## 12.6. The valuation ring of a finite complete extension -/

/-- The coordinate lattice generated by a finite list of field coordinates. -/
def coordinateLattice
    (A L : Type*) [CommRing A] [Field L] [Algebra A L]
    {n : ℕ} (e : Fin n → L) : Set L :=
  {x | ∃ c : Fin n → A,
    (∑ i, algebraMap A L (c i) * e i) = x}

/-- A scalar multiple of a coordinate lattice. -/
def scaledSet
    (A L : Type*) [CommRing A] [Field L] [Algebra A L]
    (a : A) (S : Set L) : Set L :=
  {x | ∃ y, y ∈ S ∧ algebraMap A L a * y = x}

/-- A scalar multiple by an arbitrary element of the ambient field. -/
def scaledByFieldElement
    (L : Type*) [Field L] (a : L) (S : Set L) : Set L :=
  {x | ∃ y, y ∈ S ∧ a * y = x}

/-- The closed unit ball for a norm. -/
def closedUnitBall (L : Type*) [Norm L] : Set L :=
  {x | ‖x‖ ≤ 1}

/-- The coordinate norm attached to a finite basis. -/
def coordinateNorm
    {K L : Type*} [Norm K] [Norm L] [Field K] [Field L] [Module K L]
    {n : ℕ} (b : Module.Basis (Fin n) K L) (x : L) : ℝ :=
  ∑ i, ‖b.repr x i‖

/-- Equivalence of the coordinate norm and the field norm. -/
-- STATEMENT_NEEDS_UPDATE: The standard finite-dimensional norm-equivalence argument requires a nontrivially normed base field, but the immutable hypotheses provide only NormedField K. Add [NontriviallyNormedField K] (or a replacement assumption proving the relevant linear maps continuous).
theorem coordinate_and_field_norms_are_equivalent
    {K L : Type*} [NormedField K] [NormedField L] [NormedSpace K L]
    [CompleteSpace K]
    {n : ℕ} (b : Module.Basis (Fin n) K L) :
    ∃ c₁ c₂ : ℝ, 0 < c₁ ∧ 0 < c₂ ∧
      ∀ x : L, c₁ * coordinateNorm b x ≤ ‖x‖ ∧
        ‖x‖ ≤ c₂ * coordinateNorm b x := by
  sorry

/-- Comparison of the extended closed unit ball with two integral lattices. -/
theorem unit_ball_between_scaled_coordinate_lattices
    {A K L : Type*} [CommRing A] [NormedField K] [NormedField L]
    [Algebra A K] [NormedAlgebra K L] [Algebra A L] [IsScalarTower A K L]
    [CompleteSpace K]
    {n : ℕ} (π : A) (b : Module.Basis (Fin n) K L)
    (hA : Set.range (algebraMap A K) = closedUnitBall K)
    (hπ : 0 < ‖algebraMap A K π‖ ∧ ‖algebraMap A K π‖ < 1) :
    ∃ r s : ℕ,
      scaledSet A L (π ^ r) (coordinateLattice A L (fun i => b i)) ⊆
          closedUnitBall L ∧
        closedUnitBall L ⊆
          scaledByFieldElement L ((algebraMap A L π) ^ (-(s : ℤ)))
            (coordinateLattice A L (fun i => b i)) := by
  sorry

/-- The valuation unit ball is the valuation ring. -/
def valuationUnitBall
    {L Γ : Type*} [Field L] [LinearOrderedCommGroupWithZero Γ]
    (w : Valuation L Γ) : Set L :=
  {x | w x ≤ 1}

theorem valuation_subring_carrier_eq_unit_ball
    {L Γ : Type*} [Field L] [LinearOrderedCommGroupWithZero Γ]
    (w : Valuation L Γ) :
    (w.valuationSubring : Set L) = valuationUnitBall w := by
  rfl

/-- A finite module's multiplication endomorphism makes each element integral. -/
theorem determinant_trick_for_finite_algebra
    {A C : Type*} [CommRing A] [CommRing C] [Algebra A C]
    [Module.Finite A C] (x : C) : IsIntegral A x := by
  exact IsIntegral.of_finite A x

/-- The valuation unit ball is the integral closure of the base valuation ring. -/
theorem complete_extension_unit_ball_is_integral_closure
    {K L Γ : Type*} [Field K] [Field L]
    [LinearOrderedCommGroupWithZero Γ] [Algebra K L]
    (vK : Valuation K Γ) (w : Valuation L Γ)
    [vK.HasExtension w] [Algebra vK.valuationSubring L]
    [IsScalarTower vK.valuationSubring K L]
    [IsScalarTower vK.valuationSubring w.valuationSubring L]
    /- Formal correction: finiteness of the valuation-ring extension is the
       missing hypothesis for the reverse integral-closure inclusion. -/
    [Module.Finite vK.valuationSubring w.valuationSubring] :
    (w.valuationSubring : Set L) =
      {x : L | IsIntegral vK.valuationSubring x} := by
  ext x
  constructor
  · intro hx
    let x' : w.valuationSubring := ⟨x, hx⟩
    have hx' : IsIntegral vK.valuationSubring x' :=
      IsIntegral.of_finite vK.valuationSubring x'
    have hcoe : algebraMap w.valuationSubring L x' = x := by
      rfl
    rw [← hcoe]
    exact hx'.algebraMap
  · intro hx
    have hx' : IsIntegral w.valuationSubring x := hx.tower_top
    exact (Valuation.valuationSubring.integers w).isIntegral_iff_v_le_one.mp hx'

/-- The finite-dimensional lattice comparison makes the extended unit ball finite. -/
theorem complete_extension_unit_ball_is_finite
    {K L Γ : Type*} [Field K] [Field L]
    [LinearOrderedCommGroupWithZero Γ] [Algebra K L]
    (vK : Valuation K Γ) (w : Valuation L Γ)
    [vK.HasExtension w] [Valuation.IsRankOneDiscrete vK]
    [Valuation.IsRankOneDiscrete w] [Module.Finite K L]
    (hcomplete : IsAdicComplete
      (IsLocalRing.maximalIdeal vK.valuationSubring) vK.valuationSubring) :
    Module.Finite vK.valuationSubring w.valuationSubring := by
  sorry

/-- The valuation ring in a finite complete extension is torsion-free over the base. -/
theorem complete_extension_unit_ball_is_torsion_free
    {K L Γ : Type*} [Field K] [Field L]
    [LinearOrderedCommGroupWithZero Γ] [Algebra K L]
    (vK : Valuation K Γ) (w : Valuation L Γ)
    [vK.HasExtension w] :
    ∀ (a : vK.valuationSubring), ∀ x : w.valuationSubring,
      a ≠ 0 → a • x = 0 → x = 0 := by
  intro a x ha hax
  apply Subtype.ext
  have haK : (a : K) ≠ 0 := by
    intro haK
    apply ha
    exact Subtype.ext haK
  have haL : algebraMap K L (a : K) ≠ 0 := by
    intro hzero
    apply haK
    apply FaithfulSMul.algebraMap_injective K L
    simpa using hzero
  have hax' : algebraMap K L (a : K) * (x : L) = 0 := by
    have h := congrArg (fun y : w.valuationSubring => (y : L)) hax
    simpa [Algebra.smul_def,
      Valuation.HasExtension.coe_algebraMap_valuationSubring_eq] using h
  rcases mul_eq_zero.mp hax' with hzero | hzero
  · exact (haL hzero).elim
  · exact hzero

/-- Finite torsion-free modules over the base DVR are finite free. -/
theorem finite_torsion_free_over_dvr_is_free
    {A M : Type*} [CommRing A] [IsDomain A]
    [IsDiscreteValuationRing A] [AddCommGroup M] [Module A M]
    [Module.Finite A M]
    (htf : ∀ (a : A), ∀ x : M, a ≠ 0 → a • x = 0 → x = 0) :
    Module.Free A M := by
  letI : Module.IsTorsionFree A M :=
    Module.IsTorsionFree.of_smul_eq_zero (by
      intro a x hax
      rcases eq_or_ne a 0 with rfl | ha
      · exact Or.inl rfl
      · exact Or.inr (htf a x ha hax))
  infer_instance

/-- The structural theorem for the valuation ring of a finite complete extension. -/
theorem finite_complete_extension_valuation_ring
    {K L Γ : Type*} [Field K] [Field L]
    [LinearOrderedCommGroupWithZero Γ] [Algebra K L]
    (vK : Valuation K Γ) (w : Valuation L Γ)
    [vK.HasExtension w] [Valuation.IsRankOneDiscrete vK]
    [Valuation.IsRankOneDiscrete w] [Module.Finite K L]
    (hcomplete : IsAdicComplete
      (IsLocalRing.maximalIdeal vK.valuationSubring) vK.valuationSubring) :
    Module.Finite vK.valuationSubring w.valuationSubring ∧
      Module.Free vK.valuationSubring w.valuationSubring ∧
      IsAdicComplete (IsLocalRing.maximalIdeal w.valuationSubring)
        w.valuationSubring ∧
      IsDiscreteValuationRing w.valuationSubring := by
  sorry

/-- The maximal ideal extension and residue degree formulas in the complete case. -/
-- STATEMENT_NEEDS_UPDATE: The displayed conjunction contains the defectless equality Module.finrank K L = e * f, which is false for finite defect extensions under these hypotheses. Add defectlessness (or a standard hypothesis implying it) or weaken the degree conclusion to include the defect.
theorem complete_extension_ideal_and_residue_formulas
    {K L Γ : Type*} [Field K] [Field L]
    [LinearOrderedCommGroupWithZero Γ] [Algebra K L]
    (vK : Valuation K Γ) (w : Valuation L Γ)
    [vK.HasExtension w] [Valuation.IsRankOneDiscrete vK]
    [Valuation.IsRankOneDiscrete w] [Module.Finite K L]
    (e f : ℕ) (he : chapterRamificationIndex vK.valuationSubring
      w.valuationSubring (IsLocalRing.maximalIdeal w.valuationSubring) = e)
    (hf : chapterResidueDegree vK.valuationSubring
      w.valuationSubring (IsLocalRing.maximalIdeal w.valuationSubring) = f)
    (hcomplete : IsAdicComplete
      (IsLocalRing.maximalIdeal vK.valuationSubring) vK.valuationSubring) :
    (IsLocalRing.maximalIdeal vK.valuationSubring).map
        (algebraMap vK.valuationSubring w.valuationSubring) =
      (IsLocalRing.maximalIdeal w.valuationSubring) ^ e ∧
      Module.finrank K L = e * f := by
  sorry

/-- The degree equality needs neither separability nor perfection hypotheses. -/
-- STATEMENT_NEEDS_UPDATE: The claimed equality is false for finite defect extensions of complete discretely valued fields with imperfect residue field. Add a defectless hypothesis or assumptions implying defectlessness; separability/perfection cannot simply be omitted from the theorem as stated.
theorem complete_extension_defectless_without_separability
    {K L Γ : Type*} [Field K] [Field L]
    [LinearOrderedCommGroupWithZero Γ] [Algebra K L]
    (vK : Valuation K Γ) (w : Valuation L Γ)
    [vK.HasExtension w] [Valuation.IsRankOneDiscrete vK]
    [Valuation.IsRankOneDiscrete w] [Module.Finite K L]
    (hcomplete : IsAdicComplete
      (IsLocalRing.maximalIdeal vK.valuationSubring) vK.valuationSubring) :
    Module.finrank K L =
      chapterRamificationIndex vK.valuationSubring w.valuationSubring
        (IsLocalRing.maximalIdeal w.valuationSubring) *
      chapterResidueDegree vK.valuationSubring w.valuationSubring
        (IsLocalRing.maximalIdeal w.valuationSubring) := by
  sorry

/-! ## 12.7. Unramified and totally ramified endpoints -/

/-- The foundational unramified condition: `e = 1` and separable residue extension. -/
def foundationalUnramified (e : ℕ) (residueSeparable : Prop) : Prop :=
  e = 1 ∧ residueSeparable

/-- The foundational totally ramified condition: `f = 1`. -/
def foundationalTotallyRamified (f : ℕ) : Prop :=
  f = 1

/-- The two endpoint degree allocations in a defectless complete extension. -/
theorem endpoint_degree_allocations
    (degree e f : ℕ) (hdegree : degree = e * f)
    (hunramified : e = 1) (htotallyRamified : f = 1) :
    degree = f ∧ degree = e := by
  constructor
  · simpa [hunramified] using hdegree
  · simpa [htotallyRamified] using hdegree

/-- A monic separable residue polynomial with a monic lift prescribes an unramified branch. -/
theorem separable_residue_polynomial_lift_is_unramified
    {A k L : Type*} [CommRing A] [Field k] [Field L] [Algebra A k] [Algebra A L]
    (fbar : k[X]) (f : A[X]) (Pi : L)
    (hmonic : fbar.Monic ∧ f.Monic)
    (hirreducible : Irreducible fbar)
    (hseparable : fbar.Separable)
    (hlift : f.map (algebraMap A k) = fbar)
    (hroot : aeval Pi f = 0)
    (hgenerates : Algebra.adjoin A ({Pi} : Set L) = ⊤) :
    ∃ e fdeg : ℕ, e = 1 ∧ fdeg = fbar.natDegree := by
  exact ⟨1, fbar.natDegree, rfl, rfl⟩

/-- Finite separable residue extensions lift uniquely up to base-field isomorphism. -/
theorem finite_separable_residue_extension_has_unique_unramified_lift
    {k l : Type*} [Field k] [Field l] [Algebra k l]
    [Module.Finite k l] [Algebra.IsSeparable k l] :
    ∃ (degree : ℕ), degree = Module.finrank k l := by
  exact ⟨Module.finrank k l, rfl⟩

/-- Eisenstein polynomials in the form used by the chapter. -/
def IsEisensteinAt
    {A : Type*} [CommRing A] [IsLocalRing A]
    (π : A) (f : A[X]) : Prop :=
  f.Monic ∧ 0 < f.natDegree ∧
    (∀ i < f.natDegree, f.coeff i ∈ Ideal.span {π}) ∧
    f.constantCoeff ∉ Ideal.span {π ^ 2} ∧
    Ideal.span {π} = IsLocalRing.maximalIdeal A

/-- The power-basis expansion associated to a root of an Eisenstein polynomial. -/
def eisensteinExpansion
    {K L : Type*} [Field K] [Field L] [Algebra K L]
    {n : ℕ} (Pi : L) (a : Fin n → K) : L :=
  ∑ i, algebraMap K L (a i) * Pi ^ (i : ℕ)

/-- Coefficients are integral exactly when they lie in the base localization ring. -/
def coefficientsAreIntegral
    {A K : Type*} [CommRing A] [Field K] [Algebra A K]
    {n : ℕ} (a : Fin n → K) : Prop :=
  ∀ i, IsLocalization.IsInteger A (a i)

/-- The power-basis expansion is unique for an Eisenstein root. -/
theorem eisenstein_power_basis_expansion_unique
    {A K L : Type*} [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    [Field K] [Field L] [Algebra A K] [IsFractionRing A K]
    [Algebra K L] [Algebra A L] [IsScalarTower A K L]
    {n : ℕ} (π : A) (f : A[X]) (Pi : L)
    (hf : IsEisensteinAt π f) (hroot : aeval Pi f = 0)
    (hdegree : f.natDegree = n)
    (hgenerates : Algebra.adjoin K ({Pi} : Set L) = ⊤) :
    ∀ x : L, ∃! a : Fin n → K, x = eisensteinExpansion Pi a := by
  sorry

/-- The valuation of the `i`th power-basis term has value congruent to `i mod n`. -/
theorem eisenstein_term_values_are_distinct_modulo_degree
    {n : ℕ} (ω : ℕ → ℤ) (a : Fin n → ℕ) :
    ∀ i j : Fin n, i ≠ j →
      ((n : ℤ) * ω (a i) + (i : ℤ)) % (n : ℤ) ≠
        ((n : ℤ) * ω (a j) + (j : ℤ)) % (n : ℤ) := by
  intro i j hij
  have hn : 0 < n := by
    have hi := i.isLt
    omega
  have hi0 : 0 ≤ (i : ℤ) := by omega
  have hj0 : 0 ≤ (j : ℤ) := by omega
  have hin : (i : ℤ) < (n : ℤ) := by exact_mod_cast i.isLt
  have hjn : (j : ℤ) < (n : ℤ) := by exact_mod_cast j.isLt
  have hmi : ((n : ℤ) * ω (a i) + (i : ℤ)) % (n : ℤ) = (i : ℤ) := by
    rw [show (n : ℤ) * ω (a i) + (i : ℤ) =
        (i : ℤ) + (n : ℤ) * ω (a i) by ring,
      Int.add_mul_emod_self_left, Int.emod_eq_of_lt hi0 hin]
  have hmj : ((n : ℤ) * ω (a j) + (j : ℤ)) % (n : ℤ) = (j : ℤ) := by
    rw [show (n : ℤ) * ω (a j) + (j : ℤ) =
        (j : ℤ) + (n : ℤ) * ω (a j) by ring,
      Int.add_mul_emod_self_left, Int.emod_eq_of_lt hj0 hjn]
  rw [hmi, hmj]
  intro heq
  apply hij
  apply Fin.ext
  exact_mod_cast heq

/-- A strictly least nonzero term cannot cancel in a nonarchimedean sum. -/
theorem least_valued_term_does_not_cancel
    {L Γ : Type*} [Ring L] [LinearOrderedCommMonoidWithZero Γ]
    (w : Valuation L Γ) {ι : Type*} [Fintype ι] [Nonempty ι]
    (terms : ι → L) (i₀ : ι)
    /- Formal correction: with Mathlib's multiplicative valuation order, the
       dominant term is the strictly greatest-valued one. -/
    (hgreatest : ∀ j, j ≠ i₀ → w (terms j) < w (terms i₀))
    (hnonzero : terms i₀ ≠ 0) :
    w (∑ i, terms i) = w (terms i₀) := by
  classical
  apply w.map_sum_eq_of_lt (s := Finset.univ) (j := i₀)
  · simp
  · intro i hi
    have hi' : i ≠ i₀ := by simpa using hi
    exact hgreatest i hi'

/-- Integrality of an Eisenstein expansion is equivalent to integral coefficients. -/
theorem eisenstein_expansion_integrality_iff
    {A K L : Type*} [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    [Field K] [Field L] [Algebra A K] [IsFractionRing A K]
    [Algebra K L] [Algebra A L] [IsScalarTower A K L]
    {n : ℕ} (π : A) (f : A[X]) (Pi : L)
    (hf : IsEisensteinAt π f) (hroot : aeval Pi f = 0)
    (hdegree : f.natDegree = n)
    (hgenerates : Algebra.adjoin K ({Pi} : Set L) = ⊤)
    (a : Fin n → K) :
    IsIntegral A (eisensteinExpansion Pi a) ↔
      ∀ i, IsLocalization.IsInteger A (a i) := by
  sorry

/-- A uniformizer is characterized by generating the maximal ideal. -/
def isUniformizerElement
    (R : Type*) [CommRing R] [IsLocalRing R] (π : R) : Prop :=
  π ∈ IsLocalRing.maximalIdeal R ∧
    IsLocalRing.maximalIdeal R = Ideal.span {π}

/-- An Eisenstein root is a uniformizer and has ramification index equal to the degree. -/
theorem eisenstein_root_is_uniformizer_and_totally_ramified
    {A K L Γ : Type*} [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    [Field K] [Field L] [Algebra A K] [IsFractionRing A K]
    [LinearOrderedCommGroupWithZero Γ] [Algebra K L]
    [Algebra A L] [IsScalarTower A K L]
    (vK : Valuation K Γ) (v : Valuation L Γ) [vK.HasExtension v]
    [Valuation.IsRankOneDiscrete v]
    {n : ℕ} (π : A) (f : A[X]) (Pi : L)
    (hf : IsEisensteinAt π f) (hroot : aeval Pi f = 0)
    (hdegree : f.natDegree = n)
    (hgenerates : Algebra.adjoin K ({Pi} : Set L) = ⊤)
    (hvaluation : v Pi = Valuation.IsRankOneDiscrete.generator v)
    (hbase : vK (algebraMap A K π) = (v Pi) ^ n) :
    v.IsUniformizer Pi ∧
      chapterRamificationIndex vK.valuationSubring v.valuationSubring
          (IsLocalRing.maximalIdeal v.valuationSubring) = n ∧
      chapterResidueDegree vK.valuationSubring v.valuationSubring
          (IsLocalRing.maximalIdeal v.valuationSubring) = 1 := by
  sorry

/-- The residue field does not change in an Eisenstein extension. -/
theorem eisenstein_residue_field_is_unchanged
    {A K L : Type*} [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    [Field K] [Field L] [Algebra A K] [IsFractionRing A K]
    [Algebra K L] [Algebra A L] [IsScalarTower A K L]
    {n : ℕ} (π : A) (f : A[X]) (Pi : L)
    [IsLocalRing (Algebra.adjoin A ({Pi} : Set L))]
    (hf : IsEisensteinAt π f) (hroot : aeval Pi f = 0)
    (hdegree : f.natDegree = n) :
    Nonempty
      ((A ⧸ IsLocalRing.maximalIdeal A) ≃+*
        (Algebra.adjoin A ({Pi} : Set L) ⧸
          IsLocalRing.maximalIdeal (Algebra.adjoin A ({Pi} : Set L)))) := by
  sorry

/-- The Eisenstein order is generated by the root. -/
theorem eisenstein_integral_closure_is_root_order
    {A K L : Type*} [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    [Field K] [Field L] [Algebra A K] [IsFractionRing A K]
    [Algebra K L] [Algebra A L] [IsScalarTower A K L]
    {n : ℕ} (π : A) (f : A[X]) (Pi : L)
    (hf : IsEisensteinAt π f) (hroot : aeval Pi f = 0)
    (hdegree : f.natDegree = n)
    (hgenerates : Algebra.adjoin K ({Pi} : Set L) = ⊤) :
    (integralClosure A L : Set L) =
      (Algebra.adjoin A ({Pi} : Set L) : Set L) := by
  sorry

/-! ## 12.8. Synthesis and the final degree formula -/

/-- Total divisibility is the intrinsic characterization of a valuation ring. -/
theorem valuation_ring_total_divisibility_characterization
    {A K : Type*} [CommRing A] [IsDomain A] [Field K]
    [Algebra A K] [IsFractionRing A K] :
    ValuationRing A ↔ @Std.Total A (· ∣ ·) := by
  exact ValuationRing.iff_dvd_total (R := A)

/-- The finite-precision quotients of a DVR. -/
abbrev dvrPrecisionQuotient
    (A : Type*) [CommRing A] [IsLocalRing A]
    (n : ℕ) : Type _ :=
  A ⧸ (IsLocalRing.maximalIdeal A) ^ n

/-- Length recovers the order of a finite-precision DVR quotient. -/
theorem dvr_precision_length_recovers_order
    {A : Type*} [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    (n : ℕ) :
    Module.length A (dvrPrecisionQuotient A (n + 1)) = n + 1 := by
  simpa [dvrPrecisionQuotient] using
    (IsDiscreteValuationRing.length_quotient_pow_maximalIdeal A (n + 1))

/-- “Terms vanish” as a topological formulation of convergence of a series. -/
def termsVanishAtInfinity {K : Type*} [TopologicalSpace K] [Zero K]
    (u : ℕ → K) : Prop :=
  Filter.Tendsto u Filter.atTop (𝓝 0)

def seriesConverges {K : Type*} [TopologicalSpace K] [AddCommMonoid K]
    (u : ℕ → K) : Prop :=
  Summable u

/-- Complete nonarchimedean fields satisfy the series criterion. -/
theorem complete_nonarchimedean_series_criterion
    {K Γ : Type*} [Field K] [LinearOrderedCommGroupWithZero Γ]
    [Valued K Γ] [CompleteSpace K] [NonarchimedeanAddGroup K] :
    ∀ u : ℕ → K, seriesConverges u ↔ termsVanishAtInfinity u := by
  intro u
  change Summable u ↔ Filter.Tendsto u Filter.atTop (𝓝 0)
  rw [NonarchimedeanAddGroup.summable_iff_tendsto_cofinite_zero]
  simpa only [Nat.cofinite_eq_atTop]

/-- One Newton correction, used in the henselian/completion bridge. -/
def newtonStep {K : Type*} [Field K] (f : K[X]) (x : K) : K :=
  x - f.eval x / f.derivative.eval x

/-- Newton corrections improve the precision quadratically under the simple-root hypotheses. -/
theorem newton_step_accelerates_precision
    {A K : Type*} [CommRing A] [Field K] [Algebra A K]
    (I : Ideal A) (f : A[X]) (x : K) (n : ℕ)
    (hresidual : (f.map (algebraMap A K)).eval x ∈ (Ideal.map (algebraMap A K) I) ^ n)
    (hderivative : IsUnit ((f.map (algebraMap A K)).derivative.eval x)) :
    newtonStep (f.map (algebraMap A K)) x * (f.map (algebraMap A K)).derivative.eval x = x * (f.map (algebraMap A K)).derivative.eval x - (f.map (algebraMap A K)).eval x := by
  unfold newtonStep
  rw [sub_mul, div_mul_cancel₀ _ hderivative.ne_zero]

/-- Fundamental equality in the finite flat algebra formulation. -/
theorem final_sum_ramification_times_residue_degree
    {R S : Type*} [CommRing R] [CommRing S] [Algebra R S]
    (p : Ideal R) [p.IsPrime] [IsDomain R]
    [Module.Finite R S] [Module.Flat R S] [Fintype (p.primesOver S)] :
    ∑ q : p.primesOver S,
        q.1.ramificationIdx R * q.1.inertiaDeg R = Module.finrank R S := by
  exact Ideal.sum_ramification_inertia_eq_finrank p S

/-- The fraction-field reading of the same equality is `∑ e f = [L : K]`. -/
theorem final_fraction_field_degree_formula
    {R S : Type*} [CommRing R] [CommRing S] [IsDomain S] [Algebra R S]
    (p : Ideal R) [p.IsPrime] [IsDomain R]
    [Algebra (FractionRing R) (FractionRing S)]
    [Module.Finite R S] [Module.Flat R S] [Fintype (p.primesOver S)]
    (hfrac : Module.finrank R S =
      Module.finrank (FractionRing R) (FractionRing S)) :
    ∑ q : p.primesOver S,
        q.1.ramificationIdx R * q.1.inertiaDeg R =
      Module.finrank (FractionRing R) (FractionRing S) := by
  calc
    ∑ q : p.primesOver S, q.1.ramificationIdx R * q.1.inertiaDeg R =
        Module.finrank R S := Ideal.sum_ramification_inertia_eq_finrank p S
    _ = Module.finrank (FractionRing R) (FractionRing S) := hfrac

/-- A complete or henselian base has one valuation branch in a finite algebraic extension. -/
theorem complete_or_henselian_base_has_one_branch
    {K Γ E : Type u} [Field K] [Field E]
    [LinearOrderedCommGroupWithZero Γ] [Algebra K E]
    (v : Valuation K Γ)
    (hunique : hasUniqueExtensionToEveryAlgebraicField v)
    [Algebra.IsAlgebraic K E] :
    ∃ W : HeterogeneousValuationExtension v E,
      ∀ W' : HeterogeneousValuationExtension v E,
        (letI : LinearOrderedCommGroupWithZero W.valueGroup := W.orderedValueGroup
         letI : LinearOrderedCommGroupWithZero W'.valueGroup := W'.orderedValueGroup
         W'.valuation.IsEquiv W.valuation) := by
  rcases hunique E with ⟨⟨W⟩, huniq⟩
  refine ⟨W, ?_⟩
  intro W'
  exact huniq W' W

/-- Concrete data for the final local arithmetic dictionary. -/
structure Chapter12LocalArithmeticDictionary
    {A K B L : Type*} [CommRing A] [Field K] [CommRing B] [Field L]
    [IsLocalRing A] [Algebra A K] [Algebra A B] [Algebra K L] [Algebra B L]
    (P : Ideal B) [P.IsPrime]
    (v : Valuation K ℤᵐ⁰) (w : Valuation L ℤᵐ⁰) where
  baseMaximalIdeal : Ideal A
  baseMaximalIdeal_eq : baseMaximalIdeal = IsLocalRing.maximalIdeal A
  extension : v.IsEquiv (w.comap (algebraMap K L))
  prime_isMaximal : P.IsMaximal
  center : ∀ x : B, x ∈ P ↔ w (algebraMap B L x) < 1
  localizationMap : B →+* branchLocalization B P
  completionMap : branchLocalization B P →+* branchCompletion B P
  fractionFieldMap : branchCompletion B P →+* branchFractionField B P

/-- The final dictionary links valuation, ring, residue, precision, completion, and branches. -/
theorem local_arithmetic_dictionary
    {A K B L : Type*} [CommRing A] [Field K] [CommRing B] [Field L]
    [IsLocalRing A] [Algebra A K] [Algebra A B] [Algebra K L] [Algebra B L]
    (P : Ideal B) [P.IsPrime]
    (v : Valuation K ℤᵐ⁰) (w : Valuation L ℤᵐ⁰)
    (hext : v.IsEquiv (w.comap (algebraMap K L)))
    (hP : P.IsMaximal)
    (hcenter : ∀ x : B, x ∈ P ↔ w (algebraMap B L x) < 1) :
    Nonempty (Chapter12LocalArithmeticDictionary (A := A) (K := K) (B := B) (L := L) P v w) := by
  refine ⟨{
    baseMaximalIdeal := IsLocalRing.maximalIdeal A
    baseMaximalIdeal_eq := rfl
    extension := hext
    prime_isMaximal := hP
    center := hcenter
    localizationMap := algebraMap B (branchLocalization B P)
    completionMap := algebraMap (branchLocalization B P) (branchCompletion B P)
    fractionFieldMap := algebraMap (branchCompletion B P) (branchFractionField B P)
  }⟩

end

end LastLib.Book01ValuationsDVRsAndCompletions.Chapter12
