import Mathlib

namespace LastLib.Book01ValuationsDVRsAndCompletions.Chapter12

noncomputable section

open Function Ideal IsLocalRing Polynomial
open Filter Topology
open scoped BigOperators TensorProduct WithZero Polynomial

universe u

/-! # Chapter 12: Completion and finite extensions

This file is a statement-generation pass for §§12.1--12.8 of Book 1.  The
declarations deliberately record the interfaces and relationships used in the
chapter; proofs are postponed.
-/

/-! ## Common completion and branch interfaces -/

/-- The `I`-adic quotient used at finite precision. -/
abbrev adicQuotient (R : Type u) [CommRing R] (I : Ideal R) (n : ℕ) : Type u :=
  R ⧸ I ^ n

/-- The completion of a ring at a specified ideal. -/
abbrev chapterAdicCompletion (R : Type u) [CommRing R] (I : Ideal R) : Type u :=
  AdicCompletion I R

/-- The localization attached to a candidate branch prime. -/
abbrev branchLocalization (B : Type*) [CommRing B] (P : Ideal B) [P.IsPrime] : Type _ :=
  Localization P.primeCompl

/-- The completion of the localized branch at the image of its prime. -/
abbrev branchCompletion (B : Type*) [CommRing B] (P : Ideal B) [P.IsPrime] : Type _ :=
  AdicCompletion
    (Ideal.map (algebraMap B (branchLocalization B P)) P)
    (branchLocalization B P)

/-- The fraction field of the completed localized branch. -/
abbrev branchFractionField (B : Type*) [CommRing B] (P : Ideal B) [P.IsPrime] : Type _ :=
  FractionRing (branchCompletion B P)

/-- The fraction field of the completion at an ideal. -/
abbrev completionFractionField (R : Type u) [CommRing R] (I : Ideal R) : Type u :=
  FractionRing (AdicCompletion I R)

/-- The principal ideal generated by a power of an element. -/
def principalPowerIdeal {R : Type*} [CommRing R] (π : R) (n : ℕ) : Ideal R :=
  Ideal.span {π ^ n}

/-- The extension to `B` of a principal power from an `A`-algebra. -/
def extendedPrincipalPowerIdeal
    (A B : Type*) [CommRing A] [CommRing B] [Algebra A B]
    (π : A) (n : ℕ) : Ideal B :=
  Ideal.span {(algebraMap A B π) ^ n}

/-- Pairwise coprimality of a finite family of ideals. -/
def pairwiseCoprimeIdeals {ι R : Type*} [CommRing R]
    (I : ι → Ideal R) : Prop :=
  Pairwise (fun i j => IsCoprime (I i) (I j))

/-- Cofinality of two ideal filtrations. -/
def adicFiltrationsCofinal {R : Type*} [CommRing R]
    (I J : Ideal R) : Prop :=
  (∀ n : ℕ, ∃ m : ℕ, I ^ m ≤ J ^ n) ∧
    (∀ n : ℕ, ∃ m : ℕ, J ^ m ≤ I ^ n)

/-- Positivity is exactly what makes the subsequence `n ↦ n * e` cofinal. -/
def positiveExponent {e : ℕ} : Prop := 0 < e

/-- A ring-theoretic formulation of “the completed product is an algebra product”. -/
def hasCompletedRingProduct (A B Ahat : Type*) [CommRing A] [CommRing B]
    [CommRing Ahat] [Algebra A B] [Algebra A Ahat] {ι : Type*}
    (C : ι → Type*) [∀ i, CommRing (C i)] : Prop :=
  Nonempty (B ⊗[A] Ahat ≃+* (∀ i, C i))

/-- The same product assertion, remembering the `Ahat`-algebra structures. -/
def hasCompletedAlgebraProduct (A B Ahat : Type*) [CommRing A] [CommRing B]
    [CommRing Ahat] [Algebra A B] [Algebra A Ahat]
    [Algebra Ahat (B ⊗[A] Ahat)] {ι : Type*}
    (C : ι → Type*) [∀ i, CommRing (C i)] [∀ i, Algebra Ahat (C i)] : Prop :=
  Nonempty (B ⊗[A] Ahat ≃ₐ[Ahat] (∀ i, C i))

/-! Idempotents are used below to record the branch projectors. -/

abbrev IdempotentElement (R : Type*) [Monoid R] : Type _ :=
  {e : R // e * e = e}

/-! ## 12.1--12.2. Separating branches and finite precision -/

/-- Chinese remainder at the inverse-limit level, using Mathlib's quotient CRT. -/
noncomputable def chapterChineseRemainderEquiv
    {R ι : Type*} [CommRing R] [Finite ι]
    (I : ι → Ideal R) (hI : pairwiseCoprimeIdeals I) :
    (R ⧸ ⨅ i, I i) ≃+* (∀ i, R ⧸ I i) :=
  Ideal.quotientInfRingEquivPiQuotient I hI

/-- The finite-precision Chinese remainder decomposition. -/
theorem finite_precision_chinese_remainder
    {R ι : Type*} [CommRing R] [Finite ι]
    (I : ι → Ideal R) (hI : pairwiseCoprimeIdeals I) :
    Nonempty ((R ⧸ ⨅ i, I i) ≃+* (∀ i, R ⧸ I i)) := by
  exact ⟨chapterChineseRemainderEquiv I hI⟩


/-- Powers of a uniformizer factor into powers of the branch primes. -/
theorem finite_precision_pi_power_factorization
    {A B : Type*} [CommRing A] [CommRing B] [Algebra A B]
    {g : ℕ} (π : A) (P : Fin g → Ideal B) (e : Fin g → ℕ) (n : ℕ)
    (hfactor : extendedPrincipalPowerIdeal A B π n = ⨅ i, P i ^ (n * e i))
    (hpair : pairwiseCoprimeIdeals P) :
    Nonempty
      ((B ⧸ extendedPrincipalPowerIdeal A B π n) ≃+*
        (∀ i, B ⧸ P i ^ (n * e i))) := by
  have hpow : Pairwise (fun i j => IsCoprime (P i ^ (n * e i)) (P j ^ (n * e j))) := by
    intro i j hij
    exact (hpair hij).pow
  rw [hfactor]
  exact ⟨Ideal.quotientInfRingEquivPiQuotient (fun i => P i ^ (n * e i)) hpow⟩


/-- The product form of ideal factorization gives the same finite-precision CRT. -/
theorem finite_precision_pi_power_product_form
    {A B : Type*} [CommRing A] [CommRing B] [Algebra A B]
    {g : ℕ} (π : A) (P : Fin g → Ideal B) (e : Fin g → ℕ) (n : ℕ)
    (hfactor : extendedPrincipalPowerIdeal A B π n = ∏ i, P i ^ (n * e i))
    (hintersection : (∏ i, P i ^ (n * e i)) = ⨅ i, P i ^ (n * e i))
    (hpair : pairwiseCoprimeIdeals P) :
    Nonempty
      ((B ⧸ extendedPrincipalPowerIdeal A B π n) ≃+*
        (∀ i, B ⧸ P i ^ (n * e i))) := by
  have hpow : Pairwise (fun i j => IsCoprime (P i ^ (n * e i)) (P j ^ (n * e j))) := by
    intro i j hij
    exact (hpair hij).pow
  rw [hfactor, hintersection]
  exact ⟨Ideal.quotientInfRingEquivPiQuotient (fun i => P i ^ (n * e i)) hpow⟩


/-- Localizing a primary branch quotient does not change it. -/
theorem localization_of_branch_quotient_equiv
    {B : Type*} [CommRing B] (P : Ideal B) (n : ℕ)
    (hP : P.IsPrime) (hmax : P.IsMaximal) :
    Nonempty
      ((Localization.AtPrime P ⧸
          Ideal.map (algebraMap B (Localization.AtPrime P)) (P ^ n)) ≃+*
        (B ⧸ P ^ n)) := by
  let _ : P.IsPrime := hP
  let _ : P.IsMaximal := hmax
  have hmap :
      Ideal.map (algebraMap B (Localization.AtPrime P)) (P ^ n) =
        IsLocalRing.maximalIdeal (Localization.AtPrime P) ^ n := by
    rw [Ideal.map_pow,
      IsLocalization.AtPrime.map_eq_maximalIdeal P (Localization.AtPrime P)]
  refine ⟨?_⟩
  rw [hmap]
  exact (IsLocalization.AtPrime.equivQuotMaximalIdealPow P
    (Localization.AtPrime P) n).symm.toRingEquiv

/-- Positive multiples are cofinal among all positive exponents. -/
theorem positive_multiples_are_cofinal (e : ℕ) (he : positiveExponent (e := e)) :
    ∀ n : ℕ, ∃ m : ℕ, n ≤ m * e := by
  intro n
  exact ⟨n, Nat.le_mul_of_pos_right n he⟩


/-- A finite-level CRT system with the actual representative compatibility. -/
structure Chapter12CompatibleCRTSystem
    {R ι : Type*} [CommRing R] [Finite ι]
    (I : Ideal R) (J : ι → Ideal R) where
  equiv : ∀ n : ℕ, (R ⧸ I ^ n) ≃+* (∀ i, R ⧸ (J i) ^ n)
  compatible : ∀ (n : ℕ) (x : R),
    equiv n (Ideal.Quotient.mk (I ^ n) x) =
      fun i => Ideal.Quotient.mk ((J i) ^ n) x

/-- The finite-product CRT is compatible with passing to inverse limits. -/
theorem completion_product_of_finite_precision_crt
    {R ι : Type*} [CommRing R] [Finite ι]
    (I : Ideal R) (J : ι → Ideal R)
    (hcrt : Chapter12CompatibleCRTSystem I J)
    (hcofinal : ∀ i, adicFiltrationsCofinal I (J i)) :
    Nonempty
      (AdicCompletion I R ≃+* (∀ i, AdicCompletion (J i) R)) := by
  classical
  let _ : Fintype ι := Fintype.ofFinite ι
  have htop (L : Ideal R) (n : ℕ) :
      (L ^ n • (⊤ : Ideal R)) = L ^ n := by
    ext x
    simp
  have htrans (L : Ideal R) {m n : ℕ} (hmn : m ≤ n)
      (x : AdicCompletion L R) :
      Ideal.Quotient.factorPow L hmn (AdicCompletion.evalₐ L n x) =
        AdicCompletion.evalₐ L m x := by
    have hle (k : ℕ) : L ^ k ≤ L ^ k • (⊤ : Ideal R) := by
      rw [htop L k]
    apply (Ideal.quotientEquivAlgOfEq R (htop L m)).symm.injective
    change Ideal.Quotient.factor (hle m)
        (Ideal.Quotient.factorPow L hmn (AdicCompletion.evalₐ L n x)) =
      Ideal.Quotient.factor (hle m) (AdicCompletion.evalₐ L m x)
    rw [AdicCompletion.factor_evalₐ_eq_eval L x (by
      rw [htop L m])]
    rw [← AdicCompletion.factor_eval_eq_evalₐ L x (by
      rw [htop L n])]
    change _ = x.val m
    rw [← x.property hmn]
    rw [AdicCompletion.eval_apply]
    induction x.val n using Quotient.inductionOn' with
    | _ r => rfl
  have hcrt_nat {m n : ℕ} (hmn : m ≤ n) (z : R ⧸ I ^ n) :
      hcrt.equiv m (Ideal.Quotient.factorPow I hmn z) =
        fun i => Ideal.Quotient.factorPow (J i) hmn ((hcrt.equiv n z) i) := by
    induction z using Quotient.inductionOn' with
    | _ r =>
      change hcrt.equiv m (Ideal.Quotient.factorPow I hmn
          (Ideal.Quotient.mk (I ^ n) r)) =
        fun i => Ideal.Quotient.factorPow (J i) hmn
          ((hcrt.equiv n (Ideal.Quotient.mk (I ^ n) r)) i)
      rw [hcrt.compatible n r]
      convert hcrt.compatible m r using 1 <;> rfl
  let f : ∀ i, ∀ n, AdicCompletion I R →+* R ⧸ (J i) ^ n :=
    fun i n =>
      (Pi.evalRingHom (fun j => R ⧸ (J j) ^ n) i).comp
        ((hcrt.equiv n).toRingHom.comp (AdicCompletion.evalₐ I n).toRingHom)
  have hf (i : ι) {m n : ℕ} (hmn : m ≤ n) :
      (Ideal.Quotient.factorPow (J i) hmn).comp (f i n) = f i m := by
    ext x
    have hn := congrFun (hcrt_nat hmn (AdicCompletion.evalₐ I n x)) i
    rw [htrans I hmn x] at hn
    exact hn.symm
  let φ : ∀ i, AdicCompletion I R →+* AdicCompletion (J i) R :=
    fun i => AdicCompletion.liftRingHom (J i) (f i) (hf i)
  let F : AdicCompletion I R →+* (∀ i, AdicCompletion (J i) R) :=
    RingHom.pi φ
  let g : ∀ n, (∀ i, AdicCompletion (J i) R) →+* R ⧸ I ^ n :=
    fun n =>
      (hcrt.equiv n).symm.toRingHom.comp
        (RingHom.pi (fun i =>
          (AdicCompletion.evalₐ (J i) n).toRingHom.comp
            (Pi.evalRingHom (fun i => AdicCompletion (J i) R) i)))
  have hcrt_nat_symm {m n : ℕ} (hmn : m ≤ n)
      (z : ∀ i, R ⧸ (J i) ^ n) :
      Ideal.Quotient.factorPow I hmn ((hcrt.equiv n).symm z) =
        (hcrt.equiv m).symm (fun i =>
          Ideal.Quotient.factorPow (J i) hmn (z i)) := by
    apply (hcrt.equiv m).injective
    calc
      hcrt.equiv m (Ideal.Quotient.factorPow I hmn ((hcrt.equiv n).symm z)) =
          fun i => Ideal.Quotient.factorPow (J i) hmn
            ((hcrt.equiv n ((hcrt.equiv n).symm z)) i) :=
        hcrt_nat hmn ((hcrt.equiv n).symm z)
      _ = fun i => Ideal.Quotient.factorPow (J i) hmn (z i) := by simp
      _ = hcrt.equiv m ((hcrt.equiv m).symm (fun i =>
          Ideal.Quotient.factorPow (J i) hmn (z i))) := by simp
  have hg {m n : ℕ} (hmn : m ≤ n) :
      (Ideal.Quotient.factorPow I hmn).comp (g n) = g m := by
    apply RingHom.ext
    intro z
    change Ideal.Quotient.factorPow I hmn ((hcrt.equiv n).symm
        (fun i => AdicCompletion.evalₐ (J i) n (z i))) =
      (hcrt.equiv m).symm (fun i => AdicCompletion.evalₐ (J i) m (z i))
    rw [hcrt_nat_symm hmn]
    congr 1
    funext i
    exact htrans (J i) hmn (z i)
  let G : (∀ i, AdicCompletion (J i) R) →+* AdicCompletion I R :=
    AdicCompletion.liftRingHom I g hg
  have hGF (x : AdicCompletion I R) : G (F x) = x := by
    apply AdicCompletion.ext_evalₐ
    intro n
    dsimp only [G]
    rw [AdicCompletion.evalₐ_liftRingHom]
    apply (hcrt.equiv n).injective
    simp only [g, F, φ]
    funext i
    simp [RingHom.comp_apply, RingHom.pi_apply]
    simp [f, RingHom.comp_apply]
  have hFG (z : ∀ i, AdicCompletion (J i) R) : F (G z) = z := by
    funext i
    apply AdicCompletion.ext_evalₐ
    intro n
    change AdicCompletion.evalₐ (J i) n
        (AdicCompletion.liftRingHom (J i) (f i) (hf i) (G z)) =
      AdicCompletion.evalₐ (J i) n (z i)
    rw [AdicCompletion.evalₐ_liftRingHom]
    change (Pi.evalRingHom (fun j => R ⧸ (J j) ^ n) i)
        ((hcrt.equiv n) (AdicCompletion.evalₐ I n (G z))) =
      AdicCompletion.evalₐ (J i) n (z i)
    dsimp only [G]
    rw [AdicCompletion.evalₐ_liftRingHom]
    simp [g]
  have hbij : Function.Bijective F := by
    constructor
    · intro x y hxy
      calc
        x = G (F x) := (hGF x).symm
        _ = G (F y) := congrArg G hxy
        _ = y := hGF y
    · intro z
      exact ⟨G z, hFG z⟩
  exact ⟨RingEquiv.ofBijective F hbij⟩

/--
The completed product decomposition from Theorem 12.1.  The branch factors
are the completions of the localizations at the primes `P i`.
-/
theorem completed_product_decomposition
    {A B : Type*} [CommRing A] [CommRing B] [IsDomain A] [IsDomain B]
    [IsDiscreteValuationRing A] [Algebra A B] [Algebra.IsIntegral A B]
    {g : ℕ} (m : Ideal A) (π : A) (P : Fin g → Ideal B) (e : Fin g → ℕ)
    [m.IsMaximal] [hprime : ∀ i, (P i).IsPrime]
    [hmax : ∀ i, (P i).IsMaximal]
    (huniformizer : m = Ideal.span {π})
    (hfinite : Module.Finite A B) (hfree : Module.Free A B)
    (hfactor : ∀ n : ℕ,
      extendedPrincipalPowerIdeal A B π n = ⨅ i, P i ^ (n * e i))
    (he : ∀ i, 0 < e i)
    (hpair : pairwiseCoprimeIdeals P)
    (hP : ∀ i, (P i).LiesOver m)
    (hP_exhaustive :
      ∀ (q : Ideal B), q.IsPrime → q.LiesOver m → ∃ i, P i = q)
    (hP_distinct : Function.Injective P)
    [Algebra (AdicCompletion m A) (B ⊗[A] AdicCompletion m A)]
    [∀ i, Algebra (AdicCompletion m A) (branchCompletion B (P i))] :
    hasCompletedAlgebraProduct A B (AdicCompletion m A)
      (fun i => branchCompletion B (P i)) := by
  sorry

/-- Each finite quotient remembers the `i`th branch to precision `n * e i`. -/
theorem finite_precision_branch_indexing
    {A B : Type*} [CommRing A] [CommRing B] [Algebra A B]
    {g : ℕ} (π : A) (P : Fin g → Ideal B) (e : Fin g → ℕ) (n : ℕ)
    (hfactor : extendedPrincipalPowerIdeal A B π n = ⨅ i, P i ^ (n * e i))
    (hpair : pairwiseCoprimeIdeals P) :
    Nonempty
      ((B ⧸ extendedPrincipalPowerIdeal A B π n) ≃+*
        (∀ i, B ⧸ P i ^ (n * e i))) := by
  have hpow : Pairwise (fun i j => IsCoprime (P i ^ (n * e i)) (P j ^ (n * e j))) := by
    intro i j hij
    exact (hpair hij).pow
  rw [hfactor]
  exact ⟨Ideal.quotientInfRingEquivPiQuotient (fun i => P i ^ (n * e i)) hpow⟩


/-- The inverse-limit CRT equivalence supplies orthogonal branch projectors. -/
theorem compatible_branch_projector_idempotents
    {R ι : Type*} [CommRing R] [Fintype ι] [DecidableEq ι]
    (I : Ideal R) (J : ι → Ideal R)
    (hcrt : Chapter12CompatibleCRTSystem I J)
    (hcofinal : ∀ i, adicFiltrationsCofinal I (J i)) :
    ∃ e : ι → IdempotentElement (AdicCompletion I R),
      (∀ i j, i ≠ j → (e i).1 * (e j).1 = 0) ∧
        (∑ i, (e i).1) = 1 ∧
        (∀ n i,
          hcrt.equiv n (AdicCompletion.evalₐ I n (e i).1) =
            (fun j => if j = i then 1 else 0)) := by
  classical
  let qeq (n : ℕ) :
      (R ⧸ (I ^ n • (⊤ : Ideal R))) ≃+* R ⧸ I ^ n :=
    (Ideal.quotientEquivAlgOfEq R (by
      ext x
      simp)).toRingEquiv
  have hqfactor {m n : ℕ} (hmn : m ≤ n) (x : R ⧸ I ^ n) :
      qeq m (AdicCompletion.transitionMap I R hmn ((qeq n).symm x)) =
        Ideal.Quotient.factorPow I hmn x := by
    induction x using Quotient.inductionOn' with
    | _ r => rfl
  have hcrt_nat {m n : ℕ} (hmn : m ≤ n) (z : R ⧸ I ^ n) :
      hcrt.equiv m (Ideal.Quotient.factorPow I hmn z) =
        fun i => Ideal.Quotient.factorPow (J i) hmn ((hcrt.equiv n z) i) := by
    induction z using Quotient.inductionOn' with
    | _ r =>
      change hcrt.equiv m (Ideal.Quotient.factorPow I hmn
          (Ideal.Quotient.mk (I ^ n) r)) =
        fun i => Ideal.Quotient.factorPow (J i) hmn
          ((hcrt.equiv n (Ideal.Quotient.mk (I ^ n) r)) i)
      rw [hcrt.compatible n r]
      convert hcrt.compatible m r using 1 <;> rfl
  have hcrt_nat_symm {m n : ℕ} (hmn : m ≤ n)
      (z : ∀ i, R ⧸ (J i) ^ n) :
      Ideal.Quotient.factorPow I hmn ((hcrt.equiv n).symm z) =
        (hcrt.equiv m).symm (fun i =>
          Ideal.Quotient.factorPow (J i) hmn (z i)) := by
    apply (hcrt.equiv m).injective
    calc
      hcrt.equiv m (Ideal.Quotient.factorPow I hmn ((hcrt.equiv n).symm z)) =
          fun i => Ideal.Quotient.factorPow (J i) hmn
            ((hcrt.equiv n ((hcrt.equiv n).symm z)) i) :=
        hcrt_nat hmn ((hcrt.equiv n).symm z)
      _ = fun i => Ideal.Quotient.factorPow (J i) hmn (z i) := by simp
      _ = hcrt.equiv m ((hcrt.equiv m).symm (fun i =>
          Ideal.Quotient.factorPow (J i) hmn (z i))) := by simp
  let delta (i : ι) (n : ℕ) : ∀ j, R ⧸ (J j) ^ n :=
    fun j => if j = i then 1 else 0
  let z (i : ι) : AdicCompletion I R :=
    ⟨fun n => (qeq n).symm ((hcrt.equiv n).symm (delta i n)), by
      intro m n hmn
      apply (qeq m).injective
      rw [hqfactor, hcrt_nat_symm hmn]
      simp [delta]⟩
  have hz (i : ι) (n : ℕ) :
      AdicCompletion.evalₐ I n (z i) = (hcrt.equiv n).symm (delta i n) := by
    change qeq n ((z i).val n) = _
    change qeq n ((qeq n).symm ((hcrt.equiv n).symm (delta i n))) = _
    exact (qeq n).apply_symm_apply _
  let e : ι → IdempotentElement (AdicCompletion I R) := fun i =>
    ⟨z i, by
      apply AdicCompletion.ext_evalₐ
      intro n
      rw [map_mul, hz]
      apply (hcrt.equiv n).injective
      funext j
      by_cases hji : j = i
      · simp [delta, hji]
      · simp [delta, hji]⟩
  refine ⟨e, ?_, ?_, ?_⟩
  · intro i j hij
    apply AdicCompletion.ext_evalₐ
    intro n
    change AdicCompletion.evalₐ I n (z i * z j) = 0
    rw [map_mul, hz i n, hz j n]
    apply (hcrt.equiv n).injective
    funext k
    have hji : j ≠ i := Ne.symm hij
    rcases eq_or_ne k i with rfl | hki
    · simp [delta, hij]
    · rcases eq_or_ne k j with rfl | hkj
      · simp [delta, hji]
      · simp [delta, hki, hkj]
  · apply AdicCompletion.ext_evalₐ
    intro n
    change AdicCompletion.evalₐ I n (∑ i, z i) = AdicCompletion.evalₐ I n 1
    rw [map_sum]
    simp only [map_one]
    apply (hcrt.equiv n).injective
    rw [map_sum, map_one]
    funext j
    simp [hz, delta]
  · intro n i
    rw [hz]
    exact (hcrt.equiv n).apply_symm_apply (delta i n)

/-- A complete DVR factor, with the structural typeclasses carried as data. -/
structure Chapter12CompleteDVRData (R : Type*) [CommRing R] where
  [localRing : IsLocalRing R]
  [domain : IsDomain R]
  [dvr : IsDiscreteValuationRing R]
  complete : IsAdicComplete (IsLocalRing.maximalIdeal R) R

def isCompleteDVR (R : Type*) [CommRing R] : Prop :=
  Nonempty (Chapter12CompleteDVRData R)

/-- The completed branch factors are complete DVRs and finite free over the
    completed base. -/
theorem completed_branch_factors_are_complete_DVR_and_finite_free
    {A B : Type*} [CommRing A] [CommRing B] [IsDomain A] [IsDomain B]
    [IsDiscreteValuationRing A] [Algebra A B] [Algebra.IsIntegral A B]
    {g : ℕ} (m : Ideal A) (π : A) (P : Fin g → Ideal B) (e : Fin g → ℕ)
    [m.IsMaximal] [hprime : ∀ i, (P i).IsPrime]
    [hmax : ∀ i, (P i).IsMaximal]
    (huniformizer : m = Ideal.span {π})
    (hfinite : Module.Finite A B) (hfree : Module.Free A B)
    (hfactor : ∀ n : ℕ,
      extendedPrincipalPowerIdeal A B π n = ⨅ i, P i ^ (n * e i))
    (he : ∀ i, 0 < e i)
    (hpair : pairwiseCoprimeIdeals P)
    (hP : ∀ i, (P i).LiesOver m)
    (hP_exhaustive :
      ∀ (q : Ideal B), q.IsPrime → q.LiesOver m → ∃ i, P i = q)
    (hP_distinct : Function.Injective P)
    [Algebra (AdicCompletion m A) (B ⊗[A] AdicCompletion m A)]
    [∀ i, Algebra (AdicCompletion m A) (branchCompletion B (P i))] :
    ∀ i, isCompleteDVR (branchCompletion B (P i)) ∧
    Module.Finite (AdicCompletion m A) (branchCompletion B (P i)) ∧
    Module.Free (AdicCompletion m A) (branchCompletion B (P i)) := by
  sorry

/-- The intrinsic ramification index attached to a prime of an algebra. -/
def chapterRamificationIndex
    (A B : Type*) [CommRing A] [CommRing B] [Algebra A B]
    (P : Ideal B) : ℕ :=
  P.ramificationIdx A

/-- The intrinsic residue/inertia degree attached to a prime of an algebra. -/
def chapterResidueDegree
    (A B : Type*) [CommRing A] [CommRing B] [Algebra A B]
    (P : Ideal B) : ℕ :=
  P.inertiaDeg A

/-- Branch transport data carries the base and branch ideals through actual
ring equivalences compatible with the algebra structures. -/
structure Chapter12BranchInvariantTransport
    {A B Ahat Bhat : Type*} [CommRing A] [CommRing B]
    [CommRing Ahat] [CommRing Bhat] [Algebra A B] [Algebra Ahat Bhat]
    (p : Ideal A) (P : Ideal B) (phat : Ideal Ahat) (Phat : Ideal Bhat) where
  source_prime : P.IsPrime
  target_prime : Phat.IsPrime
  source_liesOver : P.LiesOver p
  target_liesOver : Phat.LiesOver phat
  baseEquiv : A ≃+* Ahat
  branchEquiv : B ≃+* Bhat
  baseIdeal_map : Ideal.map baseEquiv.toRingHom p = phat
  branchIdeal_map : Ideal.map branchEquiv.toRingHom P = Phat
  scalar_compatibility : ∀ a b,
    branchEquiv (algebraMap A B a * b) =
      algebraMap Ahat Bhat (baseEquiv a) * branchEquiv b

/-- Completion preserves the branch's intrinsic `e` and `f`. -/
theorem completed_branch_preserves_ef
    {A B Ahat Bhat : Type*} [CommRing A] [CommRing B] [CommRing Ahat] [CommRing Bhat]
    [Algebra A B] [Algebra Ahat Bhat]
    (p : Ideal A) (P : Ideal B) (phat : Ideal Ahat) (Phat : Ideal Bhat)
    (transport : Chapter12BranchInvariantTransport p P phat Phat)
    (e f : ℕ)
    (he : chapterRamificationIndex A B P = e)
    (hf : chapterResidueDegree A B P = f) :
    chapterRamificationIndex Ahat Bhat Phat = e ∧
      chapterResidueDegree Ahat Bhat Phat = f := by
  sorry


/-- The fraction-field decomposition after inverting the base uniformizer. -/
theorem completed_product_field_decomposition
    {A B : Type*} [CommRing A] [CommRing B] [IsDomain A] [IsDomain B]
    [IsDiscreteValuationRing A] [Algebra A B] [Algebra.IsIntegral A B]
    {g : ℕ} (m : Ideal A) (π : A) (P : Fin g → Ideal B) (e : Fin g → ℕ)
    [m.IsMaximal] [hprime : ∀ i, (P i).IsPrime]
    [hmax : ∀ i, (P i).IsMaximal]
    (huniformizer : m = Ideal.span {π})
    (hfinite : Module.Finite A B) (hfree : Module.Free A B)
    (hfactor : ∀ n : ℕ,
      extendedPrincipalPowerIdeal A B π n = ⨅ i, P i ^ (n * e i))
    (he : ∀ i, 0 < e i)
    (hpair : pairwiseCoprimeIdeals P)
    (hP : ∀ i, (P i).LiesOver m)
    (hP_exhaustive :
      ∀ (q : Ideal B), q.IsPrime → q.LiesOver m → ∃ i, P i = q)
    (hP_distinct : Function.Injective P)
    [Algebra (AdicCompletion m A) (B ⊗[A] AdicCompletion m A)]
    [∀ i, Algebra (AdicCompletion m A) (branchCompletion B (P i))]
    [Algebra (FractionRing A) (FractionRing B)]
    [Algebra (FractionRing A) (completionFractionField A m)]
    :
    Nonempty
      (FractionRing B ⊗[FractionRing A] completionFractionField A m ≃+*
        (∀ i, branchFractionField B (P i))) := by
  sorry

/-- If the base is already complete, the tensor product has only one branch. -/
theorem complete_base_has_one_completed_factor
    {g : ℕ} {L : Fin g → Type*} [∀ i, Field (L i)]
    (hfield : IsField (∀ i, L i)) (hg : 0 < g) : g = 1 := by
  let _ : IsField (∀ i, L i) := hfield
  let _ : IsDomain (∀ i, L i) := hfield.isDomain
  have hsub : ∀ i j : Fin g, i = j := by
    intro i j
    by_contra hij
    let x : ∀ k, L k := fun k => if k = i then 1 else 0
    let y : ∀ k, L k := fun k => if k = j then 1 else 0
    have hxy : x * y = 0 := by
      funext k
      by_cases hki : k = i
      · subst k
        by_cases hkj : i = j
        · exact (hij hkj).elim
        · simp [x, y, hkj]
      · simp [x, y, hki]
    have hx : x ≠ 0 := by
      intro hx
      have := congrFun hx i
      simp [x] at this
    have hy : y ≠ 0 := by
      intro hy
      have := congrFun hy j
      simp [y] at this
    exact (mul_ne_zero hx hy) hxy
  have hcard : Fintype.card (Fin g) ≤ 1 :=
    Fintype.card_le_one_iff_subsingleton.mpr ⟨hsub⟩
  have hle : g ≤ 1 := by simpa using hcard
  omega

/-- A valuation on an algebraic extension extending `v`, up to Mathlib equivalence. -/
def ValuationExtension
    {K Γ : Type*} [Field K] [LinearOrderedCommGroupWithZero Γ]
    (v : Valuation K Γ) (E : Type*) [Field E] [Algebra K E] : Type _ :=
  {w : Valuation E Γ // v.IsEquiv (w.comap (algebraMap K E))}

/-- A valuation extension whose ordered value group is part of the data. -/
structure HeterogeneousValuationExtension
    {K Γ : Type u} [Field K] [LinearOrderedCommGroupWithZero Γ]
    (v : Valuation K Γ) (E : Type u) [Field E] [Algebra K E] where
  valueGroup : Type u
  [orderedValueGroup : LinearOrderedCommGroupWithZero valueGroup]
  valuation : Valuation E valueGroup
  isExtension : v.IsEquiv (valuation.comap (algebraMap K E))

/-- The center of a heterogeneous valuation on the integral closure. -/
def heterogeneousValuationCenter
    {K E Γ : Type u} [Field K] [Field E]
    [LinearOrderedCommGroupWithZero Γ] [Algebra K E]
    (v : Valuation K Γ) [Algebra v.valuationSubring E]
    (W : HeterogeneousValuationExtension v E) :
    Set (integralClosure v.valuationSubring E) :=
  {x | letI : LinearOrderedCommGroupWithZero W.valueGroup := W.orderedValueGroup
    W.valuation (algebraMap (integralClosure v.valuationSubring E) E x) < 1}

/-- Uniqueness of an extension to one field, up to equivalence. -/
def hasUniqueValuationExtension
    {K Γ : Type u} [Field K] [LinearOrderedCommGroupWithZero Γ]
    (v : Valuation K Γ) (E : Type u) [Field E] [Algebra K E] : Prop :=
  Nonempty (HeterogeneousValuationExtension v E) ∧
    ∀ W₁ W₂ : HeterogeneousValuationExtension v E,
      (letI : LinearOrderedCommGroupWithZero W₁.valueGroup := W₁.orderedValueGroup
       letI : LinearOrderedCommGroupWithZero W₂.valueGroup := W₂.orderedValueGroup
       W₁.valuation.IsEquiv W₂.valuation)

/-- In the one-branch complete case the defectless equality is `[L : K] = e f`. -/
theorem complete_one_branch_fundamental_equality
    {K L Γ : Type u} [Field K] [Field L] [Algebra K L]
    [FiniteDimensional K L]
    [LinearOrderedCommGroupWithZero Γ]
    (v : Valuation K Γ)
    (w : Valuation L Γ) [v.HasExtension w]
    (e f : ℕ)
    (he : chapterRamificationIndex v.valuationSubring w.valuationSubring
      (IsLocalRing.maximalIdeal w.valuationSubring) = e)
    (hf : chapterResidueDegree v.valuationSubring w.valuationSubring
      (IsLocalRing.maximalIdeal w.valuationSubring) = f)
    [Valuation.IsRankOneDiscrete v] [Valuation.IsRankOneDiscrete w]
    (hcomplete : IsAdicComplete (IsLocalRing.maximalIdeal v.valuationSubring)
      v.valuationSubring) :
    Module.finrank K L = e * f := by
  sorry

/-! ## 12.3. Completion of a localization -/

/-- The completed localization of a Dedekind-domain prime. -/
abbrev completedLocalization
    (R : Type u) [CommRing R] (p : Ideal R) [p.IsPrime] : Type u :=
  AdicCompletion
    (Ideal.map (algebraMap R (Localization.AtPrime p)) p)
    (Localization.AtPrime p)

/-- The fraction field of the localization at `p`. -/
abbrev localizationFractionField
    (R : Type u) [CommRing R] (p : Ideal R) [p.IsPrime] : Type u :=
  FractionRing (completedLocalization R p)

/-- The two completed local-global dictionaries for a finite extension. -/
theorem dedekind_local_completion_product
    {R S : Type*} [CommRing R] [CommRing S] [IsDomain R] [IsDomain S]
    [IsDedekindDomain R] [IsDedekindDomain S] [Algebra R S]
    [Algebra (FractionRing R) (FractionRing S)]
    [Algebra.IsSeparable (FractionRing R) (FractionRing S)]
    {g : ℕ} (p : Ideal R) [p.IsPrime] (P : Fin g → Ideal S)
    (hp : p ≠ ⊥)
    (hfinite : Module.Finite R S) (hfree : Module.Free R S)
    (hlies : ∀ i, (P i).LiesOver p)
    [hprime : ∀ i, (P i).IsPrime]
    (hP_exhaustive :
      ∀ (q : Ideal S), q.IsPrime → q.LiesOver p → ∃ i, P i = q)
    (hP_distinct : Function.Injective P) :
    Nonempty
      (S ⊗[R] completedLocalization R p ≃+*
        (∀ i, branchCompletion S (P i))) := by
  sorry

/-- Fraction-field form of the localization/completion dictionary. -/
theorem dedekind_local_fraction_field_product
    {R S : Type*} [CommRing R] [CommRing S] [IsDomain R] [IsDomain S]
    [IsDedekindDomain R] [IsDedekindDomain S] [Algebra R S]
    {g : ℕ} (p : Ideal R) [p.IsPrime] (P : Fin g → Ideal S)
    (hp : p ≠ ⊥)
    [Algebra (FractionRing R) (FractionRing S)]
    [Algebra.IsSeparable (FractionRing R) (FractionRing S)]
    [Algebra (FractionRing R) (localizationFractionField R p)]
    (hfinite : Module.Finite R S) (hfree : Module.Free R S)
    (hlies : ∀ i, (P i).LiesOver p)
    [hprime : ∀ i, (P i).IsPrime]
    (hP_exhaustive :
      ∀ (q : Ideal S), q.IsPrime → q.LiesOver p → ∃ i, P i = q)
    (hP_distinct : Function.Injective P) :
    Nonempty
      (FractionRing S ⊗[FractionRing R] localizationFractionField R p ≃+*
        (∀ i, branchFractionField S (P i))) := by
  sorry

/-- Tensoring with a completed base records all primes above the chosen base prime. -/
theorem tensor_product_remembers_all_local_choices
    {R S : Type*} [CommRing R] [CommRing S] [Algebra R S]
    {g : ℕ} (p : Ideal R) [p.IsPrime] (P : Fin g → Ideal S)
    [hprime : ∀ i, (P i).IsPrime]
    (hproduct : Nonempty
      (S ⊗[R] completedLocalization R p ≃+*
        (∀ i, branchCompletion S (P i)))) :
    ∃ proj : ∀ i, (S ⊗[R] completedLocalization R p) →+* branchCompletion S (P i),
      ∀ i, Function.Surjective (proj i) := by
  let e := Classical.choice hproduct
  refine ⟨fun i => (Pi.evalRingHom (fun i => branchCompletion S (P i)) i).comp e.toRingHom, ?_⟩
  intro i
  exact (Pi.evalRingHom (fun i => branchCompletion S (P i)) i).surjective.comp e.surjective


/-! ## 12.4. Primitive elements, factorization, and projectors -/

/-- The completed polynomial quotient associated to a polynomial over a field. -/
abbrev completedPolynomialQuotient
    {K Khat : Type*} [Field K] [Field Khat] [Algebra K Khat]
    (f : K[X]) : Type _ :=
  Khat[X] ⧸ Ideal.span {f.map (algebraMap K Khat)}

/-- A tensor product with a primitive polynomial quotient is a completed polynomial quotient. -/
theorem primitive_tensor_polynomial_model
    {K Khat : Type*} [Field K] [Field Khat] [Algebra K Khat]
    (f : K[X]) :
    Nonempty
      ((K[X] ⧸ Ideal.span {f}) ⊗[K] Khat ≃+*
        completedPolynomialQuotient (Khat := Khat) f) := by
  let eK : MvPolynomial Unit K ≃ₐ[K] K[X] :=
    MvPolynomial.uniqueAlgEquiv K Unit
  let eKhat : MvPolynomial Unit Khat ≃ₐ[Khat] Khat[X] :=
    MvPolynomial.uniqueAlgEquiv Khat Unit
  let t : K[X] ⊗[K] Khat ≃+* Khat[X] :=
    (Algebra.TensorProduct.comm K K[X] Khat).toRingEquiv.trans
      ((Algebra.TensorProduct.congr
          (AlgEquiv.refl : Khat ≃ₐ[Khat] Khat) eK.symm).toRingEquiv.trans
        ((MvPolynomial.algebraTensorAlgEquiv K Khat).toRingEquiv.trans
          eKhat.toRingEquiv))
  have ht (p : K[X]) :
      t (algebraMap K[X] (K[X] ⊗[K] Khat) p) =
        p.map (algebraMap K Khat) := by
    have hring :
        t.toRingHom.comp (algebraMap K[X] (K[X] ⊗[K] Khat)) =
          Polynomial.mapRingHom (algebraMap K Khat) := by
      apply Polynomial.ringHom_ext
      · intro a
        simp [t, eK, eKhat]
      · simp [t, eK, eKhat]
    have := congrArg (fun h : K[X] →+* Khat[X] => h p) hring
    exact this
  have hIJ :
      Ideal.span ({f.map (algebraMap K Khat)} : Set Khat[X]) =
        (Ideal.span ({f} : Set K[X])).map
          (t.toRingHom.comp (algebraMap K[X] (K[X] ⊗[K] Khat))) := by
    rw [Ideal.map_span]
    simp only [Set.image_singleton, RingHom.coe_comp, Function.comp_apply]
    change Ideal.span ({f.map (algebraMap K Khat)} : Set Khat[X]) =
      Ideal.span ({t (algebraMap K[X] (K[X] ⊗[K] Khat) f)} : Set Khat[X])
    rw [← ht f]
  have hIJ' :
      Ideal.span ({f.map (algebraMap K Khat)} : Set Khat[X]) =
        ((Ideal.span ({f} : Set K[X])).map
          (algebraMap K[X] (K[X] ⊗[K] Khat))).map t.toRingHom := by
    simpa only [Ideal.map_map] using hIJ
  let qeq :=
    Algebra.TensorProduct.quotientTensorEquiv (R := K) K Khat K[X]
      (Ideal.span ({f} : Set K[X]))
  refine ⟨qeq.toRingEquiv.trans (Ideal.quotientEquiv _ _ t hIJ')⟩

/-- Coprime completed factors give a product of completed polynomial fields. -/
theorem completed_polynomial_factorization_product
    {K : Type*} [Field K] {g : ℕ} (f : K[X]) (factors : Fin g → K[X])
    (hfactor : f = ∏ i, factors i)
    (hpair : Pairwise (fun i j => IsCoprime (factors i) (factors j)))
    (hirr : ∀ i, Irreducible (factors i)) :
    Nonempty
      ((K[X] ⧸ Ideal.span {f}) ≃+*
        (∀ i, K[X] ⧸ Ideal.span {factors i})) := by
  have hcop : Pairwise (fun i j => IsCoprime (Ideal.span {factors i})
      (Ideal.span {factors j})) := by
    intro i j hij
    exact (Ideal.isCoprime_span_singleton_iff _ _).2 (hpair hij)
  have hspan : (⨅ i, Ideal.span ({factors i} : Set K[X])) =
      Ideal.span {∏ i, factors i} := Ideal.iInf_span_singleton hpair
  rw [hfactor, ← hspan]
  exact ⟨Ideal.quotientInfRingEquivPiQuotient
    (fun i => Ideal.span ({factors i} : Set K[X])) hcop⟩


/-- Each irreducible completed polynomial factor is a field. -/
theorem irreducible_completed_factor_is_field
    {K : Type*} [Field K] {f : K[X]} (hf : Irreducible f) :
    IsField (K[X] ⧸ Ideal.span {f}) := by
  let _ : (Ideal.span ({f} : Set K[X])).IsMaximal :=
    PrincipalIdealRing.isMaximal_of_irreducible hf
  let _ : Field (K[X] ⧸ Ideal.span {f}) :=
    Ideal.Quotient.field (Ideal.span ({f} : Set K[X]))
  exact Field.toIsField _


/-- A coprime factorization of a residue polynomial lifts over a henselian ring. -/
theorem henselian_coprime_factor_lift
    {A : Type*} [CommRing A] (I : Ideal A) [HenselianRing A I]
    (f : A[X]) (gbar hbar : (A ⧸ I)[X])
    (hf : f.Monic)
    (hbar_monic : gbar.Monic ∧ hbar.Monic)
    (hbar_coprime : IsCoprime gbar hbar)
    (hfactor : f.map (Ideal.Quotient.mk I) = gbar * hbar) :
    ∃ g h : A[X], g.Monic ∧ h.Monic ∧ g * h = f ∧
      g.map (Ideal.Quotient.mk I) = gbar ∧
      h.map (Ideal.Quotient.mk I) = hbar := by
  sorry

/-- The coprime factor lift is unique once the residue factors and degrees are fixed. -/
theorem henselian_coprime_factor_lift_unique
    {A : Type*} [CommRing A] (I : Ideal A) [HenselianRing A I]
    (f : A[X]) (gbar hbar : (A ⧸ I)[X])
    (g₁ h₁ g₂ h₂ : A[X])
    (hbar_coprime : IsCoprime gbar hbar)
    (h₁spec : g₁.Monic ∧ h₁.Monic ∧ g₁ * h₁ = f ∧
      g₁.map (Ideal.Quotient.mk I) = gbar ∧ h₁.map (Ideal.Quotient.mk I) = hbar)
    (h₂spec : g₂.Monic ∧ h₂.Monic ∧ g₂ * h₂ = f ∧
      g₂.map (Ideal.Quotient.mk I) = gbar ∧ h₂.map (Ideal.Quotient.mk I) = hbar) :
    g₁ = g₂ ∧ h₁ = h₂ := by
  classical
  by_cases hA : Nontrivial A
  · let _ : Nontrivial A := hA
    have hI : I ≠ ⊤ := by
      intro htop
      have hmem : (1 : A) ∈ Ideal.jacobson (⊥ : Ideal A) :=
        (inferInstance : HenselianRing A I).jac (by simp [htop])
      have hz : IsUnit (0 : A) := by
        simpa using (Ideal.mem_jacobson_bot.mp hmem (-1 : A))
      exact not_isUnit_zero hz
    let _ : Nontrivial (A ⧸ I) := Ideal.Quotient.nontrivial_iff.mpr hI
    have hmain : g₁ = g₂ ∧ h₁ = h₂ := by
      let q : A →+* (A ⧸ I) := Ideal.Quotient.mk I
      have hgbar : gbar.Monic := by
        rw [← h₁spec.2.2.2.1]
        exact h₁spec.1.map q
      have hhbar : hbar.Monic := by
        rw [← h₁spec.2.2.2.2]
        exact h₁spec.2.1.map q
      have hresbar : IsUnit (gbar.resultant hbar) :=
        (Polynomial.isUnit_resultant_iff_isCoprime hgbar).2 hbar_coprime
      let _ : IsLocalHom q := isLocalHom_of_le_jacobson_bot I
        (inferInstance : HenselianRing A I).jac
      have hresmap : q (g₁.resultant h₂) = gbar.resultant hbar := by
        rw [← h₁spec.2.2.2.1, ← h₂spec.2.2.2.2]
        rw [← Polynomial.resultant_map_map g₁ h₂ g₁.natDegree h₂.natDegree q]
        rw [h₁spec.1.natDegree_map, h₂spec.2.1.natDegree_map]
      have hres : IsUnit (g₁.resultant h₂) := by
        apply IsUnit.of_map q
        rw [hresmap]
        exact hresbar
      have hcop : IsCoprime g₁ h₂ :=
        (Polynomial.isUnit_resultant_iff_isCoprime h₁spec.1).1 hres
      have hdiv : g₁ ∣ g₂ * h₂ := by
        refine ⟨h₁, ?_⟩
        exact h₂spec.2.2.1.trans h₁spec.2.2.1.symm
      have hgdiv : g₁ ∣ g₂ := hcop.dvd_of_dvd_mul_right hdiv
      have hdeq : g₂.natDegree = g₁.natDegree := by
        calc
          g₂.natDegree = (g₂.map q).natDegree :=
            (h₂spec.1.natDegree_map q).symm
          _ = gbar.natDegree := by rw [h₂spec.2.2.2.1]
          _ = (g₁.map q).natDegree := by rw [h₁spec.2.2.2.1]
          _ = g₁.natDegree := h₁spec.1.natDegree_map q
      have hdeg : g₂.natDegree ≤ g₁.natDegree := hdeq.le
      have hgeq : g₂ = g₁ :=
        Polynomial.eq_of_monic_of_dvd_of_natDegree_le h₁spec.1 h₂spec.1 hgdiv hdeg
      have hgeq' : g₁ = g₂ := hgeq.symm
      refine ⟨hgeq', ?_⟩
      apply sub_eq_zero.mp
      have hmul : g₁ * (h₁ - h₂) = 0 := by
        rw [mul_sub, h₁spec.2.2.1, ← h₂spec.2.2.1, hgeq, sub_self]
      by_contra hne
      have hlead : g₁.leadingCoeff * (h₁ - h₂).leadingCoeff ≠ 0 := by
        simp [h₁spec.1.leadingCoeff, Polynomial.leadingCoeff_ne_zero.mpr hne]
      have hleadmul := Polynomial.leadingCoeff_mul' hlead
      rw [hmul] at hleadmul
      exact hlead hleadmul.symm
    exact hmain
  · let _ : Subsingleton A := not_nontrivial_iff_subsingleton.mp hA
    exact ⟨Subsingleton.elim _ _, Subsingleton.elim _ _⟩

/-- The split quadratic algebra used for the explicit idempotent example. -/
abbrev quadraticSplitAlgebra (R : Type*) [CommRing R] (a b : R) : Type _ :=
  R × R

/-- The polynomial quotient whose two distinct roots give the split factors. -/
abbrev quadraticSplitQuotient (R : Type*) [CommRing R] (a b : R) : Type _ :=
  R[X] ⧸ Ideal.span {(X - C a) * (X - C b)}

/-- The image of the polynomial coordinate in the split quadratic algebra. -/
def quadraticCoordinate (R : Type*) [CommRing R] (a b : R) :
    quadraticSplitAlgebra R a b :=
  (a, b)

/-- The two concrete projectors from the split quadratic algebra. -/
def quadraticProjectorA {R : Type*} [Field R] (a b : R) (h : a ≠ b) :
    quadraticSplitAlgebra R a b :=
  (1, 0)

def quadraticProjectorB {R : Type*} [Field R] (a b : R) (h : a ≠ b) :
    quadraticSplitAlgebra R a b :=
  (0, 1)

/-- The quotient representative of `(X-b)/(a-b)`. -/
def quadraticQuotientProjectorA {R : Type*} [Field R] (a b : R) (h : a ≠ b) :
    quadraticSplitQuotient R a b :=
  Ideal.Quotient.mk _ ((a - b)⁻¹ • (X - C b))

/-- The quotient representative of `(X-a)/(b-a)`. -/
def quadraticQuotientProjectorB {R : Type*} [Field R] (a b : R) (h : a ≠ b) :
    quadraticSplitQuotient R a b :=
  Ideal.Quotient.mk _ ((b - a)⁻¹ • (X - C a))

/-- The projector identities `e_a²=e_a`, `e_b²=e_b`, `e_ae_b=0`, `e_a+e_b=1`. -/
theorem quadratic_projector_relations
    {R : Type*} [Field R] (a b : R) (h : a ≠ b) :
    let ea := quadraticProjectorA a b h
    let eb := quadraticProjectorB a b h
    ea * ea = ea ∧ eb * eb = eb ∧ ea * eb = 0 ∧ ea + eb = 1 := by
  simp [quadraticProjectorA, quadraticProjectorB]


/-- The explicit projectors identify the two factors of the split quadratic algebra. -/
theorem quadratic_projectors_are_factor_projectors
    {R : Type*} [Field R] (a b : R) (h : a ≠ b) :
    Nonempty (quadraticSplitQuotient R a b ≃+* R × R) := by
  let I : Ideal R[X] := Ideal.span {X - C a}
  let J : Ideal R[X] := Ideal.span {X - C b}
  have hcop : IsCoprime I J := by
    dsimp [I, J]
    exact (Ideal.isCoprime_span_singleton_iff _ _).2
      (isCoprime_X_sub_C_of_isUnit_sub (sub_ne_zero.mpr h).isUnit)
  have hmul : I * J =
      Ideal.span {((X - C a) * (X - C b) : R[X])} := by
    dsimp [I, J]
    rw [Ideal.span_singleton_mul_span_singleton]
  let crt : R[X] ⧸ (I * J) ≃+* R × R :=
    (Ideal.quotientMulEquivQuotientProd I J hcop).trans
      (RingEquiv.prodCongr
        (Polynomial.quotientSpanXSubCAlgEquiv a).toRingEquiv
        (Polynomial.quotientSpanXSubCAlgEquiv b).toRingEquiv)
  exact ⟨(Ideal.quotEquivOfEq hmul.symm).trans crt⟩

/-- Under the splitting equivalence, the quotient projectors are the two coordinate idempotents. -/
theorem quadratic_quotient_projectors_are_coordinates
    {R : Type*} [Field R] (a b : R) (h : a ≠ b) :
    ∃ e : quadraticSplitQuotient R a b ≃+* R × R,
      e (quadraticQuotientProjectorA a b h) = (1, 0) ∧
        e (quadraticQuotientProjectorB a b h) = (0, 1) := by
  let I : Ideal R[X] := Ideal.span {X - C a}
  let J : Ideal R[X] := Ideal.span {X - C b}
  have hcop : IsCoprime I J := by
    dsimp [I, J]
    exact (Ideal.isCoprime_span_singleton_iff _ _).2
      (isCoprime_X_sub_C_of_isUnit_sub (sub_ne_zero.mpr h).isUnit)
  have hmul : I * J =
      Ideal.span {((X - C a) * (X - C b) : R[X])} := by
    dsimp [I, J]
    rw [Ideal.span_singleton_mul_span_singleton]
  let e : quadraticSplitQuotient R a b ≃+* R × R :=
    (Ideal.quotEquivOfEq hmul.symm).trans
      ((Ideal.quotientMulEquivQuotientProd I J hcop).trans
        (RingEquiv.prodCongr
          (Polynomial.quotientSpanXSubCAlgEquiv a).toRingEquiv
          (Polynomial.quotientSpanXSubCAlgEquiv b).toRingEquiv))
  have heval (p : R[X]) :
      e (Ideal.Quotient.mk
          (Ideal.span {((X - C a) * (X - C b) : R[X])}) p) =
        (p.eval a, p.eval b) := by
    simp [e, I, J, Prod.map,
      Ideal.quotientMulEquivQuotientProd_fst,
      Ideal.quotientMulEquivQuotientProd_snd]
  have hA :
      (((a - b)⁻¹ • (X - C b)).eval a,
        ((a - b)⁻¹ • (X - C b)).eval b) = (1, 0) := by
    apply Prod.ext
    · rw [Polynomial.eval_smul, Polynomial.eval_sub, Polynomial.eval_X,
        Polynomial.eval_C]
      simpa [smul_eq_mul] using inv_mul_cancel₀ (sub_ne_zero.mpr h)
    · rw [Polynomial.eval_smul, Polynomial.eval_sub, Polynomial.eval_X,
        Polynomial.eval_C]
      simp
  have hB :
      (((b - a)⁻¹ • (X - C a)).eval a,
        ((b - a)⁻¹ • (X - C a)).eval b) = (0, 1) := by
    apply Prod.ext
    · rw [Polynomial.eval_smul, Polynomial.eval_sub, Polynomial.eval_X,
        Polynomial.eval_C]
      simp
    · rw [Polynomial.eval_smul, Polynomial.eval_sub, Polynomial.eval_X,
        Polynomial.eval_C]
      simpa [smul_eq_mul] using inv_mul_cancel₀ (sub_ne_zero.mpr h.symm)
  refine ⟨e, ?_, ?_⟩
  · rw [quadraticQuotientProjectorA, heval]
    exact hA
  · rw [quadraticQuotientProjectorB, heval]
    exact hB


/-- A repeated factorization supplies a square divisor. -/
theorem repeated_polynomial_factor_has_square_divisor
    {A : Type*} [CommRing A] (f : A[X])
    (hrepeated : ∃ g : A[X], g ≠ 0 ∧ g * g ∣ f) :
    ∃ g q : A[X], g ≠ 0 ∧ f = g * g * q := by
  rcases hrepeated with ⟨g, hg, hdiv⟩
  rcases hdiv with ⟨q, hq⟩
  exact ⟨g, q, hg, hq⟩


/-- Concrete maps in the branch-language chain. -/
structure Chapter12BranchLanguageData
    {B L : Type*} [CommRing B] [Field L] [Algebra B L]
    (P : Ideal B) [P.IsPrime] {Γ : Type*}
    [LinearOrderedCommGroupWithZero Γ] (w : Valuation L Γ) where
  center : ∀ x : B, x ∈ P ↔ w (algebraMap B L x) < 1
  valuationMap : B →+* w.valuationSubring
  valuationMap_spec : ∀ x : B, (valuationMap x : L) = algebraMap B L x
  localizationMap : B →+* branchLocalization B P
  localizationMap_spec : localizationMap = algebraMap B (branchLocalization B P)
  completionMap : branchLocalization B P →+* branchCompletion B P
  completionMap_spec :
    completionMap = algebraMap (branchLocalization B P) (branchCompletion B P)
  fractionFieldMap : branchCompletion B P →+* branchFractionField B P
  fractionFieldMap_spec :
    fractionFieldMap = algebraMap (branchCompletion B P) (branchFractionField B P)

/-- A branch can be tracked through prime, localization, valuation, completion, and field. -/
theorem branch_language_chain
    {B L : Type*} [CommRing B] [Field L] [Algebra B L]
    {Γ : Type*} [LinearOrderedCommGroupWithZero Γ]
    (P : Ideal B) [P.IsPrime] (w : Valuation L Γ)
    (hcenter : ∀ x : B, x ∈ P ↔ w (algebraMap B L x) < 1)
    (hbounded : ∀ x : B, w (algebraMap B L x) ≤ 1) :
    ∃ d : Chapter12BranchLanguageData P w, d.center = hcenter := by
  let valuationMap : B →+* w.valuationSubring :=
    { toFun := fun x => ⟨algebraMap B L x, hbounded x⟩
      map_one' := by ext; simp
      map_mul' := by intro x y; ext; simp
      map_zero' := by ext; simp
      map_add' := by intro x y; ext; simp }
  refine ⟨{
    center := hcenter
    valuationMap := valuationMap
    valuationMap_spec := by intro x; rfl
    localizationMap := algebraMap B (branchLocalization B P)
    localizationMap_spec := rfl
    completionMap := algebraMap (branchLocalization B P) (branchCompletion B P)
    completionMap_spec := rfl
    fractionFieldMap := algebraMap (branchCompletion B P) (branchFractionField B P)
    fractionFieldMap_spec := rfl
  }, ?_⟩
  rfl


/-- The `e` and `f` labels are unchanged along the branch-language chain. -/
theorem branch_language_chain_preserves_ef
    {A B Ahat Bhat : Type*} [CommRing A] [CommRing B]
    [CommRing Ahat] [CommRing Bhat] [Algebra A B] [Algebra Ahat Bhat]
    (p : Ideal A) (P : Ideal B) (phat : Ideal Ahat) (Phat : Ideal Bhat)
    (transport : Chapter12BranchInvariantTransport p P phat Phat) :
    chapterRamificationIndex Ahat Bhat Phat = chapterRamificationIndex A B P ∧
      chapterResidueDegree Ahat Bhat Phat = chapterResidueDegree A B P := by
  sorry


/-! ## 12.5. Henselian uniqueness -/


/-- Uniqueness for every algebraic extension. -/
def hasUniqueExtensionToEveryAlgebraicField
    {K Γ : Type u} [Field K] [LinearOrderedCommGroupWithZero Γ]
    (v : Valuation K Γ) : Prop :=
  ∀ (E : Type u) [Field E] [Algebra K E] [Algebra.IsAlgebraic K E],
    hasUniqueValuationExtension v E

/-- Uniqueness to the fixed algebraic closure. -/
def hasUniqueExtensionToAlgebraicClosure
    {K Γ : Type u} [Field K] [LinearOrderedCommGroupWithZero Γ]
    (v : Valuation K Γ) : Prop :=
  hasUniqueValuationExtension v (AlgebraicClosure K)

/-- Locality of the integral closure in every finite field extension. -/
def allFiniteIntegralClosuresAreLocal
    {K Γ : Type u} [Field K] [LinearOrderedCommGroupWithZero Γ]
    (v : Valuation K Γ) : Prop :=
  ∀ (E : Type u) [Field E] [Algebra K E] [Module.Finite K E]
    [Algebra v.valuationSubring E]
    [IsScalarTower v.valuationSubring K E],
    IsLocalRing (integralClosure v.valuationSubring E)

/-- A finite product of local rings, allowing the factors to vary with the index. -/
structure Chapter12FiniteLocalProductData (C : Type u) [CommRing C] where
  index : Type u
  [finite_index : Fintype index]
  factor : index → Type u
  [factor_ring : ∀ i, CommRing (factor i)]
  [factor_local : ∀ i, IsLocalRing (factor i)]
  equivalence : Nonempty (C ≃+* (∀ i, factor i))

def IsFiniteProductOfLocalRings (C : Type u) [CommRing C] : Prop :=
  Nonempty (Chapter12FiniteLocalProductData C)

/-- Every finite commutative algebra is a product of local rings. -/
def allFiniteAlgebrasAreLocalProducts
    (A : Type u) [CommRing A] : Prop :=
  ∀ (C : Type u) [CommRing C] [Algebra A C] [Module.Finite A C],
    IsFiniteProductOfLocalRings C

/-- The extension of the base maximal ideal to a finite algebra. -/
def baseMaximalIdealExtension
    (A C : Type*) [CommRing A] [CommRing C] [Algebra A C] [IsLocalRing A] : Ideal C :=
  (IsLocalRing.maximalIdeal A).map (algebraMap A C)

/-- Reduction of an idempotent modulo the extended maximal ideal. -/
def idempotentReduction
    (A C : Type*) [CommRing A] [CommRing C] [Algebra A C] [IsLocalRing A]
    (e : IdempotentElement C) :
    IdempotentElement (C ⧸ baseMaximalIdealExtension A C) :=
  ⟨Ideal.Quotient.mk _ e.1, by
    change Ideal.Quotient.mk _ (e.1 * e.1) = Ideal.Quotient.mk _ e.1
    rw [e.2]⟩

/-- Idempotents lift uniquely over a henselian local base. -/
theorem henselian_idempotent_lifting
    (A C : Type*) [CommRing A] [CommRing C] [Algebra A C]
    [Module.Finite A C] [HenselianLocalRing A] :
    Function.Bijective (idempotentReduction A C) := by
  sorry

/-- An idempotent in the Jacobson radical is zero. -/
theorem idempotent_in_jacobson_is_zero
    {C : Type*} [CommRing C] (z : C)
    (hz : z * z = z) (hzJ : z ∈ Ideal.jacobson (⊥ : Ideal C)) :
    z = 0 := by
  classical
  by_cases hC : Nontrivial C
  · let _ : Nontrivial C := hC
    have hu : IsUnit (1 - z) := by
      convert (Ideal.mem_jacobson_bot.mp hzJ) (-1) using 1; ring
    have hprod : z * (1 - z) = 0 := by
      rw [mul_sub, mul_one, hz, sub_self]
    exact hu.mul_right_cancel (by simpa using hprod)
  · let _ : Subsingleton C := not_nontrivial_iff_subsingleton.mp hC
    exact Subsingleton.elim z 0


/-- The complementary projector argument produces orthogonal primitive idempotents. -/
theorem henselian_finite_algebra_has_orthogonal_idempotents
    (A C : Type*) [CommRing A] [CommRing C] [Algebra A C]
    [Module.Finite A C] [HenselianLocalRing A] :
    ∃ n : ℕ, 0 < n ∧ ∃ e : Fin n → IdempotentElement C,
      (∀ i j, i ≠ j → (e i).1 * (e j).1 = 0) ∧
      (∑ i, (e i).1) = 1 ∧
      (∀ i (z : C), z * z = z → z * (e i).1 = z →
        z = 0 ∨ z = (e i).1) := by
  sorry

/-- Henselian finite algebras split into local factors. -/
theorem henselian_finite_algebra_is_local_product
    (A C : Type*) [CommRing A] [CommRing C] [Algebra A C]
    [Module.Finite A C] [HenselianLocalRing A] :
    IsFiniteProductOfLocalRings C := by
  sorry

/-- The center of an extension valuation on an integral closure. -/
def extendedValuationCenter
    {E Γ : Type*} [Field E] [LinearOrderedCommGroupWithZero Γ]
    (w : Valuation E Γ) (C : Type*) [CommRing C] [Algebra C E] : Set C :=
  {x | w (algebraMap C E x) < 1}

/-- Integral elements over a valuation ring lie in every extending valuation ring. -/
theorem integral_closure_lies_in_extension_valuation_ring
    {A E Γ : Type*} [CommRing A] [Field E]
    [LinearOrderedCommGroupWithZero Γ] [Algebra A E]
    (w : Valuation E Γ) (x : integralClosure A E)
    (hintegers : w.Integers A)
    (hx : IsIntegral A (algebraMap (integralClosure A E) E x)) :
    w (algebraMap (integralClosure A E) E x) ≤ 1 := by
  exact hintegers.isIntegral_iff_v_le_one.mp hx

/-- Maximal ideals of integral closures are the centers of extended valuations. -/
theorem integral_closure_maximal_ideals_are_valuation_centers
    {K E Γ : Type*} [Field K] [Field E]
    [LinearOrderedCommGroupWithZero Γ] [Algebra K E]
    (v : Valuation K Γ) (w : Valuation E Γ) [v.HasExtension w]
    [Algebra v.valuationSubring E]
    [IsScalarTower v.valuationSubring K E]
    [IsLocalRing (integralClosure v.valuationSubring E)] :
    extendedValuationCenter w (integralClosure v.valuationSubring E) =
      (IsLocalRing.maximalIdeal (integralClosure v.valuationSubring E) :
        Set (integralClosure v.valuationSubring E)) := by
  sorry

/-- The extension-center correspondence has both the valuation and maximal-ideal directions. -/
theorem integral_closure_extension_center_correspondence
    {K E Γ : Type u} [Field K] [Field E]
    [LinearOrderedCommGroupWithZero Γ] [Algebra K E]
    [Algebra.IsAlgebraic K E]
    (v : Valuation K Γ)
    [Algebra v.valuationSubring E]
    [IsScalarTower v.valuationSubring K E] :
    (∀ (W : HeterogeneousValuationExtension v E),
      ∃ P : Ideal (integralClosure v.valuationSubring E),
        P.IsMaximal ∧ P.LiesOver (IsLocalRing.maximalIdeal v.valuationSubring) ∧
          (P : Set (integralClosure v.valuationSubring E)) =
            heterogeneousValuationCenter v W) ∧
      (∀ (P : Ideal (integralClosure v.valuationSubring E)),
        P.IsMaximal → P.LiesOver (IsLocalRing.maximalIdeal v.valuationSubring) →
          ∃ W : HeterogeneousValuationExtension v E,
              (P : Set (integralClosure v.valuationSubring E)) =
                heterogeneousValuationCenter v W) := by
  sorry


/-- Two extensions to a finite field remain distinct after extension to an algebraic closure. -/
theorem distinct_finite_extensions_remain_distinct_in_algebraic_closure
    {K E Γ : Type u} [Field K] [Field E]
    [LinearOrderedCommGroupWithZero Γ] [Algebra K E] [Algebra.IsAlgebraic K E]
    (v : Valuation K Γ)
    (w₁ w₂ : HeterogeneousValuationExtension v E)
    (hne : ¬ (letI : LinearOrderedCommGroupWithZero w₁.valueGroup :=
        w₁.orderedValueGroup
      letI : LinearOrderedCommGroupWithZero w₂.valueGroup :=
        w₂.orderedValueGroup
      w₁.valuation.IsEquiv w₂.valuation))
    (ι : E →ₐ[K] AlgebraicClosure K) :
    ∃ W₁ W₂ : HeterogeneousValuationExtension v (AlgebraicClosure K),
      (letI : LinearOrderedCommGroupWithZero w₁.valueGroup :=
          w₁.orderedValueGroup
       letI : LinearOrderedCommGroupWithZero W₁.valueGroup :=
          W₁.orderedValueGroup
       w₁.valuation.IsEquiv (W₁.valuation.comap ι.toRingHom)) ∧
      (letI : LinearOrderedCommGroupWithZero w₂.valueGroup :=
          w₂.orderedValueGroup
       letI : LinearOrderedCommGroupWithZero W₂.valueGroup :=
          W₂.orderedValueGroup
       w₂.valuation.IsEquiv (W₂.valuation.comap ι.toRingHom)) ∧
      (letI : LinearOrderedCommGroupWithZero W₁.valueGroup :=
          W₁.orderedValueGroup
       letI : LinearOrderedCommGroupWithZero W₂.valueGroup :=
          W₂.orderedValueGroup
       ¬ W₁.valuation.IsEquiv W₂.valuation) := by
  sorry

/-- The four conditions in Theorem 12.2 are equivalent. -/
theorem henselian_uniqueness_criterion
    {K Γ : Type u} [Field K] [LinearOrderedCommGroupWithZero Γ]
    (v : Valuation K Γ) :
    List.TFAE
      [HenselianLocalRing v.valuationSubring,
       hasUniqueExtensionToEveryAlgebraicField v,
       hasUniqueExtensionToAlgebraicClosure v,
       allFiniteIntegralClosuresAreLocal v] := by
  sorry

/-- Completeness supplies the henselian property for a complete valued field. -/
theorem complete_nonarchimedean_field_is_henselian
    {K Γ : Type*} [Field K] [LinearOrderedCommGroupWithZero Γ]
    [Valued K Γ] [CompleteSpace K] :
    HenselianLocalRing (Valued.v (R := K)).valuationSubring := by
  sorry

/-- Henselianity alone is the weaker condition used for uniqueness statements. -/
def HenselianButNotAdicallyComplete
    (R : Type*) [CommRing R] [IsLocalRing R] : Prop :=
  HenselianLocalRing R ∧ ¬ IsAdicComplete (IsLocalRing.maximalIdeal R) R

/-! ## 12.6. The valuation ring of a finite complete extension -/

/-- The coordinate lattice generated by a finite list of field coordinates. -/
def coordinateLattice
    (A L : Type*) [CommRing A] [Field L] [Algebra A L]
    {n : ℕ} (e : Fin n → L) : Set L :=
  {x | ∃ c : Fin n → A,
    (∑ i, algebraMap A L (c i) * e i) = x}

/-- A scalar multiple of a coordinate lattice. -/
def scaledSet
    (A L : Type*) [CommRing A] [Field L] [Algebra A L]
    (a : A) (S : Set L) : Set L :=
  {x | ∃ y, y ∈ S ∧ algebraMap A L a * y = x}

/-- A scalar multiple by an arbitrary element of the ambient field. -/
def scaledByFieldElement
    (L : Type*) [Field L] (a : L) (S : Set L) : Set L :=
  {x | ∃ y, y ∈ S ∧ a * y = x}

/-- The closed unit ball for a norm. -/
def closedUnitBall (L : Type*) [Norm L] : Set L :=
  {x | ‖x‖ ≤ 1}

/-- The coordinate norm attached to a finite basis. -/
def coordinateNorm
    {K L : Type*} [Norm K] [Norm L] [Field K] [Field L] [Module K L]
    {n : ℕ} (b : Module.Basis (Fin n) K L) (x : L) : ℝ :=
  ∑ i, ‖b.repr x i‖

/-- Equivalence of the coordinate norm and the field norm. -/
theorem coordinate_and_field_norms_are_equivalent
    {K L : Type*} [NontriviallyNormedField K] [NormedField L] [NormedSpace K L]
    [CompleteSpace K]
    {n : ℕ} (b : Module.Basis (Fin n) K L) :
    ∃ c₁ c₂ : ℝ, 0 < c₁ ∧ 0 < c₂ ∧
      ∀ x : L, c₁ * coordinateNorm b x ≤ ‖x‖ ∧
        ‖x‖ ≤ c₂ * coordinateNorm b x := by
  let _ : Nonempty (Fin n) := b.index_nonempty
  let _ : FiniteDimensional K L := b.finiteDimensional_of_finite
  let Fₗ : L →ₗ[K] (Fin n → K) := b.equivFun.toLinearMap
  let Gₗ : (Fin n → K) →ₗ[K] L := b.equivFun.symm.toLinearMap
  let F : L →L[K] (Fin n → K) :=
    { toLinearMap := Fₗ
      cont := by exact LinearMap.continuous_of_finiteDimensional Fₗ }
  let G : (Fin n → K) →L[K] L :=
    { toLinearMap := Gₗ
      cont := by exact LinearMap.continuous_of_finiteDimensional Gₗ }
  obtain ⟨c, hc, hG⟩ := G.isBoundedLinearMap.bound
  obtain ⟨d, hd, hF⟩ := F.isBoundedLinearMap.bound
  have hF_apply (x : L) : F x = b.equivFun x := by
    change Fₗ x = b.equivFun x
    rfl
  have hG_apply (x : L) : G (F x) = x := by
    change Gₗ (Fₗ x) = x
    simp [Fₗ, Gₗ]
  have hcoord_le (x : L) : coordinateNorm b x ≤ (n : ℝ) * ‖F x‖ := by
    change (∑ i, ‖b.repr x i‖) ≤ (n : ℝ) * ‖F x‖
    rw [hF_apply]
    simpa [Module.Basis.equivFun_apply, nsmul_eq_mul] using
      (Pi.sum_norm_apply_le_norm (b.equivFun x))
  have hnorm_le_coord (x : L) : ‖F x‖ ≤ coordinateNorm b x := by
    rw [hF_apply]
    rw [pi_norm_le_iff_of_nonempty]
    intro i
    change ‖b.repr x i‖ ≤ ∑ j, ‖b.repr x j‖
    exact Finset.single_le_sum (fun j _ => norm_nonneg _) (Finset.mem_univ i)
  have hn : 0 < (n : ℝ) := by
    have hn_nat : 0 < n := by
      simpa using (Fintype.card_pos : 0 < Fintype.card (Fin n))
    exact_mod_cast hn_nat
  refine ⟨((n : ℝ) * d)⁻¹, c, inv_pos.mpr (mul_pos hn hd), hc, ?_⟩
  intro x
  constructor
  · have hmul : coordinateNorm b x ≤ (n : ℝ) * d * ‖x‖ := by
      calc
        coordinateNorm b x ≤ (n : ℝ) * ‖F x‖ := hcoord_le x
        _ ≤ (n : ℝ) * (d * ‖x‖) :=
          mul_le_mul_of_nonneg_left (hF x) (le_of_lt hn)
        _ = (n : ℝ) * d * ‖x‖ := by ring
    calc
      ((n : ℝ) * d)⁻¹ * coordinateNorm b x ≤
          ((n : ℝ) * d)⁻¹ * ((n : ℝ) * d * ‖x‖) :=
        mul_le_mul_of_nonneg_left hmul (le_of_lt (inv_pos.mpr (mul_pos hn hd)))
      _ = ‖x‖ := by field_simp
  · calc
      ‖x‖ = ‖G (F x)‖ := by rw [hG_apply]
      _ ≤ c * ‖F x‖ := hG (F x)
      _ ≤ c * coordinateNorm b x :=
        mul_le_mul_of_nonneg_left (hnorm_le_coord x) (le_of_lt hc)

/-- Comparison of the extended closed unit ball with two integral lattices. -/
theorem unit_ball_between_scaled_coordinate_lattices
    {A K L : Type*} [CommRing A] [NormedField K] [NormedField L]
    [Algebra A K] [NormedAlgebra K L] [Algebra A L] [IsScalarTower A K L]
    [CompleteSpace K]
    {n : ℕ} (π : A) (b : Module.Basis (Fin n) K L)
    (hA : Set.range (algebraMap A K) = closedUnitBall K)
    (hπ : 0 < ‖algebraMap A K π‖ ∧ ‖algebraMap A K π‖ < 1) :
    ∃ r s : ℕ,
      scaledSet A L (π ^ r) (coordinateLattice A L (fun i => b i)) ⊆
          closedUnitBall L ∧
        closedUnitBall L ⊆
          scaledByFieldElement L ((algebraMap A L π) ^ (-(s : ℤ)))
            (coordinateLattice A L (fun i => b i)) := by
  let _ : NontriviallyNormedField K :=
    { non_trivial := ⟨(algebraMap A K π)⁻¹, by
        rw [norm_inv]
        exact (one_lt_inv₀ hπ.1).2 hπ.2⟩ }
  obtain ⟨c₁, c₂, hc₁, hc₂, hnorms⟩ :=
    coordinate_and_field_norms_are_equivalent b
  let q : ℝ := ‖algebraMap A K π‖
  let C : ℝ := max c₂ 1 * ∑ i, ‖b i‖
  have hC : 0 ≤ C := by
    dsimp [C]
    positivity
  obtain ⟨r, hr⟩ :=
    exists_pow_lt_of_lt_one (x := (C + 1)⁻¹) (by positivity) hπ.2
  have hqC : q ^ r * C ≤ 1 := by
    have hq : q ^ r * (C + 1) < 1 := by
      calc
        q ^ r * (C + 1) < (C + 1)⁻¹ * (C + 1) :=
          mul_lt_mul_of_pos_right hr (by positivity)
        _ = 1 := by field_simp
    calc
      q ^ r * C ≤ q ^ r * (C + 1) := by
        gcongr
        linarith
      _ ≤ 1 := hq.le
  have hqnonneg : 0 ≤ q ^ r := pow_nonneg (le_of_lt hπ.1) _
  have hcoeff_unit (a : A) : ‖algebraMap A L a‖ ≤ 1 := by
    have haK : algebraMap A K a ∈ closedUnitBall K := by
      rw [← hA]
      exact ⟨a, rfl⟩
    change ‖algebraMap A K a‖ ≤ 1 at haK
    calc
      ‖algebraMap A L a‖ =
          ‖algebraMap K L (algebraMap A K a)‖ := by
        rw [IsScalarTower.algebraMap_apply A K L]
      _ = ‖algebraMap A K a‖ := norm_algebraMap' _ _
      _ ≤ 1 := haK
  have hlattice_bound (y : L)
      (hy : y ∈ coordinateLattice A L (fun i => b i)) : ‖y‖ ≤ C := by
    rcases hy with ⟨a, rfl⟩
    dsimp [coordinateLattice, C] at *
    calc
      ‖∑ i, algebraMap A L (a i) * b i‖ ≤
          ∑ i, ‖algebraMap A L (a i) * b i‖ := norm_sum_le _ _
      _ ≤ ∑ i, ‖b i‖ := by
        gcongr with i hi
        rw [norm_mul]
        exact mul_le_of_le_one_left (norm_nonneg _) (hcoeff_unit (a i))
      _ ≤ max c₂ 1 * ∑ i, ‖b i‖ := by
        calc
          (∑ i, ‖b i‖) = 1 * ∑ i, ‖b i‖ := by ring
          _ ≤ max c₂ 1 * ∑ i, ‖b i‖ := by
            gcongr
            exact le_max_right _ _
  have hfirst :
      scaledSet A L (π ^ r) (coordinateLattice A L (fun i => b i)) ⊆
        closedUnitBall L := by
    intro x hx
    rcases hx with ⟨y, hy, rfl⟩
    change ‖algebraMap A L (π ^ r) * y‖ ≤ 1
    calc
      ‖algebraMap A L (π ^ r) * y‖ = q ^ r * ‖y‖ := by
        rw [norm_mul, map_pow, norm_pow]
        congr 1
        dsimp [q]
        rw [IsScalarTower.algebraMap_apply A K L, norm_algebraMap']
      _ ≤ q ^ r * C := mul_le_mul_of_nonneg_left (hlattice_bound y hy) hqnonneg
      _ ≤ 1 := hqC
  let D : ℝ := c₁⁻¹
  have hD : 0 ≤ D := by
    dsimp [D]
    exact le_of_lt (inv_pos.mpr hc₁)
  obtain ⟨s, hs⟩ :=
    exists_pow_lt_of_lt_one (x := (D + 1)⁻¹) (by dsimp [D]; positivity) hπ.2
  have hqD : q ^ s * D ≤ 1 := by
    have hq : q ^ s * (D + 1) < 1 := by
      calc
        q ^ s * (D + 1) < (D + 1)⁻¹ * (D + 1) :=
          mul_lt_mul_of_pos_right hs (by positivity)
        _ = 1 := by field_simp
    calc
      q ^ s * D ≤ q ^ s * (D + 1) := by
        gcongr
        linarith
      _ ≤ 1 := hq.le
  have hsecond :
      closedUnitBall L ⊆
        scaledByFieldElement L ((algebraMap A L π) ^ (-(s : ℤ)))
          (coordinateLattice A L (fun i => b i)) := by
    intro x hx
    change ‖x‖ ≤ 1 at hx
    have hcoord : coordinateNorm b x ≤ D := by
      have hnorm := (hnorms x).1
      dsimp [D]
      calc
        coordinateNorm b x = c₁⁻¹ * (c₁ * coordinateNorm b x) := by
          field_simp
        _ ≤ c₁⁻¹ * ‖x‖ :=
          mul_le_mul_of_nonneg_left hnorm (le_of_lt (inv_pos.mpr hc₁))
        _ ≤ c₁⁻¹ * 1 := by
          exact mul_le_mul_of_nonneg_left hx (le_of_lt (inv_pos.mpr hc₁))
        _ = c₁⁻¹ := by ring
    let coeff : Fin n → K := fun i => (algebraMap A K π) ^ s * b.repr x i
    have hcoeff_norm (i : Fin n) : ‖coeff i‖ ≤ 1 := by
      dsimp [coeff]
      calc
        ‖(algebraMap A K π) ^ s * b.repr x i‖ =
            q ^ s * ‖b.repr x i‖ := by
          rw [norm_mul, norm_pow]
        _ ≤ q ^ s * coordinateNorm b x := by
          gcongr
          exact Finset.single_le_sum (fun j _ => norm_nonneg _)
            (Finset.mem_univ i)
        _ ≤ q ^ s * D := mul_le_mul_of_nonneg_left hcoord
            (pow_nonneg (le_of_lt hπ.1) _)
        _ ≤ 1 := hqD
    have hcoeff_range (i : Fin n) : coeff i ∈ Set.range (algebraMap A K) := by
      rw [hA]
      exact hcoeff_norm i
    choose a ha using hcoeff_range
    have hx_repr : x = ∑ i, algebraMap K L (b.repr x i) * b i := by
      calc
        x = ∑ i, (b.repr x i) • b i := (b.sum_repr x).symm
        _ = ∑ i, algebraMap K L (b.repr x i) * b i := by
          simp [Algebra.smul_def]
    have hy : algebraMap A L (π ^ s) * x ∈
        coordinateLattice A L (fun i => b i) := by
      refine ⟨a, ?_⟩
      calc
        ∑ i, algebraMap A L (a i) * b i =
            ∑ i, algebraMap K L (coeff i) * b i := by
          apply Finset.sum_congr rfl
          intro i hi
          have hmap : algebraMap A L (a i) = algebraMap K L (coeff i) := by
            calc
              algebraMap A L (a i) =
                  algebraMap K L (algebraMap A K (a i)) :=
                IsScalarTower.algebraMap_apply A K L (a i)
              _ = algebraMap K L (coeff i) := by rw [ha i]
          exact congrArg (fun z : L => z * b i) hmap
        _ = algebraMap A L (π ^ s) * x := by
          rw [hx_repr]
          simp [coeff, ← IsScalarTower.algebraMap_apply A K L,
            map_pow, map_mul, Finset.mul_sum, mul_assoc]
    have hπL : algebraMap A L π ≠ 0 := by
      intro h
      have hK : algebraMap A K π = 0 := by
        apply FaithfulSMul.algebraMap_injective K L
        simpa [IsScalarTower.algebraMap_apply A K L] using h
      have hnormK : ‖algebraMap A K π‖ = 0 := by rw [hK, norm_zero]
      exact (ne_of_gt hπ.1) hnormK
    refine ⟨algebraMap A L (π ^ s) * x, hy, ?_⟩
    rw [map_pow, zpow_neg, zpow_natCast]
    calc
      ((algebraMap A L π) ^ s)⁻¹ *
          ((algebraMap A L π) ^ s * x) =
          (((algebraMap A L π) ^ s)⁻¹ * (algebraMap A L π) ^ s) * x := by ring
      _ = x := by rw [inv_mul_cancel₀ (pow_ne_zero s hπL), one_mul]
  exact ⟨r, s, hfirst, hsecond⟩

/-- The valuation unit ball is the valuation ring. -/
def valuationUnitBall
    {L Γ : Type*} [Field L] [LinearOrderedCommGroupWithZero Γ]
    (w : Valuation L Γ) : Set L :=
  {x | w x ≤ 1}

theorem valuation_subring_carrier_eq_unit_ball
    {L Γ : Type*} [Field L] [LinearOrderedCommGroupWithZero Γ]
    (w : Valuation L Γ) :
    (w.valuationSubring : Set L) = valuationUnitBall w := by
  rfl

/-- A finite module's multiplication endomorphism makes each element integral. -/
theorem determinant_trick_for_finite_algebra
    {A C : Type*} [CommRing A] [CommRing C] [Algebra A C]
    [Module.Finite A C] (x : C) : IsIntegral A x := by
  exact IsIntegral.of_finite A x

/-- The valuation unit ball is the integral closure of the base valuation ring. -/
theorem complete_extension_unit_ball_is_integral_closure
    {K L Γ : Type*} [Field K] [Field L]
    [LinearOrderedCommGroupWithZero Γ] [Algebra K L]
    (vK : Valuation K Γ) (w : Valuation L Γ)
    [vK.HasExtension w] [Algebra vK.valuationSubring L]
    [IsScalarTower vK.valuationSubring K L]
    [IsScalarTower vK.valuationSubring w.valuationSubring L]
    /- Formal correction: finiteness of the valuation-ring extension is the
       missing hypothesis for the reverse integral-closure inclusion. -/
    [Module.Finite vK.valuationSubring w.valuationSubring] :
    (w.valuationSubring : Set L) =
      {x : L | IsIntegral vK.valuationSubring x} := by
  ext x
  constructor
  · intro hx
    let x' : w.valuationSubring := ⟨x, hx⟩
    have hx' : IsIntegral vK.valuationSubring x' :=
      IsIntegral.of_finite vK.valuationSubring x'
    have hcoe : algebraMap w.valuationSubring L x' = x := by
      rfl
    rw [← hcoe]
    exact hx'.algebraMap
  · intro hx
    have hx' : IsIntegral w.valuationSubring x := hx.tower_top
    exact (Valuation.valuationSubring.integers w).isIntegral_iff_v_le_one.mp hx'

/-- The finite-dimensional lattice comparison makes the extended unit ball finite. -/
theorem complete_extension_unit_ball_is_finite
    {K L Γ : Type*} [Field K] [Field L]
    [LinearOrderedCommGroupWithZero Γ] [Algebra K L]
    (vK : Valuation K Γ) (w : Valuation L Γ)
    [vK.HasExtension w] [Valuation.IsRankOneDiscrete vK]
    [Valuation.IsRankOneDiscrete w] [Module.Finite K L]
    (hcomplete : IsAdicComplete
      (IsLocalRing.maximalIdeal vK.valuationSubring) vK.valuationSubring) :
    Module.Finite vK.valuationSubring w.valuationSubring := by
  sorry

/-- The valuation ring in a finite complete extension is torsion-free over the base. -/
theorem complete_extension_unit_ball_is_torsion_free
    {K L Γ : Type*} [Field K] [Field L]
    [LinearOrderedCommGroupWithZero Γ] [Algebra K L]
    (vK : Valuation K Γ) (w : Valuation L Γ)
    [vK.HasExtension w] :
    ∀ (a : vK.valuationSubring), ∀ x : w.valuationSubring,
      a ≠ 0 → a • x = 0 → x = 0 := by
  intro a x ha hax
  apply Subtype.ext
  have haK : (a : K) ≠ 0 := by
    intro haK
    apply ha
    exact Subtype.ext haK
  have haL : algebraMap K L (a : K) ≠ 0 := by
    intro hzero
    apply haK
    apply FaithfulSMul.algebraMap_injective K L
    simpa using hzero
  have hax' : algebraMap K L (a : K) * (x : L) = 0 := by
    have h := congrArg (fun y : w.valuationSubring => (y : L)) hax
    simpa [Algebra.smul_def,
      Valuation.HasExtension.coe_algebraMap_valuationSubring_eq] using h
  rcases mul_eq_zero.mp hax' with hzero | hzero
  · exact (haL hzero).elim
  · exact hzero

/-- Finite torsion-free modules over the base DVR are finite free. -/
theorem finite_torsion_free_over_dvr_is_free
    {A M : Type*} [CommRing A] [IsDomain A]
    [IsDiscreteValuationRing A] [AddCommGroup M] [Module A M]
    [Module.Finite A M]
    (htf : ∀ (a : A), ∀ x : M, a ≠ 0 → a • x = 0 → x = 0) :
    Module.Free A M := by
  let _ : Module.IsTorsionFree A M :=
    Module.IsTorsionFree.of_smul_eq_zero (by
      intro a x hax
      rcases eq_or_ne a 0 with rfl | ha
      · exact Or.inl rfl
      · exact Or.inr (htf a x ha hax))
  infer_instance

/-- The structural theorem for the valuation ring of a finite complete extension. -/
theorem finite_complete_extension_valuation_ring
    {K L Γ : Type*} [Field K] [Field L]
    [LinearOrderedCommGroupWithZero Γ] [Algebra K L]
    (vK : Valuation K Γ) (w : Valuation L Γ)
    [vK.HasExtension w] [Valuation.IsRankOneDiscrete vK]
    [Valuation.IsRankOneDiscrete w] [Module.Finite K L]
    (hcomplete : IsAdicComplete
      (IsLocalRing.maximalIdeal vK.valuationSubring) vK.valuationSubring) :
    Module.Finite vK.valuationSubring w.valuationSubring ∧
    Module.Free vK.valuationSubring w.valuationSubring ∧
      IsAdicComplete (IsLocalRing.maximalIdeal w.valuationSubring)
        w.valuationSubring ∧
      IsDiscreteValuationRing w.valuationSubring ∧
      (w.valuationSubring : Set L) =
        (integralClosure vK.valuationSubring L : Set L) := by
  sorry

/-- The maximal ideal extension and residue degree formulas in the complete case. -/
theorem complete_extension_ideal_and_residue_formulas
    {K L Γ : Type*} [Field K] [Field L]
    [LinearOrderedCommGroupWithZero Γ] [Algebra K L]
    (vK : Valuation K Γ) (w : Valuation L Γ)
    [vK.HasExtension w] [Valuation.IsRankOneDiscrete vK]
    [Valuation.IsRankOneDiscrete w] [Module.Finite K L]
    (e f : ℕ) (he : chapterRamificationIndex vK.valuationSubring
      w.valuationSubring (IsLocalRing.maximalIdeal w.valuationSubring) = e)
    (hf : chapterResidueDegree vK.valuationSubring
      w.valuationSubring (IsLocalRing.maximalIdeal w.valuationSubring) = f)
    (hcomplete : IsAdicComplete
      (IsLocalRing.maximalIdeal vK.valuationSubring) vK.valuationSubring) :
    (IsLocalRing.maximalIdeal vK.valuationSubring).map
        (algebraMap vK.valuationSubring w.valuationSubring) =
      (IsLocalRing.maximalIdeal w.valuationSubring) ^ e ∧
      Module.finrank (IsLocalRing.ResidueField vK.valuationSubring)
          (IsLocalRing.ResidueField w.valuationSubring) = f ∧
      Module.finrank K L = e * f := by
  sorry

/-- The degree equality needs neither separability nor perfection hypotheses. -/
theorem complete_extension_defectless_without_separability
    {K L Γ : Type*} [Field K] [Field L]
    [LinearOrderedCommGroupWithZero Γ] [Algebra K L]
    (vK : Valuation K Γ) (w : Valuation L Γ)
    [vK.HasExtension w] [Valuation.IsRankOneDiscrete vK]
    [Valuation.IsRankOneDiscrete w] [Module.Finite K L]
    (hcomplete : IsAdicComplete
      (IsLocalRing.maximalIdeal vK.valuationSubring) vK.valuationSubring) :
    Module.finrank K L =
      chapterRamificationIndex vK.valuationSubring w.valuationSubring
        (IsLocalRing.maximalIdeal w.valuationSubring) *
      chapterResidueDegree vK.valuationSubring w.valuationSubring
        (IsLocalRing.maximalIdeal w.valuationSubring) := by
  have h := complete_extension_ideal_and_residue_formulas vK w
    (chapterRamificationIndex vK.valuationSubring w.valuationSubring
      (IsLocalRing.maximalIdeal w.valuationSubring))
    (chapterResidueDegree vK.valuationSubring w.valuationSubring
      (IsLocalRing.maximalIdeal w.valuationSubring)) rfl rfl hcomplete
  exact h.2.2

/-! ## 12.7. Unramified and totally ramified endpoints -/

/-- The foundational unramified condition: `e = 1` and separable residue extension. -/
def foundationalUnramified (e : ℕ) (residueSeparable : Prop) : Prop :=
  e = 1 ∧ residueSeparable

/-- The foundational totally ramified condition: `f = 1`. -/
def foundationalTotallyRamified (f : ℕ) : Prop :=
  f = 1

/-- The two endpoint degree allocations in a defectless complete extension. -/
theorem endpoint_degree_allocations
    (degree e f : ℕ) (hdegree : degree = e * f)
    (hunramified : e = 1) (htotallyRamified : f = 1) :
    degree = f ∧ degree = e := by
  constructor
  · simpa [hunramified] using hdegree
  · simpa [htotallyRamified] using hdegree

/-- A monic irreducible separable residue polynomial prescribes the unramified
    branch invariants after a monic lift and a chosen root. -/
theorem separable_residue_polynomial_lift_is_unramified
    {A K L Γ : Type*} [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    [Field K] [Field L] [Algebra A K] [IsFractionRing A K]
    [Algebra K L] [Algebra A L] [IsScalarTower A K L]
    [LinearOrderedCommGroupWithZero Γ]
    (vK : Valuation K Γ) (w : Valuation L Γ)
    [vK.HasExtension w] [Valuation.IsRankOneDiscrete vK]
    [Valuation.IsRankOneDiscrete w]
    [IsAdicComplete (IsLocalRing.maximalIdeal A) A]
    (fbar : (A ⧸ IsLocalRing.maximalIdeal A)[X]) (f : A[X]) (Pi : L)
    (hmonic : fbar.Monic ∧ f.Monic)
    (hirreducible : Irreducible fbar)
    (hseparable : fbar.Separable)
    (hlift : f.map (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A)) = fbar)
    (hroot : aeval Pi (f.map (algebraMap A K)) = 0)
    (hgenerates : Algebra.adjoin K ({Pi} : Set L) = ⊤)
    (hbaseIntegers : vK.Integers A)
    (hbaseValuationRing :
      (vK.valuationSubring : Set K) = Set.range (algebraMap A K))
    (hupperIntegralClosure :
      (w.valuationSubring : Set L) = (integralClosure A L : Set L)) :
    Irreducible (f.map (algebraMap A K)) ∧
      Module.finrank K L = fbar.natDegree ∧
      chapterRamificationIndex vK.valuationSubring w.valuationSubring
          (IsLocalRing.maximalIdeal w.valuationSubring) = 1 ∧
      chapterResidueDegree vK.valuationSubring w.valuationSubring
          (IsLocalRing.maximalIdeal w.valuationSubring) = fbar.natDegree := by
  sorry

/-- Eisenstein polynomials in the form used by the chapter. -/
def IsEisensteinAt
    {A : Type*} [CommRing A] [IsLocalRing A]
    (π : A) (f : A[X]) : Prop :=
  f.Monic ∧ 0 < f.natDegree ∧
    (∀ i < f.natDegree, f.coeff i ∈ Ideal.span {π}) ∧
    f.constantCoeff ∉ Ideal.span {π ^ 2} ∧
    Ideal.span {π} = IsLocalRing.maximalIdeal A

/-- The power-basis expansion associated to a root of an Eisenstein polynomial. -/
def eisensteinExpansion
    {K L : Type*} [Field K] [Field L] [Algebra K L]
    {n : ℕ} (Pi : L) (a : Fin n → K) : L :=
  ∑ i, algebraMap K L (a i) * Pi ^ (i : ℕ)

/-- Coefficients are integral exactly when they lie in the base localization ring. -/
def coefficientsAreIntegral
    {A K : Type*} [CommRing A] [Field K] [Algebra A K]
    {n : ℕ} (a : Fin n → K) : Prop :=
  ∀ i, IsLocalization.IsInteger A (a i)

/-- The power-basis expansion is unique for an Eisenstein root. -/
theorem eisenstein_power_basis_expansion_unique
    {A K L : Type*} [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    [Field K] [Field L] [Algebra A K] [IsFractionRing A K]
    [Algebra K L] [Algebra A L] [IsScalarTower A K L]
    {n : ℕ} (π : A) (f : A[X]) (Pi : L)
    (hf : IsEisensteinAt π f) (hroot : aeval Pi f = 0)
    (hdegree : f.natDegree = n)
    (hgenerates : Algebra.adjoin K ({Pi} : Set L) = ⊤) :
    ∀ x : L, ∃! a : Fin n → K, x = eisensteinExpansion Pi a := by
  have hspan : Ideal.span ({π} : Set A) = IsLocalRing.maximalIdeal A := hf.2.2.2.2
  let _ : (Ideal.span ({π} : Set A)).IsPrime := by
    rw [hspan]
    infer_instance
  have hE : f.IsEisensteinAt (Ideal.span ({π} : Set A)) := by
    apply hf.1.isEisensteinAt_of_mem_of_notMem
    · rw [hspan]
      exact (IsLocalRing.maximalIdeal.isMaximal A).ne_top
    · intro i hi
      exact hf.2.2.1 i hi
    · simpa [Ideal.span_singleton_pow] using hf.2.2.2.1
  have hprimitive : f.IsPrimitive := hf.1.isPrimitive
  have hirrA : Irreducible f :=
    hE.irreducible inferInstance hprimitive hf.2.1
  have hirrK : Irreducible (f.map (algebraMap A K)) :=
    (hprimitive.irreducible_iff_irreducible_map_fraction_map).mp hirrA
  have hrootK : aeval Pi (f.map (algebraMap A K)) = 0 := by
    simpa only [aeval_map_algebraMap, IsScalarTower.algebraMap_eq A K L] using hroot
  have hmapMonic : (f.map (algebraMap A K)).Monic := hf.1.map (algebraMap A K)
  have hmin : f.map (algebraMap A K) = minpoly K Pi :=
    minpoly.eq_of_irreducible_of_monic hirrK hrootK hmapMonic
  have hPiIntegral : IsIntegral K Pi := ⟨f.map (algebraMap A K), hmapMonic, hrootK⟩
  let B : PowerBasis K L := PowerBasis.ofAdjoinEqTop hPiIntegral hgenerates
  have hBgen : B.gen = Pi := by
    exact PowerBasis.ofAdjoinEqTop_gen hPiIntegral hgenerates
  have hBdim : B.dim = n := by
    rw [PowerBasis.ofAdjoinEqTop_dim, ← hmin,
      natDegree_map_eq_of_injective (IsFractionRing.injective A K), hdegree]
  let e : Fin n ≃ Fin B.dim := finCongr hBdim.symm
  intro x
  let a : Fin n → K := fun i => B.basis.repr x (e i)
  have hsumB : x = ∑ j, algebraMap K L (B.basis.repr x j) * Pi ^ (j : ℕ) := by
    calc
      x = ∑ j, B.basis.repr x j • B.basis j := (B.basis.sum_repr x).symm
      _ = ∑ j, algebraMap K L (B.basis.repr x j) * Pi ^ (j : ℕ) := by
        simp [B.basis_eq_pow, hBgen, Algebra.smul_def]
  have hsum : x = ∑ i, algebraMap K L (a i) * Pi ^ (i : ℕ) := by
    calc
      x = ∑ j, algebraMap K L (B.basis.repr x j) * Pi ^ (j : ℕ) := hsumB
      _ = ∑ i, algebraMap K L (a i) * Pi ^ (i : ℕ) := by
        symm
        refine Fintype.sum_equiv e _ _ ?_
        intro i
        rfl
  refine ⟨a, ?_, ?_⟩
  · simpa [eisensteinExpansion] using hsum
  · intro b hb
    have hexpand (c : Fin n → K) :
        (∑ i, algebraMap K L (c i) * Pi ^ (i : ℕ)) =
          ∑ j, c (e.symm j) • B.basis j := by
      calc
        (∑ i, algebraMap K L (c i) * Pi ^ (i : ℕ)) =
            ∑ i, c i • B.basis (e i) := by
              simp [e, B.basis_eq_pow, hBgen, Algebra.smul_def]
        _ = ∑ j, c (e.symm j) • B.basis j := by
          refine Fintype.sum_equiv e _ _ ?_
          intro i
          simp
    have hcoords :
        (fun j => a (e.symm j)) = (fun j => b (e.symm j)) := by
      have hEq :
          (∑ j, a (e.symm j) • B.basis j) =
            ∑ j, b (e.symm j) • B.basis j := by
        rw [← hexpand a, ← hexpand b]
        exact hsum.symm.trans hb
      have hrepr := congrArg (fun y : L => B.basis.repr y) hEq
      funext j
      have hj := congrArg (fun z : Fin B.dim →₀ K => z j) hrepr
      simpa only [B.basis.repr_sum_self] using hj
    funext i
    exact (congrFun hcoords (e i)).symm

/-- The valuation of the `i`th power-basis term has value congruent to `i mod n`. -/
theorem eisenstein_term_values_are_distinct_modulo_degree
    {n : ℕ} (ω : ℕ → ℤ) (a : Fin n → ℕ) :
    ∀ i j : Fin n, i ≠ j →
      ((n : ℤ) * ω (a i) + (i : ℤ)) % (n : ℤ) ≠
        ((n : ℤ) * ω (a j) + (j : ℤ)) % (n : ℤ) := by
  intro i j hij
  have hn : 0 < n := by
    have hi := i.isLt
    omega
  have hi0 : 0 ≤ (i : ℤ) := by omega
  have hj0 : 0 ≤ (j : ℤ) := by omega
  have hin : (i : ℤ) < (n : ℤ) := by exact_mod_cast i.isLt
  have hjn : (j : ℤ) < (n : ℤ) := by exact_mod_cast j.isLt
  have hmi : ((n : ℤ) * ω (a i) + (i : ℤ)) % (n : ℤ) = (i : ℤ) := by
    rw [show (n : ℤ) * ω (a i) + (i : ℤ) =
        (i : ℤ) + (n : ℤ) * ω (a i) by ring,
      Int.add_mul_emod_self_left, Int.emod_eq_of_lt hi0 hin]
  have hmj : ((n : ℤ) * ω (a j) + (j : ℤ)) % (n : ℤ) = (j : ℤ) := by
    rw [show (n : ℤ) * ω (a j) + (j : ℤ) =
        (j : ℤ) + (n : ℤ) * ω (a j) by ring,
      Int.add_mul_emod_self_left, Int.emod_eq_of_lt hj0 hjn]
  rw [hmi, hmj]
  intro heq
  apply hij
  apply Fin.ext
  exact_mod_cast heq

/-- A strictly least nonzero term cannot cancel in a nonarchimedean sum. -/
theorem least_valued_term_does_not_cancel
    {L Γ : Type*} [Ring L] [LinearOrderedCommMonoidWithZero Γ]
    (w : Valuation L Γ) {ι : Type*} [Fintype ι] [Nonempty ι]
    (terms : ι → L) (i₀ : ι)
    /- Formal correction: with Mathlib's multiplicative valuation order, the
       dominant term is the strictly greatest-valued one. -/
    (hgreatest : ∀ j, j ≠ i₀ → w (terms j) < w (terms i₀))
    (hnonzero : terms i₀ ≠ 0) :
    w (∑ i, terms i) = w (terms i₀) := by
  classical
  by_cases hzero : terms i₀ = 0
  · exact (hnonzero hzero).elim
  · apply w.map_sum_eq_of_lt (s := Finset.univ) (j := i₀)
    · simp
    · intro i hi
      have hi' : i ≠ i₀ := by simpa using hi
      exact hgreatest i hi'

/-- Integrality of an Eisenstein expansion is equivalent to integral coefficients. -/
theorem eisenstein_expansion_integrality_iff
    {A K L : Type*} [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    [Field K] [Field L] [Algebra A K] [IsFractionRing A K]
    [Algebra K L] [Algebra A L] [IsScalarTower A K L]
    {n : ℕ} (π : A) (f : A[X]) (Pi : L)
    (hf : IsEisensteinAt π f) (hroot : aeval Pi f = 0)
    (hdegree : f.natDegree = n)
    (hgenerates : Algebra.adjoin K ({Pi} : Set L) = ⊤)
    (a : Fin n → K) :
    IsIntegral A (eisensteinExpansion Pi a) ↔
      ∀ i, IsLocalization.IsInteger A (a i) := by
  sorry

/-- A uniformizer is characterized by generating the maximal ideal. -/
def isUniformizerElement
    (R : Type*) [CommRing R] [IsLocalRing R] (π : R) : Prop :=
  π ∈ IsLocalRing.maximalIdeal R ∧
    IsLocalRing.maximalIdeal R = Ideal.span {π}

/-- An Eisenstein root is a uniformizer and has ramification index equal to the degree. -/
theorem eisenstein_root_is_uniformizer_and_totally_ramified
    {A K L Γ : Type*} [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    [Field K] [Field L] [Algebra A K] [IsFractionRing A K]
    [LinearOrderedCommGroupWithZero Γ] [Algebra K L]
    [Algebra A L] [IsScalarTower A K L]
    (vK : Valuation K Γ) (v : Valuation L Γ) [vK.HasExtension v]
    [Valuation.IsRankOneDiscrete vK] [Valuation.IsRankOneDiscrete v]
    {n : ℕ} (π : A) (f : A[X]) (Pi : L)
    (hf : IsEisensteinAt π f) (hroot : aeval Pi f = 0)
    (hdegree : f.natDegree = n)
    (hgenerates : Algebra.adjoin K ({Pi} : Set L) = ⊤)
    (hvaluation : v Pi = Valuation.IsRankOneDiscrete.generator v)
    (hbaseIntegers : vK.Integers A)
    (hbaseValuationRing :
      (vK.valuationSubring : Set K) = Set.range (algebraMap A K))
    (hupperIntegralClosure :
      (v.valuationSubring : Set L) = (integralClosure A L : Set L)) :
    v.IsUniformizer Pi ∧
      chapterRamificationIndex vK.valuationSubring v.valuationSubring
          (IsLocalRing.maximalIdeal v.valuationSubring) = n ∧
      chapterResidueDegree vK.valuationSubring v.valuationSubring
          (IsLocalRing.maximalIdeal v.valuationSubring) = 1 ∧
      ∀ a : K, v (algebraMap K L a) = (vK a) ^ n := by
  sorry

/-- The residue field does not change in an Eisenstein extension. -/
theorem eisenstein_residue_field_is_unchanged
    {A K L : Type*} [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    [Field K] [Field L] [Algebra A K] [IsFractionRing A K]
    [Algebra K L] [Algebra A L] [IsScalarTower A K L]
    {n : ℕ} (π : A) (f : A[X]) (Pi : L)
    [IsLocalRing (Algebra.adjoin A ({Pi} : Set L))]
    (hf : IsEisensteinAt π f) (hroot : aeval Pi f = 0)
    (hdegree : f.natDegree = n) :
    Nonempty
      ((A ⧸ IsLocalRing.maximalIdeal A) ≃+*
        (Algebra.adjoin A ({Pi} : Set L) ⧸
          IsLocalRing.maximalIdeal (Algebra.adjoin A ({Pi} : Set L)))) := by
  have hAinj : Function.Injective (algebraMap A L) := by
    rw [IsScalarTower.algebraMap_eq A K L]
    exact (algebraMap K L).injective.comp (IsFractionRing.injective A K)
  let B := Algebra.adjoin A ({Pi} : Set L)
  have hPiIntegral : IsIntegral A Pi := ⟨f, hf.1, hroot⟩
  let _ : Algebra.IsIntegral A B := by
    apply Algebra.IsIntegral.adjoin
    intro x hx
    rw [Set.mem_singleton_iff] at hx
    subst x
    exact hPiIntegral
  let _ : FaithfulSMul A B :=
    (faithfulSMul_iff_injective_smul_one A B).mpr (by
      intro a b hab
      apply hAinj
      have h := congrArg (fun x : B => (x : L)) (hab)
      have h' : ((algebraMap A B a : B) : L) =
          ((algebraMap A B b : B) : L) := by
        simpa only [Algebra.smul_def, map_mul, map_one, mul_one] using h
      calc
        algebraMap A L a = algebraMap B L (algebraMap A B a) :=
          (IsScalarTower.algebraMap_apply A B L a).symm
        _ = ((algebraMap A B a : B) : L) := rfl
        _ = ((algebraMap A B b : B) : L) := h'
        _ = algebraMap B L (algebraMap A B b) := rfl
        _ = algebraMap A L b := IsScalarTower.algebraMap_apply A B L b)
  have hmcomap :
      (IsLocalRing.maximalIdeal B).comap (algebraMap A B) =
        IsLocalRing.maximalIdeal A := by
    exact IsLocalRing.maximalIdeal_comap (algebraMap A B)
  let piB : B := ⟨Pi, Algebra.subset_adjoin (Set.mem_singleton Pi)⟩
  have hrootB : aeval piB f = 0 := by
    apply Subtype.ext
    change (algebraMap B L) (aeval piB f) = 0
    rw [aeval_def, hom_eval₂]
    change eval₂ ((algebraMap B L).comp (algebraMap A B)) Pi f = 0
    rw [← IsScalarTower.algebraMap_eq A B L]
    simpa [aeval_def] using hroot
  let _ : Nontrivial B := by
    refine ⟨0, 1, ?_⟩
    intro h
    have h' := congrArg (fun x : B => (x : L)) h
    exact zero_ne_one h'
  let _ : (IsLocalRing.maximalIdeal B).IsPrime :=
    (IsLocalRing.maximalIdeal.isMaximal B).isPrime
  let _ : Nontrivial (B ⧸ IsLocalRing.maximalIdeal B) :=
    Ideal.Quotient.nontrivial_iff.mpr (IsLocalRing.maximalIdeal.isMaximal B).ne_top
  let qB : B →+* (B ⧸ IsLocalRing.maximalIdeal B) :=
    Ideal.Quotient.mk (IsLocalRing.maximalIdeal B)
  let qA : A →+* (B ⧸ IsLocalRing.maximalIdeal B) :=
    qB.comp (algebraMap A B)
  have hcoeff_zero (i : ℕ) (hi : i < n) : qA (f.coeff i) = 0 := by
    have hfi : f.coeff i ∈ IsLocalRing.maximalIdeal A := by
      have hfi' := hf.2.2.1 i (by simpa [hdegree] using hi)
      rw [hf.2.2.2.2] at hfi'
      exact hfi'
    have hfi' : f.coeff i ∈
        (IsLocalRing.maximalIdeal B).comap (algebraMap A B) := by
      rw [hmcomap]
      exact hfi
    change qB (algebraMap A B (f.coeff i)) = 0
    rw [Ideal.Quotient.eq_zero_iff_mem]
    exact hfi'
  have hmap_poly : f.map qA = (X ^ n : (B ⧸ IsLocalRing.maximalIdeal B)[X]) := by
    apply Polynomial.ext
    intro i
    by_cases hi : i < n
    · rw [coeff_map, hcoeff_zero i hi, coeff_X_pow, if_neg (Nat.ne_of_lt hi)]
    · by_cases hin : i = n
      · subst i
        rw [coeff_map, ← hdegree, hf.1.coeff_natDegree, map_one,
          coeff_X_pow_self]
      · have hni : n < i := Nat.lt_of_le_of_ne (Nat.le_of_not_gt hi) (Ne.symm hin)
        have hfi : f.coeff i = 0 := by
          apply coeff_eq_zero_of_natDegree_lt
          simpa [hdegree] using hni
        rw [coeff_map, hfi, map_zero, coeff_X_pow, if_neg hin]
  have hrootQ :
      (f.map qA).eval (qB piB) = 0 := by
    change (f.map qA).eval₂ (RingHom.id _) (qB piB) = 0
    rw [eval₂_map]
    have hcomp : (RingHom.id _).comp qA = qB.comp (algebraMap A B) := by
      ext a
      rfl
    rw [hcomp]
    have hq := congrArg qB hrootB
    rw [aeval_def, hom_eval₂] at hq
    exact hq
  have hpiQ : qB piB = 0 := by
    rw [hmap_poly] at hrootQ
    have hz : qB piB = 0 ∧ ¬n = 0 := by simpa using hrootQ
    exact hz.1
  let qMap : A ⧸ IsLocalRing.maximalIdeal A →+*
      B ⧸ IsLocalRing.maximalIdeal B :=
    Ideal.quotientMap (IsLocalRing.maximalIdeal B) (algebraMap A B) hmcomap.ge
  have hsurj : Function.Surjective qMap := by
    intro y
    refine Quotient.inductionOn' y ?_
    intro b
    have hb : (b : L) ∈ B := b.property
    refine Algebra.adjoin_induction
      (p := fun x hx => ∃ u, qMap u = qB ⟨x, hx⟩) ?_ ?_ ?_ ?_ hb
    · intro x hx
      rw [Set.mem_singleton_iff] at hx
      subst x
      exact ⟨0, by simpa [qMap, qB] using hpiQ.symm⟩
    · intro a
      refine ⟨Ideal.Quotient.mk (IsLocalRing.maximalIdeal A) a, ?_⟩
      rfl
    · intro x z hx hz hxh hzh
      rcases hxh with ⟨u, hu⟩
      rcases hzh with ⟨v, hv⟩
      refine ⟨u + v, ?_⟩
      simpa only [map_add, hu, hv] using
        (show qMap (u + v) = qB ⟨x + z, add_mem hx hz⟩ by
          rw [map_add, hu, hv, ← qB.map_add]
          rfl)
    · intro x z hx hz hxh hzh
      rcases hxh with ⟨u, hu⟩
      rcases hzh with ⟨v, hv⟩
      refine ⟨u * v, ?_⟩
      simpa only [map_mul, hu, hv] using
        (show qMap (u * v) = qB ⟨x * z, mul_mem hx hz⟩ by
          rw [map_mul, hu, hv, ← qB.map_mul]
          rfl)
  have hinj : Function.Injective qMap := by
    apply Ideal.quotientMap_injective'
    exact hmcomap.le
  exact ⟨RingEquiv.ofBijective qMap ⟨hinj, hsurj⟩⟩

/-- The Eisenstein order is generated by the root. -/
theorem eisenstein_integral_closure_is_root_order
    {A K L : Type*} [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    [Field K] [Field L] [Algebra A K] [IsFractionRing A K]
    [Algebra K L] [Algebra A L] [IsScalarTower A K L]
    {n : ℕ} (π : A) (f : A[X]) (Pi : L)
    (hf : IsEisensteinAt π f) (hroot : aeval Pi f = 0)
    (hdegree : f.natDegree = n)
    (hgenerates : Algebra.adjoin K ({Pi} : Set L) = ⊤) :
    (integralClosure A L : Set L) =
      (Algebra.adjoin A ({Pi} : Set L) : Set L) := by
  sorry

/-! ## 12.8. Synthesis and the final degree formula -/

/-- Total divisibility is the intrinsic characterization of a valuation ring. -/
theorem valuation_ring_total_divisibility_characterization
    {A K : Type*} [CommRing A] [IsDomain A] [Field K]
    [Algebra A K] [IsFractionRing A K] :
    ValuationRing A ↔ @Std.Total A (· ∣ ·) := by
  exact ValuationRing.iff_dvd_total (R := A)

/-- The finite-precision quotients of a DVR. -/
abbrev dvrPrecisionQuotient
    (A : Type*) [CommRing A] [IsLocalRing A]
    (n : ℕ) : Type _ :=
  A ⧸ (IsLocalRing.maximalIdeal A) ^ n

/-- Length recovers the order of a finite-precision DVR quotient. -/
theorem dvr_precision_length_recovers_order
    {A : Type*} [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    (n : ℕ) :
    Module.length A (dvrPrecisionQuotient A (n + 1)) = n + 1 := by
  simpa [dvrPrecisionQuotient] using
    (IsDiscreteValuationRing.length_quotient_pow_maximalIdeal A (n + 1))

/-- “Terms vanish” as a topological formulation of convergence of a series. -/
def termsVanishAtInfinity {K : Type*} [TopologicalSpace K] [Zero K]
    (u : ℕ → K) : Prop :=
  Filter.Tendsto u Filter.atTop (𝓝 0)

def seriesConverges {K : Type*} [TopologicalSpace K] [AddCommMonoid K]
    (u : ℕ → K) : Prop :=
  Summable u

/-- Complete nonarchimedean fields satisfy the series criterion. -/
theorem complete_nonarchimedean_series_criterion
    {K Γ : Type*} [Field K] [LinearOrderedCommGroupWithZero Γ]
    [Valued K Γ] [CompleteSpace K] [NonarchimedeanAddGroup K] :
    ∀ u : ℕ → K, seriesConverges u ↔ termsVanishAtInfinity u := by
  intro u
  change Summable u ↔ Filter.Tendsto u Filter.atTop (𝓝 0)
  rw [NonarchimedeanAddGroup.summable_iff_tendsto_cofinite_zero]
  simp only [Nat.cofinite_eq_atTop]

/-- One Newton correction, used in the henselian/completion bridge. -/
def newtonStep {K : Type*} [Field K] (f : K[X]) (x : K) : K :=
  x - f.eval x / f.derivative.eval x

/-- Newton's step can be formed in a ring once the derivative unit is named. -/
def newtonStepInRing {A : Type*} [CommRing A] (f : A[X]) (x : A) (u : Aˣ) : A :=
  x - f.eval x * (↑(u⁻¹) : A)

/-- Newton corrections improve the precision quadratically under the simple-root hypotheses. -/
theorem newton_step_accelerates_precision
    {A : Type*} [CommRing A]
    (I : Ideal A) (f : A[X]) (x : A) (u : Aˣ) (n : ℕ)
    (hderivative : (u : A) = f.derivative.eval x)
    (hresidual : f.eval x ∈ I ^ n) :
    f.eval (newtonStepInRing f x u) ∈ I ^ (2 * n) := by
  let y : A := -(f.eval x * (↑(u⁻¹) : A))
  have hy : y ∈ I ^ n := by
    dsimp [y]
    rw [Ideal.neg_mem_iff]
    simpa [mul_comm] using (I ^ n).mul_mem_left (↑(u⁻¹) : A) hresidual
  have hy2 : y ^ 2 ∈ I ^ (2 * n) := by
    rw [show 2 * n = n + n by omega, pow_add]
    simpa [pow_two] using (Ideal.mul_mem_mul hy hy)
  have hlin : f.derivative.eval x * y + f.eval x = 0 := by
    dsimp [y]
    rw [← hderivative]
    calc
      ↑u * -(f.eval x * (↑(u⁻¹) : A)) + f.eval x =
          -(f.eval x * (↑u * (↑(u⁻¹) : A))) + f.eval x := by ring
      _ = 0 := by simp
  obtain ⟨c, hc⟩ := Polynomial.exists_mul_sq_add_linear_part_eq_eval_add f x y
  have hxy : x + y = newtonStepInRing f x u := by
    simp [newtonStepInRing, y, sub_eq_add_neg]
  rw [← hxy, ← hc]
  rw [show c * y ^ 2 + f.derivative.eval x * y + f.eval x =
      c * y ^ 2 + (f.derivative.eval x * y + f.eval x) by ring]
  rw [hlin, add_zero]
  exact (I ^ (2 * n)).mul_mem_left c hy2

/-- The field-valued Newton definition satisfies its elementary cancellation identity. -/
theorem newton_step_identity
    {K : Type*} [Field K] (f : K[X]) (x : K)
    (hderivative : f.derivative.eval x ≠ 0) :
    newtonStep f x * f.derivative.eval x =
      x * f.derivative.eval x - f.eval x := by
  unfold newtonStep
  rw [sub_mul, div_mul_cancel₀ _ hderivative]

/-- Fundamental equality in the finite flat algebra formulation. -/
theorem final_sum_ramification_times_residue_degree
    {R S : Type*} [CommRing R] [CommRing S] [Algebra R S]
    (p : Ideal R) [p.IsPrime] [IsDomain R]
    [Module.Finite R S] [Module.Flat R S] [Fintype (p.primesOver S)] :
    ∑ q : p.primesOver S,
        q.1.ramificationIdx R * q.1.inertiaDeg R = Module.finrank R S := by
  exact Ideal.sum_ramification_inertia_eq_finrank p S

/-- The fraction-field reading of the same equality is `∑ e f = [L : K]`. -/
theorem final_fraction_field_degree_formula
    {R S : Type*} [CommRing R] [CommRing S] [IsDomain S] [Algebra R S]
    (p : Ideal R) [p.IsPrime] [IsDomain R]
    [Algebra (FractionRing R) (FractionRing S)]
    [Module.Finite R S] [Module.Flat R S] [Fintype (p.primesOver S)]
    (hfrac : Module.finrank R S =
      Module.finrank (FractionRing R) (FractionRing S)) :
    ∑ q : p.primesOver S,
        q.1.ramificationIdx R * q.1.inertiaDeg R =
      Module.finrank (FractionRing R) (FractionRing S) := by
  calc
    ∑ q : p.primesOver S, q.1.ramificationIdx R * q.1.inertiaDeg R =
        Module.finrank R S := Ideal.sum_ramification_inertia_eq_finrank p S
    _ = Module.finrank (FractionRing R) (FractionRing S) := hfrac

/-- A complete or henselian base has one valuation branch in a finite algebraic extension. -/
theorem complete_or_henselian_base_has_one_branch
    {K Γ E : Type u} [Field K] [Field E]
    [LinearOrderedCommGroupWithZero Γ] [Algebra K E]
    (v : Valuation K Γ)
    [Algebra.IsAlgebraic K E]
    (hbase : HenselianLocalRing v.valuationSubring ∨
      IsAdicComplete (IsLocalRing.maximalIdeal v.valuationSubring)
        v.valuationSubring) :
    ∃ W : HeterogeneousValuationExtension v E,
      ∀ W' : HeterogeneousValuationExtension v E,
        (letI : LinearOrderedCommGroupWithZero W.valueGroup := W.orderedValueGroup
         letI : LinearOrderedCommGroupWithZero W'.valueGroup := W'.orderedValueGroup
        W'.valuation.IsEquiv W.valuation) := by
  sorry

/-- Concrete data for the final local arithmetic dictionary. -/
structure Chapter12LocalArithmeticDictionary
    {A K B L : Type*} [CommRing A] [Field K] [CommRing B] [Field L]
    [IsLocalRing A] [Algebra A K] [Algebra A B] [Algebra K L] [Algebra B L]
    (P : Ideal B) [P.IsPrime]
    (v : Valuation K ℤᵐ⁰) (w : Valuation L ℤᵐ⁰) where
  baseMaximalIdeal : Ideal A
  baseMaximalIdeal_eq : baseMaximalIdeal = IsLocalRing.maximalIdeal A
  extension : v.IsEquiv (w.comap (algebraMap K L))
  prime_isMaximal : P.IsMaximal
  center : ∀ x : B, x ∈ P ↔ w (algebraMap B L x) < 1
  localizationMap : B →+* branchLocalization B P
  completionMap : branchLocalization B P →+* branchCompletion B P
  fractionFieldMap : branchCompletion B P →+* branchFractionField B P

/-- The final dictionary links valuation, ring, residue, precision, completion, and branches. -/
theorem local_arithmetic_dictionary
    {A K B L : Type*} [CommRing A] [Field K] [CommRing B] [Field L]
    [IsLocalRing A] [Algebra A K] [Algebra A B] [Algebra K L] [Algebra B L]
    (P : Ideal B) [P.IsPrime]
    (v : Valuation K ℤᵐ⁰) (w : Valuation L ℤᵐ⁰)
    (hext : v.IsEquiv (w.comap (algebraMap K L)))
    (hP : P.IsMaximal)
    (hcenter : ∀ x : B, x ∈ P ↔ w (algebraMap B L x) < 1) :
    Nonempty (Chapter12LocalArithmeticDictionary (A := A) (K := K) (B := B) (L := L) P v w) := by
  refine ⟨{
    baseMaximalIdeal := IsLocalRing.maximalIdeal A
    baseMaximalIdeal_eq := rfl
    extension := hext
    prime_isMaximal := hP
    center := hcenter
    localizationMap := algebraMap B (branchLocalization B P)
    completionMap := algebraMap (branchLocalization B P) (branchCompletion B P)
    fractionFieldMap := algebraMap (branchCompletion B P) (branchFractionField B P)
  }⟩

end

end LastLib.Book01ValuationsDVRsAndCompletions.Chapter12
