import LastLib.Book07AnalyticFoundationsForOdlyzkoPoitouBounds.Chapter11.Section01TheThresholdFour
import LastLib.Book07AnalyticFoundationsForOdlyzkoPoitouBounds.Chapter11.Section02TheThresholdThreeSqrtThree
import LastLib.Book07AnalyticFoundationsForOdlyzkoPoitouBounds.Chapter11.Section03TheThresholdFiveFourthPower
import LastLib.Book07AnalyticFoundationsForOdlyzkoPoitouBounds.Chapter11.Section04TheTwoPrimeThreshold
import LastLib.Book07AnalyticFoundationsForOdlyzkoPoitouBounds.Chapter11.Section05TotallyRealCertificates
import LastLib.Book07AnalyticFoundationsForOdlyzkoPoitouBounds.Chapter11.Section06QuadraticBaseCertificate
