import LastLib.Book07AnalyticFoundationsForOdlyzkoPoitouBounds.Chapter12.Dependencies
import LastLib.Book07AnalyticFoundationsForOdlyzkoPoitouBounds.Chapter12.Section01IntermediateSignatures
import LastLib.Book07AnalyticFoundationsForOdlyzkoPoitouBounds.Chapter12.Section02FiniteRationalSearches
import LastLib.Book07AnalyticFoundationsForOdlyzkoPoitouBounds.Chapter12.Section03PrimeIdealInformation
import LastLib.Book07AnalyticFoundationsForOdlyzkoPoitouBounds.Chapter12.Section04ChoosingBetweenGeometryAndExplicitFormula
