import LastLib.Book12BlowupsAndIntersectionTheoryOnArithmeticSurfaces.Chapter02.Section01RecordingAllPowersOfAnIdeal
import LastLib.Book12BlowupsAndIntersectionTheoryOnArithmeticSurfaces.Chapter02.Section02GeneratorsRelationsAndSymmetricAlgebra
import LastLib.Book12BlowupsAndIntersectionTheoryOnArithmeticSurfaces.Chapter02.Section03LocalizationPowersAndIntegralClosure
