import LastLib.Book12BlowupsAndIntersectionTheoryOnArithmeticSurfaces.Chapter02.Section01RecordingAllPowersOfAnIdeal

namespace LastLib.Book12BlowupsAndIntersectionTheoryOnArithmeticSurfaces.Chapter02

universe u v

noncomputable section

open AlgebraicGeometry CategoryTheory
open scoped BigOperators
open Polynomial

/-! ## 2.2. Generators, relations, and the symmetric algebra -/

/-- The degree-one linear map from an ideal to its Rees algebra. -/
def chapter02ReesDegreeOneMap
    {R : Type u} [CommRing R] (I : Ideal R) :
    I →ₗ[R] Chapter02ReesAlgebra R I where
  toFun r :=
    ⟨Polynomial.monomial 1 (r : R), by
      rw [reesAlgebra.monomial_mem, pow_one]
      exact r.2⟩
  map_add' := by
    intro r s
    ext
    simp
  map_smul' := by
    intro r s
    ext
    simp [smul_eq_mul]

/-- The canonical map `Sym_R(I) → R_A(I)`. -/
def chapter02SymmetricToRees
    {R : Type u} [CommRing R] (I : Ideal R) :
    SymmetricAlgebra R I →ₐ[R] Chapter02ReesAlgebra R I :=
  SymmetricAlgebra.lift (chapter02ReesDegreeOneMap I)

@[simp] theorem chapter02_symmetric_to_rees_on_generator
    {R : Type u} [CommRing R] (I : Ideal R) (r : I) :
    chapter02SymmetricToRees I (SymmetricAlgebra.ι R I r) =
      chapter02ReesDegreeOneMap I r := by
  simp [chapter02SymmetricToRees]

theorem chapter02_symmetric_algebra_universal_property
    {R A M : Type u} [CommRing R] [CommRing A] [AddCommGroup M]
    [Module R M] [Algebra R A] (f : M →ₗ[R] A)
    (g : SymmetricAlgebra R M →ₐ[R] A)
    (h : g ∘ₗ SymmetricAlgebra.ι R M = f) :
    g = SymmetricAlgebra.lift f := by
  apply SymmetricAlgebra.algHom_ext
  simpa [h] using h

/- LOCAL_DEPENDENCY_GUESS: the symmetric algebra has its standard total-degree internal grading,
which is not packaged by the pinned SymmetricAlgebra API. -/
structure Chapter02SymmetricGradingData
    {R M : Type u} [CommRing R] [AddCommGroup M] [Module R M] where
  component : ℕ → Submodule R (SymmetricAlgebra R M)
  graded : GradedAlgebra component
  generator_mem_degree_one :
    ∀ m : M, SymmetricAlgebra.ι R M m ∈ component 1

theorem chapter02_symmetric_grading_exists
    {R M : Type u} [CommRing R] [AddCommGroup M] [Module R M] :
    Nonempty (Chapter02SymmetricGradingData (R := R) (M := M)) := by
  sorry

theorem chapter02_symmetric_algebra_is_free
    {R M : Type u} [CommRing R] [AddCommGroup M] [Module R M] :
    SymmetricAlgebra.IsSymmetricAlgebra (SymmetricAlgebra.ι R M) := by
  exact SymmetricAlgebra.isSymmetricAlgebra_ι

/- LOCAL_DEPENDENCY_GUESS: the degree-one generators generate all of the Rees algebra, so the
symmetric-algebra map is the source's natural surjection. -/
theorem chapter02_symmetric_to_rees_surjective
    {R : Type u} [CommRing R] (I : Ideal R) :
    Function.Surjective (chapter02SymmetricToRees I) := by
  sorry

def Chapter02SymmetricToReesIsomorphism
    {R : Type u} [CommRing R] (I : Ideal R) : Prop :=
  Function.Bijective (chapter02SymmetricToRees I)

def Chapter02SymmetricToReesMayHaveKernel
    {R : Type u} [CommRing R] (I : Ideal R) : Prop :=
  ¬ Chapter02SymmetricToReesIsomorphism I

/-- The Rees element attached to one chosen generator of an ideal. -/
def chapter02ReesGenerator
    {R : Type u} [CommRing R] {I : Ideal R} {ι : Type v}
    (f : ι → R) (hI : I = Ideal.span (Set.range f)) (i : ι) :
    Chapter02ReesAlgebra R I :=
  ⟨Polynomial.monomial 1 (f i), by
    rw [reesAlgebra.monomial_mem, pow_one, hI]
    exact Ideal.subset_span ⟨i, rfl⟩⟩

/-- The presentation map `R[U_i] → R_A(I)` for a chosen generating family. -/
def chapter02FiniteGeneratorMap
    {R : Type u} [CommRing R] {I : Ideal R} {ι : Type v}
    (f : ι → R) (hI : I = Ideal.span (Set.range f)) :
    MvPolynomial ι R →ₐ[R] Chapter02ReesAlgebra R I :=
  MvPolynomial.eval₂AlgHom R (fun i => chapter02ReesGenerator f hI i)

theorem chapter02_finite_generator_map_surjective
    {R : Type u} [CommRing R] {I : Ideal R} {ι : Type v}
    (f : ι → R) (hI : I = Ideal.span (Set.range f)) :
    Function.Surjective (chapter02FiniteGeneratorMap f hI) := by
  sorry

/-- The evident Koszul-type relation `f_i U_j - f_j U_i`. -/
def chapter02EvidentGeneratorRelation
    {R : Type u} [CommRing R] {ι : Type v} (f : ι → R) (i j : ι) :
    MvPolynomial ι R :=
  MvPolynomial.C (f i) * MvPolynomial.X j -
    MvPolynomial.C (f j) * MvPolynomial.X i

def chapter02GeneratorKernel
    {R : Type u} [CommRing R] {I : Ideal R} {ι : Type v}
    (f : ι → R) (hI : I = Ideal.span (Set.range f)) : Ideal (MvPolynomial ι R) :=
  RingHom.ker (chapter02FiniteGeneratorMap f hI).toRingHom

/-- The ideal generated by the evident pairwise relations. -/
def chapter02EvidentRelationIdeal
    {R : Type u} [CommRing R] {I : Ideal R} {ι : Type v}
    (f : ι → R) (hI : I = Ideal.span (Set.range f)) : Ideal (MvPolynomial ι R) :=
  Ideal.span (Set.range (fun ij : ι × ι =>
    chapter02EvidentGeneratorRelation f ij.1 ij.2))

theorem chapter02_evident_relation_mem_generator_kernel
    {R : Type u} [CommRing R] {I : Ideal R} {ι : Type v}
    (f : ι → R) (hI : I = Ideal.span (Set.range f)) (i j : ι) :
    chapter02EvidentGeneratorRelation f i j ∈ chapter02GeneratorKernel f hI := by
  sorry

theorem chapter02_evident_relations_le_generator_kernel
    {R : Type u} [CommRing R] {I : Ideal R} {ι : Type v}
    (f : ι → R) (hI : I = Ideal.span (Set.range f)) :
    chapter02EvidentRelationIdeal f hI ≤ chapter02GeneratorKernel f hI := by
  rw [chapter02EvidentRelationIdeal]
  refine Ideal.span_le.2 ?_
  rintro _ ⟨⟨i, j⟩, rfl⟩
  exact chapter02_evident_relation_mem_generator_kernel f hI i j

def Chapter02RelationsAreComplete
    {R : Type u} [CommRing R] {I : Ideal R} {ι : Type v}
    (f : ι → R) (hI : I = Ideal.span (Set.range f)) : Prop :=
  chapter02EvidentRelationIdeal f hI = chapter02GeneratorKernel f hI

/-- A witness that higher or torsion relations remain after the evident equations. -/
def Chapter02AdditionalReesRelationWitness
    {R : Type u} [CommRing R] {I : Ideal R} {ι : Type v}
    (f : ι → R) (hI : I = Ideal.span (Set.range f)) : Prop :=
  ∃ p, p ∈ chapter02GeneratorKernel f hI ∧
    p ∉ chapter02EvidentRelationIdeal f hI

theorem chapter02_additional_relation_witness_excludes_completeness
    {R : Type u} [CommRing R] {I : Ideal R} {ι : Type v}
    (f : ι → R) (hI : I = Ideal.span (Set.range f))
    (h : Chapter02AdditionalReesRelationWitness f hI) :
    ¬ Chapter02RelationsAreComplete f hI := by
  rintro rfl
  rcases h with ⟨p, hp, hpn⟩
  exact hpn hp

/-!
On the chart obtained by inverting `f_i`, the ratio of the `j`th coordinate to the `i`th one is
the corresponding fraction `f_j/f_i`.  The statement is made in `Localization.Away (f_i)` so the
denominator hypothesis is explicit.
-/

def chapter02ChartRatio
    {R : Type u} [CommRing R] {ι : Type v} (f : ι → R) (i j : ι) :
    Localization.Away (f i) :=
  algebraMap R (Localization.Away (f i)) (f j) /
    algebraMap R (Localization.Away (f i)) (f i)

theorem chapter02_chart_ratio_mul_denominator
    {R : Type u} [CommRing R] {ι : Type v} (f : ι → R) (i j : ι) :
    algebraMap R (Localization.Away (f i)) (f i) * chapter02ChartRatio f i j =
      algebraMap R (Localization.Away (f i)) (f j) := by
  sorry

def Chapter02ChartCoordinateRelation
    {R : Type u} [CommRing R] {ι : Type v} (f : ι → R) (i : ι)
    (u : ι → Localization.Away (f i)) : Prop :=
  ∀ j, u j = chapter02ChartRatio f i j

theorem chapter02_chart_coordinates_are_ratios
    {R : Type u} [CommRing R] {ι : Type v} (f : ι → R) (i : ι)
    (u : ι → Localization.Away (f i))
    (hu : ∀ j,
      algebraMap R (Localization.Away (f i)) (f i) * u j =
        algebraMap R (Localization.Away (f i)) (f j)) :
    Chapter02ChartCoordinateRelation f i u := by
  sorry

/-- The bivariate polynomial ring used for the incidence example. -/
abbrev Chapter02BivariatePolynomial (k : Type u) [CommRing k] :=
  MvPolynomial (Fin 2) k

def chapter02BivariateX {k : Type u} [CommRing k] : Chapter02BivariatePolynomial k :=
  MvPolynomial.X 0

def chapter02BivariateY {k : Type u} [CommRing k] : Chapter02BivariatePolynomial k :=
  MvPolynomial.X 1

def chapter02BivariateGenerators {k : Type u} [CommRing k] :
    Fin 2 → Chapter02BivariatePolynomial k :=
  Fin.cases (chapter02BivariateX) (fun j => MvPolynomial.X (Fin.succ j))

def chapter02BivariateIdeal {k : Type u} [CommRing k] :
    Ideal (Chapter02BivariatePolynomial k) :=
  Ideal.span (Set.range (chapter02BivariateGenerators : Fin 2 → Chapter02BivariatePolynomial k))

def chapter02BivariateSquareGenerators {k : Type u} [CommRing k] :
    Fin 3 → Chapter02BivariatePolynomial k :=
  Fin.cases (chapter02BivariateX ^ 2) (fun i =>
    Fin.cases (chapter02BivariateX * chapter02BivariateY) (fun _ => chapter02BivariateY ^ 2) i)

def chapter02BivariateSquareIdeal {k : Type u} [CommRing k] :
    Ideal (Chapter02BivariatePolynomial k) :=
  Ideal.span
    (Set.range (chapter02BivariateSquareGenerators : Fin 3 → Chapter02BivariatePolynomial k))

theorem chapter02_bivariate_square_ideal_eq_power
    {k : Type u} [CommRing k] :
    chapter02BivariateSquareIdeal k = chapter02BivariateIdeal k ^ 2 := by
  sorry

theorem chapter02_bivariate_square_has_additional_rees_relation
    {k : Type u} [Field k] :
    Chapter02AdditionalReesRelationWitness
      (I := chapter02BivariateSquareIdeal k)
      chapter02BivariateSquareGenerators rfl := by
  sorry

/- LOCAL_DEPENDENCY_GUESS: the additional relation for the square ideal is also nontrivial in
the canonical symmetric-algebra map. -/
theorem chapter02_bivariate_square_symmetric_to_rees_has_kernel
    {k : Type u} [Field k] :
    ¬ Chapter02SymmetricToReesIsomorphism (chapter02BivariateSquareIdeal k) := by
  sorry

def chapter02IncidenceEquation {k : Type u} [CommRing k] :
    MvPolynomial (Fin 2) (Chapter02BivariatePolynomial k) :=
  MvPolynomial.C chapter02BivariateX * MvPolynomial.X 1 -
    MvPolynomial.C chapter02BivariateY * MvPolynomial.X 0

def chapter02IncidenceIdeal {k : Type u} [CommRing k] :
    Ideal (MvPolynomial (Fin 2) (Chapter02BivariatePolynomial k)) :=
  Ideal.span ({chapter02IncidenceEquation :
    MvPolynomial (Fin 2) (Chapter02BivariatePolynomial k)} : Set _)

theorem chapter02_bivariate_incidence_relation
    {k : Type u} [CommRing k] :
    chapter02EvidentGeneratorRelation chapter02BivariateGenerators 0 1 =
      chapter02IncidenceEquation := by
  sorry

theorem chapter02_bivariate_rees_kernel_is_incidence_ideal
    {k : Type u} [Field k] :
    chapter02GeneratorKernel (I := chapter02BivariateIdeal k)
        chapter02BivariateGenerators rfl =
      chapter02EvidentRelationIdeal (I := chapter02BivariateIdeal k)
        chapter02BivariateGenerators rfl := by
  sorry

theorem chapter02_bivariate_square_rees_proj_iso
    {k : Type u} [Field k] :
    Nonempty (chapter02ReesProj (chapter02BivariateIdeal k) ≅
      chapter02ReesProj (chapter02BivariateSquareIdeal k)) := by
  sorry

theorem chapter02_bivariate_square_rees_algebras_differ
    {k : Type u} [Field k] :
    chapter02ReesAlgebra (chapter02BivariateIdeal k) ≠
      chapter02ReesAlgebra (chapter02BivariateSquareIdeal k) := by
  sorry

def chapter02IncidenceEquationAt {k : Type u} [Field k]
    (a b : k) (u : Fin 2 → k) : Prop :=
  a * u 1 = b * u 0

theorem chapter02_incidence_over_origin
    {k : Type u} [Field k] (u : Fin 2 → k) :
    chapter02IncidenceEquationAt 0 0 u := by
  simp [chapter02IncidenceEquationAt]

def chapter02SameProjectiveDirection {k : Type u} [Field k]
    (u v : Fin 2 → k) : Prop :=
  ∃ c : k, c ≠ 0 ∧ ∀ i, u i = c * v i

def chapter02Direction {k : Type u} [Field k] (a b : k) : Fin 2 → k :=
  Fin.cases a (fun _ => b)

theorem chapter02_incidence_direction_forced_away_from_origin
    {k : Type u} [Field k] {a b : k} (hab : a ≠ 0 ∨ b ≠ 0)
    {u : Fin 2 → k} (hu : u 0 ≠ 0 ∨ u 1 ≠ 0)
    (hinc : chapter02IncidenceEquationAt a b u) :
    chapter02SameProjectiveDirection u (chapter02Direction a b) := by
  sorry

theorem chapter02_incidence_has_all_directions_over_origin
    {k : Type u} [Field k] :
    ∀ u : Fin 2 → k, chapter02IncidenceEquationAt 0 0 u := by
  intro u
  exact chapter02_incidence_over_origin u

/- LOCAL_DEPENDENCY_GUESS: an invertible ideal has a Rees Proj canonically isomorphic to the
base affine scheme; the module-invertibility predicate is the strongest pinned ring interface. -/
theorem chapter02_rees_proj_of_invertible_ideal
    {R : Type u} [CommRing R] (I : Ideal R)
    (hI : Chapter02InvertibleIdeal I) :
    Nonempty (chapter02ReesProj I ≅ AlgebraicGeometry.Spec (CommRingCat.of R)) := by
  sorry

/-! ### Veronese subalgebras and unchanged projective spectrum -/

abbrev chapter02ReesVeroneseCarrier
    {R : Type u} [CommRing R] (I : Ideal R) (q : ℕ) :=
  ⨁ n : ℕ, (chapter02ReesGradingData I).component (q * n)

structure Chapter02ReesVeroneseData
    {R : Type u} [CommRing R] (I : Ideal R) (q : ℕ) where
  component : ℕ → Submodule R (chapter02ReesVeroneseCarrier I q)
  commRing : CommRing (chapter02ReesVeroneseCarrier I q)
  algebra : Algebra R (chapter02ReesVeroneseCarrier I q)
  graded : GradedAlgebra component
  component_spec :
    ∀ n (x : chapter02ReesVeroneseCarrier I q),
      x ∈ component n ↔
        ∃ y : (chapter02ReesGradingData I).component (q * n),
          DirectSum.of (fun n : ℕ => (chapter02ReesGradingData I).component (q * n)) n y = x

/- LOCAL_DEPENDENCY_GUESS: the direct sum of the `I^(qn)T^(qn)` pieces carries the canonical
Veronese graded algebra structure. -/
theorem chapter02_rees_veronese_exists
    {R : Type u} [CommRing R] (I : Ideal R) {q : ℕ} (hq : 0 < q) :
    Nonempty (Chapter02ReesVeroneseData I q) := by
  sorry

noncomputable def chapter02ReesVeroneseData
    {R : Type u} [CommRing R] (I : Ideal R) {q : ℕ} (hq : 0 < q) :
    Chapter02ReesVeroneseData I q :=
  Classical.choice (chapter02_rees_veronese_exists I hq)

noncomputable def chapter02ReesVeroneseProj
    {R : Type u} [CommRing R] {I : Ideal R} {q : ℕ} (hq : 0 < q)
    (V : Chapter02ReesVeroneseData I q) : Scheme.{u} := by
  letI := V.commRing
  letI := V.algebra
  letI := V.graded
  exact AlgebraicGeometry.«Proj» V.component

theorem chapter02_rees_power_proj_iso
    {R : Type u} [CommRing R] (I : Ideal R) {q : ℕ} (hq : 0 < q)
    (V : Chapter02ReesVeroneseData I q) :
    Nonempty (chapter02ReesProj I ≅ chapter02ReesVeroneseProj hq V) := by
  sorry

theorem chapter02_rees_power_has_same_projective_spectrum
    {R : Type u} [CommRing R] (I : Ideal R) {q : ℕ} (hq : 0 < q) :
    ∃ V : Chapter02ReesVeroneseData I q,
      Nonempty (chapter02ReesProj I ≅ chapter02ReesVeroneseProj hq V) := by
  obtain ⟨V⟩ := chapter02_rees_veronese_exists I hq
  exact ⟨V, chapter02_rees_power_proj_iso I hq V⟩

theorem chapter02_invertible_ideal_multiplication_preserves_rees_proj
    {R : Type u} [CommRing R] (I J : Ideal R)
    (hJ : Chapter02InvertibleIdeal J) :
    Nonempty (chapter02ReesProj (J * I) ≅ chapter02ReesProj I) := by
  sorry

end

end LastLib.Book12BlowupsAndIntersectionTheoryOnArithmeticSurfaces.Chapter02
