import LastLib.Book01ValuationsDVRsAndCompletions.Chapter04.Section01WhyDiscretenessIsDecisive
import Mathlib.RingTheory.DiscreteValuationRing.TFAE
import Mathlib.RingTheory.Valuation.Discrete.IsDiscreteValuationRing
import Mathlib.RingTheory.KrullDimension.LocalRing
import Mathlib.RingTheory.Ideal.Height
import Mathlib.RingTheory.Ideal.KrullsHeightTheorem
import Mathlib.RingTheory.IntegralClosure.IntegrallyClosed
import Mathlib.Tactic.Push

namespace LastLib.Book01ValuationsDVRsAndCompletions.Chapter04

open scoped BigOperators Multiplicative WithZero
open Ideal IsLocalRing LinearOrderedCommGroup

noncomputable section

/-!
# Chapter 4: Discrete valuation rings

This chapter formalizes Sections 4.1--4.3 of Book 1.  The
zero-extended multiplicative target `ℤᵐ⁰` is used for Mathlib valuations; its
nonzero part is the additive integer-valued valuation `Kˣ → ℤ` from the prose.
-/

/-! # Book 1, Chapter 4, Section 4.2: Equivalent Characterizations
-/

/-- The valuation-ring/DVR correspondence for the chapter's discrete valuation
interface. -/
theorem is_discrete_valuation_ring_iff_chapter04_valuation_witness
    (A K : Type*) [CommRing A] [IsDomain A] [Field K]
    [Algebra A K] [IsFractionRing A K] :
    IsDiscreteValuationRing A ↔ IsValuationRingOfDiscreteValuation A K := by
  constructor
  · intro hA
    let := hA
    exact ⟨{
      valuation := (IsDiscreteValuationRing.maximalIdeal A).valuation K
      surjective := by
        exact IsDedekindDomain.HeightOneSpectrum.valuation_surjective K
          (IsDiscreteValuationRing.maximalIdeal A)
      valuationSubring_eq_image := by
        exact (IsDiscreteValuationRing.map_algebraMap_eq_valuationSubring
          (A := A) (K := K)).symm }⟩
  · rintro ⟨W⟩
    let : Valuation.IsRankOneDiscrete W.valuation :=
      surjective_integer_valuation_is_rank_one_discrete K W.valuation W.surjective
    let : IsDiscreteValuationRing W.valuation.valuationSubring := by
      infer_instance
    let e₀ : A ≃+* Subring.map (algebraMap A K) (⊤ : Subring A) :=
      Subring.topEquiv.symm.trans
        (Subring.equivMapOfInjective ⊤ (algebraMap A K)
          (IsFractionRing.injective A K))
    let e₁ : Subring.map (algebraMap A K) (⊤ : Subring A) ≃+*
        W.valuation.valuationSubring :=
      RingEquiv.subringCongr W.valuationSubring_eq_image.symm
    let e : A ≃+* W.valuation.valuationSubring := e₀.trans e₁
    exact IsDiscreteValuationRing.RingEquivClass.isDiscreteValuationRing e.symm

/-- In a DVR the maximal ideal is generated by a uniformizer, and every
nonzero ideal is a unique power of it. -/
theorem dvr_maximal_ideal_and_unique_ideal_powers
    (A : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A] :
    (∃ π : A, π ≠ 0 ∧ Chapter04Uniformizer A π) ∧
      ∀ I : Ideal A, I ≠ ⊥ →
        ∃! n : ℕ, I = IsLocalRing.maximalIdeal A ^ n := by
  obtain ⟨π, hπ⟩ := IsDiscreteValuationRing.exists_irreducible A
  refine ⟨⟨π, hπ.ne_zero, ⟨hπ.ne_zero, hπ.maximalIdeal_eq⟩⟩, ?_⟩
  intro I hI
  obtain ⟨n, hn⟩ := IsDiscreteValuationRing.ideal_eq_span_pow_irreducible hI hπ
  refine ⟨n, ?_, ?_⟩
  · simpa [hπ.maximalIdeal_eq, Ideal.span_singleton_pow] using hn
  · intro m hm
    have hpow : IsLocalRing.maximalIdeal A ^ n = IsLocalRing.maximalIdeal A ^ m := by
      calc
        IsLocalRing.maximalIdeal A ^ n = I := by
          simpa [hπ.maximalIdeal_eq, Ideal.span_singleton_pow] using hn.symm
        _ = IsLocalRing.maximalIdeal A ^ m := hm
    have hc := congrArg Order.coheight hpow
    simpa [IsDiscreteValuationRing.coheight_pow_maximalIdeal] using hc.symm

/-- A nonzero ideal contains an element of least additive valuation. -/
theorem dvr_nonzero_ideal_has_least_additive_value
    (A : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    (I : Ideal A) (hI : I ≠ ⊥) :
    ∃ x : A, x ∈ I ∧
      ∀ y : A, y ∈ I → chapter04AdditiveValue A x ≤ chapter04AdditiveValue A y := by
  let : IsPrincipalIdealRing A := inferInstance
  let x : A := Submodule.IsPrincipal.generator I
  have hspan : Ideal.span ({x} : Set A) = I := by
    exact Ideal.span_singleton_generator I
  have hx0 : x ≠ 0 := by
    intro hx
    apply hI
    rw [← hspan, hx, Ideal.span_singleton_eq_bot]
  refine ⟨x, hspan.symm ▸ Ideal.mem_span_singleton_self x, ?_⟩
  intro y hy
  apply (IsDiscreteValuationRing.addVal_le_iff_dvd).2
  rw [← hspan, Ideal.mem_span_singleton] at hy
  exact hy

/-- The least-valued element of a nonzero ideal generates that ideal. -/
theorem dvr_least_value_element_generates_ideal
    (A : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    (I : Ideal A) (_hI : I ≠ ⊥) (x : A) (hx : x ∈ I)
    (hmin : ∀ y : A, y ∈ I →
      chapter04AdditiveValue A x ≤ chapter04AdditiveValue A y) :
    I = Ideal.span ({x} : Set A) := by
  apply le_antisymm
  · intro y hy
    rw [Ideal.mem_span_singleton]
    exact (IsDiscreteValuationRing.addVal_le_iff_dvd).mp (hmin y hy)
  · exact Ideal.span_le.2 (by
      rintro y (rfl : y = x)
      exact hx)

/-- A principal maximal ideal forces every nonzero element to leave the chain
of its successive powers at a finite stage. -/
theorem principal_maximal_ideal_has_finite_power_order
    (A : Type*) [CommRing A] [IsDomain A] [IsNoetherianRing A]
    [IsLocalRing A] {π : A} (_hπ : π ≠ 0)
    (_hmax : IsLocalRing.maximalIdeal A = Ideal.span ({π} : Set A))
    {x : A} (hx : x ≠ 0) :
    ∃ n : ℕ,
      x ∈ IsLocalRing.maximalIdeal A ^ n ∧
        x ∉ IsLocalRing.maximalIdeal A ^ (n + 1) := by
  classical
  let m : Ideal A := IsLocalRing.maximalIdeal A
  have hmne : m ≠ ⊤ := by
    simpa [m] using (IsLocalRing.maximalIdeal.isMaximal A).ne_top
  have h_exists : ∃ n : ℕ, x ∉ m ^ n := by
    by_contra h
    push Not at h
    have hxinf : x ∈ ⨅ n : ℕ, m ^ n := Ideal.mem_iInf.mpr h
    rw [Ideal.iInf_pow_eq_bot_of_isLocalRing m hmne] at hxinf
    exact hx (by simpa [m] using hxinf)
  let N := Nat.find h_exists
  have hN : x ∉ m ^ N := Nat.find_spec h_exists
  have hN0 : N ≠ 0 := by
    intro hzero
    subst N
    apply hN
    simp [hzero, m]
  obtain ⟨n, hN_eq⟩ := Nat.exists_eq_succ_of_ne_zero hN0
  refine ⟨n, ?_, ?_⟩
  · have hmin : x ∈ m ^ n := by
      by_contra hmem
      have hle : N ≤ n := Nat.find_min' h_exists hmem
      exact (Nat.not_le_of_lt (by simp [hN_eq])) hle
    exact hmin
  · simpa [hN_eq] using hN

/-- Repeated division by a principal maximal-ideal generator gives a unit times
a unique power of that generator. -/
theorem principal_maximal_ideal_gives_unique_unit_power_factorization
    (A : Type*) [CommRing A] [IsDomain A] [IsNoetherianRing A]
    [IsLocalRing A] {π : A} (hπ : π ≠ 0)
    (hmax : IsLocalRing.maximalIdeal A = Ideal.span ({π} : Set A))
    {x : A} (hx : x ≠ 0) :
    ∃ (n : ℕ) (u : Aˣ),
      x = (u : A) * π ^ n ∧
        ∀ (m : ℕ) (w : Aˣ), x = (w : A) * π ^ m → m = n ∧ w = u := by
  have hfield : ¬ IsField A := by
    intro hA
    have hbot : IsLocalRing.maximalIdeal A = ⊥ :=
      IsLocalRing.isField_iff_maximalIdeal_eq.mp hA
    apply hπ
    have : Ideal.span ({π} : Set A) = (⊥ : Ideal A) := hmax.symm.trans hbot
    exact Ideal.span_singleton_eq_bot.mp this
  have hprincipal : (IsLocalRing.maximalIdeal A).IsPrincipal := by
    exact ⟨π, hmax⟩
  let : IsDiscreteValuationRing A :=
    ((IsDiscreteValuationRing.TFAE A hfield).out 4 0).mp hprincipal
  have hπirr := IsDiscreteValuationRing.irreducible_of_span_eq_maximalIdeal π hπ hmax
  obtain ⟨n, u, hu⟩ := IsDiscreteValuationRing.eq_unit_mul_pow_irreducible hx hπirr
  refine ⟨n, u, hu, ?_⟩
  intro m w hw
  have heq : (u : A) * π ^ n = (w : A) * π ^ m := hu.symm.trans hw
  exact ⟨(IsDiscreteValuationRing.unit_mul_pow_congr_pow hπirr hπirr u w n m heq).symm,
    (IsDiscreteValuationRing.unit_mul_pow_congr_unit hπirr u w n m heq).symm⟩

/-- Every DVR is integrally closed. -/
theorem dvr_is_integrally_closed
    (A : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A] :
    IsIntegrallyClosed A := by
  infer_instance

/-- Every DVR is one-dimensional. -/
theorem dvr_is_one_dimensional
    (A : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A] :
    ringKrullDim A = 1 := by
  exact IsDiscreteValuationRing.ringKrullDim_eq_one A

/-- The determinant-trick step in the integrally-closed characterization: under
the one-dimensional Noetherian local hypotheses, the maximal ideal is principal. -/
theorem principal_maximal_ideal_of_one_dimensional_integrally_closed_local_domain
    (A : Type*) [CommRing A] [IsDomain A] [IsNoetherianRing A] [IsLocalRing A]
    (hfield : ¬ IsField A) (hdim : ringKrullDim A = 1)
    (hnormal : IsIntegrallyClosed A) :
    (IsLocalRing.maximalIdeal A).IsPrincipal := by
  have hmax0 : IsLocalRing.maximalIdeal A ≠ ⊥ := by
    rw [ne_eq, ← IsLocalRing.isField_iff_maximalIdeal_eq]
    exact hfield
  have hprime :
      ∀ P : Ideal A, P ≠ ⊥ → P.IsPrime →
        P = IsLocalRing.maximalIdeal A := by
    intro P hP hPprime
    obtain ⟨x, hxP, hx0⟩ : ∃ x : A, x ∈ P ∧ x ≠ 0 := by
      by_contra h
      push Not at h
      exact hP (eq_bot_iff.mpr h)
    have hdim' :=
      (ringKrullDim_eq_one_iff_of_isLocalRing_isDomain.mp hdim).2 x hx0
    have hrad : Ideal.radical (Ideal.span ({x} : Set A)) ≤ P :=
      (Ideal.IsRadical.radical_le_iff hPprime.isRadical).2
        (Ideal.span_le.2 (Set.singleton_subset_iff.mpr hxP))
    exact le_antisymm
      (le_maximalIdeal_of_isPrime P)
      (le_trans hdim' hrad)
  have huniq :
      ∃! P : Ideal A, P ≠ ⊥ ∧ P.IsPrime := by
    refine ⟨IsLocalRing.maximalIdeal A, ⟨hmax0, (IsLocalRing.maximalIdeal.isMaximal A).isPrime⟩, ?_⟩
    intro P hP
    exact hprime P hP.1 hP.2
  have hded : IsDedekindDomain A :=
    ((IsDiscreteValuationRing.TFAE A hfield).out 3 2).mp
      (And.intro hnormal huniq)
  let : IsDedekindDomain A := hded
  exact maximalIdeal_isPrincipal_of_isDedekindDomain A

/-- The six conditions in Theorem 4.1, with the one-dimensional assertions
written using `ringKrullDim`. -/
def Chapter04HasUniqueNonzeroPrimeIdeal (A : Type*) [CommRing A] : Prop :=
  ∃! P : Ideal A, P ≠ ⊥ ∧ P.IsPrime

def Chapter04IsNoetherianValuationRing (A : Type*) [CommRing A] [IsDomain A] : Prop :=
  IsNoetherianRing A ∧ ValuationRing A

def Chapter04IsPIDWithUniqueNonzeroPrime (A : Type*) [CommRing A] [IsDomain A] : Prop :=
  IsPrincipalIdealRing A ∧ Chapter04HasUniqueNonzeroPrimeIdeal A

def Chapter04IsOneDimensionalNoetherianLocalPrincipal (A : Type*)
    [CommRing A] [IsDomain A] : Prop :=
  IsNoetherianRing A ∧ IsLocalRing A ∧ ringKrullDim A = 1 ∧
    ∃ m : Ideal A, m.IsMaximal ∧ m.IsPrincipal

def Chapter04IsOneDimensionalNoetherianLocalIntegrallyClosed (A : Type*)
    [CommRing A] [IsDomain A] : Prop :=
  IsNoetherianRing A ∧ IsLocalRing A ∧ IsIntegrallyClosed A ∧ ringKrullDim A = 1

def Chapter04IsLocalWithUniqueIdealPowers (A : Type*) [CommRing A] [IsDomain A] : Prop :=
  IsLocalRing A ∧
    ∃ π : A, π ≠ 0 ∧
      ∀ I : Ideal A, I ≠ ⊥ →
        ∃! n : ℕ, I = Ideal.span ({π ^ n} : Set A)

/-- Theorem 4.1: the six standard characterizations of a DVR are equivalent. -/
theorem theorem_4_1_characterizations_of_a_dvr
    (A K : Type*) [CommRing A] [IsDomain A] [Field K]
    [Algebra A K] [IsFractionRing A K] (hfield : ¬ IsField A) :
    List.TFAE
      [ IsValuationRingOfDiscreteValuation A K,
        Chapter04IsNoetherianValuationRing A,
        Chapter04IsPIDWithUniqueNonzeroPrime A,
        Chapter04IsOneDimensionalNoetherianLocalPrincipal A,
        Chapter04IsOneDimensionalNoetherianLocalIntegrallyClosed A,
        Chapter04IsLocalWithUniqueIdealPowers A ] := by
  have h0_to_dvr : IsValuationRingOfDiscreteValuation A K → IsDiscreteValuationRing A := by
    intro h
    exact (is_discrete_valuation_ring_iff_chapter04_valuation_witness A K).mpr h
  have hdvr_to0 : IsDiscreteValuationRing A → IsValuationRingOfDiscreteValuation A K :=
    fun h => (is_discrete_valuation_ring_iff_chapter04_valuation_witness A K).mp h
  have h1_to_dvr : Chapter04IsNoetherianValuationRing A → IsDiscreteValuationRing A := by
    rintro ⟨hN, hV⟩
    let : IsNoetherianRing A := hN
    let : ValuationRing A := hV
    let : IsLocalRing A := inferInstance
    exact ((IsDiscreteValuationRing.TFAE A hfield).out 1 0).mp
      (show ValuationRing A from inferInstance)
  have h2_to_dvr : Chapter04IsPIDWithUniqueNonzeroPrime A → IsDiscreteValuationRing A := by
    intro h
    exact (IsDiscreteValuationRing.iff_pid_with_one_nonzero_prime A).mpr h
  have h3_to_dvr :
      Chapter04IsOneDimensionalNoetherianLocalPrincipal A → IsDiscreteValuationRing A := by
    rintro ⟨hN, hL, hd, m, hm, hmp⟩
    let : IsNoetherianRing A := hN
    let : IsLocalRing A := hL
    have hm' : m = IsLocalRing.maximalIdeal A := IsLocalRing.eq_maximalIdeal hm
    have hmax : (IsLocalRing.maximalIdeal A).IsPrincipal := hm' ▸ hmp
    exact ((IsDiscreteValuationRing.TFAE A hfield).out 4 0).mp hmax
  have h4_to_dvr :
      Chapter04IsOneDimensionalNoetherianLocalIntegrallyClosed A →
        IsDiscreteValuationRing A := by
    rintro ⟨hN, hL, hnormal, hd⟩
    let : IsNoetherianRing A := hN
    let : IsLocalRing A := hL
    exact ((IsDiscreteValuationRing.TFAE A hfield).out 4 0).mp
      (principal_maximal_ideal_of_one_dimensional_integrally_closed_local_domain
        A hfield hd hnormal)
  have h5_to_dvr :
      Chapter04IsLocalWithUniqueIdealPowers A → IsDiscreteValuationRing A := by
    rintro ⟨hL, π, hπ, hpowers⟩
    let : IsLocalRing A := hL
    let : IsPrincipalIdealRing A :=
      { principal := fun I => by
          by_cases hI : I = ⊥
          · subst I
            exact ⟨0, Ideal.span_singleton_zero.symm⟩
          · obtain ⟨n, hn, _⟩ := hpowers I hI
            exact ⟨π ^ n, hn⟩ }
    apply IsDiscreteValuationRing.mk
    intro hbot
    exact hfield (IsLocalRing.isField_iff_maximalIdeal_eq.mpr hbot)
  have hdvr_to1 : IsDiscreteValuationRing A → Chapter04IsNoetherianValuationRing A := by
    intro h
    let := h
    exact ⟨inferInstance, inferInstance⟩
  have hdvr_to2 : IsDiscreteValuationRing A → Chapter04IsPIDWithUniqueNonzeroPrime A := by
    intro h
    let := h
    exact (IsDiscreteValuationRing.iff_pid_with_one_nonzero_prime A).mp h
  have hdvr_to3 :
      IsDiscreteValuationRing A → Chapter04IsOneDimensionalNoetherianLocalPrincipal A := by
    intro h
    let := h
    exact ⟨inferInstance, inferInstance, IsDiscreteValuationRing.ringKrullDim_eq_one A,
      IsLocalRing.maximalIdeal A, IsLocalRing.maximalIdeal.isMaximal A,
      IsPrincipalIdealRing.principal _⟩
  have hdvr_to4 :
      IsDiscreteValuationRing A →
        Chapter04IsOneDimensionalNoetherianLocalIntegrallyClosed A := by
    intro h
    let := h
    exact ⟨inferInstance, inferInstance, inferInstance,
      IsDiscreteValuationRing.ringKrullDim_eq_one A⟩
  have hdvr_to5 :
      IsDiscreteValuationRing A → Chapter04IsLocalWithUniqueIdealPowers A := by
    intro h
    let := h
    obtain ⟨⟨π, hπ, hπu⟩, hpowers⟩ :=
      dvr_maximal_ideal_and_unique_ideal_powers A
    refine ⟨inferInstance, π, hπ, ?_⟩
    intro I hI
    obtain ⟨n, hn, huniq⟩ := hpowers I hI
    refine ⟨n, ?_, ?_⟩
    · simpa [hπu.2, Ideal.span_singleton_pow] using hn
    · intro m hm
      apply huniq m
      simpa [hπu.2, Ideal.span_singleton_pow] using hm
  tfae_have 1 → 2 := fun h => hdvr_to1 (h0_to_dvr h)
  tfae_have 2 → 1 := fun h => hdvr_to0 (h1_to_dvr h)
  tfae_have 1 → 3 := fun h => hdvr_to2 (h0_to_dvr h)
  tfae_have 3 → 1 := fun h => hdvr_to0 (h2_to_dvr h)
  tfae_have 1 → 4 := fun h => hdvr_to3 (h0_to_dvr h)
  tfae_have 4 → 1 := fun h => hdvr_to0 (h3_to_dvr h)
  tfae_have 1 → 5 := fun h => hdvr_to4 (h0_to_dvr h)
  tfae_have 5 → 1 := fun h => hdvr_to0 (h4_to_dvr h)
  tfae_have 1 → 6 := fun h => hdvr_to5 (h0_to_dvr h)
  tfae_have 6 → 1 := fun h => hdvr_to0 (h5_to_dvr h)
  tfae_finish

/-- The normalized valuation is unique once its valuation ring is fixed. -/
theorem normalized_integer_valuation_unique
    (A K : Type*) [CommRing A] [IsDomain A] [Field K]
    [Algebra A K] [IsFractionRing A K]
    {v w : Valuation K ℤᵐ⁰}
    (hv : IsSurjectiveIntegerValuation K v)
    (hw : IsSurjectiveIntegerValuation K w)
    (hvA : v.valuationSubring.toSubring =
      Subring.map (algebraMap A K) (⊤ : Subring A))
    (hwA : w.valuationSubring.toSubring =
      Subring.map (algebraMap A K) (⊤ : Subring A)) :
    v = w := by
  let : Valuation.IsRankOneDiscrete v :=
    surjective_integer_valuation_is_rank_one_discrete K v hv
  let : Valuation.IsRankOneDiscrete w :=
    surjective_integer_valuation_is_rank_one_discrete K w hw
  have hsub : v.valuationSubring = w.valuationSubring := by
    apply ValuationSubring.ext
    intro x
    change x ∈ v.valuationSubring.toSubring ↔ x ∈ w.valuationSubring.toSubring
    rw [hvA, hwA]
  have heq : v.IsEquiv w :=
    (Valuation.isEquiv_iff_valuationSubring v w).2 hsub
  have hgen :
      heq.orderMonoidIso (Valuation.IsRankOneDiscrete.generator' v) =
        Valuation.IsRankOneDiscrete.generator' w := by
    let e : MonoidWithZeroHom.valueGroup (.ofClass v) ≃*
        MonoidWithZeroHom.valueGroup (.ofClass w) :=
      MulEquiv.unzero heq.orderMonoidIso.toMulEquiv
    have hlt₀ :
        heq.orderMonoidIso
            (Valuation.IsRankOneDiscrete.generator' v) < 1 := by
      rw [← heq.orderMonoidIso.map_one]
      exact (heq.orderMonoidIso.toOrderIso.lt_iff_lt).mpr
        (WithZero.coe_lt_coe.mpr
          (Valuation.IsRankOneDiscrete.generator'_lt_one v))
    have hlt : e (Valuation.IsRankOneDiscrete.generator' v) < 1 := by
      apply WithZero.coe_lt_coe.mp
      simpa [e] using hlt₀
    have hpow :
        Subgroup.zpowers (e (Valuation.IsRankOneDiscrete.generator' v)) = ⊤ := by
      calc
        Subgroup.zpowers (e (Valuation.IsRankOneDiscrete.generator' v)) =
            (Subgroup.zpowers (Valuation.IsRankOneDiscrete.generator' v)).map
              e.toMonoidHom := by
                exact (MonoidHom.map_zpowers
                  e.toMonoidHom
                  (Valuation.IsRankOneDiscrete.generator' v)).symm
        _ = (⊤ : Subgroup (MonoidWithZeroHom.valueGroup (.ofClass v))).map
              e.toMonoidHom := by
              rw [Valuation.IsRankOneDiscrete.generator'_zpowers_eq_top v]
        _ = ⊤ := Subgroup.map_top_of_surjective e.toMonoidHom e.surjective
    have hwgen :
        Valuation.IsRankOneDiscrete.generator' w =
          (⊤ : Subgroup (MonoidWithZeroHom.valueGroup (.ofClass w))).genLTOne := by
      exact (⊤ : Subgroup (MonoidWithZeroHom.valueGroup (.ofClass w))).genLTOne_unique
        (Valuation.IsRankOneDiscrete.generator'_lt_one w)
        (Valuation.IsRankOneDiscrete.generator'_zpowers_eq_top w)
    have hgen' : e (Valuation.IsRankOneDiscrete.generator' v) =
        Valuation.IsRankOneDiscrete.generator' w :=
      (⊤ : Subgroup (MonoidWithZeroHom.valueGroup (.ofClass w))).genLTOne_unique
        hlt hpow |>.trans hwgen.symm
    simpa [e] using congrArg
      (fun z : MonoidWithZeroHom.valueGroup (.ofClass w) =>
        (z : MonoidWithZeroHom.ValueGroup₀ (.ofClass w))) hgen'
  have hgenval :
      Valuation.IsRankOneDiscrete.valueGroup₀_equiv_withZeroMulInt v
          (Valuation.IsRankOneDiscrete.generator' v) =
        Valuation.IsRankOneDiscrete.valueGroup₀_equiv_withZeroMulInt w
          (Valuation.IsRankOneDiscrete.generator' w) := by
    have hvgen :=
      Valuation.IsRankOneDiscrete.valueGroup₀_equiv_withZeroMulInt_apply_zpow
        (v := v) (k := (1 : ℤ))
    have hwgen :=
      Valuation.IsRankOneDiscrete.valueGroup₀_equiv_withZeroMulInt_apply_zpow
        (v := w) (k := (1 : ℤ))
    simpa only [zpow_one] using hvgen.trans hwgen.symm
  apply Valuation.ext
  intro x
  by_cases hx0 : x = 0
  · simp [hx0]
  have hvx : v x ≠ 0 := by simp [hx0]
  have hvr : v.restrict x ≠ 0 := by
    intro h
    exact hvx ((Valuation.restrict_eq_zero_iff v).mp h)
  let g : MonoidWithZeroHom.valueGroup (.ofClass v) := WithZero.unzero hvr
  have hgr : (g : MonoidWithZeroHom.ValueGroup₀ (.ofClass v)) = v.restrict x :=
    WithZero.coe_unzero hvr
  have hggen : g ∈
      Subgroup.zpowers (Valuation.IsRankOneDiscrete.generator' v) := by
    rw [Valuation.IsRankOneDiscrete.generator'_zpowers_eq_top v]
    trivial
  obtain ⟨n, hn⟩ := Subgroup.mem_zpowers_iff.mp hggen
  have hn' : v.restrict x =
      (Valuation.IsRankOneDiscrete.generator' v) ^ n := by
    calc
      v.restrict x = (g : MonoidWithZeroHom.ValueGroup₀ (.ofClass v)) := hgr.symm
      _ = (Valuation.IsRankOneDiscrete.generator' v) ^ n :=
        congrArg (fun z : MonoidWithZeroHom.valueGroup (.ofClass v) =>
          (z : MonoidWithZeroHom.ValueGroup₀ (.ofClass v))) hn.symm
  have hwn : w.restrict x =
        (Valuation.IsRankOneDiscrete.generator' w) ^ n := by
    have hs := heq.orderMonoidIso_spec x
    rw [hn'] at hs
    rw [map_zpow₀, hgen] at hs
    exact hs.symm
  calc
    v x =
        Valuation.IsRankOneDiscrete.valueGroup₀_equiv_withZeroMulInt v
          (v.restrict x) :=
      (Valuation.IsRankOneDiscrete.valueGroup₀_equiv_withZeroMulInt_restrict_apply_of_surjective
        hv x).symm
    _ =
        Valuation.IsRankOneDiscrete.valueGroup₀_equiv_withZeroMulInt v
          ((Valuation.IsRankOneDiscrete.generator' v) ^ n) := by rw [hn']
    _ =
        (Valuation.IsRankOneDiscrete.valueGroup₀_equiv_withZeroMulInt v
          (Valuation.IsRankOneDiscrete.generator' v)) ^ n := by rw [map_zpow₀]
    _ =
        (Valuation.IsRankOneDiscrete.valueGroup₀_equiv_withZeroMulInt w
          (Valuation.IsRankOneDiscrete.generator' w)) ^ n := by rw [hgenval]
    _ =
        Valuation.IsRankOneDiscrete.valueGroup₀_equiv_withZeroMulInt w
          (w.restrict x) := by rw [hwn, map_zpow₀]
    _ = w x :=
      Valuation.IsRankOneDiscrete.valueGroup₀_equiv_withZeroMulInt_restrict_apply_of_surjective
        hw x

/-- A fixed uniformizer gives the unique fraction-field normal form
`x = π^n u` (written using Mathlib's scalar action of `Aˣ`). -/
theorem dvr_fraction_field_unique_normal_form
    (A K : Type*) [CommRing A] [IsDomain A] [Field K]
    [Algebra A K] [IsFractionRing A K] [IsDiscreteValuationRing A]
    {π : A} (hπ : Chapter04Uniformizer A π) {x : K} (hx : x ≠ 0) :
    ∃ (n : ℤ) (u : Aˣ),
      x = u • (algebraMap A K π) ^ n ∧
        ∀ (m : ℤ) (w : Aˣ),
          x = w • (algebraMap A K π) ^ m → m = n ∧ w = u := by
  have hπirr :=
    IsDiscreteValuationRing.irreducible_of_span_eq_maximalIdeal π hπ.1 hπ.2
  obtain ⟨n, u, hu⟩ :=
    IsDiscreteValuationRing.exists_units_eq_smul_zpow_of_irreducible hπirr hx
  refine ⟨n, u, hu, ?_⟩
  intro m w hw
  let v : Valuation K ℤᵐ⁰ :=
    (IsDiscreteValuationRing.maximalIdeal A).valuation K
  have hπv : v (algebraMap A K π) = WithZero.exp (-1 : ℤ) := by
    rw [IsDedekindDomain.HeightOneSpectrum.valuation_of_algebraMap]
    exact IsDedekindDomain.HeightOneSpectrum.intValuation_singleton
      (v := IsDiscreteValuationRing.maximalIdeal A) hπ.1 hπ.2
  have huv : v (algebraMap A K (u : A)) = 1 := by
    rw [IsDedekindDomain.HeightOneSpectrum.valuation_of_algebraMap]
    rw [IsDedekindDomain.HeightOneSpectrum.intValuation_eq_one_iff_mem_primeCompl]
    change (u : A) ∉ (IsDiscreteValuationRing.maximalIdeal A).asIdeal
    change (u : A) ∉ IsLocalRing.maximalIdeal A
    rw [IsLocalRing.mem_maximalIdeal, mem_nonunits_iff]
    exact not_not_intro u.isUnit
  have hwv : v (algebraMap A K (w : A)) = 1 := by
    rw [IsDedekindDomain.HeightOneSpectrum.valuation_of_algebraMap]
    rw [IsDedekindDomain.HeightOneSpectrum.intValuation_eq_one_iff_mem_primeCompl]
    change (w : A) ∉ (IsDiscreteValuationRing.maximalIdeal A).asIdeal
    change (w : A) ∉ IsLocalRing.maximalIdeal A
    rw [IsLocalRing.mem_maximalIdeal, mem_nonunits_iff]
    exact not_not_intro w.isUnit
  have hval := congrArg v (hu.symm.trans hw)
  simp only [Units.smul_def, Algebra.smul_def, map_mul, map_zpow₀, huv, hwv,
    one_mul, hπv] at hval
  have hmn : m = n := by
    have hpow : WithZero.exp (-n : ℤ) = WithZero.exp (-m : ℤ) := by
      calc
        WithZero.exp (-n : ℤ) = WithZero.exp (-1 : ℤ) ^ n := by
          rw [← WithZero.exp_zsmul]
          simp
        _ = WithZero.exp (-1 : ℤ) ^ m := hval
        _ = WithZero.exp (-m : ℤ) := by
          rw [← WithZero.exp_zsmul]
          simp
    have hneg : (-n : ℤ) = -m := WithZero.exp_injective hpow
    exact (neg_injective hneg).symm
  have heqK :
      algebraMap A K (u : A) * (algebraMap A K π) ^ n =
        algebraMap A K (w : A) * (algebraMap A K π) ^ n := by
    simpa [Units.smul_def, Algebra.smul_def, hmn] using hu.symm.trans hw
  have hπK : algebraMap A K π ≠ 0 := by
    exact (map_ne_zero_iff (algebraMap A K)
      (IsFractionRing.injective A K)).2 hπ.1
  have hunitK :
      algebraMap A K (u : A) = algebraMap A K (w : A) := by
    exact mul_right_cancel₀ (zpow_ne_zero n hπK) heqK
  refine ⟨hmn, ?_⟩
  apply Units.ext
  exact (IsFractionRing.injective A K hunitK).symm

/-- A uniformizer has normalized additive value `1`. -/
theorem dvr_uniformizer_has_value_one
    (A : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    {π : A} (hπ : Chapter04Uniformizer A π) :
    chapter04AdditiveValue A π = 1 := by
  have hπirr :=
    IsDiscreteValuationRing.irreducible_of_span_eq_maximalIdeal π hπ.1 hπ.2
  simpa [chapter04AdditiveValue] using
    IsDiscreteValuationRing.addVal_uniformizer hπirr

/-- Two uniformizers differ by a unit. -/
theorem dvr_uniformizers_are_associated
    (A : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    {π ρ : A} (hπ : Chapter04Uniformizer A π)
    (hρ : Chapter04Uniformizer A ρ) :
    Associated π ρ := by
  exact IsDiscreteValuationRing.associated_of_irreducible A
    (IsDiscreteValuationRing.irreducible_of_span_eq_maximalIdeal π hπ.1 hπ.2)
    (IsDiscreteValuationRing.irreducible_of_span_eq_maximalIdeal ρ hρ.1 hρ.2)

/-- In a DVR, generating the maximal ideal is equivalent to being a
uniformizer, and hence to being irreducible. -/
theorem dvr_uniformizer_iff_irreducible
    (A : Type*) [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    (π : A) :
    Chapter04Uniformizer A π ↔ Irreducible π := by
  constructor
  · intro h
    exact IsDiscreteValuationRing.irreducible_of_span_eq_maximalIdeal π h.1 h.2
  · intro h
    exact ⟨h.ne_zero, h.maximalIdeal_eq⟩

end
end LastLib.Book01ValuationsDVRsAndCompletions.Chapter04
