import LastLib.Book06GlobalClassFieldTheory.Chapter08.Dependencies

namespace LastLib.Book06GlobalClassFieldTheory.Chapter08

noncomputable section

open NumberField

universe u

/-! ## 8.4. Cyclotomic fields as ray class fields -/

theorem chapter08_rational_ordinary_class_group_is_trivial :
    chapter08ClassNumber ℚ = 1 := by
  sorry

theorem chapter08_rational_ray_group_with_infinity
    {I C : Type u} [CommGroup I] [CommGroup C]
    (m : ℕ) (hm0 : m ≠ 0) (hm : 2 < m)
    (R : Chapter08RayClassPresentation ℚ I C)
    (hmod : R.modulus = chapter08RationalRayModulus m hm0) :
    chapter08RayClassGroup R ≃* chapter08RationalRayGroup m := by
  sorry

theorem chapter08_rational_ray_group_without_infinity
    {I C : Type u} [CommGroup I] [CommGroup C]
    (m : ℕ) (hm0 : m ≠ 0) (hm : 2 < m)
    (R : Chapter08RayClassPresentation ℚ I C)
    (hmod : R.modulus = chapter08RationalRayModulusWithoutInfinity m hm0) :
    chapter08RayClassGroup R ≃* chapter08RationalRayGroupWithoutInfinity m := by
  sorry

/- The two rational calculations are the book-facing form of the positivity
condition: including the real place retains the sign of a generator, while
omitting it quotients by the subgroup generated by `-1`. -/
theorem chapter08_rational_infinity_positivity_retains_sign
    (m : ℕ) :
    chapter08RationalRayGroupWithoutInfinity m =
      ((ZMod m)ˣ ⧸ Subgroup.closure ({(-1 : (ZMod m)ˣ)} : Set ((ZMod m)ˣ))) := by
  rfl

noncomputable def chapter08_rational_maximal_real_subfield_is_the_no_infinity_field
    {I C I₀ C₀ : Type u} [CommGroup I] [CommGroup C]
    [CommGroup I₀] [CommGroup C₀]
    (m : ℕ) (hm0 : m ≠ 0) (hm : 2 < m)
    (R : Chapter08RayClassPresentation ℚ I C)
    (R₀ : Chapter08RayClassPresentation ℚ I₀ C₀)
    (hmod : R.modulus = chapter08RationalRayModulus m hm0)
    (hmod₀ : R₀.modulus = chapter08RationalRayModulusWithoutInfinity m hm0) :
    chapter08RayClassGroup R₀ ≃*
      chapter08RationalRayGroupWithoutInfinity m := by
  sorry

/-! Cyclotomic ramification and the conductor bound. -/

theorem chapter08_cyclotomic_extension_is_abelian
    {m : ℕ} {F : Type u} [Field F] [Algebra ℚ F]
    [NumberField F] [IsCyclotomicExtension {m} ℚ F] :
    IsAbelianGalois ℚ F := by
  exact IsCyclotomicExtension.isAbelianGalois {m} ℚ F

theorem chapter08_cyclotomic_root_is_primitive
    {m : ℕ} {F : Type u} [Field F] [Algebra ℚ F]
    [NumberField F] [IsCyclotomicExtension {m} ℚ F] [NeZero m]
    (D : Chapter08CyclotomicData m F) :
    IsPrimitiveRoot (chapter08CyclotomicRoot D) m := by
  exact IsCyclotomicExtension.zeta_spec m ℚ F

theorem chapter08_cyclotomic_degree
    {m : ℕ} {F : Type u} [Field F] [Algebra ℚ F]
    [NumberField F] [FiniteDimensional ℚ F]
    [IsCyclotomicExtension {m} ℚ F] :
    Module.finrank ℚ F = Nat.totient m := by
  sorry

theorem chapter08_cyclotomic_unramified_away_from_m
    {m p : ℕ} {F : Type u} [Field F] [Algebra ℚ F]
    [NumberField F] [FiniteDimensional ℚ F]
    [IsCyclotomicExtension {m} ℚ F]
    [Fact p.Prime] (hpm : ¬p ∣ m) :
    Algebra.IsUnramifiedIn (𝓞 F) (Ideal.span {(p : ℤ)}) := by
  sorry

theorem chapter08_cyclotomic_real_place_complexifies
    {m : ℕ} {F : Type u} [Field F] [Algebra ℚ F]
    [NumberField F] [FiniteDimensional ℚ F]
    [IsCyclotomicExtension {m} ℚ F]
    (hm : 2 < m) :
    ¬chapter08RealPlacesStayReal ℚ F := by
  sorry

theorem chapter08_cyclotomic_local_artin_is_trivial_on_principal_units
    {m : ℕ} {F : Type u} [Field F] [Algebra ℚ F]
    [NumberField F] [IsCyclotomicExtension {m} ℚ F]
    (hm : 2 < m) (P : Chapter08CyclotomicConductorProfile m F hm) :
    ∀ v : P.localPlace,
      let S := P.localSystem v
      letI : CommGroup S.unitGroup := S.unitGroupCommGroup
      S.principalUnit (P.principalUnitDepth v) ≤ S.localArtin.ker := by
  exact P.principalUnitDepth_killed

theorem chapter08_cyclotomic_conductor_divides_written_modulus
    {m : ℕ} {F : Type u} [Field F] [Algebra ℚ F]
    [NumberField F] [IsCyclotomicExtension {m} ℚ F]
    [IsAbelianGalois ℚ F]
    (hm0 : m ≠ 0) (hm : 2 < m) (P : Chapter08CyclotomicConductorProfile m F hm)
    (E : Chapter08AbelianExtensionData ℚ F)
    (hconductor : E.conductor = P.conductor)
    (hwritten : P.writtenModulus = chapter08RationalRayModulus m hm0) :
    chapter08ConductorDivides E (chapter08RationalRayModulus m hm0) := by
  sorry

theorem chapter08_cyclotomic_ray_field_contains_cyclotomic_field
    {m : ℕ} {F : Type u} [Field F] [Algebra ℚ F]
    [NumberField F] [IsCyclotomicExtension {m} ℚ F]
    [IsAbelianGalois ℚ F]
    {I C : Type u} [CommGroup I] [CommGroup C]
    (R : Chapter08RayClassPresentation ℚ I C)
    (Rfield : Chapter08RayClassFieldData ℚ R)
    (hm0 : m ≠ 0) (hm : 2 < m)
    (hmod : R.modulus = chapter08RationalRayModulus m hm0)
    (E : Chapter08AbelianExtensionData ℚ F)
    (hcond : chapter08ConductorDivides E R.modulus) :
    letI : Field Rfield.carrier := Rfield.carrierField
    letI : Algebra ℚ Rfield.carrier := Rfield.carrierAlgebra
    letI : NumberField Rfield.carrier := Rfield.carrierNumberField
    letI : FiniteDimensional ℚ Rfield.carrier := Rfield.carrierFinite
    letI : IsAbelianGalois ℚ Rfield.carrier := Rfield.carrierAbelianGalois
    chapter08ExtensionContained ℚ F Rfield.carrier := by
  sorry

theorem chapter08_ray_class_field_degree_is_totient
    {m : ℕ} {I C : Type u} [CommGroup I] [CommGroup C]
    (R : Chapter08RayClassPresentation ℚ I C)
    (Rfield : Chapter08RayClassFieldData ℚ R)
    (hm0 : m ≠ 0)
    (hmod : R.modulus = chapter08RationalRayModulus m hm0)
    (hm : 2 < m)
    (hray : chapter08RayClassGroup R ≃* chapter08RationalRayGroup m) :
    letI : Field Rfield.carrier := Rfield.carrierField
    letI : Algebra ℚ Rfield.carrier := Rfield.carrierAlgebra
    letI : NumberField Rfield.carrier := Rfield.carrierNumberField
    letI : FiniteDimensional ℚ Rfield.carrier := Rfield.carrierFinite
    letI : IsAbelianGalois ℚ Rfield.carrier := Rfield.carrierAbelianGalois
    Module.finrank ℚ Rfield.carrier = Nat.totient m := by
  sorry

theorem chapter08_cyclotomic_field_is_the_full_ray_class_field
    {m : ℕ} {F : Type u} [Field F] [Algebra ℚ F]
    [NumberField F] [IsCyclotomicExtension {m} ℚ F]
    [IsAbelianGalois ℚ F]
    {I C : Type u} [CommGroup I] [CommGroup C]
    (R : Chapter08RayClassPresentation ℚ I C)
    (Rfield : Chapter08RayClassFieldData ℚ R)
    (hm0 : m ≠ 0) (hm : 2 < m)
    (hmod : R.modulus = chapter08RationalRayModulus m hm0)
    (E : Chapter08AbelianExtensionData ℚ F)
    (hcond : chapter08ConductorDivides E R.modulus)
    (hdegreeRay :
      letI : Field Rfield.carrier := Rfield.carrierField
      letI : Algebra ℚ Rfield.carrier := Rfield.carrierAlgebra
      letI : NumberField Rfield.carrier := Rfield.carrierNumberField
      letI : FiniteDimensional ℚ Rfield.carrier := Rfield.carrierFinite
      letI : IsAbelianGalois ℚ Rfield.carrier := Rfield.carrierAbelianGalois
      Module.finrank ℚ Rfield.carrier = Nat.totient m)
    (hdegreeCyclotomic : Module.finrank ℚ F = Nat.totient m) :
    letI : Field Rfield.carrier := Rfield.carrierField
    letI : Algebra ℚ Rfield.carrier := Rfield.carrierAlgebra
    letI : NumberField Rfield.carrier := Rfield.carrierNumberField
    letI : FiniteDimensional ℚ Rfield.carrier := Rfield.carrierFinite
    letI : IsAbelianGalois ℚ Rfield.carrier := Rfield.carrierAbelianGalois
    Nonempty (F ≃ₐ[ℚ] Rfield.carrier) := by
  sorry

theorem chapter08_cyclotomic_no_infinity_field_is_maximal_real_subfield
    {m : ℕ} {F : Type u} [Field F] [Algebra ℚ F]
    [NumberField F] [IsCyclotomicExtension {m} ℚ F]
    {I C : Type u} [CommGroup I] [CommGroup C]
    (D : Chapter08CyclotomicData m F) (hm0 : m ≠ 0) (hm : 2 < m)
    (R₀ : Chapter08RayClassPresentation ℚ I C)
    (R₀field : Chapter08RayClassFieldData ℚ R₀)
    (hmod : R₀.modulus = chapter08RationalRayModulusWithoutInfinity m hm0) :
    letI : Field R₀field.carrier := R₀field.carrierField
    letI : Algebra ℚ R₀field.carrier := R₀field.carrierAlgebra
    letI : NumberField R₀field.carrier := R₀field.carrierNumberField
    letI : FiniteDimensional ℚ R₀field.carrier := R₀field.carrierFinite
    letI : IsAbelianGalois ℚ R₀field.carrier := R₀field.carrierAbelianGalois
    Nonempty (chapter08CyclotomicMaximalRealSubfield D ≃ₐ[ℚ]
      R₀field.carrier) := by
  sorry

theorem chapter08_written_modulus_covers_the_two_mod_four_case
    {m : ℕ} (hm : m % 4 = 2)
    {F : Type u} [Field F] [Algebra ℚ F]
    [NumberField F] [IsCyclotomicExtension {m} ℚ F]
    (hm0 : m ≠ 0) (hmgt : 2 < m)
    (P : Chapter08CyclotomicConductorProfile m F hmgt)
    (hwritten : P.writtenModulus = chapter08RationalRayModulus m hm0) :
    chapter08ModulusDivides P.conductor (chapter08RationalRayModulus m hm0) := by
  sorry

/-! The complete-splitting congruence. -/

theorem chapter08_cyclotomic_prime_splits_completely_iff_congruent_one
    {m p : ℕ} {F : Type u} [Field F] [Algebra ℚ F]
    [NumberField F] [FiniteDimensional ℚ F]
    [IsCyclotomicExtension {m} ℚ F]
    [IsAbelianGalois ℚ F] [Fact p.Prime] (hm : 2 < m)
    (hpm : ¬p ∣ m) :
    chapter08SplitsCompletely ℚ F (Ideal.span {(p : 𝓞 ℚ)}) ↔
      p ≡ 1 [MOD m] := by
  sorry

/-! Kronecker--Weber as the final maximality consequence. -/

theorem chapter08_kronecker_weber_from_ray_class_fields
    {L : Type u} [Field L] [Algebra ℚ L] [NumberField L]
    [FiniteDimensional ℚ L] [IsAbelianGalois ℚ L] :
    Nonempty (Chapter08CyclotomicContainmentData L) := by
  sorry

end
end LastLib.Book06GlobalClassFieldTheory.Chapter08
