import LastLib.Book05LocalClassFieldTheory.Chapter09.Dependencies
import LastLib.Book05LocalClassFieldTheory.Chapter09.Section01WhyDirectionsAreEasyToReverseAccidentally
import LastLib.Book05LocalClassFieldTheory.Chapter09.Section02NormCorrespondsToGaloisInclusion
import LastLib.Book05LocalClassFieldTheory.Chapter09.Section03MultiplicativeInclusionCorrespondsToTransfer
import LastLib.Book05LocalClassFieldTheory.Chapter09.Section04TowersAndFiniteQuotientDiagrams
import LastLib.Book05LocalClassFieldTheory.Chapter09.Section05BaseChangeAndNormSubgroups
