import LastLib.Book05LocalClassFieldTheory.Chapter06.Dependencies
import LastLib.Book05LocalClassFieldTheory.Chapter06.Section01WhyASeparateExistenceConstructionIsNecessary
import LastLib.Book05LocalClassFieldTheory.Chapter06.Section02FormalModule
import LastLib.Book05LocalClassFieldTheory.Chapter06.Section03TorsionPointsAndEisensteinPolynomials
import LastLib.Book05LocalClassFieldTheory.Chapter06.Section04GaloisActionOnTorsion
import LastLib.Book05LocalClassFieldTheory.Chapter06.Section05NormGroupOfTheTorsionExtension
import LastLib.Book05LocalClassFieldTheory.Chapter06.Section06AddingTheUnramifiedDirection
import LastLib.Book05LocalClassFieldTheory.Chapter06.Section07TheExistenceTheorem
