import LastLib.Book04AdelesAndIdeles.Chapter10.Section01TheLocalNormAsAMultiplicativeDeterminant
import LastLib.Book04AdelesAndIdeles.Chapter10.Section02TheAdelicNorm
import LastLib.Book04AdelesAndIdeles.Chapter10.Section03CompatibilityWithPrincipalIdeles
import LastLib.Book04AdelesAndIdeles.Chapter10.Section04LocalConditionsVersusGlobalNorm
import LastLib.Book04AdelesAndIdeles.Chapter10.Section05ExamplesOfNormBehavior
import LastLib.Book04AdelesAndIdeles.Chapter10.Section06NormsAndCongruenceDepth
