import LastLib.Book04AdelesAndIdeles.Chapter15.Section01MatricesOverTheAdeles
import LastLib.Book04AdelesAndIdeles.Chapter15.Section02DiagonalPointsAndDeterminants
import LastLib.Book04AdelesAndIdeles.Chapter15.Section03CompactOpenLevel
import LastLib.Book04AdelesAndIdeles.Chapter15.Section04DoubleQuotientsAndLattices
import LastLib.Book04AdelesAndIdeles.Chapter15.Section05AutomorphicFunctions
import LastLib.Book04AdelesAndIdeles.Chapter15.Section06RankOneMeetingPoint

/-! Chapter 15 is assembled from its chronological section leaves. -/
