import LastLib.Book04AdelesAndIdeles.Chapter13.Section01WhyCharactersBelongHere
import LastLib.Book04AdelesAndIdeles.Chapter13.Section02AssemblingMultiplicativeCharacters
import LastLib.Book04AdelesAndIdeles.Chapter13.Section03UnitaryCharactersAndModulusTwists
import LastLib.Book04AdelesAndIdeles.Chapter13.Section04FiniteOrderCharactersAndConductors
import LastLib.Book04AdelesAndIdeles.Chapter13.Section05TheStandardAdditiveCharacter
import LastLib.Book04AdelesAndIdeles.Chapter13.Section06SelfDualityAndTheDiagonalAnnihilator
