import LastLib.Book04AdelesAndIdeles.Chapter12.Core
import LastLib.Book04AdelesAndIdeles.Chapter12.Section01TheRationalField
import LastLib.Book04AdelesAndIdeles.Chapter12.Section02TheGaussianField
import LastLib.Book04AdelesAndIdeles.Chapter12.Section03ARealQuadraticField
import LastLib.Book04AdelesAndIdeles.Chapter12.Section04ANonprincipalIdealAsAnIdele
import LastLib.Book04AdelesAndIdeles.Chapter12.Section05SplitPlacesAndNormComponents
import LastLib.Book04AdelesAndIdeles.Chapter12.Section06QuadraticSplittingAsAnAdelicProduct
