import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter04.Dependencies
import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter04.Section01DepthAndCodimension
import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter04.Section02DimensionOneCoincidence
import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter04.Section03NormalSurfacesNeedNotBeRegular
import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter04.Section04JacobianAndFiberwiseCriteria
