import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter06.Dependencies
import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter06.Section01SpreadingEquations
import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter06.Section02ProjectiveClosure
import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter06.Section03RemovingUnwantedComponents
import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter06.Section04NormalizationOfTheClosure
import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter06.Section05ExistenceAndUniquenessUpToModification
