import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter08.Dependencies
import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter08.Section01TheResolutionTheoremInTheRequiredSetting
import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter08.Section02PreparingTheSingularLocus
import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter08.Section03ADecreasingLocalInvariant
import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter08.Section04Termination
import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter08.Section05Examples

namespace LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter08

/-! Aggregator for Book 11, Chapter 8: resolution of excellent surface singularities. -/

end LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter08
