import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter02.Dependencies
import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter02.Section01AffineConstruction
import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter02.Section02LocalizationAndGluing
import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter02.Section03UniversalProperty
import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter02.Section04BirationalInvarianceAndComponents
