import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter09.Dependencies
import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter09.Section01ExistenceOverExcellentDedekindBases
import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter09.Section02KeepingAPrescribedGoodOpen
import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter09.Section03DominatingFinitelyManyModels
import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter09.Section04SectionsAndClosuresOfPoints

namespace LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter09

/-! Aggregator for Book 11, Chapter 9: regular proper models. -/

end LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter09
