import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter10.Section01IntegralClosureOfTheBase
import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter10.Section02BaseChangeCanDestroyNormality
import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter10.Section03TheNormalizeAfterBaseChangeRule
import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter10.Section04RamificationAndVerticalMultiplicities
import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter10.Section05DescentOfModels
