import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter12.Dependencies
import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter12.Section01TheExactReusableModelTheorem
import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter12.Section02ModularCurves
import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter12.Section03ShimuraCurves
import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter12.Section04SemistableReductionInput
import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter12.Section05FiniteCorrespondences

namespace LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter12

/-! Aggregator for Book 11, Chapter 12: models for modular, Shimura, and semistable problems. -/

end LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter12
