import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter01.Dependencies
import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter01.Section01FromACurveOverAFieldToASurface
import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter01.Section02TheHierarchyOfHypotheses
import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter01.Section03StandingConventions
