import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Algebra.Group.Subgroup.Basic
import Mathlib.Data.Set.Countable
import Mathlib.Order.Filter.Cofinite
import Mathlib.Topology.Algebra.Group.Basic
import Mathlib.Topology.Compactness.Compact
import Mathlib.Topology.Constructions
import Mathlib.Topology.MetricSpace.Pseudo.Defs
import Mathlib.Topology.UniformSpace.CompleteSeparated

namespace LastLib.Book04AdelesAndIdeles.Chapter03

open Set Filter
open scoped BigOperators Pointwise Topology

noncomputable section

universe u v w

/-!
Shared interfaces for Chapter 3.

The restricted product is represented as the subgroup of the dependent product
whose elements are in the distinguished subgroups on a cofinite set of
indices.  The topology is generated by the products which have a distinguished
tail.  This keeps the algebraic object canonical while leaving the proofs of
the topological assertions to the section files.
-/

section AlgebraicConstruction

variable {I : Type u} {G : I → Type v} [∀ i, Group (G i)]

/-- The cofinite integrality condition on a family of local elements. -/
def chapter03AlmostAllIn (H : ∀ i, Subgroup (G i)) (x : ∀ i, G i) : Prop :=
  ∀ᶠ i in Filter.cofinite, x i ∈ H i

/-- The indices at which a family leaves the distinguished subgroup. -/
def chapter03ExceptionalSet (H : ∀ i, Subgroup (G i)) (x : ∀ i, G i) : Set I :=
  {i | x i ∉ H i}

/-- The subgroup defining the algebraic restricted product. -/
def chapter03RestrictedProductSubgroup (H : ∀ i, Subgroup (G i)) :
    Subgroup (∀ i, G i) where
  carrier := {x | chapter03AlmostAllIn H x}
  one_mem' := by
    change ∀ᶠ i in Filter.cofinite, (1 : G i) ∈ H i
    exact Filter.Eventually.of_forall (fun i => (H i).one_mem)
  mul_mem' := by
    intro x y hx hy
    change ∀ᶠ i in Filter.cofinite, x i ∈ H i at hx
    change ∀ᶠ i in Filter.cofinite, y i ∈ H i at hy
    exact (hx.and hy).mono fun i hi => (H i).mul_mem hi.1 hi.2
  inv_mem' := by
    intro x hx
    change ∀ᶠ i in Filter.cofinite, x i ∈ H i at hx
    exact hx.mono fun i hi => (H i).inv_mem hi

/-- The type of families integral at almost every place. -/
abbrev Chapter03RestrictedProduct (H : ∀ i, Subgroup (G i)) :=
  chapter03RestrictedProductSubgroup H

@[simp]
theorem chapter03_restrictedProduct_mem_iff
    (H : ∀ i, Subgroup (G i)) (x : ∀ i, G i) :
    x ∈ chapter03RestrictedProductSubgroup H ↔ chapter03AlmostAllIn H x :=
  Iff.rfl

@[ext]
theorem chapter03_restrictedProduct_ext
    (H : ∀ i, Subgroup (G i))
    {x y : Chapter03RestrictedProduct H}
    (h : ∀ i, ((x : ∀ i, G i) i) = ((y : ∀ i, G i) i)) :
    x = y := by
  apply Subtype.ext
  funext i
  exact h i

theorem chapter03_restrictedProduct_mem_iff_exceptional_finite
    (H : ∀ i, Subgroup (G i)) (x : ∀ i, G i) :
    x ∈ chapter03RestrictedProductSubgroup H ↔
      (chapter03ExceptionalSet H x).Finite := by
  simp [chapter03RestrictedProductSubgroup, chapter03AlmostAllIn,
    chapter03ExceptionalSet, Filter.eventually_cofinite]

/-- A family has infinitely many denominators relative to `H`. -/
def chapter03InfinitelyManyExceptionalCoordinates
    (H : ∀ i, Subgroup (G i)) (x : ∀ i, G i) : Prop :=
  (chapter03ExceptionalSet H x).Infinite

theorem chapter03_not_mem_restrictedProduct_iff_infinitely_many_exceptional
    (H : ∀ i, Subgroup (G i)) (x : ∀ i, G i) :
    x ∉ chapter03RestrictedProductSubgroup H ↔
      chapter03InfinitelyManyExceptionalCoordinates H x := by
  rw [chapter03_restrictedProduct_mem_iff_exceptional_finite]
  rfl

/-- The identity family in the unrestricted dependent product. -/
def chapter03IdentityFamily : ∀ i, G i := fun _ => 1

theorem chapter03_identityFamily_mem_restrictedProduct
    (H : ∀ i, Subgroup (G i)) :
    chapter03IdentityFamily ∈ chapter03RestrictedProductSubgroup H := by
  exact (chapter03RestrictedProductSubgroup H).one_mem

/-- A book-facing diagonal family assembled from local component maps. -/
def chapter03DiagonalFamily {A : Type w}
    (localComponent : ∀ i, A → G i) (a : A) : ∀ i, G i :=
  fun i => localComponent i a

theorem chapter03_diagonalFamily_mem_restrictedProduct
    {A : Type w} (H : ∀ i, Subgroup (G i))
    (localComponent : ∀ i, A → G i) (a : A)
    (halmost : ∀ᶠ i in Filter.cofinite,
      localComponent i a ∈ H i) :
    chapter03DiagonalFamily localComponent a ∈
      chapter03RestrictedProductSubgroup H :=
  halmost

/-- Finite-indexed exceptional stages. -/
def Chapter03FiniteStageIndex := {S : Set I // S.Finite}

instance chapter03FiniteStageIndexPreorder :
    Preorder (Chapter03FiniteStageIndex (I := I)) where
  le S T := S.1 ⊆ T.1
  le_refl S := Set.Subset.refl S.1
  le_trans _ _ _ hST hTU := Set.Subset.trans hST hTU

instance chapter03FiniteStageIndex_nonempty :
    Nonempty (Chapter03FiniteStageIndex (I := I)) :=
  ⟨⟨∅, Set.finite_empty⟩⟩

instance chapter03FiniteStageIndex_isDirected :
    IsDirectedOrder (Chapter03FiniteStageIndex (I := I)) where
  directed S T := by
    refine ⟨⟨S.1 ∪ T.1, S.2.union T.2⟩, ?_, ?_⟩
    · change S.1 ⊆ S.1 ∪ T.1
      intro i hi
      exact Or.inl hi
    · change T.1 ⊆ S.1 ∪ T.1
      intro i hi
      exact Or.inr hi

/-- The subgroup with unrestricted coordinates in `S` and integral tail. -/
def chapter03StageSubgroup (H : ∀ i, Subgroup (G i)) (S : Set I) :
    Subgroup (Chapter03RestrictedProduct H) where
  carrier := {x | ∀ i, i ∉ S → (x : ∀ i, G i) i ∈ H i}
  one_mem' := by
    intro i hi
    exact (H i).one_mem
  mul_mem' := by
    intro x y hx hy i hi
    exact (H i).mul_mem (hx i hi) (hy i hi)
  inv_mem' := by
    intro x hx i hi
    exact (H i).inv_mem (hx i hi)

abbrev Chapter03Stage (H : ∀ i, Subgroup (G i)) (S : Set I) :=
  chapter03StageSubgroup H S

theorem chapter03_stage_mem_iff
    (H : ∀ i, Subgroup (G i)) (S : Set I)
    (x : Chapter03RestrictedProduct H) :
    x ∈ chapter03StageSubgroup H S ↔
      ∀ i, i ∉ S → (x : ∀ i, G i) i ∈ H i :=
  Iff.rfl

theorem chapter03_stage_mono
    (H : ∀ i, Subgroup (G i)) {S T : Set I} (hST : S ⊆ T) :
    chapter03StageSubgroup H S ≤ chapter03StageSubgroup H T := by
  intro x hx i hi
  exact hx i (fun hiS => hi (hST hiS))

theorem chapter03_stage_inter
    (H : ∀ i, Subgroup (G i)) (S T : Set I) :
    chapter03StageSubgroup H (S ∩ T) =
      chapter03StageSubgroup H S ⊓ chapter03StageSubgroup H T := by
  ext x
  change (∀ i, i ∉ S ∩ T → ((x : ∀ i, G i) i) ∈ H i) ↔
    ((∀ i, i ∉ S → ((x : ∀ i, G i) i) ∈ H i) ∧
      (∀ i, i ∉ T → ((x : ∀ i, G i) i) ∈ H i))
  constructor
  · intro hx
    constructor
    · intro i hi
      exact hx i (fun h => hi h.1)
    · intro i hi
      exact hx i (fun h => hi h.2)
  · rintro ⟨hxS, hxT⟩ i hi
    by_cases hiS : i ∉ S
    · exact hxS i hiS
    · have hiSin : i ∈ S := by simpa using hiS
      exact hxT i (fun hiT => hi ⟨hiSin, hiT⟩)

theorem chapter03_restrictedProduct_eq_iUnion_finite_stages
    (H : ∀ i, Subgroup (G i)) :
    (Set.univ : Set (Chapter03RestrictedProduct H)) =
      ⋃ S : Chapter03FiniteStageIndex,
        (chapter03StageSubgroup H S.1 : Set (Chapter03RestrictedProduct H)) := by
  apply Set.Subset.antisymm
  · intro x _
    have hfin :=
      (chapter03_restrictedProduct_mem_iff_exceptional_finite H
        (x : ∀ i, G i)).1 x.property
    refine Set.mem_iUnion.2
      ⟨⟨chapter03ExceptionalSet H (x : ∀ i, G i), hfin⟩, ?_⟩
    intro i hi
    exact not_not.mp hi
  · intro x _
    exact Set.mem_univ x

end AlgebraicConstruction

section AdditiveConstruction

variable {I : Type u} {G : I → Type v} [∀ i, AddGroup (G i)]

/-- Additive version of the algebraic restricted product. -/
def chapter03AdditiveRestrictedProductSubgroup
    (H : ∀ i, AddSubgroup (G i)) : AddSubgroup (∀ i, G i) where
  carrier := {x | ∀ᶠ i in Filter.cofinite, x i ∈ H i}
  zero_mem' := by
    change ∀ᶠ i in Filter.cofinite, (0 : G i) ∈ H i
    exact Filter.Eventually.of_forall (fun i => (H i).zero_mem)
  add_mem' := by
    intro x y hx hy
    change ∀ᶠ i in Filter.cofinite, x i ∈ H i at hx
    change ∀ᶠ i in Filter.cofinite, y i ∈ H i at hy
    exact (hx.and hy).mono fun i hi => (H i).add_mem hi.1 hi.2
  neg_mem' := by
    intro x hx
    change ∀ᶠ i in Filter.cofinite, x i ∈ H i at hx
    exact hx.mono fun i hi => (H i).neg_mem hi

abbrev Chapter03AdditiveRestrictedProduct
    (H : ∀ i, AddSubgroup (G i)) :=
  chapter03AdditiveRestrictedProductSubgroup H

def chapter03AdditiveZeroFamily : ∀ i, G i := fun _ => 0

theorem chapter03_additiveZeroFamily_mem_restrictedProduct
    (H : ∀ i, AddSubgroup (G i)) :
    chapter03AdditiveZeroFamily ∈
      chapter03AdditiveRestrictedProductSubgroup H := by
  exact (chapter03AdditiveRestrictedProductSubgroup H).zero_mem

theorem chapter03_additiveRestrictedProduct_mem_iff
    (H : ∀ i, AddSubgroup (G i)) (x : ∀ i, G i) :
    x ∈ chapter03AdditiveRestrictedProductSubgroup H ↔
      ∀ᶠ i in Filter.cofinite, x i ∈ H i :=
  Iff.rfl

@[ext]
theorem chapter03_additiveRestrictedProduct_ext
    (H : ∀ i, AddSubgroup (G i))
    {x y : Chapter03AdditiveRestrictedProduct H}
    (h : ∀ i, ((x : ∀ i, G i) i) = ((y : ∀ i, G i) i)) :
    x = y := by
  apply Subtype.ext
  funext i
  exact h i

end AdditiveConstruction

section AdditiveTopology

variable {I : Type u} {G : I → Type v} [∀ i, AddGroup (G i)]

def chapter03AdditiveBasicProductSet
    (H : ∀ i, AddSubgroup (G i)) (U : ∀ i, Set (G i)) :
    Set (Chapter03AdditiveRestrictedProduct H) :=
  {x | ∀ i, (x : ∀ i, G i) i ∈ U i}

def chapter03AdditiveBasicProductCondition
    [∀ i, TopologicalSpace (G i)]
    (H : ∀ i, AddSubgroup (G i)) (U : ∀ i, Set (G i)) : Prop :=
  (∀ i, IsOpen (U i)) ∧
    ∀ᶠ i in Filter.cofinite, U i = (H i : Set (G i))

def chapter03AdditiveBasicOpenSets
    [∀ i, TopologicalSpace (G i)]
    (H : ∀ i, AddSubgroup (G i)) :
    Set (Set (Chapter03AdditiveRestrictedProduct H)) :=
  {s | ∃ U : ∀ i, Set (G i),
    chapter03AdditiveBasicProductCondition H U ∧
      s = chapter03AdditiveBasicProductSet H U}

@[instance_reducible]
def chapter03AdditiveRestrictedProductTopology
    [∀ i, TopologicalSpace (G i)]
    (H : ∀ i, AddSubgroup (G i)) :
    TopologicalSpace (Chapter03AdditiveRestrictedProduct H) :=
  TopologicalSpace.generateFrom (chapter03AdditiveBasicOpenSets H)

instance chapter03AdditiveRestrictedProduct.topologicalSpace
    [∀ i, TopologicalSpace (G i)]
    (H : ∀ i, AddSubgroup (G i)) :
    TopologicalSpace (Chapter03AdditiveRestrictedProduct H) :=
  chapter03AdditiveRestrictedProductTopology H

def chapter03AdditiveDistinguishedTail
    (H : ∀ i, AddSubgroup (G i)) :
    Set (Chapter03AdditiveRestrictedProduct H) :=
  {x | ∀ i, (x : ∀ i, G i) i ∈ H i}

end AdditiveTopology

section StagesAndTopology

variable {I : Type u} {G : I → Type v} [∀ i, Group (G i)]

/-- A product of coordinate sets, intersected with the restricted product. -/
def chapter03BasicProductSet
    (H : ∀ i, Subgroup (G i)) (U : ∀ i, Set (G i)) :
    Set (Chapter03RestrictedProduct H) :=
  {x | ∀ i, (x : ∀ i, G i) i ∈ U i}

/-- The finiteness condition on the exceptional coordinates of a basic set. -/
def chapter03BasicProductCondition
    [∀ i, TopologicalSpace (G i)]
    (H : ∀ i, Subgroup (G i)) (U : ∀ i, Set (G i)) : Prop :=
  (∀ i, IsOpen (U i)) ∧
    ∀ᶠ i in Filter.cofinite, U i = (H i : Set (G i))

def chapter03BasicOpenSets
    [∀ i, TopologicalSpace (G i)]
    (H : ∀ i, Subgroup (G i)) : Set (Set (Chapter03RestrictedProduct H)) :=
  {s | ∃ U : ∀ i, Set (G i),
    chapter03BasicProductCondition H U ∧ s = chapter03BasicProductSet H U}

/-- The restricted-product topology generated by basic products with an
integral tail. -/
@[instance_reducible]
def chapter03RestrictedProductTopology
    [∀ i, TopologicalSpace (G i)]
    (H : ∀ i, Subgroup (G i)) :
    TopologicalSpace (Chapter03RestrictedProduct H) :=
  TopologicalSpace.generateFrom (chapter03BasicOpenSets H)

instance chapter03RestrictedProduct.topologicalSpace
    [∀ i, TopologicalSpace (G i)]
    (H : ∀ i, Subgroup (G i)) :
    TopologicalSpace (Chapter03RestrictedProduct H) :=
  chapter03RestrictedProductTopology H

theorem chapter03_mem_basicProductSet_iff
    (H : ∀ i, Subgroup (G i)) (U : ∀ i, Set (G i))
    (x : Chapter03RestrictedProduct H) :
    x ∈ chapter03BasicProductSet H U ↔
      ∀ i, (x : ∀ i, G i) i ∈ U i :=
  Iff.rfl

theorem chapter03_basicProductSet_inter
    (H : ∀ i, Subgroup (G i)) (U V : ∀ i, Set (G i)) :
    chapter03BasicProductSet H U ∩ chapter03BasicProductSet H V =
      chapter03BasicProductSet H (fun i => U i ∩ V i) := by
  ext x
  change
    ((∀ i, ((x : ∀ i, G i) i) ∈ U i) ∧
      (∀ i, ((x : ∀ i, G i) i) ∈ V i)) ↔
      ∀ i, ((x : ∀ i, G i) i) ∈ U i ∩ V i
  constructor
  · rintro ⟨hU, hV⟩ i
    exact ⟨hU i, hV i⟩
  · intro h
    exact ⟨fun i => (h i).1, fun i => (h i).2⟩

def chapter03DistinguishedTail
    (H : ∀ i, Subgroup (G i)) : Set (Chapter03RestrictedProduct H) :=
  chapter03StageSubgroup H (∅ : Set I)

theorem chapter03_distinguishedTail_mem_iff
    (H : ∀ i, Subgroup (G i)) (x : Chapter03RestrictedProduct H) :
    x ∈ chapter03DistinguishedTail H ↔
      ∀ i, (x : ∀ i, G i) i ∈ H i := by
  change
    (∀ i, i ∉ (∅ : Set I) → (x : ∀ i, G i) i ∈ H i) ↔
      ∀ i, (x : ∀ i, G i) i ∈ H i
  constructor
  · intro hx i
    exact hx i (by simp)
  · intro hx i hi
    exact hx i

def chapter03InfinitelyManyProperDistinguishedSubgroups
    (H : ∀ i, Subgroup (G i)) : Prop :=
  {i | H i ≠ ⊤}.Infinite

@[instance_reducible]
def chapter03UnrestrictedProductSubspaceTopology
    [∀ i, TopologicalSpace (G i)]
    (H : ∀ i, Subgroup (G i)) :
    TopologicalSpace (Chapter03RestrictedProduct H) :=
  TopologicalSpace.induced
    (fun x : Chapter03RestrictedProduct H => (x : ∀ i, G i))
    inferInstance

theorem chapter03_basicProductSet_isOpen
    [∀ i, TopologicalSpace (G i)]
    (H : ∀ i, Subgroup (G i)) (U : ∀ i, Set (G i))
    (hU : chapter03BasicProductCondition H U) :
    IsOpen (chapter03BasicProductSet H U) := by
  change IsOpen[chapter03RestrictedProductTopology H]
    (chapter03BasicProductSet H U)
  exact TopologicalSpace.isOpen_generateFrom_of_mem ⟨U, hU, rfl⟩

theorem chapter03_stage_isOpen
    [∀ i, TopologicalSpace (G i)]
    (H : ∀ i, Subgroup (G i)) {S : Set I} (hS : S.Finite)
    (hH : ∀ i, IsOpen (H i : Set (G i))) :
    IsOpen (chapter03StageSubgroup H S : Set (Chapter03RestrictedProduct H)) := by
  classical
  let U : ∀ i, Set (G i) := fun i =>
    if i ∈ S then Set.univ else (H i : Set (G i))
  have hU : chapter03BasicProductCondition H U := by
    constructor
    · intro i
      by_cases hi : i ∈ S
      · simp [U, hi]
      · simpa [U, hi] using hH i
    · filter_upwards [hS.compl_mem_cofinite] with i hi
      have hi' : i ∉ S := by simpa using hi
      simp [U, hi']
  have hset : chapter03BasicProductSet H U =
      (chapter03StageSubgroup H S : Set (Chapter03RestrictedProduct H)) := by
    ext x
    change (∀ i, ((x : ∀ i, G i) i) ∈ U i) ↔
      ∀ i, i ∉ S → ((x : ∀ i, G i) i) ∈ H i
    constructor
    · intro hx i hi
      simpa [U, hi] using hx i
    · intro hx i
      by_cases hi : i ∈ S
      · simp [U, hi]
      · simpa [U, hi] using hx i hi
  rw [← hset]
  exact chapter03_basicProductSet_isOpen H U hU

theorem chapter03_stage_is_basicProduct
    [∀ i, TopologicalSpace (G i)]
    (H : ∀ i, Subgroup (G i)) {S : Set I} (hS : S.Finite)
    (hH : ∀ i, IsOpen (H i : Set (G i))) :
    ∃ U : ∀ i, Set (G i),
      chapter03BasicProductCondition H U ∧
        chapter03BasicProductSet H U =
          (chapter03StageSubgroup H S : Set (Chapter03RestrictedProduct H)) := by
  classical
  let U : ∀ i, Set (G i) := fun i =>
    if i ∈ S then Set.univ else (H i : Set (G i))
  have hU : chapter03BasicProductCondition H U := by
    constructor
    · intro i
      by_cases hi : i ∈ S
      · simp [U, hi]
      · simpa [U, hi] using hH i
    · filter_upwards [hS.compl_mem_cofinite] with i hi
      have hi' : i ∉ S := by simpa using hi
      simp [U, hi']
  refine ⟨U, hU, ?_⟩
  ext x
  change (∀ i, ((x : ∀ i, G i) i) ∈ U i) ↔
    ∀ i, i ∉ S → ((x : ∀ i, G i) i) ∈ H i
  constructor
  · intro hx i hi
    simpa [U, hi] using hx i
  · intro hx i
    by_cases hi : i ∈ S
    · simp [U, hi]
    · simpa [U, hi] using hx i hi

theorem chapter03_restrictedTopology_ne_subspaceTopology
    [∀ i, TopologicalSpace (G i)]
    (H : ∀ i, Subgroup (G i))
    (hH : ∀ i, IsOpen (H i : Set (G i)))
    (hproper : chapter03InfinitelyManyProperDistinguishedSubgroups H) :
    chapter03RestrictedProductTopology H ≠
      chapter03UnrestrictedProductSubspaceTopology H := by
  classical
  intro htop
  have htailR : IsOpen[chapter03RestrictedProductTopology H]
      (chapter03DistinguishedTail H) := by
    exact chapter03_stage_isOpen H Set.finite_empty hH
  have htailU : IsOpen[chapter03UnrestrictedProductSubspaceTopology H]
      (chapter03DistinguishedTail H) := by
    rw [← htop]
    exact htailR
  have hone : (1 : Chapter03RestrictedProduct H) ∈ chapter03DistinguishedTail H := by
    rw [chapter03_distinguishedTail_mem_iff]
    intro i
    exact (H i).one_mem
  let _ : TopologicalSpace (Chapter03RestrictedProduct H) :=
    chapter03UnrestrictedProductSubspaceTopology H
  have htail_mem : chapter03DistinguishedTail H ∈ 𝓝 (1 : Chapter03RestrictedProduct H) :=
    htailU.mem_nhds hone
  rcases (mem_nhds_induced
      (fun x : Chapter03RestrictedProduct H => (x : ∀ i, G i))
      (1 : Chapter03RestrictedProduct H)
      (chapter03DistinguishedTail H)).mp htail_mem with ⟨U, hUnh, hUsub⟩
  have hUnh' : U ∈ 𝓝 (1 : ∀ i, G i) := hUnh
  rw [nhds_pi, Filter.mem_pi'] at hUnh'
  rcases hUnh' with ⟨K, V, hV, hKV⟩
  change {i | H i ≠ ⊤}.Infinite at hproper
  obtain ⟨i, hi, hiK⟩ := hproper.exists_notMem_finset K
  have hi' : H i ≠ ⊤ := hi
  obtain ⟨g, hg⟩ := SetLike.exists_not_mem_of_ne_top (H i) hi'
  let y : ∀ j, G j := Function.update chapter03IdentityFamily i g
  have hy : y ∈ chapter03RestrictedProductSubgroup H := by
    rw [chapter03_restrictedProduct_mem_iff_exceptional_finite]
    apply (Set.finite_singleton i).subset
    intro j hj
    by_contra hji
    apply hj
    have hji' : j ≠ i := by
      intro hji'
      apply hji
      simp [hji']
    have hyj : y j = 1 := by
      simp [y, chapter03IdentityFamily, hji']
    rw [hyj]
    exact (H j).one_mem
  let z : Chapter03RestrictedProduct H := ⟨y, hy⟩
  have hyK : y ∈ Set.pi (↑K : Set I) V := by
    intro j hj
    have hjV : V j ∈ 𝓝 (chapter03IdentityFamily j) := hV j
    have honeV : chapter03IdentityFamily j ∈ V j := mem_of_mem_nhds hjV
    have hji : j ≠ i := by
      intro hji
      subst j
      exact hiK hj
    simpa [y, hji] using honeV
  have hyU : y ∈ U := hKV hyK
  have hzpre : z ∈
      (fun x : Chapter03RestrictedProduct H => (x : ∀ i, G i)) ⁻¹' U := by
    exact hyU
  have hzT : z ∈ chapter03DistinguishedTail H := hUsub hzpre
  have hgi : g ∈ H i := by
    have hgi' := (chapter03_distinguishedTail_mem_iff H z).mp hzT i
    change y i ∈ H i at hgi'
    simpa [y] using hgi'
  exact hg hgi

end StagesAndTopology

section ScalarProducts

variable {I : Type u} {G : I → Type v} [∀ i, Group (G i)]

/-- The exceptional set of a coordinatewise scalar-valued family at `x`. -/
def chapter03ScalarExceptionalSet {M : Type w} [Monoid M]
    (φ : ∀ i, G i → M) (x : ∀ i, G i) : Set I :=
  {i | φ i (x i) ≠ 1}

def chapter03ScalarProductSupportedOnFiniteSet {M : Type w} [Monoid M]
    (φ : ∀ i, G i → M) (x : ∀ i, G i) : Prop :=
  (chapter03ScalarExceptionalSet φ x).Finite

/-- The product over a finite subset of the index set. -/
noncomputable def chapter03FiniteSubsetProduct
    {M : Type w} [CommMonoid M]
    (φ : ∀ i, G i → M) (x : ∀ i, G i)
    (S : Chapter03FiniteStageIndex (I := I)) : M := by
  classical
  exact ∏ i ∈ S.2.toFinset, φ i (x i)

/-- A separate convergence argument for products over larger and larger finite
subsets. -/
def chapter03ScalarProductConvergesAlongFiniteSubsets
    {M : Type w} [CommMonoid M] [TopologicalSpace M]
    (φ : ∀ i, G i → M) (x : ∀ i, G i) : Prop :=
  ∃ y : M,
    Tendsto (chapter03FiniteSubsetProduct φ x) atTop (𝓝 y)

def chapter03ScalarProductIsDefined
    {M : Type w} [CommMonoid M] [TopologicalSpace M]
    (φ : ∀ i, G i → M) (x : ∀ i, G i) : Prop :=
  chapter03ScalarProductSupportedOnFiniteSet φ x ∨
    chapter03ScalarProductConvergesAlongFiniteSubsets φ x

/- The canonical product when the exceptional scalar support is finite. -/
noncomputable def chapter03FiniteSupportProduct
    {M : Type w} [CommMonoid M]
    (φ : ∀ i, G i → M) (x : ∀ i, G i)
    (h : (chapter03ScalarExceptionalSet φ x).Finite) : M := by
  classical
  exact ∏ i ∈ h.toFinset, φ i (x i)

omit [(i : I) → Group (G i)] in
theorem chapter03_finiteSupportProduct_eq_one
    {M : Type w} [CommMonoid M]
    (φ : ∀ i, G i → M) (x : ∀ i, G i)
    (h : (chapter03ScalarExceptionalSet φ x).Finite)
    (hφ : ∀ i, φ i (x i) = 1) :
    chapter03FiniteSupportProduct φ x h = 1 := by
  classical
  simp [chapter03FiniteSupportProduct, hφ]

omit [(i : I) → Group (G i)] in
theorem chapter03_finiteSupportProduct_eq_finiteSubsetProduct_of_subset
    {M : Type w} [CommMonoid M]
    (φ : ∀ i, G i → M) (x : ∀ i, G i)
    (h : (chapter03ScalarExceptionalSet φ x).Finite)
    (S : Chapter03FiniteStageIndex)
    (hS : chapter03ScalarExceptionalSet φ x ⊆ S.1) :
    chapter03FiniteSupportProduct φ x h =
      chapter03FiniteSubsetProduct φ x S := by
  classical
  rw [chapter03FiniteSupportProduct, chapter03FiniteSubsetProduct]
  apply Finset.prod_subset
  · intro i hi
    exact S.2.mem_toFinset.mpr (hS (h.mem_toFinset.mp hi))
  · intro i hiS hi
    by_contra hne
    apply hi
    exact h.mem_toFinset.mpr (by
      simpa [chapter03ScalarExceptionalSet] using hne)

end ScalarProducts

end
end LastLib.Book04AdelesAndIdeles.Chapter03
