import LastLib.Book06GlobalClassFieldTheory.Chapter04.Section01WhyCohomologyIsTheRightAccountingSystem
import LastLib.Book06GlobalClassFieldTheory.Chapter04.Section02TheBrauerIdeleExactSequence
import LastLib.Book06GlobalClassFieldTheory.Chapter04.Section03ConstructionOfTheFundamentalClass
import LastLib.Book06GlobalClassFieldTheory.Chapter04.Section04TheTwoClassFormationLemmas
import LastLib.Book06GlobalClassFieldTheory.Chapter04.Section05RestrictionCorestrictionAndInvariantNormalizations
import LastLib.Book06GlobalClassFieldTheory.Chapter04.Section06CupProductsAndTheLocalTrace
import LastLib.Book06GlobalClassFieldTheory.Chapter04.Section07TheGlobalTraceAndTheDualityPairing
import LastLib.Book06GlobalClassFieldTheory.Chapter04.Section08NormsInductionAndShapiroCompatibility

namespace LastLib.Book06GlobalClassFieldTheory.Chapter04

/-! Aggregator for Book 6, Chapter 4: the global class formation. -/

end LastLib.Book06GlobalClassFieldTheory.Chapter04
