import LastLib.Book06GlobalClassFieldTheory.Chapter08.Dependencies
import LastLib.Book06GlobalClassFieldTheory.Chapter08.Section01CongruenceBecomesFrobenius
import LastLib.Book06GlobalClassFieldTheory.Chapter08.Section02HilbertClassField
import LastLib.Book06GlobalClassFieldTheory.Chapter08.Section03QuadraticExamples
import LastLib.Book06GlobalClassFieldTheory.Chapter08.Section04CyclotomicRayFields
import LastLib.Book06GlobalClassFieldTheory.Chapter08.Section05QuadraticReciprocity
