import LastLib.Book06GlobalClassFieldTheory.Chapter12.Section01FieldsSubgroupsAndQuotients
import LastLib.Book06GlobalClassFieldTheory.Chapter12.Section02LocalMultiplicativeDataAndGlobalGaloisData
import LastLib.Book06GlobalClassFieldTheory.Chapter12.Section03ModuliRamificationAndSplitting
import LastLib.Book06GlobalClassFieldTheory.Chapter12.Section04NormsWithoutAmbiguity
import LastLib.Book06GlobalClassFieldTheory.Chapter12.Section05CharactersAtAGlance
import LastLib.Book06GlobalClassFieldTheory.Chapter12.Section06Conclusion
