import Mathlib.Algebra.Algebra.Subalgebra.Basic
import Mathlib.Algebra.Algebra.Subalgebra.Lattice
import Mathlib.RingTheory.Ideal.Quotient.Basic
import Mathlib.RingTheory.Localization.Away.Basic

import LastLib.Book12BlowupsAndIntersectionTheoryOnArithmeticSurfaces.Chapter05.Dependencies

namespace LastLib.Book12BlowupsAndIntersectionTheoryOnArithmeticSurfaces.Chapter05

noncomputable section

open AlgebraicGeometry CategoryTheory CategoryTheory.Limits
open LastLib.Book08AmpleLineBundlesHilbertPolynomialsAndSymmetricPowers.Chapter02
open LastLib.Book08AmpleLineBundlesHilbertPolynomialsAndSymmetricPowers.Chapter09

universe u v

/-! ### 5.1 Regularity of the new surface -/

def chapter05UChartRelation {X : Scheme.{u}}
    [Chapter05RegularNoetherianSurface X]
    (P : Chapter05RegularPoint X) :
    Polynomial (Chapter05LocalRing P) :=
  Polynomial.C (Chapter05ParameterV P) -
    Polynomial.C (Chapter05ParameterU P) * Polynomial.X

def chapter05VChartRelation {X : Scheme.{u}}
    [Chapter05RegularNoetherianSurface X]
    (P : Chapter05RegularPoint X) :
    Polynomial (Chapter05LocalRing P) :=
  Polynomial.C (Chapter05ParameterU P) -
    Polynomial.C (Chapter05ParameterV P) * Polynomial.X

/-- The `u`-chart in the local presentation `A[t]/(v - u t)`. -/
abbrev chapter05UChartRing {X : Scheme.{u}}
    [Chapter05RegularNoetherianSurface X]
    (P : Chapter05RegularPoint X) : Type u :=
  Polynomial (Chapter05LocalRing P) ⧸
    Ideal.span ({chapter05UChartRelation P} :
      Set (Polynomial (Chapter05LocalRing P)))

/-- The `v`-chart in the local presentation `A[s]/(u - v s)`. -/
abbrev chapter05VChartRing {X : Scheme.{u}}
    [Chapter05RegularNoetherianSurface X]
    (P : Chapter05RegularPoint X) : Type u :=
  Polynomial (Chapter05LocalRing P) ⧸
    Ideal.span ({chapter05VChartRelation P} :
      Set (Polynomial (Chapter05LocalRing P)))

def chapter05PointCenterIdeal {X : Scheme.{u}}
    [Chapter05RegularNoetherianSurface X]
    (P : Chapter05RegularPoint X) : Ideal (Chapter05LocalRing P) :=
  IsLocalRing.maximalIdeal (Chapter05LocalRing P)

theorem chapter05_pointCenterIdeal_eq_parameters {X : Scheme.{u}}
    [Chapter05RegularNoetherianSurface X]
    (P : Chapter05RegularPoint X) :
    chapter05PointCenterIdeal P =
      Ideal.span ({Chapter05ParameterU P, Chapter05ParameterV P} :
        Set (Chapter05LocalRing P)) := by
  exact P.parameters_is_regular_system.1.symm

def chapter05UChartParameterU {X : Scheme.{u}}
    [Chapter05RegularNoetherianSurface X]
    (P : Chapter05RegularPoint X) : chapter05UChartRing P :=
  Ideal.Quotient.mk _ (Polynomial.C (Chapter05ParameterU P))

def chapter05VChartParameterV {X : Scheme.{u}}
    [Chapter05RegularNoetherianSurface X]
    (P : Chapter05RegularPoint X) : chapter05VChartRing P :=
  Ideal.Quotient.mk _ (Polynomial.C (Chapter05ParameterV P))

def chapter05UChartExceptionalIdeal {X : Scheme.{u}}
    [Chapter05RegularNoetherianSurface X]
    (P : Chapter05RegularPoint X) : Ideal (chapter05UChartRing P) :=
  Ideal.span ({chapter05UChartParameterU P} : Set (chapter05UChartRing P))

def chapter05VChartExceptionalIdeal {X : Scheme.{u}}
    [Chapter05RegularNoetherianSurface X]
    (P : Chapter05RegularPoint X) : Ideal (chapter05VChartRing P) :=
  Ideal.span ({chapter05VChartParameterV P} : Set (chapter05VChartRing P))

def chapter05UChartRatio {X : Scheme.{u}}
    [Chapter05RegularNoetherianSurface X]
    (P : Chapter05RegularPoint X) :
    Localization.Away (Chapter05ParameterU P) :=
  IsLocalization.mk' (Localization.Away (Chapter05ParameterU P))
    (Chapter05ParameterV P)
    (⟨Chapter05ParameterU P, Submonoid.mem_powers _⟩ :
      Submonoid.powers (Chapter05ParameterU P))

def chapter05VChartRatio {X : Scheme.{u}}
    [Chapter05RegularNoetherianSurface X]
    (P : Chapter05RegularPoint X) :
    Localization.Away (Chapter05ParameterV P) :=
  IsLocalization.mk' (Localization.Away (Chapter05ParameterV P))
    (Chapter05ParameterU P)
    (⟨Chapter05ParameterV P, Submonoid.mem_powers _⟩ :
      Submonoid.powers (Chapter05ParameterV P))

/-- The subring of `Aᵤ` generated by `A` and `v/u`. -/
def chapter05UChartSubring {X : Scheme.{u}}
    [Chapter05RegularNoetherianSurface X]
    (P : Chapter05RegularPoint X) :
    Subring (Localization.Away (Chapter05ParameterU P)) :=
  (Algebra.adjoin (Chapter05LocalRing P)
    ({chapter05UChartRatio P} :
      Set (Localization.Away (Chapter05ParameterU P)))).toSubring

/-- The subring of `Aᵥ` generated by `A` and `u/v`. -/
def chapter05VChartSubring {X : Scheme.{u}}
    [Chapter05RegularNoetherianSurface X]
    (P : Chapter05RegularPoint X) :
    Subring (Localization.Away (Chapter05ParameterV P)) :=
  (Algebra.adjoin (Chapter05LocalRing P)
    ({chapter05VChartRatio P} :
      Set (Localization.Away (Chapter05ParameterV P)))).toSubring

/- LOCAL_DEPENDENCY_GUESS: the affine chart quotient-to-localization identifications are the
standard point-blowup chart theorem, not a primitive of the pinned Rees-algebra API. -/
theorem chapter05_uChart_quotient_equiv_subring {X : Scheme.{u}}
    [Chapter05RegularNoetherianSurface X]
    (P : Chapter05RegularPoint X) :
    Nonempty (chapter05UChartRing P ≃+* chapter05UChartSubring P) := by
  sorry

theorem chapter05_vChart_quotient_equiv_subring {X : Scheme.{u}}
    [Chapter05RegularNoetherianSurface X]
    (P : Chapter05RegularPoint X) :
    Nonempty (chapter05VChartRing P ≃+* chapter05VChartSubring P) := by
  sorry

structure Chapter05ChartOverlap {X : Scheme.{u}}
    [Chapter05RegularNoetherianSurface X]
    (P : Chapter05RegularPoint X) (R : Type u) [CommRing R] where
  t : Rˣ
  s : R
  transition : s * (t : R) = 1

theorem chapter05_chart_overlap_transition
    {X : Scheme.{u}} [Chapter05RegularNoetherianSurface X]
    {P : Chapter05RegularPoint X} {R : Type u} [CommRing R]
    (O : Chapter05ChartOverlap P R) :
    O.s = (↑(O.t⁻¹) : R) := by
  sorry

structure Chapter05AwayFromPointIso {X Y : Scheme.{u}}
    [Chapter05RegularNoetherianSurface X]
    (P : Chapter05RegularPoint X) (b : Y ⟶ X) where
  source_open : Y.Opens
  target_open : X.Opens
  source_open_eq_complement :
    (source_open : Set Y) = {y | b y ≠ P.point}
  target_open_eq_complement :
    (target_open : Set X) = {x | x ≠ P.point}
  iso : source_open.toScheme ≅ target_open.toScheme
  commutes : iso.hom ≫ target_open.ι = source_open.ι ≫ b

abbrev Chapter05ProjectiveMorphism {Y X : Scheme.{u}} (f : Y ⟶ X) : Prop :=
  Chapter09ProjectiveMorphism f

/- The preceding Chapter 3 interface supplies the relative-Rees/Proj presentation and the
universal blowup object.  The point-center fields below identify that canonical object with the
chosen closed point; projectivity, birationality, and regularity are retained as the separate
geometric properties used by this chapter. -/
structure Chapter05PointBlowupConstruction {X : Scheme.{u}}
    [Chapter05RegularNoetherianSurface X]
    (P : Chapter05RegularPoint X) where
  center_ideal :
    LastLib.Book12BlowupsAndIntersectionTheoryOnArithmeticSurfaces.Chapter03.Chapter03CoherentIdeal X
  center_support : (center_ideal.ideal.support : Set X) = {P.point}
  center_is_point :
    center_ideal.ideal.subscheme ≅ AlgebraicGeometry.Spec (X.residueField P.point)
  center_is_point_over :
    center_is_point.hom ≫ X.fromSpecResidueField P.point = center_ideal.ideal.subschemeι
  blowup :
    LastLib.Book12BlowupsAndIntersectionTheoryOnArithmeticSurfaces.Chapter03.Chapter03Blowup
      center_ideal
  projective : Chapter05ProjectiveMorphism blowup.projection
  birational : Scheme.Birational blowup.carrier X
  away_from_point : Chapter05AwayFromPointIso P blowup.projection

abbrev Chapter05PointBlowupConstruction.carrier {X : Scheme.{u}}
    [Chapter05RegularNoetherianSurface X]
    {P : Chapter05RegularPoint X}
    (B : Chapter05PointBlowupConstruction P) : Scheme.{u} :=
  B.blowup.carrier

abbrev Chapter05PointBlowupConstruction.projection {X : Scheme.{u}}
    [Chapter05RegularNoetherianSurface X]
    {P : Chapter05RegularPoint X}
    (B : Chapter05PointBlowupConstruction P) : B.carrier ⟶ X :=
  B.blowup.projection

theorem chapter05_pointBlowup_construction_exists {X : Scheme.{u}}
    [Chapter05RegularNoetherianSurface X]
    (P : Chapter05RegularPoint X) :
    Nonempty (Chapter05PointBlowupConstruction P) := by
  sorry

noncomputable def chapter05PointBlowup {X : Scheme.{u}}
    [Chapter05RegularNoetherianSurface X]
    (P : Chapter05RegularPoint X) :
    Chapter05PointBlowupConstruction P :=
  Classical.choice (chapter05_pointBlowup_construction_exists P)

structure Chapter05ExceptionalDivisor {X : Scheme.{u}}
    [Chapter05RegularNoetherianSurface X]
    {P : Chapter05RegularPoint X}
    (B : Chapter05PointBlowupConstruction P) where
  carrier : Scheme.{u}
  inclusion : carrier ⟶ B.carrier
  closed_immersion : IsClosedImmersion inclusion
  structure_map : carrier ⟶ AlgebraicGeometry.Spec (X.residueField P.point)
  maps_to_center :
    structure_map ≫ X.fromSpecResidueField P.point = inclusion ≫ B.projection
  projective_line_iso :
    carrier ≅ chapter05ProjectiveLine (X.residueField P.point)
  projective_line_iso_over_base :
    projective_line_iso.hom ≫
        chapter02ProjectiveSpaceProjection
          (AlgebraicGeometry.Spec (.of (X.residueField P.point))) 1 =
      structure_map
  canonical_exceptional_iso :
    carrier ≅ B.blowup.canonical_blowup.tautologicalIdeal.ideal.subscheme
  canonical_exceptional_over :
    canonical_exceptional_iso.hom ≫
        B.blowup.canonical_blowup.tautologicalIdeal.ideal.subschemeι =
      inclusion ≫ B.blowup.comparison.hom

/- LOCAL_DEPENDENCY_GUESS: identifying the exceptional closed subscheme from the Rees construction
with `P¹_{κ(x)}` is the geometric output of the point-blowup API. -/
theorem chapter05_exceptional_divisor_exists {X : Scheme.{u}}
    [Chapter05RegularNoetherianSurface X]
    (P : Chapter05RegularPoint X) :
    Nonempty (Chapter05ExceptionalDivisor (chapter05PointBlowup P)) := by
  sorry

noncomputable def chapter05ExceptionalDivisor {X : Scheme.{u}}
    [Chapter05RegularNoetherianSurface X]
    (P : Chapter05RegularPoint X) :
    Chapter05ExceptionalDivisor (chapter05PointBlowup P) :=
  Classical.choice (chapter05_exceptional_divisor_exists P)

theorem chapter05_blowup_is_regular {X : Scheme.{u}}
    [Chapter05RegularNoetherianSurface X]
    (P : Chapter05RegularPoint X) :
    Chapter05RegularNoetherianSurface (chapter05PointBlowup P).carrier := by
  sorry

theorem chapter05_blowup_is_projective {X : Scheme.{u}}
    [Chapter05RegularNoetherianSurface X]
    (P : Chapter05RegularPoint X) :
    Chapter05ProjectiveMorphism
      (chapter05PointBlowup P).projection :=
  (chapter05PointBlowup P).projective

theorem chapter05_blowup_is_birational {X : Scheme.{u}}
    [Chapter05RegularNoetherianSurface X]
    (P : Chapter05RegularPoint X) :
    Scheme.Birational (chapter05PointBlowup P).carrier X :=
  (chapter05PointBlowup P).birational

def chapter05_blowup_isomorphism_away_from_point {X : Scheme.{u}}
    [Chapter05RegularNoetherianSurface X]
    (P : Chapter05RegularPoint X) :
    Chapter05AwayFromPointIso P (chapter05PointBlowup P).projection :=
  (chapter05PointBlowup P).away_from_point

theorem chapter05_exceptional_divisor_is_projective_line {X : Scheme.{u}}
    [Chapter05RegularNoetherianSurface X]
    (P : Chapter05RegularPoint X) :
    Nonempty
      ((chapter05ExceptionalDivisor P).carrier ≅
        chapter05ProjectiveLine (X.residueField P.point)) := by
  exact ⟨(chapter05ExceptionalDivisor P).projective_line_iso⟩

theorem chapter05_exceptional_divisor_is_projective_line_over_base {X : Scheme.{u}}
    [Chapter05RegularNoetherianSurface X]
    (P : Chapter05RegularPoint X) :
    Nonempty
      { e : (chapter05ExceptionalDivisor P).carrier ≅
          chapter05ProjectiveLine (X.residueField P.point) //
        e.hom ≫
            chapter02ProjectiveSpaceProjection
              (AlgebraicGeometry.Spec (.of (X.residueField P.point))) 1 =
          (chapter05ExceptionalDivisor P).structure_map } := by
  exact ⟨⟨(chapter05ExceptionalDivisor P).projective_line_iso,
    (chapter05ExceptionalDivisor P).projective_line_iso_over_base⟩⟩

/-!
The regular-point hypotheses are intentionally visible in every construction above.  In
particular, this API does not claim regularity for a nonreduced zero-dimensional center or for a
blowup of the reduced singular point of a singular surface.
-/

def Chapter05RegularPointCenterScope (A : Type u) [CommRing A]
    (I : Ideal A) : Prop :=
  ∃ hI : I.IsPrime, I.IsRadical ∧
    letI : I.IsPrime := hI
    IsRegularLocalRing (Localization.AtPrime I)

end

end LastLib.Book12BlowupsAndIntersectionTheoryOnArithmeticSurfaces.Chapter05
