import LastLib.Book03RamificationTheory.Chapter06.Section01WhyOnlyUpperNumberingSurvivesInverseLimits
import LastLib.Book03RamificationTheory.Chapter06.Section02FiniteImageRepresentationsNeedOnlyFiniteLevels
import LastLib.Book03RamificationTheory.Chapter06.Section03FiniteUpperBreakDecompositions

/-! # Chapter 6. Ramification in infinite Galois extensions -/
