import LastLib.Book08AmpleLineBundlesHilbertPolynomialsAndSymmetricPowers.Chapter13.Dependencies
import LastLib.Book08AmpleLineBundlesHilbertPolynomialsAndSymmetricPowers.Chapter13.Section01GraphsAndSpacesOfMorphisms
import LastLib.Book08AmpleLineBundlesHilbertPolynomialsAndSymmetricPowers.Chapter13.Section02ClosedLociInsideParameterSpaces
import LastLib.Book08AmpleLineBundlesHilbertPolynomialsAndSymmetricPowers.Chapter13.Section03ProjectiveParameterSpacesForCurveFamilies
import LastLib.Book08AmpleLineBundlesHilbertPolynomialsAndSymmetricPowers.Chapter13.Section04BoundaryChecklist

/-!
Aggregator for Book 08, Chapter 13: universal constructions for later geometry.
-/
