import LastLib.Book03RamificationTheory.Chapter08.Dependencies

namespace LastLib.Book03RamificationTheory.Chapter08

noncomputable section

open Ideal Matrix
open scoped BigOperators Polynomial nonZeroDivisors

/-! ## 8.1. From a dual lattice to an ideal downstairs -/

/- The trace Gram matrix is the matrix of this canonical integral
   trace-pairing inclusion. -/
def chapter08TracePairingInclusion
    (A B : Type*) [CommRing A] [CommRing B] [Algebra A B] :
    LinearMap.BilinForm A B :=
  Algebra.traceForm A B

@[simp]
theorem chapter08TracePairingInclusion_apply
    (A B : Type*) [CommRing A] [CommRing B] [Algebra A B]
    (x y : B) :
    chapter08TracePairingInclusion A B x y =
      Algebra.trace A B (x * y) := by
  rfl

theorem chapter08_trace_pairing_inclusion_fraction_field
    (A B K L : Type*) [CommRing A] [IsDomain A] [CommRing B]
    [Field K] [Field L] [Algebra A B] [Algebra A K] [Algebra K L]
    [Algebra B L] [Algebra A L] [IsScalarTower A K L]
    [IsScalarTower A B L] [IsFractionRing A K] [IsFractionRing B L]
    [FiniteDimensional K L] [Algebra.IsSeparable K L]
    [IsIntegralClosure B A L] [IsIntegrallyClosed A]
    [IsDedekindDomain B] [Module.Finite A B] [Module.Free A B] :
    ∀ x y : B,
      algebraMap A K (chapter08TracePairingInclusion A B x y) =
        Algebra.trace K L (algebraMap B L x * algebraMap B L y) := by
  exact fun x y => by
    change algebraMap A K (Algebra.trace A B (x * y)) = _
    rw [← Algebra.intTrace_eq_trace A B]
    calc
      algebraMap A K (Algebra.intTrace A B (x * y)) =
          Algebra.trace K L (algebraMap B L (x * y)) :=
        Algebra.algebraMap_intTrace (A := A) (B := B) (K := K) (L := L) (x * y)
      _ = Algebra.trace K L (algebraMap B L x * algebraMap B L y) := by
        rw [map_mul]

/- The Gram matrix of the trace pairing.  `Algebra.traceMatrix` is the
   canonical matrix implementation of the displayed entries. -/
def chapter08TraceGramMatrix
    (A B : Type*) [CommRing A] [CommRing B] [Algebra A B]
    {ι : Type*} (b : ι → B) : Matrix ι ι A :=
  Algebra.traceMatrix A b

@[simp]
theorem chapter08TraceGramMatrix_apply
    (A B : Type*) [CommRing A] [CommRing B] [Algebra A B]
    {ι : Type*} (b : ι → B) (i j : ι) :
    chapter08TraceGramMatrix A B b i j = Algebra.trace A B (b i * b j) := by
  rfl

/- The determinant is the element-level discriminant of a finite family. -/
noncomputable def chapter08DiscriminantElement
    (A B : Type*) [CommRing A] [CommRing B] [Algebra A B]
    {ι : Type*} [Fintype ι] [DecidableEq ι] (b : ι → B) : A :=
  Algebra.discr A b

@[simp]
theorem chapter08DiscriminantElement_eq_gram_det
    (A B : Type*) [CommRing A] [CommRing B] [Algebra A B]
    {ι : Type*} [Fintype ι] [DecidableEq ι] (b : ι → B) :
    chapter08DiscriminantElement A B b =
      (chapter08TraceGramMatrix A B b).det := by
  rfl

/-- The principal ideal generated by the discriminant of a chosen basis. -/
noncomputable def chapter08DiscriminantIdealOfBasis
    (A B : Type*) [CommRing A] [CommRing B] [Algebra A B]
    {ι : Type*} [Fintype ι] [DecidableEq ι] (b : Module.Basis ι A B) : Ideal A :=
  Ideal.span ({chapter08DiscriminantElement A B b} : Set A)

/-- A basis-independent relative discriminant ideal, using a canonical free basis. -/
noncomputable def chapter08RelativeDiscriminantIdeal
    (A B : Type*) [CommRing A] [CommRing B]
    [Algebra A B] [IsDedekindDomain A] [IsDedekindDomain B]
    [Module.Finite A B] [Module.Free A B] [Module.IsTorsionFree A B] : Ideal A :=
  Ideal.span
    ({chapter08DiscriminantElement A B (Module.Free.chooseBasis A B)} : Set A)

theorem chapter08_discriminant_basis_change
    (A B : Type*) [CommRing A] [CommRing B]
    [Algebra A B] {ι : Type*} [Fintype ι] [DecidableEq ι]
    (b b' : Module.Basis ι A B) :
    ∃ u : Aˣ,
      chapter08DiscriminantElement A B b' =
        (u : A) ^ 2 * chapter08DiscriminantElement A B b := by
  exact by
    let P : Matrix ι ι A := b.toMatrix b'
    have hP : b ᵥ* P.map (algebraMap A B) = b' := by
      dsimp [P]
      exact b.toMatrix_map_vecMul b'
    have hdet : IsUnit P.det := by
      dsimp [P]
      rw [← b.det_apply]
      exact b.isUnit_det b'
    refine ⟨hdet.unit, ?_⟩
    rw [← hP]
    change Algebra.discr A (b ᵥ* P.map (algebraMap A B)) = _
    rw [Algebra.discr_of_matrix_vecMul]
    rw [hdet.unit_spec]
    rfl

theorem chapter08_discriminant_ideal_of_basis_independent
    (A B : Type*) [CommRing A] [CommRing B]
    [Algebra A B] [IsDedekindDomain A] [IsDedekindDomain B]
    [Module.Finite A B] [Module.Free A B] [Module.IsTorsionFree A B]
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (b : Module.Basis ι A B) :
    chapter08DiscriminantIdealOfBasis A B b =
      chapter08RelativeDiscriminantIdeal A B := by
  exact by
    let c := Module.Free.chooseBasis A B
    let e : Module.Free.ChooseBasisIndex A B ≃ ι :=
      Fintype.equivOfCardEq (by
        rw [← Module.finrank_eq_card_basis c, ← Module.finrank_eq_card_basis b])
    let c' := c.reindex e
    have hdisc : chapter08DiscriminantElement A B c' =
        chapter08DiscriminantElement A B c := by
      change Algebra.discr A (c.reindex e) = Algebra.discr A c
      rw [Module.Basis.coe_reindex]
      exact Algebra.discr_reindex (A := A) (B := B) c e
    change Ideal.span ({chapter08DiscriminantElement A B b} : Set A) =
      Ideal.span ({chapter08DiscriminantElement A B c} : Set A)
    rw [← hdisc]
    apply Ideal.span_singleton_eq_span_singleton.mpr
    obtain ⟨u, hu⟩ := chapter08_discriminant_basis_change A B b c'
    rw [hu]
    exact (associated_unit_mul_left _ _ (u.isUnit.pow 2)).symm

theorem chapter08_relative_discriminant_ideal_eq_norm_different
    (A B K L : Type*) [CommRing A] [CommRing B]
    [Field K] [Field L] [Algebra A B] [Algebra A K] [Algebra K L]
    [Algebra B L] [Algebra A L] [IsScalarTower A K L]
    [IsScalarTower A B L] [IsFractionRing A K] [IsFractionRing B L]
    [FiniteDimensional K L] [Algebra.IsSeparable K L]
    [IsIntegralClosure B A L]
    [IsDedekindDomain A] [IsDedekindDomain B]
    [Module.Finite A B] [Module.Free A B] [Module.IsTorsionFree A B]
    [Algebra.IsIntegral A B] :
    chapter08RelativeDiscriminantIdeal A B =
      Ideal.relNorm A (chapter08DifferentIdeal A B) := by
  sorry

/- The integral trace dual is the inverse of the different.  The coercion
   equality is the bridge from the book's lattice notation to Mathlib's
   fractional-ideal API. -/
theorem chapter08_codifferent_fractional_coe_eq_traceDual
    (A B K L : Type*) [CommRing A] [IsDomain A] [CommRing B]
    [Field K] [Field L] [Algebra A B] [Algebra A K] [Algebra K L]
    [Algebra B L] [Algebra A L] [IsScalarTower A K L]
    [IsScalarTower A B L] [IsFractionRing A K] [IsFractionRing B L]
    [FiniteDimensional K L] [Algebra.IsSeparable K L]
    [IsIntegralClosure B A L] [IsIntegrallyClosed A]
    [IsDedekindDomain B] :
    (LastLib.Book03RamificationTheory.Chapter07.chapter07CodifferentFractionalIdeal
      A B K L : Set L) =
      LastLib.Book02FiniteExtensionsOfLocalFields.Chapter04.chapter04TraceDual A B K L := by
  exact LastLib.Book03RamificationTheory.Chapter07.chapter07_codifferent_fractional_coe_eq A B K L

theorem chapter08_different_fractional_coe_eq_ideal
    (A B K L : Type*) [CommRing A] [IsDomain A] [CommRing B]
    [Field K] [Field L] [Algebra A B] [Algebra A K] [Algebra K L]
    [Algebra B L] [Algebra A L] [IsScalarTower A K L]
    [IsScalarTower A B L] [IsFractionRing A K] [IsFractionRing B L]
    [FiniteDimensional K L] [Algebra.IsSeparable K L]
    [IsIntegralClosure B A L] [IsIntegrallyClosed A]
    [IsDedekindDomain B] [Module.IsTorsionFree A B] :
    (chapter08DifferentIdeal A B : FractionalIdeal B⁰ L) =
      LastLib.Book03RamificationTheory.Chapter07.chapter07DifferentFractionalIdeal A B K L := by
  exact LastLib.Book03RamificationTheory.Chapter07.chapter07_different_fractional_coe_eq A B K L

/- The quotient is formed in the dual lattice itself, so its length is the
   book's `length_A(B^∨/B)` rather than the length of the ambient field. -/
abbrev chapter08TraceDualQuotient
    (A B K L : Type*) [CommRing A] [CommRing B] [Field K] [Field L]
    [Algebra A B] [Algebra A K] [Algebra K L] [Algebra B L] [Algebra A L]
    [IsScalarTower A K L] [IsScalarTower A B L] : Type _ :=
  (chapter08TraceDualLattice A B K L).restrictScalars A ⧸
      ((1 : Submodule B L).restrictScalars A).comap
      ((chapter08TraceDualLattice A B K L).restrictScalars A).subtype

private theorem chapter08_span_inv_quotient_length
    (A B L : Type*) [CommRing A] [IsDomain A]
    [IsDiscreteValuationRing A] [CommRing B]
    [IsDedekindDomain B] [IsDiscreteValuationRing B] [Field L]
    [Algebra A B] [Algebra B L] [Algebra A L] [IsFractionRing B L]
    [IsScalarTower A B L] [Algebra.IsIntegral A B]
    [Module.IsTorsionFree A B]
    (g : B) (hg : g ≠ 0) :
    Module.length A
        ((FractionalIdeal.spanSingleton B⁰ (algebraMap B L g)⁻¹ :
          Submodule B L).restrictScalars A ⧸
          ((1 : Submodule B L).restrictScalars A).comap
            ((FractionalIdeal.spanSingleton B⁰ (algebraMap B L g)⁻¹ :
              Submodule B L).restrictScalars A).subtype) =
      Module.length A (B ⧸ Ideal.span ({g} : Set B)) := by
  let u : L := (algebraMap B L g)⁻¹
  let D : Submodule B L :=
    (FractionalIdeal.spanSingleton B⁰ u : Submodule B L)
  let I : Ideal B := Ideal.span ({g} : Set B)
  have hmapg : algebraMap B L g ≠ 0 := by
    intro h
    apply hg
    exact (IsFractionRing.injective B L) (by simpa using h)
  have hu : u ≠ 0 := by
    simp [u, hmapg]
  change Module.length A
      (D.restrictScalars A ⧸
        ((1 : Submodule B L).restrictScalars A).comap
          (D.restrictScalars A).subtype) = Module.length A (B ⧸ I)
  let coeff : D → B := fun z =>
    Classical.choose ((FractionalIdeal.mem_spanSingleton B⁰).mp z.property)
  have coeff_spec (z : D) : algebraMap B L (coeff z) * u = z := by
    have hz := Classical.choose_spec
      ((FractionalIdeal.mem_spanSingleton B⁰).mp z.property)
    simpa [coeff, u, Algebra.smul_def] using hz
  have coeff_mul (z : D) : algebraMap B L (coeff z) = z * algebraMap B L g := by
    calc
      algebraMap B L (coeff z) = algebraMap B L (coeff z) * 1 := by simp
      _ = algebraMap B L (coeff z) * (u * algebraMap B L g) := by
        rw [show u * algebraMap B L g = 1 by simp [u, hmapg]]
      _ = (algebraMap B L (coeff z) * u) * algebraMap B L g := by ring
      _ = z * algebraMap B L g := by rw [coeff_spec]
  have coeff_add (x y : D) : coeff (x + y) = coeff x + coeff y := by
    apply IsFractionRing.injective B L
    simp only [map_add, coeff_mul]
    change ((x : L) + (y : L)) * algebraMap B L g =
      (x : L) * algebraMap B L g + (y : L) * algebraMap B L g
    rw [add_mul]
  have coeff_smul (b : B) (z : D) : coeff (b • z) = b * coeff z := by
    apply IsFractionRing.injective B L
    calc
      algebraMap B L (coeff (b • z)) =
          (b • z : L) * algebraMap B L g := coeff_mul _
      _ = algebraMap B L b * ((z : L) * algebraMap B L g) := by
        simp only [Algebra.smul_def]
        ring
      _ = algebraMap B L b * algebraMap B L (coeff z) := by rw [← coeff_mul]
      _ = algebraMap B L (b * coeff z) := by rw [map_mul]
  let coeffMap : D →ₗ[B] B :=
    { toFun := coeff
      map_add' := coeff_add
      map_smul' := coeff_smul }
  let q : D →ₗ[B] (B ⧸ I) := I.mkQ.comp coeffMap
  have qker : LinearMap.ker q =
      ((1 : Submodule B L).comap D.subtype) := by
    ext z
    constructor
    · intro hz
      change I.mkQ (coeff z) = 0 at hz
      have hzI : coeff z ∈ I := by
        exact (Submodule.Quotient.mk_eq_zero I).mp hz
      obtain ⟨b, hb⟩ := (Ideal.mem_span_singleton).mp hzI
      rw [Submodule.one_eq_range]
      refine ⟨b, ?_⟩
      calc
        algebraMap B L b = algebraMap B L b *
            (algebraMap B L g * u) := by simp [u, hmapg]
        _ = algebraMap B L (g * b) * u := by rw [map_mul]; ring
        _ = algebraMap B L (coeff z) * u := by rw [hb]
        _ = z := coeff_spec z
    · intro hz
      have hz' : (z : L) ∈ (1 : Submodule B L) := hz
      rw [Submodule.one_eq_range] at hz'
      obtain ⟨b, hb⟩ := hz'
      change I.mkQ (coeff z) = 0
      apply (Submodule.Quotient.mk_eq_zero I).mpr
      apply (Ideal.mem_span_singleton).mpr
      refine ⟨b, ?_⟩
      apply IsFractionRing.injective B L
      calc
        algebraMap B L (coeff z) = z * algebraMap B L g := coeff_mul z
        _ = algebraMap B L b * algebraMap B L g := by
          simpa only [Algebra.linearMap_apply] using
            congrArg (fun x : L => x * algebraMap B L g) hb.symm
        _ = algebraMap B L (g * b) := by rw [map_mul]; ring
  have qsurj : Function.Surjective q := by
    intro y
    obtain ⟨b, rfl⟩ := I.mkQ_surjective y
    let z : D :=
      ⟨algebraMap B L b * u, by
        apply (FractionalIdeal.mem_spanSingleton B⁰).mpr
        refine ⟨b, ?_⟩
        simp [Algebra.smul_def]
      ⟩
    refine ⟨z, ?_⟩
    change I.mkQ (coeffMap z) = I.mkQ b
    congr 1
    change coeff z = b
    apply IsFractionRing.injective B L
    rw [coeff_mul]
    simp [z, u, hmapg]
  let r : D.restrictScalars A ≃ₗ[A] D :=
    (Submodule.restrictScalarsEquiv A B L D).restrictScalars A
  let qA : D.restrictScalars A →ₗ[A] (B ⧸ I) :=
    (q.restrictScalars A).comp r.toLinearMap
  have qkerA : LinearMap.ker qA =
      ((1 : Submodule B L).restrictScalars A).comap
        (D.restrictScalars A).subtype := by
    ext z
    change r z ∈ LinearMap.ker q ↔ (z : L) ∈ (1 : Submodule B L)
    rw [qker]
    change (r z : L) ∈ (1 : Submodule B L) ↔ (z : L) ∈ (1 : Submodule B L)
    rfl
  have qAsurj : Function.Surjective qA := qsurj.comp r.surjective
  let e₀ := qA.quotKerEquivOfSurjective qAsurj
  let e :=
    (Submodule.quotEquivOfEq _ _ qkerA.symm).trans e₀
  exact e.length_eq

theorem chapter08_trace_dual_quotient_length
    (A B K L : Type*) [CommRing A] [IsDomain A]
    [IsDiscreteValuationRing A] [CommRing B]
    [IsDedekindDomain B] [IsDiscreteValuationRing B] [Field K] [Field L]
    [Algebra A B] [Algebra A K] [Algebra K L] [Algebra B L]
    [Algebra A L] [IsScalarTower A K L] [IsScalarTower A B L]
    [IsFractionRing A K] [IsFractionRing B L] [FiniteDimensional K L]
    [Algebra.IsSeparable K L] [IsIntegralClosure B A L]
    [IsIntegrallyClosed A]
    [Module.Finite A B] [Module.Free A B] [Module.IsTorsionFree A B]
    [Algebra.IsIntegral A B]
    (mA : Ideal A) (mB : Ideal B) (f d : ℕ)
    (_hmaxA : mA = IsLocalRing.maximalIdeal A)
    (hmaxB : mB = IsLocalRing.maximalIdeal B)
    (hdifferent : chapter08DifferentIdeal A B = mB ^ d)
    (hresidue : (IsLocalRing.maximalIdeal B).inertiaDeg A = f) :
    Module.length A (chapter08TraceDualQuotient A B K L) =
      (f * d : ℕ∞) := by
  let _ : IsLocalHom (algebraMap A B) := inferInstance
  let _ : (IsLocalRing.maximalIdeal B).LiesOver
      (IsLocalRing.maximalIdeal A) := by
    rw [Ideal.liesOver_iff, Ideal.under_def]
    exact IsLocalRing.maximalIdeal_comap (algebraMap A B) |>.symm
  have hquot :=
    LastLib.Book01ValuationsDVRsAndCompletions.Chapter11.chapter11_length_prime_power_over_base
      A B (IsLocalRing.maximalIdeal A)
      (IsDiscreteValuationRing.not_a_field A)
      (IsLocalRing.maximalIdeal B) d
  have hmB0 : mB ≠ (⊥ : Ideal B) := by
    rw [hmaxB]
    exact IsDiscreteValuationRing.not_a_field B
  have hI0 : mB ^ d ≠ (⊥ : Ideal B) := by
    by_cases hd0 : d = 0
    · simp [hd0]
    · intro h
      exact hmB0 ((Ideal.pow_eq_bot hd0).mp h)
  have hprincipal : (mB ^ d).IsPrincipal := inferInstance
  let g : B := hprincipal.principal.choose
  have hgspan : mB ^ d = Ideal.span ({g} : Set B) := by
    exact hprincipal.principal.choose_spec
  have hg : g ≠ 0 := by
    intro hg0
    apply hI0
    rw [hgspan, hg0]
    simp
  let J : FractionalIdeal B⁰ L := (mB ^ d : Ideal B)
  have hdf :
      LastLib.Book03RamificationTheory.Chapter07.chapter07DifferentFractionalIdeal
          A B K L =
        J := by
    calc
      LastLib.Book03RamificationTheory.Chapter07.chapter07DifferentFractionalIdeal
          A B K L = (chapter08DifferentIdeal A B : FractionalIdeal B⁰ L) :=
        (chapter08_different_fractional_coe_eq_ideal A B K L).symm
      _ = J := by
        change (chapter08DifferentIdeal A B : FractionalIdeal B⁰ L) =
          (mB ^ d : Ideal B)
        rw [hdifferent]
  have hcodiff :
      LastLib.Book03RamificationTheory.Chapter07.chapter07CodifferentFractionalIdeal
          A B K L =
        J⁻¹ := by
    calc
      LastLib.Book03RamificationTheory.Chapter07.chapter07CodifferentFractionalIdeal
          A B K L =
          (LastLib.Book03RamificationTheory.Chapter07.chapter07DifferentFractionalIdeal
            A B K L)⁻¹ := by
        symm
        rw [chapter08_different_fractional_is_inverse_codifferent A B K L]
        simp
      _ = J⁻¹ := by rw [hdf]
  have hDsub : chapter08TraceDualLattice A B K L =
      ((J⁻¹ : FractionalIdeal B⁰ L) : Submodule B L) := by
    ext x
    change x ∈ (chapter08TraceDualLattice A B K L : Set L) ↔
      x ∈ ((J⁻¹ : FractionalIdeal B⁰ L) : Set L)
    rw [chapter08_traceDualLattice_coe_eq_traceDual,
      ← chapter08_codifferent_fractional_coe_eq_traceDual A B K L, hcodiff]
  have hfracpow :
      J =
        FractionalIdeal.spanSingleton B⁰ (algebraMap B L g) := by
    change ((mB ^ d : Ideal B) : FractionalIdeal B⁰ L) = _
    rw [hgspan]
    simp
  have hfracinv :
      J⁻¹ =
        FractionalIdeal.spanSingleton B⁰ (algebraMap B L g)⁻¹ := by
    rw [hfracpow, FractionalIdeal.spanSingleton_inv]
  have hquot' : Module.length A (B ⧸ mB ^ d) = (f * d : ℕ∞) := by
    rw [hmaxB]
    simpa [hresidue, mul_comm] using hquot
  change Module.length A
      ((chapter08TraceDualLattice A B K L).restrictScalars A ⧸
        ((1 : Submodule B L).restrictScalars A).comap
          ((chapter08TraceDualLattice A B K L).restrictScalars A).subtype) =
    (f * d : ℕ∞)
  rw [hDsub, hfracinv]
  rw [chapter08_span_inv_quotient_length A B L g hg, ← hgspan, hquot']

/- The norm of a maximal-ideal power records the residue-degree factor. -/
theorem chapter08_relative_norm_of_power
    (A B : Type*) [CommRing A] [CommRing B] [Algebra A B]
    [IsDedekindDomain A] [IsDedekindDomain B]
    [Module.Finite A B] [Module.IsTorsionFree A B]
    (mA : Ideal A) (mB : Ideal B) (f d : ℕ)
    (hnorm : Ideal.relNorm A mB = mA ^ f) :
    Ideal.relNorm A (mB ^ d) = mA ^ (f * d) := by
  rw [map_pow, hnorm, ← pow_mul]

theorem chapter08_discriminant_exponent_eq_residue_degree_mul_different
    (A B K L : Type*) [CommRing A] [CommRing B]
    [Field K] [Field L] [Algebra A B] [Algebra A K] [Algebra K L]
    [Algebra B L] [Algebra A L] [IsScalarTower A K L]
    [IsScalarTower A B L] [IsFractionRing A K] [IsFractionRing B L]
    [FiniteDimensional K L] [Algebra.IsSeparable K L]
    [IsIntegralClosure B A L] [Algebra.IsIntegral A B]
    [IsDedekindDomain A] [IsDedekindDomain B]
    [Module.Finite A B] [Module.Free A B] [Module.IsTorsionFree A B]
    (mA : Ideal A) (mB : Ideal B) (f d δ : ℕ)
    (hdisc : chapter08RelativeDiscriminantIdeal A B = mA ^ δ)
    (hdiff : chapter08DifferentIdeal A B = mB ^ d)
    (hnorm : Ideal.relNorm A mB = mA ^ f)
    (hδunique : ∃! n : ℕ,
      chapter08RelativeDiscriminantIdeal A B = mA ^ n) :
    δ = f * d := by
  have hnormdiff := chapter08_relative_discriminant_ideal_eq_norm_different
    A B K L
  have hpow : chapter08RelativeDiscriminantIdeal A B = mA ^ (f * d) := by
    rw [hnormdiff, hdiff, chapter08_relative_norm_of_power A B mA mB f d hnorm]
  exact hδunique.unique hdisc hpow

theorem chapter08_discriminant_exponent_eq_different_exponent_of_residue_degree_one
    (δ f d : ℕ) (hδ : δ = f * d) (hf : f = 1) :
    δ = d := by
  simpa [hf] using hδ

/- The normalized field norm identity used to pass from the different upstairs
   to the discriminant exponent downstairs. -/
theorem chapter08_norm_valuation_formula
    (K L : Type*) [Field K] [Field L] [Algebra K L]
    [FiniteDimensional K L] {vK : AddValuation K (WithTop ℤ)}
    {vL : AddValuation L (WithTop ℤ)} (e f : ℕ)
    [Valuation.IsRankOneDiscrete vK.toValuation]
    [Valuation.IsRankOneDiscrete vL.toValuation]
    (hext : vK.IsEquiv (AddValuation.comap (algebraMap K L) vL))
    (hrestriction : ∀ y : K,
      vL (algebraMap K L y) = (e : WithTop ℤ) * vK y)
    (hf : f =
      LastLib.Book01ValuationsDVRsAndCompletions.Chapter11.chapter11AdditiveResidueDegree
        vK vL hext)
    (hunique : ∀ w : AddValuation L (WithTop ℤ),
      vK.IsEquiv (AddValuation.comap (algebraMap K L) w) → vL.IsEquiv w)
    (hdegree : Module.finrank K L = e * f) (x : L) (hx : x ≠ 0) :
    vK (Algebra.norm K x) = (f : WithTop ℤ) * vL x := by
  exact LastLib.Book02FiniteExtensionsOfLocalFields.Chapter04.chapter04_norm_valuation_formula
    K L e f hext hrestriction hf hunique hdegree x hx

end

end LastLib.Book03RamificationTheory.Chapter08
