import LastLib.Book03RamificationTheory.Chapter08.Dependencies

namespace LastLib.Book03RamificationTheory.Chapter08

noncomputable section

open Ideal Matrix
open scoped BigOperators Polynomial nonZeroDivisors

/-! ## 8.1. From a dual lattice to an ideal downstairs -/

/- The trace Gram matrix is the matrix of this canonical integral
   trace-pairing inclusion. -/
def chapter08TracePairingInclusion
    (A B : Type*) [CommRing A] [CommRing B] [Algebra A B] :
    LinearMap.BilinForm A B :=
  Algebra.traceForm A B

@[simp]
theorem chapter08TracePairingInclusion_apply
    (A B : Type*) [CommRing A] [CommRing B] [Algebra A B]
    (x y : B) :
    chapter08TracePairingInclusion A B x y =
      Algebra.trace A B (x * y) := by
  rfl

theorem chapter08_trace_pairing_inclusion_fraction_field
    (A B K L : Type*) [CommRing A] [IsDomain A] [CommRing B]
    [Field K] [Field L] [Algebra A B] [Algebra A K] [Algebra K L]
    [Algebra B L] [Algebra A L] [IsScalarTower A K L]
    [IsScalarTower A B L] [IsFractionRing A K] [IsFractionRing B L]
    [FiniteDimensional K L] [Algebra.IsSeparable K L]
    [IsIntegralClosure B A L] [IsIntegrallyClosed A]
    [IsDedekindDomain B] [Module.Finite A B] [Module.Free A B] :
    ∀ x y : B,
      algebraMap A K (chapter08TracePairingInclusion A B x y) =
        Algebra.trace K L (algebraMap B L x * algebraMap B L y) := by
  sorry

/- The Gram matrix of the trace pairing.  `Algebra.traceMatrix` is the
   canonical matrix implementation of the displayed entries. -/
def chapter08TraceGramMatrix
    (A B : Type*) [CommRing A] [CommRing B] [Algebra A B]
    {ι : Type*} (b : ι → B) : Matrix ι ι A :=
  Algebra.traceMatrix A b

@[simp]
theorem chapter08TraceGramMatrix_apply
    (A B : Type*) [CommRing A] [CommRing B] [Algebra A B]
    {ι : Type*} (b : ι → B) (i j : ι) :
    chapter08TraceGramMatrix A B b i j = Algebra.trace A B (b i * b j) := by
  rfl

/- The determinant is the element-level discriminant of a finite family. -/
noncomputable def chapter08DiscriminantElement
    (A B : Type*) [CommRing A] [CommRing B] [Algebra A B]
    {ι : Type*} [Fintype ι] [DecidableEq ι] (b : ι → B) : A :=
  Algebra.discr A b

@[simp]
theorem chapter08DiscriminantElement_eq_gram_det
    (A B : Type*) [CommRing A] [CommRing B] [Algebra A B]
    {ι : Type*} [Fintype ι] [DecidableEq ι] (b : ι → B) :
    chapter08DiscriminantElement A B b =
      (chapter08TraceGramMatrix A B b).det := by
  rfl

/-- The principal ideal generated by the discriminant of a chosen basis. -/
noncomputable def chapter08DiscriminantIdealOfBasis
    (A B : Type*) [CommRing A] [CommRing B] [Algebra A B]
    {ι : Type*} [Fintype ι] [DecidableEq ι] (b : Module.Basis ι A B) : Ideal A :=
  Ideal.span ({chapter08DiscriminantElement A B b} : Set A)

/-- A basis-independent relative discriminant ideal, using a canonical free basis. -/
noncomputable def chapter08RelativeDiscriminantIdeal
    (A B : Type*) [CommRing A] [CommRing B]
    [Algebra A B] [IsDedekindDomain A] [IsDedekindDomain B]
    [Module.Finite A B] [Module.Free A B] [Module.IsTorsionFree A B] : Ideal A :=
  Ideal.span
    ({chapter08DiscriminantElement A B (Module.Free.chooseBasis A B)} : Set A)

theorem chapter08_discriminant_basis_change
    (A B : Type*) [CommRing A] [CommRing B]
    [Algebra A B] {ι : Type*} [Fintype ι] [DecidableEq ι]
    (b b' : Module.Basis ι A B) :
    ∃ u : Aˣ,
      chapter08DiscriminantElement A B b' =
        (u : A) ^ 2 * chapter08DiscriminantElement A B b := by
  sorry

theorem chapter08_discriminant_ideal_of_basis_independent
    (A B : Type*) [CommRing A] [CommRing B]
    [Algebra A B] [IsDedekindDomain A] [IsDedekindDomain B]
    [Module.Finite A B] [Module.Free A B] [Module.IsTorsionFree A B]
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (b : Module.Basis ι A B) :
    chapter08DiscriminantIdealOfBasis A B b =
      chapter08RelativeDiscriminantIdeal A B := by
  sorry

theorem chapter08_relative_discriminant_ideal_eq_norm_different
    (A B K L : Type*) [CommRing A] [CommRing B]
    [Field K] [Field L] [Algebra A B] [Algebra A K] [Algebra K L]
    [Algebra B L] [Algebra A L] [IsScalarTower A K L]
    [IsScalarTower A B L] [IsFractionRing A K] [IsFractionRing B L]
    [FiniteDimensional K L] [Algebra.IsSeparable K L]
    [IsIntegralClosure B A L]
    [IsDedekindDomain A] [IsDedekindDomain B]
    [Module.Finite A B] [Module.Free A B] [Module.IsTorsionFree A B]
    [Algebra.IsIntegral A B] :
    chapter08RelativeDiscriminantIdeal A B =
      Ideal.relNorm A (chapter08DifferentIdeal A B) := by
  sorry

/- The integral trace dual is the inverse of the different.  The coercion
   equality is the bridge from the book's lattice notation to Mathlib's
   fractional-ideal API. -/
theorem chapter08_codifferent_fractional_coe_eq_traceDual
    (A B K L : Type*) [CommRing A] [IsDomain A] [CommRing B]
    [Field K] [Field L] [Algebra A B] [Algebra A K] [Algebra K L]
    [Algebra B L] [Algebra A L] [IsScalarTower A K L]
    [IsScalarTower A B L] [IsFractionRing A K] [IsFractionRing B L]
    [FiniteDimensional K L] [Algebra.IsSeparable K L]
    [IsIntegralClosure B A L] [IsIntegrallyClosed A]
    [IsDedekindDomain B] :
    (LastLib.Book03RamificationTheory.Chapter07.chapter07CodifferentFractionalIdeal
      A B K L : Set L) =
      LastLib.Book02FiniteExtensionsOfLocalFields.Chapter04.chapter04TraceDual A B K L := by
  sorry

theorem chapter08_different_fractional_coe_eq_ideal
    (A B K L : Type*) [CommRing A] [IsDomain A] [CommRing B]
    [Field K] [Field L] [Algebra A B] [Algebra A K] [Algebra K L]
    [Algebra B L] [Algebra A L] [IsScalarTower A K L]
    [IsScalarTower A B L] [IsFractionRing A K] [IsFractionRing B L]
    [FiniteDimensional K L] [Algebra.IsSeparable K L]
    [IsIntegralClosure B A L] [IsIntegrallyClosed A]
    [IsDedekindDomain B] [Module.IsTorsionFree A B] :
    (chapter08DifferentIdeal A B : FractionalIdeal B⁰ L) =
      LastLib.Book03RamificationTheory.Chapter07.chapter07DifferentFractionalIdeal A B K L := by
  sorry

/- The quotient is formed in the dual lattice itself, so its length is the
   book's `length_A(B^∨/B)` rather than the length of the ambient field. -/
abbrev chapter08TraceDualQuotient
    (A B K L : Type*) [CommRing A] [CommRing B] [Field K] [Field L]
    [Algebra A B] [Algebra A K] [Algebra K L] [Algebra B L] [Algebra A L]
    [IsScalarTower A K L] [IsScalarTower A B L] : Type _ :=
  (chapter08TraceDualLattice A B K L).restrictScalars A ⧸
    ((1 : Submodule B L).restrictScalars A).comap
      ((chapter08TraceDualLattice A B K L).restrictScalars A).subtype

theorem chapter08_trace_dual_quotient_length
    (A B K L : Type*) [CommRing A] [IsDomain A]
    [IsDiscreteValuationRing A] [CommRing B]
    [IsDedekindDomain B] [IsDiscreteValuationRing B] [Field K] [Field L]
    [Algebra A B] [Algebra A K] [Algebra K L] [Algebra B L]
    [Algebra A L] [IsScalarTower A K L] [IsScalarTower A B L]
    [IsFractionRing A K] [IsFractionRing B L] [FiniteDimensional K L]
    [Algebra.IsSeparable K L] [IsIntegralClosure B A L]
    [IsIntegrallyClosed A]
    [Module.Finite A B] [Module.Free A B] [Module.IsTorsionFree A B]
    [Algebra.IsIntegral A B]
    (mA : Ideal A) (mB : Ideal B) (f d : ℕ)
    (hmaxA : mA = IsLocalRing.maximalIdeal A)
    (hmaxB : mB = IsLocalRing.maximalIdeal B)
    (hdifferent : chapter08DifferentIdeal A B = mB ^ d)
    (hresidue : (IsLocalRing.maximalIdeal B).inertiaDeg A = f) :
    Module.length A (chapter08TraceDualQuotient A B K L) =
      (f * d : ℕ∞) := by
  sorry

/- The norm of a maximal-ideal power records the residue-degree factor. -/
theorem chapter08_relative_norm_of_power
    (A B : Type*) [CommRing A] [CommRing B] [Algebra A B]
    [IsDedekindDomain A] [IsDedekindDomain B]
    [Module.Finite A B] [Module.IsTorsionFree A B]
    (mA : Ideal A) (mB : Ideal B) (f d : ℕ)
    (hnorm : Ideal.relNorm A mB = mA ^ f) :
    Ideal.relNorm A (mB ^ d) = mA ^ (f * d) := by
  rw [map_pow, hnorm, ← pow_mul]

theorem chapter08_discriminant_exponent_eq_residue_degree_mul_different
    (A B K L : Type*) [CommRing A] [CommRing B]
    [Field K] [Field L] [Algebra A B] [Algebra A K] [Algebra K L]
    [Algebra B L] [Algebra A L] [IsScalarTower A K L]
    [IsScalarTower A B L] [IsFractionRing A K] [IsFractionRing B L]
    [FiniteDimensional K L] [Algebra.IsSeparable K L]
    [IsIntegralClosure B A L] [Algebra.IsIntegral A B]
    [IsDedekindDomain A] [IsDedekindDomain B]
    [Module.Finite A B] [Module.Free A B] [Module.IsTorsionFree A B]
    (mA : Ideal A) (mB : Ideal B) (f d δ : ℕ)
    (hdisc : chapter08RelativeDiscriminantIdeal A B = mA ^ δ)
    (hdiff : chapter08DifferentIdeal A B = mB ^ d)
    (hnorm : Ideal.relNorm A mB = mA ^ f)
    (hδunique : ∃! n : ℕ,
      chapter08RelativeDiscriminantIdeal A B = mA ^ n) :
    δ = f * d := by
  sorry

theorem chapter08_discriminant_exponent_eq_different_exponent_of_residue_degree_one
    (δ f d : ℕ) (hδ : δ = f * d) (hf : f = 1) :
    δ = d := by
  simpa [hf] using hδ

/- The normalized field norm identity used to pass from the different upstairs
   to the discriminant exponent downstairs. -/
theorem chapter08_norm_valuation_formula
    (K L : Type*) [Field K] [Field L] [Algebra K L]
    [FiniteDimensional K L] {vK : AddValuation K (WithTop ℤ)}
    {vL : AddValuation L (WithTop ℤ)} (e f : ℕ)
    [Valuation.IsRankOneDiscrete vK.toValuation]
    [Valuation.IsRankOneDiscrete vL.toValuation]
    (hext : vK.IsEquiv (AddValuation.comap (algebraMap K L) vL))
    (hrestriction : ∀ y : K,
      vL (algebraMap K L y) = (e : WithTop ℤ) * vK y)
    (hf : f =
      LastLib.Book01ValuationsDVRsAndCompletions.Chapter11.chapter11AdditiveResidueDegree
        vK vL hext)
    (hunique : ∀ w : AddValuation L (WithTop ℤ),
      vK.IsEquiv (AddValuation.comap (algebraMap K L) w) → vL.IsEquiv w)
    (hdegree : Module.finrank K L = e * f) (x : L) (hx : x ≠ 0) :
    vK (Algebra.norm K x) = (f : WithTop ℤ) * vL x := by
  exact LastLib.Book02FiniteExtensionsOfLocalFields.Chapter04.chapter04_norm_valuation_formula
    K L e f hext hrestriction hf hunique hdegree x hx

end

end LastLib.Book03RamificationTheory.Chapter08
