import LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter14.Section01TraceAndRelativePairing
import LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter14.Section02TheBaseChangeTheorem
import LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter14.Section03TheHodgeBundleInSmoothAndNodalFamilies
import LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter14.Section04FailureModes
