import LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter13.Section01ATwoTermModel
import LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter13.Section02SemicontinuityAndBaseChange
import LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter13.Section03RelativeRiemannRoch
import LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter13.Section04UsefulVanishingRanges

namespace LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter13

/-! Aggregator for Book 9, Chapter 13: relative Riemann--Roch and cohomology in families. -/

end LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter13
