import LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter12.Dependencies
import LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter12.Section01TheResiduePairing
import LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter12.Section02Perfectness
import LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter12.Section03DualityForLineBundlesAndVectorBundles
import LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter12.Section04Functoriality
