import LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter08.Dependencies
import LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter08.Section01TheLocalResidue
import LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter08.Section02IndependenceOfParameter
import LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter08.Section03TheGlobalResidueTheorem
import LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter08.Section04FiniteMapsAndTrace

namespace LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter08

end LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter08
