import LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter11.Dependencies
import LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter11.Section01TheTheoremAndItsMeaning
import LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter11.Section02ProofByAddingPoints
import LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter11.Section03ConsequencesAndExamples
import LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter11.Section04GorensteinAndNodalCurves

namespace LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter11

/-! Aggregator for Chapter 11: Riemann--Roch over a field, the adding-points
Euler-characteristic calculation, consequences for sections and embeddings,
and the Gorenstein and nodal extensions, using the canonical earlier-book
curve and pairing interfaces. -/

end LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter11
