import LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter05.Section01DegreeOverAField
import LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter05.Section02EulerCharacteristicAndDegree
import LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter05.Section03DegreeInProperFlatFamilies
import LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter05.Section04HorizontalDivisorsAndFibers
