import LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter01.Section01TheAbsoluteAndRelativeSettings
import LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter01.Section02DimensionOneAsAMeetingPoint
import LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter01.Section03StandingConventionsAndHypotheses

namespace LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter01

end LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter01
