import LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter09.Section01WhyOrdinaryDifferentialsAreNotEnough
import LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter09.Section02DualizingSheavesOnProperCurves
import LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter09.Section03RelativeDualizingSheaf
import LastLib.Book09DivisorsRiemannRochAndDualityOnRelativeCurves.Chapter09.Section04SmoothAndGorensteinFamilies
