import LastLib.Book08AmpleLineBundlesHilbertPolynomialsAndSymmetricPowers.Chapter06.Dependencies

namespace LastLib.Book08AmpleLineBundlesHilbertPolynomialsAndSymmetricPowers.Chapter06

noncomputable section

open CategoryTheory AlgebraicGeometry

universe u v

/-! ### 6.4 Regularity and uniform bounds -/

/-- Unpacking the definition of Castelnuovo--Mumford regularity. -/
theorem chapter06_m_regular_iff
    {R : Type v} [Ring R] {X : Chapter06Scheme}
    (C : Chapter06CohomologyTheory R) (T : Chapter06TwistSystem X)
    (F : X.Modules) (m : ℤ) :
    chapter06MRegular C T F m ↔
      ∀ i : ℕ, 0 < i →
        chapter06CohomologyIsZero C (T.twist F (m - i)) i :=
  Iff.rfl

/-- Regularity is monotone under increasing the regularity index. -/
theorem chapter06_regular_implies_next_regular
    {A : Type u} [CommRing A] {r : ℕ}
    (hA : IsNoetherianRing A)
    (C : Chapter06CohomologyTheory A)
    (P : Chapter06ProjectiveSpaceData A r)
    (H : Chapter06RegularityData C P)
    (F : P.X.Modules) (m : ℤ)
    (hF : Chapter06Coherent F)
    (hreg : chapter06MRegular C P.twisting F m) :
    chapter06MRegular C P.twisting F (m + 1) := by
  exact H.next_regular hA F m hF hreg

/-- A regular coherent sheaf is generated by global sections in its regularity degree. -/
theorem chapter06_regular_implies_global_generation
    {A : Type u} [CommRing A] {r : ℕ}
    (C : Chapter06CohomologyTheory A)
    (P : Chapter06ProjectiveSpaceData A r)
    (H : Chapter06RegularityData C P)
    (F : P.X.Modules) (m : ℤ)
    (hA : IsNoetherianRing A)
    (hF : Chapter06Coherent F)
    (hreg : chapter06MRegular C P.twisting F m) :
    chapter06GloballyGenerated (P.twisting.twist F m) := by
  exact H.global_generation hA F m hF hreg

/- `DEPENDENCY_GUESS`: the preceding chapters should identify this map with the canonical tensor
product of sections induced by the line-bundle twist. -/
structure Chapter06MultiplicationTheory
    {A : Type u} [CommRing A] {r : ℕ}
    (C : Chapter06CohomologyTheory A)
    (P : Chapter06ProjectiveSpaceData A r) where
  map : ∀ (F : P.X.Modules) (n : ℤ),
    TensorProduct A
        (C.H (P.twisting.twist F n) 0)
        (C.H (P.twisting.twist P.twisting.structureSheaf 1) 0) →ₗ[A]
      C.H (P.twisting.twist F (n + 1)) 0
  /-- The canonical section multiplication has the regularity-surjectivity property used below.
  This is the missing cohomological multiplication API, recorded as a law of the theory rather
  than attached to an arbitrary family of linear maps. -/
  regular_surjective : ∀ (F : P.X.Modules) (m n : ℤ),
    IsNoetherianRing A → Chapter06Coherent F →
      chapter06MRegular C P.twisting F m → m ≤ n →
        Function.Surjective (map F n)

/-- Regularity makes multiplication by degree-one sections surjective in every higher degree. -/
theorem chapter06_regular_multiplication_surjective
    {A : Type u} [CommRing A] {r : ℕ}
    (C : Chapter06CohomologyTheory A)
    (P : Chapter06ProjectiveSpaceData A r)
    (M : Chapter06MultiplicationTheory C P)
    (F : P.X.Modules) (m n : ℤ)
    (hA : IsNoetherianRing A)
    (hF : Chapter06Coherent F)
    (hreg : chapter06MRegular C P.twisting F m)
    (hn : m ≤ n) :
    Function.Surjective (M.map F n) := by
  exact M.regular_surjective F m n hA hF hreg hn

/-- The predicate behind the multiplication conclusion, kept separate for use by later chapters.
-/
def chapter06_regular_multiplication_statement
    {A : Type u} [CommRing A] {r : ℕ}
    (C : Chapter06CohomologyTheory A)
    (P : Chapter06ProjectiveSpaceData A r)
    (M : Chapter06MultiplicationTheory C P)
    (F : P.X.Modules) (m : ℤ) : Prop :=
  ∀ n : ℤ, m ≤ n → Function.Surjective (M.map F n)

/-- The high-degree behavior controlled by one regularity index. -/
theorem chapter06_regularity_packages_high_degree_behavior
    {A : Type u} [CommRing A] {r : ℕ}
    (C : Chapter06CohomologyTheory A)
    (P : Chapter06ProjectiveSpaceData A r)
    (H : Chapter06RegularityData C P)
    (M : Chapter06MultiplicationTheory C P)
    (F : P.X.Modules) (m : ℤ)
    (hA : IsNoetherianRing A)
    (hF : Chapter06Coherent F)
    (hreg : chapter06MRegular C P.twisting F m) :
    chapter06GloballyGenerated (P.twisting.twist F m) ∧
    chapter06_regular_multiplication_statement C P M F m := by
  constructor
  · exact H.global_generation hA F m hF hreg
  · intro n hn
    exact M.regular_surjective F m n hA hF hreg hn

/-- A uniform regularity bound for ideal sheaves with a fixed eventual Euler polynomial. -/
theorem chapter06_uniform_regular_bound_fixed_hilbert_polynomial
    {A : Type u} [CommRing A] {r : ℕ}
    (hA : IsNoetherianRing A)
    (C : Chapter06CohomologyTheory A)
    (P : Chapter06ProjectiveSpaceData A r)
    (H : Chapter06RegularityData C P)
    (Q : Polynomial ℚ) :
    ∃ m₀ : ℤ, ∀ F : P.X.Modules,
      Chapter06Coherent F →
      chapter06IdealSheaf F →
      chapter06HasHilbertPolynomial C P.twisting F Q →
      chapter06MRegular C P.twisting F m₀ := by
  exact H.uniform_bound hA Q

end

end LastLib.Book08AmpleLineBundlesHilbertPolynomialsAndSymmetricPowers.Chapter06
