import LastLib.Book08AmpleLineBundlesHilbertPolynomialsAndSymmetricPowers.Chapter06.Dependencies

namespace LastLib.Book08AmpleLineBundlesHilbertPolynomialsAndSymmetricPowers.Chapter06

noncomputable section

open CategoryTheory AlgebraicGeometry

universe u v

/-! ### 6.4 Regularity and uniform bounds -/

/-- Unpacking the definition of Castelnuovo--Mumford regularity. -/
theorem chapter06_m_regular_iff
    {R : Type v} [CommRing R] {X : Chapter06Scheme}
    (C : Chapter06CohomologyTheory R) (T : Chapter06TwistSystem X)
    (F : X.Modules) (m : ℤ) :
    chapter06MRegular C T F m ↔
      ∀ i : ℕ, 0 < i →
        chapter06CohomologyIsZero C (T.twist F (m - i)) i :=
  Iff.rfl

/- The map is constrained below to be the canonical tensor product of sections supplied by the
cohomology realization. -/
structure Chapter06MultiplicationTheory
    {A : Type u} [CommRing A] {r : ℕ}
    (C : Chapter06CohomologyTheory A)
    (P : Chapter06ProjectiveSpaceData A r)
    (hC : Chapter06CanonicalCohomologyRealization C) where
  map : ∀ (F : P.X.Modules) (n : ℤ),
      TensorProduct A
        (C.H (P.twisting.twist F n) 0)
        (C.H (P.twisting.twist P.twisting.structureSheaf 1) 0) →ₗ[A]
      C.H (P.twisting.twist F (n + 1)) 0
  /-- The displayed map is the canonical multiplication of sections, not an arbitrary linear map. -/
  map_is_canonical :
    ∀ (F : P.X.Modules) (n : ℤ),
      map F n = hC.sectionMultiplication P.twisting F n

/-- The missing hyperplane/regularity bridge.  Its fields are the reusable outputs of the
hyperplane exact-sequence argument, global-generation argument, multiplication argument, and
Gotzmann boundedness argument; the section theorems below only package those outputs. -/
structure Chapter06RegularityInterface
    {A : Type u} [CommRing A] {r : ℕ}
    (hA : IsNoetherianRing A)
    (C : Chapter06CohomologyTheory A)
    (P : Chapter06ProjectiveSpaceData A r)
    (hC : Chapter06ProjectiveSpaceCechRealization C P) where
  regular_implies_next :
    ∀ (F : P.X.Modules) (m : ℤ), Chapter06Coherent F →
      chapter06MRegular C P.twisting F m →
        chapter06MRegular C P.twisting F (m + 1)
  regular_implies_global_generation :
    ∀ (F : P.X.Modules) (m : ℤ), Chapter06Coherent F →
      chapter06MRegular C P.twisting F m →
        chapter06GloballyGenerated (P.twisting.twist F m)
  multiplication_surjective :
    ∀ (M : Chapter06MultiplicationTheory C P hC.canonical)
      (F : P.X.Modules) (m n : ℤ) (_hF : Chapter06Coherent F)
      (_hreg : chapter06MRegular C P.twisting F m) (_hn : m ≤ n),
      Function.Surjective (M.map F n)
  uniform_regular_bound_fixed_hilbert_polynomial :
    ∀ (Q : Polynomial ℚ), ∃ m₀ : ℤ, ∀ F : P.X.Modules,
      Chapter06Coherent F →
      chapter06IdealSheaf F →
      chapter06HasHilbertPolynomial C P.twisting F Q →
      chapter06MRegular C P.twisting F m₀

/-- Regularity is monotone under increasing the regularity index. -/
theorem chapter06_regular_implies_next_regular
    {A : Type u} [CommRing A] {r : ℕ}
    (hA : IsNoetherianRing A)
    (C : Chapter06CohomologyTheory A)
    (P : Chapter06ProjectiveSpaceData A r)
    (F : P.X.Modules) (m : ℤ)
    (hC : Chapter06ProjectiveSpaceCechRealization C P)
    (hF : Chapter06Coherent F)
    (hreg : chapter06MRegular C P.twisting F m)
    (hR : Chapter06RegularityInterface hA C P hC) :
    chapter06MRegular C P.twisting F (m + 1) := by
  exact hR.regular_implies_next F m hF hreg

/-- A regular coherent sheaf is generated by global sections in its regularity degree. -/
theorem chapter06_regular_implies_global_generation
    {A : Type u} [CommRing A] {r : ℕ}
    (C : Chapter06CohomologyTheory A)
    (P : Chapter06ProjectiveSpaceData A r)
    (F : P.X.Modules) (m : ℤ)
    (hA : IsNoetherianRing A)
    (hC : Chapter06ProjectiveSpaceCechRealization C P)
    (hF : Chapter06Coherent F)
    (hreg : chapter06MRegular C P.twisting F m)
    (hR : Chapter06RegularityInterface hA C P hC) :
    chapter06GloballyGenerated (P.twisting.twist F m) := by
  exact hR.regular_implies_global_generation F m hF hreg

/-- Regularity makes multiplication by degree-one sections surjective in every higher degree. -/
theorem chapter06_regular_multiplication_surjective
    {A : Type u} [CommRing A] {r : ℕ}
    (C : Chapter06CohomologyTheory A)
    (P : Chapter06ProjectiveSpaceData A r)
    (hC : Chapter06ProjectiveSpaceCechRealization C P)
    (M : Chapter06MultiplicationTheory C P hC.canonical)
    (F : P.X.Modules) (m n : ℤ)
    (hA : IsNoetherianRing A)
    (hF : Chapter06Coherent F)
    (hreg : chapter06MRegular C P.twisting F m)
    (hn : m ≤ n)
    (hR : Chapter06RegularityInterface hA C P hC) :
    Function.Surjective (M.map F n) := by
  exact hR.multiplication_surjective M F m n hF hreg hn

/-- The predicate behind the multiplication conclusion, kept separate for use by later chapters.
-/
def chapter06_regular_multiplication_statement
    {A : Type u} [CommRing A] {r : ℕ}
    (C : Chapter06CohomologyTheory A)
    (P : Chapter06ProjectiveSpaceData A r)
    (hC : Chapter06CanonicalCohomologyRealization C)
    (M : Chapter06MultiplicationTheory C P hC)
    (F : P.X.Modules) (m : ℤ) : Prop :=
  ∀ n : ℤ, m ≤ n → Function.Surjective (M.map F n)

/-- The high-degree behavior controlled by one regularity index. -/
theorem chapter06_regularity_packages_high_degree_behavior
    {A : Type u} [CommRing A] {r : ℕ}
    (C : Chapter06CohomologyTheory A)
    (P : Chapter06ProjectiveSpaceData A r)
    (hC : Chapter06ProjectiveSpaceCechRealization C P)
    (M : Chapter06MultiplicationTheory C P hC.canonical)
    (F : P.X.Modules) (m : ℤ)
    (hA : IsNoetherianRing A)
    (hF : Chapter06Coherent F)
    (hreg : chapter06MRegular C P.twisting F m)
    (hR : Chapter06RegularityInterface hA C P hC) :
    chapter06GloballyGenerated (P.twisting.twist F m) ∧
    chapter06_regular_multiplication_statement C P hC.canonical M F m := by
  refine ⟨hR.regular_implies_global_generation F m hF hreg, ?_⟩
  intro n hn
  exact hR.multiplication_surjective M F m n hF hreg hn

/-- A uniform regularity bound for ideal sheaves with a fixed eventual Euler polynomial. -/
theorem chapter06_uniform_regular_bound_fixed_hilbert_polynomial
    {A : Type u} [CommRing A] {r : ℕ}
    (hA : IsNoetherianRing A)
    (C : Chapter06CohomologyTheory A)
    (P : Chapter06ProjectiveSpaceData A r)
    (hC : Chapter06ProjectiveSpaceCechRealization C P)
    (Q : Polynomial ℚ)
    (hR : Chapter06RegularityInterface hA C P hC) :
    ∃ m₀ : ℤ, ∀ F : P.X.Modules,
      Chapter06Coherent F →
      chapter06IdealSheaf F →
      chapter06HasHilbertPolynomial C P.twisting F Q →
      chapter06MRegular C P.twisting F m₀ := by
  exact hR.uniform_regular_bound_fixed_hilbert_polynomial Q

end

end LastLib.Book08AmpleLineBundlesHilbertPolynomialsAndSymmetricPowers.Chapter06
