import LastLib.Book12BlowupsAndIntersectionTheoryOnArithmeticSurfaces.Chapter09.Dependencies

namespace LastLib.Book12BlowupsAndIntersectionTheoryOnArithmeticSurfaces.Chapter09

noncomputable section

open AlgebraicGeometry CategoryTheory CategoryTheory.Limits
open Order TopologicalSpace
open scoped AlgebraicGeometry BigOperators

universe u v

/-! ## 9.2. Intersection with principal divisors -/

/-- Rational equivalence is generated by nonzero principal divisors. -/
theorem chapter09_principal_divisor_is_rationallyEquivalent_to_zero
    (X : Chapter09RegularNoetherianIntegralSurface)
    [P : Chapter09PrincipalDivisorTheory X]
    (f : Chapter09NonzeroRationalFunction X) :
    chapter09RationallyEquivalent (P.principal f) 0 := by
  sorry

@[simp]
theorem chapter09_principal_divisor_one
    (X : Chapter09RegularNoetherianIntegralSurface)
    [P : Chapter09PrincipalDivisorTheory X] :
    P.principal ⟨1, one_ne_zero⟩ = 0 := by
  exact P.principal_one

theorem chapter09_principal_divisor_mul
    (X : Chapter09RegularNoetherianIntegralSurface)
    [P : Chapter09PrincipalDivisorTheory X]
    (f g : Chapter09NonzeroRationalFunction X) :
    P.principal ⟨f.1 * g.1, mul_ne_zero f.2 g.2⟩ =
      P.principal f + P.principal g := by
  exact P.principal_mul f g

theorem chapter09_principal_divisor_coeff_eq_order
    (X : Chapter09RegularNoetherianIntegralSurface)
    [P : Chapter09PrincipalDivisorTheory X]
    (f : Chapter09NonzeroRationalFunction X) (C : Chapter09PrimeCurve X) :
    P.principal f C = C.order f.1 := by
  exact P.principal_coeff_order f C

theorem chapter09_principal_divisor_mem_principalSubgroup
    (X : Chapter09RegularNoetherianIntegralSurface)
    [P : Chapter09PrincipalDivisorTheory X]
    (f : Chapter09NonzeroRationalFunction X) :
    P.principal f ∈ chapter09PrincipalSubgroup X := by
  sorry

theorem chapter09_rationallyEquivalent_refl
    (X : Chapter09RegularNoetherianIntegralSurface)
    [P : Chapter09PrincipalDivisorTheory X]
    (D : Chapter09WeilDivisor X) :
    chapter09RationallyEquivalent D D := by
  sorry

theorem chapter09_rationallyEquivalent_symm
    (X : Chapter09RegularNoetherianIntegralSurface)
    [P : Chapter09PrincipalDivisorTheory X]
    {D E : Chapter09WeilDivisor X}
    (h : chapter09RationallyEquivalent D E) :
    chapter09RationallyEquivalent E D := by
  sorry

theorem chapter09_rationallyEquivalent_trans
    (X : Chapter09RegularNoetherianIntegralSurface)
    [P : Chapter09PrincipalDivisorTheory X]
    {D E F : Chapter09WeilDivisor X}
    (hDE : chapter09RationallyEquivalent D E)
    (hEF : chapter09RationallyEquivalent E F) :
    chapter09RationallyEquivalent D F := by
  sorry

theorem chapter09_rationallyEquivalent_add_right
    (X : Chapter09RegularNoetherianIntegralSurface)
    [P : Chapter09PrincipalDivisorTheory X]
    {D E F : Chapter09WeilDivisor X}
    (h : chapter09RationallyEquivalent D E) :
    chapter09RationallyEquivalent (D + F) (E + F) := by
  sorry

theorem chapter09_rationallyEquivalent_add_left
    (X : Chapter09RegularNoetherianIntegralSurface)
    [P : Chapter09PrincipalDivisorTheory X]
    {D E F : Chapter09WeilDivisor X}
    (h : chapter09RationallyEquivalent D E) :
    chapter09RationallyEquivalent (F + D) (F + E) := by
  sorry

/-- The generated relation agrees with equality in the rational-equivalence
quotient. -/
theorem chapter09_rationallyEquivalent_iff_quotient_eq
    (X : Chapter09RegularNoetherianIntegralSurface)
    [P : Chapter09PrincipalDivisorTheory X]
    (D E : Chapter09WeilDivisor X) :
    chapter09RationallyEquivalent D E ↔
      Quotient.mk (chapter09RationalEquivalenceSetoid X) D =
        Quotient.mk (chapter09RationalEquivalenceSetoid X) E := by
  sorry

/-! ### Principal divisors on proper curves -/

/-- A principal divisor on a proper curve over a field has degree zero. -/
theorem chapter09_principal_divisor_degree_zero
    {k : Type u} [Field k] (C : Chapter09ProperCurveOverField k)
    [T : Chapter09ProperCurveDivisorTheory C] :
    chapter09PrincipalDivisorDegreeZero C := by
  intro f
  exact T.principal_degree_zero f

theorem chapter09_principal_divisor_degree_zero_explicit
    {k : Type u} [Field k] (C : Chapter09ProperCurveOverField k)
    [T : Chapter09ProperCurveDivisorTheory C]
    (f : { g : chapter09CurveRationalFunction C // g ≠ 0 }) :
    T.degree (T.principal f) = 0 := by
  exact T.principal_degree_zero f

/-! ### Fiberwise intersections -/

/-- Intersecting a divisor with a vertical curve is the degree of the
restricted line bundle. -/
theorem chapter09_vertical_intersection_eq_restriction_degree
    (X : Chapter09RegularNoetherianIntegralSurface)
    (P : Chapter09PrincipalDivisorTheory X)
    [I : Chapter09VerticalIntersectionTheory X P]
    (D : Chapter09WeilDivisor X) (C : Chapter09VerticalCurve X) :
    chapter09VerticalIntersection (X := X) (P := P) D C =
      I.degree C (I.restrictionLineBundle D C) := by
  exact I.intersection_eq_degree D C

theorem chapter09_vertical_intersection_additive
    (X : Chapter09RegularNoetherianIntegralSurface)
    (P : Chapter09PrincipalDivisorTheory X)
    [I : Chapter09VerticalIntersectionTheory X P]
    (D E : Chapter09WeilDivisor X) (C : Chapter09VerticalCurve X) :
    chapter09VerticalIntersection (X := X) (P := P) (D + E) C =
      chapter09VerticalIntersection (X := X) (P := P) D C +
        chapter09VerticalIntersection (X := X) (P := P) E C := by
  exact I.intersection_add D E C

@[simp]
theorem chapter09_vertical_intersection_zero
    (X : Chapter09RegularNoetherianIntegralSurface)
    (P : Chapter09PrincipalDivisorTheory X)
    [I : Chapter09VerticalIntersectionTheory X P]
    (C : Chapter09VerticalCurve X) :
    chapter09VerticalIntersection (X := X) (P := P) 0 C = 0 := by
  exact I.intersection_zero C

/-- Adding a principal divisor does not change the intersection with a proper
vertical curve. -/
theorem chapter09_intersection_with_principal_divisor_invariant
    (X : Chapter09RegularNoetherianIntegralSurface)
    (P : Chapter09PrincipalDivisorTheory X)
    [I : Chapter09VerticalIntersectionTheory X P]
    (D : Chapter09WeilDivisor X)
    (f : Chapter09NonzeroRationalFunction X)
    (C : Chapter09VerticalCurve X) :
    chapter09VerticalIntersection (X := X) (P := P) (D + P.principal f) C =
    chapter09VerticalIntersection (X := X) (P := P) D C := by
  exact I.principal_invariance D f C

theorem chapter09_vertical_intersection_respects_rational_equivalence
    (X : Chapter09RegularNoetherianIntegralSurface)
    (P : Chapter09PrincipalDivisorTheory X)
    [I : Chapter09VerticalIntersectionTheory X P]
    {D E : Chapter09WeilDivisor X}
    (h : chapter09RationallyEquivalent D E)
    (C : Chapter09VerticalCurve X) :
    chapter09VerticalIntersection (X := X) (P := P) D C =
      chapter09VerticalIntersection (X := X) (P := P) E C := by
  sorry

/-! ### Bilinear vertical--vertical intersections -/

def chapter09VerticalDivisorIntersection
    {X : Chapter09RegularNoetherianIntegralSurface}
    {P : Chapter09PrincipalDivisorTheory X}
    [V : Chapter09VerticalDivisorPairingTheory X P]
    (D E : Chapter09WeilDivisor X) : ℤ :=
  V.pairing D E

theorem chapter09_vertical_divisor_intersection_add_left
    (X : Chapter09RegularNoetherianIntegralSurface)
    (P : Chapter09PrincipalDivisorTheory X)
    [V : Chapter09VerticalDivisorPairingTheory X P]
    (D E F : Chapter09WeilDivisor X) :
    chapter09VerticalDivisorIntersection (X := X) (P := P) (D + E) F =
      chapter09VerticalDivisorIntersection (X := X) (P := P) D F +
        chapter09VerticalDivisorIntersection (X := X) (P := P) E F := by
  exact V.pairing_add_left D E F

theorem chapter09_vertical_divisor_intersection_add_right
    (X : Chapter09RegularNoetherianIntegralSurface)
    (P : Chapter09PrincipalDivisorTheory X)
    [V : Chapter09VerticalDivisorPairingTheory X P]
    (D E F : Chapter09WeilDivisor X) :
    chapter09VerticalDivisorIntersection (X := X) (P := P) D (E + F) =
      chapter09VerticalDivisorIntersection (X := X) (P := P) D E +
        chapter09VerticalDivisorIntersection (X := X) (P := P) D F := by
  exact V.pairing_add_right D E F

@[simp]
theorem chapter09_vertical_divisor_intersection_zero_left
    (X : Chapter09RegularNoetherianIntegralSurface)
    (P : Chapter09PrincipalDivisorTheory X)
    [V : Chapter09VerticalDivisorPairingTheory X P]
    (D : Chapter09WeilDivisor X) :
    chapter09VerticalDivisorIntersection (X := X) (P := P) 0 D = 0 := by
  exact V.pairing_zero_left D

@[simp]
theorem chapter09_vertical_divisor_intersection_zero_right
    (X : Chapter09RegularNoetherianIntegralSurface)
    (P : Chapter09PrincipalDivisorTheory X)
    [V : Chapter09VerticalDivisorPairingTheory X P]
    (D : Chapter09WeilDivisor X) :
    chapter09VerticalDivisorIntersection (X := X) (P := P) D 0 = 0 := by
  exact V.pairing_zero_right D

theorem chapter09_vertical_divisor_intersection_symmetric
    (X : Chapter09RegularNoetherianIntegralSurface)
    (P : Chapter09PrincipalDivisorTheory X)
    [V : Chapter09VerticalDivisorPairingTheory X P]
    (D E : Chapter09WeilDivisor X)
    (hD : chapter09IsVerticalDivisor D)
    (hE : chapter09IsVerticalDivisor E) :
    chapter09VerticalDivisorIntersection (X := X) (P := P) D E =
      chapter09VerticalDivisorIntersection (X := X) (P := P) E D := by
  exact V.pairing_symmetric_on_vertical D E hD hE

/-! ### The boundary warning -/

/-- Global principal intersections are retained as zero-cycles before taking
any boundary quotient. -/
theorem chapter09_principal_intersection_zeroCycle_is_boundaryAware
    (X : Chapter09RegularNoetherianIntegralSurface)
    (P : Chapter09PrincipalDivisorTheory X)
    [T : Chapter09PrincipalIntersectionCycleTheory X P] :
    T.principalIntersectionRationallyTrivial ∧
      T.boundaryContributionsRetained ∧ T.horizontalBoundaryMayBeNonzero := by
  exact ⟨T.principalIntersectionRationallyTrivial,
    T.boundaryContributionsRetained, T.horizontalBoundaryMayBeNonzero⟩

/-- A cycle supported over a base point can carry a nonzero residue-weighted
degree.  This is the precise boundary datum that must be retained for a
horizontal principal intersection. -/
def chapter09HorizontalPrincipalBoundaryWarning
    {X S : Scheme.{u}} (f : X ⟶ S) (s : S) (z : Chapter09ZeroCycle X) : Prop :=
  chapter09ZeroCycleSupportedOver f s z ∧ chapter09ZeroCycleDegree f z ≠ 0

theorem chapter09_horizontal_principal_boundary_warning_is_explicit
    {X S : Scheme.{u}} (f : X ⟶ S) (s : S) (z : Chapter09ZeroCycle X)
    (h : chapter09HorizontalPrincipalBoundaryWarning f s z) :
    chapter09ZeroCycleDegree f z ≠ 0 := by
  exact h.2

/- A base-uniformizer boundary is the positive-degree special case of the
generic warning above.  The local-Dedekind uniformizer and its closed-fiber
cycle are supplied by the arithmetic model using this interface. -/
def chapter09PositiveHorizontalBoundaryWarning
    {X S : Scheme.{u}} (f : X ⟶ S) (s : S) (z : Chapter09ZeroCycle X) : Prop :=
  chapter09ZeroCycleSupportedOver f s z ∧ 0 < chapter09ZeroCycleDegree f z

theorem chapter09_positive_horizontal_boundary_has_nonzero_degree
    {X S : Scheme.{u}} (f : X ⟶ S) (s : S) (z : Chapter09ZeroCycle X)
    (h : chapter09PositiveHorizontalBoundaryWarning f s z) :
    chapter09ZeroCycleDegree f z ≠ 0 := by
  exact ne_of_gt h.2

theorem chapter09_principal_intersection_boundary_terms_are_retained
    (X : Chapter09RegularNoetherianIntegralSurface)
    (P : Chapter09PrincipalDivisorTheory X)
    [T : Chapter09PrincipalIntersectionCycleTheory X P] :
    T.boundaryContributionsRetained := by
  exact T.boundaryContributionsRetained

end

end LastLib.Book12BlowupsAndIntersectionTheoryOnArithmeticSurfaces.Chapter09
