import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter07.Section07RootsOfUnity

namespace LastLib.Book02FiniteExtensionsOfLocalFields.Chapter07

open Set
open Polynomial
open scoped BigOperators TensorProduct

noncomputable section

/-! # Book 2, Chapter 7, §7.8: unramified extensions and finite precision -/

/-- The base and extended precision ideals generated by a uniformizer power. -/
abbrev Chapter07BasePrecisionIdeal
    (A : Type*) [CommRing A] (π : A) (n : ℕ) : Ideal A :=
  LastLib.Book01ValuationsDVRsAndCompletions.Chapter12.principalPowerIdeal π n

abbrev Chapter07ExtensionPrecisionIdeal
    (A B : Type*) [CommRing A] [CommRing B] [Algebra A B]
    (π : A) (n : ℕ) : Ideal B :=
  LastLib.Book01ValuationsDVRsAndCompletions.Chapter12.extendedPrincipalPowerIdeal A B π n

/-- The finite precision quotient rings appearing in §7.8. -/
abbrev Chapter07BasePrecisionQuotient
    (A : Type*) [CommRing A] (π : A) (n : ℕ) : Type _ :=
  A ⧸ Chapter07BasePrecisionIdeal A π n

abbrev Chapter07ExtensionPrecisionQuotient
    (A B : Type*) [CommRing A] [CommRing B] [Algebra A B]
    (π : A) (n : ℕ) : Type _ :=
  B ⧸ Chapter07ExtensionPrecisionIdeal A B π n

/-- A finite precision quotient is free of rank `f` over the corresponding
base quotient. -/
def Chapter07FinitePrecisionFreeOfRank
    (A B : Type*) [CommRing A] [CommRing B] [Algebra A B]
    (π : A) (f n : ℕ)
    [Algebra (Chapter07BasePrecisionQuotient A π n)
      (Chapter07ExtensionPrecisionQuotient A B π n)] : Prop :=
  Module.Finite (Chapter07BasePrecisionQuotient A π n)
      (Chapter07ExtensionPrecisionQuotient A B π n) ∧
    Module.finrank (Chapter07BasePrecisionQuotient A π n)
      (Chapter07ExtensionPrecisionQuotient A B π n) = f

/-- Unramified finite freeness at every precision.  The source's “determined
by the residue extension” phrase is represented by a compatible family of
these quotient bases. -/
structure Chapter07FinitePrecisionTower
    (A B : Type*) [CommRing A] [CommRing B] [Algebra A B]
    (π : A) (f : ℕ) (k l : Type*) [Field k] [Field l]
    [Algebra k l] [FiniteDimensional k l] where
  quotient : ∀ n : ℕ, Type*
  [quotientRing : ∀ n, CommRing (quotient n)]
  [quotientAlgebra : ∀ n,
    Algebra (Chapter07BasePrecisionQuotient A π n) (quotient n)]
  finiteFree : ∀ n,
    Module.Finite (Chapter07BasePrecisionQuotient A π n) (quotient n)
  rank : ∀ n, Module.finrank (Chapter07BasePrecisionQuotient A π n) (quotient n) = f
  residueDegree : Module.finrank k l = f
  residueSeparable : Chapter07ResidueExtensionIsSeparable k l

/-- For an unramified finite extension, all quotients `B/π^nB` are finite free
of rank equal to the residue degree. -/
theorem chapter07_unramified_quotients_are_free
    {A B : Type*} [CommRing A] [IsDomain A] [CommRing B]
    [IsDomain B] [Algebra A B] [Module.Finite A B] [Module.Free A B]
    [IsDiscreteValuationRing A] [IsDiscreteValuationRing B]
    (π : A) (f : ℕ)
    (hπ : IsLocalRing.maximalIdeal A = Ideal.span ({π} : Set A))
    (hdegree : Module.finrank A B = f) :
    ∀ n : ℕ, ∃ hA : Algebra (Chapter07BasePrecisionQuotient A π n)
        (Chapter07ExtensionPrecisionQuotient A B π n),
      Chapter07FinitePrecisionFreeOfRank A B π f n := by
  sorry

/-- A finite precision system is determined by its degree-`one` residue
quotient once the transition maps are fixed. -/
theorem chapter07_finite_precision_determined_by_residue
    {A B k l : Type*} [CommRing A] [CommRing B] [Algebra A B]
    [Field k] [Field l] [Algebra k l] [FiniteDimensional k l]
    (π : A) (f : ℕ)
    (T₁ T₂ : Chapter07FinitePrecisionTower A B π f k l)
    (hresidue : Chapter07ResidueExtensionIsSeparable k l) :
    ∀ n : ℕ,
      letI : CommRing (T₁.quotient n) := T₁.quotientRing n
      letI : Algebra (Chapter07BasePrecisionQuotient A π n) (T₁.quotient n) :=
        T₁.quotientAlgebra n
      letI : CommRing (T₂.quotient n) := T₂.quotientRing n
      letI : Algebra (Chapter07BasePrecisionQuotient A π n) (T₂.quotient n) :=
        T₂.quotientAlgebra n
      Nonempty
        (T₁.quotient n ≃ₐ[Chapter07BasePrecisionQuotient A π n] T₂.quotient n) := by
  sorry

/-- A compatible family of roots modulo all powers of an ideal.  Transition
maps are explicit because the quotient-map API depends on the chosen ideal
containments. -/
structure Chapter07CompatibleRootApproximation
    (R : Type*) [CommRing R] (I : Ideal R) (p : R[X]) where
  root : ∀ n : ℕ, R ⧸ I ^ n
  transition : ∀ n : ℕ, (R ⧸ I ^ (n + 1)) →+* (R ⧸ I ^ n)
  root_equation : ∀ n : ℕ,
    eval₂ (Ideal.Quotient.mk (I ^ n)) (root n) p = 0
  compatible : ∀ n : ℕ, transition n (root (n + 1)) = root n

/-- Hensel lifting supplies compatible roots at every finite precision. -/
theorem chapter07_hensel_constructs_compatible_precision_roots
    {R : Type*} [CommRing R] [HenselianLocalRing R]
    (I : Ideal R) (p : R[X]) (hI : I = IsLocalRing.maximalIdeal R)
    (hseparable : p.Separable) (hmonic : p.Monic) :
    Nonempty (Chapter07CompatibleRootApproximation R I p) := by
  sorry

/-- A compatible finite-precision root family has an inverse-limit lift in the
adic completion, with its prescribed finite projections. -/
theorem chapter07_compatible_roots_have_adic_limit
    {R : Type*} [CommRing R] (I : Ideal R) (p : R[X])
    (S : Chapter07CompatibleRootApproximation R I p)
    (projection : ∀ n : ℕ,
      AdicCompletion I R →+* (R ⧸ I ^ n))
    (hprojection : ∀ n, projection n = (S.transition n).comp (projection (n + 1))) :
    ∃ x : AdicCompletion I R, ∀ n, projection n x = S.root n := by
  sorry

/-- In equal characteristic, a chosen coefficient field identifies the
unramified ring with a literal power-series ring. -/
def Chapter07CoefficientwisePowerSeriesExpansion
    (B k' : Type*) [CommRing B] [Field k'] : Prop :=
  Nonempty (B ≃+* PowerSeries k')

theorem chapter07_equal_characteristic_power_series_model
    (k' : Type*) [Field k'] :
    Chapter07CoefficientwisePowerSeriesExpansion (PowerSeries k') k' := by
  exact ⟨RingEquiv.refl _⟩

/-- In mixed characteristic there is no coefficient-field embedding of a
positive-characteristic residue field into a characteristic-zero ring. -/
theorem chapter07_mixed_characteristic_has_no_coefficient_field
    {B k : Type*} [CommRing B] [Field k] [CharZero B]
    {p : ℕ} [CharP k p] [Fact p.Prime] :
    ¬Nonempty (k →+* B) := by
  sorry

/-- The warning that finite-precision data need not have a coefficientwise
power-series expansion is a property of a chosen mixed-characteristic model,
not an unconditional theorem about every ring. -/
def Chapter07FinitePrecisionHasNoCoefficientwiseExpansion
    {B k' : Type*} [CommRing B] [Field k']
    : Prop :=
  ¬Chapter07CoefficientwisePowerSeriesExpansion B k'

end
end LastLib.Book02FiniteExtensionsOfLocalFields.Chapter07
