import Mathlib.RingTheory.AdjoinRoot
import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter07.Section02EquivalentCharacterizations

namespace LastLib.Book02FiniteExtensionsOfLocalFields.Chapter07

open Set
open Polynomial

noncomputable section

universe uG

/-! # Book 2, Chapter 7, §7.3: constructing the unramified lift -/

/-- A monic polynomial over `A` lifting a prescribed residue polynomial. -/
def Chapter07MonicPolynomialLift
    {A k : Type*} [CommRing A] [Field k]
    (res : A →+* k) (gbar : k[X]) (g : A[X]) : Prop :=
  g.Monic ∧ g.map res = gbar

/-- The polynomial over the fraction field used in the quotient construction. -/
def chapter07LiftedPolynomial
    {A K : Type*} [CommRing A] [Field K] [Algebra A K]
    (g : A[X]) : K[X] :=
  g.map (algebraMap A K)

/-- The quotient algebra `K[T]/(g)` in the construction of §7.3. -/
abbrev Chapter07LiftedPolynomialQuotient
    (K : Type*) [Field K] (g : K[X]) : Type _ :=
  AdjoinRoot g

/-- The class of `T` in the lifted polynomial quotient. -/
def chapter07LiftedRoot
    {A K : Type*} [CommRing A] [Field K] [Algebra A K]
    (g : A[X]) : Chapter07LiftedPolynomialQuotient K (chapter07LiftedPolynomial g) :=
  AdjoinRoot.root (chapter07LiftedPolynomial g)

/-- A root of a monic polynomial over the base ring is integral. -/
theorem chapter07_lifted_root_is_integral
    {A K Q : Type*} [CommRing A] [Field K] [CommRing Q]
    [Algebra A K] [Algebra K Q] [Algebra A Q]
    [IsScalarTower A K Q]
    (g : A[X]) (hg : g.Monic) (θ : Q)
    (hroot : eval₂ (algebraMap A Q) θ g = 0) :
    IsIntegral A θ := by
  sorry

/-- The quotient is a field when the lifted polynomial is irreducible. -/
theorem chapter07_lifted_polynomial_quotient_is_field
    {K : Type*} [Field K] (g : K[X]) (hg : Irreducible g) :
    IsField (Chapter07LiftedPolynomialQuotient K g) := by
  sorry

/-- A monic quotient has the expected vector-space degree. -/
theorem chapter07_lifted_polynomial_quotient_degree
    {K : Type*} [Field K] (g : K[X]) (hg : g.Monic) :
    Module.finrank K (Chapter07LiftedPolynomialQuotient K g) = g.natDegree := by
  sorry

/-- Residue irreducibility forces irreducibility of a monic lift over a DVR
fraction field. -/
theorem chapter07_monic_lift_irreducible
    {A K k : Type*} [CommRing A] [IsDomain A] [Field K] [Field k]
    [Algebra A K] [IsFractionRing A K] [HenselianLocalRing A]
    [IsDiscreteValuationRing A]
    (res : A →+* k) (gbar : k[X]) (g : A[X])
    (hbar : gbar.Monic ∧ Irreducible gbar)
    (hlift : Chapter07MonicPolynomialLift res gbar g)
    (hres_surjective : Function.Surjective res)
    (hres_kernel : RingHom.ker res = IsLocalRing.maximalIdeal A) :
    Irreducible (chapter07LiftedPolynomial (K := K) g) := by
  sorry

/-- The finite quotient construction has the residue degree prescribed by the
chosen finite separable residue extension. -/
theorem chapter07_construct_unramified_lift
    {A K k k' : Type*} [CommRing A] [IsDomain A]
    [Field K] [Field k] [Field k']
    [Algebra A K] [IsFractionRing A K] [Algebra k k']
    [FiniteDimensional k k'] [Algebra.IsSeparable k k']
    [HenselianLocalRing A]
    [IsDiscreteValuationRing A]
    (res : A →+* k) (gbar : k[X]) (g : A[X])
    [Algebra A
      (Chapter07LiftedPolynomialQuotient K (chapter07LiftedPolynomial g))]
    [IsScalarTower A K
      (Chapter07LiftedPolynomialQuotient K (chapter07LiftedPolynomial g))]
    (hbar : gbar.Monic ∧ Irreducible gbar ∧ gbar.Separable)
    (hlift : Chapter07MonicPolynomialLift res gbar g)
    (hres_surjective : Function.Surjective res)
    (hres_kernel : RingHom.ker res = IsLocalRing.maximalIdeal A)
    (L : Type*) [Field L] [Algebra K L] [FiniteDimensional K L]
    (theta : L)
    (hroot : eval₂ (algebraMap K L) theta (chapter07LiftedPolynomial g) = 0)
    (hgen : Algebra.adjoin K ({theta} : Set L) = ⊤)
    (hdegree : Module.finrank K L = gbar.natDegree)
    (hresdegree : Module.finrank k k' = gbar.natDegree) :
    ∃ E : Chapter07FiniteLocalExtensionData K L k k',
      E.ramificationIndex = 1 ∧ E.residueDegree = Module.finrank k k' ∧
        Chapter07UnramifiedExtension E := by
  sorry

/-- The integral model generated by the lifted root is a finite
`A`-algebra.  The source's `B=A[theta]` is represented by the generated
subalgebra, rather than by the whole fraction-field quotient (which would
incorrectly assert `A[theta] = L`). -/
theorem chapter07_constructed_integral_model_is_finite
    {A K k : Type*} [CommRing A] [IsDomain A] [Field K] [Field k]
    [Algebra A K] [IsFractionRing A K] [HenselianLocalRing A]
    [IsDiscreteValuationRing A]
    (res : A →+* k) (gbar : k[X]) (g : A[X])
    (hbar : gbar.Monic ∧ Irreducible gbar ∧ gbar.Separable)
    (hlift : Chapter07MonicPolynomialLift res gbar g)
    (hres_surjective : Function.Surjective res)
    (hres_kernel : RingHom.ker res = IsLocalRing.maximalIdeal A) :
    Module.Finite A (Algebra.adjoin A ({chapter07LiftedRoot g} :
      Set (Chapter07LiftedPolynomialQuotient K
        (chapter07LiftedPolynomial g)))) := by
  sorry

/-- A common separable residue polynomial gives isomorphic lifted field
extensions, independently of the chosen monic coefficient lift. -/
theorem chapter07_different_monic_lifts_are_isomorphic
    {A K k : Type*} [CommRing A] [IsDomain A] [Field K] [Field k]
    [Algebra A K] [IsFractionRing A K] [HenselianLocalRing A]
    [IsDiscreteValuationRing A]
    (res : A →+* k) (gbar : k[X]) (g₁ g₂ : A[X])
    (hbar : gbar.Monic ∧ Irreducible gbar ∧ gbar.Separable)
    (h₁ : Chapter07MonicPolynomialLift res gbar g₁)
    (h₂ : Chapter07MonicPolynomialLift res gbar g₂)
    (hres_surjective : Function.Surjective res)
    (hres_kernel : RingHom.ker res = IsLocalRing.maximalIdeal A)
    (L₁ L₂ : Type*) [Field L₁] [Field L₂]
    [Algebra K L₁] [Algebra K L₂]
    [FiniteDimensional K L₁] [FiniteDimensional K L₂]
    (θ₁ : L₁) (θ₂ : L₂)
    (hroot₁ : eval₂ (algebraMap K L₁) θ₁ (chapter07LiftedPolynomial g₁) = 0)
    (hroot₂ : eval₂ (algebraMap K L₂) θ₂ (chapter07LiftedPolynomial g₂) = 0)
    (hgen₁ : Algebra.adjoin K ({θ₁} : Set L₁) = ⊤)
    (hgen₂ : Algebra.adjoin K ({θ₂} : Set L₂) = ⊤)
    (hdegree₁ : Module.finrank K L₁ = gbar.natDegree)
    (hdegree₂ : Module.finrank K L₂ = gbar.natDegree) :
    Nonempty (L₁ ≃ₐ[K] L₂) := by
  sorry

/-! The classification theorem is exposed through an explicit correspondence
interface.  This keeps the fixed separable closures and their residue maps
available to later formalizations without encoding them by hidden choices. -/

/-- The assertion that two displayed Galois groups are preserved by a
correspondence.  The group structures are supplied as part of the statement
when the corresponding carriers are not already typeclass instances. -/
def Chapter07GaloisGroupPreservation (G H : Type*) : Prop :=
  ∃ gG : Group G, ∃ gH : Group H,
    letI := gG
    letI := gH
    Nonempty (G ≃* H)

/-- Book-facing data for the reduction/lift equivalence in Theorem 7.2. -/
structure Chapter07UnramifiedClassificationInterface
    (U S : Type*) where
  reduction : U ≃ S
  degreeU : U → ℕ
  degreeS : S → ℕ
  degree_preserved : ∀ u, degreeU u = degreeS (reduction u)
  inclusionU : U → U → Prop
  inclusionS : S → S → Prop
  inclusion_preserved : ∀ u v,
    inclusionU u v ↔ inclusionS (reduction u) (reduction v)
  compositumU : U → U → U
  compositumS : S → S → S
  compositum_preserved : ∀ u v,
    reduction (compositumU u v) = compositumS (reduction u) (reduction v)
  intersectionU : U → U → U
  intersectionS : S → S → S
  intersection_preserved : ∀ u v,
    reduction (intersectionU u v) = intersectionS (reduction u) (reduction v)
  galoisU : U → Type uG
  galoisS : S → Type uG
  galois_preserved : ∀ u,
    Chapter07GaloisGroupPreservation (galoisU u) (galoisS (reduction u))

/-- Theorem 7.2, with all functorial clauses retained in the interface. -/
theorem chapter07_unramified_extensions_classified_by_residue_extensions
    {U S : Type*} (C : Chapter07UnramifiedClassificationInterface U S) :
    Nonempty (U ≃ S) ∧
      (∀ u, C.degreeU u = C.degreeS (C.reduction u)) ∧
      (∀ u v, C.inclusionU u v ↔
        C.inclusionS (C.reduction u) (C.reduction v)) ∧
      (∀ u v, C.reduction (C.compositumU u v) =
        C.compositumS (C.reduction u) (C.reduction v)) ∧
      (∀ u v, C.reduction (C.intersectionU u v) =
        C.intersectionS (C.reduction u) (C.reduction v)) ∧
      (∀ u, Chapter07GaloisGroupPreservation (C.galoisU u)
        (C.galoisS (C.reduction u))) := by
  sorry

end
end LastLib.Book02FiniteExtensionsOfLocalFields.Chapter07
