import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter07.Section02EquivalentCharacterizations

namespace LastLib.Book02FiniteExtensionsOfLocalFields.Chapter07

open Set
open Polynomial

noncomputable section

/-! # Book 2, Chapter 7, §7.3: constructing the unramified lift -/

/-- A monic polynomial over `A` lifting a prescribed residue polynomial. -/
def Chapter07MonicPolynomialLift
    {A k : Type*} [CommRing A] [Field k]
    (res : A →+* k) (gbar : k[X]) (g : A[X]) : Prop :=
  g.Monic ∧ g.map res = gbar

/-- The polynomial over the fraction field used in the quotient construction. -/
def chapter07LiftedPolynomial
    {A K : Type*} [CommRing A] [Field K] [Algebra A K]
    (g : A[X]) : K[X] :=
  g.map (algebraMap A K)

/-- The quotient algebra `K[T]/(g)` in the construction of §7.3. -/
abbrev Chapter07LiftedPolynomialQuotient
    (K : Type*) [Field K] (g : K[X]) : Type _ :=
  AdjoinRoot g

/-- The class of `T` in the lifted polynomial quotient. -/
def chapter07LiftedRoot
    {A K : Type*} [CommRing A] [Field K] [Algebra A K]
    (g : A[X]) : Chapter07LiftedPolynomialQuotient K (chapter07LiftedPolynomial g) :=
  AdjoinRoot.root (chapter07LiftedPolynomial g)

/-- The quotient is a field when the lifted polynomial is irreducible. -/
theorem chapter07_lifted_polynomial_quotient_is_field
    {K : Type*} [Field K] (g : K[X]) (hg : Irreducible g) :
    IsField (Chapter07LiftedPolynomialQuotient K g) := by
  sorry

/-- A monic quotient has the expected vector-space degree. -/
theorem chapter07_lifted_polynomial_quotient_degree
    {K : Type*} [Field K] (g : K[X]) (hg : g.Monic) :
    Module.finrank K (Chapter07LiftedPolynomialQuotient K g) = g.natDegree := by
  sorry

/-- Residue irreducibility forces irreducibility of a monic lift over a DVR
fraction field. -/
theorem chapter07_monic_lift_irreducible
    {A K k : Type*} [CommRing A] [IsDomain A] [Field K] [Field k]
    [Algebra A K] [IsFractionRing A K] [HenselianLocalRing A]
    [IsDiscreteValuationRing A]
    (res : A →+* k) (gbar : k[X]) (g : A[X])
    (hbar : gbar.Monic ∧ Irreducible gbar)
    (hlift : Chapter07MonicPolynomialLift res gbar g) :
    Irreducible (chapter07LiftedPolynomial (K := K) g) := by
  sorry

/-- The finite quotient construction has the residue degree prescribed by the
chosen finite separable residue extension. -/
theorem chapter07_construct_unramified_lift
    {A K k k' : Type*} [CommRing A] [IsDomain A]
    [Field K] [Field k] [Field k']
    [Algebra A K] [IsFractionRing A K] [Algebra k k']
    [FiniteDimensional k k'] [HenselianLocalRing A]
    [IsDiscreteValuationRing A]
    (res : A →+* k) (gbar : k[X]) (g : A[X])
    (hbar : gbar.Monic ∧ Irreducible gbar ∧ gbar.Separable)
    (hlift : Chapter07MonicPolynomialLift res gbar g)
    (L : Type*) [Field L] [Algebra K L] [FiniteDimensional K L]
    (theta : L)
    (hroot : eval₂ (algebraMap K L) theta (chapter07LiftedPolynomial g) = 0)
    (hgen : Algebra.adjoin K ({theta} : Set L) = ⊤)
    (hdegree : Module.finrank K L = gbar.natDegree)
    (hresdegree : Module.finrank k k' = gbar.natDegree)
    (hreslift : Chapter07ResidueExtensionIsSeparable k k') :
    ∃ E : Chapter07FiniteLocalExtensionData K L k k',
      E.ramificationIndex = 1 ∧ E.residueDegree = Module.finrank k k' ∧
        Chapter07UnramifiedExtension E := by
  sorry

/-- In the constructed quotient, the integral model is generated by the
lifted root; this is the ring-theoretic `B = A[theta]` assertion. -/
theorem chapter07_constructed_integral_model_is_monogenic
    {A K k : Type*} [CommRing A] [IsDomain A] [Field K] [Field k]
    [Algebra A K] [IsFractionRing A K] [HenselianLocalRing A]
    [IsDiscreteValuationRing A]
    (res : A →+* k) (gbar : k[X]) (g : A[X])
    (hbar : gbar.Monic ∧ Irreducible gbar ∧ gbar.Separable)
    (hlift : Chapter07MonicPolynomialLift res gbar g) :
    Algebra.adjoin A ({chapter07LiftedRoot g} :
      Set (Chapter07LiftedPolynomialQuotient K (chapter07LiftedPolynomial g))) = ⊤ := by
  sorry

/-- A common separable residue polynomial gives isomorphic lifted field
extensions, independently of the chosen monic coefficient lift. -/
theorem chapter07_different_monic_lifts_are_isomorphic
    {A K k : Type*} [CommRing A] [IsDomain A] [Field K] [Field k]
    [Algebra A K] [IsFractionRing A K] [HenselianLocalRing A]
    [IsDiscreteValuationRing A]
    (res : A →+* k) (gbar : k[X]) (g₁ g₂ : A[X])
    (hbar : gbar.Monic ∧ Irreducible gbar ∧ gbar.Separable)
    (h₁ : Chapter07MonicPolynomialLift res gbar g₁)
    (h₂ : Chapter07MonicPolynomialLift res gbar g₂)
    (L₁ L₂ : Type*) [Field L₁] [Field L₂]
    [Algebra K L₁] [Algebra K L₂]
    [FiniteDimensional K L₁] [FiniteDimensional K L₂]
    (θ₁ : L₁) (θ₂ : L₂)
    (hroot₁ : eval₂ (algebraMap K L₁) θ₁ (chapter07LiftedPolynomial g₁) = 0)
    (hroot₂ : eval₂ (algebraMap K L₂) θ₂ (chapter07LiftedPolynomial g₂) = 0)
    (hgen₁ : Algebra.adjoin K ({θ₁} : Set L₁) = ⊤)
    (hgen₂ : Algebra.adjoin K ({θ₂} : Set L₂) = ⊤)
    (hdegree₁ : Module.finrank K L₁ = gbar.natDegree)
    (hdegree₂ : Module.finrank K L₂ = gbar.natDegree) :
    Nonempty (L₁ ≃ₐ[K] L₂) := by
  sorry

/-- A concrete interface for the reduction/lifting maps in the classification
theorem. -/
structure Chapter07ReductionLiftEquivalence (U R : Type*) where
  reduction : U → R
  lift : R → U
  reduction_lift : Function.LeftInverse reduction lift
  lift_reduction : Function.LeftInverse lift reduction

/-- Compatibility data that makes the preceding bijection the classification
claimed in Theorem 7.2.  The order relations and lattice operations are kept
abstract because `U` and `R` stand for finite extensions in two separately
chosen closures; the fields state exactly which structures reduction must
preserve.  The last fields retain genuine group structures for the Galois
groups rather than merely recording equality of their cardinalities. -/
structure Chapter07ReductionLiftCompatibility
    {U R : Type*} (c : Chapter07ReductionLiftEquivalence U R) where
  extensionDegree : U → ℕ
  residueDegree : R → ℕ
  degree_preserved : ∀ u, extensionDegree u = residueDegree (c.reduction u)
  extensionLE : U → U → Prop
  residueLE : R → R → Prop
  inclusions_preserved : ∀ u v,
    extensionLE u v ↔ residueLE (c.reduction u) (c.reduction v)
  extensionCompositum : U → U → U
  residueCompositum : R → R → R
  composita_preserved : ∀ u v,
    c.reduction (extensionCompositum u v) = residueCompositum
      (c.reduction u) (c.reduction v)
  extensionIntersection : U → U → U
  residueIntersection : R → R → R
  intersections_preserved : ∀ u v,
    c.reduction (extensionIntersection u v) = residueIntersection
      (c.reduction u) (c.reduction v)
  extensionGaloisGroup : U → Type*
  residueGaloisGroup : R → Type*
  extensionGaloisStructure : ∀ u, Group (extensionGaloisGroup u)
  residueGaloisStructure : ∀ r, Group (residueGaloisGroup r)
  galois_groups_preserved : ∀ u,
    letI := extensionGaloisStructure u
    letI := residueGaloisStructure (c.reduction u)
    Nonempty (extensionGaloisGroup u ≃* residueGaloisGroup (c.reduction u))

theorem chapter07_reduction_lift_is_bijection
    {U R : Type*} (c : Chapter07ReductionLiftEquivalence U R) :
    Function.Bijective c.reduction := by
  exact ⟨c.lift_reduction.injective, c.reduction_lift.surjective⟩

/-- Reduction and lifting classify finite unramified extensions in fixed
separable closures.  `U` and `R` stand for the corresponding fixed-closure
objects; the equivalence structure records the actual reduction/lift maps. -/
theorem chapter07_unramified_reduction_classification
    (U R : Type*) (reduction : U → R) (lift : R → U)
    (hleft : Function.LeftInverse reduction lift)
    (hright : Function.LeftInverse lift reduction) :
    Nonempty (Chapter07ReductionLiftEquivalence U R) := by
  exact ⟨{
    reduction := reduction
    lift := lift
    reduction_lift := hleft
    lift_reduction := hright
  }⟩

end
end LastLib.Book02FiniteExtensionsOfLocalFields.Chapter07
