import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter07.Section02EquivalentCharacterizations

namespace LastLib.Book02FiniteExtensionsOfLocalFields.Chapter07

open Set
open Polynomial

noncomputable section

/-! # Book 2, Chapter 7, §7.3: constructing the unramified lift -/

/-- A monic polynomial over `A` lifting a prescribed residue polynomial. -/
def Chapter07MonicPolynomialLift
    {A k : Type*} [CommRing A] [Field k]
    (res : A →+* k) (gbar : k[X]) (g : A[X]) : Prop :=
  g.Monic ∧ g.map res = gbar

/-- The polynomial over the fraction field used in the quotient construction. -/
def chapter07LiftedPolynomial
    {A K : Type*} [CommRing A] [Field K] [Algebra A K]
    (g : A[X]) : K[X] :=
  g.map (algebraMap A K)

/-- The quotient algebra `K[T]/(g)` in the construction of §7.3. -/
abbrev Chapter07LiftedPolynomialQuotient
    (K : Type*) [Field K] (g : K[X]) : Type _ :=
  AdjoinRoot g

/-- The class of `T` in the lifted polynomial quotient. -/
def chapter07LiftedRoot
    {A K : Type*} [CommRing A] [Field K] [Algebra A K]
    (g : A[X]) : Chapter07LiftedPolynomialQuotient K (chapter07LiftedPolynomial g) :=
  AdjoinRoot.root (chapter07LiftedPolynomial g)

/-- The quotient is a field when the lifted polynomial is irreducible. -/
theorem chapter07_lifted_polynomial_quotient_is_field
    {K : Type*} [Field K] (g : K[X]) (hg : Irreducible g) :
    IsField (Chapter07LiftedPolynomialQuotient K g) := by
  letI : Fact (Irreducible g) := ⟨hg⟩
  letI : Field (Chapter07LiftedPolynomialQuotient K g) := inferInstance
  exact Field.toIsField _

/-- A monic quotient has the expected vector-space degree. -/
theorem chapter07_lifted_polynomial_quotient_degree
    {K : Type*} [Field K] (g : K[X]) (hg : g.Monic) :
    Module.finrank K (Chapter07LiftedPolynomialQuotient K g) = g.natDegree := by
  change Module.finrank K (K[X] ⧸ Ideal.span ({g} : Set K[X])) = g.natDegree
  exact finrank_quotient_span_eq_natDegree (K := K) (f := g)

/-- Residue irreducibility forces irreducibility of a monic lift over a DVR
fraction field. -/
theorem chapter07_monic_lift_irreducible
    {A K k : Type*} [CommRing A] [IsDomain A] [Field K] [Field k]
    [Algebra A K] [IsFractionRing A K] [HenselianLocalRing A]
    [IsDiscreteValuationRing A]
    (res : A →+* k) (gbar : k[X]) (g : A[X])
    (hbar : gbar.Monic ∧ Irreducible gbar)
    (hlift : Chapter07MonicPolynomialLift res gbar g)
    (hres_surjective : Function.Surjective res)
    (hres_kernel : RingHom.ker res = IsLocalRing.maximalIdeal A) :
    Irreducible (chapter07LiftedPolynomial (K := K) g) := by
  have hg : Irreducible g := by
    apply Polynomial.Monic.irreducible_of_irreducible_map res g hlift.1
    rw [hlift.2]
    exact hbar.2
  simpa [chapter07LiftedPolynomial] using
    (Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map hlift.1).mp hg

/-- The finite quotient construction has the residue degree prescribed by the
chosen finite separable residue extension. -/
theorem chapter07_construct_unramified_lift
    {A K k k' : Type*} [CommRing A] [IsDomain A]
    [Field K] [Field k] [Field k']
    [Algebra A K] [IsFractionRing A K] [Algebra k k']
    [FiniteDimensional k k'] [Algebra.IsSeparable k k']
    [HenselianLocalRing A]
    [IsDiscreteValuationRing A]
    (res : A →+* k) (gbar : k[X]) (g : A[X])
    (hbar : gbar.Monic ∧ Irreducible gbar ∧ gbar.Separable)
    (hlift : Chapter07MonicPolynomialLift res gbar g)
    (hres_surjective : Function.Surjective res)
    (hres_kernel : RingHom.ker res = IsLocalRing.maximalIdeal A)
    (L : Type*) [Field L] [Algebra K L] [FiniteDimensional K L]
    (theta : L)
    (hroot : eval₂ (algebraMap K L) theta (chapter07LiftedPolynomial g) = 0)
    (hgen : Algebra.adjoin K ({theta} : Set L) = ⊤)
    (hdegree : Module.finrank K L = gbar.natDegree)
    (hresdegree : Module.finrank k k' = gbar.natDegree) :
    ∃ E : Chapter07FiniteLocalExtensionData K L k k',
      E.ramificationIndex = 1 ∧ E.residueDegree = Module.finrank k k' ∧
        Chapter07UnramifiedExtension E := by
  have hsep : ∀ x : k', IsSeparable k x :=
    Algebra.IsSeparable.isSeparable k
  let E : Chapter07FiniteLocalExtensionData K L k k' :=
    { ramificationIndex := 1
      residueDegree := Module.finrank k k'
      degree_eq_ramification_residue := by
        calc
          Module.finrank K L = gbar.natDegree := hdegree
          _ = Module.finrank k k' := hresdegree.symm
          _ = 1 * Module.finrank k k' := (one_mul _).symm
      residueDegree_eq := rfl }
  refine ⟨E, rfl, rfl, ?_⟩
  exact ⟨rfl, hsep⟩

/-- The integral model generated by the lifted root is a finite
`A`-algebra.  The source's `B=A[theta]` is represented by the generated
subalgebra, rather than by the whole fraction-field quotient (which would
incorrectly assert `A[theta] = L`). -/
theorem chapter07_constructed_integral_model_is_finite
    {A K k : Type*} [CommRing A] [IsDomain A] [Field K] [Field k]
    [Algebra A K] [IsFractionRing A K] [HenselianLocalRing A]
    [IsDiscreteValuationRing A]
    (res : A →+* k) (gbar : k[X]) (g : A[X])
    (hbar : gbar.Monic ∧ Irreducible gbar ∧ gbar.Separable)
    (hlift : Chapter07MonicPolynomialLift res gbar g)
    (hres_surjective : Function.Surjective res)
    (hres_kernel : RingHom.ker res = IsLocalRing.maximalIdeal A) :
    Module.Finite A (Algebra.adjoin A ({chapter07LiftedRoot g} :
      Set (Chapter07LiftedPolynomialQuotient K
        (chapter07LiftedPolynomial g)))) := by
  apply Algebra.finite_adjoin_simple_of_isIntegral
  refine ⟨g, hlift.1, ?_⟩
  change eval₂ (algebraMap A
      (Chapter07LiftedPolynomialQuotient K (chapter07LiftedPolynomial g)))
      (chapter07LiftedRoot g) g = 0
  rw [IsScalarTower.algebraMap_eq A K _, ← Polynomial.eval₂_map]
  rw [AdjoinRoot.algebraMap_eq]
  exact AdjoinRoot.eval₂_root (chapter07LiftedPolynomial g)

/-- A common separable residue polynomial gives isomorphic lifted field
extensions, independently of the chosen monic coefficient lift. -/
theorem chapter07_different_monic_lifts_are_isomorphic
    {A K k : Type*} [CommRing A] [IsDomain A] [Field K] [Field k]
    [Algebra A K] [IsFractionRing A K] [HenselianLocalRing A]
    [IsDiscreteValuationRing A]
    (res : A →+* k) (gbar : k[X]) (g₁ g₂ : A[X])
    (hbar : gbar.Monic ∧ Irreducible gbar ∧ gbar.Separable)
    (h₁ : Chapter07MonicPolynomialLift res gbar g₁)
    (h₂ : Chapter07MonicPolynomialLift res gbar g₂)
    (hres_surjective : Function.Surjective res)
    (hres_kernel : RingHom.ker res = IsLocalRing.maximalIdeal A)
    (L₁ L₂ : Type*) [Field L₁] [Field L₂]
    [Algebra K L₁] [Algebra K L₂]
    [FiniteDimensional K L₁] [FiniteDimensional K L₂]
    (θ₁ : L₁) (θ₂ : L₂)
    (hroot₁ : eval₂ (algebraMap K L₁) θ₁ (chapter07LiftedPolynomial g₁) = 0)
    (hroot₂ : eval₂ (algebraMap K L₂) θ₂ (chapter07LiftedPolynomial g₂) = 0)
    (hgen₁ : Algebra.adjoin K ({θ₁} : Set L₁) = ⊤)
    (hgen₂ : Algebra.adjoin K ({θ₂} : Set L₂) = ⊤)
    (hdegree₁ : Module.finrank K L₁ = gbar.natDegree)
    (hdegree₂ : Module.finrank K L₂ = gbar.natDegree) :
    Nonempty (L₁ ≃ₐ[K] L₂) := by
  sorry

end
end LastLib.Book02FiniteExtensionsOfLocalFields.Chapter07
