import LastLib.Book01ValuationsDVRsAndCompletions.Chapter10.Section03IntegralElementsAreBounded

namespace LastLib.Book01ValuationsDVRsAndCompletions.Chapter10

universe u10K u10L u10Γ

open scoped BigOperators TensorProduct WithZero PowerSeries
open Polynomial

noncomputable section

/-!
# Chapter 10: Extensions of valuations

This file is a statement-generation formalization of Sections 10.1--10.7 of
Book 1.  The declarations deliberately keep the valuation-theoretic data
explicit: this makes the extension, residue, and ramification assertions
usable independently of the other generated chapters.
-/

/-! # Book 1, Chapter 10, Section 10.4: Ramification Index and Residue Degree
-/

/-! ## 10.4. Ramification index and residue degree -/

/-- The multiplicative subgroup generated by the nonzero values of a valuation. -/
def Chapter10ValueGroup {K Γ₀ : Type*} [Field K]
    [LinearOrderedCommGroupWithZero Γ₀] (v : Valuation K Γ₀) : Subgroup Γ₀ˣ :=
  MonoidWithZeroHom.valueGroup v.toMonoidWithZeroHom

/-- The residue field associated with a valuation. -/
abbrev Chapter10ResidueField {K Γ₀ : Type*} [Field K]
    [LinearOrderedCommGroupWithZero Γ₀] (v : Valuation K Γ₀) :=
  IsLocalRing.ResidueField v.valuationSubring

/-- The finite index of the value groups, once the inclusion is supplied. -/
noncomputable def Chapter10RamificationIndex
    {K L Γ₀ : Type*} [Field K] [Field L] [Algebra K L]
    [LinearOrderedCommGroupWithZero Γ₀]
    (v : Valuation K Γ₀) (w : Valuation L Γ₀)
    (hΓ : Chapter10ValueGroup v ≤ Chapter10ValueGroup w)
    [Finite (Chapter10ValueGroup w ⧸
      (Chapter10ValueGroup v).subgroupOf (Chapter10ValueGroup w))] : ℕ :=
  let _ := hΓ
  Nat.card (Chapter10ValueGroup w ⧸
    (Chapter10ValueGroup v).subgroupOf (Chapter10ValueGroup w))

/-- The residue degree of an extension. -/
noncomputable def Chapter10ResidueDegree
    {K L Γ₀ : Type*} [Field K] [Field L] [Algebra K L]
    [LinearOrderedCommGroupWithZero Γ₀]
    [FiniteDimensional K L]
    (v : Valuation K Γ₀) (w : Valuation L Γ₀)
    [Valuation.HasExtension v w] : ℕ :=
  Module.finrank (Chapter10ResidueField v) (Chapter10ResidueField w)

/-- The residue homomorphism induced by an extending valuation. -/
def Chapter10ResidueFieldMap
    {K L Γ₀ : Type*} [Field K] [Field L] [Algebra K L]
    [LinearOrderedCommGroupWithZero Γ₀]
    (v : Valuation K Γ₀) (w : Valuation L Γ₀)
    [Valuation.HasExtension v w] :
    Chapter10ResidueField v →+* Chapter10ResidueField w :=
  IsLocalRing.ResidueField.map (algebraMap v.valuationSubring w.valuationSubring)

/-- The residue map induced by an extending valuation is injective. -/
theorem chapter10_residue_field_map_injective
    {K L Γ₀ : Type*} [Field K] [Field L] [Algebra K L]
    [LinearOrderedCommGroupWithZero Γ₀]
    (v : Valuation K Γ₀) (w : Valuation L Γ₀)
    [Valuation.HasExtension v w] :
    Function.Injective (Chapter10ResidueFieldMap v w) := by
  intro a b hab
  obtain ⟨x, rfl⟩ := IsLocalRing.residue_surjective a
  obtain ⟨y, rfl⟩ := IsLocalRing.residue_surjective b
  have hres :
      IsLocalRing.residue w.valuationSubring
          (algebraMap v.valuationSubring w.valuationSubring x) =
        IsLocalRing.residue w.valuationSubring
          (algebraMap v.valuationSubring w.valuationSubring y) := by
    simpa [Chapter10ResidueFieldMap] using hab
  have hzero :
      IsLocalRing.residue w.valuationSubring
          (algebraMap v.valuationSubring w.valuationSubring x -
            algebraMap v.valuationSubring w.valuationSubring y) = 0 := by
    rw [map_sub, hres, sub_self]
  have hmem :
      algebraMap v.valuationSubring w.valuationSubring (x - y) ∈
        IsLocalRing.maximalIdeal w.valuationSubring := by
    apply (IsLocalRing.residue_eq_zero_iff _).mp
    simpa using hzero
  have hmem' : x - y ∈ IsLocalRing.maximalIdeal v.valuationSubring :=
    (Valuation.HasExtension.algebraMap_mem_maximalIdeal_iff v w).mp hmem
  apply sub_eq_zero.mp
  rw [← map_sub]
  exact (IsLocalRing.residue_eq_zero_iff _).mpr hmem'

/-- The residue degree for an extension whose value group may differ. -/
noncomputable def Chapter10HeterogeneousResidueDegree
    {K L ΓK ΓL : Type*} [Field K] [Field L] [Algebra K L]
    [LinearOrderedCommGroupWithZero ΓK]
    [LinearOrderedCommGroupWithZero ΓL]
    [FiniteDimensional K L]
    (v : Valuation K ΓK) (w : Valuation L ΓL)
    (h : v.IsEquiv (w.comap (algebraMap K L))) : ℕ := by
  letI : Valuation.HasExtension v w := ⟨h⟩
  exact Module.finrank (Chapter10ResidueField v) (Chapter10ResidueField w)

/-- The generator in a valuation's value group represented by a nonzero field
element.  This lets heterogeneous value-group maps state that they are
induced by restriction of the valuation, rather than merely being abstract
finite-index embeddings. -/
def Chapter10ValueGroupGenerator
    {K Γ₀ : Type*} [Field K]
    [LinearOrderedCommGroupWithZero Γ₀]
    (v : Valuation K Γ₀) (x : K) (hx : v x ≠ 0) :
    Chapter10ValueGroup v :=
  ⟨Units.mk0 (v x) (by simpa using hx),
    MonoidWithZeroHom.mem_valueGroup v.toMonoidWithZeroHom ⟨x, rfl⟩⟩

/--
The actual value-group and residue-field data of one finite branch.  The map
and its finite quotient are retained explicitly, rather than identifying
different ordered value groups with a fixed codomain.
-/
structure Chapter10HeterogeneousExtensionData
    {K L ΓK ΓL : Type*} [Field K] [Field L] [Algebra K L]
    [LinearOrderedCommGroupWithZero ΓK]
    [LinearOrderedCommGroupWithZero ΓL]
    [FiniteDimensional K L]
    (v : Valuation K ΓK) (w : Valuation L ΓL)
    (h : v.IsEquiv (w.comap (algebraMap K L))) where
  valueGroupMap : Chapter10ValueGroup v →* Chapter10ValueGroup w
  /-- The map sends every value attained on `K` to the corresponding value
  attained by its image in `L`; hence it is the canonical map induced by the
  extension, not an unrelated finite-index homomorphism. -/
  valueGroupMap_spec :
    ∀ (x : K) (hx : v x ≠ 0),
      ((valueGroupMap (Chapter10ValueGroupGenerator v x hx) :
        Chapter10ValueGroup w) : ΓLˣ) =
        Units.mk0 (w (algebraMap K L x)) (h.eq_zero.ne.mp hx)
  valueGroupMap_injective : Function.Injective valueGroupMap
  finite_quotient : Finite (Chapter10ValueGroup w ⧸ valueGroupMap.range)
  ramificationIndex : ℕ

  ramificationIndex_eq :
    ramificationIndex = Nat.card (Chapter10ValueGroup w ⧸ valueGroupMap.range)
  residueDegree : ℕ
  residueDegree_eq :
    residueDegree = Chapter10HeterogeneousResidueDegree v w h

/-- The value-group and residue-field data exist for every finite branch. -/
theorem chapter10_heterogeneous_extension_data_exists
    {K L ΓK ΓL : Type*} [Field K] [Field L] [Algebra K L]
    [LinearOrderedCommGroupWithZero ΓK]
    [LinearOrderedCommGroupWithZero ΓL] [FiniteDimensional K L]
    (v : Valuation K ΓK) (w : Valuation L ΓL)
    (h : v.IsEquiv (w.comap (algebraMap K L))) :
    Nonempty (Chapter10HeterogeneousExtensionData v w h) := by
  classical
  let vc := w.comap (algebraMap K L)
  have hinc : Chapter10ValueGroup vc ≤ Chapter10ValueGroup w := by
    change MonoidWithZeroHom.valueGroup vc.toMonoidWithZeroHom ≤
      MonoidWithZeroHom.valueGroup w.toMonoidWithZeroHom
    rw [MonoidWithZeroHom.valueGroup_def]
    refine (Subgroup.closure_le
      (MonoidWithZeroHom.valueGroup w.toMonoidWithZeroHom)).mpr ?_
    rintro y ⟨x, hx⟩
    apply MonoidWithZeroHom.mem_valueGroup w.toMonoidWithZeroHom
    refine ⟨algebraMap K L x, ?_⟩
    change w (algebraMap K L x) = (y : ΓL)
    exact hx
  let e₀ := h.orderMonoidIso
  let φ₀ : Chapter10ValueGroup v →* Chapter10ValueGroup vc :=
    (WithZero.unitsWithZeroEquiv.toMonoidHom).comp
      ((Units.map e₀.toMonoidHom).comp
        WithZero.unitsWithZeroEquiv.symm.toMonoidHom)
  have hφ₀ : Function.Injective φ₀ := by
    intro a b hab
    change
      WithZero.unitsWithZeroEquiv
          (Units.map e₀.toMonoidHom
            (WithZero.unitsWithZeroEquiv.symm a)) =
        WithZero.unitsWithZeroEquiv
          (Units.map e₀.toMonoidHom
            (WithZero.unitsWithZeroEquiv.symm b)) at hab
    have hab_units :
        Units.map e₀.toMonoidHom
            (WithZero.unitsWithZeroEquiv.symm a) =
          Units.map e₀.toMonoidHom
            (WithZero.unitsWithZeroEquiv.symm b) :=
      WithZero.unitsWithZeroEquiv.injective hab
    apply WithZero.unitsWithZeroEquiv.symm.injective
    apply Units.ext
    apply e₀.injective
    exact congrArg Units.val hab_units
  let φ : Chapter10ValueGroup v →* Chapter10ValueGroup w :=
    (Subgroup.inclusion hinc).comp φ₀
  have hφ : Function.Injective φ := by
    intro a b hab
    apply hφ₀
    exact (Subgroup.inclusion_injective hinc) hab
  have hφspec (x : K) (hx : v x ≠ 0) :
      ((φ (Chapter10ValueGroupGenerator v x hx) :
        Chapter10ValueGroup w) : ΓLˣ) =
        Units.mk0 (w (algebraMap K L x)) (h.eq_zero.ne.mp hx) := by
    apply Units.ext
    have hgen :
        (WithZero.unitsWithZeroEquiv.symm
            (Chapter10ValueGroupGenerator v x hx :
              MonoidWithZeroHom.valueGroup v.toMonoidWithZeroHom)).val =
          MonoidWithZeroHom.ValueGroup₀.restrict₀
            (MonoidWithZeroHom.ofClass v) x := by
      rw [MonoidWithZeroHom.ValueGroup₀.restrict₀_of_ne_zero
        (by simpa using hx)]
      rfl
    have hs := Valuation.IsEquiv.orderMonoidIso_spec₀ h x
    have hs' :
        e₀
            (WithZero.unitsWithZeroEquiv.symm
              (Chapter10ValueGroupGenerator v x hx :
                MonoidWithZeroHom.valueGroup v.toMonoidWithZeroHom)).val =
          MonoidWithZeroHom.ValueGroup₀.restrict₀
            (MonoidWithZeroHom.ofClass vc) x := by
      rw [hgen]
      exact hs
    change
      MonoidWithZeroHom.ValueGroup₀.embedding
          (f := MonoidWithZeroHom.ofClass vc)
          (e₀
            (WithZero.unitsWithZeroEquiv.symm
              (Chapter10ValueGroupGenerator v x hx :
                MonoidWithZeroHom.valueGroup v.toMonoidWithZeroHom)).val) =
        w (algebraMap K L x)
    rw [hs']
    simp [vc]
  refine ⟨{
    valueGroupMap := φ
    valueGroupMap_spec := hφspec
    valueGroupMap_injective := hφ
    finite_quotient := by
      let Q := Chapter10ValueGroup w ⧸ φ.range
      let rep : Q → Chapter10ValueGroup w :=
        fun q => Classical.choose (QuotientGroup.mk_surjective q)
      have hrep (q : Q) : QuotientGroup.mk (rep q) = q :=
        Classical.choose_spec (QuotientGroup.mk_surjective q)
      have hvalmem (u : Chapter10ValueGroup w) : ∃ x : L, ∃ hx : w x ≠ 0,
          Units.mk0 (w x) hx = (u : ΓLˣ) := by
        have hu : (u : ΓLˣ).val ∈
            (Units.val '' (Chapter10ValueGroup w : Set ΓLˣ)) :=
          ⟨u, u.property, rfl⟩
        change (u : ΓLˣ).val ∈
          Units.val '' (MonoidWithZeroHom.valueGroup w.toMonoidWithZeroHom : Set ΓLˣ) at hu
        rw [MonoidWithZeroHom.valueGroup_eq_range w.toMonoidWithZeroHom] at hu
        rcases hu with ⟨hu, hne⟩
        rcases hu with ⟨x, hx⟩
        have hne_u : (u : ΓLˣ).val ≠ 0 := by
          exact hne
        have hne' : w x ≠ 0 := by
          have hx' : w x = (u : ΓLˣ).val := by simpa using hx
          rw [hx']
          exact hne_u
        refine ⟨x, hne', ?_⟩
        apply Units.ext
        simpa using hx
      let x : Q → L := fun q => Classical.choose (hvalmem (rep q))
      have hx (q : Q) : w (x q) ≠ 0 :=
        Classical.choose (Classical.choose_spec (hvalmem (rep q)))
      let : Valuation.HasExtension v w := ⟨h⟩
      have hLI : LinearIndependent K x := by
        rw [linearIndependent_iff_finset_linearIndependent]
        intro s
        let e : (↥s) ≃ Fin s.card := Finset.equivFin s
        let x' : Fin s.card → L := fun i => x (e.symm i)
        have hx' (i : Fin s.card) : x' i ≠ 0 := by
          simpa [x'] using hx (e.symm i)
        have hblock : ∀ (a : Fin 1 → K),
            (∑ j, algebraMap K L (a j) * (1 : L)) = 0 →
              ∀ j, a j = 0 := by
          intro a ha j
          have ha0 : algebraMap K L (a 0) = 0 := by
            simpa using ha
          have : a 0 = 0 :=
            (RingHom.injective (algebraMap K L)) (by simpa using ha0)
          simpa [Subsingleton.elim j (0 : Fin 1)] using this
        have hvalues : ∀ (a : Fin s.card × Fin 1 → K)
            (i i' : Fin s.card), i ≠ i' →
            (∑ j, algebraMap K L (a (i, j)) * (1 : L)) ≠ 0 →
            (∑ j, algebraMap K L (a (i', j)) * (1 : L)) ≠ 0 →
            w (x' i * ∑ j, algebraMap K L (a (i, j)) * (1 : L)) ≠
              w (x' i' * ∑ j, algebraMap K L (a (i', j)) * (1 : L)) := by
          intro a i i' hii hai hai'
          simp only [Fin.sum_univ_one, mul_one] at hai hai' ⊢
          intro heq
          have hai0 : a (i, 0) ≠ 0 := by
            intro hz
            apply hai
            simp [hz]
          have hai'0 : a (i', 0) ≠ 0 := by
            intro hz
            apply hai'
            simp [hz]
          have hvai : v (a (i, 0)) ≠ 0 :=
            (Valuation.ne_zero_iff v).mpr hai0
          have hvai' : v (a (i', 0)) ≠ 0 :=
            (Valuation.ne_zero_iff v).mpr hai'0
          let ui : Chapter10ValueGroup v :=
            Chapter10ValueGroupGenerator v (a (i, 0)) hvai
          let ui' : Chapter10ValueGroup v :=
            Chapter10ValueGroupGenerator v (a (i', 0)) hvai'
          have hφui : (φ ui : ΓLˣ) =
              Units.mk0 (w (algebraMap K L (a (i, 0))))
                (h.eq_zero.ne.mp hvai) := by
            simpa [ui] using hφspec (a (i, 0)) hvai
          have hφui' : (φ ui' : ΓLˣ) =
              Units.mk0 (w (algebraMap K L (a (i', 0))))
                (h.eq_zero.ne.mp hvai') := by
            simpa [ui'] using hφspec (a (i', 0)) hvai'
          have hφui_val : (φ ui : ΓLˣ).val =
              w (algebraMap K L (a (i, 0))) := by
            rw [hφui]
            rfl
          have hφui'_val : (φ ui' : ΓLˣ).val =
              w (algebraMap K L (a (i', 0))) := by
            rw [hφui']
            rfl
          have hrepval : (rep (e.symm i) : ΓLˣ) * (φ ui : ΓLˣ) =
              (rep (e.symm i') : ΓLˣ) * (φ ui' : ΓLˣ) := by
            have hxi := Classical.choose_spec (hvalmem (rep (e.symm i)))
            have hxi' := Classical.choose_spec (hvalmem (rep (e.symm i')))
            have hxi_val : Units.mk0 (w (x (e.symm i))) (hx (e.symm i)) =
                (rep (e.symm i) : ΓLˣ) := hxi.2
            have hxi'_val : Units.mk0 (w (x (e.symm i'))) (hx (e.symm i')) =
                (rep (e.symm i') : ΓLˣ) := hxi'.2
            have hxi_val' : w (x (e.symm i)) =
                (rep (e.symm i) : ΓLˣ).val := by
              simpa using congrArg Units.val hxi_val
            have hxi'_val' : w (x (e.symm i')) =
                (rep (e.symm i') : ΓLˣ).val := by
              simpa using congrArg Units.val hxi'_val
            apply Units.ext
            simpa [x', w.map_mul, hφui_val, hφui'_val, hxi_val', hxi'_val'] using heq
          let g : Chapter10ValueGroup w :=
            ⟨(rep (e.symm i) : ΓLˣ)⁻¹ *
                (rep (e.symm i') : ΓLˣ), by
              exact (Chapter10ValueGroup w).mul_mem
                ((Chapter10ValueGroup w).inv_mem (rep (e.symm i)).property)
                (rep (e.symm i')).property⟩
          have huieq :
              ((rep (e.symm i) : ΓLˣ)⁻¹ *
                (rep (e.symm i') : ΓLˣ) : ΓLˣ) =
                (φ ui : ΓLˣ) * (φ ui' : ΓLˣ)⁻¹ := by
            calc
              ((rep (e.symm i) : ΓLˣ)⁻¹ *
                  (rep (e.symm i') : ΓLˣ) : ΓLˣ) =
                  (rep (e.symm i) : ΓLˣ)⁻¹ *
                    ((rep (e.symm i) : ΓLˣ) * (φ ui : ΓLˣ)) *
                      (φ ui' : ΓLˣ)⁻¹ := by rw [hrepval]; simp [mul_assoc]
            _ = (φ ui : ΓLˣ) * (φ ui' : ΓLˣ)⁻¹ := by simp
          have hmem' : g ∈ φ.range := by
            rw [MonoidHom.mem_range]
            refine ⟨ui * ui'⁻¹, ?_⟩
            apply Subtype.ext
            change (φ (ui * ui'⁻¹) : ΓLˣ) =
              (rep (e.symm i) : ΓLˣ)⁻¹ * (rep (e.symm i') : ΓLˣ)
            simpa [map_mul] using huieq.symm
          have hg : g = (rep (e.symm i))⁻¹ * rep (e.symm i') := by
            apply Subtype.ext
            rfl
          have hq0 :
              (QuotientGroup.mk (s := φ.range)
                  (rep (e.symm i)) : Q) =
                QuotientGroup.mk (s := φ.range)
                  (rep (e.symm i')) := by
            apply QuotientGroup.eq.mpr
            rw [← hg]
            exact hmem'
          have hq : (e.symm i : Q) = (e.symm i' : Q) := by
            calc
              (e.symm i : Q) = QuotientGroup.mk (rep (e.symm i)) :=
                (hrep (e.symm i)).symm
              _ = QuotientGroup.mk (rep (e.symm i')) := hq0
              _ = (e.symm i' : Q) := hrep (e.symm i')
          have hq' : e.symm i = e.symm i' := Subtype.ext hq
          exact hii (e.symm.injective hq')
        have hvalpair : ∀ (a : Fin s.card → K) (i i' : Fin s.card), i ≠ i' →
            a i ≠ 0 → a i' ≠ 0 →
            w (x' i * algebraMap K L (a i)) ≠
              w (x' i' * algebraMap K L (a i')) := by
          intro a i i' hii hai hai'
          let b : Fin s.card × Fin 1 → K := fun ij => a ij.1
          simpa [b] using hvalues b i i' hii
            (by simpa [b] using hai) (by simpa [b] using hai')
        have hLI'' : LinearIndependent K x' := by
          rw [Fintype.linearIndependent_iff]
          intro a ha
          let T : Finset (Fin s.card) :=
            Finset.univ.filter (fun i => a i ≠ 0)
          have hTempty : T = ∅ := by
            by_contra hT
            have hTne : T.Nonempty := Finset.nonempty_iff_ne_empty.mpr hT
            let U : Finset ΓL :=
              T.image (fun i => w (x' i * algebraMap K L (a i)))
            have hUne : U.Nonempty := hTne.image _
            obtain ⟨i₀, hi₀T, hi₀eq⟩ :=
              Finset.mem_image.mp (Finset.max'_mem U hUne)
            have hai₀ : a i₀ ≠ 0 := (Finset.mem_filter.mp hi₀T).2
            have hamap₀ : algebraMap K L (a i₀) ≠ 0 := by
              intro hamap
              apply hai₀
              exact (RingHom.injective (algebraMap K L)) (by simpa using hamap)
            have hterm₀ : w (x' i₀ * algebraMap K L (a i₀)) ≠ 0 := by
              exact (Valuation.ne_zero_iff w).mpr
                (mul_ne_zero (hx' i₀) hamap₀)
            have hmax (i : Fin s.card) (hiT : i ∈ T) :
                w (x' i * algebraMap K L (a i)) ≤
                  w (x' i₀ * algebraMap K L (a i₀)) := by
              calc
                w (x' i * algebraMap K L (a i)) ≤ U.max' hUne :=
                  Finset.le_max' U _ (Finset.mem_image.mpr ⟨i, hiT, rfl⟩)
                _ = w (x' i₀ * algebraMap K L (a i₀)) := hi₀eq.symm
            have hstrict (i : Fin s.card) (hiT : i ∈ T) (hne : i ≠ i₀) :
                w (x' i * algebraMap K L (a i)) <
                  w (x' i₀ * algebraMap K L (a i₀)) := by
              apply lt_of_le_of_ne (hmax i hiT)
              exact hvalpair a i i₀ hne
                (Finset.mem_filter.mp hiT).2 hai₀
            have hsumT :
                (∑ i ∈ T, x' i * algebraMap K L (a i)) = 0 := by
              calc
                (∑ i ∈ T, x' i * algebraMap K L (a i)) =
                    ∑ i : Fin s.card, x' i * algebraMap K L (a i) := by
                  apply Finset.sum_subset (Finset.subset_univ T)
                  intro i hiuniv hiNotT
                  have hai : a i = 0 := by
                    by_contra hai
                    exact hiNotT (Finset.mem_filter.mpr ⟨Finset.mem_univ _, hai⟩)
                  simp [hai]
                _ = 0 := by
                  calc
                    (∑ i : Fin s.card, x' i * algebraMap K L (a i)) =
                        ∑ i : Fin s.card, algebraMap K L (a i) * x' i := by
                      apply Finset.sum_congr rfl
                      intro i hi
                      rw [mul_comm]
                    _ = ∑ i : Fin s.card, a i • x' i := by
                      apply Finset.sum_congr rfl
                      intro i hi
                      rw [Algebra.smul_def]
                    _ = 0 := ha
            have hvalsum :
                w (∑ i ∈ T, x' i * algebraMap K L (a i)) =
                  w (x' i₀ * algebraMap K L (a i₀)) := by
              apply w.map_sum_eq_of_lt hi₀T
              intro i hiT
              rcases Finset.mem_sdiff.mp hiT with ⟨hiT, hiNot⟩
              exact hstrict i hiT (by simpa using hiNot)
            rw [hsumT, w.map_zero] at hvalsum
            exact hterm₀ hvalsum.symm
          have hz : ∀ i : Fin s.card, a i = 0 := by
            intro i
            by_contra hai
            have hiT : i ∈ T :=
              Finset.mem_filter.mpr ⟨Finset.mem_univ _, hai⟩
            rw [hTempty] at hiT
            simp at hiT
          intro i
          exact hz i
        have hLI_s := (linearIndependent_equiv e).mpr hLI''
        change LinearIndependent K (fun q : (↥s) => x' (e q)) at hLI_s
        have heqfun : (fun q : (↥s) => x' (e q)) =
            (fun q : (↥s) => x q) := by
          funext q
          simp [x']
        have hLI_s' : LinearIndependent K (fun q : (↥s) => x q) := by
          rw [← heqfun]
          exact hLI_s
        change LinearIndependent K (fun q : (↥s) => x q)
        exact hLI_s'
      exact hLI.finite
    ramificationIndex := Nat.card (Chapter10ValueGroup w ⧸ φ.range)
    ramificationIndex_eq := rfl
    residueDegree := Chapter10HeterogeneousResidueDegree v w h
    residueDegree_eq := rfl
  }⟩
/-- Value-group inclusion for a valuation extension. -/
theorem chapter10_value_group_inclusion
    {K L Γ₀ : Type*} [Field K] [Field L] [Algebra K L]
    [LinearOrderedCommGroupWithZero Γ₀]
    (v : Valuation K Γ₀) (w : Valuation L Γ₀)
    (hval : ∀ x : K, v x = w (algebraMap K L x)) :
    Chapter10ValueGroup v ≤ Chapter10ValueGroup w := by
  change MonoidWithZeroHom.valueGroup v.toMonoidWithZeroHom ≤
    MonoidWithZeroHom.valueGroup w.toMonoidWithZeroHom
  rw [MonoidWithZeroHom.valueGroup_def]
  refine (Subgroup.closure_le
    (MonoidWithZeroHom.valueGroup w.toMonoidWithZeroHom)).mpr ?_
  rintro y ⟨x, hx⟩
  apply MonoidWithZeroHom.mem_valueGroup w.toMonoidWithZeroHom
  refine ⟨algebraMap K L x, ?_⟩
  change w (algebraMap K L x) = (y : Γ₀)
  rw [← hval x]
  exact hx

/-- Finiteness of the value-group quotient in a finite extension. -/
theorem chapter10_value_group_quotient_finite
    {K L Γ₀ : Type*} [Field K] [Field L] [Algebra K L]
    [LinearOrderedCommGroupWithZero Γ₀] [FiniteDimensional K L]
    (v : Valuation K Γ₀) (w : Valuation L Γ₀)
    (hval : ∀ x : K, v x = w (algebraMap K L x))
    (hΓ : Chapter10ValueGroup v ≤ Chapter10ValueGroup w) :
    Finite (Chapter10ValueGroup w ⧸
      (Chapter10ValueGroup v).subgroupOf (Chapter10ValueGroup w)) := by
  classical
  have _ := hΓ
  let Q := Chapter10ValueGroup w ⧸
    (Chapter10ValueGroup v).subgroupOf (Chapter10ValueGroup w)
  let rep : Q → Chapter10ValueGroup w :=
    fun q => Classical.choose (QuotientGroup.mk_surjective q)
  have hrep (q : Q) : QuotientGroup.mk (rep q) = q :=
    Classical.choose_spec (QuotientGroup.mk_surjective q)
  have hvalmem (u : Chapter10ValueGroup w) : ∃ x : L, ∃ hx : w x ≠ 0,
      Units.mk0 (w x) hx = (u : Γ₀ˣ) := by
    have hu : (u : Γ₀ˣ).val ∈
        (Units.val '' (Chapter10ValueGroup w : Set Γ₀ˣ)) :=
      ⟨u, u.property, rfl⟩
    change (u : Γ₀ˣ).val ∈
      Units.val '' (MonoidWithZeroHom.valueGroup w.toMonoidWithZeroHom : Set Γ₀ˣ) at hu
    rw [MonoidWithZeroHom.valueGroup_eq_range w.toMonoidWithZeroHom] at hu
    rcases hu with ⟨hu, hne⟩
    rcases hu with ⟨x, hx⟩
    have hne_u : (u : Γ₀ˣ).val ≠ 0 := by
      exact hne
    have hne' : w x ≠ 0 := by
      have hx' : w x = (u : Γ₀ˣ).val := by simpa using hx
      rw [hx']
      exact hne_u
    refine ⟨x, hne', ?_⟩
    apply Units.ext
    simpa using hx
  let x : Q → L := fun q => Classical.choose (hvalmem (rep q))
  have hx (q : Q) : w (x q) ≠ 0 :=
    Classical.choose (Classical.choose_spec (hvalmem (rep q)))
  let : Valuation.HasExtension v w := ⟨by
    intro a b
    change v a ≤ v b ↔ w (algebraMap K L a) ≤ w (algebraMap K L b)
    rw [hval a, hval b]⟩
  have hLI : LinearIndependent K x := by
    rw [linearIndependent_iff_finset_linearIndependent]
    intro s
    let e : (↥s) ≃ Fin s.card := Finset.equivFin s
    let x' : Fin s.card → L := fun i => x (e.symm i)
    have hx' (i : Fin s.card) : x' i ≠ 0 := by
      simpa [x'] using hx (e.symm i)
    have hblock : ∀ (a : Fin 1 → K),
        (∑ j, algebraMap K L (a j) * (1 : L)) = 0 →
          ∀ j, a j = 0 := by
      intro a ha j
      have ha0 : algebraMap K L (a 0) = 0 := by
        simpa using ha
      have : a 0 = 0 := (RingHom.injective (algebraMap K L)) (by simpa using ha0)
      simpa [Subsingleton.elim j (0 : Fin 1)] using this
    have hvalues : ∀ (a : Fin s.card × Fin 1 → K)
        (i i' : Fin s.card), i ≠ i' →
        (∑ j, algebraMap K L (a (i, j)) * (1 : L)) ≠ 0 →
        (∑ j, algebraMap K L (a (i', j)) * (1 : L)) ≠ 0 →
        w (x' i * ∑ j, algebraMap K L (a (i, j)) * (1 : L)) ≠
          w (x' i' * ∑ j, algebraMap K L (a (i', j)) * (1 : L)) := by
      intro a i i' hii hai hai'
      simp only [Fin.sum_univ_one, mul_one] at hai hai' ⊢
      intro heq
      have hai0 : a (i, 0) ≠ 0 := by
        intro hz
        apply hai
        simp [hz]
      have hai'0 : a (i', 0) ≠ 0 := by
        intro hz
        apply hai'
        simp [hz]
      have hvai : v (a (i, 0)) ≠ 0 :=
        (Valuation.ne_zero_iff v).mpr hai0
      have hvai' : v (a (i', 0)) ≠ 0 :=
        (Valuation.ne_zero_iff v).mpr hai'0
      let ui : Chapter10ValueGroup v :=
        Chapter10ValueGroupGenerator v (a (i, 0)) hvai
      let ui' : Chapter10ValueGroup v :=
        Chapter10ValueGroupGenerator v (a (i', 0)) hvai'
      have hui : (ui : Γ₀ˣ) = Units.mk0 (v (a (i, 0))) hvai := by
        rfl
      have hui' : (ui' : Γ₀ˣ) = Units.mk0 (v (a (i', 0))) hvai' := by
        rfl
      have hrepval : (rep (e.symm i) : Γ₀ˣ) * (ui : Γ₀ˣ) =
          (rep (e.symm i') : Γ₀ˣ) * (ui' : Γ₀ˣ) := by
        have hxi := Classical.choose_spec (hvalmem (rep (e.symm i)))
        have hxi' := Classical.choose_spec (hvalmem (rep (e.symm i')))
        have hxi_val : Units.mk0 (w (x (e.symm i))) (hx (e.symm i)) =
            (rep (e.symm i) : Γ₀ˣ) := hxi.2
        have hxi'_val : Units.mk0 (w (x (e.symm i'))) (hx (e.symm i')) =
            (rep (e.symm i') : Γ₀ˣ) := hxi'.2
        have hxi_val' : w (x (e.symm i)) =
            (rep (e.symm i) : Γ₀ˣ).val := by
          simpa using congrArg Units.val hxi_val
        have hxi'_val' : w (x (e.symm i')) =
            (rep (e.symm i') : Γ₀ˣ).val := by
          simpa using congrArg Units.val hxi'_val
        apply Units.ext
        simpa [x', hval, hui, hui', w.map_mul, mul_assoc, hxi_val', hxi'_val'] using heq
      have hmem :
          ((rep (e.symm i) : Γ₀ˣ)⁻¹ *
              (rep (e.symm i') : Γ₀ˣ) : Γ₀ˣ) ∈ Chapter10ValueGroup v := by
        have huieq :
            ((rep (e.symm i) : Γ₀ˣ)⁻¹ *
                (rep (e.symm i') : Γ₀ˣ) : Γ₀ˣ) =
              (ui : Γ₀ˣ) * (ui' : Γ₀ˣ)⁻¹ := by
          calc
            ((rep (e.symm i) : Γ₀ˣ)⁻¹ *
                (rep (e.symm i') : Γ₀ˣ) : Γ₀ˣ) =
                (rep (e.symm i) : Γ₀ˣ)⁻¹ *
                  ((rep (e.symm i) : Γ₀ˣ) * (ui : Γ₀ˣ)) *
                    (ui' : Γ₀ˣ)⁻¹ := by rw [hrepval]; simp [mul_assoc]
            _ = (ui : Γ₀ˣ) * (ui' : Γ₀ˣ)⁻¹ := by simp
        rw [huieq]
        exact (Chapter10ValueGroup v).mul_mem ui.property
          ((Chapter10ValueGroup v).inv_mem ui'.property)
      let g : Chapter10ValueGroup w :=
        ⟨(rep (e.symm i) : Γ₀ˣ)⁻¹ *
            (rep (e.symm i') : Γ₀ˣ), by
          exact (Chapter10ValueGroup w).mul_mem
            ((Chapter10ValueGroup w).inv_mem (rep (e.symm i)).property)
            (rep (e.symm i')).property⟩
      have hmem' : g ∈
          (Chapter10ValueGroup v).subgroupOf (Chapter10ValueGroup w) := by
        apply Subgroup.mem_subgroupOf.mpr
        exact hmem
      have hg : g = (rep (e.symm i))⁻¹ * rep (e.symm i') := by
        apply Subtype.ext
        rfl
      have hq0 :
          (QuotientGroup.mk (s :=
              (Chapter10ValueGroup v).subgroupOf (Chapter10ValueGroup w))
            (rep (e.symm i)) : Q) =
            QuotientGroup.mk (s :=
              (Chapter10ValueGroup v).subgroupOf (Chapter10ValueGroup w))
              (rep (e.symm i')) := by
        apply QuotientGroup.eq.mpr
        rw [← hg]
        exact hmem'
      have hq : (e.symm i : Q) = (e.symm i' : Q) := by
        calc
          (e.symm i : Q) = QuotientGroup.mk (rep (e.symm i)) :=
            (hrep (e.symm i)).symm
          _ = QuotientGroup.mk (rep (e.symm i')) := hq0
          _ = (e.symm i' : Q) := hrep (e.symm i')
      have hq' : e.symm i = e.symm i' := Subtype.ext hq
      exact hii (e.symm.injective hq')
    have hvalpair : ∀ (a : Fin s.card → K) (i i' : Fin s.card), i ≠ i' →
        a i ≠ 0 → a i' ≠ 0 →
        w (x' i * algebraMap K L (a i)) ≠
          w (x' i' * algebraMap K L (a i')) := by
      intro a i i' hii hai hai'
      let b : Fin s.card × Fin 1 → K := fun ij => a ij.1
      simpa [b] using hvalues b i i' hii
        (by simpa [b] using hai) (by simpa [b] using hai')
    have hLI'' : LinearIndependent K x' := by
      rw [Fintype.linearIndependent_iff]
      intro a ha
      let T : Finset (Fin s.card) :=
        Finset.univ.filter (fun i => a i ≠ 0)
      have hTempty : T = ∅ := by
        by_contra hT
        have hTne : T.Nonempty := Finset.nonempty_iff_ne_empty.mpr hT
        let U : Finset Γ₀ :=
          T.image (fun i => w (x' i * algebraMap K L (a i)))
        have hUne : U.Nonempty := hTne.image _
        obtain ⟨i₀, hi₀T, hi₀eq⟩ :=
          Finset.mem_image.mp (Finset.max'_mem U hUne)
        have hai₀ : a i₀ ≠ 0 := (Finset.mem_filter.mp hi₀T).2
        have hamap₀ : algebraMap K L (a i₀) ≠ 0 := by
          intro hamap
          apply hai₀
          exact (RingHom.injective (algebraMap K L)) (by simpa using hamap)
        have hterm₀ : w (x' i₀ * algebraMap K L (a i₀)) ≠ 0 := by
          exact (Valuation.ne_zero_iff w).mpr
            (mul_ne_zero (hx' i₀) hamap₀)
        have hmax (i : Fin s.card) (hiT : i ∈ T) :
            w (x' i * algebraMap K L (a i)) ≤
              w (x' i₀ * algebraMap K L (a i₀)) := by
          calc
            w (x' i * algebraMap K L (a i)) ≤ U.max' hUne :=
              Finset.le_max' U _ (Finset.mem_image.mpr ⟨i, hiT, rfl⟩)
            _ = w (x' i₀ * algebraMap K L (a i₀)) := hi₀eq.symm
        have hstrict (i : Fin s.card) (hiT : i ∈ T) (hne : i ≠ i₀) :
            w (x' i * algebraMap K L (a i)) <
              w (x' i₀ * algebraMap K L (a i₀)) := by
          apply lt_of_le_of_ne (hmax i hiT)
          exact hvalpair a i i₀ hne
            (Finset.mem_filter.mp hiT).2 hai₀
        have hsumT :
            (∑ i ∈ T, x' i * algebraMap K L (a i)) = 0 := by
          calc
            (∑ i ∈ T, x' i * algebraMap K L (a i)) =
                ∑ i : Fin s.card, x' i * algebraMap K L (a i) := by
              apply Finset.sum_subset (Finset.subset_univ T)
              intro i hiuniv hiNotT
              have hai : a i = 0 := by
                by_contra hai
                exact hiNotT (Finset.mem_filter.mpr ⟨Finset.mem_univ _, hai⟩)
              simp [hai]
            _ = 0 := by
              calc
                (∑ i : Fin s.card, x' i * algebraMap K L (a i)) =
                    ∑ i : Fin s.card, algebraMap K L (a i) * x' i := by
                  apply Finset.sum_congr rfl
                  intro i hi
                  rw [mul_comm]
                _ = ∑ i : Fin s.card, a i • x' i := by
                  apply Finset.sum_congr rfl
                  intro i hi
                  rw [Algebra.smul_def]
                _ = 0 := ha
        have hvalsum :
            w (∑ i ∈ T, x' i * algebraMap K L (a i)) =
              w (x' i₀ * algebraMap K L (a i₀)) := by
          apply w.map_sum_eq_of_lt hi₀T
          intro i hiT
          rcases Finset.mem_sdiff.mp hiT with ⟨hiT, hiNot⟩
          exact hstrict i hiT (by simpa using hiNot)
        rw [hsumT, w.map_zero] at hvalsum
        exact hterm₀ hvalsum.symm
      have hz : ∀ i : Fin s.card, a i = 0 := by
        intro i
        by_contra hai
        have hiT : i ∈ T := Finset.mem_filter.mpr ⟨Finset.mem_univ _, hai⟩
        rw [hTempty] at hiT
        simp at hiT
      intro i
      exact hz i
    have hLI_s := (linearIndependent_equiv e).mpr hLI''
    change LinearIndependent K (fun q : (↥s) => x' (e q)) at hLI_s
    have heqfun : (fun q : (↥s) => x' (e q)) =
        (fun q : (↥s) => x q) := by
      funext q
      simp [x']
    have hLI_s' : LinearIndependent K (fun q : (↥s) => x q) := by
      rw [← heqfun]
      exact hLI_s
    change LinearIndependent K (fun q : (↥s) => x q)
    exact hLI_s'
  exact hLI.finite

/-- Finiteness of the induced residue-field extension. -/
theorem chapter10_residue_degree_finite
    {K L Γ₀ : Type*} [Field K] [Field L] [Algebra K L]
    [LinearOrderedCommGroupWithZero Γ₀] [FiniteDimensional K L]
    (v : Valuation K Γ₀) (w : Valuation L Γ₀)
    [h : Valuation.HasExtension v w] :
    FiniteDimensional (Chapter10ResidueField v) (Chapter10ResidueField w) := by
  classical
  let k := Chapter10ResidueField v
  let E := Chapter10ResidueField w
  let I := Module.Basis.ofVectorSpaceIndex k E
  let b : Module.Basis I k E := Module.Basis.ofVectorSpace k E
  let y₀ : I → w.valuationSubring := fun i =>
    Classical.choose (IsLocalRing.residue_surjective (b i))
  have hy₀ (i : I) :
      IsLocalRing.residue w.valuationSubring (y₀ i) = b i :=
    Classical.choose_spec (IsLocalRing.residue_surjective (b i))
  let y : I → L := fun i => y₀ i
  have hyval (i : I) : w (y i) = 1 := by
    have hbi : b i ≠ 0 := b.ne_zero i
    have hnot : y₀ i ∉ IsLocalRing.maximalIdeal w.valuationSubring := by
      intro hmem
      apply hbi
      rw [← hy₀ i]
      exact (IsLocalRing.residue_eq_zero_iff _).mpr hmem
    have hle : w (y i) ≤ 1 :=
      (Valuation.mem_valuationSubring_iff w (y i)).mpr (y₀ i).property
    have hnlt : ¬w (y i) < 1 := by
      intro hlt
      apply hnot
      exact (Valuation.mem_maximalIdeal_iff (v := w)).mpr hlt
    exact le_antisymm hle (le_of_not_gt hnlt)
  have hLI : LinearIndependent K y := by
    rw [linearIndependent_iff_finset_linearIndependent]
    intro s
    let e : (↥s) ≃ Fin s.card := Finset.equivFin s
    let y' : Fin s.card → L := fun i => y (e.symm i)
    have hy' (i : Fin s.card) : w (y' i) = 1 := by
      simpa [y'] using hyval (e.symm i)
    have hLI' : LinearIndependent K y' := by
      rw [Fintype.linearIndependent_iff]
      intro a ha
      let T : Finset (Fin s.card) :=
        Finset.univ.filter (fun i => a i ≠ 0)
      have hTempty : T = ∅ := by
        by_contra hT
        have hTne : T.Nonempty := Finset.nonempty_iff_ne_empty.mpr hT
        let U : Finset Γ₀ :=
          T.image (fun i => w (algebraMap K L (a i)))
        have hUne : U.Nonempty := hTne.image _
        obtain ⟨i₀, hi₀T, hi₀eq⟩ :=
          Finset.mem_image.mp (Finset.max'_mem U hUne)
        have hai₀ : a i₀ ≠ 0 := (Finset.mem_filter.mp hi₀T).2
        have hamap₀ : algebraMap K L (a i₀) ≠ 0 := by
          simpa using (RingHom.injective (algebraMap K L)).ne hai₀
        have hw₀ : w (algebraMap K L (a i₀)) ≠ 0 :=
          (Valuation.ne_zero_iff w).mpr hamap₀
        have hmax (i : Fin s.card) (hiT : i ∈ T) :
            w (algebraMap K L (a i)) ≤
              w (algebraMap K L (a i₀)) := by
          calc
            w (algebraMap K L (a i)) ≤ U.max' hUne :=
              Finset.le_max' U _ (Finset.mem_image.mpr ⟨i, hiT, rfl⟩)
            _ = w (algebraMap K L (a i₀)) := hi₀eq.symm
        let c : Fin s.card → v.valuationSubring := fun i =>
          ⟨a i / a i₀, by
            by_cases hai : a i = 0
            · simp [hai]
            · have hiT : i ∈ T :=
                Finset.mem_filter.mpr ⟨Finset.mem_univ _, hai⟩
              apply (Valuation.mem_valuationSubring_iff v _).mpr
              apply (Valuation.HasExtension.val_map_le_one_iff v w _).mp
              rw [map_div₀, w.map_div]
              exact (div_le_one₀ (w.pos_iff.mpr hamap₀)).mpr (hmax i hiT)
            ⟩
        have hnorm :
            (∑ i : Fin s.card,
              algebraMap K L (a i / a i₀) * y' i) = 0 := by
          have ha' :
              (∑ i : Fin s.card, algebraMap K L (a i) * y' i) = 0 := by
            simpa only [Algebra.smul_def] using ha
          calc
            (∑ i : Fin s.card,
                algebraMap K L (a i / a i₀) * y' i) =
                ∑ i : Fin s.card,
                  (algebraMap K L (a i₀))⁻¹ *
                    (algebraMap K L (a i) * y' i) := by
              apply Finset.sum_congr rfl
              intro i hi
              rw [map_div₀]
              field_simp [hw₀]
            _ = (algebraMap K L (a i₀))⁻¹ *
                ∑ i : Fin s.card, algebraMap K L (a i) * y' i := by
              rw [Finset.mul_sum]
            _ = 0 := by rw [ha', mul_zero]
        have hnormB :
            (∑ i : Fin s.card,
                (algebraMap v.valuationSubring w.valuationSubring (c i)) *
                  (y₀ (e.symm i))) = 0 := by
          apply Subtype.ext
          simpa [c, y', y] using hnorm
        have hresnorm :=
          congrArg (IsLocalRing.residue w.valuationSubring) hnormB
        have hresrel :
            (∑ i : Fin s.card,
              algebraMap (Chapter10ResidueField v) (Chapter10ResidueField w)
                (IsLocalRing.residue v.valuationSubring (c i)) *
                b (e.symm i)) = 0 := by
          simpa only [map_sum, map_mul,
            Valuation.HasExtension.algebraMap_residue_eq_residue_algebraMap,
            hy₀, map_zero] using hresnorm
        have hb' : LinearIndependent k (fun i : Fin s.card => b (e.symm i)) :=
          b.linearIndependent.comp
            (fun i : Fin s.card => (e.symm i : I))
            (fun i j hij => by
              exact e.symm.injective (Subtype.ext hij))
        have hc0 : ∀ i : Fin s.card,
            IsLocalRing.residue v.valuationSubring (c i) = 0 := by
          apply (Fintype.linearIndependent_iff.mp hb')
          simpa only [Algebra.smul_def] using hresrel
        have hc₀ : c i₀ = 1 := by
          apply Subtype.ext
          dsimp [c]
          exact div_self hai₀
        have honezero : (1 : Chapter10ResidueField v) = 0 := by
          calc
            (1 : Chapter10ResidueField v) =
                IsLocalRing.residue v.valuationSubring (c i₀) := by
              rw [hc₀]
              simp
            _ = 0 := hc0 i₀
        exact one_ne_zero honezero
      have hz : ∀ i : Fin s.card, a i = 0 := by
        intro i
        by_contra hai
        have hiT : i ∈ T := Finset.mem_filter.mpr ⟨Finset.mem_univ _, hai⟩
        rw [hTempty] at hiT
        simp at hiT
      intro i
      exact hz i
    have heq :
        (fun i : Fin s.card => y' i) ∘ e =
          (fun q : (↥s) => y q) := by
      funext q
      simp [y']
    exact (linearIndependent_equiv' e heq).mpr hLI'
  let : Finite I := Cardinal.mk_lt_aleph0_iff.mp
    hLI.lt_aleph0_of_finiteDimensional
  exact b.finiteDimensional_of_finite

/-- The value-group and residue directions give independent vectors. -/
theorem chapter10_value_residue_product_independence
    {K L Γ₀ : Type*} [Field K] [Field L] [Algebra K L]
    [LinearOrderedCommGroupWithZero Γ₀]
    (v : Valuation K Γ₀) (w : Valuation L Γ₀)
    [Valuation.HasExtension v w]
    {r s : ℕ} (x : Fin r → L) (y : Fin s → L)
    (hx : ∀ i, x i ≠ 0)
    (hblock : ∀ (a : Fin s → K),
      (∑ j, algebraMap K L (a j) * y j) = 0 → ∀ j, a j = 0)
    (hvalues : ∀ (a : Fin r × Fin s → K) (i i' : Fin r), i ≠ i' →
      (∑ j, algebraMap K L (a (i, j)) * y j) ≠ 0 →
      (∑ j, algebraMap K L (a (i', j)) * y j) ≠ 0 →
      w (x i * ∑ j, algebraMap K L (a (i, j)) * y j) ≠
        w (x i' * ∑ j, algebraMap K L (a (i', j)) * y j)) :
    LinearIndependent K (fun ij : Fin r × Fin s => x ij.1 * y ij.2) := by
  classical
  rw [Fintype.linearIndependent_iff]
  intro a ha
  let z : Fin r → L := fun i => ∑ j, algebraMap K L (a (i, j)) * y j
  have hregroup :
      (∑ ij : Fin r × Fin s, a ij • (x ij.1 * y ij.2)) =
        ∑ i : Fin r, x i * z i := by
    rw [Fintype.sum_prod_type]
    apply Finset.sum_congr rfl
    intro i hi
    simp only [z, Finset.mul_sum]
    apply Finset.sum_congr rfl
    intro j hj
    simp only [Algebra.smul_def]
    ring
  have hzero : (∑ i : Fin r, x i * z i) = 0 := by
    rw [← hregroup]
    exact ha
  let T : Finset (Fin r) := Finset.univ.filter (fun i => z i ≠ 0)
  have hTempty : T = ∅ := by
    by_contra hT
    have hTne : T.Nonempty := Finset.nonempty_iff_ne_empty.mpr hT
    let U : Finset Γ₀ := T.image (fun i => w (x i * z i))
    have hUne : U.Nonempty := hTne.image _
    obtain ⟨i₀, hi₀T, hi₀eq⟩ :=
      Finset.mem_image.mp (Finset.max'_mem U hUne)
    have hzi₀ : z i₀ ≠ 0 := (Finset.mem_filter.mp hi₀T).2
    have hterm₀ : w (x i₀ * z i₀) ≠ 0 := by
      exact (Valuation.ne_zero_iff w).mpr (mul_ne_zero (hx i₀) hzi₀)
    have hmax (i : Fin r) (hiT : i ∈ T) :
        w (x i * z i) ≤ w (x i₀ * z i₀) := by
      calc
        w (x i * z i) ≤ U.max' hUne :=
          Finset.le_max' U _ (Finset.mem_image.mpr ⟨i, hiT, rfl⟩)
        _ = w (x i₀ * z i₀) := hi₀eq.symm
    have hstrict (i : Fin r) (hiT : i ∈ T) (hne : i ≠ i₀) :
        w (x i * z i) < w (x i₀ * z i₀) := by
      apply lt_of_le_of_ne (hmax i hiT)
      exact hvalues a i i₀ hne (Finset.mem_filter.mp hiT).2 hzi₀
    have hsumT : (∑ i ∈ T, x i * z i) = 0 := by
      calc
        (∑ i ∈ T, x i * z i) = ∑ i : Fin r, x i * z i := by
          apply Finset.sum_subset (Finset.subset_univ T)
          intro i hiuniv hiNotT
          have hzi : z i = 0 := by
            by_contra hzi
            exact hiNotT (Finset.mem_filter.mpr ⟨Finset.mem_univ _, hzi⟩)
          simp [hzi]
        _ = 0 := hzero
    have hvalsum : w (∑ i ∈ T, x i * z i) = w (x i₀ * z i₀) := by
      apply w.map_sum_eq_of_lt hi₀T
      intro i hiT
      rcases Finset.mem_sdiff.mp hiT with ⟨hiT, hiNot⟩
      exact hstrict i hiT (by simpa using hiNot)
    rw [hsumT, w.map_zero] at hvalsum
    exact hterm₀ hvalsum.symm
  have hz : ∀ i : Fin r, z i = 0 := by
    intro i
    by_contra hzi
    have hiT : i ∈ T := Finset.mem_filter.mpr ⟨Finset.mem_univ _, hzi⟩
    rw [hTempty] at hiT
    simp at hiT
  intro ij
  exact (hblock (fun j => a (ij.1, j)) (hz ij.1)) ij.2

/-- The single-extension fundamental inequality ef ≤ [L:K]. -/
theorem chapter10_single_extension_fundamental_inequality
    {K L Γ₀ : Type*} [Field K] [Field L] [Algebra K L]
    [LinearOrderedCommGroupWithZero Γ₀] [FiniteDimensional K L]
    (v : Valuation K Γ₀) (w : Valuation L Γ₀)
    [h : Valuation.HasExtension v w]
    (hval : ∀ x : K, v x = w (algebraMap K L x))
    (hΓ : Chapter10ValueGroup v ≤ Chapter10ValueGroup w)
    [hfinite : Finite (Chapter10ValueGroup w ⧸
      (Chapter10ValueGroup v).subgroupOf (Chapter10ValueGroup w))] :
    Chapter10RamificationIndex v w hΓ * Chapter10ResidueDegree v w ≤
      Module.finrank K L := by
  set_option maxHeartbeats 1000000 in
    classical
    let : FiniteDimensional (Chapter10ResidueField v)
        (Chapter10ResidueField w) := chapter10_residue_degree_finite v w
    let Q := Chapter10ValueGroup w ⧸
      (Chapter10ValueGroup v).subgroupOf (Chapter10ValueGroup w)
    let : Fintype Q := Fintype.ofFinite Q
    let d : ℕ := Module.finrank (Chapter10ResidueField v)
      (Chapter10ResidueField w)
    let b : Module.Basis (Fin d) (Chapter10ResidueField v)
        (Chapter10ResidueField w) := Module.finBasis _ _
    let rep : Q → Chapter10ValueGroup w := fun q =>
      Classical.choose (QuotientGroup.mk_surjective q)
    have hrep (q : Q) : QuotientGroup.mk (rep q) = q :=
      Classical.choose_spec (QuotientGroup.mk_surjective q)
    have hvalmem (u : Chapter10ValueGroup w) : ∃ z : L, ∃ hz : w z ≠ 0,
        Units.mk0 (w z) hz = (u : Γ₀ˣ) := by
      have hu : (u : Γ₀ˣ).val ∈
          (Units.val '' (Chapter10ValueGroup w : Set Γ₀ˣ)) :=
        ⟨u, u.property, rfl⟩
      change (u : Γ₀ˣ).val ∈
        Units.val ''
          (MonoidWithZeroHom.valueGroup w.toMonoidWithZeroHom : Set Γ₀ˣ) at hu
      rw [MonoidWithZeroHom.valueGroup_eq_range w.toMonoidWithZeroHom] at hu
      rcases hu with ⟨hu, hne⟩
      rcases hu with ⟨z, hz⟩
      have hne_u : (u : Γ₀ˣ).val ≠ 0 := by exact hne
      have hz' : w z ≠ 0 := by
        have hz_eq : w z = (u : Γ₀ˣ).val := by simpa using hz
        rw [hz_eq]
        exact hne_u
      refine ⟨z, hz', ?_⟩
      apply Units.ext
      simpa using hz
    let x : Q → L := fun q => Classical.choose (hvalmem (rep q))
    have hx (q : Q) : w (x q) ≠ 0 :=
      Classical.choose (Classical.choose_spec (hvalmem (rep q)))
    let y₀ : Fin d → w.valuationSubring := fun i =>
      Classical.choose (IsLocalRing.residue_surjective (b i))
    have hy₀ (i : Fin d) :
        IsLocalRing.residue w.valuationSubring (y₀ i) = b i :=
      Classical.choose_spec (IsLocalRing.residue_surjective (b i))
    let y : Fin d → L := fun i => y₀ i
    have hyval (i : Fin d) : w (y i) = 1 := by
      have hbi : b i ≠ 0 := b.ne_zero i
      have hnot : y₀ i ∉ IsLocalRing.maximalIdeal w.valuationSubring := by
        intro hmem
        apply hbi
        rw [← hy₀ i]
        exact (IsLocalRing.residue_eq_zero_iff _).mpr hmem
      have hle : w (y i) ≤ 1 :=
        (Valuation.mem_valuationSubring_iff w (y i)).mpr (y₀ i).property
      have hnlt : ¬w (y i) < 1 := by
        intro hlt
        apply hnot
        exact (Valuation.mem_maximalIdeal_iff (v := w)).mpr hlt
      exact le_antisymm hle (le_of_not_gt hnlt)
    have hLIy : LinearIndependent K y := by
      rw [Fintype.linearIndependent_iff]
      intro a ha
      let T : Finset (Fin d) :=
        Finset.univ.filter (fun i => a i ≠ 0)
      have hTempty : T = ∅ := by
        by_contra hT
        have hTne : T.Nonempty := Finset.nonempty_iff_ne_empty.mpr hT
        let U : Finset Γ₀ :=
          T.image (fun i => w (algebraMap K L (a i)))
        have hUne : U.Nonempty := hTne.image _
        obtain ⟨i₀, hi₀T, hi₀eq⟩ :=
          Finset.mem_image.mp (Finset.max'_mem U hUne)
        have hai₀ : a i₀ ≠ 0 := (Finset.mem_filter.mp hi₀T).2
        have hamap₀ : algebraMap K L (a i₀) ≠ 0 := by
          simpa using (RingHom.injective (algebraMap K L)).ne hai₀
        have hw₀ : w (algebraMap K L (a i₀)) ≠ 0 :=
          (Valuation.ne_zero_iff w).mpr hamap₀
        have hmax (i : Fin d) (hiT : i ∈ T) :
            w (algebraMap K L (a i)) ≤
              w (algebraMap K L (a i₀)) := by
          calc
            w (algebraMap K L (a i)) ≤ U.max' hUne :=
              Finset.le_max' U _ (Finset.mem_image.mpr ⟨i, hiT, rfl⟩)
            _ = w (algebraMap K L (a i₀)) := hi₀eq.symm
        let c : Fin d → v.valuationSubring := fun i =>
          ⟨a i / a i₀, by
            by_cases hai : a i = 0
            · simp [hai]
            · have hiT : i ∈ T :=
                Finset.mem_filter.mpr ⟨Finset.mem_univ _, hai⟩
              apply (Valuation.mem_valuationSubring_iff v _).mpr
              apply (Valuation.HasExtension.val_map_le_one_iff v w _).mp
              rw [map_div₀, w.map_div]
              exact (div_le_one₀ (w.pos_iff.mpr hamap₀)).mpr (hmax i hiT)
            ⟩
        have hnorm :
            (∑ i : Fin d, algebraMap K L (a i / a i₀) * y i) = 0 := by
          have ha' : (∑ i : Fin d, algebraMap K L (a i) * y i) = 0 := by
            simpa only [Algebra.smul_def] using ha
          calc
            (∑ i : Fin d, algebraMap K L (a i / a i₀) * y i) =
                ∑ i : Fin d,
                  (algebraMap K L (a i₀))⁻¹ *
                    (algebraMap K L (a i) * y i) := by
              apply Finset.sum_congr rfl
              intro i hi
              rw [map_div₀]
              field_simp [hw₀]
            _ = (algebraMap K L (a i₀))⁻¹ *
                ∑ i : Fin d, algebraMap K L (a i) * y i := by
              rw [Finset.mul_sum]
            _ = 0 := by rw [ha', mul_zero]
        have hnormB :
            (∑ i : Fin d,
                (algebraMap v.valuationSubring w.valuationSubring (c i)) *
                  (y₀ i)) = 0 := by
          apply Subtype.ext
          simpa [c, y] using hnorm
        have hresnorm :=
          congrArg (IsLocalRing.residue w.valuationSubring) hnormB
        have hresrel :
            (∑ i : Fin d,
              algebraMap (Chapter10ResidueField v) (Chapter10ResidueField w)
                (IsLocalRing.residue v.valuationSubring (c i)) * b i) = 0 := by
          simpa only [map_sum, map_mul,
            Valuation.HasExtension.algebraMap_residue_eq_residue_algebraMap v w,
            hy₀, map_zero] using hresnorm
        have hc0 : ∀ i : Fin d,
            IsLocalRing.residue v.valuationSubring (c i) = 0 := by
          apply (Fintype.linearIndependent_iff.mp b.linearIndependent)
          simpa only [Algebra.smul_def] using hresrel
        have hc₀ : c i₀ = 1 := by
          apply Subtype.ext
          dsimp [c]
          exact div_self hai₀
        have honezero : (1 : Chapter10ResidueField v) = 0 := by
          calc
            (1 : Chapter10ResidueField v) =
                IsLocalRing.residue v.valuationSubring (c i₀) := by
              rw [hc₀]
              simp
            _ = 0 := hc0 i₀
        exact one_ne_zero honezero
      have hz : ∀ i : Fin d, a i = 0 := by
        intro i
        by_contra hai
        have hiT : i ∈ T := Finset.mem_filter.mpr ⟨Finset.mem_univ _, hai⟩
        rw [hTempty] at hiT
        simp at hiT
      intro i
      exact hz i
    have hblock : ∀ (a : Fin d → K),
        (∑ j, algebraMap K L (a j) * y j) = 0 → ∀ j, a j = 0 := by
      intro a ha
      apply (Fintype.linearIndependent_iff.mp hLIy) a
      simpa only [Algebra.smul_def] using ha
    have hsum_value (a : Fin d → K)
        (ha : (∑ j, algebraMap K L (a j) * y j) ≠ 0) :
        ∃ j, a j ≠ 0 ∧
          w (∑ j, algebraMap K L (a j) * y j) =
            w (algebraMap K L (a j)) := by
      let T : Finset (Fin d) :=
        Finset.univ.filter (fun i => a i ≠ 0)
      have hTne : T.Nonempty := by
        by_contra hT
        apply ha
        have hz : ∀ i : Fin d, a i = 0 := by
          intro i
          by_contra hai
          exact hT ⟨i, Finset.mem_filter.mpr ⟨Finset.mem_univ _, hai⟩⟩
        simp [hz]
      let U : Finset Γ₀ :=
        T.image (fun i => w (algebraMap K L (a i)))
      have hUne : U.Nonempty := hTne.image _
      obtain ⟨i₀, hi₀T, hi₀eq⟩ :=
        Finset.mem_image.mp (Finset.max'_mem U hUne)
      have hai₀ : a i₀ ≠ 0 := (Finset.mem_filter.mp hi₀T).2
      have hamap₀ : algebraMap K L (a i₀) ≠ 0 := by
        simpa using (RingHom.injective (algebraMap K L)).ne hai₀
      have hw₀ : w (algebraMap K L (a i₀)) ≠ 0 :=
        (Valuation.ne_zero_iff w).mpr hamap₀
      have hmax (i : Fin d) (hiT : i ∈ T) :
          w (algebraMap K L (a i)) ≤
            w (algebraMap K L (a i₀)) := by
        calc
          w (algebraMap K L (a i)) ≤ U.max' hUne :=
            Finset.le_max' U _ (Finset.mem_image.mpr ⟨i, hiT, rfl⟩)
          _ = w (algebraMap K L (a i₀)) := hi₀eq.symm
      let c : Fin d → v.valuationSubring := fun i =>
        ⟨a i / a i₀, by
          by_cases hai : a i = 0
          · simp [hai]
          · have hiT : i ∈ T :=
              Finset.mem_filter.mpr ⟨Finset.mem_univ _, hai⟩
            apply (Valuation.mem_valuationSubring_iff v _).mpr
            apply (Valuation.HasExtension.val_map_le_one_iff v w _).mp
            rw [map_div₀, w.map_div]
            exact (div_le_one₀ (w.pos_iff.mpr hamap₀)).mpr (hmax i hiT)
          ⟩
      let normB : w.valuationSubring :=
        ∑ i : Fin d,
          (algebraMap v.valuationSubring w.valuationSubring (c i)) * y₀ i
      have hnormB_coe : (normB : L) =
          ∑ i : Fin d, algebraMap K L (a i / a i₀) * y i := by
        simp [normB, c, y]
      have hresnorm_ne :
          IsLocalRing.residue w.valuationSubring normB ≠ 0 := by
        intro hres
        have hresrel :
            (∑ i : Fin d,
              algebraMap (Chapter10ResidueField v) (Chapter10ResidueField w)
                (IsLocalRing.residue v.valuationSubring (c i)) * b i) = 0 := by
          have hres' := hres
          simpa [normB, map_sum, map_mul,
            Valuation.HasExtension.algebraMap_residue_eq_residue_algebraMap v w,
            hy₀] using hres'
        have hc0 : ∀ i : Fin d,
            IsLocalRing.residue v.valuationSubring (c i) = 0 := by
          apply (Fintype.linearIndependent_iff.mp b.linearIndependent)
          simpa only [Algebra.smul_def] using hresrel
        have hc₀ : c i₀ = 1 := by
          apply Subtype.ext
          dsimp [c]
          exact div_self hai₀
        have honezero : (1 : Chapter10ResidueField v) = 0 := by
          calc
            (1 : Chapter10ResidueField v) =
                IsLocalRing.residue v.valuationSubring (c i₀) := by
              rw [hc₀]
              simp
            _ = 0 := hc0 i₀
        exact one_ne_zero honezero
      have hnormval : w (normB : L) = 1 := by
        have hle : w (normB : L) ≤ 1 :=
          (Valuation.mem_valuationSubring_iff w (normB : L)).mpr normB.property
        have hnlt : ¬w (normB : L) < 1 := by
          intro hlt
          apply hresnorm_ne
          exact (IsLocalRing.residue_eq_zero_iff _).mpr
            ((Valuation.mem_maximalIdeal_iff (v := w)).mpr hlt)
        exact le_antisymm hle (le_of_not_gt hnlt)
      have hnorm_eq :
          (∑ i : Fin d, algebraMap K L (a i / a i₀) * y i) =
            (algebraMap K L (a i₀))⁻¹ *
              ∑ i : Fin d, algebraMap K L (a i) * y i := by
        calc
          (∑ i : Fin d, algebraMap K L (a i / a i₀) * y i) =
              ∑ i : Fin d,
                (algebraMap K L (a i₀))⁻¹ *
                  (algebraMap K L (a i) * y i) := by
            apply Finset.sum_congr rfl
            intro i hi
            rw [map_div₀]
            field_simp [hw₀]
          _ = (algebraMap K L (a i₀))⁻¹ *
              ∑ i : Fin d, algebraMap K L (a i) * y i := by
            rw [Finset.mul_sum]
      have hsum_eq :
          (∑ i : Fin d, algebraMap K L (a i) * y i) =
            algebraMap K L (a i₀) * (normB : L) := by
        calc
          (∑ i : Fin d, algebraMap K L (a i) * y i) =
              algebraMap K L (a i₀) *
                ((algebraMap K L (a i₀))⁻¹ *
                  ∑ i : Fin d, algebraMap K L (a i) * y i) := by
            field_simp [hw₀]
          _ = algebraMap K L (a i₀) *
              (∑ i : Fin d, algebraMap K L (a i / a i₀) * y i) := by
            rw [hnorm_eq]
          _ = algebraMap K L (a i₀) * (normB : L) := by
            rw [hnormB_coe]
      refine ⟨i₀, hai₀, ?_⟩
      rw [hsum_eq, w.map_mul, hnormval, mul_one]
    have hvalues : ∀ (a : Q × Fin d → K) (q q' : Q), q ≠ q' →
        (∑ j, algebraMap K L (a (q, j)) * y j) ≠ 0 →
        (∑ j, algebraMap K L (a (q', j)) * y j) ≠ 0 →
        w (x q * ∑ j, algebraMap K L (a (q, j)) * y j) ≠
          w (x q' * ∑ j, algebraMap K L (a (q', j)) * y j) := by
      intro a q q' hqq' hq hq'
      obtain ⟨j, haj, hj⟩ := hsum_value (fun j => a (q, j)) hq
      obtain ⟨j', haj', hj'⟩ := hsum_value (fun j => a (q', j)) hq'
      intro heq
      have hvj : v (a (q, j)) ≠ 0 :=
        (Valuation.ne_zero_iff v).mpr haj
      have hvj' : v (a (q', j')) ≠ 0 :=
        (Valuation.ne_zero_iff v).mpr haj'
      let uj : Chapter10ValueGroup v :=
        Chapter10ValueGroupGenerator v (a (q, j)) hvj
      let uj' : Chapter10ValueGroup v :=
        Chapter10ValueGroupGenerator v (a (q', j')) hvj'
      have huj : (uj : Γ₀ˣ) =
          Units.mk0 (v (a (q, j))) hvj := by rfl
      have huj' : (uj' : Γ₀ˣ) =
          Units.mk0 (v (a (q', j'))) hvj' := by rfl
      have hrepval :
          (rep q : Γ₀ˣ) * (uj : Γ₀ˣ) =
            (rep q' : Γ₀ˣ) * (uj' : Γ₀ˣ) := by
        have hxi := Classical.choose_spec (hvalmem (rep q))
        have hxi' := Classical.choose_spec (hvalmem (rep q'))
        have hxi_val : Units.mk0 (w (x q)) (hx q) = (rep q : Γ₀ˣ) := hxi.2
        have hxi'_val : Units.mk0 (w (x q')) (hx q') =
            (rep q' : Γ₀ˣ) := hxi'.2
        have hxi_val' : w (x q) = (rep q : Γ₀ˣ).val := by
          simpa using congrArg Units.val hxi_val
        have hxi'_val' : w (x q') = (rep q' : Γ₀ˣ).val := by
          simpa using congrArg Units.val hxi'_val
        apply Units.ext
        simpa [w.map_mul, hval, huj, huj', hj, hj', hxi_val', hxi'_val']
          using heq
      have hmem :
          ((uj : Γ₀ˣ) * (uj' : Γ₀ˣ)⁻¹) ∈ Chapter10ValueGroup v := by
        exact (Chapter10ValueGroup v).mul_mem uj.property
          ((Chapter10ValueGroup v).inv_mem uj'.property)
      let g : Chapter10ValueGroup w :=
        ⟨(rep q : Γ₀ˣ)⁻¹ * (rep q' : Γ₀ˣ), by
          exact (Chapter10ValueGroup w).mul_mem
            ((Chapter10ValueGroup w).inv_mem (rep q).property)
            (rep q').property⟩
      have huieq :
          ((rep q : Γ₀ˣ)⁻¹ * (rep q' : Γ₀ˣ) : Γ₀ˣ) =
            (uj : Γ₀ˣ) * (uj' : Γ₀ˣ)⁻¹ := by
        calc
          ((rep q : Γ₀ˣ)⁻¹ * (rep q' : Γ₀ˣ) : Γ₀ˣ) =
              (rep q : Γ₀ˣ)⁻¹ *
                ((rep q : Γ₀ˣ) * (uj : Γ₀ˣ)) *
                  (uj' : Γ₀ˣ)⁻¹ := by rw [hrepval]; simp [mul_assoc]
          _ = (uj : Γ₀ˣ) * (uj' : Γ₀ˣ)⁻¹ := by simp
      have hmem' : g ∈
          (Chapter10ValueGroup v).subgroupOf (Chapter10ValueGroup w) := by
        apply Subgroup.mem_subgroupOf.mpr
        change ((rep q : Γ₀ˣ)⁻¹ * (rep q' : Γ₀ˣ)) ∈ Chapter10ValueGroup v
        rw [huieq]
        exact hmem
      have hg : g = (rep q)⁻¹ * rep q' := by
        apply Subtype.ext
        rfl
      have hq0 :
          (QuotientGroup.mk (s :=
              (Chapter10ValueGroup v).subgroupOf (Chapter10ValueGroup w))
            (rep q) : Q) =
            QuotientGroup.mk (s :=
              (Chapter10ValueGroup v).subgroupOf (Chapter10ValueGroup w))
              (rep q') := by
        apply QuotientGroup.eq.mpr
        rw [← hg]
        exact hmem'
      have hq'' : q = q' := by
        calc
          q = QuotientGroup.mk (rep q) := (hrep q).symm
          _ = QuotientGroup.mk (rep q') := hq0
          _ = q' := hrep q'
      exact hqq' hq''
    let eQ : Q ≃ Fin (Fintype.card Q) := Fintype.equivFin Q
    let x' : Fin (Fintype.card Q) → L := fun i => x (eQ.symm i)
    have hx' (i : Fin (Fintype.card Q)) : x' i ≠ 0 := by
      simpa [x'] using (Valuation.ne_zero_iff w).mp (hx (eQ.symm i))
    have hvalues' : ∀ (a : Fin (Fintype.card Q) × Fin d → K)
        (i i' : Fin (Fintype.card Q)), i ≠ i' →
        (∑ j, algebraMap K L (a (i, j)) * y j) ≠ 0 →
        (∑ j, algebraMap K L (a (i', j)) * y j) ≠ 0 →
        w (x' i * ∑ j, algebraMap K L (a (i, j)) * y j) ≠
          w (x' i' * ∑ j, algebraMap K L (a (i', j)) * y j) := by
      intro a i i' hii hi hi'
      let a' : Q × Fin d → K := fun qj => a (eQ qj.1, qj.2)
      have hq : eQ.symm i ≠ eQ.symm i' := by
        intro heq
        apply hii
        exact eQ.symm.injective heq
      simpa [x', a'] using
        hvalues a' (eQ.symm i) (eQ.symm i') hq
          (by simpa [a'] using hi) (by simpa [a'] using hi')
    have hLI := chapter10_value_residue_product_independence v w x' y hx' hblock hvalues'
    have hcard := hLI.fintype_card_le_finrank
    simpa [Chapter10RamificationIndex, Chapter10ResidueDegree, Q, d,
      Nat.card_eq_fintype_card] using hcard

/-- Normalized discrete additive valuations. -/
def Chapter10DiscreteAddValuation {K : Type*} [Field K]
    (v : AddValuation K (WithTop ℤ)) : Prop :=
  ∃ π : K, π ≠ 0 ∧ v π = 1 ∧
    ∀ x : K, x ≠ 0 → ∃ n : ℤ, v x = (n : WithTop ℤ)

/-- Units for an additive valuation. -/
def Chapter10AddValuationUnit {K : Type*} [Field K]
    (v : AddValuation K (WithTop ℤ)) (u : K) : Prop :=
  u ≠ 0 ∧ v u = 0

/-- Restriction of a normalized discrete valuation scales by the ramification index. -/
theorem chapter10_normalized_restriction_formula
    {K L : Type*} [Field K] [Field L] [Algebra K L]
    (v : AddValuation K (WithTop ℤ)) (w : AddValuation L (WithTop ℤ))
    (hv : Chapter10DiscreteAddValuation v)
    (hw : Chapter10DiscreteAddValuation w)
    (hext : v.IsEquiv (w.comap (algebraMap K L))) :
    ∃ e : ℕ, 0 < e ∧ ∀ x : K, x ≠ 0 →
      w (algebraMap K L x) = e • v x := by
  rcases hv with ⟨π, hπ0, hπ, hv⟩
  rcases hw with ⟨Pi, hPi0, hPi, hw⟩
  obtain ⟨m, hm⟩ := hw (algebraMap K L π)
    (by simpa using (RingHom.injective (algebraMap K L)).ne hπ0)
  have hmpos : (0 : WithTop ℤ) < (m : WithTop ℤ) := by
    rw [← hm]
    have hlt_hidden :
        (AddValuation.toValuation v) π <
          (AddValuation.toValuation v) 1 := by
      simp only [AddValuation.toValuation_apply]
      change (OrderDual.toDual (v π)) < (OrderDual.toDual (v 1))
      rw [hπ, v.map_one]
      exact OrderDual.toDual_lt_toDual.mpr zero_lt_one
    have hlt_hidden' :=
      (hext.lt_iff_lt (x := π) (y := (1 : K))).mp hlt_hidden
    have hlt_add : w (algebraMap K L (1 : K)) <
        w (algebraMap K L π) := by
      change (OrderDual.toDual (w (algebraMap K L π))) <
        (OrderDual.toDual (w (algebraMap K L (1 : K)))) at hlt_hidden'
      exact OrderDual.toDual_lt_toDual.mp hlt_hidden'
    simpa using hlt_add
  have hm_int : 0 < m := by
    exact_mod_cast hmpos
  have hm0 : 0 ≤ m := by
    exact hm_int.le
  let e : ℕ := m.toNat
  have hme : (m : ℤ) = e := by
    simp [e, Int.toNat_of_nonneg hm0]
  have hepos : 0 < e := by
    have he_int : (0 : ℤ) < (e : ℤ) := by
      simpa [hme] using hm_int
    exact_mod_cast he_int
  refine ⟨e, hepos, ?_⟩
  intro x hx0
  obtain ⟨n, hn⟩ := hv x hx0
  have hone : ∀ z : ℕ, z • (1 : WithTop ℤ) = (z : WithTop ℤ) := by
    intro z
    induction z with
    | zero => simp
    | succ z ih =>
        rw [succ_nsmul, Nat.cast_succ, ih]
  have hnat : ∀ a b : ℕ,
      a • (b : WithTop ℤ) = b • (a : WithTop ℤ) := by
    intro a b
    induction b with
    | zero => simp
    | succ b ih =>
        rw [Nat.cast_succ, smul_add, succ_nsmul, ih, hone]
  have hnegcast : ∀ z : ℕ,
      (Int.negSucc z : WithTop ℤ) = -((z + 1 : ℕ) : WithTop ℤ) := by
    intro z
    simp [Int.negSucc_eq]
  have hpow_v : ∀ z : ℤ, v (π ^ z) = (z : WithTop ℤ) := by
    intro z
    cases z with
    | ofNat z =>
        change v (π ^ (z : ℤ)) = (z : WithTop ℤ)
        rw [zpow_natCast, v.map_pow, hπ, hone]
    | negSucc z =>
        rw [zpow_negSucc, v.map_inv, v.map_pow, hπ]
        rw [hnegcast z, hone]
  have hpow_w : ∀ z : ℤ,
      w (algebraMap K L (π ^ z)) = z • w (algebraMap K L π) := by
    intro z
    cases z with
    | ofNat z =>
        change w (algebraMap K L (π ^ (z : ℤ))) =
          (z : ℤ) • w (algebraMap K L π)
        rw [zpow_natCast, map_pow, w.map_pow, natCast_zsmul]
    | negSucc z =>
        rw [zpow_negSucc, map_inv₀, map_pow, w.map_inv, w.map_pow,
          negSucc_zsmul]
  have hv_eq : v x = v (π ^ n) := hn.trans (hpow_v n).symm
  have hw_eq : w (algebraMap K L x) =
      w (algebraMap K L (π ^ n)) :=
    (hext.eq_iff).mp hv_eq
  rw [hw_eq, hpow_w, hm, hme, hn]
  have hcast : ∀ z : ℕ,
      ((z : ℤ) : WithTop ℤ) = (z : WithTop ℤ) := by
    intro z
    norm_cast
  have hneg_nsmul : ∀ (a : ℕ) (b : WithTop ℤ),
      a • -b = -(a • b) := by
    intro a b
    induction a with
    | zero => simp
    | succ a ih =>
        simp only [succ_nsmul, ih]
        rw [neg_add_rev, add_comm]
  cases n with
  | ofNat n =>
      rw [Int.ofNat_eq_natCast, hcast e, natCast_zsmul]
      exact hnat n e
  | negSucc n =>
      rw [hcast e, negSucc_zsmul, hnegcast n, hneg_nsmul]
      congr 1
      exact hnat (n + 1) e

/-- Uniformizers are related by π = u Piᵉ. -/
theorem chapter10_uniformizer_relation
    {K L : Type*} [Field K] [Field L] [Algebra K L]
    (v : AddValuation K (WithTop ℤ)) (w : AddValuation L (WithTop ℤ))
    (π : K) (Pi : L) (e : ℕ)
    (he : 0 < e) (hπ : v π = 1) (hPi : w Pi = 1)
    (hv : Chapter10DiscreteAddValuation v)
    (hw : Chapter10DiscreteAddValuation w)
    (hscale : ∀ x : K, x ≠ 0 →
      w (algebraMap K L x) = e • v x) :
    ∃ u : L, Chapter10AddValuationUnit w u ∧
      algebraMap K L π = u * Pi ^ e := by
  have _ := he
  have _ := hv
  have _ := hw
  have hπ0 : π ≠ 0 := by
    intro h
    subst π
    simp at hπ
  have hPi0 : Pi ≠ 0 := by
    intro h
    subst Pi
    simp at hPi
  have hpow0 : Pi ^ e ≠ 0 := pow_ne_zero _ hPi0
  let u : L := algebraMap K L π / Pi ^ e
  refine ⟨u, ?_, (div_mul_cancel₀ _ hpow0).symm⟩
  constructor
  · have hmap0 : algebraMap K L π ≠ 0 := by
      simpa using (RingHom.injective (algebraMap K L)).ne hπ0
    exact div_ne_zero hmap0 hpow0
  · dsimp [u]
    rw [div_eq_mul_inv, w.map_mul, w.map_inv, w.map_pow, hscale π hπ0, hπ, hPi]
    simp

/-- The residue-field injection is finite in the finite-extension setting. -/
theorem chapter10_ramification_residue_finite
    {K L Γ₀ : Type*} [Field K] [Field L] [Algebra K L]
    [LinearOrderedCommGroupWithZero Γ₀] [FiniteDimensional K L]
    (v : Valuation K Γ₀) (w : Valuation L Γ₀)
    [Valuation.HasExtension v w] :
    FiniteDimensional (Chapter10ResidueField v) (Chapter10ResidueField w) := by
  exact chapter10_residue_degree_finite v w

end

end LastLib.Book01ValuationsDVRsAndCompletions.Chapter10
