import LastLib.Book01ValuationsDVRsAndCompletions.Chapter13.Section01CoordinatesForACompleteLocalRing
import Mathlib.RingTheory.Algebraic.Basic
import Mathlib.RingTheory.Algebraic.Integral
import Mathlib.RingTheory.AlgebraicIndependent.Basic
import Mathlib.RingTheory.Localization.FractionRing

namespace LastLib.Book01ValuationsDVRsAndCompletions.Chapter13

open Filter Ideal IsLocalRing Polynomial
open scoped Polynomial

noncomputable section

/-! # Book 1, Chapter 13, Section 13.2: Coefficient fields in equal characteristic zero -/

universe u v w

/-- A chosen field presentation of the residue ring. -/
structure Chapter13ResidueFieldPresentation
    (A : Type u) [CommRing A] [IsLocalRing A]
    (k : Type v) [Field k] where
  equiv : Chapter13ResidueRing A ≃+* k

/-- Every subfield of a local ring reduces injectively to its residue field. -/
theorem chapter13_subfield_reduction_injective
    {A : Type u} [CommRing A] [IsLocalRing A]
    (K : Chapter13Subfield A) :
    Function.Injective ((Chapter13ResidueMap A).comp K.carrier.subtype) := by
  let : Field K.carrier := K.field_carrier.toField
  intro x y hxy
  have hz : Chapter13ResidueMap A (K.carrier.subtype x - K.carrier.subtype y) = 0 := by
    rw [map_sub, sub_eq_zero]
    exact hxy
  have hm : K.carrier.subtype x - K.carrier.subtype y ∈ IsLocalRing.maximalIdeal A := by
    change Ideal.Quotient.mk _ (K.carrier.subtype x - K.carrier.subtype y) = 0 at hz
    exact (Ideal.Quotient.eq_zero_iff_mem).mp hz
  have heq : K.carrier.subtype x = K.carrier.subtype y := by
    by_contra hne
    have hxy' : x ≠ y := fun h => hne (congrArg K.carrier.subtype h)
    have hu' : IsUnit (x - y) := isUnit_iff_ne_zero.mpr (sub_ne_zero.mpr hxy')
    have hu : IsUnit (K.carrier.subtype x - K.carrier.subtype y) := by
      simpa using IsUnit.map K.carrier.subtype hu'
    exact (IsLocalRing.notMem_maximalIdeal.mpr hu) hm
  exact K.carrier.subtype_injective heq

/-- The data used to lift a transcendental residue element. -/
structure Chapter13TranscendentalLiftData
    (A : Type u) [CommRing A] [IsLocalRing A]
    (K : Type v) [Field K]
    (k : Type w) [Field k] [Algebra K k]
    (σ : K →+* A) (ρ : A →+* k) (b : k) (a : A) : Prop where
  residue_kernel : RingHom.ker ρ = IsLocalRing.maximalIdeal A
  residue_compatibility : ρ.comp σ = algebraMap K k
  residue_lift : ρ a = b
  transcendental : Transcendental K b

/-- Nonzero polynomials in a lifted transcendental element are units. -/
theorem chapter13_transcendental_lift_polynomials_are_units
    {A : Type u} [CommRing A] [IsLocalRing A]
    {K : Type v} [Field K]
    {k : Type w} [Field k] [Algebra K k]
    {σ : K →+* A} {ρ : A →+* k} {b : k} {a : A}
    (h : Chapter13TranscendentalLiftData A K k σ ρ b a) :
    ∀ p : K[X], p ≠ 0 → IsUnit (Polynomial.eval₂RingHom σ a p) := by
  intro p hp
  by_contra hunit
  have hmem : Polynomial.eval₂RingHom σ a p ∈ IsLocalRing.maximalIdeal A := by
    by_contra hnotmem
    exact hunit (IsLocalRing.notMem_maximalIdeal.mp hnotmem)
  have hzeroρ : ρ (Polynomial.eval₂RingHom σ a p) = 0 := by
    change Polynomial.eval₂RingHom σ a p ∈ RingHom.ker ρ
    rw [h.residue_kernel]
    exact hmem
  have hpoly : ρ (Polynomial.eval₂RingHom σ a p) =
      Polynomial.eval₂RingHom (ρ.comp σ) (ρ a) p := by
    simpa only [Polynomial.coe_eval₂RingHom] using
      (Polynomial.hom_eval₂ (p := p) (f := σ) (g := ρ) a)
  have hzeroeval : Polynomial.eval₂ (ρ.comp σ) (ρ a) p = 0 := by
    calc
      Polynomial.eval₂ (ρ.comp σ) (ρ a) p =
          ρ (Polynomial.eval₂RingHom σ a p) := by
        simpa only [Polynomial.coe_eval₂RingHom] using hpoly.symm
      _ = 0 := hzeroρ
  have hzero : Polynomial.aeval b p = 0 := by
    simpa [aeval_def, h.residue_compatibility, h.residue_lift] using hzeroeval
  exact h.transcendental ⟨p, hp, hzero⟩

/-- The fraction field generated by a lifted transcendental element maps into `A`. -/
theorem chapter13_transcendental_fraction_field_lift
    {A : Type u} [CommRing A] [IsLocalRing A]
    {K : Type v} [Field K]
    {k : Type w} [Field k] [Algebra K k]
    {σ : K →+* A} {ρ : A →+* k} {b : k} {a : A}
    (h : Chapter13TranscendentalLiftData A K k σ ρ b a) :
    ∃ ι : FractionRing K[X] →+* A,
      ι.comp (algebraMap K[X] (FractionRing K[X])) =
        Polynomial.eval₂RingHom σ a := by
  let ι : FractionRing K[X] →+* A :=
    IsLocalization.lift (M := nonZeroDivisors K[X]) (S := FractionRing K[X])
      (g := Polynomial.eval₂RingHom σ a) (fun y =>
        chapter13_transcendental_lift_polynomials_are_units h y.1
          (mem_nonZeroDivisors_iff_ne_zero.mp y.2))
  refine ⟨ι, ?_⟩
  exact IsLocalization.lift_comp (M := nonZeroDivisors K[X])
    (S := FractionRing K[X])
    (hg := fun y => chapter13_transcendental_lift_polynomials_are_units h y.1
      (mem_nonZeroDivisors_iff_ne_zero.mp y.2))

/-- A separable residue element has a unique Hensel lift as a root of its minimal polynomial. -/
theorem chapter13_separable_residue_lift
    {A : Type u} [CommRing A] [IsLocalRing A]
    {K : Type v} [Field K]
    {k : Type w} [Field k] [Algebra K k]
    (hA : LastLib.Book01ValuationsDVRsAndCompletions.Chapter09.SimpleResidueRootLiftingProperty A)
    (σ : K →+* A) (ρ : A →+* k)
    (hρ : RingHom.ker ρ = IsLocalRing.maximalIdeal A)
    (hρsurj : Function.Surjective ρ)
    (hσ : ρ.comp σ = algebraMap K k)
    (b : k) (hb : IsSeparable K b) :
    ∃! a : A,
      Polynomial.eval₂RingHom σ a (minpoly K b) = 0 ∧ ρ a = b := by
  obtain ⟨a₀, ha₀⟩ := hρsurj b
  let e : Chapter13ResidueRing A ≃+* k :=
    (Ideal.quotEquivOfEq hρ.symm).trans
      (RingHom.quotientKerEquivOfSurjective hρsurj)
  let f : Polynomial A := (minpoly K b).map σ
  have hf : f.Monic := (minpoly.monic hb.isIntegral).map σ
  have he : e.toRingHom.comp (Chapter09.residueMap A) = ρ := by
    ext y
    simp [e, Chapter09.residueMap,
      Ideal.quotEquivOfEq_mk,
      RingHom.quotientKerEquivOfSurjective_apply_mk]
  have heσ : (e.toRingHom.comp (Chapter09.residueMap A)).comp σ =
      algebraMap K k := by
    rw [he, hσ]
  have heσ' : e.toRingHom.comp ((Chapter09.residueMap A).comp σ) =
      algebraMap K k := by
    simpa only [RingHom.comp_assoc] using heσ
  have heclass : e (Chapter09.residueClass a₀) = b := by
    change (e.toRingHom.comp (Chapter09.residueMap A)) a₀ = b
    rw [he]
    exact ha₀
  have heclass' : e.toRingHom (Chapter09.residueClass a₀) = b := by
    simpa using heclass
  have hroot : (Chapter09.residuePolynomial f).eval (Chapter09.residueClass a₀) = 0 := by
    apply e.injective
    simp only [map_zero]
    change e.toRingHom ((Chapter09.residuePolynomial f).eval
      (Chapter09.residueClass a₀)) = 0
    rw [← Polynomial.eval_map_apply (p := Chapter09.residuePolynomial f)
      (f := e.toRingHom)]
    simp only [Chapter09.residuePolynomial, f, Polynomial.map_map]
    rw [Polynomial.eval_map]
    rw [heσ', heclass']
    exact minpoly.aeval K b
  have hsimple : IsUnit ((Chapter09.residuePolynomial f).derivative.eval
      (Chapter09.residueClass a₀)) := by
    apply isUnit_iff_ne_zero.mpr
    intro hz
    have hz' := congrArg e hz
    change e.toRingHom ((Chapter09.residuePolynomial f).derivative.eval
      (Chapter09.residueClass a₀)) = e.toRingHom 0 at hz'
    rw [← Polynomial.eval_map_apply (p := (Chapter09.residuePolynomial f).derivative)
      (f := e.toRingHom)] at hz'
    simp only [Chapter09.residuePolynomial, f, Polynomial.map_map,
      Polynomial.derivative_map] at hz'
    rw [Polynomial.eval_map] at hz'
    apply (hb.eval₂_derivative_ne_zero (algebraMap K k)
      (minpoly.aeval K b))
    rw [heσ', heclass'] at hz'
    simpa using hz'
  obtain ⟨a, ha, hres⟩ := hA f (Chapter09.residueClass a₀) hf hroot hsimple
  have hρa : ρ a = b := by
    calc
      ρ a = e (Chapter09.residueClass a) := by
        symm
        simp [e, Chapter09.residueClass, Chapter09.residueMap,
          Ideal.quotEquivOfEq_mk,
          RingHom.quotientKerEquivOfSurjective_apply_mk]
      _ = e (Chapter09.residueClass a₀) := by rw [ha.2]
      _ = ρ a₀ := by
        simp [e, Chapter09.residueClass, Chapter09.residueMap,
          Ideal.quotEquivOfEq_mk,
          RingHom.quotientKerEquivOfSurjective_apply_mk]
      _ = b := ha₀
  refine ⟨a, ?_, ?_⟩
  · constructor
    · simpa [f, Polynomial.eval_map] using ha.1
    · exact hρa
  · intro a' ha'
    refine (hA f (Chapter09.residueClass a₀) hf hroot hsimple).unique ?_ ha
    constructor
    · simpa [f, Polynomial.eval_map] using ha'.1
    · apply e.injective
      calc
        e (Chapter09.residueClass a') = ρ a' := by
          simp [e, Chapter09.residueClass, Chapter09.residueMap,
            Ideal.quotEquivOfEq_mk,
            RingHom.quotientKerEquivOfSurjective_apply_mk]
        _ = b := ha'.2
        _ = ρ a₀ := ha₀.symm
        _ = e (Chapter09.residueClass a₀) := by
          symm
          simp [e, Chapter09.residueClass, Chapter09.residueMap,
            Ideal.quotEquivOfEq_mk,
            RingHom.quotientKerEquivOfSurjective_apply_mk]

/-- A separable algebraic residue extension is already a field after adjoining one element. -/
theorem chapter13_separable_adjoin_is_field
    {K k : Type u} [Field K] [Field k] [Algebra K k]
    (b : k) (hb : IsSeparable K b) :
    IsField (Algebra.adjoin K ({b} : Set k)) := by
  let : Algebra.IsIntegral K (Algebra.adjoin K ({b} : Set k)) :=
    Algebra.IsIntegral.adjoin (by
      intro x hx
      rw [Set.mem_singleton_iff.mp hx]
      exact hb.isIntegral)
  exact isField_of_isIntegral_of_isField' (R := K)
    (S := Algebra.adjoin K ({b} : Set k)) (Field.toIsField K)

/-- A complete local ring of residue characteristic zero contains a coefficient field. -/
theorem chapter13_coefficient_field_exists_equal_characteristic_zero
    {A : Type u} [CommRing A] [IsLocalRing A]
    (hA : IsAdicComplete (IsLocalRing.maximalIdeal A) A)
    (hchar : CharP (Chapter13ResidueRing A) 0)
    (hcontains : Chapter13ContainsField A) :
    (∃ K : Chapter13Subfield A, Chapter13IsCoefficientField K) ∧
      (∀ K : Chapter13Subfield A,
        Chapter13IsMaximalSubfield K → Chapter13IsCoefficientField K) ∧
      (∀ K : Chapter13Subfield A,
        ∃ L : Chapter13Subfield A,
          K.carrier ≤ L.carrier ∧ Chapter13IsCoefficientField L) := by
  sorry

end

end LastLib.Book01ValuationsDVRsAndCompletions.Chapter13
