import LastLib.Book01ValuationsDVRsAndCompletions.Chapter13.Section01CoordinatesForACompleteLocalRing
import Mathlib.RingTheory.Algebraic.Basic
import Mathlib.RingTheory.AlgebraicIndependent.Basic
import Mathlib.RingTheory.Localization.FractionRing

namespace LastLib.Book01ValuationsDVRsAndCompletions.Chapter13

open Filter Ideal IsLocalRing Polynomial
open scoped Polynomial

noncomputable section

/-! # Book 1, Chapter 13, Section 13.2: Coefficient fields in equal characteristic zero -/

universe u v w

/-- A chosen field presentation of the residue ring. -/
structure Chapter13ResidueFieldPresentation
    (A : Type u) [CommRing A] [IsLocalRing A]
    (k : Type v) [Field k] where
  equiv : Chapter13ResidueRing A ≃+* k

/-- Every subfield of a local ring reduces injectively to its residue field. -/
theorem chapter13_subfield_reduction_injective
    {A : Type u} [CommRing A] [IsLocalRing A]
    (K : Chapter13Subfield A) :
    Function.Injective ((Chapter13ResidueMap A).comp K.carrier.subtype) := by
  sorry

/-- The data used to lift a transcendental residue element. -/
structure Chapter13TranscendentalLiftData
    (A : Type u) [CommRing A] [IsLocalRing A]
    (K : Type v) [Field K]
    (k : Type w) [Field k] [Algebra K k]
    (σ : K →+* A) (ρ : A →+* k) (b : k) (a : A) : Prop where
  residue_kernel : RingHom.ker ρ = IsLocalRing.maximalIdeal A
  residue_compatibility : ρ.comp σ = algebraMap K k
  residue_lift : ρ a = b
  transcendental : Transcendental K b

/-- Nonzero polynomials in a lifted transcendental element are units. -/
theorem chapter13_transcendental_lift_polynomials_are_units
    {A : Type u} [CommRing A] [IsLocalRing A]
    {K : Type v} [Field K]
    {k : Type w} [Field k] [Algebra K k]
    {σ : K →+* A} {ρ : A →+* k} {b : k} {a : A}
    (h : Chapter13TranscendentalLiftData A K k σ ρ b a) :
    ∀ p : K[X], p ≠ 0 → IsUnit (Polynomial.eval₂RingHom σ a p) := by
  sorry

/-- The fraction field generated by a lifted transcendental element maps into `A`. -/
theorem chapter13_transcendental_fraction_field_lift
    {A : Type u} [CommRing A] [IsLocalRing A]
    {K : Type v} [Field K]
    {k : Type w} [Field k] [Algebra K k]
    {σ : K →+* A} {ρ : A →+* k} {b : k} {a : A}
    (h : Chapter13TranscendentalLiftData A K k σ ρ b a) :
    ∃ ι : FractionRing K[X] →+* A,
      ι.comp (algebraMap K[X] (FractionRing K[X])) =
        Polynomial.eval₂RingHom σ a := by
  sorry

/-- A separable residue element has a unique Hensel lift as a root of its minimal polynomial. -/
theorem chapter13_separable_residue_lift
    {A : Type u} [CommRing A] [IsLocalRing A]
    {K : Type v} [Field K]
    {k : Type w} [Field k] [Algebra K k]
    (hA : LastLib.Book01ValuationsDVRsAndCompletions.Chapter09.SimpleResidueRootLiftingProperty A)
    (σ : K →+* A) (ρ : A →+* k)
    (hρ : RingHom.ker ρ = IsLocalRing.maximalIdeal A)
    (hσ : ρ.comp σ = algebraMap K k)
    (b : k) (hb : IsSeparable K b) :
    ∃! a : A,
      Polynomial.eval₂RingHom σ a (minpoly K b) = 0 ∧ ρ a = b := by
  sorry

/-- A separable algebraic residue extension is already a field after adjoining one element. -/
theorem chapter13_separable_adjoin_is_field
    {K k : Type u} [Field K] [Field k] [Algebra K k]
    (b : k) (hb : IsSeparable K b) :
    IsField (Algebra.adjoin K ({b} : Set k)) := by
  sorry

/-- A complete local ring of residue characteristic zero contains a coefficient field. -/
theorem chapter13_coefficient_field_exists_equal_characteristic_zero
    {A : Type u} [CommRing A] [IsLocalRing A]
    (hA : IsAdicComplete (IsLocalRing.maximalIdeal A) A)
    (hchar : CharP (Chapter13ResidueRing A) 0)
    (hcontains : Chapter13ContainsField A) :
    (∃ K : Chapter13Subfield A, Chapter13IsCoefficientField K) ∧
      (∀ K : Chapter13Subfield A,
        Chapter13IsMaximalSubfield K → Chapter13IsCoefficientField K) ∧
      (∀ K : Chapter13Subfield A,
        ∃ L : Chapter13Subfield A,
          K.carrier ≤ L.carrier ∧ Chapter13IsCoefficientField L) := by
  sorry

end

end LastLib.Book01ValuationsDVRsAndCompletions.Chapter13
