import LastLib.Book01ValuationsDVRsAndCompletions.Chapter13.Section01CoordinatesForACompleteLocalRing
import Mathlib.RingTheory.Algebraic.Basic
import Mathlib.RingTheory.Algebraic.Integral
import Mathlib.RingTheory.AlgebraicIndependent.Basic
import Mathlib.RingTheory.Localization.FractionRing

namespace LastLib.Book01ValuationsDVRsAndCompletions.Chapter13

open Filter Ideal IsLocalRing Polynomial
open scoped Polynomial

noncomputable section

/-! # Book 1, Chapter 13, Section 13.2: Coefficient fields in equal characteristic zero -/

universe u v w

/-- A chosen field presentation of the residue ring. -/
structure Chapter13ResidueFieldPresentation
    (A : Type u) [CommRing A] [IsLocalRing A]
    (k : Type v) [Field k] where
  equiv : Chapter13ResidueRing A ≃+* k

/-- Every subfield of a local ring reduces injectively to its residue field. -/
theorem chapter13_subfield_reduction_injective
    {A : Type u} [CommRing A] [IsLocalRing A]
    (K : Chapter13Subfield A) :
    Function.Injective ((Chapter13ResidueMap A).comp K.carrier.subtype) := by
  let : Field K.carrier := K.field_carrier.toField
  intro x y hxy
  have hz : Chapter13ResidueMap A (K.carrier.subtype x - K.carrier.subtype y) = 0 := by
    rw [map_sub, sub_eq_zero]
    exact hxy
  have hm : K.carrier.subtype x - K.carrier.subtype y ∈ IsLocalRing.maximalIdeal A := by
    change Ideal.Quotient.mk _ (K.carrier.subtype x - K.carrier.subtype y) = 0 at hz
    exact (Ideal.Quotient.eq_zero_iff_mem).mp hz
  have heq : K.carrier.subtype x = K.carrier.subtype y := by
    by_contra hne
    have hxy' : x ≠ y := fun h => hne (congrArg K.carrier.subtype h)
    have hu' : IsUnit (x - y) := isUnit_iff_ne_zero.mpr (sub_ne_zero.mpr hxy')
    have hu : IsUnit (K.carrier.subtype x - K.carrier.subtype y) := by
      simpa using IsUnit.map K.carrier.subtype hu'
    exact (IsLocalRing.notMem_maximalIdeal.mpr hu) hm
  exact K.carrier.subtype_injective heq

/-- The data used to lift a transcendental residue element. -/
structure Chapter13TranscendentalLiftData
    (A : Type u) [CommRing A] [IsLocalRing A]
    (K : Type v) [Field K]
    (k : Type w) [Field k] [Algebra K k]
    (σ : K →+* A) (ρ : A →+* k) (b : k) (a : A) : Prop where
  residue_kernel : RingHom.ker ρ = IsLocalRing.maximalIdeal A
  residue_compatibility : ρ.comp σ = algebraMap K k
  residue_lift : ρ a = b
  transcendental : Transcendental K b

/-- Nonzero polynomials in a lifted transcendental element are units. -/
theorem chapter13_transcendental_lift_polynomials_are_units
    {A : Type u} [CommRing A] [IsLocalRing A]
    {K : Type v} [Field K]
    {k : Type w} [Field k] [Algebra K k]
    {σ : K →+* A} {ρ : A →+* k} {b : k} {a : A}
    (h : Chapter13TranscendentalLiftData A K k σ ρ b a) :
    ∀ p : K[X], p ≠ 0 → IsUnit (Polynomial.eval₂RingHom σ a p) := by
  intro p hp
  by_contra hunit
  have hmem : Polynomial.eval₂RingHom σ a p ∈ IsLocalRing.maximalIdeal A := by
    by_contra hnotmem
    exact hunit (IsLocalRing.notMem_maximalIdeal.mp hnotmem)
  have hzeroρ : ρ (Polynomial.eval₂RingHom σ a p) = 0 := by
    change Polynomial.eval₂RingHom σ a p ∈ RingHom.ker ρ
    rw [h.residue_kernel]
    exact hmem
  have hpoly : ρ (Polynomial.eval₂RingHom σ a p) =
      Polynomial.eval₂RingHom (ρ.comp σ) (ρ a) p := by
    simpa only [Polynomial.coe_eval₂RingHom] using
      (Polynomial.hom_eval₂ (p := p) (f := σ) (g := ρ) a)
  have hzeroeval : Polynomial.eval₂ (ρ.comp σ) (ρ a) p = 0 := by
    calc
      Polynomial.eval₂ (ρ.comp σ) (ρ a) p =
          ρ (Polynomial.eval₂RingHom σ a p) := by
        simpa only [Polynomial.coe_eval₂RingHom] using hpoly.symm
      _ = 0 := hzeroρ
  have hzero : Polynomial.aeval b p = 0 := by
    simpa [aeval_def, h.residue_compatibility, h.residue_lift] using hzeroeval
  exact h.transcendental ⟨p, hp, hzero⟩

/-- The fraction field generated by a lifted transcendental element maps into `A`. -/
theorem chapter13_transcendental_fraction_field_lift
    {A : Type u} [CommRing A] [IsLocalRing A]
    {K : Type v} [Field K]
    {k : Type w} [Field k] [Algebra K k]
    {σ : K →+* A} {ρ : A →+* k} {b : k} {a : A}
    (h : Chapter13TranscendentalLiftData A K k σ ρ b a) :
    ∃ ι : FractionRing K[X] →+* A,
      ι.comp (algebraMap K[X] (FractionRing K[X])) =
        Polynomial.eval₂RingHom σ a := by
  let ι : FractionRing K[X] →+* A :=
    IsLocalization.lift (M := nonZeroDivisors K[X]) (S := FractionRing K[X])
      (g := Polynomial.eval₂RingHom σ a) (fun y =>
        chapter13_transcendental_lift_polynomials_are_units h y.1
          (mem_nonZeroDivisors_iff_ne_zero.mp y.2))
  refine ⟨ι, ?_⟩
  exact IsLocalization.lift_comp (M := nonZeroDivisors K[X])
    (S := FractionRing K[X])
    (hg := fun y => chapter13_transcendental_lift_polynomials_are_units h y.1
      (mem_nonZeroDivisors_iff_ne_zero.mp y.2))

/-- A separable residue element has a unique Hensel lift as a root of its minimal polynomial. -/
theorem chapter13_separable_residue_lift
    {A : Type u} [CommRing A] [IsLocalRing A]
    {K : Type v} [Field K]
    {k : Type w} [Field k] [Algebra K k]
    (hA : LastLib.Book01ValuationsDVRsAndCompletions.Chapter09.SimpleResidueRootLiftingProperty A)
    (σ : K →+* A) (ρ : A →+* k)
    (hρ : RingHom.ker ρ = IsLocalRing.maximalIdeal A)
    (hρsurj : Function.Surjective ρ)
    (hσ : ρ.comp σ = algebraMap K k)
    (b : k) (hb : IsSeparable K b) :
    ∃! a : A,
      Polynomial.eval₂RingHom σ a (minpoly K b) = 0 ∧ ρ a = b := by
  obtain ⟨a₀, ha₀⟩ := hρsurj b
  let e : Chapter13ResidueRing A ≃+* k :=
    (Ideal.quotEquivOfEq hρ.symm).trans
      (RingHom.quotientKerEquivOfSurjective hρsurj)
  let f : Polynomial A := (minpoly K b).map σ
  have hf : f.Monic := (minpoly.monic hb.isIntegral).map σ
  have he : e.toRingHom.comp (Chapter09.residueMap A) = ρ := by
    ext y
    simp [e, Chapter09.residueMap,
      Ideal.quotEquivOfEq_mk,
      RingHom.quotientKerEquivOfSurjective_apply_mk]
  have heσ : (e.toRingHom.comp (Chapter09.residueMap A)).comp σ =
      algebraMap K k := by
    rw [he, hσ]
  have heσ' : e.toRingHom.comp ((Chapter09.residueMap A).comp σ) =
      algebraMap K k := by
    simpa only [RingHom.comp_assoc] using heσ
  have heclass : e (Chapter09.residueClass a₀) = b := by
    change (e.toRingHom.comp (Chapter09.residueMap A)) a₀ = b
    rw [he]
    exact ha₀
  have heclass' : e.toRingHom (Chapter09.residueClass a₀) = b := by
    simpa using heclass
  have hroot : (Chapter09.residuePolynomial f).eval (Chapter09.residueClass a₀) = 0 := by
    apply e.injective
    simp only [map_zero]
    change e.toRingHom ((Chapter09.residuePolynomial f).eval
      (Chapter09.residueClass a₀)) = 0
    rw [← Polynomial.eval_map_apply (p := Chapter09.residuePolynomial f)
      (f := e.toRingHom)]
    simp only [Chapter09.residuePolynomial, f, Polynomial.map_map]
    rw [Polynomial.eval_map]
    rw [heσ', heclass']
    exact minpoly.aeval K b
  have hsimple : IsUnit ((Chapter09.residuePolynomial f).derivative.eval
      (Chapter09.residueClass a₀)) := by
    apply isUnit_iff_ne_zero.mpr
    intro hz
    have hz' := congrArg e hz
    change e.toRingHom ((Chapter09.residuePolynomial f).derivative.eval
      (Chapter09.residueClass a₀)) = e.toRingHom 0 at hz'
    rw [← Polynomial.eval_map_apply (p := (Chapter09.residuePolynomial f).derivative)
      (f := e.toRingHom)] at hz'
    simp only [Chapter09.residuePolynomial, f, Polynomial.map_map,
      Polynomial.derivative_map] at hz'
    rw [Polynomial.eval_map] at hz'
    apply (hb.eval₂_derivative_ne_zero (algebraMap K k)
      (minpoly.aeval K b))
    rw [heσ', heclass'] at hz'
    simpa using hz'
  obtain ⟨a, ha, hres⟩ := hA f (Chapter09.residueClass a₀) hf hroot hsimple
  have hρa : ρ a = b := by
    calc
      ρ a = e (Chapter09.residueClass a) := by
        symm
        simp [e, Chapter09.residueClass, Chapter09.residueMap,
          Ideal.quotEquivOfEq_mk,
          RingHom.quotientKerEquivOfSurjective_apply_mk]
      _ = e (Chapter09.residueClass a₀) := by rw [ha.2]
      _ = ρ a₀ := by
        simp [e, Chapter09.residueClass, Chapter09.residueMap,
          Ideal.quotEquivOfEq_mk,
          RingHom.quotientKerEquivOfSurjective_apply_mk]
      _ = b := ha₀
  refine ⟨a, ?_, ?_⟩
  · constructor
    · simpa [f, Polynomial.eval_map] using ha.1
    · exact hρa
  · intro a' ha'
    refine (hA f (Chapter09.residueClass a₀) hf hroot hsimple).unique ?_ ha
    constructor
    · simpa [f, Polynomial.eval_map] using ha'.1
    · apply e.injective
      calc
        e (Chapter09.residueClass a') = ρ a' := by
          simp [e, Chapter09.residueClass, Chapter09.residueMap,
            Ideal.quotEquivOfEq_mk,
            RingHom.quotientKerEquivOfSurjective_apply_mk]
        _ = b := ha'.2
        _ = ρ a₀ := ha₀.symm
        _ = e (Chapter09.residueClass a₀) := by
          symm
          simp [e, Chapter09.residueClass, Chapter09.residueMap,
            Ideal.quotEquivOfEq_mk,
            RingHom.quotientKerEquivOfSurjective_apply_mk]

/-- A separable algebraic residue extension is already a field after adjoining one element. -/
theorem chapter13_separable_adjoin_is_field
    {K k : Type u} [Field K] [Field k] [Algebra K k]
    (b : k) (hb : IsSeparable K b) :
    IsField (Algebra.adjoin K ({b} : Set k)) := by
  let : Algebra.IsIntegral K (Algebra.adjoin K ({b} : Set k)) :=
    Algebra.IsIntegral.adjoin (by
      intro x hx
      rw [Set.mem_singleton_iff.mp hx]
      exact hb.isIntegral)
  exact isField_of_isIntegral_of_isField' (R := K)
    (S := Algebra.adjoin K ({b} : Set k)) (Field.toIsField K)

private def chapter13_subfield_of_field_hom
    {F A : Type*} [Field F] [CommRing A] [Nontrivial A]
    (f : F →+* A) : Chapter13Subfield A :=
  { carrier := f.range
    field_carrier :=
      { exists_pair_ne := by
          refine ⟨⟨f 0, ⟨0, rfl⟩⟩, ⟨f 1, ⟨1, rfl⟩⟩, ?_⟩
          simp
        mul_comm := by
          intro x y
          apply Subtype.ext
          exact mul_comm x.1 y.1
        mul_inv_cancel := by
          intro x hx
          rcases x.property with ⟨y, hyx⟩
          have hy : y ≠ 0 := by
            intro hy
            apply hx
            apply Subtype.ext
            simpa [hy] using hyx.symm
          refine ⟨⟨f y⁻¹, ⟨y⁻¹, rfl⟩⟩, ?_⟩
          apply Subtype.ext
          calc
            x.1 * f y⁻¹ = f y * f y⁻¹ := by rw [hyx]
            _ = 1 := by simpa using congrArg f (mul_inv_cancel₀ hy) } }

/-- A complete local ring of residue characteristic zero contains a coefficient field. -/
theorem chapter13_coefficient_field_exists_equal_characteristic_zero
    {A : Type u} [CommRing A] [IsLocalRing A]
    (hA : IsAdicComplete (IsLocalRing.maximalIdeal A) A)
    (hchar : CharP (Chapter13ResidueRing A) 0)
    (hcontains : Chapter13ContainsField A) :
    (∃ K : Chapter13Subfield A, Chapter13IsCoefficientField K) ∧
      (∀ K : Chapter13Subfield A,
        Chapter13IsMaximalSubfield K → Chapter13IsCoefficientField K) ∧
      (∀ K : Chapter13Subfield A,
        ∃ L : Chapter13Subfield A,
          K.carrier ≤ L.carrier ∧ Chapter13IsCoefficientField L) := by
  let : Preorder (Chapter13Subfield A) :=
    { le := fun K L => K.carrier ≤ L.carrier
      le_refl := fun K => le_rfl
      le_trans := fun _ _ _ hKL hLM => hKL.trans hLM }
  have hmaximal_extension : ∀ K₀ : Chapter13Subfield A,
      ∃ K : Chapter13Subfield A,
        K₀.carrier ≤ K.carrier ∧ Chapter13IsMaximalSubfield K := by
    intro K₀
    obtain ⟨K, hK, hKmax⟩ := zorn_le_nonempty_Ici₀ K₀
      (fun c hc hchain y hy => by
        let U : Set A := ⋃ K : Chapter13Subfield A,
          ⋃ (_ : K ∈ c), (K.carrier : Set A)
        have memU : ∀ {x : A}, x ∈ U → ∃ K ∈ c, x ∈ K.carrier := by
          intro x hx
          change x ∈ ⋃ K : Chapter13Subfield A,
            ⋃ (_ : K ∈ c), (K.carrier : Set A) at hx
          rcases Set.mem_iUnion.mp hx with ⟨K, hx⟩
          rcases Set.mem_iUnion.mp hx with ⟨hK, hx⟩
          exact ⟨K, hK, hx⟩
        have memU' : ∀ {K : Chapter13Subfield A}, K ∈ c →
            ∀ {x : A}, x ∈ K.carrier → x ∈ U := by
          intro K hK x hx
          change x ∈ ⋃ K : Chapter13Subfield A,
            ⋃ (_ : K ∈ c), (K.carrier : Set A)
          exact Set.mem_iUnion.2 ⟨K, Set.mem_iUnion.2 ⟨hK, hx⟩⟩
        let Ucarrier : Subring A :=
          { carrier := U
            zero_mem' := memU' hy (zero_mem y.carrier)
            add_mem' := by
              intro x z hx hz
              obtain ⟨Kx, hKx, hx⟩ := memU hx
              obtain ⟨Kz, hKz, hz⟩ := memU hz
              have hcomp : Kx ≤ Kz ∨ Kz ≤ Kx := by
                by_cases heq : Kx = Kz
                · subst Kz
                  exact Or.inl le_rfl
                · exact hchain hKx hKz heq
              rcases hcomp with hle | hle
              · exact memU' hKz (Kz.carrier.add_mem (hle hx) hz)
              · exact memU' hKx (Kx.carrier.add_mem hx (hle hz))
            one_mem' := memU' hy (one_mem y.carrier)
            mul_mem' := by
              intro x z hx hz
              obtain ⟨Kx, hKx, hx⟩ := memU hx
              obtain ⟨Kz, hKz, hz⟩ := memU hz
              have hcomp : Kx ≤ Kz ∨ Kz ≤ Kx := by
                by_cases heq : Kx = Kz
                · subst Kz
                  exact Or.inl le_rfl
                · exact hchain hKx hKz heq
              rcases hcomp with hle | hle
              · exact memU' hKz (Kz.carrier.mul_mem (hle hx) hz)
              · exact memU' hKx (Kx.carrier.mul_mem hx (hle hz))
            neg_mem' := by
              intro x hx
              obtain ⟨Kx, hKx, hx⟩ := memU hx
              exact memU' hKx (Kx.carrier.neg_mem hx) }
        let : Field y.carrier := y.field_carrier.toField
        have hUfield : IsField Ucarrier :=
          { exists_pair_ne := by
              obtain ⟨x, z, hxz⟩ := y.field_carrier.exists_pair_ne
              refine ⟨⟨x, memU' hy x.property⟩, ⟨z, memU' hy z.property⟩, ?_⟩
              intro heq
              apply hxz
              apply Subtype.ext
              exact congrArg (fun w : Ucarrier => w.1) heq
            mul_comm := by
              intro x z
              apply Subtype.ext
              exact mul_comm x.1 z.1
            mul_inv_cancel := by
              intro x hx
              obtain ⟨Kx, hKx, hxK⟩ := memU x.property
              let xK : Kx.carrier := ⟨x.1, hxK⟩
              have hxK0 : xK ≠ 0 := by
                intro hzero
                apply hx
                apply Subtype.ext
                exact congrArg (fun w : Kx.carrier => w.1) hzero
              obtain ⟨z, hz⟩ := Kx.field_carrier.mul_inv_cancel hxK0
              refine ⟨⟨z.1, memU' hKx z.property⟩, ?_⟩
              apply Subtype.ext
              simpa using congrArg Subtype.val hz }
        let Usub : Chapter13Subfield A :=
          { carrier := Ucarrier, field_carrier := hUfield }
        refine ⟨Usub, ?_⟩
        intro z hz
        exact fun x hx => memU' hz hx) K₀ le_rfl
    refine ⟨K, hK, ?_⟩
    intro L hKL
    exact hKmax hKL
  have hmaximal_is_coefficient : ∀ K : Chapter13Subfield A,
      Chapter13IsMaximalSubfield K → Chapter13IsCoefficientField K := by
    intro K hKmax
    let : Field K.carrier := K.field_carrier.toField
    have hKchar : CharP K.carrier 0 :=
      ((Chapter13ResidueMap A).comp K.carrier.subtype).charP_iff_charP 0 |>.mpr hchar
    let : CharP K.carrier 0 := hKchar
    let : CharZero K.carrier := CharP.charP_to_charZero K.carrier
    refine ⟨chapter13_subfield_reduction_injective K, ?_⟩
    intro b
    by_contra hb
    have hb' : b ∉ Set.range
        ((Chapter13ResidueMap A).comp K.carrier.subtype) := hb
    obtain ⟨a, ha⟩ := Ideal.Quotient.mk_surjective b
    let σ : K.carrier →+* A := K.carrier.subtype
    let ρ : A →+* Chapter13ResidueRing A := Chapter13ResidueMap A
    have haρ : ρ a = b := by
      change Ideal.Quotient.mk (IsLocalRing.maximalIdeal A) a = b
      exact ha
    let : Algebra K.carrier (Chapter13ResidueRing A) :=
      (ρ.comp σ).toAlgebra
    have hσ : ρ.comp σ = algebraMap K.carrier (Chapter13ResidueRing A) := by
      rfl
    have hρ : RingHom.ker ρ = IsLocalRing.maximalIdeal A := by
      change RingHom.ker (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A)) =
        IsLocalRing.maximalIdeal A
      exact Ideal.mk_ker
    by_cases hbtrans : Transcendental K.carrier b
    · obtain ⟨ι, hι⟩ := chapter13_transcendental_fraction_field_lift
          (Chapter13TranscendentalLiftData.mk hρ hσ haρ hbtrans)
      let L := chapter13_subfield_of_field_hom ι
      have hKL : K.carrier ≤ L.carrier := by
        intro x hx
        let xK : K.carrier := ⟨x, hx⟩
        change σ xK ∈ RingHom.range ι
        refine ⟨algebraMap K.carrier[X] (FractionRing K.carrier[X])
          (Polynomial.C xK), ?_⟩
        have hx' := congrArg (fun f => f (Polynomial.C xK)) hι
        simpa [σ, Polynomial.eval₂RingHom] using hx'
      have haL : a ∈ L.carrier := by
        change a ∈ RingHom.range ι
        refine ⟨algebraMap K.carrier[X] (FractionRing K.carrier[X]) Polynomial.X, ?_⟩
        have ha' := congrArg (fun f => f Polynomial.X) hι
        simpa [ρ, σ, Polynomial.eval₂RingHom] using ha'
      have hnot : ¬L.carrier ≤ K.carrier := by
        intro hLK
        have haK : a ∈ K.carrier := hLK haL
        let x : K.carrier := ⟨a, haK⟩
        apply hb'
        refine ⟨x, ?_⟩
        simpa [x, σ, ρ] using haρ
      exact hnot (hKmax L hKL)
    · have hbalg : IsAlgebraic K.carrier b := by
        exact not_not.mp hbtrans
      have hminpoly : Irreducible (minpoly K.carrier b) :=
        minpoly.irreducible hbalg.isIntegral
      let : Fact (Irreducible (minpoly K.carrier b)) := ⟨hminpoly⟩
      have hsep : IsSeparable K.carrier b := by
        unfold IsSeparable
        exact hminpoly.separable
      have hsimple :
          LastLib.Book01ValuationsDVRsAndCompletions.Chapter09.SimpleResidueRootLiftingProperty A := by
        let : HenselianLocalRing A :=
          Chapter09.complete_separated_local_ring_has_simple_root_henselianity hA
        exact (Chapter09.mathlib_henselian_iff_simple_residue_root_lifting (A := A)).mp
          inferInstance
      obtain ⟨a, ha_root, _ha_res⟩ := chapter13_separable_residue_lift
        hsimple σ ρ hρ Ideal.Quotient.mk_surjective hσ b hsep
      let ψ : AdjoinRoot (minpoly K.carrier b) →+* A :=
        AdjoinRoot.lift σ a (by
          simpa [Polynomial.eval₂RingHom] using ha_root.1)
      let L := chapter13_subfield_of_field_hom ψ
      have hKL : K.carrier ≤ L.carrier := by
        intro x hx
        let xK : K.carrier := ⟨x, hx⟩
        change σ xK ∈ RingHom.range ψ
        refine ⟨AdjoinRoot.of (minpoly K.carrier b) xK, ?_⟩
        simp [ψ]
      have haL : a ∈ L.carrier := by
        change a ∈ RingHom.range ψ
        refine ⟨AdjoinRoot.root (minpoly K.carrier b), ?_⟩
        simp [ψ]
      have hnot : ¬L.carrier ≤ K.carrier := by
        intro hLK
        have haK : a ∈ K.carrier := hLK haL
        let x : K.carrier := ⟨a, haK⟩
        apply hb'
        refine ⟨x, ?_⟩
        simpa [x, σ, ρ] using ha_root.2
      exact hnot (hKmax L hKL)
  obtain ⟨K₀⟩ := hcontains
  obtain ⟨K, hK₀, hKmax⟩ := hmaximal_extension K₀
  have hKcoeff := hmaximal_is_coefficient K hKmax
  refine ⟨⟨K, hKcoeff⟩, ?_, ?_⟩
  · intro K hKmax'
    exact hmaximal_is_coefficient K hKmax'
  · intro K
    obtain ⟨L, hKL, hLmax⟩ := hmaximal_extension K
    exact ⟨L, hKL, hmaximal_is_coefficient L hLmax⟩

end

end LastLib.Book01ValuationsDVRsAndCompletions.Chapter13
