import LastLib.Book01ValuationsDVRsAndCompletions.Chapter13.Section02CoefficientFieldsInEqualCharacteristicZero
import Mathlib.Algebra.CharP.Frobenius
import Mathlib.Algebra.MvPolynomial.Eval
import Mathlib.LinearAlgebra.Basis.Basic
import Mathlib.LinearAlgebra.Dimension.Finite
import Mathlib.RingTheory.Derivation.ToSquareZero

namespace LastLib.Book01ValuationsDVRsAndCompletions.Chapter13

open Filter Ideal IsLocalRing
open Module
open scoped BigOperators Polynomial

noncomputable section

/-! # Book 1, Chapter 13, Section 13.3: `p`-bases and derivations -/

universe u v

/-- The subfield generated by the `p`-th powers in a field. -/
def Chapter13PthPowerSubfield (k : Type u) [Field k] (p : ℕ) : Subfield k :=
  Subfield.closure (Set.range (fun x : k => x ^ p))

/-- A finite-support exponent vector whose entries are all less than `p`. -/
def Chapter13PMonomialIndex (ι : Type u) (p : ℕ) :=
  {e : ι →₀ ℕ // ∀ i, e i < p}

/-- The `p`-monomial associated to an exponent vector. -/
def Chapter13PMonomial
    {k : Type u} [CommSemiring k] {ι : Type v} {p : ℕ}
    (b : ι → k) (e : Chapter13PMonomialIndex ι p) : k :=
  Finset.prod e.1.support (fun i => b i ^ e.1 i)

/-- `p`-independence: all finite families of `p`-monomials are linearly independent. -/
def Chapter13PIndependent
    {k : Type u} [Field k] (F : Subfield k) (B : Set k) (p : ℕ) : Prop :=
  ∀ (r : ℕ) (b : Fin r → k), Set.range b ⊆ B → Function.Injective b →
    LinearIndependent F
      (fun e : Chapter13PMonomialIndex (Fin r) p => Chapter13PMonomial b e)

/-- The span condition saying that a family of `p`-monomials generates the field. -/
def Chapter13PMonomialsSpan
    {k : Type u} [Field k] (F : Subfield k) (B : Set k) (p : ℕ) : Prop :=
  Submodule.span F
      (Set.range (fun e : Chapter13PMonomialIndex B p =>
        Chapter13PMonomial (fun b : B => (b : k)) e)) = ⊤

/-- A `p`-basis relative to a chosen base subfield. -/
def Chapter13PBasis
    {k : Type u} [Field k] (F : Subfield k) (B : Set k) (p : ℕ) : Prop :=
  Chapter13PIndependent F B p ∧ Chapter13PMonomialsSpan F B p

/-- Maximality among `p`-independent subsets. -/
def Chapter13IsMaximalPIndependent
    {k : Type u} [Field k] (F : Subfield k) (B : Set k) (p : ℕ) : Prop :=
  Chapter13PIndependent F B p ∧
    ∀ B' : Set k, B ⊆ B' → Chapter13PIndependent F B' p → B' = B

/-- The field-theoretic version of being perfect in characteristic `p`. -/
def Chapter13PerfectAtPrime (k : Type u) [Field k] (p : ℕ) : Prop :=
  Function.Surjective (fun x : k => x ^ p)

/-- The degree-one-or-`p` calculation for an intermediate field. -/
theorem chapter13_simple_p_extension_degree
    {k : Type u} [Field k] (p : ℕ) [Fact (Nat.Prime p)] [CharP k p]
    (F : Subfield k)
    (hF : Chapter13PthPowerSubfield k p ≤ F) (b : k) :
    Subalgebra.toSubmodule (Algebra.adjoin F ({b} : Set k)) =
        Submodule.span F (Set.range (fun i : Fin p => b ^ (i : ℕ))) ∧
      FiniteDimensional F (Algebra.adjoin F ({b} : Set k)) ∧
      ((b ∈ F ∧ Module.finrank F (Algebra.adjoin F ({b} : Set k)) = 1) ∨
        (b ∉ F ∧ Module.finrank F (Algebra.adjoin F ({b} : Set k)) = p)) := by
  sorry

/-- Three equivalent formulations of `p`-independence. -/
theorem chapter13_p_independence_three_forms
    {k : Type u} [Field k] (p : ℕ) [Fact (Nat.Prime p)] [CharP k p]
    (B : Set k) :
    (Chapter13PIndependent (Chapter13PthPowerSubfield k p) B p ↔
      (∀ (r : ℕ) (b : Fin r → k), Set.range b ⊆ B → Function.Injective b →
        Module.finrank (Chapter13PthPowerSubfield k p)
          (Algebra.adjoin (Chapter13PthPowerSubfield k p) (Set.range b)) = p ^ r)) ↔
      (∀ b : k, b ∈ B →
        b ∉ Algebra.adjoin (Chapter13PthPowerSubfield k p) (B \ {b})) := by
  sorry

/-- Existence, maximality, and the perfect-field criterion for `p`-bases. -/
theorem chapter13_p_basis_existence
    {k : Type u} [Field k] (p : ℕ) [Fact (Nat.Prime p)] [CharP k p] :
    (∀ B : Set k, Chapter13PIndependent (Chapter13PthPowerSubfield k p) B p →
      ∃ B' : Set k, B ⊆ B' ∧
        Chapter13PBasis (Chapter13PthPowerSubfield k p) B' p) ∧
      (∃ B : Set k, Chapter13PBasis (Chapter13PthPowerSubfield k p) B p) ∧
      (∀ B : Set k,
        Chapter13PBasis (Chapter13PthPowerSubfield k p) B p ↔
          Chapter13IsMaximalPIndependent (Chapter13PthPowerSubfield k p) B p) ∧
      (Chapter13PerfectAtPrime k p ↔
        Chapter13PBasis (Chapter13PthPowerSubfield k p) (∅ : Set k) p) := by
  sorry

/-- The `p`-monomial basis attached to a `p`-basis. -/
theorem chapter13_p_basis_monomial_basis
    {k : Type u} [Field k] (p : ℕ) [Fact (Nat.Prime p)] [CharP k p]
    (B : Set k)
    (hB : Chapter13PBasis (Chapter13PthPowerSubfield k p) B p) :
    ∃ β : Basis (Chapter13PMonomialIndex B p)
        (Chapter13PthPowerSubfield k p) k,
      ∀ e, β e = Chapter13PMonomial (fun b : B => (b : k)) e := by
  sorry

/-- Polynomial presentation and finite-degree formula supplied by a finite `p`-basis. -/
theorem chapter13_p_basis_polynomial_presentation
    {k : Type u} [Field k] (p : ℕ) [Fact (Nat.Prime p)] [CharP k p]
    (B : Set k)
    (hB : Chapter13PBasis (Chapter13PthPowerSubfield k p) B p)
    (c : B → Chapter13PthPowerSubfield k p)
    (hc : ∀ b : B, (c b : k) = (b : k) ^ p) :
    Function.Surjective
        (MvPolynomial.aeval (fun b : B => (b : k)) :
          MvPolynomial B (Chapter13PthPowerSubfield k p) →ₐ[
            Chapter13PthPowerSubfield k p] k) ∧
      RingHom.ker
          (MvPolynomial.aeval (fun b : B => (b : k)) :
            MvPolynomial B (Chapter13PthPowerSubfield k p) →ₐ[
              Chapter13PthPowerSubfield k p] k).toRingHom =
        Ideal.span (Set.range (fun b : B =>
          MvPolynomial.X b ^ p - MvPolynomial.C (c b))) ∧
      (B.Finite →
        FiniteDimensional (Chapter13PthPowerSubfield k p) k ∧
        Module.finrank (Chapter13PthPowerSubfield k p) k = p ^ B.ncard) := by
  sorry

/-- Restriction of a derivation to a chosen `p`-basis. -/
def Chapter13DerivationRestriction
    {k : Type u} [Field k] (p : ℕ) (B : Set k) (M : Type v)
    [AddCommGroup M] [Module k M]
    (D : Derivation (Chapter13PthPowerSubfield k p) k M) : B → M :=
  fun b => D (b : k)

/-- Every prescribed family of values on a `p`-basis extends uniquely to a derivation. -/
theorem chapter13_derivation_extension
    {k : Type u} [Field k] (p : ℕ) [Fact (Nat.Prime p)] [CharP k p]
    (B : Set k)
    (hB : Chapter13PBasis (Chapter13PthPowerSubfield k p) B p)
    (M : Type v) [AddCommGroup M] [Module k M] (δ : B → M) :
    ∃! D : Derivation (Chapter13PthPowerSubfield k p) k M,
      ∀ b : B, D (b : k) = δ b := by
  sorry

/-- Restriction identifies derivations with arbitrary values on a `p`-basis. -/
theorem chapter13_derivation_restriction_bijective
    {k : Type u} [Field k] (p : ℕ) [Fact (Nat.Prime p)] [CharP k p]
    (B : Set k)
    (hB : Chapter13PBasis (Chapter13PthPowerSubfield k p) B p)
    (M : Type v) [AddCommGroup M] [Module k M] :
    Function.Bijective
      (Chapter13DerivationRestriction p B M) := by
  sorry

/-- Lifting a characteristic-`p` field map across a square-zero extension. -/
theorem chapter13_char_p_square_zero_lift
    {R : Type u} [CommRing R]
    {k : Type v} [Field k]
    (p : ℕ) (hp : Nat.Prime p) [CharP R p] [CharP k p]
    (B : Set k)
    (hB : Chapter13PBasis (Chapter13PthPowerSubfield k p) B p)
    (I : Ideal R) (hI : I ^ 2 = ⊥)
    (ψ : k →+* (R ⧸ I)) (β : B → R)
    (hβ : ∀ b : B, Ideal.Quotient.mk I (β b) = ψ (b : k)) :
    ∃! φ : k →+* R,
      (Ideal.Quotient.mk I).comp φ = ψ ∧
        ∀ b : B, φ (b : k) = β b := by
  sorry

/-- Perfect residue fields have no `p`-basis choices. -/
theorem chapter13_perfect_field_empty_p_basis
    {k : Type u} [Field k] (p : ℕ) [Fact (Nat.Prime p)] [CharP k p]
    (hperfect : Chapter13PerfectAtPrime k p) :
    Chapter13PBasis (Chapter13PthPowerSubfield k p) (∅ : Set k) p := by
  sorry

/-- A separable algebraic extension preserves a chosen `p`-basis. -/
theorem chapter13_separable_extension_preserves_p_basis
    {k l : Type u} [Field k] [Field l] [Algebra k l]
    (p : ℕ) [Fact (Nat.Prime p)] [CharP k p] [CharP l p] (B : Set k)
    (hB : Chapter13PBasis (Chapter13PthPowerSubfield k p) B p)
    (hsep : Algebra.IsSeparable k l) :
    Chapter13PBasis (Chapter13PthPowerSubfield l p)
      ((algebraMap k l) '' B) p := by
  sorry

end

end LastLib.Book01ValuationsDVRsAndCompletions.Chapter13
