import LastLib.Book01ValuationsDVRsAndCompletions.Chapter13.Section02CoefficientFieldsInEqualCharacteristicZero
import Mathlib.Algebra.CharP.Frobenius
import Mathlib.Algebra.MvPolynomial.Eval
import Mathlib.LinearAlgebra.Basis.Basic
import Mathlib.LinearAlgebra.Dimension.Finite
import Mathlib.FieldTheory.PurelyInseparable.Exponent
import Mathlib.RingTheory.Adjoin.PowerBasis
import Mathlib.RingTheory.IntegralClosure.IsIntegral.Basic
import Mathlib.RingTheory.Derivation.ToSquareZero

namespace LastLib.Book01ValuationsDVRsAndCompletions.Chapter13

open Filter Ideal IsLocalRing
open Module
open scoped BigOperators Polynomial

noncomputable section

/-! # Book 1, Chapter 13, Section 13.3: `p`-bases and derivations -/

universe u v

/-- The subfield generated by the `p`-th powers in a field. -/
def Chapter13PthPowerSubfield (k : Type u) [Field k] (p : ℕ) : Subfield k :=
  Subfield.closure (Set.range (fun x : k => x ^ p))

/-- A finite-support exponent vector whose entries are all less than `p`. -/
def Chapter13PMonomialIndex (ι : Type u) (p : ℕ) :=
  {e : ι →₀ ℕ // ∀ i, e i < p}

/-- The `p`-monomial associated to an exponent vector. -/
def Chapter13PMonomial
    {k : Type u} [CommSemiring k] {ι : Type v} {p : ℕ}
    (b : ι → k) (e : Chapter13PMonomialIndex ι p) : k :=
  Finset.prod e.1.support (fun i => b i ^ e.1 i)

/-- `p`-independence: all finite families of `p`-monomials are linearly independent. -/
def Chapter13PIndependent
    {k : Type u} [Field k] (F : Subfield k) (B : Set k) (p : ℕ) : Prop :=
  ∀ (r : ℕ) (b : Fin r → k), Set.range b ⊆ B → Function.Injective b →
    LinearIndependent F
      (fun e : Chapter13PMonomialIndex (Fin r) p => Chapter13PMonomial b e)

/-- The span condition saying that a family of `p`-monomials generates the field. -/
def Chapter13PMonomialsSpan
    {k : Type u} [Field k] (F : Subfield k) (B : Set k) (p : ℕ) : Prop :=
  Submodule.span F
      (Set.range (fun e : Chapter13PMonomialIndex B p =>
        Chapter13PMonomial (fun b : B => (b : k)) e)) = ⊤

/-- A `p`-basis relative to a chosen base subfield. -/
def Chapter13PBasis
    {k : Type u} [Field k] (F : Subfield k) (B : Set k) (p : ℕ) : Prop :=
  Chapter13PIndependent F B p ∧ Chapter13PMonomialsSpan F B p

/-- Maximality among `p`-independent subsets. -/
def Chapter13IsMaximalPIndependent
    {k : Type u} [Field k] (F : Subfield k) (B : Set k) (p : ℕ) : Prop :=
  Chapter13PIndependent F B p ∧
    ∀ B' : Set k, B ⊆ B' → Chapter13PIndependent F B' p → B' = B

/-- The field-theoretic version of being perfect in characteristic `p`. -/
def Chapter13PerfectAtPrime (k : Type u) [Field k] (p : ℕ) : Prop :=
  Function.Surjective (fun x : k => x ^ p)

/-- The degree-one-or-`p` calculation for an intermediate field. -/
theorem chapter13_simple_p_extension_degree
    {k : Type u} [Field k] (p : ℕ) [Fact (Nat.Prime p)] [CharP k p]
    (F : Subfield k)
    (hF : Chapter13PthPowerSubfield k p ≤ F) (b : k) :
    Subalgebra.toSubmodule (Algebra.adjoin F ({b} : Set k)) =
        Submodule.span F (Set.range (fun i : Fin p => b ^ (i : ℕ))) ∧
      FiniteDimensional F (Algebra.adjoin F ({b} : Set k)) ∧
      ((b ∈ F ∧ Module.finrank F (Algebra.adjoin F ({b} : Set k)) = 1) ∨
        (b ∉ F ∧ Module.finrank F (Algebra.adjoin F ({b} : Set k)) = p)) := by
  classical
  let bp : F := ⟨b ^ p,
    hF (Subfield.subset_closure ⟨b, rfl⟩)⟩
  have hp0 : p ≠ 0 := (Fact.out : Nat.Prime p).ne_zero
  let f : Polynomial F := Polynomial.X ^ p - Polynomial.C bp
  have hf : f.Monic := by
    dsimp [f]
    exact Polynomial.monic_X_pow_sub_C _ hp0
  have hfx : Polynomial.aeval b f = 0 := by
    have hmap : algebraMap F k bp = (bp : k) :=
      Algebra.algebraMap_ofSubsemiring_apply F bp
    simp [f, hmap, bp]
  have hbint : IsIntegral F b := ⟨f, hf, hfx⟩
  have hspan := Submodule.span_range_natDegree_eq_adjoin hf hfx
  have hnat : f.natDegree = p := by
    simp [f]
  rw [hnat] at hspan
  have himage :
      (↑(Finset.image (fun i : ℕ => b ^ i) (Finset.range p)) : Set k) =
        Set.range (fun i : Fin p => b ^ (i : ℕ)) := by
    ext y
    constructor
    · intro hy
      change y ∈ Finset.image (fun i : ℕ => b ^ i) (Finset.range p) at hy
      rcases Finset.mem_image.mp hy with ⟨i, hi, rfl⟩
      exact ⟨⟨i, Finset.mem_range.mp hi⟩, rfl⟩
    · rintro ⟨i, rfl⟩
      change b ^ (i : ℕ) ∈ Finset.image (fun i : ℕ => b ^ i) (Finset.range p)
      exact Finset.mem_image.mpr
        ⟨(i : ℕ), Finset.mem_range.mpr i.isLt, rfl⟩
  have hsubmodule :
      Subalgebra.toSubmodule (Algebra.adjoin F ({b} : Set k)) =
        Submodule.span F (Set.range (fun i : Fin p => b ^ (i : ℕ))) := by
    rw [← hspan, himage]
  have hfinite : FiniteDimensional F (Algebra.adjoin F ({b} : Set k)) :=
    (Algebra.adjoin.powerBasis hbint).finite
  have hdegree : Module.finrank F (Algebra.adjoin F ({b} : Set k)) =
      (minpoly F b).natDegree := by
    simpa using (PowerBasis.finrank (Algebra.adjoin.powerBasis hbint))
  have hchar : IsPurelyInseparable F k :=
    (isPurelyInseparable_iff_pow_mem F p).mpr (by
      intro x
      let y : F := ⟨x ^ p,
        hF (Subfield.subset_closure ⟨x, rfl⟩)⟩
      refine ⟨1, ⟨y, ?_⟩⟩
      have hmap : algebraMap F k y = (y : k) :=
        Algebra.algebraMap_ofSubsemiring_apply F y
      rw [hmap]
      simp [y])
  let : IsPurelyInseparable F k := hchar
  refine ⟨hsubmodule, hfinite, ?_⟩
  by_cases hbF : b ∈ F
  · left
    have hbot : Algebra.adjoin F ({b} : Set k) = ⊥ := by
      apply le_antisymm
      · apply Algebra.adjoin_le
        intro x hx
        rw [Set.mem_singleton_iff.mp hx]
        change ∃ y : F, algebraMap F k y = b
        exact ⟨⟨b, hbF⟩, rfl⟩
      · exact bot_le
    exact ⟨hbF, by rw [hbot, Subalgebra.finrank_bot]⟩
  · right
    have hdegree_p : (minpoly F b).natDegree = p := by
      have hbp_range : b ^ p ^ (1 : ℕ) ∈ (algebraMap F k).range := by
        simpa using (show b ^ p ∈ (algebraMap F k).range from ⟨bp, rfl⟩)
      have hle : IsPurelyInseparable.elemExponent F b ≤ 1 :=
        IsPurelyInseparable.elemExponent_le_of_pow_mem' (K := F) p
          (n := 1) hbp_range
      have hne : IsPurelyInseparable.elemExponent F b ≠ 0 := by
        intro he
        have hdef := IsPurelyInseparable.elemExponent_def' (K := F) p b
        rw [he] at hdef
        have hbrange : b ∈ (algebraMap F k).range := by
          simpa using hdef
        obtain ⟨c, hc⟩ := hbrange
        exact hbF (by simpa using hc.symm ▸ c.property)
      have he : IsPurelyInseparable.elemExponent F b = 1 := by
        rcases Nat.le_one_iff_eq_zero_or_eq_one.mp hle with h | h
        · exact (hne h).elim
        · exact h
      rw [IsPurelyInseparable.minpoly_natDegree_eq' (K := F) p b, he]
      simp
    exact ⟨hbF, hdegree.trans hdegree_p⟩

/-!
Proof roadmap for `chapter13_p_independence_three_forms`.

The statement below agrees with `Chapter13PIndependent`: both quantify over injective
`Fin r`-indexed subfamilies.  The deletion clause is deliberately about all of `B`, not only a
finite subset; adjoining has finite character, so these formulations are still equivalent when
`B` is infinite.

Two finite-family interfaces should be proved locally before assembling the equivalences (they are
the missing step which `chapter13_simple_p_extension_degree` cannot replace).

1. Prove a cardinality lemma
   `Fintype.card (Chapter13PMonomialIndex (Fin r) p) = p ^ r`.  Reindex through the explicit
   equivalence
   `e |-> fun i => (⟨e.1 i, e.2 i⟩ : Fin p)` with inverse built from
   `Finsupp.equivFunOnFinite.symm`.  Finish with `Fintype.card_congr`, `Fintype.card_pi`, and
   `Fintype.card_fin` (from `Mathlib.Data.Finsupp.Fintype` and
   `Mathlib.Data.Fintype.BigOperators`).  Keep `r` and `p` as `Nat`; no cardinal or universe lift is
   needed.

2. Prove the finite spanning interface, for `F : Subfield k` satisfying
   `Chapter13PthPowerSubfield k p <= F` and `b : Fin r -> k`:

       Submodule.span F
           (Set.range (fun e : Chapter13PMonomialIndex (Fin r) p =>
             Chapter13PMonomial b e)) =
         Subalgebra.toSubmodule (Algebra.adjoin F (Set.range b)).

   Induct on `r`.  Split `Fin (r + 1)` into the first `r` coordinates and `Fin.last r` using
   `finSumFinEquiv`/`Fin.lastCases`, and split the exponent via
   `Finsupp.equivFunOnFinite`.  Apply the induction hypothesis to
   `fun i => b i.castSucc`.  For the last coordinate apply the first conjunct of
   `chapter13_simple_p_extension_degree p F hF (b (Fin.last r))`.  Rewrite the full range as the
   union of the prefix range and the singleton containing the last value, and combine the two
   submodules with `Algebra.adjoin_union_coe_submodule` followed by
   `Submodule.span_mul_span`.  The product of a prefix monomial and the last power is exactly the
   full monomial under the exponent reindexing.  The focused APIs are in
   `Mathlib.FieldTheory.IntermediateField.Adjoin.Algebra`,
   `Mathlib.LinearAlgebra.Dimension.Free`, and `Mathlib.RingTheory.Adjoin.Dimension`; add those
   imports if they are not already transitively available.

With these interfaces, prove the first displayed iff by specializing the spanning equality to the
subtype `Algebra.adjoin F (Set.range b)`.  A spanning family of the cardinality computed in (1) is
linearly independent exactly when its cardinality is the finrank: use
`linearIndependent_iff_card_eq_finrank_span` from
`Mathlib.LinearAlgebra.Dimension.OrzechProperty` (transport the family along the subalgebra subtype,
whose map is injective).  This gives precisely the quantified clause after unfolding only
`Chapter13PIndependent`.

For the second iff, use intermediate fields to make the tower argument explicit.
First factor out the construction already used inside `chapter13_simple_p_extension_degree`:
`(isPurelyInseparable_iff_pow_mem F p).mpr` gives `IsPurelyInseparable F k` because every
`y ^ p` lies in `F = Chapter13PthPowerSubfield k p`; install it locally and obtain
`Algebra.IsAlgebraic F k` from `IsPurelyInseparable.isAlgebraic`.  This is what licenses every
conversion between the two kinds of adjoin below.

* From the finrank formula to deletion, suppose `x in B` also lies in the adjoin of
  `B \\ {x}`.  Rewrite `Algebra.adjoin` as `IntermediateField.adjoin` with
  `IntermediateField.adjoin_toSubalgebra_of_isAlgebraic`.  Apply
  `IntermediateField.exists_finset_of_mem_adjoin` (in
  `Mathlib.FieldTheory.IntermediateField.Adjoin.Basic`) to obtain a finite
  `T subset B \\ {x}` supporting `x`.  Enumerate `T` by
  `fun i => ((T.equivFin.symm i : T) : k)` using `Finset.equivFin` from
  `Mathlib.Data.Fintype.EquivFin`, then append `x` with `Fin.lastCases`; the resulting map on
  `Fin (T.card + 1)` is injective because `x notin T`.
  The two adjoins are equal because `x` already belongs to the first.  The assumed formula gives
  their finranks as `p ^ T.card` and `p ^ (T.card + 1)`, a contradiction using
  `(Fact.out : Nat.Prime p).one_lt`.

* From deletion to the formula, induct on `r`.  For the successor step let
  `b0 i := b i.castSucc`, `x := b (Fin.last r)`, and
  `E := IntermediateField.adjoin F (Set.range b0)`, with
  `F := Chapter13PthPowerSubfield k p`.  Injectivity makes `Set.range b0 subset B \\ {x}`;
  `IntermediateField.adjoin.mono`, the deletion hypothesis, and
  `IntermediateField.adjoin_toSubalgebra_of_isAlgebraic` therefore give `x notin E`.
  Apply `chapter13_simple_p_extension_degree p E.toSubfield _ x` to get relative finrank `p`, use
  `IntermediateField.adjoin_toSubalgebra_of_isAlgebraic` and
  `IntermediateField.adjoin_adjoin_left` to identify adjoining `x` with the full range, and apply
  `Module.finrank_mul_finrank F E (IntermediateField.adjoin E {x})` from
  `Mathlib.LinearAlgebra.Dimension.Free`.  Substitute the induction hypothesis and normalize
  `p ^ (r + 1)` with `pow_succ`.

Finally package the already obtained two iff proofs as `⟨h_independent_iff_degree,
h_degree_iff_delete⟩`.  Do not retry direct unfolding plus the singleton lemma: without the spanning
interface in (2), it provides neither the finite monomial basis nor the successor-step tower
identification.
-/

/-- Three equivalent formulations of `p`-independence. -/
theorem chapter13_p_independence_three_forms
    {k : Type u} [Field k] (p : ℕ) [Fact (Nat.Prime p)] [CharP k p]
    (B : Set k) :
    (Chapter13PIndependent (Chapter13PthPowerSubfield k p) B p ↔
      (∀ (r : ℕ) (b : Fin r → k), Set.range b ⊆ B → Function.Injective b →
        Module.finrank (Chapter13PthPowerSubfield k p)
          (Algebra.adjoin (Chapter13PthPowerSubfield k p) (Set.range b)) = p ^ r)) ∧
      ((∀ (r : ℕ) (b : Fin r → k), Set.range b ⊆ B → Function.Injective b →
          Module.finrank (Chapter13PthPowerSubfield k p)
            (Algebra.adjoin (Chapter13PthPowerSubfield k p) (Set.range b)) = p ^ r) ↔
        (∀ b : k, b ∈ B →
          b ∉ Algebra.adjoin (Chapter13PthPowerSubfield k p) (B \ {b}))) := by
  sorry

/-- Existence, maximality, and the perfect-field criterion for `p`-bases. -/
theorem chapter13_p_basis_existence
    {k : Type u} [Field k] (p : ℕ) [Fact (Nat.Prime p)] [CharP k p] :
    (∀ B : Set k, Chapter13PIndependent (Chapter13PthPowerSubfield k p) B p →
      ∃ B' : Set k, B ⊆ B' ∧
        Chapter13PBasis (Chapter13PthPowerSubfield k p) B' p) ∧
      (∃ B : Set k, Chapter13PBasis (Chapter13PthPowerSubfield k p) B p) ∧
      (∀ B : Set k,
        Chapter13PBasis (Chapter13PthPowerSubfield k p) B p ↔
          Chapter13IsMaximalPIndependent (Chapter13PthPowerSubfield k p) B p) ∧
      (Chapter13PerfectAtPrime k p ↔
        Chapter13PBasis (Chapter13PthPowerSubfield k p) (∅ : Set k) p) := by
  sorry

/-- The `p`-monomial basis attached to a `p`-basis. -/
theorem chapter13_p_basis_monomial_basis
    {k : Type u} [Field k] (p : ℕ) [Fact (Nat.Prime p)] [CharP k p]
    (B : Set k)
    (hB : Chapter13PBasis (Chapter13PthPowerSubfield k p) B p) :
    ∃ β : Basis (Chapter13PMonomialIndex B p)
        (Chapter13PthPowerSubfield k p) k,
      ∀ e, β e = Chapter13PMonomial (fun b : B => (b : k)) e := by
  sorry

/-- Polynomial presentation and finite-degree formula supplied by a finite `p`-basis. -/
theorem chapter13_p_basis_polynomial_presentation
    {k : Type u} [Field k] (p : ℕ) [Fact (Nat.Prime p)] [CharP k p]
    (B : Set k)
    (hB : Chapter13PBasis (Chapter13PthPowerSubfield k p) B p)
    (c : B → Chapter13PthPowerSubfield k p)
    (hc : ∀ b : B, (c b : k) = (b : k) ^ p) :
    Function.Surjective
        (MvPolynomial.aeval (fun b : B => (b : k)) :
          MvPolynomial B (Chapter13PthPowerSubfield k p) →ₐ[
            Chapter13PthPowerSubfield k p] k) ∧
      RingHom.ker
          (MvPolynomial.aeval (fun b : B => (b : k)) :
            MvPolynomial B (Chapter13PthPowerSubfield k p) →ₐ[
              Chapter13PthPowerSubfield k p] k).toRingHom =
        Ideal.span (Set.range (fun b : B =>
          MvPolynomial.X b ^ p - MvPolynomial.C (c b))) ∧
      (B.Finite →
        FiniteDimensional (Chapter13PthPowerSubfield k p) k ∧
        Module.finrank (Chapter13PthPowerSubfield k p) k = p ^ B.ncard) := by
  sorry

/-- Restriction of a derivation to a chosen `p`-basis. -/
def Chapter13DerivationRestriction
    {k : Type u} [Field k] (p : ℕ) (B : Set k) (M : Type v)
    [AddCommGroup M] [Module k M]
    (D : Derivation (Chapter13PthPowerSubfield k p) k M) : B → M :=
  fun b => D (b : k)

/-- Every prescribed family of values on a `p`-basis extends uniquely to a derivation. -/
theorem chapter13_derivation_extension
    {k : Type u} [Field k] (p : ℕ) [Fact (Nat.Prime p)] [CharP k p]
    (B : Set k)
    (hB : Chapter13PBasis (Chapter13PthPowerSubfield k p) B p)
    (M : Type v) [AddCommGroup M] [Module k M] (δ : B → M) :
    ∃! D : Derivation (Chapter13PthPowerSubfield k p) k M,
      ∀ b : B, D (b : k) = δ b := by
  sorry

/-- Restriction identifies derivations with arbitrary values on a `p`-basis. -/
theorem chapter13_derivation_restriction_bijective
    {k : Type u} [Field k] (p : ℕ) [Fact (Nat.Prime p)] [CharP k p]
    (B : Set k)
    (hB : Chapter13PBasis (Chapter13PthPowerSubfield k p) B p)
    (M : Type v) [AddCommGroup M] [Module k M] :
    Function.Bijective
      (Chapter13DerivationRestriction p B M) := by
  constructor
  · intro D₁ D₂ hD
    obtain ⟨D, hD_values, hD_unique⟩ :=
      chapter13_derivation_extension p B hB M
        (Chapter13DerivationRestriction p B M D₁)
    have h₁ : ∀ b : B, D₁ (b : k) =
        Chapter13DerivationRestriction p B M D₁ b := by
      intro b
      rfl
    have h₂ : ∀ b : B, D₂ (b : k) =
        Chapter13DerivationRestriction p B M D₁ b := by
      intro b
      change D₂ (b : k) = D₁ (b : k)
      exact (congrFun hD b).symm
    exact (hD_unique D₁ h₁).trans (hD_unique D₂ h₂).symm
  · intro δ
    obtain ⟨D, hD, hD_unique⟩ :=
      chapter13_derivation_extension p B hB M δ
    refine ⟨D, ?_⟩
    funext b
    exact (hD b).trans rfl

/-- Lifting a characteristic-`p` field map across a square-zero extension. -/
theorem chapter13_char_p_square_zero_lift
    {R : Type u} [CommRing R]
    {k : Type v} [Field k]
    (p : ℕ) (hp : Nat.Prime p) [CharP R p] [CharP k p]
    (B : Set k)
    (hB : Chapter13PBasis (Chapter13PthPowerSubfield k p) B p)
    (I : Ideal R) (hI : I ^ 2 = ⊥)
    (ψ : k →+* (R ⧸ I)) (β : B → R)
    (hβ : ∀ b : B, Ideal.Quotient.mk I (β b) = ψ (b : k)) :
    ∃! φ : k →+* R,
      (Ideal.Quotient.mk I).comp φ = ψ ∧
        ∀ b : B, φ (b : k) = β b := by
  sorry

/-- Perfect residue fields have no `p`-basis choices. -/
theorem chapter13_perfect_field_empty_p_basis
    {k : Type u} [Field k] (p : ℕ) [Fact (Nat.Prime p)] [CharP k p]
    (hperfect : Chapter13PerfectAtPrime k p) :
    Chapter13PBasis (Chapter13PthPowerSubfield k p) (∅ : Set k) p := by
  have hF : Chapter13PthPowerSubfield k p = ⊤ := by
    apply top_unique
    intro x hx
    obtain ⟨y, hy⟩ := hperfect x
    exact Subfield.subset_closure ⟨y, hy⟩
  constructor
  · intro r b hb hbi
    by_cases hr : r = 0
    · subst r
      let : Subsingleton (Chapter13PMonomialIndex (Fin 0) p) :=
        ⟨fun a b => by
          apply Subtype.ext
          apply Finsupp.ext
          intro i
          exact i.elim0⟩
      apply (linearIndependent_subsingleton_index_iff _).2
      intro e
      have hs : e.1.support = ∅ := by
        apply Finset.eq_empty_iff_forall_notMem.mpr
        intro i hi
        exact i.elim0
      simp [Chapter13PMonomial, hs]
    · let i : Fin r := ⟨0, Nat.pos_of_ne_zero hr⟩
      exact (hb ⟨i, rfl⟩).elim
  · rw [hF]
    apply top_unique
    intro x hx
    let e : Chapter13PMonomialIndex (∅ : Set k) p :=
      ⟨0, by intro i; exact i.property.elim⟩
    have he : Chapter13PMonomial (fun b : (∅ : Set k) => (b : k)) e = 1 := by
      simp [Chapter13PMonomial, e]
    have hgen : Chapter13PMonomial (fun b : (∅ : Set k) => (b : k)) e ∈
        Submodule.span (⊤ : Subfield k)
          (Set.range (fun e =>
            Chapter13PMonomial (fun b : (∅ : Set k) => (b : k)) e)) :=
      Submodule.subset_span ⟨e, rfl⟩
    let x' : (⊤ : Subfield k) := ⟨x, trivial⟩
    have hsmul := Submodule.smul_mem
      (Submodule.span (⊤ : Subfield k)
        (Set.range (fun e =>
          Chapter13PMonomial (fun b : (∅ : Set k) => (b : k)) e))) x' hgen
    have hmul : x' • (1 : k) = x := by
      change x * 1 = x
      simp
    rw [he, hmul] at hsmul
    exact hsmul

/-- A separable algebraic extension preserves a chosen `p`-basis. -/
theorem chapter13_separable_extension_preserves_p_basis
    {k l : Type u} [Field k] [Field l] [Algebra k l]
    (p : ℕ) [Fact (Nat.Prime p)] [CharP k p] [CharP l p] (B : Set k)
    (hB : Chapter13PBasis (Chapter13PthPowerSubfield k p) B p)
    (hsep : Algebra.IsSeparable k l) :
    Chapter13PBasis (Chapter13PthPowerSubfield l p)
      ((algebraMap k l) '' B) p := by
  sorry

end

end LastLib.Book01ValuationsDVRsAndCompletions.Chapter13
