import LastLib.Book10FaithfullyFlatDescentInAlgebraicGeometry.Chapter02.Section01CoveringFamilies

/-!
## 2.4 Stability and refinement

Base change and composition are expressed at the family level.  A refinement is represented as a
second fpqc/fppf family over each member of a coarse family; its composite is the refined cover of
the original base.
-/

namespace LastLib.Book10FaithfullyFlatDescentInAlgebraicGeometry.Chapter02

noncomputable section

open AlgebraicGeometry CategoryTheory CategoryTheory.Limits Topology
open scoped AlgebraicGeometry

universe u v w v' u'

variable {S S' : Scheme.{u}} {I : Type v}

noncomputable def SchemeFamily.baseChange
    (F : SchemeFamily S I) (g : S' ⟶ S) : SchemeFamily S' I where
  obj := fun i ↦ pullback (F.map i) g
  map := fun i ↦ pullback.snd (F.map i) g

@[reassoc]
theorem SchemeFamily.baseChange_projection
    (F : SchemeFamily S I) (g : S' ⟶ S) (i : I) :
    pullback.fst (F.map i) g ≫ F.map i =
      (F.baseChange g).map i ≫ g := by
  simp [SchemeFamily.baseChange]

theorem flat_family_baseChange
    (F : SchemeFamily S I) (g : S' ⟶ S)
    (hF : ∀ i, Flat (F.map i)) :
    ∀ i, Flat ((F.baseChange g).map i) := by
  sorry

theorem locallyOfFinitePresentation_family_baseChange
    (F : SchemeFamily S I) (g : S' ⟶ S)
    (hF : ∀ i, LocallyOfFinitePresentation (F.map i)) :
    ∀ i, LocallyOfFinitePresentation ((F.baseChange g).map i) := by
  sorry

theorem jointlySurjective_family_baseChange_of_flat
    (F : SchemeFamily S I) (g : S' ⟶ S)
    (hflat : ∀ i, Flat (F.map i)) (hjoint : JointlySurjective F) :
    JointlySurjective (F.baseChange g) := by
  sorry

theorem fpqcCoveringFamily_baseChange
    {F : SchemeFamily S I} (g : S' ⟶ S)
    (hF : FpqcCoveringFamily F) :
    FpqcCoveringFamily (F.baseChange g) := by
  sorry

theorem fppfCoveringFamily_baseChange
    {F : SchemeFamily S I} (g : S' ⟶ S)
    (hF : FppfCoveringFamily F) :
    FppfCoveringFamily (F.baseChange g) := by
  sorry

/-- A second-stage family covering each member of a coarse family. -/
structure FamilyTower (F : SchemeFamily S I) (J : I → Type w) where
  inner : ∀ i, SchemeFamily (F.obj i) (J i)

noncomputable def FamilyTower.composite
    {F : SchemeFamily S I} {J : I → Type w}
    (G : FamilyTower F J) : SchemeFamily S (Σ i, J i) where
  obj := fun ij ↦ (G.inner ij.1).obj ij.2
  map := fun ij ↦ (G.inner ij.1).map ij.2 ≫ F.map ij.1

@[simp]
theorem FamilyTower.composite_map
    {F : SchemeFamily S I} {J : I → Type w} (G : FamilyTower F J)
    (ij : Σ i, J i) :
    (G.composite.map ij) = (G.inner ij.1).map ij.2 ≫ F.map ij.1 := by
  rfl

theorem fpqcFamilyTower_composite
    {F : SchemeFamily S I} {J : I → Type w} (G : FamilyTower F J)
    (hF : FpqcCoveringFamily F)
    (hG : ∀ i, FpqcCoveringFamily (G.inner i)) :
    FpqcCoveringFamily G.composite := by
  sorry

theorem fppfFamilyTower_composite
    {F : SchemeFamily S I} {J : I → Type w} (G : FamilyTower F J)
    (hF : FppfCoveringFamily F)
    (hG : ∀ i, FppfCoveringFamily (G.inner i)) :
    FppfCoveringFamily G.composite := by
  sorry

/-- A refinement records a local family over every member of a coarse family. -/
structure FamilyRefinement (F : SchemeFamily S I) (J : I → Type w) where
  family : FamilyTower F J
  fpqc : ∀ i, FpqcCoveringFamily (family.inner i)

def FamilyRefinement.refinedFamily
    {F : SchemeFamily S I} {J : I → Type w}
    (R : FamilyRefinement F J) : SchemeFamily S (Σ i, J i) :=
  R.family.composite

theorem familyRefinement_is_fpqc
    {F : SchemeFamily S I} {J : I → Type w}
    (hF : FpqcCoveringFamily F) (R : FamilyRefinement F J) :
    FpqcCoveringFamily R.refinedFamily := by
  exact fpqcFamilyTower_composite R.family hF R.fpqc

/-- The fppf analogue of a refinement. -/
structure FppfFamilyRefinement (F : SchemeFamily S I) (J : I → Type w) where
  family : FamilyTower F J
  fppf : ∀ i, FppfCoveringFamily (family.inner i)

def FppfFamilyRefinement.refinedFamily
    {F : SchemeFamily S I} {J : I → Type w}
    (R : FppfFamilyRefinement F J) : SchemeFamily S (Σ i, J i) :=
  R.family.composite

theorem fppfFamilyRefinement_is_fppf
    {F : SchemeFamily S I} {J : I → Type w}
    (hF : FppfCoveringFamily F) (R : FppfFamilyRefinement F J) :
    FppfCoveringFamily R.refinedFamily := by
  exact fppfFamilyTower_composite R.family hF R.fppf

/-- Canonical descent data only depends on the sieve generated by a covering family. -/
theorem descentData_effectivity_invariant_under_same_sieve
    {C : Type u} [Category.{v} C]
    (P : Pseudofunctor (LocallyDiscrete Cᵒᵖ) Cat.{v', u'})
    {ι ι' : Type w} {S : C} {X : ι → C} {X' : ι' → C}
    (f : ∀ i, X i ⟶ S) (f' : ∀ j, X' j ⟶ S)
    (h : Sieve.ofArrows _ f = Sieve.ofArrows _ f') :
    (P.toDescentData f).IsEquivalence ↔
      (P.toDescentData f').IsEquivalence := by
  exact Pseudofunctor.DescentData.isEquivalence_toDescentData_iff_of_sieve_eq P f f' h

theorem schemeFamily_descentData_effectivity_invariant_under_same_sieve
    {S : Scheme.{u}} (P : Pseudofunctor (LocallyDiscrete Schemeᵒᵖ) Cat.{v', u'})
    {I J : Type w} (F : SchemeFamily S I) (G : SchemeFamily S J)
    (h : Sieve.ofArrows F.obj F.map = Sieve.ofArrows G.obj G.map) :
    (P.toDescentData F.map).IsEquivalence ↔
      (P.toDescentData G.map).IsEquivalence := by
  exact Pseudofunctor.DescentData.isEquivalence_toDescentData_iff_of_sieve_eq
    P F.map G.map h

end

end LastLib.Book10FaithfullyFlatDescentInAlgebraicGeometry.Chapter02
