import Mathlib.LinearAlgebra.Dual.Defs
import LastLib.Book12BlowupsAndIntersectionTheoryOnArithmeticSurfaces.Chapter04.Dependencies

namespace LastLib.Book12BlowupsAndIntersectionTheoryOnArithmeticSurfaces.Chapter04

noncomputable section

open AlgebraicGeometry CategoryTheory CategoryTheory.Limits
open scoped AlgebraicGeometry

universe u v

/-! ## 4.1. The exceptional ideal and normal directions -/

/-- The scheme-theoretic exceptional locus is the subscheme cut out by the
pullback of the center ideal. -/
abbrev Chapter04Blowup.exceptionalSubscheme
    {X : Scheme.{u}} {I : X.IdealSheafData}
    (B : Chapter04Blowup X I) : Scheme.{u} :=
  B.exceptionalIdeal.subscheme

/-- The closed immersion of the exceptional locus into the blowup. -/
abbrev Chapter04Blowup.exceptionalInclusion
    {X : Scheme.{u}} {I : X.IdealSheafData}
    (B : Chapter04Blowup X I) : B.exceptionalSubscheme ⟶ B.carrier :=
  B.exceptionalIdeal.subschemeι

/-- The exceptional locus maps to the center through the canonical pullback
comparison for the comap ideal. -/
def Chapter04Blowup.exceptionalToCenter
    {X : Scheme.{u}} {I : X.IdealSheafData}
    (B : Chapter04Blowup X I) : B.exceptionalSubscheme ⟶ B.center :=
  (I.comapIso B.morphism).hom ≫
    pullback.snd B.morphism I.subschemeι

/-- An effective Cartier divisor whose ideal is the exceptional ideal. -/
structure Chapter04ExceptionalDivisorData
    {X : Scheme.{u}} {I : X.IdealSheafData}
    (B : Chapter04Blowup X I) where
  divisor : Chapter04EffectiveCartierDivisor B.carrier
  ideal_eq_exceptional : divisor.ideal = B.exceptionalIdeal

abbrev Chapter04ExceptionalDivisor
    {X : Scheme.{u}} {I : X.IdealSheafData}
    (B : Chapter04Blowup X I) :=
  Chapter04ExceptionalDivisorData B

/- The pullback ideal is invertible on the relative Proj blowup.  On an
integral blowup it is also generated by a non-zero-divisor, hence it is an
effective Cartier divisor.  The relative Proj construction is not present in
the pinned Mathlib tree, so existence is exposed as a proof-ready theorem
over the universal-property interface. -/
theorem chapter04_exceptional_divisor_exists
    {X : Scheme.{u}} {I : X.IdealSheafData}
    (hX : IsIntegral X)
    (hI : Chapter04CoherentIdeal I)
    (hI_ne_zero : I ≠ (⊥ : X.IdealSheafData))
    (B : Chapter04Blowup X I) :
    Nonempty (Chapter04ExceptionalDivisorData B) := by
  sorry

/- LOCAL_DEPENDENCY_GUESS (4.1): the relative-Proj carrier of a nonzero ideal
over an integral scheme is integral.  This bridge supplies the hypothesis
needed by the effective Cartier pullback adapter in Section 4.2. -/
theorem chapter04_blowup_carrier_is_integral
    {X : Scheme.{u}} {I : X.IdealSheafData}
    (hX : IsIntegral X)
    (hI : Chapter04CoherentIdeal I)
    (hI_ne_zero : I ≠ (⊥ : X.IdealSheafData))
    (B : Chapter04Blowup X I) :
    IsIntegral B.carrier := by
  sorry

noncomputable def chapter04ExceptionalDivisor
    {X : Scheme.{u}} {I : X.IdealSheafData}
    (hX : IsIntegral X)
    (hI : Chapter04CoherentIdeal I)
    (hI_ne_zero : I ≠ (⊥ : X.IdealSheafData))
    (B : Chapter04Blowup X I) :
    Chapter04ExceptionalDivisorData B :=
  Classical.choice (chapter04_exceptional_divisor_exists hX hI hI_ne_zero B)

@[simp]
theorem chapter04ExceptionalDivisor_ideal
    {X : Scheme.{u}} {I : X.IdealSheafData}
    {B : Chapter04Blowup X I}
    (E : Chapter04ExceptionalDivisorData B) :
    E.divisor.ideal = B.exceptionalIdeal :=
  E.ideal_eq_exceptional

/-- The exceptional support is the inverse image of the center support. -/
theorem chapter04_exceptional_support
    {X : Scheme.{u}} {I : X.IdealSheafData}
    (B : Chapter04Blowup X I) :
    B.exceptionalIdeal.support = I.support.preimage B.morphism.continuous := by
  sorry

theorem chapter04_exceptional_divisor_support
    {X : Scheme.{u}} {I : X.IdealSheafData}
    {B : Chapter04Blowup X I} (E : Chapter04ExceptionalDivisorData B) :
    E.divisor.ideal.support = I.support.preimage B.morphism.continuous := by
  rw [E.ideal_eq_exceptional]
  exact chapter04_exceptional_support B

class Chapter04ConormalSheafAPI
    {X : Scheme.{u}} (I : X.IdealSheafData) where
  conormal : I.subscheme.Modules
  finiteLocallyFree :
    LastLib.Book08AmpleLineBundlesHilbertPolynomialsAndSymmetricPowers.Chapter04.chapter04FiniteLocallyFree
      conormal
  conormal_is_ideal_quotient :
    ∀ U : X.affineOpens,
      Γ(conormal, I.subschemeι ⁻¹ᵁ U.1) ≃+
        (I.ideal U).Cotangent
  conormal_is_ideal_quotient_smul :
    ∀ (U : X.affineOpens)
      (r : Γ(I.subscheme, I.subschemeι ⁻¹ᵁ U.1))
      (m : Γ(conormal, I.subschemeι ⁻¹ᵁ U.1)),
      conormal_is_ideal_quotient U (r • m) =
        (I.subschemeObjIso U).hom r • conormal_is_ideal_quotient U m

abbrev chapter04ConormalSheaf {X : Scheme.{u}} (I : X.IdealSheafData)
    [Chapter04ConormalSheafAPI I] : I.subscheme.Modules :=
  Chapter04ConormalSheafAPI.conormal

def Chapter04ConormalSheafIsFiniteLocallyFree
    {X : Scheme.{u}} (I : X.IdealSheafData)
    [Chapter04ConormalSheafAPI I] : Prop :=
  LastLib.Book08AmpleLineBundlesHilbertPolynomialsAndSymmetricPowers.Chapter04.chapter04FiniteLocallyFree
    (chapter04ConormalSheaf I)

theorem chapter04_conormal_is_finiteLocallyFree
    {X : Scheme.{u}} (I : X.IdealSheafData)
    [Chapter04ConormalSheafAPI I] :
    Chapter04ConormalSheafIsFiniteLocallyFree I := by
  exact Chapter04ConormalSheafAPI.finiteLocallyFree

/- The projective bundle presentation of the exceptional divisor, including
the sign convention distinguishing its conormal line from its normal line. -/
structure Chapter04ExceptionalProjectiveBundleData
    {X : Scheme.{u}} {I : X.IdealSheafData}
    (B : Chapter04Blowup X I) [Chapter04ConormalSheafAPI I] where
  projectiveBundle : Chapter04ProjectiveBundle B.center
  projectiveBundle_module_eq :
    projectiveBundle.E = chapter04ConormalSheaf I
  exceptionalIso : B.exceptionalSubscheme ≅ projectiveBundle.space
  exceptionalIso_over_center :
    exceptionalIso.hom ≫ projectiveBundle.projection = B.exceptionalToCenter
  /- The restriction of the exceptional ideal is the conormal line
     `O_E(-E)`, not the normal line `O_E(E)`.  With the quotient convention
     this is the tautological `O(1)`. -/
  exceptionalConormalBundle : Chapter04LineBundle B.exceptionalSubscheme
  exceptionalIdealRestriction : Chapter04LineBundle B.exceptionalSubscheme
  exceptionalIdealRestriction_section_quotient :
    ∀ U : B.carrier.affineOpens,
      Γ(exceptionalIdealRestriction.sheaf,
        B.exceptionalInclusion ⁻¹ᵁ U.1) ≃+
        (B.exceptionalIdeal.ideal U).Cotangent
  exceptionalIdealRestriction_section_quotient_smul :
    ∀ (U : B.carrier.affineOpens)
      (r : Γ(B.exceptionalSubscheme, B.exceptionalInclusion ⁻¹ᵁ U.1))
      (m : Γ(exceptionalIdealRestriction.sheaf,
        B.exceptionalInclusion ⁻¹ᵁ U.1)),
      exceptionalIdealRestriction_section_quotient U (r • m) =
        (B.exceptionalIdeal.subschemeObjIso U).hom r •
          exceptionalIdealRestriction_section_quotient U m
  exceptionalIdealRestriction_is_pullback_ideal :
    exceptionalIdealRestriction.sheaf ≅
      (Scheme.Modules.pullback B.exceptionalInclusion).obj
        (Chapter04IdealModule B.exceptionalIdeal)
  exceptionalConormalBundle_is_restriction_of_exceptional_ideal :
    chapter04LineBundleIsomorphic exceptionalConormalBundle exceptionalIdealRestriction
  exceptionalConormalBundle_is_tautological :
    chapter04LineBundleIsomorphic exceptionalConormalBundle
      (LastLib.Book08AmpleLineBundlesHilbertPolynomialsAndSymmetricPowers.Chapter04.chapter04PullbackLineBundle
        exceptionalIso.hom
        (chapter04ProjectiveBundleTautological projectiveBundle))

/- The conormal sheaf is the canonical finite-locally-free module supplied by
   a regular closed immersion.  Keep its construction as a separate adapter
   so callers need not postulate an unrelated module just to use the
   exceptional projective-bundle theorem. -/
theorem chapter04_conormal_sheaf_api_exists
    {X : Scheme.{u}} [IsNoetherian X] {I : X.IdealSheafData}
    (hreg : Chapter04RegularClosedCenter I) :
    Nonempty (Chapter04ConormalSheafAPI I) := by
  sorry

theorem chapter04_exceptional_is_projective_bundle
    {X : Scheme.{u}} {I : X.IdealSheafData}
    (hreg : Chapter04RegularClosedCenter I)
    (B : Chapter04Blowup X I)
    [Chapter04ConormalSheafAPI I] :
    Nonempty (Chapter04ExceptionalProjectiveBundleData B) := by
  sorry

noncomputable def chapter04ExceptionalProjectiveBundle
    {X : Scheme.{u}} {I : X.IdealSheafData}
    (hreg : Chapter04RegularClosedCenter I)
    (B : Chapter04Blowup X I)
    [Chapter04ConormalSheafAPI I] :
    Chapter04ExceptionalProjectiveBundleData B :=
  Classical.choice (chapter04_exceptional_is_projective_bundle hreg B)

theorem chapter04_exceptional_conormal_bundle_is_O_one
    {X : Scheme.{u}} {I : X.IdealSheafData}
    (hreg : Chapter04RegularClosedCenter I)
    (B : Chapter04Blowup X I)
    [Chapter04ConormalSheafAPI I] :
    chapter04LineBundleIsomorphic
      (chapter04ExceptionalProjectiveBundle hreg B).exceptionalConormalBundle
      (LastLib.Book08AmpleLineBundlesHilbertPolynomialsAndSymmetricPowers.Chapter04.chapter04PullbackLineBundle
        (chapter04ExceptionalProjectiveBundle hreg B).exceptionalIso.hom
        (chapter04ProjectiveBundleTautological
          (chapter04ExceptionalProjectiveBundle hreg B).projectiveBundle)) := by
  exact (chapter04ExceptionalProjectiveBundle hreg B).exceptionalConormalBundle_is_tautological

/-- The local regular-surface hypothesis at a point. -/
def Chapter04RegularSurfacePoint {X : Scheme.{u}} (x : X) : Prop :=
  IsRegularLocalRing (X.presheaf.stalk x) ∧
    ringKrullDim (X.presheaf.stalk x) = 2

/-- The normal space is the dual of the cotangent space at a regular point. -/
abbrev chapter04NormalSpace (R : Type u) [CommRing R] [IsLocalRing R]
    : Type u :=
  Module.Dual (IsLocalRing.ResidueField R) (IsLocalRing.CotangentSpace R)

theorem chapter04_regular_surface_point_tangent_plane_dimension
    {X : Scheme.{u}} (x : X)
    [IsRegularLocalRing (X.presheaf.stalk x)]
    (hx : Chapter04RegularSurfacePoint x) :
    Module.finrank (IsLocalRing.ResidueField (X.presheaf.stalk x))
        (IsLocalRing.CotangentSpace (X.presheaf.stalk x)) = 2 := by
  sorry

theorem chapter04_regular_surface_point_normal_space_dimension
    {X : Scheme.{u}} (x : X)
    [IsRegularLocalRing (X.presheaf.stalk x)]
    (hx : Chapter04RegularSurfacePoint x) :
    Module.finrank (IsLocalRing.ResidueField (X.presheaf.stalk x))
        (chapter04NormalSpace (X.presheaf.stalk x)) = 2 := by
  sorry

/-- One-dimensional tangent directions in the normal space of a local ring.
The projective-line description of an exceptional fiber is expressed through
these lines, with the usual tangent/cotangent duality supplied by the
regular-local proof. -/
def Chapter04TangentDirection (R : Type u) [CommRing R] [IsLocalRing R] : Type u :=
  { V : Submodule (IsLocalRing.ResidueField R) (chapter04NormalSpace R) //
      Module.finrank (IsLocalRing.ResidueField R) V = 1 }

/- A local equation is recorded through a germ of a section of the Cartier
ideal.  This is the stalkwise form used again in the multiplicity section. -/
def Chapter04CurveHasMultiplicityAt
    {X : Scheme.{u}} (C : Chapter04EffectiveCartierDivisor X)
    (x : X) (m : ℕ) : Prop :=
  ∃ (U : X.affineOpens) (hx : x ∈ U.1) (f : Γ(X, U.1)),
    C.ideal.ideal U = Ideal.span ({f} : Set Γ(X, U.1)) ∧
      X.presheaf.germ U.1 x hx f ∈
        (IsLocalRing.maximalIdeal (X.presheaf.stalk x)) ^ m ∧
      X.presheaf.germ U.1 x hx f ∉
        (IsLocalRing.maximalIdeal (X.presheaf.stalk x)) ^ (m + 1)

def Chapter04SmoothCurveAtPoint
    {X : Scheme.{u}} (C : Chapter04EffectiveCartierDivisor X)
    (x : X) : Prop :=
  Chapter04CurveHasMultiplicityAt C x 1 ∧
    ∀ y : C.subscheme, C.inclusion y = x →
      IsRegularLocalRing (C.subscheme.presheaf.stalk y)

/- LOCAL_DEPENDENCY_GUESS (4.1): the pointwise identification of the
exceptional fiber with projective one-space is retained as an explicit
correspondence field until the relative projective-bundle and point-functor
interfaces are available in the earlier chapters. -/
structure Chapter04ExceptionalTangentDirectionData
    {X : Scheme.{u}} {I : X.IdealSheafData}
    (x : X) (B : Chapter04Blowup X I) where
  centerPoint : B.center ≅ AlgebraicGeometry.Spec (X.residueField x)
  centerPoint_over :
    centerPoint.inv ≫ B.centerι = X.fromSpecResidueField x
  projectiveLineIso :
    B.exceptionalSubscheme ≅
      LastLib.Book08AmpleLineBundlesHilbertPolynomialsAndSymmetricPowers.Chapter04.chapter04ProjectiveLine
        (X.residueField x)
  projectiveLineIso_over :
    projectiveLineIso.hom ≫
        LastLib.Book08AmpleLineBundlesHilbertPolynomialsAndSymmetricPowers.Chapter04.chapter04ProjectiveLineStructureMap
          (X.residueField x) =
      B.exceptionalToCenter ≫ centerPoint.hom
  rationalPointDirectionEquiv :
    {p : AlgebraicGeometry.Spec (X.residueField x) ⟶ B.exceptionalSubscheme //
        p ≫ B.exceptionalToCenter = centerPoint.inv} ≃
      Chapter04TangentDirection (X.presheaf.stalk x)

theorem chapter04_exceptional_fiber_is_projective_line
    {X : Scheme.{u}} {I : X.IdealSheafData}
    {x : X} (hx : Chapter04RegularSurfacePoint x)
    (hx_closed : IsClosed ({x} : Set X))
    (hcenter : Chapter04RegularClosedCenter I)
    (B : Chapter04Blowup X I)
    (centerPoint : B.center ≅ AlgebraicGeometry.Spec (X.residueField x))
    (centerPoint_over : centerPoint.inv ≫ B.centerι = X.fromSpecResidueField x)
    [Chapter04ConormalSheafAPI I] :
    Nonempty (Chapter04ExceptionalTangentDirectionData x B) := by
  sorry

end

end LastLib.Book12BlowupsAndIntersectionTheoryOnArithmeticSurfaces.Chapter04
