import Mathlib.LinearAlgebra.Dual.Defs
import LastLib.Book12BlowupsAndIntersectionTheoryOnArithmeticSurfaces.Chapter04.Dependencies

namespace LastLib.Book12BlowupsAndIntersectionTheoryOnArithmeticSurfaces.Chapter04

noncomputable section

open AlgebraicGeometry CategoryTheory CategoryTheory.Limits
open scoped AlgebraicGeometry

universe u v

/-! ## 4.1. The exceptional ideal and normal directions -/

/-- The scheme-theoretic exceptional locus is the subscheme cut out by the
pullback of the center ideal. -/
abbrev Chapter04Blowup.exceptionalSubscheme
    {X : Scheme.{u}} {I : X.IdealSheafData}
    (B : Chapter04Blowup X I) : Scheme.{u} :=
  B.exceptionalIdeal.subscheme

/-- The closed immersion of the exceptional locus into the blowup. -/
abbrev Chapter04Blowup.exceptionalInclusion
    {X : Scheme.{u}} {I : X.IdealSheafData}
    (B : Chapter04Blowup X I) : B.exceptionalSubscheme ⟶ B.carrier :=
  B.exceptionalIdeal.subschemeι

/-- The exceptional locus maps to the center through the canonical pullback
comparison for the comap ideal. -/
def Chapter04Blowup.exceptionalToCenter
    {X : Scheme.{u}} {I : X.IdealSheafData}
    (B : Chapter04Blowup X I) : B.exceptionalSubscheme ⟶ B.center :=
  (I.comapIso B.morphism).hom ≫
    pullback.snd B.morphism I.subschemeι

/-- An effective Cartier divisor whose ideal is the exceptional ideal. -/
structure Chapter04ExceptionalDivisorData
    {X : Scheme.{u}} {I : X.IdealSheafData}
    (B : Chapter04Blowup X I) where
  divisor : Chapter04EffectiveCartierDivisor B.carrier
  ideal_eq_exceptional : divisor.ideal = B.exceptionalIdeal

abbrev Chapter04ExceptionalDivisor
    {X : Scheme.{u}} {I : X.IdealSheafData}
    (B : Chapter04Blowup X I) :=
  Chapter04ExceptionalDivisorData B

/- The pullback ideal is invertible on the relative Proj blowup.  On an
integral blowup it is also generated by a non-zero-divisor, hence it is an
effective Cartier divisor.  The relative Proj construction is not present in
the pinned Mathlib tree, so existence is exposed as a proof-ready theorem
over the universal-property interface. -/
theorem chapter04_exceptional_divisor_exists
    {X : Scheme.{u}} {I : X.IdealSheafData}
    (hX : IsIntegral X)
    (hI : Chapter04CoherentIdeal I)
    (hI_ne_zero : I ≠ (⊥ : X.IdealSheafData))
    (B : Chapter04Blowup X I) :
    Nonempty (Chapter04ExceptionalDivisorData B) := by
  sorry

/- LOCAL_DEPENDENCY_GUESS (4.1): the relative-Proj carrier of a nonzero ideal
over an integral scheme is integral.  This bridge supplies the hypothesis
needed by the effective Cartier pullback adapter in Section 4.2. -/
theorem chapter04_blowup_carrier_is_integral
    {X : Scheme.{u}} {I : X.IdealSheafData}
    (hX : IsIntegral X)
    (hI : Chapter04CoherentIdeal I)
    (hI_ne_zero : I ≠ (⊥ : X.IdealSheafData))
    (B : Chapter04Blowup X I) :
    IsIntegral B.carrier := by
  sorry

noncomputable def chapter04ExceptionalDivisor
    {X : Scheme.{u}} {I : X.IdealSheafData}
    (hX : IsIntegral X)
    (hI : Chapter04CoherentIdeal I)
    (hI_ne_zero : I ≠ (⊥ : X.IdealSheafData))
    (B : Chapter04Blowup X I) :
    Chapter04ExceptionalDivisorData B :=
  Classical.choice (chapter04_exceptional_divisor_exists hX hI hI_ne_zero B)

@[simp]
theorem chapter04ExceptionalDivisor_ideal
    {X : Scheme.{u}} {I : X.IdealSheafData}
    {B : Chapter04Blowup X I}
    (E : Chapter04ExceptionalDivisorData B) :
    E.divisor.ideal = B.exceptionalIdeal :=
  E.ideal_eq_exceptional

/-- The exceptional support is the inverse image of the center support. -/
theorem chapter04_exceptional_support
    {X : Scheme.{u}} {I : X.IdealSheafData}
    (B : Chapter04Blowup X I) :
    B.exceptionalIdeal.support = I.support.preimage B.morphism.continuous := by
  simpa [Chapter04Blowup.exceptionalIdeal] using
    (Scheme.IdealSheafData.support_comap I B.morphism)

theorem chapter04_exceptional_divisor_support
    {X : Scheme.{u}} {I : X.IdealSheafData}
    {B : Chapter04Blowup X I} (E : Chapter04ExceptionalDivisorData B) :
    E.divisor.ideal.support = I.support.preimage B.morphism.continuous := by
  rw [E.ideal_eq_exceptional]
  exact chapter04_exceptional_support B

/- LOCAL_DEPENDENCY_GUESS (4.1): the pinned Mathlib tree has the affine
`Ideal.Cotangent` module but no sheaf-level conormal quotient for an ideal
sheaf.  This interface records precisely that missing quotient and its finite
locally-free package, leaving the quotient construction available to the
proof/fixup pass. -/
class Chapter04ConormalSheafAPI
    {X : Scheme.{u}} (I : X.IdealSheafData) where
  conormal : I.subscheme.Modules
  finiteLocallyFree : chapter04FiniteLocallyFree conormal
  /- LOCAL_DEPENDENCY_GUESS (4.1): replace by the canonical sheaf quotient
     identification `I/I^2` when the earlier conormal-sheaf API is available. -/
  conormal_is_ideal_quotient : Prop

abbrev chapter04ConormalSheaf {X : Scheme.{u}} (I : X.IdealSheafData)
    [Chapter04ConormalSheafAPI I] : I.subscheme.Modules :=
  Chapter04ConormalSheafAPI.conormal I

def Chapter04ConormalSheafIsFiniteLocallyFree
    {X : Scheme.{u}} (I : X.IdealSheafData)
    [Chapter04ConormalSheafAPI I] : Prop :=
  chapter04FiniteLocallyFree (chapter04ConormalSheaf I)

theorem chapter04_conormal_is_finiteLocallyFree
    {X : Scheme.{u}} (I : X.IdealSheafData)
    [Chapter04ConormalSheafAPI I] :
    Chapter04ConormalSheafIsFiniteLocallyFree I := by
  exact Chapter04ConormalSheafAPI.finiteLocallyFree

/- The projective bundle presentation of the exceptional divisor, including
the sign convention for its normal line bundle. -/
structure Chapter04ExceptionalProjectiveBundleData
    {X : Scheme.{u}} {I : X.IdealSheafData}
    (B : Chapter04Blowup X I) [Chapter04ConormalSheafAPI I] where
  projectiveBundle : Chapter04ProjectiveBundle B.center
  projectiveBundle_module_eq :
    projectiveBundle.E = chapter04ConormalSheaf I
  exceptionalIso : B.exceptionalSubscheme ≅ projectiveBundle.space
  exceptionalIso_over_center :
    exceptionalIso.hom ≫ projectiveBundle.projection = B.exceptionalToCenter
  exceptionalNormalBundle : Chapter04LineBundle B.exceptionalSubscheme
  /- LOCAL_DEPENDENCY_GUESS (4.1): this identifies the chosen line bundle with
     the restriction of the exceptional ideal, i.e. `O_E(-E)`. -/
  exceptionalNormalBundle_is_restriction_of_exceptional_ideal : Prop
  exceptionalNormalBundle_is_tautological :
    chapter04LineBundleIsomorphic exceptionalNormalBundle
      (chapter04PullbackLineBundle exceptionalIso.hom
        (chapter04ProjectiveBundleTautological projectiveBundle))

theorem chapter04_exceptional_is_projective_bundle
    {X : Scheme.{u}} {I : X.IdealSheafData}
    (hreg : Chapter04RegularClosedCenter I)
    (B : Chapter04Blowup X I)
    [Chapter04ConormalSheafAPI I] :
    Nonempty (Chapter04ExceptionalProjectiveBundleData B) := by
  sorry

noncomputable def chapter04ExceptionalProjectiveBundle
    {X : Scheme.{u}} {I : X.IdealSheafData}
    (hreg : Chapter04RegularClosedCenter I)
    (B : Chapter04Blowup X I)
    [Chapter04ConormalSheafAPI I] :
    Chapter04ExceptionalProjectiveBundleData B :=
  Classical.choice (chapter04_exceptional_is_projective_bundle hreg B)

theorem chapter04_exceptional_normal_bundle_is_O_one
    {X : Scheme.{u}} {I : X.IdealSheafData}
    (hreg : Chapter04RegularClosedCenter I)
    (B : Chapter04Blowup X I)
    [Chapter04ConormalSheafAPI I] :
    chapter04LineBundleIsomorphic
      (chapter04ExceptionalProjectiveBundle hreg B).exceptionalNormalBundle
      (chapter04PullbackLineBundle
        (chapter04ExceptionalProjectiveBundle hreg B).exceptionalIso.hom
        (chapter04ProjectiveBundleTautological
          (chapter04ExceptionalProjectiveBundle hreg B).projectiveBundle)) := by
  exact (chapter04ExceptionalProjectiveBundle hreg B).exceptionalNormalBundle_is_tautological

/-- The local regular-surface hypothesis at a point. -/
def Chapter04RegularSurfacePoint {X : Scheme.{u}} (x : X) : Prop :=
  IsRegularLocalRing (X.presheaf.stalk x) ∧
    ringKrullDim (X.presheaf.stalk x) = 2

/-- The normal space is the dual of the cotangent space at a regular point. -/
def chapter04NormalSpace (R : Type u) [CommRing R] [IsLocalRing R]
    : Type u :=
  Module.Dual (IsLocalRing.ResidueField R) (IsLocalRing.CotangentSpace R)

theorem chapter04_regular_surface_point_tangent_plane_dimension
    {X : Scheme.{u}} (x : X)
    [IsLocalRing (X.presheaf.stalk x)]
    [IsNoetherianRing (X.presheaf.stalk x)]
    [IsRegularLocalRing (X.presheaf.stalk x)]
    (hx : Chapter04RegularSurfacePoint x) :
    Module.finrank (IsLocalRing.ResidueField (X.presheaf.stalk x))
        (IsLocalRing.CotangentSpace (X.presheaf.stalk x)) = 2 := by
  sorry

theorem chapter04_regular_surface_point_normal_space_dimension
    {X : Scheme.{u}} (x : X)
    [IsLocalRing (X.presheaf.stalk x)]
    [IsNoetherianRing (X.presheaf.stalk x)]
    [IsRegularLocalRing (X.presheaf.stalk x)]
    (hx : Chapter04RegularSurfacePoint x) :
    Module.finrank (IsLocalRing.ResidueField (X.presheaf.stalk x))
        (chapter04NormalSpace (X.presheaf.stalk x)) = 2 := by
  sorry

/-- One-dimensional tangent directions in the normal space of a local ring.
The projective-line description of an exceptional fiber is expressed through
these lines, with the usual tangent/cotangent duality supplied by the
regular-local proof. -/
def Chapter04TangentDirection (R : Type u) [CommRing R] [IsLocalRing R]
    (L : Type v) [Field L] [Module L (chapter04NormalSpace R)] : Type max u v :=
  { V : Submodule L (chapter04NormalSpace R) //
      Module.finrank L V = 1 }

/- A local equation is recorded through a germ of a section of the Cartier
ideal.  This is the stalkwise form used again in the multiplicity section. -/
def Chapter04CurveHasMultiplicityAt
    {X : Scheme.{u}} (C : Chapter04EffectiveCartierDivisor X)
    (x : X) (m : ℕ) : Prop :=
  ∃ (U : X.affineOpens) (hx : x.1 ∈ U.1) (f : Γ(X, U.1)),
    f ∈ C.ideal.ideal U ∧
      X.presheaf.germ U.1 x hx f ∈ (maximalIdeal (X.presheaf.stalk x)) ^ m ∧
      X.presheaf.germ U.1 x hx f ∉ (maximalIdeal (X.presheaf.stalk x)) ^ (m + 1)

def Chapter04SmoothCurveAtPoint
    {X : Scheme.{u}} (C : Chapter04EffectiveCartierDivisor X)
    (x : X) : Prop :=
  Chapter04CurveHasMultiplicityAt C x 1 ∧
    ∀ y : C.subscheme, C.inclusion y = x →
      IsRegularLocalRing (C.subscheme.presheaf.stalk y)

/- LOCAL_DEPENDENCY_GUESS (4.1): the pointwise identification of the
exceptional fiber with projective one-space is retained as an explicit
correspondence field until the relative projective-bundle and point-functor
interfaces are available in the earlier chapters. -/
structure Chapter04ExceptionalTangentDirectionData
    {X : Scheme.{u}} {I : X.IdealSheafData}
    (x : X) (B : Chapter04Blowup X I) where
  centerPoint : B.center ≅ AlgebraicGeometry.Spec (X.residueField x)
  rationalPointDirectionEquiv :
    {p : AlgebraicGeometry.Spec (X.residueField x) ⟶ B.exceptionalSubscheme //
        p ≫ B.exceptionalToCenter = centerPoint.inv} ≃
      Chapter04TangentDirection (X.presheaf.stalk x)
        (X.residueField x)

theorem chapter04_exceptional_fiber_is_projective_line
    {X : Scheme.{u}} {I : X.IdealSheafData}
    {x : X} (hx : Chapter04RegularSurfacePoint x)
    (B : Chapter04Blowup X I)
    [Chapter04ConormalSheafAPI I] :
    Nonempty (Chapter04ExceptionalTangentDirectionData x B) := by
  sorry

/- The tangent-cone assertion is kept as a source-facing data package.  Its
degree field is the multiplicity of the curve, so smooth curves and multiple
curves are both represented before the transform API is introduced. -/
structure Chapter04ProjectivizedTangentConeData
    {X : Scheme.{u}} {I : X.IdealSheafData}
    (x : X) (B : Chapter04Blowup X I)
    (C : Chapter04EffectiveCartierDivisor X) where
  tangentCone : Chapter04EffectiveCartierDivisor B.exceptionalSubscheme
  strictTransformIdeal : B.carrier.IdealSheafData
  multiplicity : ℕ
  tangentCone_degree : ℕ
  tangentCone_degree_eq_multiplicity : tangentCone_degree = multiplicity
  /- LOCAL_DEPENDENCY_GUESS (4.1): replace by the scheme-theoretic graded
     initial-form construction once strict transforms expose their Rees charts. -/
  intersection_with_strict_transform_is_tangentCone : Prop

theorem chapter04_curve_meets_exceptional_in_tangent_cone
    {X : Scheme.{u}} {I : X.IdealSheafData}
    {x : X} (hx : Chapter04RegularSurfacePoint x)
    (B : Chapter04Blowup X I)
    (C : Chapter04EffectiveCartierDivisor X)
    [Chapter04ConormalSheafAPI I] :
    Nonempty (Chapter04ProjectivizedTangentConeData x B C) := by
  sorry

theorem chapter04_smooth_curve_tangent_cone_degree_one
    {X : Scheme.{u}} {I : X.IdealSheafData}
    {x : X} (hx : Chapter04RegularSurfacePoint x)
    (B : Chapter04Blowup X I)
    (C : Chapter04EffectiveCartierDivisor X)
    (hC_smooth : Chapter04SmoothCurveAtPoint C x)
    [Chapter04ConormalSheafAPI I] :
    ∃ T : Chapter04ProjectivizedTangentConeData x B C,
      T.multiplicity = 1 ∧ T.tangentCone_degree = 1 := by
  sorry

theorem chapter04_curve_tangent_cone_degree_multiplicity
    {X : Scheme.{u}} {I : X.IdealSheafData}
    {x : X} (hx : Chapter04RegularSurfacePoint x)
    (B : Chapter04Blowup X I)
    (C : Chapter04EffectiveCartierDivisor X)
    (m : ℕ) (hC_multiplicity : Chapter04CurveHasMultiplicityAt C x m)
    [Chapter04ConormalSheafAPI I] :
    ∃ T : Chapter04ProjectivizedTangentConeData x B C,
      T.multiplicity = m ∧ T.tangentCone_degree = m := by
  sorry

end

end LastLib.Book12BlowupsAndIntersectionTheoryOnArithmeticSurfaces.Chapter04
