import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter08.Section03UniformizersAndMinimalPolynomials

namespace LastLib.Book02FiniteExtensionsOfLocalFields.Chapter08

noncomputable section

open Polynomial

/-! # 8.5. Monogenicity: what is true and what is not -/

/-- Book §8.5: monogenicity of an integral algebra, with integrality of the
chosen generator made explicit. -/
def chapter08Monogenic
    (A B : Type*) [CommRing A] [CommRing B] [Algebra A B] : Prop :=
  (∀ b : B, IsIntegral A b) ∧
    ∃ α : B, IsIntegral A α ∧ Algebra.adjoin A ({α} : Set B) = ⊤

/-- Monogenicity by one specified element, used to separate field generation
from equality of integral rings. -/
def chapter08MonogenicBy
    (A B : Type*) [CommRing A] [CommRing B] [Algebra A B]
    (α : B) : Prop :=
  IsIntegral A α ∧ Algebra.adjoin A ({α} : Set B) = ⊤

/-- The specified-element version of `B = A[α]` when `B` is the integral
closure inside a field. -/
def chapter08IntegralGeneratorFor
    (A L : Type*) [CommRing A] [Field L] [Algebra A L]
    (α : L) : Prop :=
  IsIntegral A α ∧
    (integralClosure A L : Set L) =
      (Algebra.adjoin A ({α} : Set L) : Set L)

/-- The two-generator presentation `B = A[θ, π_L]` used before the local
monogenicity theorem in Book §8.5. -/
def chapter08TwoGeneratorIntegralPresentation
    (A L : Type*) [CommRing A] [Field L] [Algebra A L]
    (θ πL : L) : Prop :=
  IsIntegral A θ ∧ IsIntegral A πL ∧
    (integralClosure A L : Set L) =
      (Algebra.adjoin A ({θ, πL} : Set L) : Set L)

/-- A finite residue extension is simple in the sense required by reduction of
a one-generator integral algebra. -/
def chapter08ResidueExtensionIsSimple
    (k l : Type*) [Field k] [Field l] [Algebra k l] : Prop :=
  ∃ x : l, Algebra.adjoin k ({x} : Set l) = ⊤

/-- Book §8.5: reduction of a monogenic algebra is generated by the residue
of the same element.  Surjectivity of the algebra reduction map and its base
compatibility are made explicit. -/
theorem chapter08_monogenicity_forces_simple_residue_extension
    {A B k l : Type*} [CommRing A] [CommRing B] [Field k] [Field l]
    [Algebra A B] [Algebra k l]
    (ρA : A →+* k) (ρB : B →+* l)
    (hρB : Function.Surjective ρB)
    (hcompat : ∀ a : A,
      ρB (algebraMap A B a) = algebraMap k l (ρA a))
    (α : B) (hmono : Algebra.adjoin A ({α} : Set B) = ⊤) :
    chapter08ResidueExtensionIsSimple k l := by
  refine ⟨ρB α, ?_⟩
  apply top_unique
  intro y hy
  rcases hρB y with ⟨b, rfl⟩
  have hb : b ∈ Algebra.adjoin A ({α} : Set B) := by
    rw [hmono]
    trivial
  refine Algebra.adjoin_induction ?_ ?_ ?_ ?_ hb
  · intro x hx
    have hx' : x = α := Set.mem_singleton_iff.mp hx
    subst x
    exact Algebra.subset_adjoin (by simp)
  · intro r
    rw [hcompat r]
    exact Subalgebra.algebraMap_mem _ _
  · intro x z hx hz hxh hzh
    rw [map_add]
    exact add_mem hxh hzh
  · intro x z hx hz hxh hzh
    rw [map_mul]
    exact mul_mem hxh hzh

/-- A proper integral order generated by a field primitive element is the
precise obstruction to concluding integral monogenicity from field generation.
-/
theorem chapter08_primitive_element_does_not_identify_the_integral_closure
    {A L : Type*} [CommRing A] [IsDomain A] [Field L]
    [Algebra A L]
    (α : L)
    (hproper : (Algebra.adjoin A ({α} : Set L) : Set L) ≠
      (integralClosure A L : Set L)) :
    ¬ chapter08IntegralGeneratorFor A L α := by
  intro hgenerator
  exact hproper hgenerator.2.symm

/-- Book §8.5: a separable residue polynomial lifted over a henselian base
produces an integral generator of the unramified part. -/
theorem chapter08_unramified_lift_is_integrally_monogenic
    {A K L k : Type*} [CommRing A] [IsDomain A]
    [IsDiscreteValuationRing A] [Field K] [Field L] [Field k]
    [Algebra A K] [IsFractionRing A K] [Algebra K L]
    [Algebra A L] [IsScalarTower A K L] [FiniteDimensional K L]
    [Algebra A k] [HenselianLocalRing A]
    (fbar : k[X]) (f : A[X]) (θ : L)
    (hmonic : fbar.Monic ∧ f.Monic)
    (hirreducible : Irreducible fbar)
    (hseparable : fbar.Separable)
    (hlift : f.map (algebraMap A k) = fbar)
    (hroot : aeval θ f = 0)
    (hgen : Algebra.adjoin K ({θ} : Set L) = ⊤)
    (hdegree : Module.finrank K L = fbar.natDegree)
    (hresidue : ∃ e : IsLocalRing.ResidueField A ≃+* k,
      ∀ a : A, algebraMap A k a = e (IsLocalRing.residue A a)) :
    chapter08IntegralGeneratorFor A L θ := by
  /- PROOF ROADMAP.
  This statement is intentionally the normalization-free interface: its
  hypotheses already force `f.map (algebraMap A K)` to be irreducible and
  separable, hence `L/K` is separable and the normalization is finite.  Do
  not try to apply
  `Chapter12.separable_residue_polynomial_lift_is_unramified` directly: that
  theorem (Book01/Chapter12/Section07UnramifiedAndTotallyRamifiedEndpoints)
  is formulated using complete valued-field models and an equality with an
  upper valuation ring, neither of which is present here.

  1. Choose `e` from `hresidue`.  Transport `fbar` along `e.symm` to a
     polynomial over `IsLocalRing.ResidueField A`; after rewriting `hlift`,
     apply
     `Chapter09.irreducible_of_irreducible_residue_reduction`
     (Book01/Chapter09/Section06AlgebraicConsequences) to obtain
     `Irreducible (f.map (algebraMap A K))`.  For separability, use
     `Polynomial.separable_iff_derivative_ne_zero` for that irreducible
     polynomial; nonvanishing of the derivative descends from `hseparable`
     using `Polynomial.derivative_map`, `hlift`, and injectivity of
     `algebraMap A K`.  Convert `hroot` with `aeval_map_algebraMap`.
  2. Use `minpoly.eq_of_irreducible_of_monic`, `hgen`, and `hdegree` to make
     `θ` a `PowerBasis K L`; install `Algebra.IsSeparable K L`.  Then obtain
     `Module.Finite A (integralClosure A L)` from
     `Chapter11.chapter11_separable_extension_gives_finite_normalization`
     (Book01/Chapter11/Section02FinitenessHypotheses), and locality from
     `Chapter01.chapter01_henselian_integral_closure_is_local`
     (Book02/Chapter01/Section02ExistenceUniquenessAndCompleteness).
  3. Put `B := integralClosure A L`.  Give it the standard
     `IsIntegralClosure B A L`, `IsFractionRing B L`, and local-DVR
     instances (the fraction-ring bridge is
     `IsIntegralClosure.isFractionRing_of_finite_extension`).  Let `θB : B`
     be `⟨θ, hmonic.2.isIntegral hroot⟩`.  The canonical residue maps and `e`
     identify the reduction of the powers
     `1, θB, ..., θB^(fbar.natDegree-1)` with the power basis of
     `k[X]/(fbar)`; use irreducibility and `hdegree` for the latter basis.
  4. Apply `IsLocalRing.span_eq_top_of_tmul_eq_basis`
     (Mathlib/RingTheory/LocalRing/Module) to those powers.  Since every
     power lies in `Algebra.adjoin A {θB}`, its underlying `A`-submodule is
     top.  This gives `Algebra.adjoin A {θB} = ⊤`; transport the set equality
     through the subtype inclusion `B -> L` to obtain the second conjunct
     of `chapter08IntegralGeneratorFor`.  The first conjunct is the monic
     root integrality from step 3.
  -/
  sorry

/-- Book §8.5: the totally ramified endpoint is monogenic by any uniformizer.
This is the monogenicity reading of the uniformizer theorem in §8.3. -/
theorem chapter08_totally_ramified_extension_is_integrally_monogenic
    {A K L : Type*} [CommRing A] [IsDomain A]
    [IsDiscreteValuationRing A] [Field K] [Field L]
    [Algebra A K] [IsFractionRing A K] [Algebra K L]
    [Algebra A L] [IsScalarTower A K L] [FiniteDimensional K L]
    (hcomplete : IsAdicComplete (IsLocalRing.maximalIdeal A) A)
    (hfinite : Module.Finite A (integralClosure A L))
    (vK : AddValuation K (WithTop ℤ))
    (vL : AddValuation L (WithTop ℤ))
    (hdiscreteK :
      LastLib.Book01ValuationsDVRsAndCompletions.Chapter10.Chapter10DiscreteAddValuation vK)
    (hdiscreteL :
      LastLib.Book01ValuationsDVRsAndCompletions.Chapter10.Chapter10DiscreteAddValuation vL)
    (hval : vK.IsEquiv (AddValuation.comap (algebraMap K L) vL))
    (htotal : chapter08TotallyRamified vK vL hval)
    (hintegralK : ∀ x : K, IsIntegral A x ↔ 0 ≤ vK x)
    (hintegralL : ∀ x : L, IsIntegral A x ↔ 0 ≤ vL x)
    (πK : A) (hπK : vK (algebraMap A K πK) = 1)
    (πL : L) (hπL : vL πL = 1) :
    chapter08IntegralGeneratorFor A L πL := by
  rcases chapter08_uniformizer_theorem
      hcomplete hfinite vK vL hdiscreteK hdiscreteL hval htotal
      hintegralK hintegralL πK hπK πL hπL with
    ⟨g, _, _, _, _, _, hclosure, _⟩
  refine ⟨?_, hclosure⟩
  apply (hintegralL πL).2
  rw [hπL]
  norm_num

-- SOURCE_ISSUE: Theorem 8.3 is only valid in the local normalization setting;
-- its standalone wording suppresses the henselian DVR, finite-normalization,
-- and compatibility hypotheses needed for the integral-ring conclusion.  The
-- corrected declaration below makes those hypotheses explicit.
/-- Book §8.5, Theorem 8.3: a separable finite residue extension over a
henselian local DVR has an integrally monogenic normalization. -/
theorem chapter08_local_monogenicity
    {A K B L k l : Type*} [CommRing A] [IsDomain A]
    [IsDiscreteValuationRing A] [HenselianLocalRing A]
    [Field K] [Field L] [Field k] [Field l]
    [CommRing B] [IsDomain B]
    [Algebra A K] [IsFractionRing A K] [Algebra K L]
    [Algebra A B] [Algebra B L] [Algebra A L]
    [IsScalarTower A B L] [IsScalarTower A K L]
    [FiniteDimensional K L]
    [IsIntegralClosure B A L] [IsFractionRing B L]
    [IsDiscreteValuationRing B] [Module.Finite A B]
    [Algebra k l] [Module.Finite k l] [Algebra.IsSeparable k l]
    (hresidue : ∃ eA : IsLocalRing.ResidueField A ≃+* k,
      ∃ eB : IsLocalRing.ResidueField B ≃+* l,
        ∀ a : A,
          eB (IsLocalRing.residue B (algebraMap A B a)) =
            algebraMap k l (eA (IsLocalRing.residue A a))) :
    chapter08Monogenic A B := by
  /- PROOF ROADMAP.
  The two added typeclasses are the missing normalization interface, not new
  mathematics: in applications they come from a finite local integral
  closure.  They expose the uniformizer and fraction-field operations needed
  by the standard Henselian perturbation argument.

  1. The first conjunct of `chapter08Monogenic A B` is
     `IsIntegralClosure.isIntegral A L`.  For the generator, use
     `Field.exists_primitive_element k l` (Mathlib/FieldTheory/PrimitiveElement)
     with `[Module.Finite k l]` and `[Algebra.IsSeparable k l]`.  Via the two
     equivalences in `hresidue`, choose `theta0 : B` whose residue is that
     primitive element (`IsLocalRing.residue_surjective`).
  2. Choose `pi : B` generating `IsLocalRing.maximalIdeal B`, using
     `IsPrincipalIdealRing.principal`; the DVR assumptions ensure the ideal
     is nonzero and proper.  First prove the two-generator claim
     `Algebra.adjoin A {theta0, pi} = top`: reduce modulo the maximal ideal,
     use residue generation for the coefficient-field part, and lift the
     resulting span equality with `IsLocalRing.map_mkQ_eq_top` (or
     `IsLocalRing.map_tensorProduct_mk_eq_top`) from
     Mathlib/RingTheory/LocalRing/Module.  Finiteness of `B` is exactly the
     Nakayama hypothesis.
  3. Package the genuinely missing Henselian-normalization construction as a
     source-local intermediate claim: if `theta0` lifts a separable residue
     generator and `pi` generates the maximal ideal, then there is
     `alpha : B` with both
     `theta0 ∈ Algebra.adjoin A {alpha}` and
     `pi ∈ Algebra.adjoin A {alpha}`.  Its proof is the standard two-stage
     Henselian argument: first use `HenselianLocalRing.is_henselian` and the
     unit derivative of the lifted residue minpoly to form the finite étale
     coefficient subring `C = A[theta0]`; then prove `B = C[pi]` by the
     maximal-ideal filtration and Nakayama, and apply the usual sufficiently
     high uniformizer perturbation to replace `(theta0, pi)` by one element.
     State the intermediate claim with these two membership conclusions and
     with the displayed residue-generation/maximal-ideal hypotheses (rather
     than as an opaque monogenicity axiom), so it is also usable by the
     unramified endpoint.  No declaration in the current import closure
     performs this perturbation; this is the new mathematical core of the
     proof, not an instance-synthesis gap.
     A suitable local signature is
     `henselian_normalization_perturbation (theta0 pi : B)
       (hresgen : Algebra.adjoin k {eB (residue B theta0)} = top)
       (hpi : Ideal.span {pi} = IsLocalRing.maximalIdeal B) :
       ∃ alpha : B, theta0 ∈ Algebra.adjoin A {alpha} ∧
         pi ∈ Algebra.adjoin A {alpha}`;
     keep all ring, tower, finite-normalization, DVR, and residue-equivalence
     parameters exactly those of this theorem.
  4. From step 3 and the two-generator equality, use
     `Algebra.adjoin_le` and `top_unique` to show
     `Algebra.adjoin A {alpha} = top`.  Pair this with integrality of every
     element from `IsIntegralClosure.isIntegral`.

  Dead ends: `IsLocalRing.exists_adjoin_eq_top` requires
  `Algebra.FormallyUnramified A B` and therefore covers only the unramified
  case.  A primitive element of `L/K` would additionally require
  `[Algebra.IsSeparable K L]`, which is deliberately not assumed here.
  -/
  sorry

/-- Book §8.5: every finite extension of a p-adic field is integrally
monogenic over its p-adic valuation ring. -/
theorem chapter08_padic_extensions_are_integrally_monogenic
    (p : ℕ) [Fact p.Prime]
    {L : Type*} [Field L] [CharZero L]
    [Algebra (ℚ_[p]) L] [FiniteDimensional (ℚ_[p]) L]
    [Algebra (ℤ_[p]) L]
    [IsScalarTower (ℤ_[p]) (ℚ_[p]) L] :
    chapter08Monogenic (ℤ_[p]) (integralClosure (ℤ_[p]) L) := by
  /- PROOF ROADMAP.
  This corollary needs no extra public hypotheses; all normalization and
  residue facts follow canonically in mixed characteristic.

  1. Install `Algebra.IsSeparable (ℚ_[p]) L` from `CharZero L` and finite
     dimensionality.  Obtain
     `Module.Finite (ℤ_[p]) (integralClosure (ℤ_[p]) L)` from
     `Chapter11.chapter11_separable_extension_gives_finite_normalization`
     (Book01/Chapter11/Section02FinitenessHypotheses).
  2. With `B := integralClosure (ℤ_[p]) L`, install its standard
     `IsIntegralClosure`, `IsDomain`, and
     `IsFractionRing B L` instances, then obtain `IsLocalRing B` from
     `Chapter01.chapter01_henselian_integral_closure_is_local`
     (Book02/Chapter01/Section02ExistenceUniquenessAndCompleteness).  Combine
     localness with the finite integral closure of the DVR to install
     `IsDiscreteValuationRing B`.
  3. Take
     `k := IsLocalRing.ResidueField (ℤ_[p])` and
     `l := IsLocalRing.ResidueField B`.  The canonical residue algebra and
     compatibility are `IsLocalRing.algebraMap_residue`; residue finiteness
     is the instance `IsLocalRing.finite_of_module_finite`
     (Mathlib/RingTheory/LocalRing/ResidueField/Basic).  The base residue
     field is identified with `ZMod p` by `PadicInt.residueField`, hence is
     finite/perfect; the standard perfect-field instance supplies
     `Algebra.IsSeparable k l`.  Use identity ring equivalences for `eA` and
     `eB` in `hresidue`.
  4. Apply `chapter08_local_monogenicity` with
     `A := ℤ_[p]`, `K := ℚ_[p]`, `B := B`, `L := L`, and the canonical
     residue fields from step 3.  Its conclusion is definitionally the
     required goal.
  -/
  sorry

/-- Book §8.5: if the residue extension is not simple, the normalization
cannot be generated by one integral element. -/
theorem chapter08_non_simple_residue_extension_obstructs_monogenicity
    {A B k l : Type*} [CommRing A] [CommRing B] [Field k] [Field l]
    [Algebra A B] [Algebra k l]
    (ρA : A →+* k) (ρB : B →+* l)
    (hρB : Function.Surjective ρB)
    (hcompat : ∀ a : A,
      ρB (algebraMap A B a) = algebraMap k l (ρA a))
    (hnotSimple : ¬ chapter08ResidueExtensionIsSimple k l) :
    ¬ chapter08Monogenic A B := by
  intro hmono
  rcases hmono.2 with ⟨α, _, hgen⟩
  apply hnotSimple
  exact chapter08_monogenicity_forces_simple_residue_extension
    ρA ρB hρB hcompat α hgen

end

end LastLib.Book02FiniteExtensionsOfLocalFields.Chapter08
