import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter08.Section03UniformizersAndMinimalPolynomials

namespace LastLib.Book02FiniteExtensionsOfLocalFields.Chapter08

noncomputable section

open Polynomial

/-! # 8.5. Monogenicity: what is true and what is not -/

/-- Book §8.5: monogenicity of an integral algebra, with integrality of the
chosen generator made explicit. -/
def chapter08Monogenic
    (A B : Type*) [CommRing A] [CommRing B] [Algebra A B] : Prop :=
  (∀ b : B, IsIntegral A b) ∧
    ∃ α : B, IsIntegral A α ∧ Algebra.adjoin A ({α} : Set B) = ⊤

/-- Monogenicity by one specified element, used to separate field generation
from equality of integral rings. -/
def chapter08MonogenicBy
    (A B : Type*) [CommRing A] [CommRing B] [Algebra A B]
    (α : B) : Prop :=
  IsIntegral A α ∧ Algebra.adjoin A ({α} : Set B) = ⊤

/-- The specified-element version of `B = A[α]` when `B` is the integral
closure inside a field. -/
def chapter08IntegralGeneratorFor
    (A L : Type*) [CommRing A] [Field L] [Algebra A L]
    (α : L) : Prop :=
  IsIntegral A α ∧
    (integralClosure A L : Set L) =
      (Algebra.adjoin A ({α} : Set L) : Set L)

/-- The two-generator presentation `B = A[θ, π_L]` used before the local
monogenicity theorem in Book §8.5. -/
def chapter08TwoGeneratorIntegralPresentation
    (A L : Type*) [CommRing A] [Field L] [Algebra A L]
    (θ πL : L) : Prop :=
  IsIntegral A θ ∧ IsIntegral A πL ∧
    (integralClosure A L : Set L) =
      (Algebra.adjoin A ({θ, πL} : Set L) : Set L)

/-- A finite residue extension is simple in the sense required by reduction of
a one-generator integral algebra. -/
def chapter08ResidueExtensionIsSimple
    (k l : Type*) [Field k] [Field l] [Algebra k l] : Prop :=
  ∃ x : l, Algebra.adjoin k ({x} : Set l) = ⊤

/-- Book §8.5: reduction of a monogenic algebra is generated by the residue
of the same element.  The two surjective reduction maps and their base
compatibility are made explicit. -/
theorem chapter08_monogenicity_forces_simple_residue_extension
    {A B k l : Type*} [CommRing A] [CommRing B] [Field k] [Field l]
    [Algebra A B] [Algebra k l]
    (ρA : A →+* k) (ρB : B →+* l)
    (_hρA : Function.Surjective ρA)
    (hρB : Function.Surjective ρB)
    (hcompat : ∀ a : A,
      ρB (algebraMap A B a) = algebraMap k l (ρA a))
    (α : B) (hmono : Algebra.adjoin A ({α} : Set B) = ⊤) :
    chapter08ResidueExtensionIsSimple k l := by
  refine ⟨ρB α, ?_⟩
  apply top_unique
  intro y hy
  rcases hρB y with ⟨b, rfl⟩
  have hb : b ∈ Algebra.adjoin A ({α} : Set B) := by
    rw [hmono]
    trivial
  refine Algebra.adjoin_induction ?_ ?_ ?_ ?_ hb
  · intro x hx
    have hx' : x = α := Set.mem_singleton_iff.mp hx
    subst x
    exact Algebra.subset_adjoin (by simp)
  · intro r
    rw [hcompat r]
    exact Subalgebra.algebraMap_mem _ _
  · intro x z hx hz hxh hzh
    rw [map_add]
    exact add_mem hxh hzh
  · intro x z hx hz hxh hzh
    rw [map_mul]
    exact mul_mem hxh hzh

/-- A proper integral order generated by a field primitive element is the
precise obstruction to concluding integral monogenicity from field generation.
-/
theorem chapter08_primitive_element_does_not_identify_the_integral_closure
    {A L : Type*} [CommRing A] [IsDomain A] [Field L]
    [Algebra A L]
    (α : L)
    (hproper : (Algebra.adjoin A ({α} : Set L) : Set L) ≠
      (integralClosure A L : Set L)) :
    ¬ chapter08IntegralGeneratorFor A L α := by
  intro hgenerator
  exact hproper hgenerator.2.symm

/-- Book §8.5: a separable residue polynomial lifted over a henselian base
produces an integral generator of the unramified part. -/
theorem chapter08_unramified_lift_is_integrally_monogenic
    {A K L k : Type*} [CommRing A] [IsDomain A]
    [IsDiscreteValuationRing A] [Field K] [Field L] [Field k]
    [Algebra A K] [IsFractionRing A K] [Algebra K L]
    [Algebra A L] [IsScalarTower A K L] [FiniteDimensional K L]
    [Algebra A k] [HenselianLocalRing A]
    (fbar : k[X]) (f : A[X]) (θ : L)
    (hmonic : fbar.Monic ∧ f.Monic)
    (hirreducible : Irreducible fbar)
    (hseparable : fbar.Separable)
    (hlift : f.map (algebraMap A k) = fbar)
    (hroot : aeval θ f = 0)
    (hgen : Algebra.adjoin K ({θ} : Set L) = ⊤)
    (hdegree : Module.finrank K L = fbar.natDegree)
    (hresidue : ∃ e : IsLocalRing.ResidueField A ≃+* k,
      ∀ a : A, algebraMap A k a = e (IsLocalRing.residue A a)) :
    chapter08IntegralGeneratorFor A L θ := by
  sorry

/-- Book §8.5: the totally ramified endpoint is monogenic by any uniformizer.
This is the monogenicity reading of the uniformizer theorem in §8.3. -/
theorem chapter08_totally_ramified_extension_is_integrally_monogenic
    {A K L : Type*} [CommRing A] [IsDomain A]
    [IsDiscreteValuationRing A] [Field K] [Field L]
    [Algebra A K] [IsFractionRing A K] [Algebra K L]
    [Algebra A L] [IsScalarTower A K L] [FiniteDimensional K L]
    (hcomplete : IsAdicComplete (IsLocalRing.maximalIdeal A) A)
    (hfinite : Module.Finite A (integralClosure A L))
    (vK : AddValuation K (WithTop ℤ))
    (vL : AddValuation L (WithTop ℤ))
    (hdiscreteK :
      LastLib.Book01ValuationsDVRsAndCompletions.Chapter10.Chapter10DiscreteAddValuation vK)
    (hdiscreteL :
      LastLib.Book01ValuationsDVRsAndCompletions.Chapter10.Chapter10DiscreteAddValuation vL)
    (hval : vK.IsEquiv (AddValuation.comap (algebraMap K L) vL))
    (htotal : chapter08TotallyRamified vK vL hval)
    (hintegralK : ∀ x : K, IsIntegral A x ↔ 0 ≤ vK x)
    (hintegralL : ∀ x : L, IsIntegral A x ↔ 0 ≤ vL x)
    (πK : A) (hπK : vK (algebraMap A K πK) = 1)
    (πL : L) (hπL : vL πL = 1) :
    chapter08IntegralGeneratorFor A L πL := by
  rcases chapter08_uniformizer_theorem
      hcomplete hfinite vK vL hdiscreteK hdiscreteL hval htotal
      hintegralK hintegralL πK hπK πL hπL with
    ⟨g, _, _, _, _, _, hclosure, _⟩
  refine ⟨?_, hclosure⟩
  apply (hintegralL πL).2
  rw [hπL]
  norm_num

-- SOURCE_ISSUE: Theorem 8.3 is only valid in the local normalization setting;
-- its standalone wording suppresses the henselian DVR, finite-normalization,
-- and compatibility hypotheses needed for the integral-ring conclusion.  The
-- corrected declaration below makes those hypotheses explicit.
/-- Book §8.5, Theorem 8.3: a separable finite residue extension over a
henselian local DVR has an integrally monogenic normalization. -/
theorem chapter08_local_monogenicity
    {A K B L k l : Type*} [CommRing A] [IsDomain A]
    [IsDiscreteValuationRing A] [HenselianLocalRing A]
    [Field K] [Field L] [Field k] [Field l]
    [CommRing B] [IsDomain B] [IsLocalRing B]
    [Algebra A K] [IsFractionRing A K] [Algebra K L]
    [Algebra A B] [Algebra B L] [Algebra A L]
    [IsScalarTower A B L] [IsScalarTower A K L]
    [FiniteDimensional K L]
    [IsIntegralClosure B A L] [Module.Finite A B]
    [Algebra k l] [Module.Finite k l] [Algebra.IsSeparable k l]
    (hresidue : ∃ eA : IsLocalRing.ResidueField A ≃+* k,
      ∃ eB : IsLocalRing.ResidueField B ≃+* l,
        ∀ a : A,
          eB (IsLocalRing.residue B (algebraMap A B a)) =
            algebraMap k l (eA (IsLocalRing.residue A a))) :
    chapter08Monogenic A B := by
  sorry

/-- Book §8.5: every finite extension of a p-adic field is integrally
monogenic over its p-adic valuation ring. -/
theorem chapter08_padic_extensions_are_integrally_monogenic
    (p : ℕ) [Fact p.Prime]
    {L : Type*} [Field L] [CharZero L]
    [Algebra (ℚ_[p]) L] [FiniteDimensional (ℚ_[p]) L]
    [Algebra (ℤ_[p]) L]
    [IsScalarTower (ℤ_[p]) (ℚ_[p]) L] :
    chapter08Monogenic (ℤ_[p]) (integralClosure (ℤ_[p]) L) := by
  sorry

/-- Book §8.5: if the residue extension is not simple, the normalization
cannot be generated by one integral element. -/
theorem chapter08_non_simple_residue_extension_obstructs_monogenicity
    {A B k l : Type*} [CommRing A] [CommRing B] [Field k] [Field l]
    [Algebra A B] [Algebra k l]
    (ρA : A →+* k) (ρB : B →+* l)
    (hρA : Function.Surjective ρA)
    (hρB : Function.Surjective ρB)
    (hcompat : ∀ a : A,
      ρB (algebraMap A B a) = algebraMap k l (ρA a))
    (hnotSimple : ¬ chapter08ResidueExtensionIsSimple k l) :
    ¬ chapter08Monogenic A B := by
  intro hmono
  rcases hmono.2 with ⟨α, _, hgen⟩
  apply hnotSimple
  exact chapter08_monogenicity_forces_simple_residue_extension
    ρA ρB hρA hρB hcompat α hgen

end

end LastLib.Book02FiniteExtensionsOfLocalFields.Chapter08
