import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter08.Section01TheMeaningOfTotalRamification
import LastLib.Book01ValuationsDVRsAndCompletions.Chapter12

namespace LastLib.Book02FiniteExtensionsOfLocalFields.Chapter08

noncomputable section

open Polynomial
open scoped BigOperators WithTop

/-! # 8.2. Why Eisenstein coefficients have their shape -/

/-- The power-basis expression used in the integral-basis conclusion of
Book §8.2. -/
def chapter08PowerBasisExpansion
    {A L : Type*} [CommRing A] [Ring L] [Algebra A L]
    {n : ℕ} (α : L) (a : Fin n → A) : L :=
  ∑ i, algebraMap A L (a i) * α ^ (i : ℕ)

/-- Book §8.2: in a normalized DVR, the coefficient condition and the
valuation condition are equivalent formulations of Eisenstein. -/
theorem chapter08_eisenstein_coefficient_valuation_form
    {A K : Type*} [CommRing A] [IsDomain A]
    [IsDiscreteValuationRing A] [Field K]
    [Algebra A K] [IsFractionRing A K]
    (vK : AddValuation K (WithTop ℤ)) (π : A) (g : A[X])
    (hvalue_ideal : ∀ a : A,
      a ∈ IsLocalRing.maximalIdeal A ↔
        0 < vK (algebraMap A K a))
    (hvalue_square : ∀ a : A,
      a ∈ IsLocalRing.maximalIdeal A ∧
        a ∉ (IsLocalRing.maximalIdeal A) ^ 2 ↔
        vK (algebraMap A K a) = 1) :
    LastLib.Book01ValuationsDVRsAndCompletions.Chapter12.IsEisensteinAt π g ↔
      g.Monic ∧ 0 < g.natDegree ∧
        (∀ i < g.natDegree,
          0 < vK (algebraMap A K (g.coeff i))) ∧
        vK (algebraMap A K g.constantCoeff) = 1 := by
  sorry

/-- Book §8.2, Theorem 8.1: an Eisenstein root gives an irreducible
polynomial, a totally ramified extension of the polynomial degree, a
uniformizer, and the full integral order. -/
theorem chapter08_eisenstein_extension
    {A K L : Type*} [CommRing A] [IsDomain A]
    [IsDiscreteValuationRing A] [Field K] [Field L]
    [Algebra A K] [IsFractionRing A K] [Algebra K L]
    [Algebra A L] [IsScalarTower A K L] [FiniteDimensional K L]
    (vK : AddValuation K (WithTop ℤ))
    (vL : AddValuation L (WithTop ℤ))
    (hval : vK.IsEquiv (AddValuation.comap (algebraMap K L) vL))
    (π : A) (g : A[X]) (α : L)
    (hf : LastLib.Book01ValuationsDVRsAndCompletions.Chapter12.IsEisensteinAt π g)
    (hroot : aeval α g = 0)
    (hgen : Algebra.adjoin K ({α} : Set L) = ⊤)
    (hrestrict : ∀ x : K, x ≠ 0 →
      vL (algebraMap K L x) = g.natDegree • vK x)
    (hπ : vK (algebraMap A K π) = 1) :
    Irreducible (g.map (algebraMap A K)) ∧
      Module.finrank K L = g.natDegree ∧
      chapter08TotallyRamified vK vL hval ∧
      vL α = 1 ∧
      (integralClosure A L : Set L) =
        (Algebra.adjoin A ({α} : Set L) : Set L) ∧
      (∀ x : L, IsIntegral A x →
        ∃! a : Fin g.natDegree → A,
          x = chapter08PowerBasisExpansion α a) := by
  sorry

/-- The additive value of the `i`th term in a root equation. -/
def chapter08RootEquationTermValue
    {K L Γ : Type*} [Field K] [Field L]
    [LinearOrderedAddCommGroupWithTop Γ] [Algebra K L]
    (vL : AddValuation L Γ) (a : K) (α : L) (i : ℕ) : Γ :=
  vL (algebraMap K L a) + i • vL α

/-- A strictly least nonzero additive-valued term cannot cancel in a finite
sum, the additive form of the key Newton-polygon calculation in Book §8.2. -/
theorem chapter08_strictly_least_valued_term_does_not_cancel
    {L Γ : Type*} [Field L]
    [LinearOrderedAddCommGroupWithTop Γ]
    (v : AddValuation L Γ) {ι : Type*} [Fintype ι]
    (terms : ι → L) (i₀ : ι)
    (hnonzero : terms i₀ ≠ 0)
    (hleast : ∀ j, j ≠ i₀ → v (terms i₀) < v (terms j)) :
    v (∑ i, terms i) = v (terms i₀) := by
  sorry

/-- Book §8.2: after extending a normalized valuation to a root field, the
root of an Eisenstein polynomial has value `1/n`. -/
theorem chapter08_eisenstein_root_has_reciprocal_value
    {A K L : Type*} [CommRing A] [IsDomain A]
    [IsDiscreteValuationRing A] [Field K] [Field L]
    [Algebra A K] [IsFractionRing A K] [Algebra K L]
    [Algebra A L] [IsScalarTower A K L]
    (vK : AddValuation K (WithTop ℚ))
    (vL : AddValuation L (WithTop ℚ))
    (hrestrict : ∀ x : K, vL (algebraMap K L x) = vK x)
    (n : ℕ) (hn : 0 < n) (g : A[X]) (α : L)
    (hdegree : g.natDegree = n)
    (hmonic : g.Monic)
    (hcoeff : ∀ i < n, 0 < vK (algebraMap A K (g.coeff i)))
    (hconstant : vK (algebraMap A K g.constantCoeff) = 1)
    (hroot : aeval α g = 0) :
    vL α = ((1 : ℚ) / (n : ℚ) : WithTop ℚ) := by
  sorry

/-- Book §8.2: the value group generated by an Eisenstein root contains the
fractional lattice `(1/n)ℤ`. -/
theorem chapter08_eisenstein_value_group_contains_fractional_lattice
    {L : Type*} [Field L]
    (vL : AddValuation L (WithTop ℚ))
    (n : ℕ) (hn : n ≠ 0) (α : L) (hα : α ≠ 0)
    (hvalue : vL α = ((1 : ℚ) / (n : ℚ) : WithTop ℚ)) :
    ∀ z : ℤ, ∃ x : L,
      vL x = ((z : ℚ) / (n : ℚ) : WithTop ℚ) := by
  sorry

/-- Book §8.2: the value-group lower bound and the root-equation upper bound
force the degree of an Eisenstein extension to be exactly `n`. -/
theorem chapter08_eisenstein_value_group_forces_degree
    {K L : Type*} [Field K] [Field L] [Algebra K L]
    [FiniteDimensional K L]
    (vK : AddValuation K (WithTop ℚ))
    (vL : AddValuation L (WithTop ℚ))
    (hval : vK.IsEquiv (AddValuation.comap (algebraMap K L) vL))
    (hrestrict : ∀ x : K, x ≠ 0 →
      vL (algebraMap K L x) = vK x)
    (n : ℕ) (hn : 0 < n) (πK : K)
    (hπK : vK πK = 1)
    (hbase : ∀ x : K, x ≠ 0 →
      ∃ z : ℤ, vK x = ((z : ℚ) : WithTop ℚ))
    (hvalue_group : ∀ z : ℤ, ∃ x : L,
      vL x = ((z : ℚ) / (n : ℚ) : WithTop ℚ))
    (hupper : Module.finrank K L ≤ n) :
    n ≤ Module.finrank K L ∧ Module.finrank K L = n := by
  sorry

/-- Distinctness of the valuation residues used in the Eisenstein basis
calculation (Book 2, Section 8.2). -/
theorem chapter08_eisenstein_terms_distinct_mod_degree
    (n : ℕ) (ω : ℕ → ℤ) (a : Fin n → ℕ) :
    ∀ i j : Fin n, i ≠ j →
      ((n : ℤ) * ω (a i) + (i : ℤ)) % (n : ℤ) ≠
        ((n : ℤ) * ω (a j) + (j : ℤ)) % (n : ℤ) := by
  sorry

/-- Integrality of an Eisenstein power-basis expansion is coefficientwise
integrality (Book 2, Section 8.2). -/
theorem chapter08_eisenstein_expansion_integrality_iff
    {A K L : Type*} [CommRing A] [IsDomain A]
    [IsDiscreteValuationRing A] [Field K] [Field L]
    [Algebra A K] [IsFractionRing A K] [Algebra K L]
    [Algebra A L] [IsScalarTower A K L]
    {n : ℕ} (π : A) (f : A[X]) (varpi : L)
    (hf : LastLib.Book01ValuationsDVRsAndCompletions.Chapter12.IsEisensteinAt π f)
    (hroot : aeval varpi f = 0)
    (hdegree : f.natDegree = n)
    (hgenerates : Algebra.adjoin K ({varpi} : Set L) = ⊤)
    (a : Fin n → K) :
    IsIntegral A (LastLib.Book01ValuationsDVRsAndCompletions.Chapter12.eisensteinExpansion varpi a) ↔
      ∀ i, IsLocalization.IsInteger A (a i) := by
  sorry

end

end LastLib.Book02FiniteExtensionsOfLocalFields.Chapter08
