import Mathlib.AlgebraicGeometry.Fiber
import Mathlib.AlgebraicGeometry.Morphisms.Affine
import Mathlib.AlgebraicGeometry.Morphisms.ClosedImmersion
import Mathlib.AlgebraicGeometry.Morphisms.Descent
import Mathlib.AlgebraicGeometry.Morphisms.Etale
import Mathlib.AlgebraicGeometry.Morphisms.Finite
import Mathlib.AlgebraicGeometry.Morphisms.FinitePresentation
import Mathlib.AlgebraicGeometry.Morphisms.FlatRank
import Mathlib.AlgebraicGeometry.Morphisms.FlatMono
import Mathlib.AlgebraicGeometry.Morphisms.FormallyUnramified
import Mathlib.AlgebraicGeometry.Morphisms.Immersion
import Mathlib.AlgebraicGeometry.Morphisms.IsIso
import Mathlib.AlgebraicGeometry.Morphisms.OpenImmersion
import Mathlib.AlgebraicGeometry.Morphisms.Proper
import Mathlib.AlgebraicGeometry.Morphisms.QuasiCompact
import Mathlib.AlgebraicGeometry.Morphisms.QuasiSeparated
import Mathlib.AlgebraicGeometry.Morphisms.Separated
import Mathlib.AlgebraicGeometry.Morphisms.SmoothFiber
import Mathlib.AlgebraicGeometry.Morphisms.UniversallyClosed
import Mathlib.AlgebraicGeometry.Morphisms.UnderlyingMap
import Mathlib.AlgebraicGeometry.Sites.Fpqc
import Mathlib.CategoryTheory.Comma.Arrow
import Mathlib.CategoryTheory.Comma.Over.Pullback
import Mathlib.CategoryTheory.Limits.Shapes.Equalizers
import Mathlib.CategoryTheory.Limits.Shapes.Diagonal
import Mathlib.CategoryTheory.Limits.Types.Equalizers
import Mathlib.RingTheory.RingHom.FaithfullyFlat

/-!
# Chapter 10: morphisms and properties local on the base

The source chapter uses the fpqc topology both as a topology generated by families and through a
single faithfully flat, quasi-compact, surjective morphism.  This dependency layer keeps those two
interfaces separate, then packages scheme-over-a-base notation and the canonical base-change maps
used by the four source-order sections.
-/

namespace LastLib.Book10FaithfullyFlatDescentInAlgebraicGeometry.Chapter10

open CategoryTheory CategoryTheory.Limits AlgebraicGeometry
open scoped AlgebraicGeometry

noncomputable section

universe u v

/-! ## Covering data -/

/-- The single-morphism form of an fpqc cover used by the descent statements. -/
structure Chapter10FpqcCover {S T : Scheme.{u}} (p : T ⟶ S) : Prop where
  surjective : Surjective p
  flat : Flat p
  quasiCompact : QuasiCompact p

attribute [instance] Chapter10FpqcCover.surjective Chapter10FpqcCover.flat
  Chapter10FpqcCover.quasiCompact

/-- A family of flat morphisms with finite control over every quasi-compact open of the base. -/
structure Chapter10FpqcCoverFamily (S : Scheme.{u}) (I : Type v) where
  source : I → Scheme.{u}
  map : ∀ i, source i ⟶ S
  flat : ∀ i, Flat (map i)
  jointlySurjective : ∀ s : S, ∃ i (x : source i), map i x = s
  finiteControl : ∀ (U : S.Opens), IsCompact (U : Set S) →
    ∃ (F : Finset I) (V : ∀ i, (source i).Opens),
      (∀ i, i ∈ F → IsCompact (V i : Set (source i))) ∧
        (U : Set S) ⊆ ⋃ i ∈ F, (map i).base '' (V i : Set (source i))

/-- A jointly surjective fppf family. -/
structure Chapter10FppfCoverFamily (S : Scheme.{u}) (I : Type v) where
  source : I → Scheme.{u}
  map : ∀ i, source i ⟶ S
  flat : ∀ i, Flat (map i)
  locallyOfFinitePresentation : ∀ i, LocallyOfFinitePresentation (map i)
  jointlySurjective : ∀ s : S, ∃ i (x : source i), map i x = s

/-- The morphism property underlying the single-morphism fpqc convention. -/
abbrev chapter10FpqcMorphismProperty : MorphismProperty Scheme.{u} :=
  @Surjective ⊓ @Flat ⊓ @QuasiCompact

/-- The explicit proposition corresponding to `Chapter10FpqcCover`. -/
def chapter10IsFpqc {S T : Scheme.{u}} (p : T ⟶ S) : Prop :=
  Surjective p ∧ Flat p ∧ QuasiCompact p

theorem chapter10FpqcCover_iff {S T : Scheme.{u}} (p : T ⟶ S) :
    Chapter10FpqcCover p ↔ chapter10IsFpqc p := by
  sorry

/-- A quasi-compact, surjective, flat morphism gives a singleton family cover. -/
def chapter10SingletonFpqcFamily {S T : Scheme.{u}} (p : T ⟶ S)
    (hp : Chapter10FpqcCover p) : Chapter10FpqcCoverFamily S PUnit.{v} where
  source _ := T
  map _ := p
  flat _ := hp.flat
  jointlySurjective s := by
    obtain ⟨x, hx⟩ := hp.surjective.surj s
    exact ⟨PUnit.unit, x, hx⟩
  finiteControl := by
    intro U hU
    sorry

/-- Every fppf covering family is fpqc in the family sense. -/
theorem chapter10_fppfFamily_is_fpqc
    {S : Scheme.{u}} {I : Type v} (𝒞 : Chapter10FppfCoverFamily S I) :
    Chapter10FpqcCoverFamily S I := by
  sorry

/-- The affine singleton form of faithful flatness. -/
def chapter10FaithfullyFlatRingHom {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) : Prop :=
  φ.FaithfullyFlat

theorem chapter10_affine_fpqc_iff_faithfullyFlat
    {R S : CommRingCat.{u}} (φ : R ⟶ S) :
    chapter10IsFpqc (Spec.map φ) ↔ φ.hom.FaithfullyFlat := by
  sorry

/-! ## Schemes over a base and pullback notation -/

/-- A scheme equipped with a specified morphism to a fixed base. -/
structure Chapter10SchemeOver (S : Scheme.{u}) where
  scheme : Scheme.{u}
  toBase : scheme ⟶ S

/-- The corresponding object of the categorical over category. -/
abbrev chapter10OverObject {S : Scheme.{u}} (X : Chapter10SchemeOver S) : Over S :=
  Over.mk X.toBase

/-- Morphisms over the base, i.e. the source notation `Hom_S(X,Y)`. -/
abbrev chapter10OverHom {S : Scheme.{u}}
    (X Y : Chapter10SchemeOver S) : Type u :=
  chapter10OverObject X ⟶ chapter10OverObject Y

/-- The underlying scheme-theoretic base change of a morphism. -/
abbrev chapter10BaseChange {X S T : Scheme.{u}} (f : X ⟶ S) (p : T ⟶ S) : Scheme.{u} :=
  pullback f p

/-- The projection from the base change to the original source. -/
abbrev chapter10BaseChangeToSource {X S T : Scheme.{u}} (f : X ⟶ S) (p : T ⟶ S) :
    chapter10BaseChange f p ⟶ X :=
  pullback.fst f p

/-- The base-changed morphism `X_T ⟶ T`. -/
abbrev chapter10BaseChangeMorphism {X S T : Scheme.{u}} (f : X ⟶ S) (p : T ⟶ S) :
    chapter10BaseChange f p ⟶ T :=
  pullback.snd f p

@[simp, reassoc]
theorem chapter10BaseChange_condition {X S T : Scheme.{u}} (f : X ⟶ S) (p : T ⟶ S) :
    chapter10BaseChangeToSource f p ≫ f = chapter10BaseChangeMorphism f p ≫ p :=
  pullback.condition

/-- Base change of an object over `S`, expressed in the canonical over category. -/
abbrev chapter10BaseChangeOver {S T : Scheme.{u}} (p : T ⟶ S)
    (X : Chapter10SchemeOver S) : Over T :=
  (Over.pullback p).obj (chapter10OverObject X)

/-- Pullback of a morphism over `S` to a morphism over `T`. -/
def chapter10BaseChangeOverHom {S T : Scheme.{u}} (p : T ⟶ S)
    {X Y : Chapter10SchemeOver S} (f : chapter10OverHom X Y) :
    chapter10BaseChangeOver p X ⟶ chapter10BaseChangeOver p Y :=
  (Over.pullback p).map f

/-- The double overlap `T^[1] = T ×_S T`. -/
abbrev chapter10DoubleOverlap {S T : Scheme.{u}} (p : T ⟶ S) : Scheme.{u} :=
  pullback p p

abbrev chapter10DoubleOverlapFirst {S T : Scheme.{u}} (p : T ⟶ S) :
    chapter10DoubleOverlap p ⟶ T :=
  pullback.fst p p

abbrev chapter10DoubleOverlapSecond {S T : Scheme.{u}} (p : T ⟶ S) :
    chapter10DoubleOverlap p ⟶ T :=
  pullback.snd p p

@[simp, reassoc]
theorem chapter10DoubleOverlap_condition {S T : Scheme.{u}} (p : T ⟶ S) :
    chapter10DoubleOverlapFirst p ≫ p = chapter10DoubleOverlapSecond p ≫ p :=
  pullback.condition

/-- The canonical comparison between the two iterated pullbacks of an object over `S` to the
double overlap. -/
noncomputable def chapter10DoubleOverlapComparison {S T : Scheme.{u}} (p : T ⟶ S)
    (X : Chapter10SchemeOver S) :
    (Over.pullback (chapter10DoubleOverlapFirst p)).obj (chapter10BaseChangeOver p X) ≅
      (Over.pullback (chapter10DoubleOverlapSecond p)).obj (chapter10BaseChangeOver p X) := by
  exact
    ((Over.pullbackComp (chapter10DoubleOverlapFirst p) p).hom.app
        (chapter10OverObject X)).symm ≪≫
      eqToIso (congrArg
        (fun q : chapter10DoubleOverlap p ⟶ S =>
          (Over.pullback q).obj (chapter10OverObject X))
        (chapter10DoubleOverlap_condition p)) ≪≫
      (Over.pullbackComp (chapter10DoubleOverlapSecond p) p).hom.app
        (chapter10OverObject X)

/-- The two chosen overlap objects, exposed so subsequent equalities do not rely on definitional
identification of the two pullback presentations. -/
abbrev chapter10OverlapFirstObject {S T : Scheme.{u}} (p : T ⟶ S)
    (X : Chapter10SchemeOver S) : Over (chapter10DoubleOverlap p) :=
  (Over.pullback (chapter10DoubleOverlapFirst p)).obj (chapter10BaseChangeOver p X)

abbrev chapter10OverlapSecondObject {S T : Scheme.{u}} (p : T ⟶ S)
    (X : Chapter10SchemeOver S) : Over (chapter10DoubleOverlap p) :=
  (Over.pullback (chapter10DoubleOverlapSecond p)).obj (chapter10BaseChangeOver p X)

/-- Restriction of an upstairs morphism to the first projection of the double overlap. -/
def chapter10OverlapFirstHom {S T : Scheme.{u}} (p : T ⟶ S)
    {X Y : Chapter10SchemeOver S}
    (u : chapter10BaseChangeOver p X ⟶ chapter10BaseChangeOver p Y) :
    chapter10OverlapFirstObject p X ⟶ chapter10OverlapFirstObject p Y :=
  (Over.pullback (chapter10DoubleOverlapFirst p)).map u

/-- Restriction of an upstairs morphism to the second projection of the double overlap. -/
def chapter10OverlapSecondHom {S T : Scheme.{u}} (p : T ⟶ S)
    {X Y : Chapter10SchemeOver S}
    (u : chapter10BaseChangeOver p X ⟶ chapter10BaseChangeOver p Y) :
    chapter10OverlapSecondObject p X ⟶ chapter10OverlapSecondObject p Y :=
  (Over.pullback (chapter10DoubleOverlapSecond p)).map u

/-- Transport the second restriction back to the first chosen overlap objects. -/
def chapter10OverlapSecondHomTransported {S T : Scheme.{u}} (p : T ⟶ S)
    {X Y : Chapter10SchemeOver S}
    (u : chapter10BaseChangeOver p X ⟶ chapter10BaseChangeOver p Y) :
    chapter10OverlapFirstObject p X ⟶ chapter10OverlapFirstObject p Y :=
  (chapter10DoubleOverlapComparison p X).hom ≫ chapter10OverlapSecondHom p u ≫
    (chapter10DoubleOverlapComparison p Y).inv

/-- Restriction to the first overlap of a morphism already defined over the base. -/
def chapter10DownstairsOverlapFirstHom {S T : Scheme.{u}} (p : T ⟶ S)
    {X Y : Chapter10SchemeOver S} (f : chapter10OverHom X Y) :
    chapter10OverlapFirstObject p X ⟶ chapter10OverlapFirstObject p Y :=
  chapter10OverlapFirstHom p (chapter10BaseChangeOverHom p f)

/-- Restriction to the second overlap of a morphism already defined over the base, transported to
the first chosen overlap objects. -/
def chapter10DownstairsOverlapSecondHom {S T : Scheme.{u}} (p : T ⟶ S)
    {X Y : Chapter10SchemeOver S} (f : chapter10OverHom X Y) :
    chapter10OverlapFirstObject p X ⟶ chapter10OverlapFirstObject p Y :=
  chapter10OverlapSecondHomTransported p (chapter10BaseChangeOverHom p f)

/-- The overlap compatibility condition for a morphism on the cover. -/
def chapter10DescentCompatible {S T : Scheme.{u}} (p : T ⟶ S)
    {X Y : Chapter10SchemeOver S} (u : chapter10BaseChangeOver p X ⟶
      chapter10BaseChangeOver p Y) : Prop :=
  chapter10OverlapFirstHom p u = chapter10OverlapSecondHomTransported p u

/-- A morphism together with its Cech-overlap compatibility. -/
structure Chapter10MorphismDescentData {S T : Scheme.{u}} (p : T ⟶ S)
    (X Y : Chapter10SchemeOver S) where
  upstairs : chapter10BaseChangeOver p X ⟶ chapter10BaseChangeOver p Y
  compatible : chapter10DescentCompatible p upstairs

/-- The equalizer fork for morphisms over a faithfully flat cover. -/
noncomputable def chapter10HomEqualizerFork {S T : Scheme.{u}}
    (p : T ⟶ S) (X Y : Chapter10SchemeOver S) :
    Fork (fun u : chapter10BaseChangeOver p X ⟶ chapter10BaseChangeOver p Y =>
        chapter10OverlapFirstHom p u)
      (fun u : chapter10BaseChangeOver p X ⟶ chapter10BaseChangeOver p Y =>
        chapter10OverlapSecondHomTransported p u) :=
  Fork.ofι (fun f : chapter10OverHom X Y => chapter10BaseChangeOverHom p f) (by
    sorry)

/-! ## Morphism properties used by the table -/

/-- Finite type and finite presentation in the source's separated form. -/
def chapter10FiniteType {X S : Scheme.{u}} (f : X ⟶ S) : Prop :=
  LocallyOfFiniteType f ∧ QuasiCompact f

def chapter10FinitePresentation {X S : Scheme.{u}} (f : X ⟶ S) : Prop :=
  LocallyOfFinitePresentation f ∧ QuasiCompact f

/-- Finite locally free of constant rank `r`, expressed through Mathlib's finite-flat rank API. -/
def chapter10FiniteLocallyFreeOfRank {X S : Scheme.{u}} (f : X ⟶ S) (r : ℕ) : Prop :=
  IsFinite f ∧ Flat f ∧ LocallyOfFinitePresentation f ∧
    ∀ s : S, Scheme.Hom.finrank f s = r

/-- The book-facing unramified condition: locally of finite type and open diagonal. -/
def chapter10Unramified {X S : Scheme.{u}} (f : X ⟶ S) : Prop :=
  LocallyOfFiniteType f ∧ IsOpenImmersion (pullback.diagonal f)

/-- Geometric regularity of a fiber, represented by the canonical smoothness test over its residue
field.  In the pinned Mathlib snapshot this is the available finite-presentation interface for the
fiber criterion; it is a book-facing placeholder for a future standalone geometric-regularity
predicate. -/
def chapter10GeometricallyRegularFiber {X S : Scheme.{u}} (f : X ⟶ S) (s : S) : Prop :=
  Smooth (f.fiberToSpecResidueField s)

def chapter10GeometricallyRegularFibers {X S : Scheme.{u}} (f : X ⟶ S) : Prop :=
  ∀ s : S, chapter10GeometricallyRegularFiber f s

/-- The corresponding ring-level fiber test used for faithfully flat field extensions.  This uses
the same finite-presentation smoothness proxy as `chapter10GeometricallyRegularFiber`. -/
def chapter10GeometricallyRegularAlgebra (K A : Type u) [Field K] [CommRing A]
    [Algebra K A] : Prop :=
  Smooth (Spec.map (CommRingCat.ofHom (algebraMap K A)))

/-- A base property is fpqc local on the base when it can be recognized after every single fpqc
cover. -/
def chapter10FpqcLocalOnBase (P : MorphismProperty Scheme.{u}) : Prop :=
  ∀ {X S T : Scheme.{u}} (f : X ⟶ S) (p : T ⟶ S),
    Chapter10FpqcCover p →
      (P f ↔ P (chapter10BaseChangeMorphism f p))

/-- Explicit ascent along base change, useful when a descent theorem supplies only the reverse
direction. -/
def chapter10StableUnderBaseChange (P : MorphismProperty Scheme.{u}) : Prop :=
  ∀ {X S T : Scheme.{u}} (f : X ⟶ S) (p : T ⟶ S),
    P f → P (chapter10BaseChangeMorphism f p)

/-- Locality on the source, target, or both sides of a morphism. -/
def chapter10LocalOnSource (P : MorphismProperty Scheme.{u}) : Prop :=
  ∀ {X Y : Scheme.{u}} (f : X ⟶ Y) (𝒰 : X.OpenCover),
    P f ↔ ∀ i, P (𝒰.f i ≫ f)

def chapter10LocalOnTarget (P : MorphismProperty Scheme.{u}) : Prop :=
  ∀ {X Y : Scheme.{u}} (f : X ⟶ Y) (𝒰 : Y.OpenCover),
    P f ↔ ∀ i, P (chapter10BaseChangeMorphism f (𝒰.f i))

def chapter10LocalOnSourceAndTarget (P : MorphismProperty Scheme.{u}) : Prop :=
  chapter10LocalOnSource P ∧ chapter10LocalOnTarget P

end

end LastLib.Book10FaithfullyFlatDescentInAlgebraicGeometry.Chapter10
