import LastLib.Book01ValuationsDVRsAndCompletions.Chapter10.Section01TheExtensionProblem
import Mathlib.RingTheory.Henselian
import Mathlib.RingTheory.AdicCompletion.Basic
import Mathlib.RingTheory.AdicCompletion.Algebra
import Mathlib.RingTheory.AdicCompletion.Topology
import Mathlib.RingTheory.AdicCompletion.Completeness
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.RingTheory.Localization.Basic
import Mathlib.RingTheory.Localization.FractionRing
import Mathlib.RingTheory.DedekindDomain.Basic
import Mathlib.RingTheory.DedekindDomain.Dvr
import Mathlib.RingTheory.Valuation.Basic
import Mathlib.RingTheory.Valuation.ValuationRing
import Mathlib.RingTheory.Valuation.Extension
import Mathlib.RingTheory.Valuation.Integral
import Mathlib.RingTheory.Valuation.Discrete.RankOne
import Mathlib.RingTheory.DiscreteValuationRing.Basic
import Mathlib.RingTheory.TensorProduct.Basic
import Mathlib.RingTheory.TensorProduct.Finite
import Mathlib.RingTheory.Finiteness.Basic
import Mathlib.RingTheory.QuasiFinite.Basic
import Mathlib.RingTheory.Polynomial.Eisenstein.Criterion
import Mathlib.RingTheory.RamificationInertia.Basic
import Mathlib.RingTheory.Polynomial.Resultant.Basic
import Mathlib.FieldTheory.Separable
import Mathlib.FieldTheory.IsAlgClosed.AlgebraicClosure
import Mathlib.FieldTheory.AlgebraicClosure
import Mathlib.LinearAlgebra.Dimension.Finite
import Mathlib.LinearAlgebra.Charpoly.Basic
import Mathlib.Analysis.Normed.Field.Basic
import Mathlib.Analysis.Normed.Field.Lemmas
import Mathlib.Analysis.Normed.Unbundled.FiniteExtension
import Mathlib.Topology.Algebra.Polynomial
import Mathlib.Topology.Algebra.Valued.ValuedField
import Mathlib.RingTheory.Polynomial.Eisenstein.Basic
import Mathlib.Tactic.NormNum
import Mathlib.Tactic.Ring
import Mathlib.Tactic.Positivity
import Mathlib.Tactic.FieldSimp
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.GCongr

namespace LastLib.Book01ValuationsDVRsAndCompletions.Chapter12

noncomputable section

open Function Ideal IsLocalRing Polynomial
open Filter Topology
open scoped BigOperators TensorProduct WithZero Polynomial

universe u

/-! Shared Chapter 12 interfaces.  Section files import this module directly so
    their dependency graph follows mathematical API needs rather than prose order. -/

/-- The `I`-adic quotient used at finite precision. -/
abbrev adicQuotient (R : Type u) [CommRing R] (I : Ideal R) (n : ℕ) : Type u :=
  R ⧸ I ^ n

/-- The completion of a ring at a specified ideal. -/
abbrev chapterAdicCompletion (R : Type u) [CommRing R] (I : Ideal R) : Type u :=
  AdicCompletion I R

/-- The localization attached to a candidate branch prime. -/
abbrev branchLocalization (B : Type*) [CommRing B] (P : Ideal B) [P.IsPrime] : Type _ :=
  Localization P.primeCompl

/-- The completion of the localized branch at the image of its prime. -/
abbrev branchCompletion (B : Type*) [CommRing B] (P : Ideal B) [P.IsPrime] : Type _ :=
  AdicCompletion
    (Ideal.map (algebraMap B (branchLocalization B P)) P)
    (branchLocalization B P)

/-- The fraction field of the completed localized branch. -/
abbrev branchFractionField (B : Type*) [CommRing B] (P : Ideal B) [P.IsPrime] : Type _ :=
  FractionRing (branchCompletion B P)

/-- The fraction field of the completion at an ideal. -/
abbrev completionFractionField (R : Type u) [CommRing R] (I : Ideal R) : Type u :=
  FractionRing (AdicCompletion I R)

/-- The principal ideal generated by a power of an element. -/
def principalPowerIdeal {R : Type*} [CommRing R] (π : R) (n : ℕ) : Ideal R :=
  Ideal.span {π ^ n}

/-- The extension to `B` of a principal power from an `A`-algebra. -/
def extendedPrincipalPowerIdeal
    (A B : Type*) [CommRing A] [CommRing B] [Algebra A B]
    (π : A) (n : ℕ) : Ideal B :=
  Ideal.span {(algebraMap A B π) ^ n}

/-- Pairwise coprimality of a finite family of ideals. -/
def pairwiseCoprimeIdeals {ι R : Type*} [CommRing R]
    (I : ι → Ideal R) : Prop :=
  Pairwise (fun i j => IsCoprime (I i) (I j))

/-- Cofinality of two ideal filtrations. -/
def adicFiltrationsCofinal {R : Type*} [CommRing R]
    (I J : Ideal R) : Prop :=
  (∀ n : ℕ, ∃ m : ℕ, I ^ m ≤ J ^ n) ∧
    (∀ n : ℕ, ∃ m : ℕ, J ^ m ≤ I ^ n)

/-! Cofinal adic filtrations have the same inverse-limit completion. -/
theorem adic_completion_equiv_of_cofinal_filtrations
    {R : Type*} [CommRing R] (I J : Ideal R)
    (hcofinal : adicFiltrationsCofinal I J) :
    Nonempty (AdicCompletion I R ≃+* AdicCompletion J R) := by
  classical
  let cIJ : ℕ → ℕ := fun n => Classical.choose (hcofinal.1 n)
  have hcIJ (n : ℕ) : I ^ cIJ n ≤ J ^ n :=
    Classical.choose_spec (hcofinal.1 n)
  let a : ℕ → ℕ := fun n =>
    Nat.rec (max 0 (cIJ 0))
      (fun n k => max k (max (n + 1) (cIJ (n + 1)))) n
  have hca (n : ℕ) : cIJ n ≤ a n := by
    induction n with
    | zero => exact le_max_right _ _
    | succ n ih =>
        change cIJ (n + 1) ≤ max (a n) (max (n + 1) (cIJ (n + 1)))
        exact le_trans (le_max_right _ _) (le_max_right _ _)
  have hna (n : ℕ) : n ≤ a n := by
    induction n with
    | zero => exact Nat.zero_le _
    | succ n ih =>
        change n + 1 ≤ max (a n) (max (n + 1) (cIJ (n + 1)))
        exact le_trans (le_max_left _ _) (le_max_right _ _)
  have haa (n : ℕ) : a n ≤ a (n + 1) := by
    change a n ≤ max (a n) (max (n + 1) (cIJ (n + 1)))
    exact le_max_left _ _
  have hmono_a : Monotone a := monotone_nat_of_le_succ haa
  have ha (n : ℕ) : I ^ a n ≤ J ^ n := by
    exact (Ideal.pow_le_pow_right (hca n)).trans (hcIJ n)
  let factorMap (S T : Ideal R) (hST : S ≤ T) :
      R ⧸ S →+* R ⧸ T :=
    Ideal.Quotient.factor hST
  have factorMap_comp (S T U : Ideal R) (hST : S ≤ T) (hTU : T ≤ U)
      (x : R ⧸ S) :
      factorMap T U hTU (factorMap S T hST x) =
        factorMap S U (hST.trans hTU) x := by
    simp [factorMap]
  have htrans (L : Ideal R) {m n : ℕ} (hmn : m ≤ n)
      (x : AdicCompletion L R) :
      Ideal.Quotient.factorPow L hmn (AdicCompletion.evalₐ L n x) =
        AdicCompletion.evalₐ L m x := by
    have htop (k : ℕ) : (L ^ k • (⊤ : Ideal R)) = L ^ k := by
      ext y
      simp
    have hle (k : ℕ) : L ^ k ≤ L ^ k • (⊤ : Ideal R) := by
      rw [htop k]
    apply (Ideal.quotientEquivAlgOfEq R (htop m)).symm.injective
    change Ideal.Quotient.factor (hle m)
        (Ideal.Quotient.factorPow L hmn (AdicCompletion.evalₐ L n x)) =
      Ideal.Quotient.factor (hle m) (AdicCompletion.evalₐ L m x)
    rw [AdicCompletion.factor_evalₐ_eq_eval L x (by rw [htop m])]
    rw [← AdicCompletion.factor_eval_eq_evalₐ L x (by rw [htop n])]
    change _ = x.val m
    rw [← x.property hmn]
    rw [AdicCompletion.eval_apply]
    induction x.val n using Quotient.inductionOn' with
    | _ r => rfl
  let f : ∀ n, AdicCompletion I R →+* R ⧸ J ^ n := fun n =>
    (factorMap (I ^ a n) (J ^ n) (ha n)).comp
      (AdicCompletion.evalₐ I (a n)).toRingHom
  have hf {m n : ℕ} (hmn : m ≤ n) :
      (Ideal.Quotient.factorPow J hmn).comp (f n) = f m := by
    apply RingHom.ext
    intro x
    have hamn : a m ≤ a n := hmono_a hmn
    have hjmn : J ^ n ≤ J ^ m := Ideal.pow_le_pow_right hmn
    dsimp [f]
    have hJmap : Ideal.Quotient.factorPow J hmn =
        factorMap (J ^ n) (J ^ m) hjmn := by
      rfl
    rw [hJmap]
    calc
      factorMap (J ^ n) (J ^ m) hjmn
          (factorMap (I ^ a n) (J ^ n) (ha n)
            (AdicCompletion.evalₐ I (a n) x)) =
        factorMap (I ^ a n) (J ^ m) (ha n |>.trans hjmn)
          (AdicCompletion.evalₐ I (a n) x) := by
        rw [factorMap_comp]
      _ =
          factorMap (I ^ a m) (J ^ m) (ha m)
            (factorMap (I ^ a n) (I ^ a m)
              (Ideal.pow_le_pow_right hamn)
              (AdicCompletion.evalₐ I (a n) x)) := by
        rw [factorMap_comp]
      _ = factorMap (I ^ a m) (J ^ m) (ha m)
          (AdicCompletion.evalₐ I (a m) x) := by
        have hImap : Ideal.Quotient.factorPow I hamn =
            factorMap (I ^ a n) (I ^ a m)
              (Ideal.pow_le_pow_right hamn) := by
          rfl
        rw [← hImap, htrans I hamn x]
  let cJI : ℕ → ℕ := fun n => Classical.choose (hcofinal.2 n)
  have hcJI (n : ℕ) : J ^ cJI n ≤ I ^ n :=
    Classical.choose_spec (hcofinal.2 n)
  let b : ℕ → ℕ := fun n =>
    Nat.rec (max 0 (cJI 0))
      (fun n k => max k (max (n + 1) (cJI (n + 1)))) n
  have hcb (n : ℕ) : cJI n ≤ b n := by
    induction n with
    | zero => exact le_max_right _ _
    | succ n ih =>
        change cJI (n + 1) ≤ max (b n) (max (n + 1) (cJI (n + 1)))
        exact le_trans (le_max_right _ _) (le_max_right _ _)
  have hnb (n : ℕ) : n ≤ b n := by
    induction n with
    | zero => exact Nat.zero_le _
    | succ n ih =>
        change n + 1 ≤ max (b n) (max (n + 1) (cJI (n + 1)))
        exact le_trans (le_max_left _ _) (le_max_right _ _)
  have hbb (n : ℕ) : b n ≤ b (n + 1) := by
    change b n ≤ max (b n) (max (n + 1) (cJI (n + 1)))
    exact le_max_left _ _
  have hmono_b : Monotone b := monotone_nat_of_le_succ hbb
  have hb (n : ℕ) : J ^ b n ≤ I ^ n := by
    exact (Ideal.pow_le_pow_right (hcb n)).trans (hcJI n)
  let g : ∀ n, AdicCompletion J R →+* R ⧸ I ^ n := fun n =>
    (factorMap (J ^ b n) (I ^ n) (hb n)).comp
      (AdicCompletion.evalₐ J (b n)).toRingHom
  have hg {m n : ℕ} (hmn : m ≤ n) :
      (Ideal.Quotient.factorPow I hmn).comp (g n) = g m := by
    apply RingHom.ext
    intro x
    have hbmn : b m ≤ b n := hmono_b hmn
    have himn : I ^ n ≤ I ^ m := Ideal.pow_le_pow_right hmn
    dsimp [g]
    have hImap : Ideal.Quotient.factorPow I hmn =
        factorMap (I ^ n) (I ^ m) himn := by
      rfl
    rw [hImap]
    calc
      factorMap (I ^ n) (I ^ m) himn
          (factorMap (J ^ b n) (I ^ n) (hb n)
            (AdicCompletion.evalₐ J (b n) x)) =
        factorMap (J ^ b n) (I ^ m) (hb n |>.trans himn)
          (AdicCompletion.evalₐ J (b n) x) := by
        rw [factorMap_comp]
      _ =
          factorMap (J ^ b m) (I ^ m) (hb m)
            (factorMap (J ^ b n) (J ^ b m)
              (Ideal.pow_le_pow_right hbmn)
              (AdicCompletion.evalₐ J (b n) x)) := by
        rw [factorMap_comp]
      _ = factorMap (J ^ b m) (I ^ m) (hb m)
          (AdicCompletion.evalₐ J (b m) x) := by
        have hJmap : Ideal.Quotient.factorPow J hbmn =
            factorMap (J ^ b n) (J ^ b m)
              (Ideal.pow_le_pow_right hbmn) := by
          rfl
        rw [← hJmap, htrans J hbmn x]
  let F : AdicCompletion I R →+* AdicCompletion J R :=
    AdicCompletion.liftRingHom J f hf
  let G : AdicCompletion J R →+* AdicCompletion I R :=
    AdicCompletion.liftRingHom I g hg
  have hGF (x : AdicCompletion I R) : G (F x) = x := by
    apply AdicCompletion.ext_evalₐ
    intro n
    rw [show G = AdicCompletion.liftRingHom I g hg by rfl]
    rw [AdicCompletion.evalₐ_liftRingHom]
    dsimp [g]
    rw [show F = AdicCompletion.liftRingHom J f hf by rfl]
    rw [AdicCompletion.evalₐ_liftRingHom]
    dsimp [f]
    rw [factorMap_comp]
    have hnab : n ≤ a (b n) := (hnb n).trans (hna (b n))
    have hmap : Ideal.Quotient.factorPow I hnab =
        factorMap (I ^ a (b n)) (I ^ n)
          (Ideal.pow_le_pow_right hnab) := by
      rfl
    rw [← hmap, htrans I hnab x]
  have hFG (x : AdicCompletion J R) : F (G x) = x := by
    apply AdicCompletion.ext_evalₐ
    intro n
    rw [show F = AdicCompletion.liftRingHom J f hf by rfl]
    rw [AdicCompletion.evalₐ_liftRingHom]
    dsimp [f]
    rw [show G = AdicCompletion.liftRingHom I g hg by rfl]
    rw [AdicCompletion.evalₐ_liftRingHom]
    dsimp [g]
    rw [factorMap_comp]
    have hban : n ≤ b (a n) := (hna n).trans (hnb (a n))
    have hmap : Ideal.Quotient.factorPow J hban =
        factorMap (J ^ b (a n)) (J ^ n)
          (Ideal.pow_le_pow_right hban) := by
      rfl
    rw [← hmap, htrans J hban x]
  have hbij : Function.Bijective F := by
    constructor
    · intro x y hxy
      calc
        x = G (F x) := (hGF x).symm
        _ = G (F y) := congrArg G hxy
        _ = y := hGF y
    · intro z
      exact ⟨G z, hFG z⟩
  exact ⟨RingEquiv.ofBijective F hbij⟩

/-- Positivity is exactly what makes the subsequence `n ↦ n * e` cofinal. -/
def positiveExponent {e : ℕ} : Prop := 0 < e

/-- A ring-theoretic formulation of “the completed product is an algebra product”. -/
def hasCompletedRingProduct (A B Ahat : Type*) [CommRing A] [CommRing B]
    [CommRing Ahat] [Algebra A B] [Algebra A Ahat] {ι : Type*}
    (C : ι → Type*) [∀ i, CommRing (C i)] : Prop :=
  Nonempty (B ⊗[A] Ahat ≃+* (∀ i, C i))

/-- The same product assertion, remembering the `Ahat`-algebra structures. -/
def hasCompletedAlgebraProduct (A B Ahat : Type*) [CommRing A] [CommRing B]
    [CommRing Ahat] [Algebra A B] [Algebra A Ahat]
    [Algebra Ahat (B ⊗[A] Ahat)] {ι : Type*}
    (C : ι → Type*) [∀ i, CommRing (C i)] [∀ i, Algebra Ahat (C i)] : Prop :=
  Nonempty (B ⊗[A] Ahat ≃ₐ[Ahat] (∀ i, C i))

/-! Idempotents are used by the finite-product and henselian interfaces. -/
abbrev IdempotentElement (R : Type*) [Monoid R] : Type _ :=
  {e : R // e * e = e}

/-! The finite-level CRT data used to pass to inverse limits. -/
structure Chapter12CompatibleCRTSystem
    {R ι : Type*} [CommRing R] [Finite ι]
    (I : Ideal R) (J : ι → Ideal R) where
  equiv : ∀ n : ℕ, (R ⧸ I ^ n) ≃+* (∀ i, R ⧸ (J i) ^ n)
  compatible : ∀ (n : ℕ) (x : R),
    equiv n (Ideal.Quotient.mk (I ^ n) x) =
      fun i => Ideal.Quotient.mk ((J i) ^ n) x

/-! Ramification labels are kept under the book-facing names. -/
def chapterRamificationIndex
    (A B : Type*) [CommRing A] [CommRing B] [Algebra A B]
    (P : Ideal B) : ℕ :=
  P.ramificationIdx A

def chapterResidueDegree
    (A B : Type*) [CommRing A] [CommRing B] [Algebra A B]
    (P : Ideal B) : ℕ :=
  P.inertiaDeg A

/-! Transport data makes the invariance statements independent of a choice of
    presentation of the base and branch rings. -/
structure Chapter12BranchInvariantTransport
    {A B Ahat Bhat : Type*} [CommRing A] [CommRing B]
    [CommRing Ahat] [CommRing Bhat] [Algebra A B] [Algebra Ahat Bhat]
    (p : Ideal A) (P : Ideal B) (phat : Ideal Ahat) (Phat : Ideal Bhat) where
  source_prime : P.IsPrime
  target_prime : Phat.IsPrime
  source_liesOver : P.LiesOver p
  target_liesOver : Phat.LiesOver phat
  baseEquiv : A ≃+* Ahat
  branchEquiv : B ≃+* Bhat
  baseIdeal_map : Ideal.map baseEquiv.toRingHom p = phat
  branchIdeal_map : Ideal.map branchEquiv.toRingHom P = Phat
  scalar_compatibility : ∀ a b,
    branchEquiv (algebraMap A B a * b) =
      algebraMap Ahat Bhat (baseEquiv a) * branchEquiv b

/-- Completion preserves the branch's intrinsic `e` and `f`. -/
theorem completed_branch_preserves_ef
    {A B Ahat Bhat : Type*} [CommRing A] [CommRing B] [CommRing Ahat] [CommRing Bhat]
    [Algebra A B] [Algebra Ahat Bhat]
    (p : Ideal A) (P : Ideal B) (phat : Ideal Ahat) (Phat : Ideal Bhat)
    (transport : Chapter12BranchInvariantTransport p P phat Phat)
    (e f : ℕ)
    (he : chapterRamificationIndex A B P = e)
    (hf : chapterResidueDegree A B P = f) :
    chapterRamificationIndex Ahat Bhat Phat = e ∧
      chapterResidueDegree Ahat Bhat Phat = f := by
  sorry

/-! Valuation-extension data is shared by the henselian and final-synthesis
    sections. -/
def ValuationExtension
    {K Γ : Type*} [Field K] [LinearOrderedCommGroupWithZero Γ]
    (v : Valuation K Γ) (E : Type*) [Field E] [Algebra K E] : Type _ :=
  {w : Valuation E Γ // v.IsEquiv (w.comap (algebraMap K E))}

abbrev HeterogeneousValuationExtension
    {K Γ : Type u} [Field K] [LinearOrderedCommGroupWithZero Γ]
    (v : Valuation K Γ) (E : Type u) [Field E] [Algebra K E] :=
  Chapter10.Chapter10HeterogeneousValuationExtension E v

def heterogeneousValuationCenter
    {K E Γ : Type u} [Field K] [Field E]
    [LinearOrderedCommGroupWithZero Γ] [Algebra K E]
    (v : Valuation K Γ) [Algebra v.valuationSubring E]
    (W : HeterogeneousValuationExtension v E) :
    Set (integralClosure v.valuationSubring E) :=
  {x | letI : LinearOrderedCommGroupWithZero W.valueGroup := W.orderedValueGroup
    W.valuation (algebraMap (integralClosure v.valuationSubring E) E x) < 1}

abbrev hasUniqueValuationExtension
    {K Γ : Type u} [Field K] [LinearOrderedCommGroupWithZero Γ]
    (v : Valuation K Γ) (E : Type u) [Field E] [Algebra K E] : Prop :=
  Chapter10.Chapter10HasUniqueValuationExtension (L := E) v

end

end LastLib.Book01ValuationsDVRsAndCompletions.Chapter12
