import Mathlib.RingTheory.Henselian
import Mathlib.RingTheory.AdicCompletion.Basic
import Mathlib.RingTheory.AdicCompletion.Algebra
import Mathlib.RingTheory.AdicCompletion.Topology
import Mathlib.RingTheory.AdicCompletion.Completeness
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.RingTheory.Localization.Basic
import Mathlib.RingTheory.Localization.FractionRing
import Mathlib.RingTheory.DedekindDomain.Basic
import Mathlib.RingTheory.DedekindDomain.Dvr
import Mathlib.RingTheory.Valuation.Basic
import Mathlib.RingTheory.Valuation.ValuationRing
import Mathlib.RingTheory.Valuation.Extension
import Mathlib.RingTheory.Valuation.Integral
import Mathlib.RingTheory.Valuation.Discrete.RankOne
import Mathlib.RingTheory.DiscreteValuationRing.Basic
import Mathlib.RingTheory.TensorProduct.Basic
import Mathlib.RingTheory.TensorProduct.Finite
import Mathlib.RingTheory.Finiteness.Basic
import Mathlib.RingTheory.QuasiFinite.Basic
import Mathlib.RingTheory.Polynomial.Eisenstein.Criterion
import Mathlib.RingTheory.RamificationInertia.Basic
import Mathlib.RingTheory.Polynomial.Resultant.Basic
import Mathlib.FieldTheory.Separable
import Mathlib.FieldTheory.IsAlgClosed.AlgebraicClosure
import Mathlib.FieldTheory.AlgebraicClosure
import Mathlib.LinearAlgebra.Dimension.Finite
import Mathlib.LinearAlgebra.Charpoly.Basic
import Mathlib.Analysis.Normed.Field.Basic
import Mathlib.Analysis.Normed.Field.Lemmas
import Mathlib.Analysis.Normed.Unbundled.FiniteExtension
import Mathlib.Topology.Algebra.Polynomial
import Mathlib.Topology.Algebra.Valued.ValuedField
import Mathlib.RingTheory.Polynomial.Eisenstein.Basic
import Mathlib.Tactic.NormNum
import Mathlib.Tactic.Ring
import Mathlib.Tactic.Positivity
import Mathlib.Tactic.FieldSimp
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.GCongr

namespace LastLib.Book01ValuationsDVRsAndCompletions.Chapter12

noncomputable section

open Function Ideal IsLocalRing Polynomial
open Filter Topology
open scoped BigOperators TensorProduct WithZero Polynomial

universe u

/-! # Chapter 12: Completion and finite extensions

This file is a statement-generation pass for §§12.1--12.8 of Book 1.  The
declarations deliberately record the interfaces and relationships used in the
chapter; proofs are postponed.
-/

/-! # Book 1, Chapter 12, Section 12.1: Separating Branches by Completion
-/

/-! ## Common completion and branch interfaces -/

/-- The `I`-adic quotient used at finite precision. -/
abbrev adicQuotient (R : Type u) [CommRing R] (I : Ideal R) (n : ℕ) : Type u :=
  R ⧸ I ^ n

/-- The completion of a ring at a specified ideal. -/
abbrev chapterAdicCompletion (R : Type u) [CommRing R] (I : Ideal R) : Type u :=
  AdicCompletion I R

/-- The localization attached to a candidate branch prime. -/
abbrev branchLocalization (B : Type*) [CommRing B] (P : Ideal B) [P.IsPrime] : Type _ :=
  Localization P.primeCompl

/-- The completion of the localized branch at the image of its prime. -/
abbrev branchCompletion (B : Type*) [CommRing B] (P : Ideal B) [P.IsPrime] : Type _ :=
  AdicCompletion
    (Ideal.map (algebraMap B (branchLocalization B P)) P)
    (branchLocalization B P)

/-- The fraction field of the completed localized branch. -/
abbrev branchFractionField (B : Type*) [CommRing B] (P : Ideal B) [P.IsPrime] : Type _ :=
  FractionRing (branchCompletion B P)

/-- The fraction field of the completion at an ideal. -/
abbrev completionFractionField (R : Type u) [CommRing R] (I : Ideal R) : Type u :=
  FractionRing (AdicCompletion I R)

/-- The principal ideal generated by a power of an element. -/
def principalPowerIdeal {R : Type*} [CommRing R] (π : R) (n : ℕ) : Ideal R :=
  Ideal.span {π ^ n}

/-- The extension to `B` of a principal power from an `A`-algebra. -/
def extendedPrincipalPowerIdeal
    (A B : Type*) [CommRing A] [CommRing B] [Algebra A B]
    (π : A) (n : ℕ) : Ideal B :=
  Ideal.span {(algebraMap A B π) ^ n}

/-- Pairwise coprimality of a finite family of ideals. -/
def pairwiseCoprimeIdeals {ι R : Type*} [CommRing R]
    (I : ι → Ideal R) : Prop :=
  Pairwise (fun i j => IsCoprime (I i) (I j))

/-- Cofinality of two ideal filtrations. -/
def adicFiltrationsCofinal {R : Type*} [CommRing R]
    (I J : Ideal R) : Prop :=
  (∀ n : ℕ, ∃ m : ℕ, I ^ m ≤ J ^ n) ∧
    (∀ n : ℕ, ∃ m : ℕ, J ^ m ≤ I ^ n)

/-- Positivity is exactly what makes the subsequence `n ↦ n * e` cofinal. -/
def positiveExponent {e : ℕ} : Prop := 0 < e

/-- A ring-theoretic formulation of “the completed product is an algebra product”. -/
def hasCompletedRingProduct (A B Ahat : Type*) [CommRing A] [CommRing B]
    [CommRing Ahat] [Algebra A B] [Algebra A Ahat] {ι : Type*}
    (C : ι → Type*) [∀ i, CommRing (C i)] : Prop :=
  Nonempty (B ⊗[A] Ahat ≃+* (∀ i, C i))

/-- The same product assertion, remembering the `Ahat`-algebra structures. -/
def hasCompletedAlgebraProduct (A B Ahat : Type*) [CommRing A] [CommRing B]
    [CommRing Ahat] [Algebra A B] [Algebra A Ahat]
    [Algebra Ahat (B ⊗[A] Ahat)] {ι : Type*}
    (C : ι → Type*) [∀ i, CommRing (C i)] [∀ i, Algebra Ahat (C i)] : Prop :=
  Nonempty (B ⊗[A] Ahat ≃ₐ[Ahat] (∀ i, C i))

/-! Idempotents are used below to record the branch projectors. -/

abbrev IdempotentElement (R : Type*) [Monoid R] : Type _ :=
  {e : R // e * e = e}

/-! ## 12.1--12.2. Separating branches and finite precision -/

/-- Chinese remainder at the inverse-limit level, using Mathlib's quotient CRT. -/
noncomputable def chapterChineseRemainderEquiv
    {R ι : Type*} [CommRing R] [Finite ι]
    (I : ι → Ideal R) (hI : pairwiseCoprimeIdeals I) :
    (R ⧸ ⨅ i, I i) ≃+* (∀ i, R ⧸ I i) :=
  Ideal.quotientInfRingEquivPiQuotient I hI

/-- The finite-precision Chinese remainder decomposition. -/
theorem finite_precision_chinese_remainder
    {R ι : Type*} [CommRing R] [Finite ι]
    (I : ι → Ideal R) (hI : pairwiseCoprimeIdeals I) :
    Nonempty ((R ⧸ ⨅ i, I i) ≃+* (∀ i, R ⧸ I i)) := by
  exact ⟨chapterChineseRemainderEquiv I hI⟩


/-- Powers of a uniformizer factor into powers of the branch primes. -/
theorem finite_precision_pi_power_factorization
    {A B : Type*} [CommRing A] [CommRing B] [Algebra A B]
    {g : ℕ} (π : A) (P : Fin g → Ideal B) (e : Fin g → ℕ) (n : ℕ)
    (hfactor : extendedPrincipalPowerIdeal A B π n = ⨅ i, P i ^ (n * e i))
    (hpair : pairwiseCoprimeIdeals P) :
    Nonempty
      ((B ⧸ extendedPrincipalPowerIdeal A B π n) ≃+*
        (∀ i, B ⧸ P i ^ (n * e i))) := by
  have hpow : Pairwise (fun i j => IsCoprime (P i ^ (n * e i)) (P j ^ (n * e j))) := by
    intro i j hij
    exact (hpair hij).pow
  rw [hfactor]
  exact ⟨Ideal.quotientInfRingEquivPiQuotient (fun i => P i ^ (n * e i)) hpow⟩


/-- The product form of ideal factorization gives the same finite-precision CRT. -/
theorem finite_precision_pi_power_product_form
    {A B : Type*} [CommRing A] [CommRing B] [Algebra A B]
    {g : ℕ} (π : A) (P : Fin g → Ideal B) (e : Fin g → ℕ) (n : ℕ)
    (hfactor : extendedPrincipalPowerIdeal A B π n = ∏ i, P i ^ (n * e i))
    (hintersection : (∏ i, P i ^ (n * e i)) = ⨅ i, P i ^ (n * e i))
    (hpair : pairwiseCoprimeIdeals P) :
    Nonempty
      ((B ⧸ extendedPrincipalPowerIdeal A B π n) ≃+*
        (∀ i, B ⧸ P i ^ (n * e i))) := by
  have hpow : Pairwise (fun i j => IsCoprime (P i ^ (n * e i)) (P j ^ (n * e j))) := by
    intro i j hij
    exact (hpair hij).pow
  rw [hfactor, hintersection]
  exact ⟨Ideal.quotientInfRingEquivPiQuotient (fun i => P i ^ (n * e i)) hpow⟩


/-- Localizing a primary branch quotient does not change it. -/
theorem localization_of_branch_quotient_equiv
    {B : Type*} [CommRing B] (P : Ideal B) (n : ℕ)
    (hP : P.IsPrime) (hmax : P.IsMaximal) :
    Nonempty
      ((Localization.AtPrime P ⧸
          Ideal.map (algebraMap B (Localization.AtPrime P)) (P ^ n)) ≃+*
        (B ⧸ P ^ n)) := by
  let _ : P.IsPrime := hP
  let _ : P.IsMaximal := hmax
  have hmap :
      Ideal.map (algebraMap B (Localization.AtPrime P)) (P ^ n) =
        IsLocalRing.maximalIdeal (Localization.AtPrime P) ^ n := by
    rw [Ideal.map_pow,
      IsLocalization.AtPrime.map_eq_maximalIdeal P (Localization.AtPrime P)]
  refine ⟨?_⟩
  rw [hmap]
  exact (IsLocalization.AtPrime.equivQuotMaximalIdealPow P
    (Localization.AtPrime P) n).symm.toRingEquiv

/-- Positive multiples are cofinal among all positive exponents. -/
theorem positive_multiples_are_cofinal (e : ℕ) (he : positiveExponent (e := e)) :
    ∀ n : ℕ, ∃ m : ℕ, n ≤ m * e := by
  intro n
  exact ⟨n, Nat.le_mul_of_pos_right n he⟩


/-- A finite-level CRT system with the actual representative compatibility. -/
structure Chapter12CompatibleCRTSystem
    {R ι : Type*} [CommRing R] [Finite ι]
    (I : Ideal R) (J : ι → Ideal R) where
  equiv : ∀ n : ℕ, (R ⧸ I ^ n) ≃+* (∀ i, R ⧸ (J i) ^ n)
  compatible : ∀ (n : ℕ) (x : R),
    equiv n (Ideal.Quotient.mk (I ^ n) x) =
      fun i => Ideal.Quotient.mk ((J i) ^ n) x

/-- The finite-product CRT is compatible with passing to inverse limits. -/
theorem completion_product_of_finite_precision_crt
    {R ι : Type*} [CommRing R] [Finite ι]
    (I : Ideal R) (J : ι → Ideal R)
    (hcrt : Chapter12CompatibleCRTSystem I J)
    (_hcofinal : ∀ i, adicFiltrationsCofinal I (J i)) :
    Nonempty
      (AdicCompletion I R ≃+* (∀ i, AdicCompletion (J i) R)) := by
  classical
  let _ : Fintype ι := Fintype.ofFinite ι
  have htop (L : Ideal R) (n : ℕ) :
      (L ^ n • (⊤ : Ideal R)) = L ^ n := by
    ext x
    simp
  have htrans (L : Ideal R) {m n : ℕ} (hmn : m ≤ n)
      (x : AdicCompletion L R) :
      Ideal.Quotient.factorPow L hmn (AdicCompletion.evalₐ L n x) =
        AdicCompletion.evalₐ L m x := by
    have hle (k : ℕ) : L ^ k ≤ L ^ k • (⊤ : Ideal R) := by
      rw [htop L k]
    apply (Ideal.quotientEquivAlgOfEq R (htop L m)).symm.injective
    change Ideal.Quotient.factor (hle m)
        (Ideal.Quotient.factorPow L hmn (AdicCompletion.evalₐ L n x)) =
      Ideal.Quotient.factor (hle m) (AdicCompletion.evalₐ L m x)
    rw [AdicCompletion.factor_evalₐ_eq_eval L x (by
      rw [htop L m])]
    rw [← AdicCompletion.factor_eval_eq_evalₐ L x (by
      rw [htop L n])]
    change _ = x.val m
    rw [← x.property hmn]
    rw [AdicCompletion.eval_apply]
    induction x.val n using Quotient.inductionOn' with
    | _ r => rfl
  have hcrt_nat {m n : ℕ} (hmn : m ≤ n) (z : R ⧸ I ^ n) :
      hcrt.equiv m (Ideal.Quotient.factorPow I hmn z) =
        fun i => Ideal.Quotient.factorPow (J i) hmn ((hcrt.equiv n z) i) := by
    induction z using Quotient.inductionOn' with
    | _ r =>
      change hcrt.equiv m (Ideal.Quotient.factorPow I hmn
          (Ideal.Quotient.mk (I ^ n) r)) =
        fun i => Ideal.Quotient.factorPow (J i) hmn
          ((hcrt.equiv n (Ideal.Quotient.mk (I ^ n) r)) i)
      rw [hcrt.compatible n r]
      convert hcrt.compatible m r using 1 <;> rfl
  let f : ∀ i, ∀ n, AdicCompletion I R →+* R ⧸ (J i) ^ n :=
    fun i n =>
      (Pi.evalRingHom (fun j => R ⧸ (J j) ^ n) i).comp
        ((hcrt.equiv n).toRingHom.comp (AdicCompletion.evalₐ I n).toRingHom)
  have hf (i : ι) {m n : ℕ} (hmn : m ≤ n) :
      (Ideal.Quotient.factorPow (J i) hmn).comp (f i n) = f i m := by
    ext x
    have hn := congrFun (hcrt_nat hmn (AdicCompletion.evalₐ I n x)) i
    rw [htrans I hmn x] at hn
    exact hn.symm
  let φ : ∀ i, AdicCompletion I R →+* AdicCompletion (J i) R :=
    fun i => AdicCompletion.liftRingHom (J i) (f i) (hf i)
  let F : AdicCompletion I R →+* (∀ i, AdicCompletion (J i) R) :=
    RingHom.pi φ
  let g : ∀ n, (∀ i, AdicCompletion (J i) R) →+* R ⧸ I ^ n :=
    fun n =>
      (hcrt.equiv n).symm.toRingHom.comp
        (RingHom.pi (fun i =>
          (AdicCompletion.evalₐ (J i) n).toRingHom.comp
            (Pi.evalRingHom (fun i => AdicCompletion (J i) R) i)))
  have hcrt_nat_symm {m n : ℕ} (hmn : m ≤ n)
      (z : ∀ i, R ⧸ (J i) ^ n) :
      Ideal.Quotient.factorPow I hmn ((hcrt.equiv n).symm z) =
        (hcrt.equiv m).symm (fun i =>
          Ideal.Quotient.factorPow (J i) hmn (z i)) := by
    apply (hcrt.equiv m).injective
    calc
      hcrt.equiv m (Ideal.Quotient.factorPow I hmn ((hcrt.equiv n).symm z)) =
          fun i => Ideal.Quotient.factorPow (J i) hmn
            ((hcrt.equiv n ((hcrt.equiv n).symm z)) i) :=
        hcrt_nat hmn ((hcrt.equiv n).symm z)
      _ = fun i => Ideal.Quotient.factorPow (J i) hmn (z i) := by simp
      _ = hcrt.equiv m ((hcrt.equiv m).symm (fun i =>
          Ideal.Quotient.factorPow (J i) hmn (z i))) := by simp
  have hg {m n : ℕ} (hmn : m ≤ n) :
      (Ideal.Quotient.factorPow I hmn).comp (g n) = g m := by
    apply RingHom.ext
    intro z
    change Ideal.Quotient.factorPow I hmn ((hcrt.equiv n).symm
        (fun i => AdicCompletion.evalₐ (J i) n (z i))) =
      (hcrt.equiv m).symm (fun i => AdicCompletion.evalₐ (J i) m (z i))
    rw [hcrt_nat_symm hmn]
    congr 1
    funext i
    exact htrans (J i) hmn (z i)
  let G : (∀ i, AdicCompletion (J i) R) →+* AdicCompletion I R :=
    AdicCompletion.liftRingHom I g hg
  have hGF (x : AdicCompletion I R) : G (F x) = x := by
    apply AdicCompletion.ext_evalₐ
    intro n
    dsimp only [G]
    rw [AdicCompletion.evalₐ_liftRingHom]
    apply (hcrt.equiv n).injective
    simp only [g, F, φ]
    funext i
    simp [RingHom.comp_apply, RingHom.pi_apply]
    simp [f, RingHom.comp_apply]
  have hFG (z : ∀ i, AdicCompletion (J i) R) : F (G z) = z := by
    funext i
    apply AdicCompletion.ext_evalₐ
    intro n
    change AdicCompletion.evalₐ (J i) n
        (AdicCompletion.liftRingHom (J i) (f i) (hf i) (G z)) =
      AdicCompletion.evalₐ (J i) n (z i)
    rw [AdicCompletion.evalₐ_liftRingHom]
    change (Pi.evalRingHom (fun j => R ⧸ (J j) ^ n) i)
        ((hcrt.equiv n) (AdicCompletion.evalₐ I n (G z))) =
      AdicCompletion.evalₐ (J i) n (z i)
    dsimp only [G]
    rw [AdicCompletion.evalₐ_liftRingHom]
    simp [g]
  have hbij : Function.Bijective F := by
    constructor
    · intro x y hxy
      calc
        x = G (F x) := (hGF x).symm
        _ = G (F y) := congrArg G hxy
        _ = y := hGF y
    · intro z
      exact ⟨G z, hFG z⟩
  exact ⟨RingEquiv.ofBijective F hbij⟩

end

end LastLib.Book01ValuationsDVRsAndCompletions.Chapter12
