import Mathlib.RingTheory.Henselian
import Mathlib.RingTheory.AdicCompletion.Basic
import Mathlib.RingTheory.AdicCompletion.Algebra
import Mathlib.RingTheory.AdicCompletion.Topology
import Mathlib.RingTheory.AdicCompletion.Completeness
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.RingTheory.Localization.Basic
import Mathlib.RingTheory.Localization.FractionRing
import Mathlib.RingTheory.DedekindDomain.Basic
import Mathlib.RingTheory.DedekindDomain.Dvr
import Mathlib.RingTheory.Valuation.Basic
import Mathlib.RingTheory.Valuation.ValuationRing
import Mathlib.RingTheory.Valuation.Extension
import Mathlib.RingTheory.Valuation.Integral
import Mathlib.RingTheory.Valuation.Discrete.RankOne
import Mathlib.RingTheory.DiscreteValuationRing.Basic
import Mathlib.RingTheory.TensorProduct.Basic
import Mathlib.RingTheory.TensorProduct.Finite
import Mathlib.RingTheory.Finiteness.Basic
import Mathlib.RingTheory.QuasiFinite.Basic
import Mathlib.RingTheory.Polynomial.Eisenstein.Criterion
import Mathlib.RingTheory.RamificationInertia.Basic
import Mathlib.RingTheory.Polynomial.Resultant.Basic
import Mathlib.FieldTheory.Separable
import Mathlib.FieldTheory.IsAlgClosed.AlgebraicClosure
import Mathlib.FieldTheory.AlgebraicClosure
import Mathlib.LinearAlgebra.Dimension.Finite
import Mathlib.LinearAlgebra.Charpoly.Basic
import Mathlib.Analysis.Normed.Field.Basic
import Mathlib.Analysis.Normed.Field.Lemmas
import Mathlib.Analysis.Normed.Unbundled.FiniteExtension
import Mathlib.Topology.Algebra.Polynomial
import Mathlib.Topology.Algebra.Valued.ValuedField
import Mathlib.RingTheory.Polynomial.Eisenstein.Basic
import Mathlib.Tactic.NormNum
import Mathlib.Tactic.Ring
import Mathlib.Tactic.Positivity
import Mathlib.Tactic.FieldSimp
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.GCongr

namespace LastLib.Book01ValuationsDVRsAndCompletions.Chapter12

noncomputable section

open Function Ideal IsLocalRing Polynomial
open Filter Topology
open scoped BigOperators TensorProduct WithZero Polynomial

universe u

/-! # Chapter 12: Completion and finite extensions

This file is a statement-generation pass for §§12.1--12.8 of Book 1.  The
declarations deliberately record the interfaces and relationships used in the
chapter; proofs are postponed.
-/

/-! # Book 1, Chapter 12, Section 12.1: Separating Branches by Completion
-/

/-! ## 12.1--12.2. Separating branches and finite precision -/

/-- The `I`-adic quotient used at finite precision. -/
abbrev adicQuotient (R : Type u) [CommRing R] (I : Ideal R) (n : ℕ) : Type u :=
  R ⧸ I ^ n

/-- The completion of a ring at a specified ideal. -/
abbrev chapterAdicCompletion (R : Type u) [CommRing R] (I : Ideal R) : Type u :=
  AdicCompletion I R

/-- The localization attached to a candidate branch prime. -/
abbrev branchLocalization (B : Type*) [CommRing B] (P : Ideal B) [P.IsPrime] : Type _ :=
  Localization P.primeCompl

/-- The completion of the localized branch at the image of its prime. -/
abbrev branchCompletion (B : Type*) [CommRing B] (P : Ideal B) [P.IsPrime] : Type _ :=
  AdicCompletion
    (Ideal.map (algebraMap B (branchLocalization B P)) P)
    (branchLocalization B P)

/-- The fraction field of the completed localized branch. -/
abbrev branchFractionField (B : Type*) [CommRing B] (P : Ideal B) [P.IsPrime] : Type _ :=
  FractionRing (branchCompletion B P)

/-- The fraction field of the completion at an ideal. -/
abbrev completionFractionField (R : Type u) [CommRing R] (I : Ideal R) : Type u :=
  FractionRing (AdicCompletion I R)

/-- The principal ideal generated by a power of an element. -/
def principalPowerIdeal {R : Type*} [CommRing R] (π : R) (n : ℕ) : Ideal R :=
  Ideal.span {π ^ n}

/-- The extension to `B` of a principal power from an `A`-algebra. -/
def extendedPrincipalPowerIdeal
    (A B : Type*) [CommRing A] [CommRing B] [Algebra A B]
    (π : A) (n : ℕ) : Ideal B :=
  Ideal.span {(algebraMap A B π) ^ n}

/-- Pairwise coprimality of a finite family of ideals. -/
def pairwiseCoprimeIdeals {ι R : Type*} [CommRing R]
    (I : ι → Ideal R) : Prop :=
  Pairwise (fun i j => IsCoprime (I i) (I j))

/-- Cofinality of two ideal filtrations. -/
def adicFiltrationsCofinal {R : Type*} [CommRing R]
    (I J : Ideal R) : Prop :=
  (∀ n : ℕ, ∃ m : ℕ, I ^ m ≤ J ^ n) ∧
    (∀ n : ℕ, ∃ m : ℕ, J ^ m ≤ I ^ n)

/-! Cofinal adic filtrations have the same inverse-limit completion. -/
theorem adic_completion_equiv_of_cofinal_filtrations
    {R : Type*} [CommRing R] (I J : Ideal R)
    (hcofinal : adicFiltrationsCofinal I J) :
    Nonempty (AdicCompletion I R ≃+* AdicCompletion J R) := by
  classical
  let cIJ : ℕ → ℕ := fun n => Classical.choose (hcofinal.1 n)
  have hcIJ (n : ℕ) : I ^ cIJ n ≤ J ^ n :=
    Classical.choose_spec (hcofinal.1 n)
  let a : ℕ → ℕ := fun n =>
    Nat.rec (max 0 (cIJ 0))
      (fun n k => max k (max (n + 1) (cIJ (n + 1)))) n
  have hca (n : ℕ) : cIJ n ≤ a n := by
    induction n with
    | zero => exact le_max_right _ _
    | succ n ih =>
        change cIJ (n + 1) ≤ max (a n) (max (n + 1) (cIJ (n + 1)))
        exact le_trans (le_max_right _ _) (le_max_right _ _)
  have hna (n : ℕ) : n ≤ a n := by
    induction n with
    | zero => exact Nat.zero_le _
    | succ n ih =>
        change n + 1 ≤ max (a n) (max (n + 1) (cIJ (n + 1)))
        exact le_trans (le_max_left _ _) (le_max_right _ _)
  have haa (n : ℕ) : a n ≤ a (n + 1) := by
    change a n ≤ max (a n) (max (n + 1) (cIJ (n + 1)))
    exact le_max_left _ _
  have hmono_a : Monotone a := monotone_nat_of_le_succ haa
  have ha (n : ℕ) : I ^ a n ≤ J ^ n := by
    exact (Ideal.pow_le_pow_right (hca n)).trans (hcIJ n)
  let factorMap (S T : Ideal R) (hST : S ≤ T) :
      R ⧸ S →+* R ⧸ T :=
    Ideal.Quotient.factor hST
  have factorMap_comp (S T U : Ideal R) (hST : S ≤ T) (hTU : T ≤ U)
      (x : R ⧸ S) :
      factorMap T U hTU (factorMap S T hST x) =
        factorMap S U (hST.trans hTU) x := by
    simp [factorMap]
  have htrans (L : Ideal R) {m n : ℕ} (hmn : m ≤ n)
      (x : AdicCompletion L R) :
      Ideal.Quotient.factorPow L hmn (AdicCompletion.evalₐ L n x) =
        AdicCompletion.evalₐ L m x := by
    have htop (k : ℕ) : (L ^ k • (⊤ : Ideal R)) = L ^ k := by
      ext y
      simp
    have hle (k : ℕ) : L ^ k ≤ L ^ k • (⊤ : Ideal R) := by
      rw [htop k]
    apply (Ideal.quotientEquivAlgOfEq R (htop m)).symm.injective
    change Ideal.Quotient.factor (hle m)
        (Ideal.Quotient.factorPow L hmn (AdicCompletion.evalₐ L n x)) =
      Ideal.Quotient.factor (hle m) (AdicCompletion.evalₐ L m x)
    rw [AdicCompletion.factor_evalₐ_eq_eval L x (by rw [htop m])]
    rw [← AdicCompletion.factor_eval_eq_evalₐ L x (by rw [htop n])]
    change _ = x.val m
    rw [← x.property hmn]
    rw [AdicCompletion.eval_apply]
    induction x.val n using Quotient.inductionOn' with
    | _ r => rfl
  let f : ∀ n, AdicCompletion I R →+* R ⧸ J ^ n := fun n =>
    (factorMap (I ^ a n) (J ^ n) (ha n)).comp
      (AdicCompletion.evalₐ I (a n)).toRingHom
  have hf {m n : ℕ} (hmn : m ≤ n) :
      (Ideal.Quotient.factorPow J hmn).comp (f n) = f m := by
    apply RingHom.ext
    intro x
    have hamn : a m ≤ a n := hmono_a hmn
    have hjmn : J ^ n ≤ J ^ m := Ideal.pow_le_pow_right hmn
    dsimp [f]
    have hJmap : Ideal.Quotient.factorPow J hmn =
        factorMap (J ^ n) (J ^ m) hjmn := by
      rfl
    rw [hJmap]
    calc
      factorMap (J ^ n) (J ^ m) hjmn
          (factorMap (I ^ a n) (J ^ n) (ha n)
            (AdicCompletion.evalₐ I (a n) x)) =
        factorMap (I ^ a n) (J ^ m) (ha n |>.trans hjmn)
          (AdicCompletion.evalₐ I (a n) x) := by
        rw [factorMap_comp]
      _ =
          factorMap (I ^ a m) (J ^ m) (ha m)
            (factorMap (I ^ a n) (I ^ a m)
              (Ideal.pow_le_pow_right hamn)
              (AdicCompletion.evalₐ I (a n) x)) := by
        rw [factorMap_comp]
      _ = factorMap (I ^ a m) (J ^ m) (ha m)
          (AdicCompletion.evalₐ I (a m) x) := by
        have hImap : Ideal.Quotient.factorPow I hamn =
            factorMap (I ^ a n) (I ^ a m)
              (Ideal.pow_le_pow_right hamn) := by
          rfl
        rw [← hImap, htrans I hamn x]
  let cJI : ℕ → ℕ := fun n => Classical.choose (hcofinal.2 n)
  have hcJI (n : ℕ) : J ^ cJI n ≤ I ^ n :=
    Classical.choose_spec (hcofinal.2 n)
  let b : ℕ → ℕ := fun n =>
    Nat.rec (max 0 (cJI 0))
      (fun n k => max k (max (n + 1) (cJI (n + 1)))) n
  have hcb (n : ℕ) : cJI n ≤ b n := by
    induction n with
    | zero => exact le_max_right _ _
    | succ n ih =>
        change cJI (n + 1) ≤ max (b n) (max (n + 1) (cJI (n + 1)))
        exact le_trans (le_max_right _ _) (le_max_right _ _)
  have hnb (n : ℕ) : n ≤ b n := by
    induction n with
    | zero => exact Nat.zero_le _
    | succ n ih =>
        change n + 1 ≤ max (b n) (max (n + 1) (cJI (n + 1)))
        exact le_trans (le_max_left _ _) (le_max_right _ _)
  have hbb (n : ℕ) : b n ≤ b (n + 1) := by
    change b n ≤ max (b n) (max (n + 1) (cJI (n + 1)))
    exact le_max_left _ _
  have hmono_b : Monotone b := monotone_nat_of_le_succ hbb
  have hb (n : ℕ) : J ^ b n ≤ I ^ n := by
    exact (Ideal.pow_le_pow_right (hcb n)).trans (hcJI n)
  let g : ∀ n, AdicCompletion J R →+* R ⧸ I ^ n := fun n =>
    (factorMap (J ^ b n) (I ^ n) (hb n)).comp
      (AdicCompletion.evalₐ J (b n)).toRingHom
  have hg {m n : ℕ} (hmn : m ≤ n) :
      (Ideal.Quotient.factorPow I hmn).comp (g n) = g m := by
    apply RingHom.ext
    intro x
    have hbmn : b m ≤ b n := hmono_b hmn
    have himn : I ^ n ≤ I ^ m := Ideal.pow_le_pow_right hmn
    dsimp [g]
    have hImap : Ideal.Quotient.factorPow I hmn =
        factorMap (I ^ n) (I ^ m) himn := by
      rfl
    rw [hImap]
    calc
      factorMap (I ^ n) (I ^ m) himn
          (factorMap (J ^ b n) (I ^ n) (hb n)
            (AdicCompletion.evalₐ J (b n) x)) =
        factorMap (J ^ b n) (I ^ m) (hb n |>.trans himn)
          (AdicCompletion.evalₐ J (b n) x) := by
        rw [factorMap_comp]
      _ =
          factorMap (J ^ b m) (I ^ m) (hb m)
            (factorMap (J ^ b n) (J ^ b m)
              (Ideal.pow_le_pow_right hbmn)
              (AdicCompletion.evalₐ J (b n) x)) := by
        rw [factorMap_comp]
      _ = factorMap (J ^ b m) (I ^ m) (hb m)
          (AdicCompletion.evalₐ J (b m) x) := by
        have hJmap : Ideal.Quotient.factorPow J hbmn =
            factorMap (J ^ b n) (J ^ b m)
              (Ideal.pow_le_pow_right hbmn) := by
          rfl
        rw [← hJmap, htrans J hbmn x]
  let F : AdicCompletion I R →+* AdicCompletion J R :=
    AdicCompletion.liftRingHom J f hf
  let G : AdicCompletion J R →+* AdicCompletion I R :=
    AdicCompletion.liftRingHom I g hg
  have hGF (x : AdicCompletion I R) : G (F x) = x := by
    apply AdicCompletion.ext_evalₐ
    intro n
    rw [show G = AdicCompletion.liftRingHom I g hg by rfl]
    rw [AdicCompletion.evalₐ_liftRingHom]
    dsimp [g]
    rw [show F = AdicCompletion.liftRingHom J f hf by rfl]
    rw [AdicCompletion.evalₐ_liftRingHom]
    dsimp [f]
    rw [factorMap_comp]
    have hnab : n ≤ a (b n) := (hnb n).trans (hna (b n))
    have hmap : Ideal.Quotient.factorPow I hnab =
        factorMap (I ^ a (b n)) (I ^ n)
          (Ideal.pow_le_pow_right hnab) := by
      rfl
    rw [← hmap, htrans I hnab x]
  have hFG (x : AdicCompletion J R) : F (G x) = x := by
    apply AdicCompletion.ext_evalₐ
    intro n
    rw [show F = AdicCompletion.liftRingHom J f hf by rfl]
    rw [AdicCompletion.evalₐ_liftRingHom]
    dsimp [f]
    rw [show G = AdicCompletion.liftRingHom I g hg by rfl]
    rw [AdicCompletion.evalₐ_liftRingHom]
    dsimp [g]
    rw [factorMap_comp]
    have hban : n ≤ b (a n) := (hna n).trans (hnb (a n))
    have hmap : Ideal.Quotient.factorPow J hban =
        factorMap (J ^ b (a n)) (J ^ n)
          (Ideal.pow_le_pow_right hban) := by
      rfl
    rw [← hmap, htrans J hban x]
  have hbij : Function.Bijective F := by
    constructor
    · intro x y hxy
      calc
        x = G (F x) := (hGF x).symm
        _ = G (F y) := congrArg G hxy
        _ = y := hGF y
    · intro z
      exact ⟨G z, hFG z⟩
  exact ⟨RingEquiv.ofBijective F hbij⟩

/-- Positivity is exactly what makes the subsequence `n ↦ n * e` cofinal. -/
def positiveExponent {e : ℕ} : Prop := 0 < e

/-! Idempotents are used by the finite-product and henselian interfaces. -/
abbrev IdempotentElement (R : Type*) [Monoid R] : Type _ :=
  {e : R // e * e = e}

/-! The finite-level CRT data used to pass to inverse limits. -/
structure Chapter12CompatibleCRTSystem
    {R ι : Type*} [CommRing R] [Finite ι]
    (I : Ideal R) (J : ι → Ideal R) where
  equiv : ∀ n : ℕ, (R ⧸ I ^ n) ≃+* (∀ i, R ⧸ (J i) ^ n)
  compatible : ∀ (n : ℕ) (x : R),
    equiv n (Ideal.Quotient.mk (I ^ n) x) =
      fun i => Ideal.Quotient.mk ((J i) ^ n) x

/-- Chinese remainder at the inverse-limit level, using Mathlib's quotient CRT. -/
noncomputable def chapterChineseRemainderEquiv
    {R ι : Type*} [CommRing R] [Finite ι]
    (I : ι → Ideal R) (hI : pairwiseCoprimeIdeals I) :
    (R ⧸ ⨅ i, I i) ≃+* (∀ i, R ⧸ I i) :=
  Ideal.quotientInfRingEquivPiQuotient I hI

/-- The finite-precision Chinese remainder decomposition. -/
theorem finite_precision_chinese_remainder
    {R ι : Type*} [CommRing R] [Finite ι]
    (I : ι → Ideal R) (hI : pairwiseCoprimeIdeals I) :
    Nonempty ((R ⧸ ⨅ i, I i) ≃+* (∀ i, R ⧸ I i)) := by
  exact ⟨chapterChineseRemainderEquiv I hI⟩


/-- Powers of a uniformizer factor into powers of the branch primes. -/
theorem finite_precision_pi_power_factorization
    {A B : Type*} [CommRing A] [CommRing B] [Algebra A B]
    {g : ℕ} (π : A) (P : Fin g → Ideal B) (e : Fin g → ℕ) (n : ℕ)
    (hfactor : extendedPrincipalPowerIdeal A B π n = ⨅ i, P i ^ (n * e i))
    (hpair : pairwiseCoprimeIdeals P) :
    Nonempty
      ((B ⧸ extendedPrincipalPowerIdeal A B π n) ≃+*
        (∀ i, B ⧸ P i ^ (n * e i))) := by
  have hpow : Pairwise (fun i j => IsCoprime (P i ^ (n * e i)) (P j ^ (n * e j))) := by
    intro i j hij
    exact (hpair hij).pow
  rw [hfactor]
  exact ⟨Ideal.quotientInfRingEquivPiQuotient (fun i => P i ^ (n * e i)) hpow⟩


/-- The product form of ideal factorization gives the same finite-precision CRT. -/
theorem finite_precision_pi_power_product_form
    {A B : Type*} [CommRing A] [CommRing B] [Algebra A B]
    {g : ℕ} (π : A) (P : Fin g → Ideal B) (e : Fin g → ℕ) (n : ℕ)
    (hfactor : extendedPrincipalPowerIdeal A B π n = ∏ i, P i ^ (n * e i))
    (hintersection : (∏ i, P i ^ (n * e i)) = ⨅ i, P i ^ (n * e i))
    (hpair : pairwiseCoprimeIdeals P) :
    Nonempty
      ((B ⧸ extendedPrincipalPowerIdeal A B π n) ≃+*
        (∀ i, B ⧸ P i ^ (n * e i))) := by
  have hpow : Pairwise (fun i j => IsCoprime (P i ^ (n * e i)) (P j ^ (n * e j))) := by
    intro i j hij
    exact (hpair hij).pow
  rw [hfactor, hintersection]
  exact ⟨Ideal.quotientInfRingEquivPiQuotient (fun i => P i ^ (n * e i)) hpow⟩


/-- Evaluation from an adic completion commutes with the transition between
finite quotients. -/
theorem adic_completion_factorPow_evalₐ
    {R : Type*} [CommRing R] (I : Ideal R) {m n : ℕ}
    (hmn : m ≤ n) (x : AdicCompletion I R) :
    Ideal.Quotient.factorPow I hmn (AdicCompletion.evalₐ I n x) =
      AdicCompletion.evalₐ I m x := by
  have htop (k : ℕ) : I ^ k • (⊤ : Ideal R) = I ^ k := by ext y; simp
  have hle (k : ℕ) : I ^ k ≤ I ^ k • (⊤ : Ideal R) := by rw [htop k]
  apply (Ideal.quotientEquivAlgOfEq R (htop m)).symm.injective
  change Ideal.Quotient.factor (hle m)
      (Ideal.Quotient.factorPow I hmn (AdicCompletion.evalₐ I n x)) =
    Ideal.Quotient.factor (hle m) (AdicCompletion.evalₐ I m x)
  rw [AdicCompletion.factor_evalₐ_eq_eval I x (by rw [htop m])]
  rw [← AdicCompletion.factor_eval_eq_evalₐ I x (by rw [htop n])]
  change _ = x.val m
  rw [← x.property hmn, AdicCompletion.eval_apply]
  induction x.val n using Quotient.inductionOn' with
  | _ r => rfl

/-- Compatible quotient equivalences between two adic systems. -/
structure Chapter12CompatibleAdicEquiv
    {R S : Type*} [CommRing R] [CommRing S]
    (I : Ideal R) (J : Ideal S) where
  equiv : ∀ n : ℕ, (R ⧸ I ^ n) ≃+* (S ⧸ J ^ n)
  transition : ∀ {m n : ℕ} (hmn : m ≤ n) (x : R ⧸ I ^ n),
    equiv m (Ideal.Quotient.factorPow I hmn x) =
      Ideal.Quotient.factorPow J hmn (equiv n x)

/-- Isomorphic compatible quotient systems have isomorphic inverse-limit completions. -/
theorem adic_completion_equiv_of_compatible_quotient_equiv
    {R S : Type*} [CommRing R] [CommRing S]
    (I : Ideal R) (J : Ideal S) (h : Chapter12CompatibleAdicEquiv I J) :
    Nonempty (AdicCompletion I R ≃+* AdicCompletion J S) := by
  let f : ∀ n, AdicCompletion I R →+* S ⧸ J ^ n := fun n ↦
    (h.equiv n).toRingHom.comp (AdicCompletion.evalₐ I n).toRingHom
  have hf {m n : ℕ} (hmn : m ≤ n) :
      (Ideal.Quotient.factorPow J hmn).comp (f n) = f m := by
    ext x
    exact (h.transition hmn (AdicCompletion.evalₐ I n x)).symm.trans
      (congrArg (h.equiv m) (adic_completion_factorPow_evalₐ I hmn x))
  let F : AdicCompletion I R →+* AdicCompletion J S :=
    AdicCompletion.liftRingHom J f hf
  let g : ∀ n, AdicCompletion J S →+* R ⧸ I ^ n := fun n ↦
    (h.equiv n).symm.toRingHom.comp (AdicCompletion.evalₐ J n).toRingHom
  have hg {m n : ℕ} (hmn : m ≤ n) :
      (Ideal.Quotient.factorPow I hmn).comp (g n) = g m := by
    ext x
    apply (h.equiv m).injective
    change h.equiv m (Ideal.Quotient.factorPow I hmn
        ((h.equiv n).symm (AdicCompletion.evalₐ J n x))) =
      h.equiv m ((h.equiv m).symm (AdicCompletion.evalₐ J m x))
    rw [h.transition hmn]
    simp only [RingEquiv.apply_symm_apply]
    exact adic_completion_factorPow_evalₐ J hmn x
  let G : AdicCompletion J S →+* AdicCompletion I R :=
    AdicCompletion.liftRingHom I g hg
  have hGF (x : AdicCompletion I R) : G (F x) = x := by
    apply AdicCompletion.ext_evalₐ
    intro n
    dsimp only [G]
    rw [AdicCompletion.evalₐ_liftRingHom]
    dsimp only [g, F]
    change (h.equiv n).symm (AdicCompletion.evalₐ J n
        (AdicCompletion.liftRingHom J f hf x)) = AdicCompletion.evalₐ I n x
    rw [AdicCompletion.evalₐ_liftRingHom]
    simp [f]
  have hFG (x : AdicCompletion J S) : F (G x) = x := by
    apply AdicCompletion.ext_evalₐ
    intro n
    dsimp only [F]
    rw [AdicCompletion.evalₐ_liftRingHom]
    dsimp only [f, G]
    change h.equiv n (AdicCompletion.evalₐ I n
        (AdicCompletion.liftRingHom I g hg x)) = AdicCompletion.evalₐ J n x
    rw [AdicCompletion.evalₐ_liftRingHom]
    simp [g]
  refine ⟨RingEquiv.ofBijective F ?_⟩
  constructor
  · intro x y hxy
    simpa only [hGF] using congrArg G hxy
  · intro y
    exact ⟨G y, hFG y⟩

/-- Localizing a primary branch quotient does not change it. -/
theorem localization_of_branch_quotient_equiv
    {B : Type*} [CommRing B] (P : Ideal B) (n : ℕ)
    (hP : P.IsPrime) (hmax : P.IsMaximal) :
    Nonempty
      ((Localization.AtPrime P ⧸
          Ideal.map (algebraMap B (Localization.AtPrime P)) (P ^ n)) ≃+*
        (B ⧸ P ^ n)) := by
  let _ : P.IsPrime := hP
  let _ : P.IsMaximal := hmax
  have hmap :
      Ideal.map (algebraMap B (Localization.AtPrime P)) (P ^ n) =
        IsLocalRing.maximalIdeal (Localization.AtPrime P) ^ n := by
    rw [Ideal.map_pow,
      IsLocalization.AtPrime.map_eq_maximalIdeal P (Localization.AtPrime P)]
  refine ⟨?_⟩
  rw [hmap]
  exact (IsLocalization.AtPrime.equivQuotMaximalIdealPow P
    (Localization.AtPrime P) n).symm.toRingEquiv

/-- Positive multiples are cofinal among all positive exponents. -/
theorem positive_multiples_are_cofinal (e : ℕ) (he : positiveExponent (e := e)) :
    ∀ n : ℕ, ∃ m : ℕ, n ≤ m * e := by
  intro n
  exact ⟨n, Nat.le_mul_of_pos_right n he⟩

/-- Replacing an ideal by a positive power does not change its adic completion. -/
theorem adic_completion_equiv_power
    {R : Type*} [CommRing R] (I : Ideal R) (e : ℕ) (he : 0 < e) :
    Nonempty (AdicCompletion (I ^ e) R ≃+* AdicCompletion I R) := by
  apply adic_completion_equiv_of_cofinal_filtrations
  constructor
  · intro n
    refine ⟨n, ?_⟩
    rw [← pow_mul]
    exact Ideal.pow_le_pow_right (Nat.le_mul_of_pos_left n he)
  · intro n
    refine ⟨n * e, ?_⟩
    rw [← pow_mul, Nat.mul_comm]


/-- The finite-product CRT is compatible with passing to inverse limits. -/
theorem completion_product_of_finite_precision_crt
    {R ι : Type*} [CommRing R] [Finite ι]
    (I : Ideal R) (J : ι → Ideal R)
    (hcrt : Chapter12CompatibleCRTSystem I J)
    : Nonempty
      (AdicCompletion I R ≃+* (∀ i, AdicCompletion (J i) R)) := by
  classical
  let _ : Fintype ι := Fintype.ofFinite ι
  have htop (L : Ideal R) (n : ℕ) :
      (L ^ n • (⊤ : Ideal R)) = L ^ n := by
    ext x
    simp
  have htrans (L : Ideal R) {m n : ℕ} (hmn : m ≤ n)
      (x : AdicCompletion L R) :
      Ideal.Quotient.factorPow L hmn (AdicCompletion.evalₐ L n x) =
        AdicCompletion.evalₐ L m x := by
    have hle (k : ℕ) : L ^ k ≤ L ^ k • (⊤ : Ideal R) := by
      rw [htop L k]
    apply (Ideal.quotientEquivAlgOfEq R (htop L m)).symm.injective
    change Ideal.Quotient.factor (hle m)
        (Ideal.Quotient.factorPow L hmn (AdicCompletion.evalₐ L n x)) =
      Ideal.Quotient.factor (hle m) (AdicCompletion.evalₐ L m x)
    rw [AdicCompletion.factor_evalₐ_eq_eval L x (by
      rw [htop L m])]
    rw [← AdicCompletion.factor_eval_eq_evalₐ L x (by
      rw [htop L n])]
    change _ = x.val m
    rw [← x.property hmn]
    rw [AdicCompletion.eval_apply]
    induction x.val n using Quotient.inductionOn' with
    | _ r => rfl
  have hcrt_nat {m n : ℕ} (hmn : m ≤ n) (z : R ⧸ I ^ n) :
      hcrt.equiv m (Ideal.Quotient.factorPow I hmn z) =
        fun i => Ideal.Quotient.factorPow (J i) hmn ((hcrt.equiv n z) i) := by
    induction z using Quotient.inductionOn' with
    | _ r =>
      change hcrt.equiv m (Ideal.Quotient.factorPow I hmn
          (Ideal.Quotient.mk (I ^ n) r)) =
        fun i => Ideal.Quotient.factorPow (J i) hmn
          ((hcrt.equiv n (Ideal.Quotient.mk (I ^ n) r)) i)
      rw [hcrt.compatible n r]
      convert hcrt.compatible m r using 1 <;> rfl
  let f : ∀ i, ∀ n, AdicCompletion I R →+* R ⧸ (J i) ^ n :=
    fun i n =>
      (Pi.evalRingHom (fun j => R ⧸ (J j) ^ n) i).comp
        ((hcrt.equiv n).toRingHom.comp (AdicCompletion.evalₐ I n).toRingHom)
  have hf (i : ι) {m n : ℕ} (hmn : m ≤ n) :
      (Ideal.Quotient.factorPow (J i) hmn).comp (f i n) = f i m := by
    ext x
    have hn := congrFun (hcrt_nat hmn (AdicCompletion.evalₐ I n x)) i
    rw [htrans I hmn x] at hn
    exact hn.symm
  let φ : ∀ i, AdicCompletion I R →+* AdicCompletion (J i) R :=
    fun i => AdicCompletion.liftRingHom (J i) (f i) (hf i)
  let F : AdicCompletion I R →+* (∀ i, AdicCompletion (J i) R) :=
    RingHom.pi φ
  let g : ∀ n, (∀ i, AdicCompletion (J i) R) →+* R ⧸ I ^ n :=
    fun n =>
      (hcrt.equiv n).symm.toRingHom.comp
        (RingHom.pi (fun i =>
          (AdicCompletion.evalₐ (J i) n).toRingHom.comp
            (Pi.evalRingHom (fun i => AdicCompletion (J i) R) i)))
  have hcrt_nat_symm {m n : ℕ} (hmn : m ≤ n)
      (z : ∀ i, R ⧸ (J i) ^ n) :
      Ideal.Quotient.factorPow I hmn ((hcrt.equiv n).symm z) =
        (hcrt.equiv m).symm (fun i =>
          Ideal.Quotient.factorPow (J i) hmn (z i)) := by
    apply (hcrt.equiv m).injective
    calc
      hcrt.equiv m (Ideal.Quotient.factorPow I hmn ((hcrt.equiv n).symm z)) =
          fun i => Ideal.Quotient.factorPow (J i) hmn
            ((hcrt.equiv n ((hcrt.equiv n).symm z)) i) :=
        hcrt_nat hmn ((hcrt.equiv n).symm z)
      _ = fun i => Ideal.Quotient.factorPow (J i) hmn (z i) := by simp
      _ = hcrt.equiv m ((hcrt.equiv m).symm (fun i =>
          Ideal.Quotient.factorPow (J i) hmn (z i))) := by simp
  have hg {m n : ℕ} (hmn : m ≤ n) :
      (Ideal.Quotient.factorPow I hmn).comp (g n) = g m := by
    apply RingHom.ext
    intro z
    change Ideal.Quotient.factorPow I hmn ((hcrt.equiv n).symm
        (fun i => AdicCompletion.evalₐ (J i) n (z i))) =
      (hcrt.equiv m).symm (fun i => AdicCompletion.evalₐ (J i) m (z i))
    rw [hcrt_nat_symm hmn]
    congr 1
    funext i
    exact htrans (J i) hmn (z i)
  let G : (∀ i, AdicCompletion (J i) R) →+* AdicCompletion I R :=
    AdicCompletion.liftRingHom I g hg
  have hGF (x : AdicCompletion I R) : G (F x) = x := by
    apply AdicCompletion.ext_evalₐ
    intro n
    dsimp only [G]
    rw [AdicCompletion.evalₐ_liftRingHom]
    apply (hcrt.equiv n).injective
    simp only [g, F, φ]
    funext i
    simp [RingHom.comp_apply, RingHom.pi_apply]
    simp [f, RingHom.comp_apply]
  have hFG (z : ∀ i, AdicCompletion (J i) R) : F (G z) = z := by
    funext i
    apply AdicCompletion.ext_evalₐ
    intro n
    change AdicCompletion.evalₐ (J i) n
        (AdicCompletion.liftRingHom (J i) (f i) (hf i) (G z)) =
      AdicCompletion.evalₐ (J i) n (z i)
    rw [AdicCompletion.evalₐ_liftRingHom]
    change (Pi.evalRingHom (fun j => R ⧸ (J j) ^ n) i)
        ((hcrt.equiv n) (AdicCompletion.evalₐ I n (G z))) =
      AdicCompletion.evalₐ (J i) n (z i)
    dsimp only [G]
    rw [AdicCompletion.evalₐ_liftRingHom]
    simp [g]
  have hbij : Function.Bijective F := by
    constructor
    · intro x y hxy
      calc
        x = G (F x) := (hGF x).symm
        _ = G (F y) := congrArg G hxy
        _ = y := hGF y
    · intro z
      exact ⟨G z, hFG z⟩
  exact ⟨RingEquiv.ofBijective F hbij⟩

/-- A ramified factorization of every uniformizer power gives the corresponding
product decomposition after completing at the extended uniformizer ideal.  The
factors are initially completed at `P i ^ e i`; positivity later identifies
these with the usual `P i`-adic completions. -/
theorem ramified_branch_completion_product
    {A B : Type*} [CommRing A] [CommRing B] [Algebra A B]
    {g : ℕ} (π : A) (P : Fin g → Ideal B) (e : Fin g → ℕ)
    (hfactor : ∀ n : ℕ,
      extendedPrincipalPowerIdeal A B π n = ⨅ i, P i ^ (n * e i))
    (hpair : pairwiseCoprimeIdeals P) :
    Nonempty
      (AdicCompletion (extendedPrincipalPowerIdeal A B π 1) B ≃+*
        (∀ i, AdicCompletion (P i ^ e i) B)) := by
  let K : Ideal B := extendedPrincipalPowerIdeal A B π 1
  let J : Fin g → Ideal B := fun i ↦ P i ^ e i
  have hKpow (n : ℕ) : K ^ n = extendedPrincipalPowerIdeal A B π n := by
    simp [K, extendedPrincipalPowerIdeal, Ideal.span_singleton_pow]
  have hKJ (n : ℕ) : K ^ n = ⨅ i, (J i) ^ n := by
    rw [hKpow, hfactor]
    congr 1
    funext i
    simp only [J, ← pow_mul, Nat.mul_comm]
  have hJpair : pairwiseCoprimeIdeals J := by
    intro i j hij
    exact (hpair hij).pow
  let crt : Chapter12CompatibleCRTSystem K J := {
    equiv := fun n ↦
      (Ideal.quotientEquivAlgOfEq B (hKJ n)).toRingEquiv.trans
        (Ideal.quotientInfRingEquivPiQuotient (fun i ↦ (J i) ^ n)
          (fun i j hij ↦ (hJpair hij).pow))
    compatible := by
      intro n x
      rfl }
  simpa [K, J] using completion_product_of_finite_precision_crt K J crt

end

end LastLib.Book01ValuationsDVRsAndCompletions.Chapter12
