import LastLib.Book01ValuationsDVRsAndCompletions.Chapter12.Dependencies
import Mathlib.Analysis.Normed.Module.FiniteDimension
import Mathlib.Analysis.Normed.Operator.BoundedLinearMaps

namespace LastLib.Book01ValuationsDVRsAndCompletions.Chapter12

noncomputable section

open Function Ideal IsLocalRing Polynomial
open Filter Topology
open scoped BigOperators TensorProduct WithZero Polynomial

universe u

/-! # Chapter 12: Completion and finite extensions

This file is a statement-generation pass for §§12.1--12.8 of Book 1.  The
declarations deliberately record the interfaces and relationships used in the
chapter; proofs are postponed.
-/

/-! # Book 1, Chapter 12, Section 12.6: The Valuation Ring in a Finite Complete Extension
-/

/-! ## 12.6. The valuation ring of a finite complete extension -/

/-- The coordinate lattice generated by a finite list of field coordinates. -/
def coordinateLattice
    (A L : Type*) [CommRing A] [Field L] [Algebra A L]
    {n : ℕ} (e : Fin n → L) : Set L :=
  {x | ∃ c : Fin n → A,
    (∑ i, algebraMap A L (c i) * e i) = x}

/-- A scalar multiple of a coordinate lattice. -/
def scaledSet
    (A L : Type*) [CommRing A] [Field L] [Algebra A L]
    (a : A) (S : Set L) : Set L :=
  {x | ∃ y, y ∈ S ∧ algebraMap A L a * y = x}

/-- A scalar multiple by an arbitrary element of the ambient field. -/
def scaledByFieldElement
    (L : Type*) [Field L] (a : L) (S : Set L) : Set L :=
  {x | ∃ y, y ∈ S ∧ a * y = x}

/-- The closed unit ball for a norm. -/
def closedUnitBall (L : Type*) [Norm L] : Set L :=
  {x | ‖x‖ ≤ 1}

/-- The coordinate norm attached to a finite basis. -/
def coordinateNorm
    {K L : Type*} [Norm K] [Norm L] [Field K] [Field L] [Module K L]
    {n : ℕ} (b : Module.Basis (Fin n) K L) (x : L) : ℝ :=
  ∑ i, ‖b.repr x i‖

/-- Equivalence of the coordinate norm and the field norm. -/
theorem coordinate_and_field_norms_are_equivalent
    {K L : Type*} [NontriviallyNormedField K] [NormedField L] [NormedSpace K L]
    [CompleteSpace K]
    {n : ℕ} (b : Module.Basis (Fin n) K L) :
    ∃ c₁ c₂ : ℝ, 0 < c₁ ∧ 0 < c₂ ∧
      ∀ x : L, c₁ * coordinateNorm b x ≤ ‖x‖ ∧
        ‖x‖ ≤ c₂ * coordinateNorm b x := by
  let _ : Nonempty (Fin n) := b.index_nonempty
  let _ : FiniteDimensional K L := b.finiteDimensional_of_finite
  let Fₗ : L →ₗ[K] (Fin n → K) := b.equivFun.toLinearMap
  let Gₗ : (Fin n → K) →ₗ[K] L := b.equivFun.symm.toLinearMap
  let F : L →L[K] (Fin n → K) :=
    { toLinearMap := Fₗ
      cont := by exact LinearMap.continuous_of_finiteDimensional Fₗ }
  let G : (Fin n → K) →L[K] L :=
    { toLinearMap := Gₗ
      cont := by exact LinearMap.continuous_of_finiteDimensional Gₗ }
  obtain ⟨c, hc, hG⟩ := G.isBoundedLinearMap.bound
  obtain ⟨d, hd, hF⟩ := F.isBoundedLinearMap.bound
  have hF_apply (x : L) : F x = b.equivFun x := by
    change Fₗ x = b.equivFun x
    rfl
  have hG_apply (x : L) : G (F x) = x := by
    change Gₗ (Fₗ x) = x
    simp [Fₗ, Gₗ]
  have hcoord_le (x : L) : coordinateNorm b x ≤ (n : ℝ) * ‖F x‖ := by
    change (∑ i, ‖b.repr x i‖) ≤ (n : ℝ) * ‖F x‖
    rw [hF_apply]
    simpa [Module.Basis.equivFun_apply, nsmul_eq_mul] using
      (Pi.sum_norm_apply_le_norm (b.equivFun x))
  have hnorm_le_coord (x : L) : ‖F x‖ ≤ coordinateNorm b x := by
    rw [hF_apply]
    rw [pi_norm_le_iff_of_nonempty]
    intro i
    change ‖b.repr x i‖ ≤ ∑ j, ‖b.repr x j‖
    exact Finset.single_le_sum (fun j _ => norm_nonneg _) (Finset.mem_univ i)
  have hn : 0 < (n : ℝ) := by
    have hn_nat : 0 < n := by
      simpa using (Fintype.card_pos : 0 < Fintype.card (Fin n))
    exact_mod_cast hn_nat
  refine ⟨((n : ℝ) * d)⁻¹, c, inv_pos.mpr (mul_pos hn hd), hc, ?_⟩
  intro x
  constructor
  · have hmul : coordinateNorm b x ≤ (n : ℝ) * d * ‖x‖ := by
      calc
        coordinateNorm b x ≤ (n : ℝ) * ‖F x‖ := hcoord_le x
        _ ≤ (n : ℝ) * (d * ‖x‖) :=
          mul_le_mul_of_nonneg_left (hF x) (le_of_lt hn)
        _ = (n : ℝ) * d * ‖x‖ := by ring
    calc
      ((n : ℝ) * d)⁻¹ * coordinateNorm b x ≤
          ((n : ℝ) * d)⁻¹ * ((n : ℝ) * d * ‖x‖) :=
        mul_le_mul_of_nonneg_left hmul (le_of_lt (inv_pos.mpr (mul_pos hn hd)))
      _ = ‖x‖ := by field_simp
  · calc
      ‖x‖ = ‖G (F x)‖ := by rw [hG_apply]
      _ ≤ c * ‖F x‖ := hG (F x)
      _ ≤ c * coordinateNorm b x :=
        mul_le_mul_of_nonneg_left (hnorm_le_coord x) (le_of_lt hc)

/-- Comparison of the extended closed unit ball with two integral lattices. -/
theorem unit_ball_between_scaled_coordinate_lattices
    {A K L : Type*} [CommRing A] [NormedField K] [NormedField L]
    [Algebra A K] [NormedAlgebra K L] [Algebra A L] [IsScalarTower A K L]
    [CompleteSpace K]
    {n : ℕ} (π : A) (b : Module.Basis (Fin n) K L)
    (hA : Set.range (algebraMap A K) = closedUnitBall K)
    (hπ : 0 < ‖algebraMap A K π‖ ∧ ‖algebraMap A K π‖ < 1) :
    ∃ r s : ℕ,
      scaledSet A L (π ^ r) (coordinateLattice A L (fun i => b i)) ⊆
          closedUnitBall L ∧
        closedUnitBall L ⊆
          scaledByFieldElement L ((algebraMap A L π) ^ (-(s : ℤ)))
            (coordinateLattice A L (fun i => b i)) := by
  let _ : NontriviallyNormedField K :=
    { non_trivial := ⟨(algebraMap A K π)⁻¹, by
        rw [norm_inv]
        exact (one_lt_inv₀ hπ.1).2 hπ.2⟩ }
  obtain ⟨c₁, c₂, hc₁, hc₂, hnorms⟩ :=
    coordinate_and_field_norms_are_equivalent b
  let q : ℝ := ‖algebraMap A K π‖
  let C : ℝ := max c₂ 1 * ∑ i, ‖b i‖
  have hC : 0 ≤ C := by
    dsimp [C]
    positivity
  obtain ⟨r, hr⟩ :=
    exists_pow_lt_of_lt_one (x := (C + 1)⁻¹) (by positivity) hπ.2
  have hqC : q ^ r * C ≤ 1 := by
    have hq : q ^ r * (C + 1) < 1 := by
      calc
        q ^ r * (C + 1) < (C + 1)⁻¹ * (C + 1) :=
          mul_lt_mul_of_pos_right hr (by positivity)
        _ = 1 := by field_simp
    calc
      q ^ r * C ≤ q ^ r * (C + 1) := by
        gcongr
        linarith
      _ ≤ 1 := hq.le
  have hqnonneg : 0 ≤ q ^ r := pow_nonneg (le_of_lt hπ.1) _
  have hcoeff_unit (a : A) : ‖algebraMap A L a‖ ≤ 1 := by
    have haK : algebraMap A K a ∈ closedUnitBall K := by
      rw [← hA]
      exact ⟨a, rfl⟩
    change ‖algebraMap A K a‖ ≤ 1 at haK
    calc
      ‖algebraMap A L a‖ =
          ‖algebraMap K L (algebraMap A K a)‖ := by
        rw [IsScalarTower.algebraMap_apply A K L]
      _ = ‖algebraMap A K a‖ := norm_algebraMap' _ _
      _ ≤ 1 := haK
  have hlattice_bound (y : L)
      (hy : y ∈ coordinateLattice A L (fun i => b i)) : ‖y‖ ≤ C := by
    rcases hy with ⟨a, rfl⟩
    dsimp [coordinateLattice, C] at *
    calc
      ‖∑ i, algebraMap A L (a i) * b i‖ ≤
          ∑ i, ‖algebraMap A L (a i) * b i‖ := norm_sum_le _ _
      _ ≤ ∑ i, ‖b i‖ := by
        gcongr with i hi
        rw [norm_mul]
        exact mul_le_of_le_one_left (norm_nonneg _) (hcoeff_unit (a i))
      _ ≤ max c₂ 1 * ∑ i, ‖b i‖ := by
        calc
          (∑ i, ‖b i‖) = 1 * ∑ i, ‖b i‖ := by ring
          _ ≤ max c₂ 1 * ∑ i, ‖b i‖ := by
            gcongr
            exact le_max_right _ _
  have hfirst :
      scaledSet A L (π ^ r) (coordinateLattice A L (fun i => b i)) ⊆
        closedUnitBall L := by
    intro x hx
    rcases hx with ⟨y, hy, rfl⟩
    change ‖algebraMap A L (π ^ r) * y‖ ≤ 1
    calc
      ‖algebraMap A L (π ^ r) * y‖ = q ^ r * ‖y‖ := by
        rw [norm_mul, map_pow, norm_pow]
        congr 1
        dsimp [q]
        rw [IsScalarTower.algebraMap_apply A K L, norm_algebraMap']
      _ ≤ q ^ r * C := mul_le_mul_of_nonneg_left (hlattice_bound y hy) hqnonneg
      _ ≤ 1 := hqC
  let D : ℝ := c₁⁻¹
  have hD : 0 ≤ D := by
    dsimp [D]
    exact le_of_lt (inv_pos.mpr hc₁)
  obtain ⟨s, hs⟩ :=
    exists_pow_lt_of_lt_one (x := (D + 1)⁻¹) (by dsimp [D]; positivity) hπ.2
  have hqD : q ^ s * D ≤ 1 := by
    have hq : q ^ s * (D + 1) < 1 := by
      calc
        q ^ s * (D + 1) < (D + 1)⁻¹ * (D + 1) :=
          mul_lt_mul_of_pos_right hs (by positivity)
        _ = 1 := by field_simp
    calc
      q ^ s * D ≤ q ^ s * (D + 1) := by
        gcongr
        linarith
      _ ≤ 1 := hq.le
  have hsecond :
      closedUnitBall L ⊆
        scaledByFieldElement L ((algebraMap A L π) ^ (-(s : ℤ)))
          (coordinateLattice A L (fun i => b i)) := by
    intro x hx
    change ‖x‖ ≤ 1 at hx
    have hcoord : coordinateNorm b x ≤ D := by
      have hnorm := (hnorms x).1
      dsimp [D]
      calc
        coordinateNorm b x = c₁⁻¹ * (c₁ * coordinateNorm b x) := by
          field_simp
        _ ≤ c₁⁻¹ * ‖x‖ :=
          mul_le_mul_of_nonneg_left hnorm (le_of_lt (inv_pos.mpr hc₁))
        _ ≤ c₁⁻¹ * 1 := by
          exact mul_le_mul_of_nonneg_left hx (le_of_lt (inv_pos.mpr hc₁))
        _ = c₁⁻¹ := by ring
    let coeff : Fin n → K := fun i => (algebraMap A K π) ^ s * b.repr x i
    have hcoeff_norm (i : Fin n) : ‖coeff i‖ ≤ 1 := by
      dsimp [coeff]
      calc
        ‖(algebraMap A K π) ^ s * b.repr x i‖ =
            q ^ s * ‖b.repr x i‖ := by
          rw [norm_mul, norm_pow]
        _ ≤ q ^ s * coordinateNorm b x := by
          gcongr
          exact Finset.single_le_sum (fun j _ => norm_nonneg _)
            (Finset.mem_univ i)
        _ ≤ q ^ s * D := mul_le_mul_of_nonneg_left hcoord
            (pow_nonneg (le_of_lt hπ.1) _)
        _ ≤ 1 := hqD
    have hcoeff_range (i : Fin n) : coeff i ∈ Set.range (algebraMap A K) := by
      rw [hA]
      exact hcoeff_norm i
    choose a ha using hcoeff_range
    have hx_repr : x = ∑ i, algebraMap K L (b.repr x i) * b i := by
      calc
        x = ∑ i, (b.repr x i) • b i := (b.sum_repr x).symm
        _ = ∑ i, algebraMap K L (b.repr x i) * b i := by
          simp [Algebra.smul_def]
    have hy : algebraMap A L (π ^ s) * x ∈
        coordinateLattice A L (fun i => b i) := by
      refine ⟨a, ?_⟩
      calc
        ∑ i, algebraMap A L (a i) * b i =
            ∑ i, algebraMap K L (coeff i) * b i := by
          apply Finset.sum_congr rfl
          intro i hi
          have hmap : algebraMap A L (a i) = algebraMap K L (coeff i) := by
            calc
              algebraMap A L (a i) =
                  algebraMap K L (algebraMap A K (a i)) :=
                IsScalarTower.algebraMap_apply A K L (a i)
              _ = algebraMap K L (coeff i) := by rw [ha i]
          exact congrArg (fun z : L => z * b i) hmap
        _ = algebraMap A L (π ^ s) * x := by
          rw [hx_repr]
          simp [coeff, ← IsScalarTower.algebraMap_apply A K L,
            map_pow, map_mul, Finset.mul_sum, mul_assoc]
    have hπL : algebraMap A L π ≠ 0 := by
      intro h
      have hK : algebraMap A K π = 0 := by
        apply FaithfulSMul.algebraMap_injective K L
        simpa [IsScalarTower.algebraMap_apply A K L] using h
      have hnormK : ‖algebraMap A K π‖ = 0 := by rw [hK, norm_zero]
      exact (ne_of_gt hπ.1) hnormK
    refine ⟨algebraMap A L (π ^ s) * x, hy, ?_⟩
    rw [map_pow, zpow_neg, zpow_natCast]
    calc
      ((algebraMap A L π) ^ s)⁻¹ *
          ((algebraMap A L π) ^ s * x) =
          (((algebraMap A L π) ^ s)⁻¹ * (algebraMap A L π) ^ s) * x := by ring
      _ = x := by rw [inv_mul_cancel₀ (pow_ne_zero s hπL), one_mul]
  exact ⟨r, s, hfirst, hsecond⟩

/-- The valuation unit ball is the valuation ring. -/
def valuationUnitBall
    {L Γ : Type*} [Field L] [LinearOrderedCommGroupWithZero Γ]
    (w : Valuation L Γ) : Set L :=
  {x | w x ≤ 1}

theorem valuation_subring_carrier_eq_unit_ball
    {L Γ : Type*} [Field L] [LinearOrderedCommGroupWithZero Γ]
    (w : Valuation L Γ) :
    (w.valuationSubring : Set L) = valuationUnitBall w := by
  rfl

/-- A finite module's multiplication endomorphism makes each element integral. -/
theorem determinant_trick_for_finite_algebra
    {A C : Type*} [CommRing A] [CommRing C] [Algebra A C]
    [Module.Finite A C] (x : C) : IsIntegral A x := by
  exact IsIntegral.of_finite A x

/-- The finite-dimensional lattice comparison makes the extended unit ball finite. -/
theorem complete_extension_unit_ball_is_finite
    {K L Γ : Type*} [Field K] [Field L]
    [LinearOrderedCommGroupWithZero Γ] [Algebra K L]
    (vK : Valuation K Γ) (w : Valuation L Γ)
    [vK.HasExtension w] [Valuation.IsRankOneDiscrete vK]
    [Valuation.IsRankOneDiscrete w] [Module.Finite K L]
    (hcomplete : IsAdicComplete
      (IsLocalRing.maximalIdeal vK.valuationSubring) vK.valuationSubring) :
    Module.Finite vK.valuationSubring w.valuationSubring := by
  sorry

/-- Once the preceding lattice theorem supplies module finiteness, the
determinant trick identifies the valuation unit ball with the integral
closure. -/
theorem complete_extension_unit_ball_is_integral_closure
    {K L Γ : Type*} [Field K] [Field L]
    [LinearOrderedCommGroupWithZero Γ] [Algebra K L]
    (vK : Valuation K Γ) (w : Valuation L Γ)
    [vK.HasExtension w] [Algebra vK.valuationSubring L]
    [IsScalarTower vK.valuationSubring K L]
    [IsScalarTower vK.valuationSubring w.valuationSubring L]
    (hfinite : Module.Finite vK.valuationSubring w.valuationSubring) :
    (w.valuationSubring : Set L) =
      {x : L | IsIntegral vK.valuationSubring x} := by
  letI := hfinite
  ext x
  constructor
  · intro hx
    let x' : w.valuationSubring := ⟨x, hx⟩
    have hx' : IsIntegral vK.valuationSubring x' :=
      IsIntegral.of_finite vK.valuationSubring x'
    have hcoe : algebraMap w.valuationSubring L x' = x := by
      rfl
    rw [← hcoe]
    exact hx'.algebraMap
  · intro hx
    have hx' : IsIntegral w.valuationSubring x := hx.tower_top
    exact (Valuation.valuationSubring.integers w).isIntegral_iff_v_le_one.mp hx'

/-- The valuation ring in a finite complete extension is torsion-free over the base. -/
theorem complete_extension_unit_ball_is_torsion_free
    {K L Γ : Type*} [Field K] [Field L]
    [LinearOrderedCommGroupWithZero Γ] [Algebra K L]
    (vK : Valuation K Γ) (w : Valuation L Γ)
    [vK.HasExtension w] :
    ∀ (a : vK.valuationSubring), ∀ x : w.valuationSubring,
      a ≠ 0 → a • x = 0 → x = 0 := by
  intro a x ha hax
  apply Subtype.ext
  have haK : (a : K) ≠ 0 := by
    intro haK
    apply ha
    exact Subtype.ext haK
  have haL : algebraMap K L (a : K) ≠ 0 := by
    intro hzero
    apply haK
    apply FaithfulSMul.algebraMap_injective K L
    simpa using hzero
  have hax' : algebraMap K L (a : K) * (x : L) = 0 := by
    have h := congrArg (fun y : w.valuationSubring => (y : L)) hax
    simpa [Algebra.smul_def,
      Valuation.HasExtension.coe_algebraMap_valuationSubring_eq] using h
  rcases mul_eq_zero.mp hax' with hzero | hzero
  · exact (haL hzero).elim
  · exact hzero

/-- Finite torsion-free modules over the base DVR are finite free. -/
theorem finite_torsion_free_over_dvr_is_free
    {A M : Type*} [CommRing A] [IsDomain A]
    [IsDiscreteValuationRing A] [AddCommGroup M] [Module A M]
    [Module.Finite A M]
    (htf : ∀ (a : A), ∀ x : M, a ≠ 0 → a • x = 0 → x = 0) :
    Module.Free A M := by
  let _ : Module.IsTorsionFree A M :=
    Module.IsTorsionFree.of_smul_eq_zero (by
      intro a x hax
      rcases eq_or_ne a 0 with rfl | ha
      · exact Or.inl rfl
      · exact Or.inr (htf a x ha hax))
  infer_instance

/-- The structural theorem for the valuation ring of a finite complete extension. -/
theorem finite_complete_extension_valuation_ring
    {K L Γ : Type*} [Field K] [Field L]
    [LinearOrderedCommGroupWithZero Γ] [Algebra K L]
    (vK : Valuation K Γ) (w : Valuation L Γ)
    [vK.HasExtension w] [Valuation.IsRankOneDiscrete vK]
    [Valuation.IsRankOneDiscrete w] [Module.Finite K L]
    (hcomplete : IsAdicComplete
      (IsLocalRing.maximalIdeal vK.valuationSubring) vK.valuationSubring) :
    Module.Finite vK.valuationSubring w.valuationSubring ∧
    Module.Free vK.valuationSubring w.valuationSubring ∧
      IsAdicComplete (IsLocalRing.maximalIdeal w.valuationSubring)
        w.valuationSubring ∧
      IsDiscreteValuationRing w.valuationSubring ∧
      (w.valuationSubring : Set L) =
        (integralClosure vK.valuationSubring L : Set L) := by
  sorry

/-- The maximal ideal extension and residue degree formulas in the complete case. -/
theorem complete_extension_ideal_and_residue_formulas
    {K L Γ : Type*} [Field K] [Field L]
    [LinearOrderedCommGroupWithZero Γ] [Algebra K L]
    (vK : Valuation K Γ) (w : Valuation L Γ)
    [vK.HasExtension w] [Valuation.IsRankOneDiscrete vK]
    [Valuation.IsRankOneDiscrete w] [Module.Finite K L]
    (e f : ℕ) (he : chapterRamificationIndex vK.valuationSubring
      w.valuationSubring (IsLocalRing.maximalIdeal w.valuationSubring) = e)
    (hf : chapterResidueDegree vK.valuationSubring
      w.valuationSubring (IsLocalRing.maximalIdeal w.valuationSubring) = f)
    (hcomplete : IsAdicComplete
      (IsLocalRing.maximalIdeal vK.valuationSubring) vK.valuationSubring) :
    (IsLocalRing.maximalIdeal vK.valuationSubring).map
        (algebraMap vK.valuationSubring w.valuationSubring) =
      (IsLocalRing.maximalIdeal w.valuationSubring) ^ e ∧
      Module.finrank (IsLocalRing.ResidueField vK.valuationSubring)
          (IsLocalRing.ResidueField w.valuationSubring) = f ∧
      Module.finrank K L = e * f := by
  sorry

/-- The degree equality needs neither separability nor perfection hypotheses. -/
theorem complete_extension_defectless_without_separability
    {K L Γ : Type*} [Field K] [Field L]
    [LinearOrderedCommGroupWithZero Γ] [Algebra K L]
    (vK : Valuation K Γ) (w : Valuation L Γ)
    [vK.HasExtension w] [Valuation.IsRankOneDiscrete vK]
    [Valuation.IsRankOneDiscrete w] [Module.Finite K L]
    (hcomplete : IsAdicComplete
      (IsLocalRing.maximalIdeal vK.valuationSubring) vK.valuationSubring) :
    Module.finrank K L =
      chapterRamificationIndex vK.valuationSubring w.valuationSubring
        (IsLocalRing.maximalIdeal w.valuationSubring) *
      chapterResidueDegree vK.valuationSubring w.valuationSubring
        (IsLocalRing.maximalIdeal w.valuationSubring) := by
  have h := complete_extension_ideal_and_residue_formulas vK w
    (chapterRamificationIndex vK.valuationSubring w.valuationSubring
      (IsLocalRing.maximalIdeal w.valuationSubring))
    (chapterResidueDegree vK.valuationSubring w.valuationSubring
      (IsLocalRing.maximalIdeal w.valuationSubring)) rfl rfl hcomplete
  exact h.2.2

end

end LastLib.Book01ValuationsDVRsAndCompletions.Chapter12
