import Mathlib.RingTheory.LocalRing.ResidueField.Basic
import LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter04.Section01DepthAndCodimension

namespace LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter04

open AlgebraicGeometry CategoryTheory CategoryTheory.Limits Set TopologicalSpace
open scoped AlgebraicGeometry BigOperators

noncomputable section

universe u

/-! ### 4.3 Normal surfaces need not be regular -/

/-- The polynomial ring used for the quadratic cone. -/
abbrev chapter04QuadraticConePolynomialRing (k : Type u) [CommRing k] :=
  MvPolynomial (Fin 3) k

/-- The equation `xy - z^2` of the quadratic cone. -/
def chapter04QuadraticConeEquation (k : Type u) [CommRing k] :
    chapter04QuadraticConePolynomialRing k :=
  MvPolynomial.X 0 * MvPolynomial.X 1 - MvPolynomial.X 2 ^ 2

def chapter04QuadraticConeAmbientOriginIdeal (k : Type u) [CommRing k] :
    Ideal (chapter04QuadraticConePolynomialRing k) :=
  Ideal.span ({MvPolynomial.X 0, MvPolynomial.X 1, MvPolynomial.X 2} :
    Set (chapter04QuadraticConePolynomialRing k))

theorem chapter04_quadratic_cone_equation_has_no_linear_term
    (k : Type u) [CommRing k] :
    chapter04QuadraticConeEquation k ∈
      (chapter04QuadraticConeAmbientOriginIdeal k) ^ 2 := by
  sorry

def chapter04QuadraticConeRelationIdeal (k : Type u) [CommRing k] :
    Ideal (chapter04QuadraticConePolynomialRing k) :=
  Ideal.span ({chapter04QuadraticConeEquation k} : Set (chapter04QuadraticConePolynomialRing k))

/-- The affine quadratic cone ring `k[x,y,z]/(xy-z^2)`. -/
abbrev chapter04QuadraticConeRing (k : Type u) [CommRing k] :=
  chapter04QuadraticConePolynomialRing k ⧸ chapter04QuadraticConeRelationIdeal k

def chapter04QuadraticConeCoordinate (k : Type u) [CommRing k] (i : Fin 3) :
    chapter04QuadraticConeRing k :=
  Ideal.Quotient.mk (chapter04QuadraticConeRelationIdeal k)
    (MvPolynomial.X i)

theorem chapter04_quadratic_cone_equation
    (k : Type u) [CommRing k] :
    chapter04QuadraticConeCoordinate k 0 * chapter04QuadraticConeCoordinate k 1 =
      chapter04QuadraticConeCoordinate k 2 ^ 2 := by
  sorry

/-- The origin ideal generated by the three coordinate classes. -/
def chapter04QuadraticConeOriginIdeal (k : Type u) [CommRing k] :
    Ideal (chapter04QuadraticConeRing k) :=
  Ideal.span ({chapter04QuadraticConeCoordinate k 0,
    chapter04QuadraticConeCoordinate k 1,
    chapter04QuadraticConeCoordinate k 2} : Set (chapter04QuadraticConeRing k))

def chapter04QuadraticConeScheme (k : Type u) [CommRing k] : Scheme.{u} :=
  Scheme.Spec (CommRingCat.of (chapter04QuadraticConeRing k))

def chapter04QuadraticConeOriginPoint (k : Type u) [CommRing k]
    (hprime : (chapter04QuadraticConeOriginIdeal k).IsPrime) :
    chapter04QuadraticConeScheme k :=
  ⟨chapter04QuadraticConeOriginIdeal k, hprime⟩

/-- Regularity at the vertex, with the prime proof made explicit for localization. -/
def Chapter04QuadraticConeRegularAtOrigin (k : Type u) [CommRing k]
    (hprime : (chapter04QuadraticConeOriginIdeal k).IsPrime) : Prop :=
  letI := hprime
  IsRegularLocalRing (Localization.AtPrime (chapter04QuadraticConeOriginIdeal k))

/-- The vertex needs three generators, expressed as non-generation by two elements. -/
def Chapter04QuadraticConeOriginNeedsThreeGenerators (k : Type u) [CommRing k] : Prop :=
  ¬ ∃ a b : chapter04QuadraticConeRing k,
      chapter04QuadraticConeOriginIdeal k =
        Ideal.span ({a, b} : Set (chapter04QuadraticConeRing k))

theorem chapter04_quadratic_cone_origin_is_generated_by_coordinates
    (k : Type u) [CommRing k] :
    chapter04QuadraticConeOriginIdeal k =
      Ideal.span ({chapter04QuadraticConeCoordinate k 0,
        chapter04QuadraticConeCoordinate k 1,
        chapter04QuadraticConeCoordinate k 2} :
        Set (chapter04QuadraticConeRing k)) := by
  rfl

/-- The normality assertion for the quadratic cone. -/
def Chapter04QuadraticConeNormal (k : Type u) [CommRing k] : Prop :=
  IsDomain (chapter04QuadraticConeRing k) ∧
    IsIntegrallyClosed (chapter04QuadraticConeRing k)

/-- The singularity assertion at the vertex. -/
def Chapter04QuadraticConeOriginSingular (k : Type u) [CommRing k] : Prop :=
  ∃ hprime : (chapter04QuadraticConeOriginIdeal k).IsPrime,
    ¬ Chapter04QuadraticConeRegularAtOrigin k hprime

/-- The vertex is the only nonregular point of the cone. -/
def Chapter04QuadraticConeOnlySingularAtOrigin (k : Type u) [CommRing k] : Prop :=
  ∃ hprime : (chapter04QuadraticConeOriginIdeal k).IsPrime,
    ∀ x : chapter04QuadraticConeScheme k,
      x ∈ Chapter04NonRegularLocus (chapter04QuadraticConeScheme k) ↔
        x = chapter04QuadraticConeOriginPoint k hprime

/-- The vertex has codimension two on the two-dimensional cone. -/
def Chapter04QuadraticConeOriginHasCodimensionTwo (k : Type u) [CommRing k] : Prop :=
  ∃ hprime : (chapter04QuadraticConeOriginIdeal k).IsPrime,
    Order.coheight (chapter04QuadraticConeOriginPoint k hprime) = 2

/-- A hypersurface presentation of the cone is Cohen--Macaulay. -/
theorem chapter04_quadratic_cone_hypersurface_is_CohenMacaulay
    (k : Type u) [Field k] (hchar : ringChar k ≠ 2) :
    Chapter04CohenMacaulay (chapter04QuadraticConeRing k) := by
  sorry

theorem chapter04_quadratic_cone_hypersurface_is_S2
    (k : Type u) [Field k] (hchar : ringChar k ≠ 2) :
    Chapter04S2 (chapter04QuadraticConeRing k) := by
  sorry

/-- The isolated vertex gives the height-one regularity condition `(R1)`. -/
theorem chapter04_quadratic_cone_satisfies_R1
    (k : Type u) [Field k] (hchar : ringChar k ≠ 2) :
    Chapter04R1 (chapter04QuadraticConeRing k) := by
  sorry

/-- The quadratic cone is a normal domain although it is not regular at its vertex. -/
theorem chapter04_quadratic_cone_normal_not_regular
    (k : Type u) [Field k] (hchar : ringChar k ≠ 2) :
    Chapter04QuadraticConeNormal k ∧
      Chapter04QuadraticConeOriginNeedsThreeGenerators k ∧
      Chapter04QuadraticConeOriginSingular k ∧
      Chapter04QuadraticConeOnlySingularAtOrigin k ∧
      Chapter04QuadraticConeOriginHasCodimensionTwo k := by
  sorry

/-- The relative-normalization map of an already normal cone is an isomorphism. -/
def Chapter04NormalizationIsTrivial {X Y : Scheme.{u}} (f : X ⟶ Y)
    [QuasiCompact f] [QuasiSeparated f] : Prop :=
  IsIso f.toNormalization

theorem chapter04_quadratic_cone_normalization_does_nothing
    (k : Type u) [Field k] (hchar : ringChar k ≠ 2) :
    Chapter04NormalizationIsTrivial
      (𝟙 (chapter04QuadraticConeScheme k)) := by
  sorry

/-- Blowing up the vertex produces a regular surface with projective-line exceptional divisor. -/
theorem chapter04_quadratic_cone_blowup_resolves_vertex
    (k : Type u) [Field k] (hchar : ringChar k ≠ 2) :
    Nonempty (Chapter04QuadraticConeResolutionData k) := by
  sorry

/-! The arithmetic node `R[x,y]/(xy-π)`. -/

/-- The equation of the node over a base ring. -/
def chapter04DvrNodeEquation (R : Type u) [CommRing R] (π : R) :
    MvPolynomial (Fin 2) R :=
  MvPolynomial.X 0 * MvPolynomial.X 1 - MvPolynomial.C π

def chapter04DvrNodeRelationIdeal (R : Type u) [CommRing R] (π : R) :
    Ideal (MvPolynomial (Fin 2) R) :=
  Ideal.span ({chapter04DvrNodeEquation R π} : Set (MvPolynomial (Fin 2) R))

def chapter04DvrNodeAmbientIdeal (R : Type u) [CommRing R] (π : R) :
    Ideal (MvPolynomial (Fin 2) R) :=
  Ideal.span ({MvPolynomial.C π, MvPolynomial.X 0, MvPolynomial.X 1} :
    Set (MvPolynomial (Fin 2) R))

def chapter04DvrNodeAmbientLocalRing (R : Type u) [CommRing R] (π : R)
    (hprime : (chapter04DvrNodeAmbientIdeal R π).IsPrime) : Type u :=
  letI := hprime
  Localization.AtPrime (chapter04DvrNodeAmbientIdeal R π)

def Chapter04DvrNodeAmbientParametersRegular (R : Type u) [CommRing R] (π : R)
    (hprime : (chapter04DvrNodeAmbientIdeal R π).IsPrime) : Prop :=
  letI := hprime
  RingTheory.Sequence.IsRegular (chapter04DvrNodeAmbientLocalRing R π hprime)
    [algebraMap (MvPolynomial (Fin 2) R)
        (chapter04DvrNodeAmbientLocalRing R π hprime) (MvPolynomial.C π),
      algebraMap (MvPolynomial (Fin 2) R)
        (chapter04DvrNodeAmbientLocalRing R π hprime) (MvPolynomial.X 0),
      algebraMap (MvPolynomial (Fin 2) R)
        (chapter04DvrNodeAmbientLocalRing R π hprime) (MvPolynomial.X 1)]

theorem chapter04_dvr_node_ambient_ideal_is_prime
    (R : Type u) [CommRing R] [IsDomain R] [IsDiscreteValuationRing R]
    (π : R) (hπ : Irreducible π) :
    (chapter04DvrNodeAmbientIdeal R π).IsPrime := by
  sorry

theorem chapter04_dvr_node_ambient_parameters_are_regular
    (R : Type u) [CommRing R] [IsDomain R] [IsDiscreteValuationRing R]
    (π : R) (hπ : Irreducible π)
    (hprime : (chapter04DvrNodeAmbientIdeal R π).IsPrime) :
    Chapter04DvrNodeAmbientParametersRegular R π hprime := by
  sorry

def Chapter04DvrNodeAmbientLocalRingIsRegular
    (R : Type u) [CommRing R] (π : R)
    (hprime : (chapter04DvrNodeAmbientIdeal R π).IsPrime) : Prop :=
  letI := hprime
  IsRegularLocalRing (chapter04DvrNodeAmbientLocalRing R π hprime)

theorem chapter04_dvr_node_ambient_local_ring_is_regular
    (R : Type u) [CommRing R] [IsDomain R] [IsDiscreteValuationRing R]
    (π : R) (hπ : Irreducible π)
    (hprime : (chapter04DvrNodeAmbientIdeal R π).IsPrime) :
    Chapter04DvrNodeAmbientLocalRingIsRegular R π hprime := by
  sorry

/-- The arithmetic node ring `R[x,y]/(xy-π)`. -/
abbrev chapter04DvrNodeRing (R : Type u) [CommRing R] (π : R) :=
  MvPolynomial (Fin 2) R ⧸ chapter04DvrNodeRelationIdeal R π

def chapter04DvrNodeStructureMap (R : Type u) [CommRing R] (π : R) :
    Scheme.Spec (CommRingCat.of (chapter04DvrNodeRing R π)) ⟶
      Scheme.Spec (CommRingCat.of R) :=
  Scheme.Spec.map (CommRingCat.ofHom (algebraMap R (chapter04DvrNodeRing R π)))

def chapter04DvrNodeCoordinate (R : Type u) [CommRing R] (π : R) (i : Fin 2) :
    chapter04DvrNodeRing R π :=
  Ideal.Quotient.mk (chapter04DvrNodeRelationIdeal R π) (MvPolynomial.X i)

theorem chapter04_dvr_node_equation (R : Type u) [CommRing R] (π : R) :
    chapter04DvrNodeCoordinate R π 0 * chapter04DvrNodeCoordinate R π 1 =
      algebraMap R (chapter04DvrNodeRing R π) π := by
  sorry

/-- The node point, whose maximal ideal is generated by the two coordinates. -/
def chapter04DvrNodeMaximalIdeal (R : Type u) [CommRing R] (π : R) :
    Ideal (chapter04DvrNodeRing R π) :=
  Ideal.span ({chapter04DvrNodeCoordinate R π 0,
    chapter04DvrNodeCoordinate R π 1} : Set (chapter04DvrNodeRing R π))

theorem chapter04_dvr_node_uniformizer_mem_maximal_ideal
    (R : Type u) [CommRing R] (π : R) :
    algebraMap R (chapter04DvrNodeRing R π) π ∈ chapter04DvrNodeMaximalIdeal R π := by
  sorry

def Chapter04DvrNodeMaximalIdealIsMaximal (R : Type u) [CommRing R] (π : R) : Prop :=
  (chapter04DvrNodeMaximalIdeal R π).IsMaximal

def Chapter04DvrNodeLocalDimensionTwo (R : Type u) [CommRing R] (π : R)
    (hprime : (chapter04DvrNodeMaximalIdeal R π).IsPrime) : Prop :=
  letI := hprime
  ringKrullDim (Localization.AtPrime (chapter04DvrNodeMaximalIdeal R π)) = 2

theorem chapter04_dvr_node_maximal_ideal_is_maximal
    (R : Type u) [CommRing R] [IsDomain R] [IsDiscreteValuationRing R]
    (π : R) (hπ : Irreducible π) :
    Chapter04DvrNodeMaximalIdealIsMaximal R π := by
  sorry

def Chapter04DvrNodeRegularAtNode (R : Type u) [CommRing R] (π : R)
    (hprime : (chapter04DvrNodeMaximalIdeal R π).IsPrime) : Prop :=
  letI := hprime
  IsRegularLocalRing (Localization.AtPrime (chapter04DvrNodeMaximalIdeal R π))

theorem chapter04_dvr_node_local_dimension_two
    (R : Type u) [CommRing R] [IsDomain R] [IsDiscreteValuationRing R]
    (π : R) (hπ : Irreducible π)
    (hprime : (chapter04DvrNodeMaximalIdeal R π).IsPrime) :
    Chapter04DvrNodeLocalDimensionTwo R π hprime := by
  sorry

def Chapter04DvrNodeFlatOverBase (R : Type u) [CommRing R]
    (π : R) : Prop :=
  Module.Flat R (chapter04DvrNodeRing R π)

def Chapter04DvrNodeMorphismFlat (R : Type u) [CommRing R] (π : R) : Prop :=
  Flat (chapter04DvrNodeStructureMap R π)

/-- The special fiber has the nodal equation `k[x,y]/(xy)`. -/
abbrev chapter04DvrNodeSpecialFiber (R : Type u) [CommRing R] [IsLocalRing R] :=
  MvPolynomial (Fin 2) (IsLocalRing.ResidueField R) ⧸
    Ideal.span ({MvPolynomial.X 0 * MvPolynomial.X 1} :
      Set (MvPolynomial (Fin 2) (IsLocalRing.ResidueField R)))

def chapter04DvrNodeSpecialFiberOriginIdeal (R : Type u) [CommRing R] [IsLocalRing R] :
    Ideal (chapter04DvrNodeSpecialFiber R) :=
  Ideal.span ({
    Ideal.Quotient.mk (Ideal.span ({MvPolynomial.X 0 * MvPolynomial.X 1} :
      Set (MvPolynomial (Fin 2) (IsLocalRing.ResidueField R)))) (MvPolynomial.X 0),
    Ideal.Quotient.mk (Ideal.span ({MvPolynomial.X 0 * MvPolynomial.X 1} :
      Set (MvPolynomial (Fin 2) (IsLocalRing.ResidueField R)))) (MvPolynomial.X 1)
  } : Set (chapter04DvrNodeSpecialFiber R))

def Chapter04DvrNodeSpecialFiberNodal (R : Type u) [CommRing R] [IsLocalRing R] : Prop :=
  ∃ hprime : (chapter04DvrNodeSpecialFiberOriginIdeal R).IsPrime,
    ¬ (letI := hprime
       IsRegularLocalRing
         (Localization.AtPrime (chapter04DvrNodeSpecialFiberOriginIdeal R)))

def Chapter04DvrNodeSmoothAtNode (R : Type u) [CommRing R]
    [IsDomain R] [IsDiscreteValuationRing R] (π : R)
    (hprime : (chapter04DvrNodeMaximalIdeal R π).IsPrime) : Prop :=
  Chapter04AlgebraSmoothAt R (chapter04DvrNodeRing R π)
    (chapter04DvrNodeMaximalIdeal R π) hprime

/-- The node is regular and flat, but its special fiber is nodal and it is not smooth. -/
theorem chapter04_dvr_node_regular_flat_nodal_not_smooth
    (R : Type u) [CommRing R] [IsDomain R] [IsDiscreteValuationRing R]
    (π : R) (hπ : Irreducible π)
    (hprime : (chapter04DvrNodeMaximalIdeal R π).IsPrime) :
    Chapter04DvrNodeRegularAtNode R π hprime ∧
      Chapter04DvrNodeFlatOverBase R π ∧
      Chapter04DvrNodeMorphismFlat R π ∧
      Chapter04DvrNodeSpecialFiberNodal R ∧
      ¬ Chapter04DvrNodeSmoothAtNode R π hprime ∧
      ¬ Smooth (chapter04DvrNodeStructureMap R π) := by
  sorry

end

end LastLib.Book11NormalizationAndRegularModelsOfArithmeticCurves.Chapter04
