import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter06.Section01WhyFrobeniusIsCanonical
import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter06.Section02FrobeniusInAnUnramifiedExtension
import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter06.Section03CompatibilityInTowers
import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter06.Section04PolynomialPicture
import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter06.Section05TraceAndNormUnderFiniteFieldFrobenius
import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter06.Section06FrobeniusAndRestriction
