import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter14.Section01APrimeAndItsCompletedBranches
import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter14.Section02FrobeniusAtAnUnramifiedPrime
import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter14.Section03FactorizationAndFrobeniusCycleType
import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter14.Section04WeakApproximationForCoefficients
import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter14.Section05PrescribingFinitelyManyLocalCompletions
import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter14.Section06WhatApproximationDoesNotPrescribe
