import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter04.Section01LinearAlgebraTurnedIntoArithmetic
import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter04.Section02CharacteristicPolynomialsAndIntegralRestriction
import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter04.Section03Transitivity
import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter04.Section04TheValuationOfANorm
import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter04.Section05ResidueFieldShadows
import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter04.Section06TracePairingsAndSeparability
import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter04.Section07MinimalPolynomialsAndMultiplicities
import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter04.Section08NormsOfIdealsAndDeterminants
