import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter03.Section01WhyTowerFormulasMatter
import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter03.Section02IntersectionsAndComposita
import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter03.Section03CompletionSeparatesBranches
import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter03.Section04ScalarExtensionOfALocalField
import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter03.Section05MixedAndEqualCharacteristic
import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter03.Section06QuadraticLaboratory
import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter03.Section07ContinuityOfEmbeddings

/-! # Chapter 3: Towers, completion, and change of base

The imports follow the seven sections of the chapter in source order. -/
