import LastLib.Book12BlowupsAndIntersectionTheoryOnArithmeticSurfaces.Chapter03.Section01ConstructionAndProjectivity

namespace LastLib.Book12BlowupsAndIntersectionTheoryOnArithmeticSurfaces.Chapter03

universe u v

noncomputable section

open AlgebraicGeometry CategoryTheory Set
open Polynomial
open scoped AlgebraicGeometry

/-! ## 3.2. Affine charts -/

/-- The chart subalgebra generated by the ratios `f_j / f_i` in `A_{f_i}`. -/
def chapter03AffineChartRing
    {A : Type u} [CommRing A] {ι : Type v} (f : ι → A) (i : ι) :
    Subalgebra A (Localization.Away (f i)) :=
  Algebra.adjoin A (Set.range (fun j =>
    algebraMap A (Localization.Away (f i)) (f j) /
      algebraMap A (Localization.Away (f i)) (f i)))

/-- The coordinate represented by the ratio `f_j / f_i` in the `i`-chart. -/
def chapter03AffineChartCoordinate
    {A : Type u} [CommRing A] {ι : Type v} (f : ι → A) (i j : ι) :
    Localization.Away (f i) :=
  algebraMap A (Localization.Away (f i)) (f j) /
    algebraMap A (Localization.Away (f i)) (f i)

@[simp]
theorem chapter03_affine_chart_ring_mem_iff
    {A : Type u} [CommRing A] {ι : Type v} (f : ι → A) (i : ι)
    (z : Localization.Away (f i)) :
    z ∈ chapter03AffineChartRing f i ↔
      z ∈ Algebra.adjoin A (Set.range (fun j =>
        algebraMap A (Localization.Away (f i)) (f j) /
          algebraMap A (Localization.Away (f i)) (f i))) :=
  Iff.rfl

theorem chapter03_affine_chart_coordinate_mul_denominator
    {A : Type u} [CommRing A] {ι : Type v} (f : ι → A) (i j : ι) :
    algebraMap A (Localization.Away (f i)) (f i) *
        chapter03AffineChartCoordinate f i j =
      algebraMap A (Localization.Away (f i)) (f j) := by
  sorry

def Chapter03AffineChartPresentation
    {A : Type u} [CommRing A] {ι : Type v}
    (f : ι → A) (i : ι) : Prop :=
  chapter03AffineChartRing f i =
    Algebra.adjoin A (Set.range (fun j =>
      algebraMap A (Localization.Away (f i)) (f j) /
        algebraMap A (Localization.Away (f i)) (f i)))

theorem chapter03_affine_chart_presentation
    {A : Type u} [CommRing A] {ι : Type v} (f : ι → A) (i : ι) :
    Chapter03AffineChartPresentation f i := by
  rfl

theorem chapter03_affine_chart_domain_formula
    {A : Type u} [CommRing A] [IsDomain A] {ι : Type v}
    (f : ι → A) (i : ι) (hi : f i ≠ 0) :
    chapter03AffineChartRing f i =
      Algebra.adjoin A (Set.range (fun j =>
        algebraMap A (Localization.Away (f i)) (f j) /
          algebraMap A (Localization.Away (f i)) (f i))) := by
  rfl

/-! ### The origin in the affine plane -/

abbrev Chapter03AffinePlane (k : Type u) [CommRing k] := MvPolynomial (Fin 2) k

def chapter03AffinePlaneX {k : Type u} [CommRing k] : Chapter03AffinePlane k :=
  MvPolynomial.X 0

def chapter03AffinePlaneY {k : Type u} [CommRing k] : Chapter03AffinePlane k :=
  MvPolynomial.X 1

def chapter03OriginGenerators {k : Type u} [CommRing k] :
    Fin 2 → Chapter03AffinePlane k :=
  Fin.cases chapter03AffinePlaneX (fun _ => chapter03AffinePlaneY)

def chapter03OriginPlaneIdeal {k : Type u} [CommRing k] :
    Ideal (Chapter03AffinePlane k) :=
  Ideal.span (Set.range (chapter03OriginGenerators : Fin 2 → Chapter03AffinePlane k))

theorem chapter03_origin_plane_ideal_fg
    {k : Type u} [CommRing k] :
    (chapter03OriginPlaneIdeal k).FG := by
  sorry

def chapter03OriginBaseScheme {k : Type u} [CommRing k] : Scheme.{u} :=
  AlgebraicGeometry.Spec (CommRingCat.of (Chapter03AffinePlane k))

noncomputable def chapter03OriginCoherentIdeal
    {k : Type u} [CommRing k] : Chapter03CoherentIdeal (chapter03OriginBaseScheme k) :=
  chapter07AffineCoherentIdeal
    (Chapter03AffinePlane k) (chapter03OriginPlaneIdeal k)
    (chapter03_origin_plane_ideal_fg (k := k))

def chapter03OriginXChartRing {k : Type u} [CommRing k] :=
  MvPolynomial (Fin 2) k

def chapter03OriginYChartRing {k : Type u} [CommRing k] :=
  MvPolynomial (Fin 2) k

def chapter03OriginXChartX {k : Type u} [CommRing k] : chapter03OriginXChartRing k :=
  MvPolynomial.X 0

def chapter03OriginXChartT {k : Type u} [CommRing k] : chapter03OriginXChartRing k :=
  MvPolynomial.X 1

def chapter03OriginYChartS {k : Type u} [CommRing k] : chapter03OriginYChartRing k :=
  MvPolynomial.X 0

def chapter03OriginYChartY {k : Type u} [CommRing k] : chapter03OriginYChartRing k :=
  MvPolynomial.X 1

def chapter03OriginXChartMap {k : Type u} [CommRing k] :
    Chapter03AffinePlane k →ₐ[k] chapter03OriginXChartRing k :=
  MvPolynomial.eval₂AlgHom k
    (Fin.cases chapter03OriginXChartX
      (fun _ => chapter03OriginXChartX * chapter03OriginXChartT))

def chapter03OriginYChartMap {k : Type u} [CommRing k] :
    Chapter03AffinePlane k →ₐ[k] chapter03OriginYChartRing k :=
  MvPolynomial.eval₂AlgHom k
    (Fin.cases (chapter03OriginYChartS * chapter03OriginYChartY)
      (fun _ => chapter03OriginYChartY))

theorem chapter03_origin_x_chart_x_coordinate
    {k : Type u} [CommRing k] :
    chapter03OriginXChartMap k chapter03AffinePlaneX = chapter03OriginXChartX := by
  sorry

theorem chapter03_origin_x_chart_y_coordinate
    {k : Type u} [CommRing k] :
    chapter03OriginXChartMap k chapter03AffinePlaneY =
      chapter03OriginXChartX * chapter03OriginXChartT := by
  sorry

theorem chapter03_origin_y_chart_x_coordinate
    {k : Type u} [CommRing k] :
    chapter03OriginYChartMap k chapter03AffinePlaneX =
      chapter03OriginYChartS * chapter03OriginYChartY := by
  sorry

theorem chapter03_origin_y_chart_y_coordinate
    {k : Type u} [CommRing k] :
    chapter03OriginYChartMap k chapter03AffinePlaneY = chapter03OriginYChartY := by
  sorry

def chapter03OriginOverlapRing {k : Type u} [CommRing k] :=
  Localization.Away (chapter03OriginXChartT (k := k))

def chapter03OriginOverlapT {k : Type u} [CommRing k] : chapter03OriginOverlapRing k :=
  algebraMap (chapter03OriginXChartRing k) (chapter03OriginOverlapRing k)
    chapter03OriginXChartT

def chapter03OriginOverlapS {k : Type u} [CommRing k] : chapter03OriginOverlapRing k :=
  (chapter03OriginOverlapT (k := k))⁻¹

theorem chapter03_origin_overlap_s_mul_t
    {k : Type u} [CommRing k] :
    chapter03OriginOverlapS (k := k) * chapter03OriginOverlapT (k := k) = 1 := by
  sorry

theorem chapter03_origin_overlap_s_eq_t_inv
    {k : Type u} [CommRing k] :
    chapter03OriginOverlapS (k := k) =
      (chapter03OriginOverlapT (k := k))⁻¹ :=
  rfl

def chapter03OriginXChartExceptionalIdeal {k : Type u} [CommRing k] :
    Ideal (chapter03OriginXChartRing k) :=
  Ideal.span ({chapter03OriginXChartX} : Set (chapter03OriginXChartRing k))

def chapter03OriginYChartExceptionalIdeal {k : Type u} [CommRing k] :
    Ideal (chapter03OriginYChartRing k) :=
  Ideal.span ({chapter03OriginYChartY} : Set (chapter03OriginYChartRing k))

theorem chapter03_origin_x_chart_exceptional_equation
    {k : Type u} [CommRing k] :
    chapter03OriginXChartExceptionalIdeal (k := k) =
      Ideal.span ({chapter03OriginXChartX} : Set (chapter03OriginXChartRing k)) := by
  rfl

theorem chapter03_origin_y_chart_exceptional_equation
    {k : Type u} [CommRing k] :
    chapter03OriginYChartExceptionalIdeal (k := k) =
      Ideal.span ({chapter03OriginYChartY} : Set (chapter03OriginYChartRing k)) := by
  rfl

noncomputable def chapter03OriginBlowup
    {k : Type u} [Field k] :
    Chapter03Blowup (chapter03OriginCoherentIdeal (k := k)) :=
  chapter03Blowup (chapter03OriginCoherentIdeal (k := k))

/- LOCAL_DEPENDENCY_GUESS (3.2): the two chart affine lines glue along the inversion overlap and
identify the exceptional subscheme of the origin blowup with the projective line. -/
structure Chapter03OriginBlowupChartData (k : Type u) [Field k] where
  x_chart_relation :
    chapter03OriginXChartMap k chapter03AffinePlaneY =
      chapter03OriginXChartX * chapter03OriginXChartT
  y_chart_relation :
    chapter03OriginYChartMap k chapter03AffinePlaneX =
      chapter03OriginYChartS * chapter03OriginYChartY
  overlap_relation :
    chapter03OriginOverlapS (k := k) =
      (chapter03OriginOverlapT (k := k))⁻¹
  x_exceptional :
    chapter03OriginXChartExceptionalIdeal (k := k) =
      Ideal.span ({chapter03OriginXChartX} : Set (chapter03OriginXChartRing k))
  y_exceptional :
    chapter03OriginYChartExceptionalIdeal (k := k) =
      Ideal.span ({chapter03OriginYChartY} : Set (chapter03OriginYChartRing k))
  exceptional_is_projective_line :
    chapter03BlowupExceptionalSubscheme (chapter03OriginBlowup (k := k)) ≅
      chapter04ProjectiveLine k

theorem chapter03_origin_blowup_chart_data_exists
    (k : Type u) [Field k] :
    Nonempty (Chapter03OriginBlowupChartData k) := by
  sorry

noncomputable def chapter03OriginBlowupChartData
    (k : Type u) [Field k] :
    Chapter03OriginBlowupChartData k :=
  Classical.choice (chapter03_origin_blowup_chart_data_exists k)

theorem chapter03_origin_exceptional_is_projective_line
    (k : Type u) [Field k] :
    Nonempty (chapter03BlowupExceptionalSubscheme (chapter03OriginBlowup (k := k)) ≅
      chapter04ProjectiveLine k) := by
  exact ⟨(chapter03OriginBlowupChartData k).exceptional_is_projective_line⟩

/-! ### A cusp chart and the distinction between strict and total transforms -/

def chapter03CuspBaseEquation {k : Type u} [CommRing k] : Chapter03AffinePlane k :=
  chapter03AffinePlaneY ^ 2 - chapter03AffinePlaneX ^ 3

def chapter03CuspXChartTotalTransformEquation {k : Type u} [CommRing k] :
    chapter03OriginXChartRing k :=
  chapter03OriginXChartX ^ 2 *
    (chapter03OriginXChartT ^ 2 - chapter03OriginXChartX)

def chapter03CuspXChartExceptionalFactor {k : Type u} [CommRing k] :
    chapter03OriginXChartRing k :=
  chapter03OriginXChartX ^ 2

def chapter03CuspXChartStrictTransformEquation {k : Type u} [CommRing k] :
    chapter03OriginXChartRing k :=
  chapter03OriginXChartT ^ 2 - chapter03OriginXChartX

theorem chapter03_cusp_x_chart_substitution
    {k : Type u} [CommRing k] :
    chapter03OriginXChartMap k (chapter03CuspBaseEquation (k := k)) =
      chapter03CuspXChartTotalTransformEquation (k := k) := by
  sorry

theorem chapter03_cusp_x_chart_exceptional_factorization
    {k : Type u} [CommRing k] :
    chapter03CuspXChartTotalTransformEquation (k := k) =
      chapter03CuspXChartExceptionalFactor (k := k) *
        chapter03CuspXChartStrictTransformEquation (k := k) := by
  rfl

structure Chapter03CuspChartAnalysis (k : Type u) [Field k] where
  total_transform_equation :
    chapter03CuspXChartTotalTransformEquation (k := k) =
      chapter03CuspXChartExceptionalFactor (k := k) *
        chapter03CuspXChartStrictTransformEquation (k := k)
  exceptional_part_is_x_squared :
    chapter03CuspXChartExceptionalFactor (k := k) = chapter03OriginXChartX ^ 2
  strict_transform_equation :
    chapter03CuspXChartStrictTransformEquation (k := k) =
      chapter03OriginXChartT ^ 2 - chapter03OriginXChartX
  strict_transform_is_smooth : Prop
  strict_transform_tangent_to_exceptional : Prop
  resolving_curve_differs_from_normal_crossing_boundary : Prop

theorem chapter03_cusp_chart_analysis_exists
    (k : Type u) [Field k] :
    Nonempty (Chapter03CuspChartAnalysis k) := by
  sorry

noncomputable def chapter03CuspChartAnalysis
    (k : Type u) [Field k] : Chapter03CuspChartAnalysis k :=
  Classical.choice (chapter03_cusp_chart_analysis_exists k)

end

end LastLib.Book12BlowupsAndIntersectionTheoryOnArithmeticSurfaces.Chapter03
