import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter14.Section02FrobeniusAtAnUnramifiedPrime

namespace LastLib.Book02FiniteExtensionsOfLocalFields.Chapter14

noncomputable section

open Polynomial
open scoped BigOperators NumberField TensorProduct

universe uF uΩ uK uk uL

/-! ## 14.3. Factorization and Frobenius cycle type -/

/- A localization-friendly spelling of “the order generated by `α` agrees
   with the integral closure”.  Membership in both sides is expressed by the
   same denominator test outside the chosen prime. -/
def chapter14LocalizedOrderMembership
    {F E : Type*} [Field F] [NumberField F] [Field E] [NumberField E]
    [Algebra F E] (O : Subalgebra (𝓞 F) E) (p : Chapter14Prime F) (x : E) : Prop :=
  ∃ s : 𝓞 F, s ∉ p.asIdeal ∧
    algebraMap (𝓞 F) E s * x ∈ O

def chapter14LocalizedIntegralClosureMembership
    {F E : Type*} [Field F] [NumberField F] [Field E] [NumberField E]
    [Algebra F E] (p : Chapter14Prime F) (x : E) : Prop :=
  ∃ s : 𝓞 F, s ∉ p.asIdeal ∧
    IsIntegral (𝓞 F) (algebraMap (𝓞 F) E s * x)

def chapter14OrderAgreesWithIntegralClosureAtPrime
    {F E : Type*} [Field F] [NumberField F] [Field E] [NumberField E]
    [Algebra F E] (O : Subalgebra (𝓞 F) E) (p : Chapter14Prime F) : Prop :=
  ∀ x : E,
    chapter14LocalizedOrderMembership O p x ↔
      chapter14LocalizedIntegralClosureMembership p x

def chapter14MonogenicOrder
    {F E : Type*} [Field F] [NumberField F] [Field E] [NumberField E]
    [Algebra F E] (α : E) : Subalgebra (𝓞 F) E :=
  Algebra.adjoin (𝓞 F) ({α} : Set E)

structure Chapter14GoodReductionData
    (F E : Type*) [Field F] [NumberField F] [Field E] [NumberField E]
    [Algebra F E] [FiniteDimensional F E] (p : Chapter14Prime F) where
  alpha : E
  generates : Algebra.adjoin F ({alpha} : Set E) = ⊤
  polynomial : (𝓞 F)[X]
  monic : polynomial.Monic
  irreducible : Irreducible polynomial
  root : aeval alpha polynomial = 0
  minimal :
    polynomial.map (algebraMap (𝓞 F) F) = minpoly F alpha
  order_agrees :
    chapter14OrderAgreesWithIntegralClosureAtPrime
      (chapter14MonogenicOrder alpha) p
  reduction : p.asIdeal.ResidueField[X]
  reduction_eq_map :
    reduction = polynomial.map (algebraMap (𝓞 F) p.asIdeal.ResidueField)
  reduction_separable : reduction.Separable

def chapter14GoodReductionQualification
    {F E : Type*} [Field F] [NumberField F] [Field E] [NumberField E]
    [Algebra F E] [FiniteDimensional F E] {p : Chapter14Prime F}
    (D : Chapter14GoodReductionData F E p) : Prop :=
  chapter14OrderAgreesWithIntegralClosureAtPrime
      (chapter14MonogenicOrder D.alpha) p ∧ D.reduction.Separable

/- A failed separability or order condition is the precise obstruction behind
   the source's warning that a repeated reduction factor is not intrinsic. -/
def chapter14ReductionNotSeparable
    {F E : Type*} [Field F] [NumberField F] [Field E] [NumberField E]
    [Algebra F E] [FiniteDimensional F E] {p : Chapter14Prime F}
    (D : Chapter14GoodReductionData F E p) : Prop :=
  ¬D.reduction.Separable

def chapter14NonIntrinsicFactorizationWarning
    {F E : Type*} [Field F] [NumberField F] [Field E] [NumberField E]
    [Algebra F E] [FiniteDimensional F E] {p : Chapter14Prime F}
    (D : Chapter14GoodReductionData F E p) : Prop :=
  ¬ chapter14OrderAgreesWithIntegralClosureAtPrime
      (chapter14MonogenicOrder D.alpha) p ∨ chapter14ReductionNotSeparable D

structure Chapter14ReducedFactorization
    {F E : Type*} [Field F] [NumberField F] [Field E] [NumberField E]
    [Algebra F E] [FiniteDimensional F E] {p : Chapter14Prime F}
    (D : Chapter14GoodReductionData F E p) (g : ℕ) where
  factor : Fin g → p.asIdeal.ResidueField[X]
  monic : ∀ i, (factor i).Monic
  irreducible : ∀ i, Irreducible (factor i)
  separable : ∀ i, (factor i).Separable
  distinct : Pairwise (fun i j => factor i ≠ factor j)
  product : D.reduction = ∏ i, factor i

def chapter14PrimeUnramifiedAt
    {F E : Type*} [Field F] [NumberField F] [Field E] [NumberField E]
    [Algebra F E] [FiniteDimensional F E] (p : Chapter14Prime F) : Prop :=
  ∀ P : Chapter14PrimeAbove F E p, chapter14RamificationIndex E p P = 1

/- A factor is retained as a bundled local field, residue field, and residue
   quotient so its unramified-extension data survive existential statements. -/
structure Chapter14UnramifiedFactor
    (K : Type uK) (k : Type uk) [Field K] [Field k] (factor : k[X]) where
  carrier : Type uL
  [field_carrier : Field carrier]
  [algebra : Algebra K carrier]
  [finite_dimensional : FiniteDimensional K carrier]
  residue : Type uL
  [residue_field : Field residue]
  [residue_algebra : Algebra k residue]
  [residue_finite_dimensional : FiniteDimensional k residue]
  profile :
    LastLib.Book02FiniteExtensionsOfLocalFields.Chapter07.Chapter07FiniteLocalExtensionData
      K carrier k residue
  unramified :
    LastLib.Book02FiniteExtensionsOfLocalFields.Chapter07.Chapter07UnramifiedExtension profile
  degree :
    letI : Field carrier := field_carrier
    letI : Algebra K carrier := algebra
    letI : FiniteDimensional K carrier := finite_dimensional
    Module.finrank K carrier = factor.natDegree
  factor_quotient_equiv : Nonempty (AdjoinRoot factor ≃ₐ[k] residue)

theorem chapter14_good_reduction_gives_prime_factorization
    {F E : Type*} [Field F] [NumberField F] [Field E] [NumberField E]
    [Algebra F E] [FiniteDimensional F E] (p : Chapter14Prime F)
    (D : Chapter14GoodReductionData F E p) (g : ℕ)
    (H : Chapter14ReducedFactorization D g) :
    ∃ e : Fin g ≃ Chapter14PrimeAbove F E p,
      chapter14PrimeUnramifiedAt (E := E) p ∧
        (∀ i, chapter14RamificationIndex E p (e i) = 1) ∧
        (∀ i, chapter14ResidueDegree E p (e i) =
          (H.factor i).natDegree) := by
  sorry

theorem chapter14_good_reduction_completed_factorization
    {F E : Type*} [Field F] [NumberField F] [Field E] [NumberField E]
    [Algebra F E] [FiniteDimensional F E] (p : Chapter14Prime F)
    [Algebra F (chapter14BaseCompletion F p)]
    (D : Chapter14GoodReductionData F E p) (g : ℕ)
    (H : Chapter14ReducedFactorization D g) :
    ∃ L : ∀ i, Chapter14UnramifiedFactor
        (chapter14BaseCompletion F p) p.asIdeal.ResidueField (H.factor i),
      letI : ∀ i, Field (L i).carrier := fun i => (L i).field_carrier
      Nonempty
        (E ⊗[F] chapter14BaseCompletion F p ≃+*
          (∀ i, (L i).carrier)) := by
  sorry

def Chapter14RootSet
    (F : Type uF) (Ω : Type uΩ) [Field F] [Field Ω] [Algebra F Ω]
    (f : F[X]) : Type uΩ :=
  {x : Ω // aeval x f = 0}

def chapter14RootPermutation
    {F Ω : Type*} [Field F] [Field Ω] [Algebra F Ω]
    (f : F[X]) (σ : Gal(Ω / F)) :
    Equiv.Perm (Chapter14RootSet F Ω f) := by
  sorry

theorem chapter14_root_permutation_apply
    {F Ω : Type*} [Field F] [Field Ω] [Algebra F Ω]
    (f : F[X]) (σ : Gal(Ω / F))
    (x : Chapter14RootSet F Ω f) :
    (chapter14RootPermutation f σ x).1 = σ x.1 := by
  sorry

/- DEPENDENCY_GUESS: The earlier chapters do not yet package the reduction of
   global roots to a common residue splitting field.  This record keeps that
   missing bridge explicit by requiring the natural fiber equivalences; the
   cycle-count conclusion is then not itself an input field. -/
structure Chapter14FrobeniusOrbitData
    {F Ω k κ : Type*} [Field F] [Field Ω] [Field k] [Field κ]
    [Algebra F Ω] [Algebra k κ] [Finite κ]
    (f : F[X]) (g : ℕ) (factor : Fin g → k[X]) where
  frobenius : Gal(Ω / F)
  polynomial_separable : f.Separable
  factor_index : Chapter14RootSet F Ω f → Fin g
  orbit_iff_factor_index :
    ∀ x y, (∃ n : ℕ, (chapter14RootPermutation f (frobenius ^ n)) x = y) ↔
      factor_index x = factor_index y
  factor_monic : ∀ i, (factor i).Monic
  factor_irreducible : ∀ i, Irreducible (factor i)
  factor_splits : ∀ i,
    ((factor i).map (algebraMap k κ)).Splits
  factor_separable : ∀ i, (factor i).Separable
  fiber_equivalence : ∀ i, Nonempty
    ({x : Chapter14RootSet F Ω f // factor_index x = i} ≃
      {x : κ // aeval x (factor i) = 0})

def chapter14FactorDegreeMultiset
    {k : Type*} [Field k] (g : ℕ) (factor : Fin g → k[X]) : Multiset ℕ :=
  Multiset.ofList (List.ofFn (fun i => (factor i).natDegree))

noncomputable def chapter14RootCycleType
    {F Ω : Type*} [Field F] [Field Ω] [Algebra F Ω]
    (f : F[X]) (σ : Gal(Ω / F))
    [Finite (Chapter14RootSet F Ω f)] : Multiset ℕ := by
  letI := Fintype.ofFinite (Chapter14RootSet F Ω f)
  classical
  exact (chapter14RootPermutation f σ).cycleType

theorem chapter14_frobenius_cycle_type_eq_factor_degrees
    {F Ω k κ : Type*} [Field F] [Field Ω] [Field k] [Field κ]
    [Algebra F Ω] [Algebra k κ] [Finite κ]
    (f : F[X]) (g : ℕ) (factor : Fin g → k[X])
    [Finite (Chapter14RootSet F Ω f)]
    (H : Chapter14FrobeniusOrbitData (F := F) (Ω := Ω) (k := k) (κ := κ)
      f g factor) :
    chapter14RootCycleType f H.frobenius =
      chapter14FactorDegreeMultiset g factor := by
  sorry

end
end LastLib.Book02FiniteExtensionsOfLocalFields.Chapter14
