import LastLib.Book05LocalClassFieldTheory.Chapter12.Core

namespace LastLib.Book05LocalClassFieldTheory.Chapter12

noncomputable section

/-! ## 12.1. Fields and subgroups -/

/- DEPENDENCY_GUESS: The finite local reciprocity theorem from the missing
preceding Book 5 chapters supplies the quotient equivalence and its lattice
compatibilities for the bundled subextensions below. -/
/-- Finite reciprocity identifies the norm quotient with the Galois group. -/
theorem chapter12_subextension_artin_quotient_equiv
    {K : Type*} [Field K]
    (P : Chapter12LocalFieldProfile K)
    (E : Chapter12FiniteAbelianSubextension K) :
    Nonempty
      (Kˣ ⧸ E.normSubgroup ≃* Gal(E.field / K)) := by
  sorry

/-- The index of the norm subgroup is the extension degree. -/
theorem chapter12_subextension_norm_index_eq_degree
    {K : Type*} [Field K]
    (P : Chapter12LocalFieldProfile K)
    (E : Chapter12FiniteAbelianSubextension K) :
    Nat.card (Kˣ ⧸ E.normSubgroup) = E.degree := by
  sorry

/-- Every open finite-index subgroup is realized by a unique finite abelian
subextension of the fixed algebraic closure. -/
-- DEPENDENCY_GUESS: This is the existence theorem from the explicit
-- unramified/formal-module construction in Book 5, Chapter 6.
theorem chapter12_open_subgroup_correspondence
    {K : Type*} [Field K] [TopologicalSpace Kˣ] [IsTopologicalGroup Kˣ]
    (P : Chapter12LocalFieldProfile K)
    (H : Subgroup Kˣ) (hH : chapter12OpenFiniteIndex H) :
    ∃! E : Chapter12FiniteAbelianSubextension K,
      E.normSubgroup = H := by
  sorry

/-- Inclusion of finite abelian fields reverses inclusion of norm groups. -/
theorem chapter12_field_inclusion_iff_norm_inclusion
    {K : Type*} [Field K]
    (P : Chapter12LocalFieldProfile K)
    (E₁ E₂ : Chapter12FiniteAbelianSubextension K) :
    E₁.field ≤ E₂.field ↔ E₂.normSubgroup ≤ E₁.normSubgroup := by
  sorry

/-- The compositum/intersection rule for norm groups. -/
theorem chapter12_norm_group_of_compositum
    {K : Type*} [Field K]
    (P : Chapter12LocalFieldProfile K)
    (E₁ E₂ : Chapter12FiniteAbelianSubextension K) :
    ∃ E₁₂ : Chapter12FiniteAbelianSubextension K,
      E₁₂.field = E₁.field ⊔ E₂.field ∧
        E₁₂.normSubgroup = E₁.normSubgroup ⊓ E₂.normSubgroup := by
  sorry

/-- The intersection/product rule for norm groups. -/
theorem chapter12_norm_group_of_intersection
    {K : Type*} [Field K]
    (P : Chapter12LocalFieldProfile K)
    (E₁ E₂ : Chapter12FiniteAbelianSubextension K) :
    ∃ E₁₂ : Chapter12FiniteAbelianSubextension K,
      E₁₂.field = E₁.field ⊓ E₂.field ∧
        E₁₂.normSubgroup =
          chapter12NormSubgroupProduct E₁.normSubgroup E₂.normSubgroup := by
  sorry

/-- A finite abelian extension is cyclic exactly when its norm quotient is. -/
theorem chapter12_cyclic_extension_iff_cyclic_norm_quotient
    {K : Type*} [Field K]
    (P : Chapter12LocalFieldProfile K)
    (E : Chapter12FiniteAbelianSubextension K) :
    (∃ g : Gal(E.field / K),
      ∀ σ : Gal(E.field / K), ∃ n : ℤ, g ^ n = σ) ↔
      chapter12CyclicQuotient E.normSubgroup := by
  sorry

/-- The book-facing unramified norm profile is exactly
`π^(mℤ) · Oˣ`, represented by the subgroup generated by `π^m` and units. -/
def chapter12UnramifiedNormProfile
    {K k : Type*} [Field K] [Field k]
    (C : Chapter12LocalCoordinates K k) (H : Subgroup Kˣ) (m : ℕ) : Prop :=
  H = chapter12UnramifiedNormSubgroup C m ∧
    Finite (Kˣ ⧸ H) ∧ Nat.card (Kˣ ⧸ H) = m

theorem chapter12_unramified_norm_profile_iff
    {K k : Type*} [Field K] [Field k]
    (C : Chapter12LocalCoordinates K k) (H : Subgroup Kˣ) (m : ℕ) :
    chapter12UnramifiedNormProfile C H m ↔
      H = chapter12UnramifiedNormSubgroup C m ∧
        Finite (Kˣ ⧸ H) ∧ Nat.card (Kˣ ⧸ H) = m := by
  rfl

/-- A total norm subgroup has unrestricted valuation coordinate. -/
theorem chapter12_totally_ramified_norm_has_all_valuation_coordinates
    {K k : Type*} [Field K] [Field k]
    (C : Chapter12LocalCoordinates K k) (H : Subgroup Kˣ)
    (hH : chapter12TotallyRamifiedNormSubgroup C H) :
    ∀ z : ℤ, ∃ x : H, C.valuation x.1 = z := by
  intro z
  exact hH z

/-- In the total-ramified case the valuation-one norm is only determined up to
a unit; the chosen uniformizer itself is not part of the statement. -/
theorem chapter12_totally_ramified_norm_has_unit_times_uniformizer
    {K k : Type*} [Field K] [Field k]
    (C : Chapter12LocalCoordinates K k) (H : Subgroup Kˣ)
    (hH : chapter12TotallyRamifiedNormSubgroup C H) :
    chapter12ValuationOneNormForm C H := by sorry

end

end LastLib.Book05LocalClassFieldTheory.Chapter12
