import LastLib.Book05LocalClassFieldTheory.Chapter12.Core
import LastLib.Book05LocalClassFieldTheory.Chapter06.Section07TheExistenceTheorem

namespace LastLib.Book05LocalClassFieldTheory.Chapter12

noncomputable section

/-! ## 12.1. Fields and subgroups -/

/-- Finite reciprocity identifies the norm quotient with the Galois group. -/
theorem chapter12_subextension_artin_quotient_equiv
    {K : Type*} [Field K]
    (P : Chapter12LocalFieldProfile K)
    (E : Chapter12FiniteAbelianSubextension K) :
    Nonempty
      (Kˣ ⧸ E.normSubgroup ≃* Gal(E.field / K)) := by
  letI : FiniteDimensional K E.field := E.finite
  letI : IsGalois K E.field := E.galois
  letI : Fintype (Gal(E.field / K)) := E.galois_group_finite
  obtain ⟨A⟩ :=
    LastLib.Book05LocalClassFieldTheory.Chapter06.chapter06_finite_artin_map_exists_for_subextension E
  have hmap : chapter12MultiplicativeNormMap K E.field =
      LastLib.Book05LocalClassFieldTheory.Chapter05.chapter05NormMap K E.field := by
    rfl
  have hsub :
      LastLib.Book05LocalClassFieldTheory.Chapter06.chapter06NormSubgroup K E.field =
        chapter12NormSubgroup K E.field := by
    ext x
    rw [LastLib.Book05LocalClassFieldTheory.Chapter06.chapter06_mem_normSubgroup_iff,
      chapter12_mem_normSubgroup_iff, hmap]
  have hnorm : E.normSubgroup = chapter12NormSubgroup K E.field := by
    rw [LastLib.Book05LocalClassFieldTheory.Chapter06.chapter06FiniteAbelianSubextension_normSubgroup_coe E,
      hsub]
  let A' : LastLib.Book05LocalClassFieldTheory.Chapter10.Chapter10FiniteArtinMap
      K E.field := {
    reciprocity := A.reciprocity
    kernel_eq_norm := by
      rw [A.kernel_eq_norm, hsub]
    surjective := A.surjective }
  rw [hnorm]
  exact ⟨LastLib.Book05LocalClassFieldTheory.Chapter10.chapter10ArtinQuotientEquiv
    K E.field A'⟩

/-- The index of the norm subgroup is the extension degree. -/
theorem chapter12_subextension_norm_index_eq_degree
    {K : Type*} [Field K]
    (P : Chapter12LocalFieldProfile K)
    (E : Chapter12FiniteAbelianSubextension K) :
    Nat.card (Kˣ ⧸ E.normSubgroup) = E.degree := by
  sorry

 /-- Every open finite-index subgroup is realized by a unique finite abelian
subextension of the fixed algebraic closure. -/
theorem chapter12_open_subgroup_correspondence
    {K : Type*} [Field K] [TopologicalSpace Kˣ] [IsTopologicalGroup Kˣ]
    (P : Chapter12LocalFieldProfile K)
    (H : Subgroup Kˣ) (hH : chapter12OpenFiniteIndex H) :
    ∃! E : Chapter12FiniteAbelianSubextension K,
      E.normSubgroup = H := by
  sorry

/-- Inclusion of finite abelian fields reverses inclusion of norm groups. -/
theorem chapter12_field_inclusion_iff_norm_inclusion
    {K : Type*} [Field K]
    (P : Chapter12LocalFieldProfile K)
    (E₁ E₂ : Chapter12FiniteAbelianSubextension K) :
    E₁.field ≤ E₂.field ↔ E₂.normSubgroup ≤ E₁.normSubgroup := by
  sorry

/-- The compositum/intersection rule for norm groups. -/
theorem chapter12_norm_group_of_compositum
    {K : Type*} [Field K]
    (P : Chapter12LocalFieldProfile K)
    (E₁ E₂ : Chapter12FiniteAbelianSubextension K) :
    ∃ E₁₂ : Chapter12FiniteAbelianSubextension K,
      E₁₂.field = E₁.field ⊔ E₂.field ∧
        E₁₂.normSubgroup = E₁.normSubgroup ⊓ E₂.normSubgroup := by
  sorry

/-- The intersection/product rule for norm groups. -/
theorem chapter12_norm_group_of_intersection
    {K : Type*} [Field K]
    (P : Chapter12LocalFieldProfile K)
    (E₁ E₂ : Chapter12FiniteAbelianSubextension K) :
    ∃ E₁₂ : Chapter12FiniteAbelianSubextension K,
      E₁₂.field = E₁.field ⊓ E₂.field ∧
        E₁₂.normSubgroup =
          chapter12NormSubgroupProduct E₁.normSubgroup E₂.normSubgroup := by
  sorry

/-- A finite abelian extension is cyclic exactly when its norm quotient is. -/
theorem chapter12_cyclic_extension_iff_cyclic_norm_quotient
    {K : Type*} [Field K]
    (P : Chapter12LocalFieldProfile K)
    (E : Chapter12FiniteAbelianSubextension K) :
    (∃ g : Gal(E.field / K),
      ∀ σ : Gal(E.field / K), ∃ n : ℤ, g ^ n = σ) ↔
      chapter12CyclicQuotient E.normSubgroup := by
  sorry

/-- The book-facing unramified norm profile is exactly
`π^(mℤ) · Oˣ`, represented by the subgroup generated by `π^m` and units. -/
def chapter12UnramifiedNormProfile
    {K k : Type*} [Field K] [Field k]
    (C : Chapter12LocalCoordinates K k) (H : Subgroup Kˣ) (m : ℕ) : Prop :=
  H = chapter12UnramifiedNormSubgroup C m ∧
    Finite (Kˣ ⧸ H) ∧ Nat.card (Kˣ ⧸ H) = m

theorem chapter12_unramified_norm_profile_iff
    {K k : Type*} [Field K] [Field k]
    (C : Chapter12LocalCoordinates K k) (H : Subgroup Kˣ) (m : ℕ)
    (_hm : 0 < m) :
    chapter12UnramifiedNormProfile C H m ↔
      H = chapter12UnramifiedNormSubgroup C m ∧
        Finite (Kˣ ⧸ H) ∧ Nat.card (Kˣ ⧸ H) = m := by
  rfl

/-- A total norm subgroup has unrestricted valuation coordinate. -/
theorem chapter12_totally_ramified_norm_has_all_valuation_coordinates
    {K k : Type*} [Field K] [Field k]
    (C : Chapter12LocalCoordinates K k) (H : Subgroup Kˣ)
    (hH : chapter12TotallyRamifiedNormSubgroup C H) :
    ∀ z : ℤ, ∃ x : H, C.valuation x.1 = z := by
  intro z
  exact hH z

/-- In the total-ramified case the valuation-one norm is only determined up to
a unit; the chosen uniformizer itself is not part of the statement. -/
theorem chapter12_totally_ramified_norm_has_unit_times_uniformizer
    {K k : Type*} [Field K] [Field k]
    (C : Chapter12LocalCoordinates K k) (H : Subgroup Kˣ)
    (hH : chapter12TotallyRamifiedNormSubgroup C H) :
    chapter12ValuationOneNormForm C H := by sorry

end

end LastLib.Book05LocalClassFieldTheory.Chapter12
