import LastLib.Book06GlobalClassFieldTheory.Chapter10.Dependencies

namespace LastLib.Book06GlobalClassFieldTheory.Chapter10

noncomputable section

open CategoryTheory
open CategoryTheory.Limits

universe u v w

/-!
## 10.1. Passing over all finite abelian extensions
-/

/-- The topology generated by the open finite-index subgroups used in the
profinite completion of `C_K`. -/
@[instance_reducible]
def chapter10FiniteIndexTopology
    (C : Type u) [CommGroup C] [TopologicalSpace C] : TopologicalSpace C :=
  TopologicalSpace.generateFrom
    {U : Set C | ∃ H : Chapter10OpenFiniteIndexNormalSubgroup C, ∃ c : C,
      U = {x | c⁻¹ * x ∈ H.toSubgroup}}

theorem chapter10FiniteIndexTopology_generatedByOpenFiniteIndex
    (C : Type u) [CommGroup C] [TopologicalSpace C] :
    chapter10FiniteIndexTopology C =
      TopologicalSpace.generateFrom
        {U : Set C | ∃ H : Chapter10OpenFiniteIndexNormalSubgroup C, ∃ c : C,
          U = {x | c⁻¹ * x ∈ H.toSubgroup}} :=
  rfl

/-- The target is given its natural profinite topology through the infinite
Galois inverse limit. -/
noncomputable def chapter10ProfiniteAbelianGaloisTarget
    (K : Type u) (Kab : Type v) [Field K] [Field Kab] [Algebra K Kab]
    [IsGalois K Kab] (_A : Chapter10AbelianClosureData K Kab) : ProfiniteGrp :=
  InfiniteGalois.profiniteGalGrp K Kab

theorem chapter10ProfiniteAbelianGaloisTarget_coe
    (K : Type u) (Kab : Type v) [Field K] [Field Kab] [Algebra K Kab]
    [IsGalois K Kab] (A : Chapter10AbelianClosureData K Kab) :
    (chapter10ProfiniteAbelianGaloisTarget K Kab A : Type v) = Gal(Kab / K) :=
  rfl

noncomputable def chapter10_finite_reciprocity_identifies_quotient
    {C : Type u} {K : Type v} {Kab : Type w}
    [CommGroup C] [TopologicalSpace C]
    [IsTopologicalGroup C] [Field K] [Field Kab] [Algebra K Kab]
    [IsGalois K Kab] (F : Chapter10FiniteArtinFamily C K Kab)
    (L : FiniteGaloisIntermediateField K Kab) :
    C ⧸ (F.map L).ker ≃* Gal(L / K) :=
  Chapter10FiniteArtinFamily.quotientEquiv F L

theorem chapter10_finite_reciprocity_identifies_open_system
    {C : Type u} {K : Type v} {Kab : Type w}
    [CommGroup C] [TopologicalSpace C]
    [IsTopologicalGroup C] [Field K] [Field Kab] [Algebra K Kab]
    [IsGalois K Kab] (F : Chapter10FiniteArtinFamily C K Kab)
    (R : Chapter10FiniteReciprocityData F) :
    ∀ H : Chapter10OpenFiniteIndexNormalSubgroup C,
      ∃ L : FiniteGaloisIntermediateField K Kab,
        H.toSubgroup = (F.map L).ker :=
  R.kernel_cofinal

/-- The source-order formulation of compatibility with every finite abelian
Artin map. -/
theorem chapter10_global_artin_restricts_to_finite_artin
    {C : Type u} {K : Type v} {Kab : Type w}
    [CommGroup C] [TopologicalSpace C]
    [IsTopologicalGroup C] [Field K] [Field Kab] [Algebra K Kab]
    [IsGalois K Kab] (F : Chapter10FiniteArtinFamily C K Kab)
    (L : FiniteGaloisIntermediateField K Kab) :
    (chapter10RestrictionMap L).comp (chapter10GlobalArtinMap F) = F.map L :=
  chapter10GlobalArtinMap_restrict F L

/-- Global Artin reciprocity, in the topology-sensitive inverse-limit form of
Theorem 10.1. -/
noncomputable def chapter10InfiniteReciprocityEquiv
    {C : Type u} {K : Type v} {Kab : Type w}
    [CommGroup C] [TopologicalSpace C]
    [IsTopologicalGroup C] [Field K] [Field Kab] [Algebra K Kab]
    [IsGalois K Kab] (F : Chapter10FiniteArtinFamily C K Kab)
    (R : Chapter10FiniteReciprocityData F) :
    chapter10ProfiniteCompletion C ≃ₜ* Gal(Kab / K) := by
  sorry

theorem chapter10InfiniteReciprocityEquiv_apply_eta
    {C : Type u} {K : Type v} {Kab : Type w}
    [CommGroup C] [TopologicalSpace C]
    [IsTopologicalGroup C] [Field K] [Field Kab] [Algebra K Kab]
    [IsGalois K Kab] (F : Chapter10FiniteArtinFamily C K Kab)
    (R : Chapter10FiniteReciprocityData F) (c : C) :
    chapter10InfiniteReciprocityEquiv F R (chapter10ProfiniteCompletionEta C c) =
      chapter10GlobalArtinMap F c := by
  sorry

noncomputable def chapter10CompletedFiniteArtinMap
    {C : Type u} {K : Type v} {Kab : Type w}
    [CommGroup C] [TopologicalSpace C]
    [IsTopologicalGroup C] [Field K] [Field Kab] [Algebra K Kab]
    [IsGalois K Kab] (F : Chapter10FiniteArtinFamily C K Kab)
    (R : Chapter10FiniteReciprocityData F)
    (L : FiniteGaloisIntermediateField K Kab) :
    chapter10ProfiniteCompletion C →* Gal(L / K) :=
  (chapter10RestrictionMap L).comp
    (chapter10InfiniteReciprocityEquiv F R).toMulEquiv.toMonoidHom

theorem chapter10CompletedFiniteArtinMap_apply_eta
    {C : Type u} {K : Type v} {Kab : Type w}
    [CommGroup C] [TopologicalSpace C]
    [IsTopologicalGroup C] [Field K] [Field Kab] [Algebra K Kab]
    [IsGalois K Kab] (F : Chapter10FiniteArtinFamily C K Kab)
    (R : Chapter10FiniteReciprocityData F) (L : FiniteGaloisIntermediateField K Kab)
    (c : C) :
    chapter10CompletedFiniteArtinMap F R L (chapter10ProfiniteCompletionEta C c) =
      F.map L c := by
  sorry

end

end LastLib.Book06GlobalClassFieldTheory.Chapter10
