import LastLib.Book05LocalClassFieldTheory.Chapter01.Dependencies

namespace LastLib.Book05LocalClassFieldTheory.Chapter01

noncomputable section

universe u

open Set
open scoped BigOperators Pointwise Topology WithZero

/-! ## 1.1. What kind of local field is meant -/

/-- A complete discrete valuation has a normalized uniformizer. -/
theorem chapter01_local_field_has_uniformizer
    {K : Type*} [Field K]
    (v : AddValuation K (WithTop ℤ))
    (hlocal : Chapter01LocalField v) :
    ∃ π : Chapter01ValuationRing v, chapter01IsUniformizer v π := by
  sorry

/-- A complete discretely valued field with infinite residue field is outside
the local-field scope fixed in this chapter. -/
theorem chapter01_infinite_residue_field_outside_scope
    {K : Type*} [Field K]
    (v : AddValuation K (WithTop ℤ))
    (hinfinite : ¬Finite (Chapter01ResidueField v)) :
    ¬Chapter01LocalField v := by
  intro hlocal
  exact hinfinite hlocal.2

/-- Reduction onto the residue field is surjective. -/
theorem chapter01_residue_map_surjective
    {K : Type*} [Field K] (v : AddValuation K (WithTop ℤ)) :
    Function.Surjective (chapter01ResidueMap v) := by
  exact IsLocalRing.residue_surjective

/-- The maximal ideal is generated by a normalized uniformizer. -/
theorem chapter01_maximal_ideal_eq_span_uniformizer
    {K : Type*} [Field K]
    (v : AddValuation K (WithTop ℤ))
    (π : Chapter01ValuationRing v)
    (hπ : chapter01IsUniformizer v π)
    (hdiscrete :
      LastLib.Book01ValuationsDVRsAndCompletions.Chapter10.Chapter10DiscreteAddValuation v) :
    Chapter01MaximalIdeal v = Ideal.span ({π} : Set (Chapter01ValuationRing v)) := by
  sorry

/-- The zeroth unit group is the full valuation-ring unit group. -/
theorem chapter01_unit_filtration_zero
    {K : Type*} [Field K] (v : AddValuation K (WithTop ℤ)) :
    Chapter01UnitFiltration v 0 = ⊤ := by
  exact LastLib.Book02FiniteExtensionsOfLocalFields.Chapter10.chapter10_unit_filtration_zero
    (Chapter01ValuationRing v)

/-- Membership in `Uⁿ` is exactly the congruence `u - 1 ∈ 𝔪ⁿ`. -/
theorem chapter01_unit_filtration_mem_iff
    {K : Type*} [Field K] (v : AddValuation K (WithTop ℤ))
    (n : ℕ) (u : Chapter01UnitGroup v) :
    u ∈ Chapter01UnitFiltration v n ↔
      (u : Chapter01ValuationRing v) - 1 ∈ (Chapter01MaximalIdeal v) ^ n :=
  Iff.rfl

/-- The unit filtration is descending. -/
theorem chapter01_unit_filtration_descending
    {K : Type*} [Field K] (v : AddValuation K (WithTop ℤ)) :
    ∀ n : ℕ, Chapter01UnitFiltration v (n + 1) ≤
      Chapter01UnitFiltration v n := by
  intro n
  exact LastLib.Book02FiniteExtensionsOfLocalFields.Chapter10.chapter10_unit_filtration_descending
    (Chapter01ValuationRing v) n

/- LOCAL_DEPENDENCY_GUESS: the normalized additive valuation coordinate is the
earlier DVR decomposition map; the exact sequence itself is kept explicit in
`Chapter01ValuationCoordinateData`. -/
theorem chapter01_valuation_coordinate_exists
    {K : Type*} [Field K]
    (v : AddValuation K (WithTop ℤ))
    (hlocal : Chapter01LocalField v) :
    Nonempty (Chapter01ValuationCoordinateData v) := by
  sorry

/-- A finite residue field is perfect, so finite residue extensions are
separable. -/
theorem chapter01_finite_residue_field_is_perfect
    {K : Type*} [Field K]
    (v : AddValuation K (WithTop ℤ))
    [Finite (Chapter01ResidueField v)] :
    PerfectField (Chapter01ResidueField v) := by
  exact LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.chapter09_finite_field_is_perfect
    (Chapter01ResidueField v)

/-- Finite extensions of finite fields are separable. -/
theorem chapter01_finite_residue_extension_is_separable
    {k l : Type*} [Field k] [Field l] [Algebra k l]
    [Finite k] [Finite l] [FiniteDimensional k l] :
    Algebra.IsSeparable k l := by
  sorry

/-- Purely inseparable finite extensions are not silently admitted as class
field-theoretic levels. -/
theorem chapter01_purely_inseparable_warning
    {K L : Type*} [Field K] [Field L] [Algebra K L]
    (h : Chapter01PurelyInseparableExtension K L)
    (hnontrivial : 1 < Module.finrank K L) :
    ¬ Chapter01FiniteSeparableExtension K L := by
  sorry

/-- The finite residue-field hypothesis gives the local-field compactness of
the valuation ring.  The topological instances are the canonical valuation
topology interfaces from the earlier books. -/
theorem chapter01_local_field_integer_ring_compact
    {K : Type*} [Field K] [Valued K ℤᵐ⁰]
    (v : AddValuation K (WithTop ℤ))
    (hlocal : Chapter01LocalField v)
    (hvaluation : Valuation.IsEquiv (Valued.v : Valuation K ℤᵐ⁰) v.toValuation)
    [(Valued.v : Valuation K ℤᵐ⁰).RankOne]
    [CompleteSpace ((Valued.v : Valuation K ℤᵐ⁰).valuationSubring)]
    [IsDiscreteValuationRing ((Valued.v : Valuation K ℤᵐ⁰).valuationSubring)] :
    IsCompact
      (Set.univ : Set ((Valued.v : Valuation K ℤᵐ⁰).valuationSubring)) := by
  sorry

/- LOCAL_DEPENDENCY_GUESS: the earlier valuation-topology theorem identifies
the additive valuation used here with the `Valued` topology on `K`; once that
bridge is reconciled, finite residue compactness gives local compactness. -/
theorem chapter01_local_field_is_locally_compact
    {K : Type*} [Field K] [Valued K ℤᵐ⁰]
    (v : AddValuation K (WithTop ℤ))
    (hlocal : Chapter01LocalField v)
    (hvaluation : Valuation.IsEquiv (Valued.v : Valuation K ℤᵐ⁰) v.toValuation)
    [(Valued.v : Valuation K ℤᵐ⁰).RankOne]
    [CompleteSpace ((Valued.v : Valuation K ℤᵐ⁰).valuationSubring)]
    [IsDiscreteValuationRing ((Valued.v : Valuation K ℤᵐ⁰).valuationSubring)] :
    LocallyCompactSpace K := by
  sorry

/- LOCAL_DEPENDENCY_GUESS: the valuation-coordinate quotient is the standard
noncompact `ℤ` coordinate of the local-field multiplicative group. -/
theorem chapter01_local_field_units_noncompact
    {K : Type*} [Field K]
    (v : AddValuation K (WithTop ℤ))
    (hlocal : Chapter01LocalField v)
    (D : Chapter01ValuationCoordinateData v)
    [TopologicalSpace Kˣ] [IsTopologicalGroup Kˣ]
    [TopologicalSpace (Chapter01UnitGroup v)]
    [IsTopologicalGroup (Chapter01UnitGroup v)]
    (hcoordinate :
      Nonempty (Kˣ ≃ₜ* Multiplicative ℤ × Chapter01UnitGroup v)) :
    NoncompactSpace Kˣ := by
  sorry

/-- The unique-extension theorem used to fix the separable closure branch. -/
theorem chapter01_finite_extension_has_unique_valuation
    {K L Γ : Type u} [Field K] [Field L] [Algebra K L]
    [Algebra.IsAlgebraic K L]
    [LinearOrderedCommGroupWithZero Γ]
    (v : Valuation K Γ) [Valuation.IsRankOneDiscrete v]
    (hcomplete : IsAdicComplete
      (IsLocalRing.maximalIdeal v.valuationSubring) v.valuationSubring) :
    LastLib.Book01ValuationsDVRsAndCompletions.Chapter12.hasUniqueValuationExtension v L := by
  sorry

/-- A finite extension of a complete discretely valued field remains complete
and discretely valued on its normalized branch. -/
theorem chapter01_finite_extension_remains_local
    {K L : Type*} [Field K] [Field L] [Algebra K L]
    [FiniteDimensional K L]
    (vK : Valuation K ℤᵐ⁰) (vL : Valuation L ℤᵐ⁰)
    [vK.HasExtension vL] [Valuation.IsRankOneDiscrete vK]
    [Valuation.IsRankOneDiscrete vL]
    (hcomplete : IsAdicComplete
      (IsLocalRing.maximalIdeal vK.valuationSubring) vK.valuationSubring) :
    Module.Finite vK.valuationSubring vL.valuationSubring ∧
      Module.Free vK.valuationSubring vL.valuationSubring ∧
      IsAdicComplete (IsLocalRing.maximalIdeal vL.valuationSubring)
        vL.valuationSubring ∧
      IsDiscreteValuationRing vL.valuationSubring := by
  exact
    LastLib.Book02FiniteExtensionsOfLocalFields.Chapter01.chapter01_finite_extension_remains_local
      vK vL hcomplete

/-- The clean unramified-then-totally-ramified decomposition in a finite
local extension with separable residue extension. -/
theorem chapter01_finite_separable_extension_decomposes
    (A B K L : Type*) [CommRing A] [CommRing B] [Field K] [Field L]
    [Algebra A B] [Algebra A K] [Algebra K L] [Algebra B L] [Algebra A L]
    [IsScalarTower A K L] [IsScalarTower A B L]
    [IsDomain A] [IsDomain B]
    [IsDiscreteValuationRing A] [IsDiscreteValuationRing B]
    [IsLocalHom (algebraMap A B)] [IsFractionRing A K] [IsFractionRing B L]
    [FiniteDimensional K L] [Module.Finite A B] [Module.IsTorsionFree A B]
    [FaithfulSMul A B] [IsIntegralClosure B A L]
    [Module.Finite (LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.chapter09BaseResidueField A)
      (LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.chapter09ExtensionResidueField B)]
    [PerfectField
      (LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.chapter09BaseResidueField A)]
    [LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.Chapter09FiniteLocalExtension
      A B K L]
    (_hfield_separable : Chapter01FiniteSeparableExtension K L)
    (hseparable : Algebra.IsSeparable
      (LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.chapter09BaseResidueField A)
      (LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.chapter09ExtensionResidueField B)) :
    Nonempty
      (LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.Chapter09Corollary92Data
        A B K L) := by
  simpa [LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.chapter09CleanTwoStageDecomposition]
    using
      (LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.chapter09_clean_two_stage_decomposition_iff_residue_separable
        A B K L).mpr hseparable

/-- The unramified stage in the preceding decomposition is explicit. -/
theorem chapter01_decomposition_unramified_stage
    {A B K L : Type*} [CommRing A] [CommRing B] [Field K] [Field L]
    [Algebra A B] [Algebra A K] [Algebra K L] [Algebra B L] [Algebra A L]
    [IsScalarTower A K L] [IsScalarTower A B L]
    [IsDomain A] [IsDomain B]
    [IsDiscreteValuationRing A] [IsDiscreteValuationRing B]
    [IsLocalHom (algebraMap A B)] [IsFractionRing A K] [IsFractionRing B L]
    [FiniteDimensional K L] [Module.Finite A B] [Module.IsTorsionFree A B]
    [FaithfulSMul A B] [IsIntegralClosure B A L]
    [Module.Finite (LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.chapter09BaseResidueField A)
      (LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.chapter09ExtensionResidueField B)]
    [LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.Chapter09FiniteLocalExtension
      A B K L]
    (d : LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.Chapter09Corollary92Data
      A B K L) :
    LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.chapter09UnramifiedIntermediate
      A B K L d.K₀ := by
  exact d.unramified

/-- The remainder in the preceding decomposition is totally ramified. -/
theorem chapter01_decomposition_remainder_totally_ramified
    {A B K L : Type*} [CommRing A] [CommRing B] [Field K] [Field L]
    [Algebra A B] [Algebra A K] [Algebra K L] [Algebra B L] [Algebra A L]
    [IsScalarTower A K L] [IsScalarTower A B L]
    [IsDomain A] [IsDomain B]
    [IsDiscreteValuationRing A] [IsDiscreteValuationRing B]
    [IsLocalHom (algebraMap A B)] [IsFractionRing A K] [IsFractionRing B L]
    [FiniteDimensional K L] [Module.Finite A B] [Module.IsTorsionFree A B]
    [FaithfulSMul A B] [IsIntegralClosure B A L]
    [Module.Finite (LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.chapter09BaseResidueField A)
      (LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.chapter09ExtensionResidueField B)]
    [LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.Chapter09FiniteLocalExtension
      A B K L]
    (d : LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.Chapter09Corollary92Data
      A B K L) :
    d.remainder.residue_degree = 1 := by
  exact d.remainder_totally_ramified

/-- The fundamental equality in the valuation notation used by this book. -/
theorem chapter01_fundamental_equality
    {K L : Type*} [Field K] [Field L] [Algebra K L]
    (vK : Valuation K ℤᵐ⁰) (vL : Valuation L ℤᵐ⁰)
    [vK.HasExtension vL] [Valuation.IsRankOneDiscrete vK]
    [Valuation.IsRankOneDiscrete vL] [FiniteDimensional K L]
    (hcomplete : IsAdicComplete
      (IsLocalRing.maximalIdeal vK.valuationSubring) vK.valuationSubring) :
    Module.finrank K L =
      LastLib.Book01ValuationsDVRsAndCompletions.Chapter12.chapterRamificationIndex
          vK.valuationSubring vL.valuationSubring
          (IsLocalRing.maximalIdeal vL.valuationSubring) *
        LastLib.Book01ValuationsDVRsAndCompletions.Chapter12.chapterResidueDegree
          vK.valuationSubring vL.valuationSubring
          (IsLocalRing.maximalIdeal vL.valuationSubring) := by
  exact LastLib.Book02FiniteExtensionsOfLocalFields.Chapter02.fundamental_equality
    vK vL hcomplete

/-- The norm valuation identity used throughout local reciprocity. -/
theorem chapter01_norm_valuation_formula
    (K L : Type*) [Field K] [Field L] [Algebra K L]
    [FiniteDimensional K L] {vK : AddValuation K (WithTop ℤ)}
    {vL : AddValuation L (WithTop ℤ)} (e f : ℕ)
    [Valuation.IsRankOneDiscrete vK.toValuation]
    [Valuation.IsRankOneDiscrete vL.toValuation]
    (hext : vK.IsEquiv (AddValuation.comap (algebraMap K L) vL))
    (hrestrict : ∀ y : K,
      vL (algebraMap K L y) = (e : WithTop ℤ) * vK y)
    (hf : f =
      LastLib.Book01ValuationsDVRsAndCompletions.Chapter11.chapter11AdditiveResidueDegree
        vK vL hext)
    (hunique : ∀ w : AddValuation L (WithTop ℤ),
      vK.IsEquiv (AddValuation.comap (algebraMap K L) w) → vL.IsEquiv w)
    (hdegree : Module.finrank K L = e * f) (x : L) (hx : x ≠ 0) :
    vK (Algebra.norm K x) = (f : WithTop ℤ) * vL x := by
  exact LastLib.Book02FiniteExtensionsOfLocalFields.Chapter04.chapter04_norm_valuation_formula
    K L e f hext hrestrict hf hunique hdegree x hx

/-- The unramified-extension classification is imported in its functorial
book-facing form. -/
abbrev Chapter01UnramifiedClassificationInterface :=
  LastLib.Book02FiniteExtensionsOfLocalFields.Chapter07.Chapter07UnramifiedClassificationInterface

theorem chapter01_unramified_extensions_classified_by_residue_extensions
    {U S : Type*} (C : Chapter01UnramifiedClassificationInterface U S) :
    Nonempty (U ≃ S) ∧
      (∀ u, C.degreeU u = C.degreeS (C.reduction u)) ∧
      (∀ u v, C.inclusionU u v ↔
        C.inclusionS (C.reduction u) (C.reduction v)) ∧
      (∀ u v, C.reduction (C.compositumU u v) =
        C.compositumS (C.reduction u) (C.reduction v)) ∧
      (∀ u v, C.reduction (C.intersectionU u v) =
        C.intersectionS (C.reduction u) (C.reduction v)) ∧
      (∀ u, LastLib.Book02FiniteExtensionsOfLocalFields.Chapter07.Chapter07GaloisGroupPreservation
        (C.galoisU u) (C.galoisS (C.reduction u))) := by
  exact LastLib.Book02FiniteExtensionsOfLocalFields.Chapter07.chapter07_unramified_extensions_classified_by_residue_extensions C

end

end LastLib.Book05LocalClassFieldTheory.Chapter01
