import LastLib.Book05LocalClassFieldTheory.Chapter01.Dependencies
import LastLib.Book01ValuationsDVRsAndCompletions.Chapter06.Section06CompactnessAndLocalCompactness
import LastLib.Book02FiniteExtensionsOfLocalFields.Chapter08.Section03UniformizersAndMinimalPolynomials
import Mathlib.Topology.Algebra.Valued.LocallyCompact

namespace LastLib.Book05LocalClassFieldTheory.Chapter01

noncomputable section

universe u

open Set
open scoped BigOperators Pointwise Topology WithZero

/-! ## 1.1. What kind of local field is meant -/

/-- A complete discrete valuation has a normalized uniformizer. -/
theorem chapter01_local_field_has_uniformizer
    {K : Type*} [Field K]
    (v : AddValuation K (WithTop ℤ))
    (hlocal : Chapter01LocalField v) :
    ∃ π : Chapter01ValuationRing v, chapter01IsUniformizer v π := by
  rcases hlocal.1.1 with ⟨π, hπ0, hπ, _⟩
  have hπmem : π ∈ v.toValuation.valuationSubring := by
    rw [Valuation.mem_valuationSubring_iff]
    change (0 : WithTop ℤ) ≤ v π
    rw [hπ]
    norm_num
  let π' : Chapter01ValuationRing v := ⟨π, hπmem⟩
  refine ⟨π', ?_⟩
  constructor
  · intro hzero
    apply hπ0
    exact congrArg (fun x : Chapter01ValuationRing v => (x : K)) hzero
  · exact hπ

/-- A complete discretely valued field with infinite residue field is outside
the local-field scope fixed in this chapter. -/
theorem chapter01_infinite_residue_field_outside_scope
    {K : Type*} [Field K]
    (v : AddValuation K (WithTop ℤ))
    (hinfinite : ¬Finite (Chapter01ResidueField v)) :
    ¬Chapter01LocalField v := by
  intro hlocal
  exact hinfinite hlocal.2

/-- Reduction onto the residue field is surjective. -/
theorem chapter01_residue_map_surjective
    {K : Type*} [Field K] (v : AddValuation K (WithTop ℤ)) :
    Function.Surjective (chapter01ResidueMap v) := by
  exact IsLocalRing.residue_surjective

/-- The maximal ideal is generated by a normalized uniformizer. -/
theorem chapter01_maximal_ideal_eq_span_uniformizer
    {K : Type*} [Field K]
    (v : AddValuation K (WithTop ℤ))
    (π : Chapter01ValuationRing v)
    (hπ : chapter01IsUniformizer v π)
    (hdiscrete :
      LastLib.Book01ValuationsDVRsAndCompletions.Chapter10.Chapter10DiscreteAddValuation v) :
    Chapter01MaximalIdeal v = Ideal.span ({π} : Set (Chapter01ValuationRing v)) := by
  let _ : Valuation.IsRankOneDiscrete v.toValuation :=
    LastLib.Book02FiniteExtensionsOfLocalFields.Chapter08.chapter08_rank_one_discrete_of_add_valuation
      v hdiscrete
  have hintegral : ∀ x : K, IsIntegral (Chapter01ValuationRing v) x ↔ 0 ≤ v x := by
    intro x
    constructor
    · intro hx
      obtain ⟨a, ha⟩ :=
        (IsIntegrallyClosed.isIntegral_iff (R := Chapter01ValuationRing v)).mp hx
      have ha0 : 0 ≤ v (a : K) := a.property
      have ha' : (a : K) = x := ha
      rw [ha'] at ha0
      exact ha0
    · intro hx
      apply (IsIntegrallyClosed.isIntegral_iff (R := Chapter01ValuationRing v)).mpr
      exact ⟨⟨x, hx⟩, rfl⟩
  rcases hπ with ⟨_, hπval⟩
  simpa [ValuationSubring.algebraMap_apply] using
    (LastLib.Book02FiniteExtensionsOfLocalFields.Chapter08.chapter08_value_one_generates_maximal_ideal
      v hdiscrete hintegral π hπval)

/-- The zeroth unit group is the full valuation-ring unit group. -/
theorem chapter01_unit_filtration_zero
    {K : Type*} [Field K] (v : AddValuation K (WithTop ℤ)) :
    Chapter01UnitFiltration v 0 = ⊤ := by
  exact LastLib.Book02FiniteExtensionsOfLocalFields.Chapter10.chapter10_unit_filtration_zero
    (Chapter01ValuationRing v)

/-- Membership in `Uⁿ` is exactly the congruence `u - 1 ∈ 𝔪ⁿ`. -/
theorem chapter01_unit_filtration_mem_iff
    {K : Type*} [Field K] (v : AddValuation K (WithTop ℤ))
    (n : ℕ) (u : Chapter01UnitGroup v) :
    u ∈ Chapter01UnitFiltration v n ↔
      (u : Chapter01ValuationRing v) - 1 ∈ (Chapter01MaximalIdeal v) ^ n :=
  Iff.rfl

/-- The unit filtration is descending. -/
theorem chapter01_unit_filtration_descending
    {K : Type*} [Field K] (v : AddValuation K (WithTop ℤ)) :
    ∀ n : ℕ, Chapter01UnitFiltration v (n + 1) ≤
      Chapter01UnitFiltration v n := by
  intro n
  exact LastLib.Book02FiniteExtensionsOfLocalFields.Chapter10.chapter10_unit_filtration_descending
    (Chapter01ValuationRing v) n

/-- The normalized additive valuation coordinate is recorded by the exact
sequence interface from the dependencies file. -/
theorem chapter01_valuation_coordinate_exists
    {K : Type*} [Field K]
    (v : AddValuation K (WithTop ℤ))
    (hlocal : Chapter01LocalField v) :
    Nonempty (Chapter01ValuationCoordinateData v) := by
  classical
  obtain ⟨π, hπ0, hπ, hvalues⟩ := hlocal.1.1
  have unit_val (u : Kˣ) : ∃ z : ℤ, v (u : K) = (z : WithTop ℤ) :=
    hvalues (u : K) (Units.ne_zero u)
  let valInt : Kˣ → ℤ := fun u => Classical.choose (unit_val u)
  have valInt_spec (u : Kˣ) : v (u : K) = (valInt u : WithTop ℤ) :=
    Classical.choose_spec (unit_val u)
  have hpow (z : ℤ) : v (π ^ z) = (z : WithTop ℤ) := by
    cases z with
    | ofNat n =>
        change v (π ^ (n : ℤ)) = (n : WithTop ℤ)
        rw [zpow_natCast]
        rw [v.map_pow, hπ]
        simp
    | negSucc n =>
        rw [zpow_negSucc, v.map_inv, v.map_pow, hπ]
        simp [Int.negSucc_eq]
  let ν : Kˣ →* Multiplicative ℤ :=
    { toFun := fun u => Multiplicative.ofAdd (valInt u)
      map_one' := by
        change valInt (1 : Kˣ) = 0
        apply WithTop.coe_injective
        rw [← valInt_spec]
        change v (1 : K) = 0
        rw [v.map_one]
      map_mul' := by
        intro u w
        change valInt (u * w) = valInt u + valInt w
        apply WithTop.coe_injective
        have huv : ((u * w : Kˣ) : K) = (u : K) * (w : K) := rfl
        calc
          (valInt (u * w) : WithTop ℤ) = v ((u * w : Kˣ) : K) :=
            (valInt_spec (u * w)).symm
          _ = v (u : K) + v (w : K) := by rw [huv, v.map_mul]
          _ = (valInt u : WithTop ℤ) + (valInt w : WithTop ℤ) := by
            rw [valInt_spec, valInt_spec] }
  let hvint : v.toValuation.Integers (Chapter01ValuationRing v) :=
    Valuation.valuationSubring.integers v.toValuation
  refine ⟨⟨ν, ?_⟩⟩
  change Function.Injective (chapter01UnitInclusion v) ∧
    Function.MulExact (chapter01UnitInclusion v) ν ∧ Function.Surjective ν
  refine ⟨?_, ?_, ?_⟩
  · intro a b hab
    apply Units.ext
    apply Subtype.ext
    exact congrArg (fun z : Kˣ => (z : K)) hab
  · intro u
    constructor
    · intro hu
      have huvint : valInt u = 0 := by
        change Multiplicative.ofAdd (valInt u) = Multiplicative.ofAdd 0 at hu
        exact Multiplicative.ofAdd.injective hu
      have huval : v (u : K) = 0 := by
        rw [valInt_spec, huvint]
        simp
      let a0 : Chapter01ValuationRing v :=
        ⟨(u : K), by
          change 0 ≤ v (u : K)
          rw [huval]
          ⟩
      have haunit : IsUnit a0 := by
        apply hvint.isUnit_iff_valuation_eq_one.mpr
        change v (u : K) = 0
        exact huval
      obtain ⟨a, ha⟩ := haunit
      refine ⟨a, ?_⟩
      apply Units.ext
      change ((a : Chapter01ValuationRing v) : K) = (u : K)
      simpa [a0] using congrArg (fun z : Chapter01ValuationRing v => (z : K)) ha
    · rintro ⟨a, rfl⟩
      have hav : v ((chapter01UnitInclusion v a : Kˣ) : K) = 0 := by
        change v ((a : Chapter01ValuationRing v) : K) = 0
        exact hvint.valuation_unit a
      have havint : valInt (chapter01UnitInclusion v a) = 0 := by
        apply WithTop.coe_injective
        rw [← valInt_spec, hav]
        simp
      simp [ν, havint]
  · intro z
    let u : Kˣ :=
      Units.mk0 (π ^ (Multiplicative.toAdd z))
        (zpow_ne_zero _ hπ0)
    refine ⟨u, ?_⟩
    have huvint : valInt u = Multiplicative.toAdd z := by
      apply WithTop.coe_injective
      rw [← valInt_spec]
      change v (π ^ (Multiplicative.toAdd z)) = _
      exact hpow (Multiplicative.toAdd z)
    change Multiplicative.ofAdd (valInt u) = z
    rw [huvint]
    simp

/-- A finite residue field is perfect, so finite residue extensions are
separable. -/
theorem chapter01_finite_residue_field_is_perfect
    {K : Type*} [Field K]
    (v : AddValuation K (WithTop ℤ))
    [Finite (Chapter01ResidueField v)] :
    PerfectField (Chapter01ResidueField v) := by
  exact LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.chapter09_finite_field_is_perfect
    (Chapter01ResidueField v)

/-- Finite extensions of finite fields are separable. -/
theorem chapter01_finite_residue_extension_is_separable
    {k l : Type*} [Field k] [Field l] [Algebra k l]
    [Finite k] [Finite l] [FiniteDimensional k l] :
    Algebra.IsSeparable k l := by
  let _ : PerfectField k := PerfectField.ofFinite
  exact LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.chapter09_perfect_residue_field_gives_separable_extension
    k l

/-- Purely inseparable finite extensions are not silently admitted as class
field-theoretic levels. -/
theorem chapter01_purely_inseparable_warning
    {K L : Type*} [Field K] [Field L] [Algebra K L]
    (h : Chapter01PurelyInseparableExtension K L)
    (hnontrivial : 1 < Module.finrank K L) :
    ¬ Chapter01FiniteSeparableExtension K L := by
  intro hsep
  let _ : IsPurelyInseparable K L := h.2
  let _ : Algebra.IsSeparable K L := ⟨hsep.2⟩
  have hfin : Field.finSepDegree K L = Module.finrank K L :=
    Field.finSepDegree_eq_finrank_of_isSeparable K L
  have hone := IsPurelyInseparable.finSepDegree_eq_one K L
  have hdegree := hnontrivial
  rw [← hfin, hone] at hdegree
  omega

/-- The finite residue-field hypothesis gives the local-field compactness of
the valuation ring.  The topological instances are the canonical valuation
topology interfaces from the earlier books. -/
theorem chapter01_local_field_integer_ring_compact
    {K : Type*} [Field K] [Valued K ℤᵐ⁰]
    (v : AddValuation K (WithTop ℤ))
    (hlocal : Chapter01LocalField v)
    (hvaluation : Valuation.IsEquiv (Valued.v : Valuation K ℤᵐ⁰) v.toValuation)
    [(Valued.v : Valuation K ℤᵐ⁰).RankOne]
    [CompleteSpace ((Valued.v : Valuation K ℤᵐ⁰).valuationSubring)]
    [IsDiscreteValuationRing ((Valued.v : Valuation K ℤᵐ⁰).valuationSubring)] :
    IsCompact
      (Set.univ : Set ((Valued.v : Valuation K ℤᵐ⁰).valuationSubring)) := by
  have hsub := (Valuation.isEquiv_iff_valuationSubring
    (v₁ := (Valued.v : Valuation K ℤᵐ⁰)) (v₂ := v.toValuation)).mp hvaluation
  let _ : Finite (IsLocalRing.ResidueField
      ((Valued.v : Valuation K ℤᵐ⁰).valuationSubring)) := hsub ▸ hlocal.2
  exact isCompact_univ_iff.mpr
    (LastLib.Book01ValuationsDVRsAndCompletions.Chapter06.chapter06_integer_compact_iff_complete_dvr_finite_residue.mpr
      ⟨inferInstance, inferInstance, inferInstance⟩)

/-- The supplied valuation equivalence and canonical `Valued` topology are the
bridge from compactness of the valuation ring to local compactness of `K`. -/
theorem chapter01_local_field_is_locally_compact
    {K : Type*} [Field K] [Valued K ℤᵐ⁰]
    (v : AddValuation K (WithTop ℤ))
    (hlocal : Chapter01LocalField v)
    (hvaluation : Valuation.IsEquiv (Valued.v : Valuation K ℤᵐ⁰) v.toValuation)
    [(Valued.v : Valuation K ℤᵐ⁰).RankOne]
    [CompleteSpace ((Valued.v : Valuation K ℤᵐ⁰).valuationSubring)]
    [IsDiscreteValuationRing ((Valued.v : Valuation K ℤᵐ⁰).valuationSubring)] :
    LocallyCompactSpace K := by
  sorry

/-- A topological product decomposition with its noncompact valuation
coordinate forces the field-unit group to be noncompact. -/
theorem chapter01_local_field_units_noncompact
    {K : Type*} [Field K]
    (v : AddValuation K (WithTop ℤ))
    (hlocal : Chapter01LocalField v)
    [TopologicalSpace Kˣ] [IsTopologicalGroup Kˣ]
    [TopologicalSpace (Chapter01UnitGroup v)]
    [IsTopologicalGroup (Chapter01UnitGroup v)]
    [NoncompactSpace (Multiplicative ℤ)]
    (hcoordinate :
      Nonempty (Kˣ ≃ₜ* Multiplicative ℤ × Chapter01UnitGroup v)) :
    NoncompactSpace Kˣ := by
  sorry

/-- The unique-extension theorem used to fix the separable closure branch. -/
theorem chapter01_finite_extension_has_unique_valuation
    {K L Γ : Type u} [Field K] [Field L] [Algebra K L]
    [Algebra.IsAlgebraic K L]
    [LinearOrderedCommGroupWithZero Γ]
    (v : Valuation K Γ) [Valuation.IsRankOneDiscrete v]
    (hcomplete : IsAdicComplete
      (IsLocalRing.maximalIdeal v.valuationSubring) v.valuationSubring) :
    LastLib.Book01ValuationsDVRsAndCompletions.Chapter12.hasUniqueValuationExtension v L := by
  sorry

/-- A finite extension of a complete discretely valued field remains complete
and discretely valued on its normalized branch. -/
theorem chapter01_finite_extension_remains_local
    {K L : Type*} [Field K] [Field L] [Algebra K L]
    [FiniteDimensional K L]
    (vK : Valuation K ℤᵐ⁰) (vL : Valuation L ℤᵐ⁰)
    [vK.HasExtension vL] [Valuation.IsRankOneDiscrete vK]
    [Valuation.IsRankOneDiscrete vL]
    (hcomplete : IsAdicComplete
      (IsLocalRing.maximalIdeal vK.valuationSubring) vK.valuationSubring) :
    Module.Finite vK.valuationSubring vL.valuationSubring ∧
      Module.Free vK.valuationSubring vL.valuationSubring ∧
      IsAdicComplete (IsLocalRing.maximalIdeal vL.valuationSubring)
        vL.valuationSubring ∧
      IsDiscreteValuationRing vL.valuationSubring := by
  exact
    LastLib.Book02FiniteExtensionsOfLocalFields.Chapter01.chapter01_finite_extension_remains_local
      vK vL hcomplete

/-- The clean unramified-then-totally-ramified decomposition in a finite
local extension with separable residue extension. -/
theorem chapter01_finite_separable_extension_decomposes
    (A B K L : Type*) [CommRing A] [CommRing B] [Field K] [Field L]
    [Algebra A B] [Algebra A K] [Algebra K L] [Algebra B L] [Algebra A L]
    [IsScalarTower A K L] [IsScalarTower A B L]
    [IsDomain A] [IsDomain B]
    [IsDiscreteValuationRing A] [IsDiscreteValuationRing B]
    [IsLocalHom (algebraMap A B)] [IsFractionRing A K] [IsFractionRing B L]
    [FiniteDimensional K L] [Module.Finite A B] [Module.IsTorsionFree A B]
    [FaithfulSMul A B] [IsIntegralClosure B A L]
    [Module.Finite (LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.chapter09BaseResidueField A)
      (LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.chapter09ExtensionResidueField B)]
    [PerfectField
      (LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.chapter09BaseResidueField A)]
    [LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.Chapter09FiniteLocalExtension
      A B K L]
    (_hfield_separable : Chapter01FiniteSeparableExtension K L)
    (hseparable : Algebra.IsSeparable
      (LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.chapter09BaseResidueField A)
      (LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.chapter09ExtensionResidueField B)) :
    Nonempty
      (LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.Chapter09Corollary92Data
        A B K L) := by
  simpa [LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.chapter09CleanTwoStageDecomposition]
    using
      (LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.chapter09_clean_two_stage_decomposition_iff_residue_separable
        A B K L).mpr hseparable

/-- The unramified stage in the preceding decomposition is explicit. -/
theorem chapter01_decomposition_unramified_stage
    {A B K L : Type*} [CommRing A] [CommRing B] [Field K] [Field L]
    [Algebra A B] [Algebra A K] [Algebra K L] [Algebra B L] [Algebra A L]
    [IsScalarTower A K L] [IsScalarTower A B L]
    [IsDomain A] [IsDomain B]
    [IsDiscreteValuationRing A] [IsDiscreteValuationRing B]
    [IsLocalHom (algebraMap A B)] [IsFractionRing A K] [IsFractionRing B L]
    [FiniteDimensional K L] [Module.Finite A B] [Module.IsTorsionFree A B]
    [FaithfulSMul A B] [IsIntegralClosure B A L]
    [Module.Finite (LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.chapter09BaseResidueField A)
      (LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.chapter09ExtensionResidueField B)]
    [LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.Chapter09FiniteLocalExtension
      A B K L]
    (d : LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.Chapter09Corollary92Data
      A B K L) :
    LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.chapter09UnramifiedIntermediate
      A B K L d.K₀ := by
  exact d.unramified

/-- The remainder in the preceding decomposition is totally ramified. -/
theorem chapter01_decomposition_remainder_totally_ramified
    {A B K L : Type*} [CommRing A] [CommRing B] [Field K] [Field L]
    [Algebra A B] [Algebra A K] [Algebra K L] [Algebra B L] [Algebra A L]
    [IsScalarTower A K L] [IsScalarTower A B L]
    [IsDomain A] [IsDomain B]
    [IsDiscreteValuationRing A] [IsDiscreteValuationRing B]
    [IsLocalHom (algebraMap A B)] [IsFractionRing A K] [IsFractionRing B L]
    [FiniteDimensional K L] [Module.Finite A B] [Module.IsTorsionFree A B]
    [FaithfulSMul A B] [IsIntegralClosure B A L]
    [Module.Finite (LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.chapter09BaseResidueField A)
      (LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.chapter09ExtensionResidueField B)]
    [LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.Chapter09FiniteLocalExtension
      A B K L]
    (d : LastLib.Book02FiniteExtensionsOfLocalFields.Chapter09.Chapter09Corollary92Data
      A B K L) :
    d.remainder.residue_degree = 1 := by
  exact d.remainder_totally_ramified

/-- The fundamental equality in the valuation notation used by this book. -/
theorem chapter01_fundamental_equality
    {K L : Type*} [Field K] [Field L] [Algebra K L]
    (vK : Valuation K ℤᵐ⁰) (vL : Valuation L ℤᵐ⁰)
    [vK.HasExtension vL] [Valuation.IsRankOneDiscrete vK]
    [Valuation.IsRankOneDiscrete vL] [FiniteDimensional K L]
    (hcomplete : IsAdicComplete
      (IsLocalRing.maximalIdeal vK.valuationSubring) vK.valuationSubring) :
    Module.finrank K L =
      LastLib.Book01ValuationsDVRsAndCompletions.Chapter12.chapterRamificationIndex
          vK.valuationSubring vL.valuationSubring
          (IsLocalRing.maximalIdeal vL.valuationSubring) *
        LastLib.Book01ValuationsDVRsAndCompletions.Chapter12.chapterResidueDegree
          vK.valuationSubring vL.valuationSubring
          (IsLocalRing.maximalIdeal vL.valuationSubring) := by
  exact LastLib.Book02FiniteExtensionsOfLocalFields.Chapter02.fundamental_equality
    vK vL hcomplete

/-- The norm valuation identity used throughout local reciprocity. -/
theorem chapter01_norm_valuation_formula
    (K L : Type*) [Field K] [Field L] [Algebra K L]
    [FiniteDimensional K L] {vK : AddValuation K (WithTop ℤ)}
    {vL : AddValuation L (WithTop ℤ)} (e f : ℕ)
    [Valuation.IsRankOneDiscrete vK.toValuation]
    [Valuation.IsRankOneDiscrete vL.toValuation]
    (hext : vK.IsEquiv (AddValuation.comap (algebraMap K L) vL))
    (hrestrict : ∀ y : K,
      vL (algebraMap K L y) = (e : WithTop ℤ) * vK y)
    (hf : f =
      LastLib.Book01ValuationsDVRsAndCompletions.Chapter11.chapter11AdditiveResidueDegree
        vK vL hext)
    (hunique : ∀ w : AddValuation L (WithTop ℤ),
      vK.IsEquiv (AddValuation.comap (algebraMap K L) w) → vL.IsEquiv w)
    (hdegree : Module.finrank K L = e * f) (x : L) (hx : x ≠ 0) :
    vK (Algebra.norm K x) = (f : WithTop ℤ) * vL x := by
  exact LastLib.Book02FiniteExtensionsOfLocalFields.Chapter04.chapter04_norm_valuation_formula
    K L e f hext hrestrict hf hunique hdegree x hx

/-- The unramified-extension classification is imported through its concrete
book-facing intermediate-field interface. -/
abbrev Chapter01UnramifiedClassificationInterface :=
  LastLib.Book02FiniteExtensionsOfLocalFields.Chapter07.Chapter07ActualUnramifiedClassificationInterface

theorem chapter01_unramified_extensions_classified_by_residue_extensions
    {K Ω k κ U S : Type*} [Field K] [Field Ω] [Field k] [Field κ]
    [Algebra K Ω] [Algebra k κ]
    [IsAlgClosed Ω] [Algebra.IsAlgebraic K Ω]
    [IsAlgClosed κ] [Algebra.IsAlgebraic k κ]
    (C : Chapter01UnramifiedClassificationInterface K Ω k κ U S) :
    Nonempty (U ≃ S) ∧
      (∀ u,
        letI : FiniteDimensional K (C.extension u) := C.extension_finite u
        letI : FiniteDimensional k (C.residueExtension (C.reduction u)) :=
          C.residue_finite (C.reduction u)
        Module.finrank K (C.extension u) =
          Module.finrank k (C.residueExtension (C.reduction u))) ∧
      (∀ u,
        letI : FiniteDimensional K (C.extension u) := C.extension_finite u
        letI : FiniteDimensional k (C.residueExtension (C.reduction u)) :=
          C.residue_finite (C.reduction u)
        LastLib.Book02FiniteExtensionsOfLocalFields.Chapter07.Chapter07UnramifiedExtension
          (C.profile u)) := by
  sorry

end

end LastLib.Book05LocalClassFieldTheory.Chapter01
